package RosettaEmit;
#-----------------------------------------------------------------------
#
# Name: RosettaEmit
# Description: deterministic YAML emission for cracking-rosetta's generated
#              tool inventories
#
#-----------------------------------------------------------------------
# METHODOLOGY AND WHY THESE CHOICES
#
# WHY NOT YAML::XS, WHICH IS INSTALLED
#
# Because it emits hash keys in an order Perl chooses, and these files are
# regenerated on every upstream release and then read as a git diff by a human
# reviewing an automated PR. A dump whose key order can move turns a two-line
# change into a whole-file rewrite, and the reviewer stops reading. Key order
# here is passed in explicitly and is the same on every run, so a diff shows
# exactly what upstream changed and nothing else.
#
# The same reasoning rules out sorting keys alphabetically: "mode" and "name"
# should lead a hashcat entry because that is how a person reads it, not
# because of where they fall in the alphabet.
#
# QUOTING IS DELIBERATELY UNSUBTLE
#
# Every string is double-quoted, always, even when YAML would not require it.
# The values here are hashes and example passwords - they contain ':', '#',
# '*', '$', '@', '{', leading '-', leading '0', and backslashes, and several
# of them would otherwise parse as YAML numbers, booleans or nulls. "0e1234"
# is a real MD5-magic example hash and is also a valid YAML float. Rather than
# maintain a predicate for which of those need quoting, quote all of them and
# escape the two characters that matter inside a double-quoted YAML scalar.
#
# Numbers and booleans are the only bare values, and they are opted into by
# the caller: an integer is emitted bare only when the value matches an
# integer exactly, and a boolean only when the caller passes a scalar ref
# (\1 or \0), which nothing else in this data can be confused with.
#
#-----------------------------------------------------------------------
# Generated by Claude Opus 5 on 2026-08-29

use strict;
use warnings;

use Exporter 'import';
use YAML::XS ();
our @EXPORT_OK = qw(yaml_scalar emit_header emit_records emit_entry entry_text);

# yaml_scalar($value) - render one value as a YAML scalar.
#
# undef        -> null
# \1 or \0     -> true / false   (scalar ref; see methodology above)
# /^-?\d+$/    -> bare integer
# anything else-> double-quoted, with \ and " escaped
sub yaml_scalar {
    my ($v) = @_;

    return 'null' unless defined $v;

    # A scalar ref is the caller saying "this is a boolean, not a string".
    if (ref $v eq 'SCALAR') {
        return $$v ? 'true' : 'false';
    }

    # An array ref becomes an inline flow sequence: [0, 2600, 3500]. Inline
    # rather than block style so one record stays one diff hunk, and because
    # these lists are short sets of identifiers, not prose.
    if (ref $v eq 'ARRAY') {
        return '[' . join(', ', map { yaml_scalar($_) } @$v) . ']';
    }

    return $v if $v =~ /^-?[0-9]+$/;

    # Escape backslash first, then the quote - the other order double-escapes.
    (my $s = $v) =~ s/\\/\\\\/g;
    $s =~ s/"/\\"/g;
    # A raw newline inside a double-quoted scalar is legal YAML but FOLDS: the
    # loader gives back a space, so the value that comes out is not the value
    # that went in. hashcat's usage_notice for the caching_sha2_password modes
    # carries an embedded SQL query and is the first field to hit this.
    $s =~ s/\r/\\r/g;
    $s =~ s/\n/\\n/g;
    $s =~ s/\t/\\t/g;
    return qq{"$s"};
}

# emit_header($fh, $lines_arrayref) - the "do not edit" banner.
#
# Written as comments rather than as YAML keys so that the warning survives
# into any tool that parses the file and prints a record back out.
sub emit_header {
    my ($fh, $lines) = @_;
    # A blank line in the banner emits a bare "#", never "# " - trailing
    # whitespace in a committed generated file is noise every linter finds.
    print {$fh} (length($_) ? "# $_\n" : "#\n") for @$lines;
    print {$fh} "#\n";
    return;
}

# emit_records($fh, $key, $records, $order) - emit a top-level list of maps
# under $key, with every map's keys in $order.
#
# A key whose value is undef is omitted entirely rather than emitted as null,
# so an optional field (a salt length on an unsalted mode) is absent rather
# than present-and-empty. Absent is the honest encoding: hashcat did not
# report the field at all.
sub emit_records {
    my ($fh, $key, $records, $order) = @_;

    print {$fh} "$key:\n";

    for my $rec (@$records) {
        my $first = 1;
        for my $k (@$order) {
            next unless exists $rec->{$k} && defined $rec->{$k};
            next if ref $rec->{$k} eq 'ARRAY' && !@{ $rec->{$k} };
            my $lead = $first ? '  - ' : '    ';
            printf {$fh} "%s%s: %s\n", $lead, $k, yaml_scalar($rec->{$k});
            $first = 0;
        }
        # A record with no emittable field at all would silently vanish and
        # break the count in the header; refuse rather than lie.
        die "emit_records: record has no fields in the given key order\n" if $first;
    }

    return;
}

#-----------------------------------------------------------------------
# Curated-entry emission.
#
# WHY THE KEY ORDER LIVES HERE AS DATA
#
# tools/import-sheet.py wrote the first 646 entries and tools/seed-upstream.pl
# now rewrites some of them. If the two disagree about key order by even one
# field, the seed pass reformats every file it touches and the diff stops
# showing what actually changed. So the order is stated once, here, and both
# emitters follow it; seed-upstream.pl self-tests by re-emitting an untouched
# entry and requiring the bytes to match what the importer produced.

my @ENTRY_ORDER = qw(
    id name aliases expression john_dynamic_expr expression_proof denotation
    category application application_version status merged_into
    tools relations vectors legacy notes
);
my @TOOL_ORDER   = qw(hashcat mdxfind john crack);
my %TOOL_KEYS = (
    hashcat => [qw(modes verified verified_at verified_with note)],
    mdxfind => [qw(types iterations verified verified_at verified_with note)],
    john    => [qw(cpu gpu verified verified_at verified_with note)],
    crack   => [qw(supported note)],
);
# Keys whose value is a YAML boolean, addressed as "<tool>.<key>".
#
# YAML::XS loads "true" as 1 and "false" as the empty string, so a boolean
# round-tripped through a loader arrives looking like an integer or like
# nothing at all. Left to the generic path that turned crack.supported: true
# into "supported: 1" and made crack.supported: false disappear entirely --
# and "Crack cannot do this" is exactly the claim docs/CRACK.md is built on.
# So these keys are rendered as booleans, and only an absent value is skipped.
my %BOOL_KEYS = ('crack.supported' => 1);

# form, reads_in and credential come after the vector itself. form says which
# serialization the string is written in and sits beside source: because the
# two are routinely confused -- source is WHERE THE STRING CAME FROM, form is
# WHOSE FORMAT IT IS IN, and reading the first as the second is what once made
# seven entries look like divergent serializations. reads_in is a MEASUREMENT
# of which tools loaded this exact string, credential groups two spellings of
# one credential so they are not counted twice.
my @VECTOR_KEYS   = qw(hash pass salt source form reads_in credential);

# relations: is a list of maps like vectors:, and emitted the same way -- the
# first key of each edge carries the "- " so one edge is one readable stanza.
my @RELATION_KEYS = qw(kind entry distinction note);
# Flat nested maps: one key, a fixed inner key order, no list. legacy: was the
# only one; expression_proof: and denotation: are the same shape and are
# emitted by the same branch rather than three near-identical ones.
#
# expression_proof: is the tier on expression:, in the same vocabulary the
# per-tool blocks use, because it is the same kind of claim -- "was this
# reproduced, by what, when". Without it the field cannot say whether it was
# round-tripped through john's dynamic compiler or transcribed from john's
# own subformat listing, and validate.pl fails a build on it.
#
# denotation: is how people refer to an algorithm that has NO machine-checkable
# expression -- a pseudo-expression in a richer language than john's dynamic
# ('hmac("sha1", $plain, $salt)'), or simply the label a suite uses. It carries
# a source so it is never an unattributed human claim.
my %FLAT_BLOCKS = (
    legacy           => [qw(hashes_org hashkiller)],
    expression_proof => [qw(verified verified_at verified_with note)],
    denotation       => [qw(text source note)],
);

# Skip a value that carries no information: undef, empty string, empty list,
# empty map. Matches the importer, which omits rather than writes null.
sub _empty {
    my ($v) = @_;
    return 1 unless defined $v;
    return 1 if ref $v eq 'ARRAY' && !@$v;
    return 1 if ref $v eq 'HASH'  && !%$v;
    return 1 if !ref $v && $v eq '';
    return 0;
}

# _block_kv($pad, $key, $value) - render "key: |" plus indented content, or
# undef when this value must not be written that way.
#
# WHY A BLOCK AT ALL
#
# yaml_scalar folds a newline to the two characters \n inside a double-quoted
# string, which is correct and unreadable. An entry whose notes: field is a
# multi-paragraph document then arrives in review as one 4000-character line,
# and a one-word edit to it is a whole-file diff -- the exact failure fmt.pl
# was written to prevent, reappearing inside a single field.
#
# WHY IT REFUSES SO MUCH
#
# A block scalar can hand back a DIFFERENT string, and nothing in the file
# looks wrong when it does. Leading indentation on the first line needs an
# explicit indentation indicator; trailing whitespace on any line is preserved
# and invisible; a bare CR is ambiguous with the line break the form
# introduces; more than one trailing newline needs an explicit chomping
# indicator. Each is cheap to test for and expensive to discover later, so the
# rule is to fall back to the quoted form rather than to handle the case.
#
# And then, having tested for all of them, it PARSES WHAT IT IS ABOUT TO
# WRITE and requires the value back byte for byte. That check is what makes
# the refusal list a belt rather than the only guard: a shape nobody thought
# of cannot get through it, it merely stays quoted.
sub _block_kv {
    my ($pad, $key, $v) = @_;

    return undef if ref $v || !defined $v;
    return undef unless $v =~ /\n/;              # single line: nothing to gain
    return undef if $v =~ /\r/;                  # ambiguous with the line break
    return undef if $v =~ /[^\t\n\x20-\x7e]/;    # control or non-ASCII: quote it
    return undef if $v =~ /\A[ \t]/;             # indented first line needs an indicator
    return undef if $v =~ /[ \t]\n/;             # trailing whitespace, including
    return undef if $v =~ /[ \t]\z/;             # a whitespace-only line
    return undef if $v =~ /\n\n\z/;              # two trailing newlines: not worth a case

    # "|" keeps exactly one trailing newline; "|-" keeps none.
    my $chomp = $v =~ /\n\z/ ? '' : '-';

    # text($pad) - the same rendering at any indent, so the probe below can be
    # built at column zero and still be the thing being tested.
    my $text = sub {
        my ($p) = @_;
        my $ind  = ' ' x (length($p) + 2);
        my $body = $v;
        $body .= "\n" unless $body =~ /\n\z/;
        # (?=.) matches only where a character follows, so an empty line stays
        # empty rather than becoming a line of spaces.
        $body =~ s/^(?=.)/$ind/mg;
        return "$p$key: |$chomp\n$body";
    };

    my $probe = eval { YAML::XS::Load($text->('')) };
    return undef unless ref $probe eq 'HASH'
                     && defined $probe->{$key}
                     && $probe->{$key} eq $v;

    return $text->($pad);
}

sub _kv {
    my ($pad, $k, $v) = @_;
    my $block = _block_kv($pad, $k, $v);
    return $block if defined $block;
    return sprintf("%s%s: %s\n", $pad, $k, yaml_scalar($v));
}

# entry_text($entry) - render one curated algorithm entry as YAML text.
sub entry_text {
    my ($e) = @_;
    my $out = '';

    for my $k (@ENTRY_ORDER) {
        next if _empty($e->{$k});
        my $v = $e->{$k};

        if ($k eq 'tools') {
            my @tools = grep { !_empty($v->{$_}) } @TOOL_ORDER;
            next unless @tools;
            $out .= "tools:\n";
            for my $t (@tools) {
                $out .= "  $t:\n";
                for my $tk (@{ $TOOL_KEYS{$t} }) {
                    if ($BOOL_KEYS{"$t.$tk"}) {
                        next unless defined $v->{$t}{$tk};
                        $out .= _kv('    ', $tk, \(!!$v->{$t}{$tk}));
                        next;
                    }
                    next if _empty($v->{$t}{$tk});
                    $out .= _kv('    ', $tk, $v->{$t}{$tk});
                }
            }
        }
        elsif ($k eq 'relations') {
            # Sorted by (kind, entry) so the file is stable no matter what
            # order a tool discovered the edges in.
            $out .= "relations:\n";
            for my $rel (sort { ($a->{kind} // '') cmp ($b->{kind} // '')
                             || ($a->{entry} // '') cmp ($b->{entry} // '') } @$v) {
                my $first = 1;
                for my $rk (@RELATION_KEYS) {
                    next if _empty($rel->{$rk});
                    $out .= _kv($first ? '  - ' : '    ', $rk, $rel->{$rk});
                    $first = 0;
                }
            }
        }
        elsif ($k eq 'vectors') {
            $out .= "vectors:\n";
            for my $vec (@$v) {
                my $first = 1;
                for my $vk (@VECTOR_KEYS) {
                    next if _empty($vec->{$vk});
                    $out .= _kv($first ? '  - ' : '    ', $vk, $vec->{$vk});
                    $first = 0;
                }
            }
        }
        elsif ($FLAT_BLOCKS{$k}) {
            $out .= "$k:\n";
            for my $lk (@{ $FLAT_BLOCKS{$k} }) {
                next if _empty($v->{$lk});
                $out .= _kv('  ', $lk, $v->{$lk});
            }
        }
        else {
            $out .= _kv('', $k, $v);
        }
    }

    return $out;
}

# emit_entry($path, $entry) - write the entry, returning 1 if the file changed.
# Unchanged files are left alone so the seed pass touches only what it altered.
sub emit_entry {
    my ($path, $entry) = @_;
    my $new = entry_text($entry);

    if (-r $path) {
        open my $fh, '<', $path or die "cannot read $path: $!\n";
        local $/;
        my $old = <$fh>;
        close $fh;
        return 0 if defined $old && $old eq $new;
    }

    open my $fh, '>', $path or die "cannot write $path: $!\n";
    print {$fh} $new;
    close $fh;
    return 1;
}

1;
