package RosettaTools;
#-----------------------------------------------------------------------
#
# Name: RosettaTools
# Description: resolve where hashcat, john and mdxfind live, so a clone that
#              is not the machine this repository grew on can run the tools
#
#-----------------------------------------------------------------------
# METHODOLOGY AND WHY THIS EXISTS
#
# Seven scripts each hardcoded a default like
# /usr/local/src/sec/crack/john-latest/run/john. That is honest documentation
# of one machine and useless on any other: a second clone has to pass --john
# on every single invocation or edit seven files. Since the whole point of
# publishing this is that other people run the verifiers, the paths have to be
# settable once.
#
# THE ORDER, AND WHY THE HARDCODED PATH IS STILL IN IT
#
#   1. the explicit --john / --hashcat / --mdxfind flag  (the caller wins)
#   2. $JOHN / $HASHCAT / $MDXFIND from the environment  (the clone's setup)
#   3. the path this repository's data was generated with (unchanged behavior)
#   4. the name on PATH                                  (a packaged install)
#
# Keeping (3) means nothing changes for the machine that has been running
# these all along, so this cannot silently alter which binary produced a tier.
# Keeping (4) last rather than first is deliberate: a distribution john on
# PATH is usually not a jumbo build, and picking it up in preference to a
# known-good local build would be a surprising downgrade.
#
# WHY IT DOES NOT VERIFY THE VERSION, BUT DOES REPORT IT
#
# The version belongs in verified_with:, recorded per mapping by whatever
# established the tier. A resolver that also POLICED versions would be
# deciding what counts as proof, which is the gate's job.
#
# Asking a binary what it is, though, is not policing -- it is the instrument
# naming itself, and every caller needed it. tool_version() was added on
# 2026-09-05 because three discovery tools were taking the version from the
# INVENTORY and stamping it on a round-trip run by the BINARY. That is
# harmless only while the two are the same build, and on that day they were
# not: data/tools/mdxfind.yaml is RCS 1.576 and /usr/local/bin/mdxfind is RCS
# 1.545, so discover-mdxfind.pl would have credited 1.576 with every claim
# 1.545 proved. Given the RAW-family repair the week before -- where WHICH
# mdxfind ran decided whether thirteen mappings were true -- that is not a
# cosmetic difference.
#
#-----------------------------------------------------------------------
# Generated by Claude Opus 5 on 2026-08-30

use strict;
use warnings;

use Exporter 'import';
our @EXPORT_OK = qw(tool_path tool_env_help tool_version
                    share_measurable share_unmeasurable_reason
                    hc_plain_is hc_line_plain_is
                    hashpipe_label);

# The path each tool has had all along on the machine this data was generated
# on. Do not change these to make a different machine work -- set the
# environment variable there instead.
my %DEFAULT = (
    hashcat  => '/usr/local/bin/hashcat',
    mdxfind  => '/usr/local/bin/mdxfind',
    john     => '/usr/local/src/sec/crack/john-latest/run/john',
    # hashpipe was built from source and run out of its working tree until
    # 2026-09-04, when it was installed alongside the others. The old default
    # was one `mv` from breaking and that is not hypothetical: rebuilding
    # from a fresh clone moved the tree to hashpipe.old the same day. An
    # installed path does not move when the tree does.
    hashpipe => '/usr/local/bin/hashpipe',
);
my %ENV_VAR = (hashcat => 'HASHCAT', mdxfind => 'MDXFIND', john => 'JOHN',
               hashpipe => 'HASHPIPE');

# tool_path($name, $explicit) - where to find one of the three tools.
#
# $explicit is whatever the caller's --john/--hashcat/--mdxfind option holds,
# which may be undef; it always wins when set, because a person naming a
# binary on the command line has said something more specific than any
# fallback here.
sub tool_path {
    my ($name, $explicit) = @_;
    die "RosettaTools: unknown tool '$name'\n" unless $DEFAULT{$name};

    return $explicit if defined $explicit && length $explicit;

    my $env = $ENV{ $ENV_VAR{$name} };
    return $env if defined $env && length $env;

    return $DEFAULT{$name} if -x $DEFAULT{$name};

    # Last resort: the bare name, which the shell resolves against PATH. Not
    # checked here -- the caller reports "cannot run X" with its own wording
    # and exit code, and a check here would just duplicate that badly.
    return $name;
}

# tool_version($name, $path) - what that binary says it is, or undef.
#
# Each tool states its identity somewhere different and none of them agree:
# mdxfind and hashpipe print an RCS $Header on STDERR, hashcat prints a bare
# version on stdout, and john only says under --list=build-info run from its
# own directory. Undef means the binary would not say, and the caller must
# then decide what to record -- never a guess.
sub tool_version {
    my ($name, $path) = @_;
    $path = tool_path($name, $path);
    if ($name eq 'mdxfind' || $name eq 'hashpipe') {
        # The banner is on stderr, which is the one stream worth merging: a
        # version line has no twin that a merge could make it look like.
        my $v = `\Q$path\E -V 2>&1 </dev/null`;
        return "RCS $1 ($2)" if $v =~ m{RCS/\Q$name\E\.c,v\s+(\S+)\s+(\S+)};
        return undef;
    }
    if ($name eq 'hashcat') {
        my $v = `\Q$path\E --version 2>/dev/null </dev/null`;
        return $1 if $v =~ /^\s*(v?[\w.+-]+)\s*$/m;
        return undef;
    }
    if ($name eq 'john') {
        # john reads its conf relative to its own directory, so --list=
        # anything must be run from there.
        my ($dir, $base) = ($path, $path);
        $dir  =~ s{/[^/]+$}{};
        $base =~ s{^.*/}{};
        my $v = (length $dir && $dir ne $path)
              ? `cd \Q$dir\E && ./\Q$base\E --list=build-info 2>/dev/null </dev/null`
              : `\Q$path\E --list=build-info 2>/dev/null </dev/null`;
        return $1 if $v =~ /^Version:\s*(.+?)\s*$/m;
        return undef;
    }
    return undef;
}

# tool_env_help($name) - the one line each script's --help prints, so the
# override is discoverable where someone is already looking for it.
sub tool_env_help {
    my ($name) = @_;
    return sprintf('$%s, else %s', $ENV_VAR{$name}, $DEFAULT{$name});
}


#-----------------------------------------------------------------------
# THE --max-share GUARD, AND WHEN IT HAS MEASURED NOTHING
#
# All three discovery tools hold back an identifier that matched more than
# --max-share percent of the corpus:
#
#     $hits{$_} * 100 > $max_share * $corpus
#
# The corpus is the TARGET set, so every option that narrows the targets
# narrows the denominator. Under --only it is 1, every format that matched at
# all scores 100%, and the entry is held saying "every matching format is
# over-broad" -- which is not what was measured and reads like a fact about
# the format. Measured 2026-09-05: saph on sapcodvnh256 was held that way, and
# the same run as --format '^saph$' --all measures its true share at 4 of 1561
# and applies.
#
# The guard is right to withhold and wrong to explain. Withholding a claim
# costs coverage; explaining one wrongly writes a sentence into the review
# file that a reader will believe. So neither tool drops the guard on a narrow
# run -- it reports the share as unmeasurable instead.
#
# The predicate is the guard's own arithmetic with hits fixed at 1: if a
# SINGLE hit already trips the threshold, then every identifier that matched
# is over-broad by construction and the comparison has distinguished nothing.
# Deriving it that way rather than testing for --only is deliberate -- it is
# --mirror-gpu and a small --all-less run too, it scales with --max-share, and
# it cannot drift away from the rule it describes.

# share_measurable($corpus, $max_share) - true when a share verdict on this
# corpus says something about the identifier rather than about the run.
sub share_measurable {
    my ($corpus, $max_share) = @_;
    return 0 unless defined $corpus && defined $max_share;
    return 0 if $corpus <= 0 || $max_share <= 0;
    return 100 <= $max_share * $corpus ? 1 : 0;
}

# share_unmeasurable_reason($kind, $corpus, $max_share) - what to say instead.
# $kind is the tool's word for its identifier: format, type, mode.
sub share_unmeasurable_reason {
    my ($kind, $corpus, $max_share) = @_;
    return sprintf(
        'share UNMEASURABLE: the corpus is %d %s, so a single hit is %s%% and '
      . 'trips --max-share %d by itself. Every matching %s is held, which is a '
      . 'fact about this run and not about the %s -- re-run against the whole '
      . 'corpus (--all, without --only) to measure the share',
        $corpus, ($corpus == 1 ? 'entry' : 'entries'),
        ($corpus > 0 ? sprintf('%g', 100 / $corpus) : '100'),
        $max_share, $kind, $kind);
}


#-----------------------------------------------------------------------
# READING HASHCAT'S CRACK LINE
#
# These live here rather than in the one script that calls them because the
# second one was WRONG once and nothing could have caught it: a wrong answer
# understates hashcat's support, which looks exactly like a mode that does not
# crack. A pure function in a module can be asserted without a GPU.

# hc_plain_is($said, $want) - is the plaintext hashcat printed the plaintext
# the vector records?
#
# The two do not always spell it the same way. hashcat writes a non-printable
# password as $HEX[<hex>], and a vector may store either spelling: mode 9710's
# vector here is "$HEX[91b2e062b9]" and hashcat's crack line ends
# ":91b2e062b9". Both are the same five bytes. So one $HEX wrapper on either
# side is unwrapped and nothing else is: a comparison that normalized harder
# than that would start accepting different plaintexts.
sub hc_plain_is {
    my ($said, $want) = @_;
    return 0 unless defined $said && defined $want;
    return 1 if $said eq $want;
    for my $p ([$said, $want], [$want, $said]) {
        my ($a, $b) = @$p;
        next unless $a =~ /^\$HEX\[([0-9a-fA-F]*)\]$/;
        return 1 if lc($1) eq lc($b);              # the inner hex, as text
        return 1 if pack('H*', $1) eq $b;          # the inner hex, as bytes
    }
    return 0;
}

# hc_line_plain_is($line, $want) - does this whole crack line end in $want as a
# colon-delimited FIELD?
#
# Only for a SOLO run, where the file held one hash and the wordlist one
# candidate, so the line can only be about them and the hash's spelling stops
# mattering. A grouped run must keep matching the hash string exactly, because
# its output lines do not correspond to its input lines.
#
# Match from the END, never on the first colon: hashcat's re-serialization puts
# colons in the hash half. Measured 2026-09-05 on v7.1.2-549-g8a15e210b,
# -m 22000 is handed
#   WPA*01*<pmkid>*<mac>*<mac>*<hex essid>***
# and prints
#   <pmkid>:<mac>:<mac>:<essid>:<plain>
# -- different separators and the essid hex-decoded to text. Splitting on the
# first colon read the plaintext as "<mac>:<mac>:<essid>:hashcat!" and the
# round trip was recorded as a failure.
#
# The tail widens one field at a time so a plaintext containing a colon still
# matches, and at least one field must remain ahead of it: a line that is
# nothing but the candidate echoed back is not a crack.
sub hc_line_plain_is {
    my ($line, $want) = @_;
    return 0 unless defined $line && defined $want;
    my @f = split /:/, $line, -1;
    for my $k (1 .. $#f) {
        return 1 if hc_plain_is(join(':', @f[ @f - $k .. $#f ]), $want);
    }
    return 0;
}


# hashpipe_label($type, $iterations) - how to NAME a type to `hashpipe -c`.
#
# TWELVE mdxfind/hashpipe type names END IN A BARE `x`, and hashpipe resolves
# a bare one to the WRONG TYPE. Measured 2026-09-16 against RCS 1.194:
#
#     echo "MD5SHA1x    <digest>:password123" | hashpipe -c
#          ->  MD5SHA1x01   ... which is type MD5SHA1 (e178) at depth 1
#     echo "MD5SHA1xx01 <digest>:password123" | hashpipe -c
#          ->  MD5SHA1xx01  ... which is type MD5SHA1x (e702) at depth 1
#
# Both names are real types. hashpipe emits `<name>x%02d` when the depth is
# non-zero (hashpipe.c around line 30225), so the ECHO distinguishes them
# perfectly -- it is the INPUT parse that takes the trailing `x` for a suffix
# marker and hands back a different type. 11 of the 12 answer as the shorter
# type and one is refused outright.
#
# So a trailing-`x` type is always named with an explicit depth. That is not a
# workaround for our matchers: they were already right, and refused the wrong
# type's echo, which is why this cost coverage and never correctness. What was
# wrong was the question.
#
# The depth defaults to 1 because that is what a bare label means for every
# other type. A caller that knows the entry's iteration count should pass it;
# a type whose first emitted value is deeper will be refused rather than
# searched for, because trying depths until one passes is the re-casing
# pitfall in another costume.
sub hashpipe_label {
    my ($type, $iter) = @_;
    return $type unless defined $type && $type =~ /x\z/;
    return sprintf('%sx%02d', $type, ($iter && $iter > 0) ? $iter : 1);
}

1;
