package RosettaExpr;
#-----------------------------------------------------------------------
#
# Name: RosettaExpr
# Description: compile an entry's expression: into a Perl sub, for the
#              constructions this host can compute directly
#
#-----------------------------------------------------------------------
# METHODOLOGY AND WHY THIS EXISTS
#
# Two tools need to compute an entry's construction without asking a cracker.
# vanity.pl searches for a salt that makes a digest start 'dec0ded', which is
# hundreds of millions of evaluations and cannot shell out. triage-expressions
# needs a control vector it computed itself, so that "john's compiler will not
# reproduce this" can be separated from "nobody knows what this computes".
#
# It was vanity.pl's private parser first. It moved here the moment there was
# a second caller, because two implementations of "what does this expression
# mean" is exactly the drift this repository exists to prevent: the day they
# disagree, one of them is silently wrong about an entry.
#
# THE VOCABULARY IS SMALL ON PURPOSE
#
# md5, sha1, sha256, sha512 -- the four Digest:: gives us directly, and the
# fast ones, which vanity.pl's method depends on. Everything else BAILS: an
# unknown function returns undef rather than being skipped, because skipping
# a token silently changes the meaning of the expression. cap(md5($p)) with
# cap() dropped is md5($p), which is a different algorithm that happens to
# agree on lowercase digests -- the exact trap md5cap records.
#
# WHY IT EMITS PERL SOURCE RATHER THAN NESTED CLOSURES
#
# Speed, measured: a closure chain ran 1.8x slower than the flat expression
# (0.88 vs 1.55 MH/s on this host), and vanity.pl evaluates 2.7e8 candidates
# for one seven-character marker. Nothing from an entry file reaches the eval
# except the SHAPE: function names are looked up in %HASH and never
# interpolated, and a token outside the grammar bails before any source is
# built.
#
#-----------------------------------------------------------------------
# Generated by Claude Opus 5 on 2026-08-30

use strict;
use warnings;

use Digest::MD5 qw(md5_hex);
use Digest::SHA qw(sha1_hex sha256_hex sha512_hex);

use Exporter 'import';
our @EXPORT_OK = qw(compile_expression expr_functions);

our %HASH = (
    md5    => \&md5_hex,
    sha1   => \&sha1_hex,
    sha256 => \&sha256_hex,
    sha512 => \&sha512_hex,
);

sub expr_functions { return sort keys %HASH }

sub _tokenize {
    my ($e) = @_;
    my @t;
    while (length $e) {
        $e =~ s/^\s+// and next;
        if ($e =~ s/^([A-Za-z][A-Za-z0-9_]*)//) { push @t, [ name => $1 ]; next }
        if ($e =~ s/^\$([ps])//)                { push @t, [ var  => $1 ]; next }
        if ($e =~ s/^([().])//)                 { push @t, [ punc => $1 ]; next }
        return;                                  # a token we do not know: bail
    }
    return \@t;
}

# _parse_concat / _parse_term - return a fragment of PERL SOURCE, or undef.
# $pos is an index into the token list, advanced in place.
sub _parse_concat {
    my ($t, $pos) = @_;
    my $left = _parse_term($t, $pos) or return;
    while ($pos->[0] < @$t
        && $t->[ $pos->[0] ][0] eq 'punc' && $t->[ $pos->[0] ][1] eq '.') {
        $pos->[0]++;
        my $right = _parse_term($t, $pos) or return;
        $left = "$left . $right";
    }
    return $left;
}

sub _parse_term {
    my ($t, $pos) = @_;
    return unless $pos->[0] < @$t;
    my ($kind, $val) = @{ $t->[ $pos->[0] ] };

    if ($kind eq 'var') {
        $pos->[0]++;
        return $val eq 'p' ? '$_[0]' : '$_[1]';
    }
    if ($kind eq 'name') {
        my $name = lc $val;
        return unless $HASH{$name};              # unknown function: bail
        $pos->[0]++;
        return unless $pos->[0] < @$t
                   && $t->[ $pos->[0] ][0] eq 'punc' && $t->[ $pos->[0] ][1] eq '(';
        $pos->[0]++;
        my $inner = _parse_concat($t, $pos) or return;
        return unless $pos->[0] < @$t
                   && $t->[ $pos->[0] ][0] eq 'punc' && $t->[ $pos->[0] ][1] eq ')';
        $pos->[0]++;
        # $RosettaExpr::HASH{...} resolves at eval time against this package.
        return "\$RosettaExpr::HASH{'$name'}->($inner)";
    }
    return;
}

# compile_expression($expression) - a sub($pass, $salt) returning the hex
# digest, or undef if any part of the expression is outside the vocabulary.
sub compile_expression {
    my ($expr) = @_;
    return unless defined $expr && length $expr;
    my $t = _tokenize($expr) or return;
    my $pos = [0];
    my $body = _parse_concat($t, $pos) or return;
    return unless $pos->[0] == @$t;              # trailing junk: bail
    return scalar eval "sub { $body }";
}

1;
