package RosettaExpr;
#-----------------------------------------------------------------------
#
# Name: RosettaExpr
# Description: compile an entry's expression: into a Perl sub, for the
#              constructions this host can compute directly
#
#-----------------------------------------------------------------------
# METHODOLOGY AND WHY THIS EXISTS
#
# Two tools need to compute an entry's construction without asking a cracker.
# vanity.pl searches for a salt that makes a digest start 'dec0ded', which is
# hundreds of millions of evaluations and cannot shell out. triage-expressions
# needs a control vector it computed itself, so that "john's compiler will not
# reproduce this" can be separated from "nobody knows what this computes".
#
# It was vanity.pl's private parser first. It moved here the moment there was
# a second caller, because two implementations of "what does this expression
# mean" is exactly the drift this repository exists to prevent: the day they
# disagree, one of them is silently wrong about an entry.
#
# THE VOCABULARY IS STILL SMALL, AND STILL BAILS
#
# It began as md5/sha1/sha256/sha512 over hex strings, and that was the whole
# language. On 2026-09-02 the measurement that widened it: of the 181 entries
# whose expression sits at tier `upstream`, 143 carried triage's verdict
# [no-john-format] -- "no john format, and RosettaExpr cannot compile this
# either, so nothing here can check it". Every one of those 143 was the SAME
# branch. They were not unanswerable questions about the data; they were this
# module's four-function vocabulary, reported as if it were a fact about the
# entries. curate.pl suppresses a human question on that verdict, so the
# boundary of this file was silently deciding what nobody would ever be asked.
#
# What was added is exactly what those 143 needed and nothing else: raw
# (binary) digest output, and the representation and slicing operators --
# cut, pad, trunc, upper, lower, cap, rev, hex, base64, fromhex, frombase64.
#
# The bail rule is UNCHANGED and is what keeps the widening safe: an unknown
# function, a wrong arity, a token outside the grammar, all return undef
# rather than being skipped. Skipping a token silently changes the meaning of
# the expression -- cap(md5($p)) with cap() dropped is md5($p), a different
# algorithm that happens to agree on every digest whose first letter is
# already upper case, which is the exact trap md5cap records.
#
# THE SEMANTICS ARE UPSTREAM'S, MEASURED, NOT INFERRED
#
# Every operator below matches mdxfind's own hx engine, checked by building
# its standalone evaluator from the source tree CLAUDE.md names as the highest
# authority and running both over the same inputs. tools/test-rosetta-expr.pl
# carries the fixture and re-measures it with --oracle. Two that a careful
# reading would still have got wrong, and which the oracle settled:
#
#   cap()  capitalises the first lower-case LETTER, not the first character.
#          cap('975790dfb...') moves the 'd' at index 6.
#   pad()  TRUNCATES when the input is already longer than the width; it is
#          "make it exactly this many bytes", not "at least".
#
# THE VALUE MODEL IS BYTES
#
# It had to become bytes to add _raw at all: base64(sha1_raw($p)) is base64 of
# 20 bytes, and base64 of the 40-character hex string is a different value
# that also looks plausible. Hashes emit lower-case hex by default and raw
# bytes under _raw (hx spells that suffix _bin; this repository spells it
# _raw, and RosettaHx translates -- both are accepted here). Nothing decodes
# or re-encodes text, so non-ASCII bytes pass through untouched.
#
# WHY IT EMITS PERL SOURCE RATHER THAN NESTED CLOSURES
#
# Speed, measured: a closure chain ran 1.8x slower than the flat expression
# (0.88 vs 1.55 MH/s on this host), and vanity.pl evaluates 2.7e8 candidates
# for one seven-character marker. Nothing from an entry file reaches the eval
# except the SHAPE: function names are looked up in %HASH/%RAW/%OP and never
# interpolated, integer arguments are emitted only after matching /^-?\d+$/,
# and a token outside the grammar bails before any source is built.
#
#-----------------------------------------------------------------------
# Generated by Claude Opus 5 on 2026-08-30

use strict;
use warnings;

use Digest::MD5 qw(md5 md5_hex);
use Digest::SHA qw(sha1 sha1_hex sha256 sha256_hex sha512 sha512_hex);
use MIME::Base64 qw(encode_base64);

use Exporter 'import';
our @EXPORT_OK = qw(compile_expression expr_functions);

# Hex-emitting form: the default role for every hash in hx.
our %HASH = (
    md5    => \&md5_hex,
    sha1   => \&sha1_hex,
    sha256 => \&sha256_hex,
    sha512 => \&sha512_hex,
);

# Raw-emitting form, reached by the _raw (or hx's _bin) suffix.
our %RAW = (
    md5    => \&md5,
    sha1   => \&sha1,
    sha256 => \&sha256,
    sha512 => \&sha512,
);

#-----------------------------------------------------------------------
# The representation and slicing operators, each a transcription of the
# matching fn_* in mdxfind's hx_func.c. Kept as named subs rather than
# inlined source so the emitted expression stays a flat chain of calls.
#-----------------------------------------------------------------------

# fn_upper / fn_lower use toupper/tolower under the C locale, so ASCII only.
# tr/// rather than uc()/lc() because those can touch bytes above 0x7f.
sub _upper { my $x = $_[0]; $x =~ tr/a-z/A-Z/; return $x }
sub _lower { my $x = $_[0]; $x =~ tr/A-Z/a-z/; return $x }

sub _rev { return scalar reverse $_[0] }

# fn_hex: bytes to lower-case hex.
sub _hex { return unpack('H*', $_[0]) }

# fn_cap: with no position, upper-case the FIRST byte in a-z and stop. With a
# position, only that byte, and only if it is in a-z; a negative position
# counts back from the end. Anything else is left exactly as it was.
sub _cap {
    my ($x, $pos) = @_;
    if (defined $pos) {
        $pos += length($x) if $pos < 0;
        return $x if $pos < 0 || $pos >= length $x;
        my $c = substr($x, $pos, 1);
        substr($x, $pos, 1) = uc $c if $c ge 'a' && $c le 'z';
        return $x;
    }
    # \G[^a-z]* anchors the scan at the string start, so this replaces the
    # first a-z byte and nothing later.
    $x =~ s/\G([^a-z]*)([a-z])/$1 . uc($2)/e;
    return $x;
}

# fn_cut: start defaults to 0, a negative start counts back from the end and
# clamps at 0, a start past the end yields the empty string, and a length
# past the end is clamped rather than being an error.
sub _cut {
    my ($x, $start, $len) = @_;
    my $inlen = length $x;
    $start = 0 unless defined $start;
    if ($start < 0) { $start += $inlen; $start = 0 if $start < 0 }
    $start = $inlen if $start > $inlen;
    if (defined $len) { $len = 0 if $len < 0 }
    else              { $len = $inlen - $start }
    $len = $inlen - $start if $start + $len > $inlen;
    return substr($x, $start, $len);
}

# fn_trunc: cut from zero.
sub _trunc { return _cut($_[0], 0, $_[1]) }

# fn_pad: NUL-pad to exactly this width, or truncate to it. hx clamps the
# width to [0, 65536].
sub _pad {
    my ($x, $n) = @_;
    $n = 0     if $n < 0;
    $n = 65536 if $n > 65536;
    return substr($x, 0, $n) if length($x) >= $n;
    return $x . ("\0" x ($n - length $x));
}

# fn_base64: standard alphabet, padded, no line breaks.
sub _base64 { return encode_base64($_[0], '') }

# fn_frombase64: transcribed rather than handed to MIME::Base64, which
# discards characters outside the alphabet where hx STOPS at the first one.
# They agree on well-formed input and the corpus is well-formed, but the
# difference is exactly the kind that would surface as one entry disagreeing
# for a reason nobody could see.
my %B64 = do {
    my $a = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/';
    map { substr($a, $_, 1) => $_ } 0 .. 63;
};
sub _frombase64 {
    my @in = split //, $_[0];
    my $out = '';
    my $i = 0;
    while ($i + 1 < @in) {
        my $a = $B64{ $in[$i++] };
        my $b = $i < @in ? $B64{ $in[$i++] } : 0;
        my $c = ($i < @in && $in[$i] ne '=') ? $B64{ $in[$i++] } : undef;
        my $d = ($i < @in && $in[$i] ne '=') ? $B64{ $in[$i++] } : undef;
        last if !defined $a || !defined $b;
        $out .= chr((($a << 2) | ($b >> 4)) & 0xff);
        $out .= chr(((($b & 0xf) << 4) | ($c >> 2)) & 0xff) if defined $c;
        $out .= chr(((($c & 0x3) << 6) | $d) & 0xff)        if defined $d;
    }
    return $out;
}

# fn_fromhex: whole pairs only, and a non-hex nibble reads as 0 rather than
# aborting -- which is what hx does, however odd it looks.
sub _fromhex {
    my ($x) = @_;
    my $out = '';
    for my $i (0 .. int(length($x) / 2) - 1) {
        my $pair = substr($x, $i * 2, 2);
        my $hi = index('0123456789abcdef', lc substr($pair, 0, 1));
        my $lo = index('0123456789abcdef', lc substr($pair, 1, 1));
        $hi = 0 if $hi < 0;
        $lo = 0 if $lo < 0;
        $out .= chr(($hi << 4) | $lo);
    }
    return $out;
}

# name => [ sub, min args, max args, { position => 1 } for integer arguments ]
# Argument positions are counted from 1; position 0 is the value operand.
our %OP = (
    upper      => [ \&_upper,      1, 1, {} ],
    lower      => [ \&_lower,      1, 1, {} ],
    rev        => [ \&_rev,        1, 1, {} ],
    hex        => [ \&_hex,        1, 1, {} ],
    base64     => [ \&_base64,     1, 1, {} ],
    frombase64 => [ \&_frombase64, 1, 1, {} ],
    fromhex    => [ \&_fromhex,    1, 1, {} ],
    cap        => [ \&_cap,        1, 2, { 1 => 1 } ],
    cut        => [ \&_cut,        2, 3, { 1 => 1, 2 => 1 } ],
    trunc      => [ \&_trunc,      2, 2, { 1 => 1 } ],
    pad        => [ \&_pad,        2, 2, { 1 => 1 } ],
);

sub expr_functions {
    return sort keys %HASH, (map { ("${_}_raw", "${_}_bin") } keys %HASH),
                 keys %OP;
}

sub _tokenize {
    my ($e) = @_;
    my @t;
    while (length $e) {
        $e =~ s/^\s+// and next;
        # An integer literal, optionally negative: cut()'s start can be < 0.
        if ($e =~ s/^(-?[0-9]+)//)              { push @t, [ int  => $1 ]; next }
        if ($e =~ s/^([A-Za-z][A-Za-z0-9_]*)//) { push @t, [ name => $1 ]; next }
        if ($e =~ s/^\$([ps])(?![A-Za-z0-9_])//){ push @t, [ var  => $1 ]; next }
        if ($e =~ s/^([().,])//)                { push @t, [ punc => $1 ]; next }
        return;                                  # a token we do not know: bail
    }
    return \@t;
}

sub _at {
    my ($t, $pos, $kind, $val) = @_;
    return 0 unless $pos->[0] < @$t;
    return 0 unless $t->[ $pos->[0] ][0] eq $kind;
    return 1 unless defined $val;
    return $t->[ $pos->[0] ][1] eq $val;
}

# _parse_concat / _parse_term - return a fragment of PERL SOURCE, or undef.
# $pos is an index into the token list, advanced in place.
sub _parse_concat {
    my ($t, $pos) = @_;
    my $left = _parse_term($t, $pos);
    return unless defined $left;
    while (_at($t, $pos, punc => '.')) {
        $pos->[0]++;
        my $right = _parse_term($t, $pos);
        return unless defined $right;
        $left = "$left . $right";
    }
    return $left;
}

# The argument list of a call: each argument is either a bare integer literal
# (only where the function declares that position an integer) or a full
# concatenation. Returns the list of source fragments, or undef.
sub _parse_args {
    my ($t, $pos, $ints) = @_;
    my @arg;
    while (1) {
        my $n = scalar @arg;                 # 0 is the value operand
        if ($ints->{$n} && _at($t, $pos, 'int')) {
            push @arg, $t->[ $pos->[0] ][1] + 0;
            $pos->[0]++;
        }
        else {
            my $a = _parse_concat($t, $pos);
            return unless defined $a;
            push @arg, $a;
        }
        last unless _at($t, $pos, punc => ',');
        $pos->[0]++;
    }
    return \@arg;
}

sub _parse_term {
    my ($t, $pos) = @_;
    return unless $pos->[0] < @$t;
    my ($kind, $val) = @{ $t->[ $pos->[0] ] };

    if ($kind eq 'var') {
        $pos->[0]++;
        return $val eq 'p' ? '$_[0]' : '$_[1]';
    }
    return unless $kind eq 'name';

    my $name = lc $val;
    # A hash, in either output role. hx spells the raw suffix _bin; this
    # repository spells it _raw. Both resolve to the same primitive.
    my ($table, $key);
    if    ($HASH{$name})                            { $table = \%HASH; $key = $name }
    elsif ($name =~ /^(.+)_(?:raw|bin)$/ && $RAW{$1}) { $table = \%RAW;  $key = $1 }

    if ($table) {
        $pos->[0]++;
        return unless _at($t, $pos, punc => '(');
        $pos->[0]++;
        my $inner = _parse_concat($t, $pos);
        return unless defined $inner;
        return unless _at($t, $pos, punc => ')');   # arity is exactly one
        $pos->[0]++;
        my $which = $table == \%HASH ? 'HASH' : 'RAW';
        return "\$RosettaExpr::${which}{'$key'}->($inner)";
    }

    my $op = $OP{$name} or return;                  # unknown function: bail
    my (undef, $min, $max, $ints) = @$op;
    $pos->[0]++;
    return unless _at($t, $pos, punc => '(');
    $pos->[0]++;
    my $arg = _parse_args($t, $pos, $ints);
    return unless defined $arg;
    return unless _at($t, $pos, punc => ')');
    $pos->[0]++;
    return if @$arg < $min || @$arg > $max;
    # Integer arguments are emitted as literals, so re-check the shape: only
    # a value that came from an 'int' token can reach here, and it has to
    # look like one before it is written into source.
    for my $n (keys %$ints) {
        next unless $n < @$arg;
        return unless $arg->[$n] =~ /^-?[0-9]+$/;
    }
    return "\$RosettaExpr::OP{'$name'}[0]->(" . join(', ', @$arg) . ')';
}

# compile_expression($expression) - a sub($pass, $salt) returning the value
# the expression denotes (lower-case hex for a plain hash, but base64 or raw
# bytes where the expression says so), or undef if any part of the expression
# is outside the vocabulary.
sub compile_expression {
    my ($expr) = @_;
    return unless defined $expr && length $expr;
    my $t = _tokenize($expr) or return;
    return unless @$t;
    my $pos = [0];
    my $body = _parse_concat($t, $pos);
    return unless defined $body;
    return unless $pos->[0] == @$t;              # trailing junk: bail
    return scalar eval "sub { $body }";
}

1;
