package RosettaTools;
#-----------------------------------------------------------------------
#
# Name: RosettaTools
# Description: resolve where hashcat, john and mdxfind live, so a clone that
#              is not the machine this repository grew on can run the tools
#
#-----------------------------------------------------------------------
# METHODOLOGY AND WHY THIS EXISTS
#
# Seven scripts each hardcoded a default like
# /usr/local/src/sec/crack/john-latest/run/john. That is honest documentation
# of one machine and useless on any other: a second clone has to pass --john
# on every single invocation or edit seven files. Since the whole point of
# publishing this is that other people run the verifiers, the paths have to be
# settable once.
#
# THE ORDER, AND WHY THE HARDCODED PATH IS STILL IN IT
#
#   1. the explicit --john / --hashcat / --mdxfind flag  (the caller wins)
#   2. $JOHN / $HASHCAT / $MDXFIND from the environment  (the clone's setup)
#   3. the path this repository's data was generated with (unchanged behaviour)
#   4. the name on PATH                                  (a packaged install)
#
# Keeping (3) means nothing changes for the machine that has been running
# these all along, so this cannot silently alter which binary produced a tier.
# Keeping (4) last rather than first is deliberate: a distribution john on
# PATH is usually not a jumbo build, and picking it up in preference to a
# known-good local build would be a surprising downgrade.
#
# WHY IT DOES NOT VERIFY THE VERSION
#
# The version belongs in verified_with:, recorded per mapping by whatever
# established the tier. A resolver that also policed versions would be
# deciding what counts as proof, which is the gate's job.
#
#-----------------------------------------------------------------------
# Generated by Claude Opus 5 on 2026-08-30

use strict;
use warnings;

use Exporter 'import';
our @EXPORT_OK = qw(tool_path tool_env_help);

# The path each tool has had all along on the machine this data was generated
# on. Do not change these to make a different machine work -- set the
# environment variable there instead.
my %DEFAULT = (
    hashcat => '/usr/local/bin/hashcat',
    mdxfind => '/usr/local/bin/mdxfind',
    john    => '/usr/local/src/sec/crack/john-latest/run/john',
);
my %ENV_VAR = (hashcat => 'HASHCAT', mdxfind => 'MDXFIND', john => 'JOHN');

# tool_path($name, $explicit) - where to find one of the three tools.
#
# $explicit is whatever the caller's --john/--hashcat/--mdxfind option holds,
# which may be undef; it always wins when set, because a person naming a
# binary on the command line has said something more specific than any
# fallback here.
sub tool_path {
    my ($name, $explicit) = @_;
    die "RosettaTools: unknown tool '$name'\n" unless $DEFAULT{$name};

    return $explicit if defined $explicit && length $explicit;

    my $env = $ENV{ $ENV_VAR{$name} };
    return $env if defined $env && length $env;

    return $DEFAULT{$name} if -x $DEFAULT{$name};

    # Last resort: the bare name, which the shell resolves against PATH. Not
    # checked here -- the caller reports "cannot run X" with its own wording
    # and exit code, and a check here would just duplicate that badly.
    return $name;
}

# tool_env_help($name) - the one line each script's --help prints, so the
# override is discoverable where someone is already looking for it.
sub tool_env_help {
    my ($name) = @_;
    return sprintf('$%s, else %s', $ENV_VAR{$name}, $DEFAULT{$name});
}

1;
