package RosettaJohn;
#-----------------------------------------------------------------------
#
# Name: RosettaJohn
# Description: rewrite this repository's hx-style expression: into the
#              notation john's dynamic expression compiler actually parses
#
#-----------------------------------------------------------------------
# METHODOLOGY AND WHY THIS EXISTS
#
# expression: is documented as hx-style, and hx spells a representation
# change as a wrapper: upper(md5($p)), base64(md5_bin($p)). John spells the
# same three things as FLAVOURS OF THE HASH FUNCTION ITSELF -- doc/DYNAMIC_
# EXPRESSIONS, "The hashing functions come in multiple 'flavors'":
#
#     md5(...)      lower-case base16      hx  lower(md5(...))  / md5(...)
#     MD5(...)      upper-case base16      hx  upper(md5(...))
#     md5_raw(...)  the raw digest bytes   hx  md5_bin(...)
#     md5_64(...)   mime base64            hx  base64(md5_bin(...))
#
# and its only free-standing modifiers are lc()/uc(), legal on $p and $u
# alone. So an entry can carry a perfectly correct expression that john
# refuses outright: md5(upper(md5($p))) is a syntax error, md5(MD5($p))
# compiles and cracks that entry's own vector. Measured 2026-09-02 on
# md5-strtoupper-md5-pass.
#
# That is worth a module rather than a private helper because the two strings
# are ONE claim written twice, and the fields are already separate: the hx
# form stays in expression:, the john form is what john_dynamic_expr: means.
# Two private translations would eventually disagree, and then a reader could
# not tell which of an entry's two strings was the one that was proven.
#
# THE TRANSLATION IS EXACT OR IT IS REFUSED
#
# Same rule as RosettaHx: a token outside the table is not dropped, it kills
# the candidate. Dropping a modifier is how a wrong expression proves itself
# -- cap() on a lowercase digest and lower() on a hex string are both no-ops
# on SOME inputs, so john would happily crack the vector and the entry would
# record a construction nobody computes. Refusal costs coverage; a silent drop
# costs correctness, and this repository trades the first for the second.
#
# Three rewrites are exact and are the whole of what this does:
#
#   upper(F(x))   -> F_UPPERCASED(x)   john's upper-case flavour
#   lower(F(x))   -> F(x)              john's default flavour IS lower-case
#   hex(F_raw(x)) -> F(x)              base16 of the raw digest IS the default
#   base64(F_raw(x)) -> F_64(x)        john's mime-base64 flavour
#   upper($p|$u)  -> uc($p|$u)         and lower(...) -> lc(...)
#
# One more is exact but is spelled as a fixed-length token:
#
#   pad($p,100)   -> pad100($p)       and pad16 / pad20, on $p and nothing else
#
# Everything else hx can write -- cut(), rev(), cap(), frombase64(), base64()
# of a hex STRING, upper() of a concatenation -- has no john spelling at all,
# so the whole expression is refused. John is still the oracle: a translation
# that survives here is handed to john and either recovers the entry's own
# plaintext or does not.
#
# THE BOUNDARY COMES FROM JOHN'S LEXER, NOT FROM ITS DOCUMENTATION
#
# doc/DYNAMIC_EXPRESSIONS names only lc() and uc(). The lexer in
# src/dynamic_compiler.c (comp_get_symbol, the block after LARGE_HASH_EDIT_
# POINT) has four more: pad16($p), pad20($p), pad100($p), utf16() and
# utf16be(). Measured 2026-09-02: trusting the doc refused 19 radmin2 entries
# and 13 utf16 ones on the first pass here, while 46 entries in this corpus
# ALREADY carried a proven john_dynamic_expr containing utf16(). The doc was
# demonstrably not the boundary. Read the lexer.
#
# Not every token the lexer accepts works in this build: pad16($p) compiles
# and then dies with "unknown flag: Flag=MGF_KEYS_INPUT_pad16" (measured
# 2026-09-02). It is emitted anyway rather than special-cased, because john is
# the oracle and a build-specific defect is not a fact about the notation.
#
#-----------------------------------------------------------------------
# Generated by Claude Opus 5 on 2026-09-02

use strict;
use warnings;
use Exporter qw(import);

our @EXPORT_OK = qw(hx_to_john);

# Modifiers hx writes as wrappers. Anything here is handled by _wrap() or the
# expression is refused; nothing here may ever fall through to _call().
my %MODIFIER = map { $_ => 1 } qw(upper lower hex base64);

# Modifiers with no john spelling whatsoever. Listed rather than left to the
# default so that adding a token to RosettaHx's %FUNC cannot silently start
# emitting it into a john command.
my %NO_JOHN = map { $_ => 1 } qw(cut rev cap frombase64 utf16le);

# hx writes a padding length as an argument; john writes it into the token
# name, on $p alone. Only these three lengths exist.
my %PAD = map { $_ => 1 } qw(16 20 100);

#-----------------------------------------------------------------------
# Tokeniser. The grammar is the same shape RosettaExpr parses, plus the
# variables john adds ($u, $s2, $c1..$c8) and the ",cN=..." constants trailer,
# which is DATA rather than expression and is carried across untouched.

sub _tokenize {
    my ($e) = @_;
    my @t;
    while (length $e) {
        $e =~ s/^\s+// and next;
        if ($e =~ s/^([A-Za-z][A-Za-z0-9_]*)//) { push @t, [ name => $1 ]; next }
        if ($e =~ s/^(\$(?:s2|[psu]|c[1-8]))//)  { push @t, [ var  => $1 ]; next }
        if ($e =~ s/^([0-9]+)//)                { push @t, [ num  => $1 ]; next }
        if ($e =~ s/^([().,])//)                { push @t, [ punc => $1 ]; next }
        return;                                  # a token we do not know: bail
    }
    return \@t;
}

# _concat / _term - return a fragment of JOHN source, or undef. $pos is an
# index into the token list, advanced in place.
sub _concat {
    my ($t, $pos) = @_;
    my $left = _term($t, $pos);
    return unless defined $left;
    while ($pos->[0] < @$t
        && $t->[ $pos->[0] ][0] eq 'punc' && $t->[ $pos->[0] ][1] eq '.') {
        $pos->[0]++;
        my $right = _term($t, $pos);
        return unless defined $right;
        $left = "$left.$right";
    }
    return $left;
}

# Parse one function call and hand back the function name plus the token span
# of its argument, so _wrap() can look INSIDE it. Returns nothing on anything
# that is not a call.
sub _call_head {
    my ($t, $pos) = @_;
    return unless $pos->[0] + 1 < @$t;
    return unless $t->[ $pos->[0] ][0] eq 'name';
    return unless $t->[ $pos->[0] + 1 ][0] eq 'punc'
               && $t->[ $pos->[0] + 1 ][1] eq '(';
    return $t->[ $pos->[0] ][1];
}

sub _term {
    my ($t, $pos) = @_;
    return unless $pos->[0] < @$t;
    my ($kind, $val) = @{ $t->[ $pos->[0] ] };

    if ($kind eq 'var') { $pos->[0]++; return $val }
    return unless $kind eq 'name';

    my $fn = lc $val;
    return if $NO_JOHN{$fn};                     # no john spelling: refuse
    my $head = _call_head($t, $pos);
    return unless defined $head;                 # a bare name is not a term

    $pos->[0] += 2;                              # consume NAME and '('
    my $body;
    if ($fn eq 'pad') {
        $body = _pad($t, $pos);
    }
    elsif ($MODIFIER{$fn}) {
        $body = _wrap($fn, $t, $pos);
    }
    else {
        my $inner = _concat($t, $pos);
        return unless defined $inner;
        $body = "$val($inner)";                  # spelling preserved verbatim
    }
    return unless defined $body;
    return unless $pos->[0] < @$t
               && $t->[ $pos->[0] ][0] eq 'punc' && $t->[ $pos->[0] ][1] eq ')';
    $pos->[0]++;
    return $body;
}

# _pad(...) - the argument of pad() has already had its '(' consumed. john
# pads the PASSWORD and only the password, so pad(md5($p),100) is refused
# rather than approximated: the radmin2 family contains both shapes and the
# difference is the whole algorithm.
sub _pad {
    my ($t, $pos) = @_;
    return unless $pos->[0] + 2 < @$t;
    return unless $t->[ $pos->[0] ][0] eq 'var'
               && $t->[ $pos->[0] ][1] eq '$p';
    return unless $t->[ $pos->[0] + 1 ][0] eq 'punc'
               && $t->[ $pos->[0] + 1 ][1] eq ',';
    return unless $t->[ $pos->[0] + 2 ][0] eq 'num';
    my $n = $t->[ $pos->[0] + 2 ][1];
    return unless $PAD{$n};
    $pos->[0] += 3;
    return "pad$n(\$p)";
}

# _wrap($modifier, ...) - the argument of upper/lower/hex/base64 has already
# had its '(' consumed. A modifier is a claim about a SINGLE value, so a
# concatenation inside one is refused rather than distributed: john cannot
# upper-case a concatenation and guessing that it means "upper-case each part"
# would be inventing a reading upstream never stated.
sub _wrap {
    my ($fn, $t, $pos) = @_;

    # upper($p) / lower($u) -- john's only free-standing casing operators.
    if ($pos->[0] < @$t && $t->[ $pos->[0] ][0] eq 'var') {
        my $v = $t->[ $pos->[0] ][1];
        return unless $fn eq 'upper' || $fn eq 'lower';
        return unless $v eq '$p' || $v eq '$u';
        $pos->[0]++;
        return ($fn eq 'upper' ? 'uc' : 'lc') . "($v)";
    }

    my $inner_fn = _call_head($t, $pos);
    return unless defined $inner_fn;             # e.g. upper($s): no spelling
    my $raw = $inner_fn =~ /_raw$/ ? 1 : 0;
    (my $base = $inner_fn) =~ s/_raw$//;

    # Which flavour of the inner function this modifier asks for -- and which
    # combinations mean nothing. base64() of a hex STRING is not john's _64
    # flavour (that is base64 of the raw digest), so it is refused.
    my $flavour;
    if    ($fn eq 'upper'  && !$raw) { $flavour = uc $base }
    elsif ($fn eq 'lower'  && !$raw) { $flavour = $base }
    elsif ($fn eq 'hex'    &&  $raw) { $flavour = $base }
    elsif ($fn eq 'base64' &&  $raw) { $flavour = "${base}_64" }
    else                             { return }

    $pos->[0] += 2;                              # consume the inner NAME, '('
    my $inner = _concat($t, $pos);
    return unless defined $inner;
    return unless $pos->[0] < @$t
               && $t->[ $pos->[0] ][0] eq 'punc' && $t->[ $pos->[0] ][1] eq ')';
    $pos->[0]++;                                 # the inner call's ')'
    return "$flavour($inner)";
}

#-----------------------------------------------------------------------
# hx_to_john($expression) - the john-notation spelling of the same claim, or
# undef where john has no way to say it. Returns the input unchanged when no
# rewrite applies, so a caller can compare the two to see whether the entry
# needs a distinct john_dynamic_expr: at all.

sub hx_to_john {
    my ($expr) = @_;
    return unless defined $expr && length $expr;

    # The ",c1=...,c2=..." trailer is constant DATA, not expression. Split it
    # off before parsing and put it back untouched: escaping inside it (a ':'
    # written \x3a) is john's own and must not be re-interpreted here.
    my ($body, $consts) = ($expr, '');
    if ($body =~ s/(,c[1-8]=.*)\z//s) { $consts = $1 }

    my $t = _tokenize($body) or return;
    my $pos = [0];
    my $out = _concat($t, $pos);
    return unless defined $out;
    return unless $pos->[0] == @$t;              # trailing junk: bail
    return $out . $consts;
}

1;
