package RosettaTools;
#-----------------------------------------------------------------------
#
# Name: RosettaTools
# Description: resolve where hashcat, john and mdxfind live, so a clone that
#              is not the machine this repository grew on can run the tools
#
#-----------------------------------------------------------------------
# METHODOLOGY AND WHY THIS EXISTS
#
# Seven scripts each hardcoded a default like
# /usr/local/src/sec/crack/john-latest/run/john. That is honest documentation
# of one machine and useless on any other: a second clone has to pass --john
# on every single invocation or edit seven files. Since the whole point of
# publishing this is that other people run the verifiers, the paths have to be
# settable once.
#
# THE ORDER, AND WHY THE HARDCODED PATH IS STILL IN IT
#
#   1. the explicit --john / --hashcat / --mdxfind flag  (the caller wins)
#   2. $JOHN / $HASHCAT / $MDXFIND from the environment  (the clone's setup)
#   3. the path this repository's data was generated with (unchanged behavior)
#   4. the name on PATH                                  (a packaged install)
#
# Keeping (3) means nothing changes for the machine that has been running
# these all along, so this cannot silently alter which binary produced a tier.
# Keeping (4) last rather than first is deliberate: a distribution john on
# PATH is usually not a jumbo build, and picking it up in preference to a
# known-good local build would be a surprising downgrade.
#
# WHY IT DOES NOT VERIFY THE VERSION, BUT DOES REPORT IT
#
# The version belongs in verified_with:, recorded per mapping by whatever
# established the tier. A resolver that also POLICED versions would be
# deciding what counts as proof, which is the gate's job.
#
# Asking a binary what it is, though, is not policing -- it is the instrument
# naming itself, and every caller needed it. tool_version() was added on
# 2026-09-05 because three discovery tools were taking the version from the
# INVENTORY and stamping it on a round-trip run by the BINARY. That is
# harmless only while the two are the same build, and on that day they were
# not: data/tools/mdxfind.yaml is RCS 1.576 and /usr/local/bin/mdxfind is RCS
# 1.545, so discover-mdxfind.pl would have credited 1.576 with every claim
# 1.545 proved. Given the RAW-family repair the week before -- where WHICH
# mdxfind ran decided whether thirteen mappings were true -- that is not a
# cosmetic difference.
#
#-----------------------------------------------------------------------
# Generated by Claude Opus 5 on 2026-08-30

use strict;
use warnings;

use Exporter 'import';
our @EXPORT_OK = qw(tool_path tool_env_help tool_version
                    share_measurable share_unmeasurable_reason);

# The path each tool has had all along on the machine this data was generated
# on. Do not change these to make a different machine work -- set the
# environment variable there instead.
my %DEFAULT = (
    hashcat  => '/usr/local/bin/hashcat',
    mdxfind  => '/usr/local/bin/mdxfind',
    john     => '/usr/local/src/sec/crack/john-latest/run/john',
    # hashpipe was built from source and run out of its working tree until
    # 2026-09-04, when it was installed alongside the others. The old default
    # was one `mv` from breaking and that is not hypothetical: rebuilding
    # from a fresh clone moved the tree to hashpipe.old the same day. An
    # installed path does not move when the tree does.
    hashpipe => '/usr/local/bin/hashpipe',
);
my %ENV_VAR = (hashcat => 'HASHCAT', mdxfind => 'MDXFIND', john => 'JOHN',
               hashpipe => 'HASHPIPE');

# tool_path($name, $explicit) - where to find one of the three tools.
#
# $explicit is whatever the caller's --john/--hashcat/--mdxfind option holds,
# which may be undef; it always wins when set, because a person naming a
# binary on the command line has said something more specific than any
# fallback here.
sub tool_path {
    my ($name, $explicit) = @_;
    die "RosettaTools: unknown tool '$name'\n" unless $DEFAULT{$name};

    return $explicit if defined $explicit && length $explicit;

    my $env = $ENV{ $ENV_VAR{$name} };
    return $env if defined $env && length $env;

    return $DEFAULT{$name} if -x $DEFAULT{$name};

    # Last resort: the bare name, which the shell resolves against PATH. Not
    # checked here -- the caller reports "cannot run X" with its own wording
    # and exit code, and a check here would just duplicate that badly.
    return $name;
}

# tool_version($name, $path) - what that binary says it is, or undef.
#
# Each tool states its identity somewhere different and none of them agree:
# mdxfind and hashpipe print an RCS $Header on STDERR, hashcat prints a bare
# version on stdout, and john only says under --list=build-info run from its
# own directory. Undef means the binary would not say, and the caller must
# then decide what to record -- never a guess.
sub tool_version {
    my ($name, $path) = @_;
    $path = tool_path($name, $path);
    if ($name eq 'mdxfind' || $name eq 'hashpipe') {
        # The banner is on stderr, which is the one stream worth merging: a
        # version line has no twin that a merge could make it look like.
        my $v = `\Q$path\E -V 2>&1 </dev/null`;
        return "RCS $1 ($2)" if $v =~ m{RCS/\Q$name\E\.c,v\s+(\S+)\s+(\S+)};
        return undef;
    }
    if ($name eq 'hashcat') {
        my $v = `\Q$path\E --version 2>/dev/null </dev/null`;
        return $1 if $v =~ /^\s*(v?[\w.+-]+)\s*$/m;
        return undef;
    }
    if ($name eq 'john') {
        # john reads its conf relative to its own directory, so --list=
        # anything must be run from there.
        my ($dir, $base) = ($path, $path);
        $dir  =~ s{/[^/]+$}{};
        $base =~ s{^.*/}{};
        my $v = (length $dir && $dir ne $path)
              ? `cd \Q$dir\E && ./\Q$base\E --list=build-info 2>/dev/null </dev/null`
              : `\Q$path\E --list=build-info 2>/dev/null </dev/null`;
        return $1 if $v =~ /^Version:\s*(.+?)\s*$/m;
        return undef;
    }
    return undef;
}

# tool_env_help($name) - the one line each script's --help prints, so the
# override is discoverable where someone is already looking for it.
sub tool_env_help {
    my ($name) = @_;
    return sprintf('$%s, else %s', $ENV_VAR{$name}, $DEFAULT{$name});
}


#-----------------------------------------------------------------------
# THE --max-share GUARD, AND WHEN IT HAS MEASURED NOTHING
#
# All three discovery tools hold back an identifier that matched more than
# --max-share percent of the corpus:
#
#     $hits{$_} * 100 > $max_share * $corpus
#
# The corpus is the TARGET set, so every option that narrows the targets
# narrows the denominator. Under --only it is 1, every format that matched at
# all scores 100%, and the entry is held saying "every matching format is
# over-broad" -- which is not what was measured and reads like a fact about
# the format. Measured 2026-09-05: saph on sapcodvnh256 was held that way, and
# the same run as --format '^saph$' --all measures its true share at 4 of 1561
# and applies.
#
# The guard is right to withhold and wrong to explain. Withholding a claim
# costs coverage; explaining one wrongly writes a sentence into the review
# file that a reader will believe. So neither tool drops the guard on a narrow
# run -- it reports the share as unmeasurable instead.
#
# The predicate is the guard's own arithmetic with hits fixed at 1: if a
# SINGLE hit already trips the threshold, then every identifier that matched
# is over-broad by construction and the comparison has distinguished nothing.
# Deriving it that way rather than testing for --only is deliberate -- it is
# --mirror-gpu and a small --all-less run too, it scales with --max-share, and
# it cannot drift away from the rule it describes.

# share_measurable($corpus, $max_share) - true when a share verdict on this
# corpus says something about the identifier rather than about the run.
sub share_measurable {
    my ($corpus, $max_share) = @_;
    return 0 unless defined $corpus && defined $max_share;
    return 0 if $corpus <= 0 || $max_share <= 0;
    return 100 <= $max_share * $corpus ? 1 : 0;
}

# share_unmeasurable_reason($kind, $corpus, $max_share) - what to say instead.
# $kind is the tool's word for its identifier: format, type, mode.
sub share_unmeasurable_reason {
    my ($kind, $corpus, $max_share) = @_;
    return sprintf(
        'share UNMEASURABLE: the corpus is %d %s, so a single hit is %s%% and '
      . 'trips --max-share %d by itself. Every matching %s is held, which is a '
      . 'fact about this run and not about the %s -- re-run against the whole '
      . 'corpus (--all, without --only) to measure the share',
        $corpus, ($corpus == 1 ? 'entry' : 'entries'),
        ($corpus > 0 ? sprintf('%g', 100 / $corpus) : '100'),
        $max_share, $kind, $kind);
}

1;
