package RosettaHx;
#-----------------------------------------------------------------------
#
# Name: RosettaHx
# Description: read Appendix A of the hx Language Specification and decide
#              what this repository may say about each mdxfind type
#
#-----------------------------------------------------------------------
# METHODOLOGY AND WHY THIS EXISTS
#
# Appendix A of the hx Language Specification (Waffle, rev 1.15, Aug 2026)
# states an hx expression for 1011 mdxfind types. Two tools consume it and
# they must agree, because they write MUTUALLY EXCLUSIVE fields: seed-hx.pl
# writes expression:, denote-hx.pl writes denotation:, and validate.pl fails
# an entry carrying both. Two private copies of "is this expressible here"
# would eventually disagree, and the day they do an entry says the same thing
# twice at two strengths. So the boundary lives here, once.
#
# The specification is NOT vendored: this repository is MIT throughout and the
# PDF carries no licence grant. Re-fetch it to tmp/hx/ to re-run either tool.
#
# WHAT THE BOUNDARY IS
#
# %FUNC is the set of hx function tokens this repository knows how to spell in
# an expression:. A candidate naming anything outside it is NOT partially
# translated -- it is refused whole. Dropping a token silently is how
# md5(md5($p).":".$u) once looked like md5(md5($p).$s), and how cap() -- a
# no-op on a lowercase digest -- can make a wrong expression "prove" itself.
#
# The complement is what makes denotation: a checkable fact rather than a
# shrug: pbkdf2_sha256(), bcrypt(), blake2b512(), groestl256() name functions
# john's dynamic EXPRESSION language does not have, so those types have no
# expression here and never will. That is a lookup, not an opinion. Note what
# it does NOT say: john has FORMATS for bcrypt and for HMAC-SHA1.
#
# TWO PARSE DEFECTS THIS FIXES, both found 2026-08-31 by bucketing the 309
# types seed-hx.pl was refusing under one undifferentiated label:
#
#   1. The trailing prose gloss. Appendix A appends explanations to some
#      expressions -- "sha1(fromhex(salt) . pass) (macOS 10.4-10.6; salt is
#      hex-decoded)". The first stripper required the gloss to begin with a
#      capital, so a lowercase one survived into the expression, and its ';'
#      and '=' then made the whole type look like a multi-statement hx program.
#      Five types were lost that way, three of them (MACOSX, POSTGRESCRAM,
#      WINPHONE) perfectly translatable. strip_gloss() instead finds the
#      trailing parenthesised group and takes it only when what precedes it is
#      itself a complete balanced expression -- so md5(pass) is never mistaken
#      for a gloss, and the gloss is kept rather than discarded.
#
#   2. PDF typography. The PDF renders hx's iteration operator as U+02C6
#      MODIFIER LETTER CIRCUMFLEX, so the extracted text carries
#      "sha512^65536(...)" spelled with a non-ASCII lookalike -- and a
#      consumer of dist/rosetta.csv grepping for '^' does not find it. En and
#      em dashes and curly quotes come through the same way. All of it is
#      typesetting rather than content, so ascii_fold() flattens it on the way
#      in. This is not cosmetic: the corpus was 100% ASCII until an en dash
#      from a gloss reached one entry on 2026-08-31, and fmt.pl's
#      render-and-reparse check failed on it immediately, because YAML::XS
#      wants UTF-8 octets and had been handed decoded characters.
#
# MULTI-EMIT IS TWO LISTS, NOT ONE
#
# Note [24] names 34 types that emit SEVERAL candidate digests per input and
# match if any one reproduces the stored hash; such a type has no single
# expression, so writing one is a false claim even when the string is one of
# the forms. Appendix A ALSO spells emit() in the expression for 14 further
# types, and the two sets are disjoint -- measured 2026-08-31. So the note is
# not the whole population and must not be treated as one. is_multi_emit()
# answers from both.
#
#-----------------------------------------------------------------------
# Generated by Claude Opus 5 on 2026-08-31

use strict;
use warnings;
use Exporter qw(import);

our @EXPORT_OK = qw(parse_appendix translate_hx strip_gloss ascii_fold
                    is_multi_emit %FUNC %MODIFIER);

#-----------------------------------------------------------------------
# %MODIFIER -- the tokens that change REPRESENTATION or STRUCTURE rather than
# computing a digest, in THIS repository's spelling (the one an expression:
# field is written in, not hx's).
#
# It is declared before %FUNC and the modifier half of %FUNC is built from it,
# so the two cannot drift. That matters because a consumer counting hash
# applications -- render.pl's nesting depth -- has to tell md5(upper(md5($p)))
# (two hashes) from md5(md5(md5($p))) (three), and the only thing separating
# them is which tokens are in here. A new modifier added to %FUNC and not to
# this list would silently inflate every depth that used it.
#
# The two lists are in DIFFERENT namespaces, which is why one is built from
# the other rather than repeated: %FUNC is keyed by hx's spelling, %MODIFIER
# holds this repository's. They differ on exactly one token -- hx writes the
# little-endian widening utf16le where an expression: here normally writes
# utf16 -- so %MOD_HX carries the mapping and both lists come out of it.
#
# utf16le is then ALSO admitted as a repository spelling, because one entry
# (PEOPLESOFT, e858) carries the hx form in its own expression:. That is a
# token a reader will meet, so a consumer must classify it; it is not licence
# to write new expressions that way.
my %MOD_HX = (
    upper => 'upper', lower => 'lower', cap => 'cap', rev => 'rev',
    base64 => 'base64', hex => 'hex',
    cut => 'cut', pad => 'pad', fromhex => 'fromhex',
    frombase64 => 'frombase64', utf16be => 'utf16be', utf16le => 'utf16',
);
our %MODIFIER = map { $_ => 1 } (values %MOD_HX), 'utf16le';

#-----------------------------------------------------------------------
# hx spelling -> this repository's spelling. A token absent from here is a
# token neither tool will translate.

our %FUNC = (
    md5 => 'md5', md4 => 'md4', md2 => 'md2',
    sha1 => 'sha1', sha0 => 'sha0', sha224 => 'sha224', sha256 => 'sha256',
    sha384 => 'sha384', sha512 => 'sha512',
    wrl => 'whirlpool', gost => 'gost',
    rmd128 => 'ripemd128', rmd160 => 'ripemd160',
    rmd256 => 'ripemd256', rmd320 => 'ripemd320',
    sne128 => 'snefru128', sne256 => 'snefru256',
    hav128 => 'haval128_3', hav160 => 'haval160_3',
    hav192 => 'haval192_3', hav224 => 'haval224_3', hav256 => 'haval256_3',
    # The representation and structural modifiers are NOT listed again here.
    # They come from %MODIFIER above, spliced in below, because a token in one
    # list and not the other is exactly the drift that makes a nesting depth
    # or a denotation wrong. They are descriptive rather than cryptographic:
    # john cannot compile cut() or pad(), so an expression using one stays at
    # tier upstream -- but the field is documented as hx-style, ciscoasa
    # already carries a pad(), and refusing them would lose real information
    # for no gain. denote-hx.pl must therefore NOT count them as grounds for
    # `absent`.
);
$FUNC{$_} = $MOD_HX{$_} for keys %MOD_HX;
# hav128_4 / hav160_5 / ... expand mechanically
for my $w (qw(128 160 192 224 256)) {
    for my $r (3, 4, 5) { $FUNC{"hav${w}_$r"} = "haval${w}_$r" }
}
# _bin is this repository's _raw
for my $k (keys %FUNC) {
    $FUNC{"${k}_bin"} = "$FUNC{$k}_raw" if $k =~ /^(md|sha|wrl|gost|rmd|sne|hav)/;
}

#-----------------------------------------------------------------------
# MEASURED MULTI-EMIT, WHICH NEITHER UPSTREAM LIST CARRIES
#
# The two document-derived tests below miss a whole family, and the way to
# find that out is not to read harder. "mdxfind -z" dumps every candidate
# digest the tool computes for a password, so an emit count is MEASURABLE:
# MD5 prints one line, MD51SALTMD5 prints 480. Measured 2026-09-02 against
# RCS 1.545, and corroborated by reading the implementation in mdxfind.c --
# the 1SALT family sweeps a single salt byte over 9 and 32..126, 96 values,
# and emits five placements at each:
#
#     s.d    d.s    s.d.s    s.s.d    d.s.s        (d = hex32 inner digest)
#
# 5 x 96 = 480, and the corpus entries for these types already carried exactly
# those five forms as their name plus four aliases -- nobody had confirmed why.
# Appendix A's row for them is the prose "(complex: iterates over single-char
# salts)", so translate_hx refuses it and Note [24] does not name them: the
# family was invisible to both tests.
#
# WHY THIS IS A LIST AND NOT A SWEEP
#
# A full measured sweep of all 1002 types is the right end state and is now
# clearly possible, but it is not a drop-in replacement for the documents and
# must not be treated as one. Measured 2026-09-02: NTLM prints ONE candidate
# under this invocation while hx Note [29] states it emits three, so an emit
# count is authoritative for what the binary computes UNDER THE OPTIONS GIVEN
# and not for the type in general -- several families take extra inputs (-u
# user lists, -j peppers) that change what they emit. Until that is understood
# a measured zero or one cannot be allowed to overrule a document that says
# otherwise, so what goes in here is the set where measurement and the SOURCE
# agree and the documents are simply silent.
#
# Each entry cites where it was established. Re-measure with:
#   mdxfind -z -h '^TYPE$' -f <hashes> -i 1 <one-word-wordlist> | grep -c ^TYPE

my %MULTI_SOURCE = map { $_ => 1 } qw(
    MD51SALTMD5 MD51SALTMD5UC MD51SALTMD5MD5 MD51SALTMD5MD5MD5
    MD51SALTMD5MD5MD5MD5 MD51SALTMD5MD5MD5MD5MD5
    SHA11SALTMD5 SHA11SALTMD5UC SHA11SALTMD5SHA256 SHA1MD51SALTMD5
);

#-----------------------------------------------------------------------
# THE SECOND MEASURED GROUP: TYPES THAT REACH A MULTI-EMIT BLOCK BY
# FALLTHROUGH OR goto, WHICH IS WHY NOTE [24] DOES NOT NAME THEM
#
# Note [24] names types that sit AT a C case label whose body emits several
# digests. It does not name the types that reach that same body by falling
# through from an earlier label or by jumping to it, and those compute
# exactly the same thing because they run exactly the same code. Found
# 2026-09-02 by reading mdxfind.c rather than the appendix, after three
# corpus entries carried the TRIAGE verdict `partial` -- each reproducing
# one of its two vectors and not the other -- and is_multi_emit() said no to
# all three.
#
# mdxfind.c's b64md5raw block is the clearest case. It computes
#
#     len = b64_encode(digest, buf, 16);      24 chars, trailing "=="
#     mymd5(buf, len,     &mdcur[0]);         md5 of the whole base64
#     if (len > 18)
#       mymd5(buf, len - 2, &mdcur[1]);       md5 of it MINUS the padding
#
# and checkhash()es both on every iteration. MD5BASE64MD5RAW and
# MD5UCBASE64MD5RAW sit at that label and Note [24] names them;
# MD5BASE64MD5RAWSHA1 gotos it and MD5BASE64MD5RAWMD5 and
# MD5BASE64MD5RAWMD5MD5 fall into it, and the note names none of the three.
# The corpus settles it independently: each of those three entries carries
# two vectors for one plaintext, and the hx VM reproduces one of them from
# the padded form and the other from the 22-character form.
#
# Every name below was confirmed BOTH ways, which is what this list's rule
# requires: the source says the body emits more than one, and "mdxfind -z"
# agrees. Measured against RCS 1.545 on 2026-09-02 --
#
#     type                     -z lines   emissions   source
#     MD5BASE64MD5RAWSHA1          2          2          2
#     MD5BASE64MD5RAWMD5MD5        2          2          2
#     MD5BASE64MD5RAWMD5           2          2          2
#     MD5-DBL-PASS                 2          2          2
#     MD5SQL5-32                   8          8          8
#     SHA1MD5MD5PASS               4          2          2
#     SHA1SQL5                     6          3          3
#     SHA1SQL5MD5                  6          3          3
#     SHA1SQL5MD5MD5               6          3          3
#
# -z LINES ARE NOT EMISSIONS, AND THE DIFFERENCE IS PER OUTPUT WIDTH
#
# For a type whose output is a 40-hex SHA-1 digest, "mdxfind -z" prints every
# emission TWICE: the true digest, and a twin equal to the true digest with
# its first 8 hex characters dropped and eight "0"s appended --
#
#     SHA1BASE64x01 a07445b1a23792a88c177ae6e315dfadac81bdde:rosetta
#     SHA1BASE64x01 a23792a88c177ae6e315dfadac81bdde00000000:rosetta
#
# so the line count is DOUBLE the emission count there, while for a 32-hex
# md5-output type it is equal to it. Counting lines and calling the result an
# emission count therefore reports every ordinary SHA-1 type as multi-emit.
# Divide by two whenever the digests differ only by that shift; two lines that
# are unrelated digests are two real emissions --
#
#     MD5BASE64MD5RAWMD5x01 bf69328d466cdfc0da6b852d643937ad:rosetta
#     MD5BASE64MD5RAWMD5x01 dcf5f5226be78c2a212535a0f2a26e8e:rosetta
#
# Measured 2026-09-02. This is why the list's rule is a CONJUNCTION and not
# either test alone: the raw counts above were first read as emissions, and
# requiring the source to agree independently is what kept a wrong number from
# becoming a wrong claim. Nothing in this list changed when the counts were
# corrected.
#
# NOTE THE SPELLING. These are the names the BINARY publishes, which is what
# is_multi_emit() is asked about and what data/tools/mdxfind.yaml carries.
# The C identifiers differ: JOB_MD5DBLPASS is the type MD5-DBL-PASS and
# JOB_MD5SQL5_32 is MD5SQL5-32. Measuring the C spelling reports ZERO
# emissions, which looks exactly like a single-emit type rather than like a
# name that was never found. That is the separator-drift pitfall in
# CLAUDE.md, reached from a new direction.
#
# TWO THINGS DELIBERATELY LEFT OUT, both open questions:
#
#   - MD5BASE64SHA1RAWMD5 and MD5BASE64SHA1RAWBASE64SHA1RAW reach the
#     b64sha1raw block, which carries the same "if (len > 18)" second
#     emission, but "mdxfind -z" counts ONE for them -- and one for
#     MD5BASE64SHA1RAW too, which Note [24] DOES name. Source and
#     measurement disagree, so by this list's own rule neither may be
#     asserted here. The note keeps MD5BASE64SHA1RAW; its two siblings stay
#     unclaimed rather than being guessed either way.
#   - SHA1BASE64, SHA1SQL5-32, SHA1SQL5-40 and SHA1MD5PASSMD5 are NOT in this
#     list and must not be added: each prints 2 -z lines, but the two are the
#     shift-twins described above, so each is a SINGLE emission. SHA1_start
#     has been read since -- it is one checkhash() per iteration, and 71 types
#     goto it -- so the tail is single-emit and agrees. Resolved 2026-09-02;
#     it is recorded here because the raw count invites the mistake again.

$MULTI_SOURCE{$_} = 1 for qw(
    MD5BASE64MD5RAWSHA1 MD5BASE64MD5RAWMD5MD5 MD5BASE64MD5RAWMD5
    MD5-DBL-PASS SHA1MD5MD5PASS MD5SQL5-32
    SHA1SQL5 SHA1SQL5MD5 SHA1SQL5MD5MD5
);

#-----------------------------------------------------------------------
# THE THIRD GROUP: FOUND BY SWEEPING ALL 1002 TYPES, CONFIRMED IN THE SOURCE
#
# tmp/sweep-multiemit.pl measured every type the binary publishes rather than
# reading a document: 1002 types in 1022 seconds on 2026-09-02, against RCS
# 1.545. Results are in tmp/multiemit/sweep2.tsv, and the raw -z output for
# every type with more than one emission is under tmp/multiemit/raw/.
#
# READING "mdxfind -z" IS NOT COUNTING ITS LINES, AND THREE THINGS BITE.
# The first sweep proposed 55 names; 39 of them were artefacts of the method
# and would have gone straight into this hash. In order of how convincing the
# wrong answer looked:
#
#   - EVERY DIGEST IS PRINTED WITH ITS TRAILING-128-BIT WINDOWS. MD5 prints
#     1 line, SHA-1 2, SHA-512 and Whirlpool 4, all for ONE emission. This is
#     the masked/truncated-leak family, not a second candidate.
#   - THE WINDOW IS NOT ALWAYS ZERO-PADDED. SHA1SHA256 prints
#     ...7cbd4366 and then 54faf880...7cbd4366eec897b6, where the tail is
#     residue of the INNER sha256 left in the buffer. A rule that required
#     zeros missed it and called ~30 ordinary types multi-emit.
#   - ONE EMISSION IS OFTEN PRINTED IN TWO SPELLINGS. BLAKE2 prints each
#     digest bare and behind "$BLAKE2$"; MSSQL2000/2005/2012 print theirs
#     with and without a leading "0x"; APPLE-SECURE-NOTES prints one digest
#     in both "$ASN$" and "$fvde$" container syntax. None is multi-emit.
#
# So the sweep collapses windows structurally (a digest that BEGINS with a
# 32-hex-or-longer suffix of another is a window of it), strips serialization
# tags, and refuses to count non-hex serializations at all. DESCRYPT and
# BSDICRYPT print 4096 crypt(3) strings -- the 12-bit DES salt sweep, with
# the salt inside the ciphertext -- and are reported as their own class
# rather than claimed here.
#
# WHAT WENT IN, AND WHY EACH ONE
#
# The CAP family, which is the substantial find. JOB_SHA1SHA11CAP upper-cases
# each lower-case hex character of the inner digest IN TURN and emits sha1 of
# each result, then upper-cases ALL occurrences of each letter a-f and emits
# six more. For "rosetta" that is 16 + 6 = 22, and the sweep measured exactly
# 22. The count is INPUT-DEPENDENT -- it follows how many lower-case hex
# letters the digest happens to have -- which is on its own conclusive: no
# single expression can describe a type whose number of candidates varies
# with the candidate. Every entry naming one of these carried an expression
# spelling exactly one of the forms, usually with cap().
#
#     SHA1SHA11CAP  22    SHA1SHA256CAP  27    SHA1SHA1CAPSALT  16
#     SHA1MD51CAPMD5  13  SHA1MD51CAPMD5MD5  13   SHA1MD5UC1LC  9
#
# MD52SALTMD5MD5 and MD52SALTMD5MD5MD5 fall through into MD52SALTMD5, which
# Note [24] names; the same fallthrough blindness as the group above, found
# again from the other direction. 3 emissions each, measured.
#
# SHA1BASE64CUSTBASE64MD5 emits 4 unrelated digests, measured and read.
#
# WHAT WAS DELIBERATELY LEFT OUT, all measured >1 and none of it multi-emit:
# MSSQL2000/2005/2012 and APPLE-SECURE-NOTES (serialization duplicates, see
# above); DESCRYPT and BSDICRYPT (non-hex salt sweep); and EPISERVER, which
# dispatches on a VERSION carried in its salt -- mdxfind.c's own comment says
# the salt key is "V*SALT_B64" where V=0 selects SHA-1 and V=1 SHA-256 -- so
# for any one stored hash the version is fixed and one computation applies.
# That entry's expression covers only the v0 form, which is a completeness
# question about the row and not a multi-emit one.

$MULTI_SOURCE{$_} = 1 for qw(
    SHA1SHA11CAP SHA1SHA256CAP SHA1SHA1CAPSALT
    SHA1MD51CAPMD5 SHA1MD51CAPMD5MD5 SHA1MD5UC1LC
    MD52SALTMD5MD5 MD52SALTMD5MD5MD5
    SHA1BASE64CUSTBASE64MD5
);

#-----------------------------------------------------------------------
# Note [24]'s 34 named types.

my %MULTI_NOTE = map { $_ => 1 } qw(
    MD5MD5PASS MD5PASSMD5 MD5HEXSALT SHA1HEXSALT SHA256HEXSALT GOSTHEXSALT
    HAV128HEXSALT MD5BASE64MD5RAW MD5BASE64SHA1RAW MD52SALTMD5 MD5MD5USER
    SHA1MD5USER MD5CAPMD5USER MD5CAPMD5MD5USER MD5UCBASE64MD5RAW
    MD5UCBASE64SHA1RAW SHA1MD5DSALT SHA1MD5MD5DSALT SHA1SHA1MD5MD5PASS1SALT
    SHA1MD5BASE641SALT SHA1SHA256TRUNC SHA1SHA1TRUNC SHA1SHA512TRUNC
    SHA1MD6TRUNC SHA1SHA1CAPTRUNC SHA1SHA1UCTRUNC SHA1SHA256TRUNCSALT
    SHA1SHA512UCTRUNC SHA1SALTSHA512UCTRUNC SHA1SALTSHA256UCTRUNC
    SHA1SHA384TRUNC SHA1RMD160TRUNC SHA1SHA1SHA1TRUNC SHA1SHA1TRUNCMD5
);

# A SWEPT TRUNCATION LENGTH IS THE THIRD MULTI-EMIT SHAPE
#
# Note [24] names 34 types and Appendix A spells emit() for 14 more, and
# CLAUDE.md says to ask this function rather than re-derive either list. Both
# lists still miss a shape that the appendix states plainly in its own gloss:
#
#     SHA1SHA3-256TRUNC   sha1(cut(sha3_256(pass), 0, N))   (N = 21-64)
#
# N is not bound. The type computes a digest at every truncation length in the
# stated range and matches if any reproduces the stored hash, which is exactly
# what CLAUDE.md already describes the TRUNC family as doing. Note [24] names
# most of that family -- SHA1SHA256TRUNC, SHA1SHA1TRUNC, SHA1MD6TRUNC and a
# dozen more -- so the 16 it misses are an omission upstream, not a different
# construction. Found 2026-09-02, when denote-hx.pl stalled on
# SHA1SHA3-256TRUNC for an unrelated reason and the family turned out to be
# split across the two lists.
#
# The test is a lookup, not a judgement: the gloss states a NUMERIC RANGE for
# N. That is what distinguishes it from
#
#     SHA1MD5x            sha1(md5^N(pass))                 (N = iteration count)
#
# which must NOT match. An iteration count is identity in this repository --
# MD5x01 is not MD5x02, it is john's dynamic_2 -- so those 16 types are a
# family parameterised by N, not one type emitting several digests. Marking
# them multi-emit would forbid an expression: that each of them can honestly
# carry once N is fixed.
#
# Verified before widening: of the 16 types this newly catches, no entry
# carries an expression:, so nothing already claimed is withdrawn. Fifteen
# carried neither an expression nor a denotation and were sitting in the
# curation queue with nothing able to answer them.

my $N_RANGE = qr/\bN \s* = \s* \d+ \s* [-\x{2013}] \s* \d+/x;

# is_multi_emit($type, $hx) - true when the type emits several candidates.
# $hx is the hashref parse_appendix returned for that type, or undef; the
# second test reads emit() straight out of the appendix, which is how the 14
# types Note [24] omits are caught, and the third reads a swept range out of
# the gloss, which is how the 16 BOTH lists omit are caught.
sub is_multi_emit {
    my ($type, $hx) = @_;
    return 1 if defined $type && $MULTI_NOTE{$type};
    return 1 if defined $type && $MULTI_SOURCE{$type};
    return 0 unless $hx;
    return 1 if defined $hx->{expr} && $hx->{expr} =~ /\bemit\b/;

    # A swept range, and only where the expression actually uses N: a gloss
    # mentioning a range for something else is not a statement about emission.
    my $gloss = join ' ', @{ $hx->{gloss} || [] };
    return 1 if $gloss =~ $N_RANGE
             && defined $hx->{expr}
             && $hx->{expr} =~ /\bN\b/;

    return 0;
}

#-----------------------------------------------------------------------
# strip_gloss($text) -> ($expression, @glosses)
#
# Appendix A appends prose in parentheses. Take a trailing parenthesised group
# ONLY when the text before it is a complete balanced expression -- otherwise
# md5(pass) would lose its own argument list. Repeats, because a type can
# carry both a note citation and a gloss.

sub strip_gloss {
    my ($t) = @_;
    my @gloss;
    $t =~ s/\s+$//;
    while ($t =~ /\)$/) {
        # scan back from the final ')' to its matching '('
        my $depth = 0;
        my $open  = -1;
        for (my $i = length($t) - 1; $i >= 0; $i--) {
            my $c = substr($t, $i, 1);
            $depth++ if $c eq ')';
            if ($c eq '(') { $depth--; if ($depth == 0) { $open = $i; last } }
        }
        last if $open <= 0;                       # unbalanced, or the whole text
        my $before = substr($t, 0, $open);
        last unless $before =~ /\S\s$/;           # a gloss is set off by space
        $before =~ s/\s+$//;
        # what remains must itself be balanced, or we just cut an argument list
        my $bal = 0;
        for my $c (split //, $before) { $bal++ if $c eq '('; $bal-- if $c eq ')' }
        last if $bal != 0 || !length $before;
        unshift @gloss, substr($t, $open + 1, length($t) - $open - 2);
        $t = $before;
    }
    return ($t, @gloss);
}

#-----------------------------------------------------------------------
# ascii_fold($text) - flatten the PDF's typography to ASCII.

sub ascii_fold {
    my ($t) = @_;
    $t =~ s/\x{02C6}/^/g;                        # hx's iteration operator
    $t =~ tr/\x{2010}-\x{2015}\x{2212}/-/;        # hyphens, dashes, minus
    $t =~ tr/\x{2018}\x{2019}/'/;
    $t =~ tr/\x{201C}\x{201D}/"/;
    $t =~ s/\x{2026}/.../g;
    $t =~ s/\x{00A0}/ /g;
    return $t;
}

#-----------------------------------------------------------------------
# parse_appendix($path) -> { TYPENAME => { index, expr, raw, gloss } }
#
# 'raw' is the line as extracted, 'expr' is it with the glosses removed and
# U+02C6 normalised, 'gloss' is the arrayref of what was removed.

sub parse_appendix {
    my ($path) = @_;
    open my $fh, '<:encoding(UTF-8)', $path or die "RosettaHx: $path: $!\n";
    my %hx;
    while (my $line = <$fh>) {
        next unless $line =~ /^(e\d+)\s+(\S+)\s+(.+?)\s*$/;
        my ($idx, $name, $raw) = ($1, $2, $3);
        my ($expr, @gloss) = strip_gloss(ascii_fold($raw));
        $hx{$name} = { index => $idx, expr => $expr, raw => ascii_fold($raw),
                       gloss => \@gloss };
    }
    close $fh;
    return \%hx;
}

#-----------------------------------------------------------------------
# translate_hx($expr) -> ($repo_expression, $reason)
#
# Exactly one of the two is defined. $reason names why a refusal happened, so
# a caller can bucket its residue instead of printing one undifferentiated
# label -- which is what hid the two parse defects above for a whole session.
#
# 'unknown-token' additionally returns the offending tokens, comma-joined, as
# a third value: that list is the evidence denote-hx.pl writes into the entry.

sub translate_hx {
    my ($e) = @_;
    return (undef, 'no-expression') unless defined $e && length $e;
    return (undef, 'appendix-declines') if $e =~ /^\(/;
    return (undef, 'multi-emit')        if $e =~ /\bemit\b/;

    # hx binds a repeated subexpression: "h=md5(md5(pass)); md5(h . h)".
    # Inline it; the meaning is identical and this repository has no variables
    # in the expression field.
    my $orig = $e;
    if ($e =~ /^\s*(\w+)\s*=\s*(.+?)\s*;\s*(.+)$/) {
        my ($var, $val, $body) = ($1, $2, $3);
        return (undef, 'multi-statement') if $val =~ /[;=]/;
        $body =~ s/\b\Q$var\E\b/$val/g;
        $e = $body;
    }
    return (undef, 'multi-statement') if $e =~ /[;=]/;

    # STRING LITERALS BECOME john's CONSTANTS.
    #
    # john's dynamic language has $c1..$c8, appended after the expression as
    # ,c1=... -- doc/DYNAMIC_EXPRESSIONS lines 53-73, and confirmed on this
    # host 2026-09-02: md5($c1.$p),c1=x compiles and cracks. Every literal used
    # to fall out here as 'stray-literal', which stranded entries whose
    # construction the appendix states plainly and john can PROVE. mediawiki
    # is the worked example: md5(salt . "-" . md5(pass)) becomes
    # md5($s.$c1.md5($p)),c1=- and john recovers the entry's own plaintext.
    #
    # fromhex("0d") is a literal too, and turning it into a constant REMOVES a
    # token john's language does not have, rather than adding one. fromhex on
    # a VARIABLE is untouched and still refused later.
    my (@const, %seen_const);
    my $litfail;
    my $take = sub {
        my ($raw) = @_;                     # the constant's actual bytes
        # A comma would be read as the start of the next ,cN= assignment and
        # there is no documented escape for it, so refuse rather than emit
        # something john would silently misparse.
        if ($raw =~ /,/) { $litfail = 'constant-comma'; return '' }
        unless (defined $seen_const{$raw}) {
            if (@const >= 8) { $litfail = 'too-many-constants'; return '' }
            push @const, $raw;
            $seen_const{$raw} = scalar @const;    # $c1 is the first
        }
        return '$c' . $seen_const{$raw};
    };

    # fromhex("hh..") first, so its bytes are decoded rather than quoted.
    $e =~ s{\bfromhex\s*\(\s*"([0-9A-Fa-f]+)"\s*\)}
           { $take->(pack 'H*', $1) }ge;
    $e =~ s{"([^"]*)"}{ $take->($1) }ge;
    return (undef, $litfail) if $litfail;

    $e =~ s/\s+//g;
    # Operands. hx's `user` is this repository's $s wherever an entry stores
    # the userid in the salt field, which is every such entry here today --
    # but ONLY where the expression does not also name `salt`. POSTGRESCRAM is
    # md5(md5(pass . user) . fromhex(salt)): two different fields, and
    # collapsing both onto $s would claim the username and the 8-hex challenge
    # are the same string. That is a false expression, not an approximate one.
    return (undef, 'user-and-salt') if $e =~ /\buser\b/ && $e =~ /\bsalt\b/;
    $e =~ s/\bpass\b/\$p/g;
    $e =~ s/\bsalt\b/\$s/g;
    $e =~ s/\buser\b/\$s/g;

    # every function token must be known, and the misses are the answer
    my @tok = $e =~ /([A-Za-z][A-Za-z0-9_]*)\s*\(/g;
    my (%miss, @order);
    for my $t (@tok) { push @order, $t unless $FUNC{$t} || $miss{$t}++ }
    return (undef, 'unknown-token', join(',', @order)) if @order;
    $e =~ s/([A-Za-z][A-Za-z0-9_]*)\s*\(/$FUNC{$1}."("/ge;

    # Every BARE identifier left must be an operand this repository can spell.
    # hx has more of them than john's dynamic does -- salt2, s1, s2, site_key,
    # cost, and the iteration count N -- and the first version of this check
    # only looked at function tokens, so those walked straight through into
    # expression: as themselves. Four entries were carrying the result on
    # 2026-08-31. Refuse rather than guess which john operand a second salt is:
    # john has $s2, but which of hx's two salt fields it denotes is a claim
    # about field order that nothing here can check.
    my (%bad, @badorder);
    while ($e =~ /(?<![\$\w])([A-Za-z][A-Za-z0-9_]*)(\(?)/g) {
        next if $2 eq '(';                       # a function, already checked
        push @badorder, $1 unless $bad{$1}++;
    }
    return (undef, 'unknown-operand', join(',', @badorder)) if @badorder;

    # must actually mention the password: a candidate that never uses $p is
    # the tokeniser having lost an operand, not an algorithm.
    return (undef, 'no-password') unless $e =~ /\$p/;

    # The stray-literal guard runs on the BODY, before the constant data is
    # appended: that data is arbitrary bytes by definition -- "{SSHA}", a
    # space, a NUL -- and testing it here would reject every constant this
    # function just built.
    return (undef, 'stray-literal') if $e =~ /[^A-Za-z0-9_\$\(\)\.,]/;

    # ':' terminates a field in john's input, so a constant containing one has
    # to be escaped. The doc gives the form: md5($c1.$p),c1=test_\x3a_test
    if (@const) {
        my $i = 0;
        for my $c (@const) {
            my $v = $c;
            $v =~ s/([:\\])/sprintf '\\x%02x', ord $1/ge;
            $v =~ s/([^\x20-\x7e])/sprintf '\\x%02x', ord $1/ge;
            $e .= ',c' . (++$i) . '=' . $v;
        }
    }
    return ($e, undef);
}

1;
