package RosettaHx;
#-----------------------------------------------------------------------
#
# Name: RosettaHx
# Description: read Appendix A of the hx Language Specification and decide
#              what this repository may say about each mdxfind type
#
#-----------------------------------------------------------------------
# METHODOLOGY AND WHY THIS EXISTS
#
# Appendix A of the hx Language Specification (Waffle, rev 1.15, Aug 2026)
# states an hx expression for 1011 mdxfind types. Two tools consume it and
# they must agree, because they write MUTUALLY EXCLUSIVE fields: seed-hx.pl
# writes expression:, denote-hx.pl writes denotation:, and validate.pl fails
# an entry carrying both. Two private copies of "is this expressible here"
# would eventually disagree, and the day they do an entry says the same thing
# twice at two strengths. So the boundary lives here, once.
#
# The specification is NOT vendored: this repository is MIT throughout and the
# PDF carries no licence grant. Re-fetch it to tmp/hx/ to re-run either tool.
#
# WHAT THE BOUNDARY IS
#
# %FUNC is the set of hx function tokens this repository knows how to spell in
# an expression:. A candidate naming anything outside it is NOT partially
# translated -- it is refused whole. Dropping a token silently is how
# md5(md5($p).":".$u) once looked like md5(md5($p).$s), and how cap() -- a
# no-op on a lowercase digest -- can make a wrong expression "prove" itself.
#
# The complement is what makes denotation: a checkable fact rather than a
# shrug: pbkdf2_sha256(), bcrypt(), blake2b512(), groestl256() name functions
# john's dynamic EXPRESSION language does not have, so those types have no
# expression here and never will. That is a lookup, not an opinion. Note what
# it does NOT say: john has FORMATS for bcrypt and for HMAC-SHA1.
#
# TWO PARSE DEFECTS THIS FIXES, both found 2026-08-31 by bucketing the 309
# types seed-hx.pl was refusing under one undifferentiated label:
#
#   1. The trailing prose gloss. Appendix A appends explanations to some
#      expressions -- "sha1(fromhex(salt) . pass) (macOS 10.4-10.6; salt is
#      hex-decoded)". The first stripper required the gloss to begin with a
#      capital, so a lowercase one survived into the expression, and its ';'
#      and '=' then made the whole type look like a multi-statement hx program.
#      Five types were lost that way, three of them (MACOSX, POSTGRESCRAM,
#      WINPHONE) perfectly translatable. strip_gloss() instead finds the
#      trailing parenthesised group and takes it only when what precedes it is
#      itself a complete balanced expression -- so md5(pass) is never mistaken
#      for a gloss, and the gloss is kept rather than discarded.
#
#   2. PDF typography. The PDF renders hx's iteration operator as U+02C6
#      MODIFIER LETTER CIRCUMFLEX, so the extracted text carries
#      "sha512^65536(...)" spelled with a non-ASCII lookalike -- and a
#      consumer of dist/rosetta.csv grepping for '^' does not find it. En and
#      em dashes and curly quotes come through the same way. All of it is
#      typesetting rather than content, so ascii_fold() flattens it on the way
#      in. This is not cosmetic: the corpus was 100% ASCII until an en dash
#      from a gloss reached one entry on 2026-08-31, and fmt.pl's
#      render-and-reparse check failed on it immediately, because YAML::XS
#      wants UTF-8 octets and had been handed decoded characters.
#
# MULTI-EMIT IS TWO LISTS, NOT ONE
#
# Note [24] names 34 types that emit SEVERAL candidate digests per input and
# match if any one reproduces the stored hash; such a type has no single
# expression, so writing one is a false claim even when the string is one of
# the forms. Appendix A ALSO spells emit() in the expression for 14 further
# types, and the two sets are disjoint -- measured 2026-08-31. So the note is
# not the whole population and must not be treated as one. is_multi_emit()
# answers from both.
#
#-----------------------------------------------------------------------
# Generated by Claude Opus 5 on 2026-08-31

use strict;
use warnings;
use Exporter qw(import);

our @EXPORT_OK = qw(parse_appendix translate_hx strip_gloss ascii_fold
                    is_multi_emit %FUNC);

#-----------------------------------------------------------------------
# hx spelling -> this repository's spelling. A token absent from here is a
# token neither tool will translate.

our %FUNC = (
    md5 => 'md5', md4 => 'md4', md2 => 'md2',
    sha1 => 'sha1', sha0 => 'sha0', sha224 => 'sha224', sha256 => 'sha256',
    sha384 => 'sha384', sha512 => 'sha512',
    wrl => 'whirlpool', gost => 'gost',
    rmd128 => 'ripemd128', rmd160 => 'ripemd160',
    rmd256 => 'ripemd256', rmd320 => 'ripemd320',
    sne128 => 'snefru128', sne256 => 'snefru256',
    hav128 => 'haval128_3', hav160 => 'haval160_3',
    hav192 => 'haval192_3', hav224 => 'haval224_3', hav256 => 'haval256_3',
    # representation modifiers that carry over unchanged in meaning
    upper => 'upper', lower => 'lower', cap => 'cap', rev => 'rev',
    base64 => 'base64', hex => 'hex',
    # structural, and descriptive rather than cryptographic. These cannot be
    # compiled by john, so an expression using one stays at tier upstream --
    # but the field is documented as hx-style, and ciscoasa already carries a
    # pad(). Refusing them would lose real information for no gain, and
    # denote-hx.pl must therefore NOT count them as grounds for `absent`.
    cut => 'cut', pad => 'pad', fromhex => 'fromhex',
    frombase64 => 'frombase64', utf16be => 'utf16be',
);
# hav128_4 / hav160_5 / ... expand mechanically
for my $w (qw(128 160 192 224 256)) {
    for my $r (3, 4, 5) { $FUNC{"hav${w}_$r"} = "haval${w}_$r" }
}
# _bin is this repository's _raw
for my $k (keys %FUNC) {
    $FUNC{"${k}_bin"} = "$FUNC{$k}_raw" if $k =~ /^(md|sha|wrl|gost|rmd|sne|hav)/;
}
$FUNC{utf16le} = 'utf16';

#-----------------------------------------------------------------------
# Note [24]'s 34 named types.

my %MULTI_NOTE = map { $_ => 1 } qw(
    MD5MD5PASS MD5PASSMD5 MD5HEXSALT SHA1HEXSALT SHA256HEXSALT GOSTHEXSALT
    HAV128HEXSALT MD5BASE64MD5RAW MD5BASE64SHA1RAW MD52SALTMD5 MD5MD5USER
    SHA1MD5USER MD5CAPMD5USER MD5CAPMD5MD5USER MD5UCBASE64MD5RAW
    MD5UCBASE64SHA1RAW SHA1MD5DSALT SHA1MD5MD5DSALT SHA1SHA1MD5MD5PASS1SALT
    SHA1MD5BASE641SALT SHA1SHA256TRUNC SHA1SHA1TRUNC SHA1SHA512TRUNC
    SHA1MD6TRUNC SHA1SHA1CAPTRUNC SHA1SHA1UCTRUNC SHA1SHA256TRUNCSALT
    SHA1SHA512UCTRUNC SHA1SALTSHA512UCTRUNC SHA1SALTSHA256UCTRUNC
    SHA1SHA384TRUNC SHA1RMD160TRUNC SHA1SHA1SHA1TRUNC SHA1SHA1TRUNCMD5
);

# is_multi_emit($type, $hx) - true when the type emits several candidates.
# $hx is the hashref parse_appendix returned for that type, or undef; the
# second test reads emit() straight out of the appendix, which is how the 14
# types Note [24] omits are caught.
sub is_multi_emit {
    my ($type, $hx) = @_;
    return 1 if defined $type && $MULTI_NOTE{$type};
    return 1 if $hx && defined $hx->{expr} && $hx->{expr} =~ /\bemit\b/;
    return 0;
}

#-----------------------------------------------------------------------
# strip_gloss($text) -> ($expression, @glosses)
#
# Appendix A appends prose in parentheses. Take a trailing parenthesised group
# ONLY when the text before it is a complete balanced expression -- otherwise
# md5(pass) would lose its own argument list. Repeats, because a type can
# carry both a note citation and a gloss.

sub strip_gloss {
    my ($t) = @_;
    my @gloss;
    $t =~ s/\s+$//;
    while ($t =~ /\)$/) {
        # scan back from the final ')' to its matching '('
        my $depth = 0;
        my $open  = -1;
        for (my $i = length($t) - 1; $i >= 0; $i--) {
            my $c = substr($t, $i, 1);
            $depth++ if $c eq ')';
            if ($c eq '(') { $depth--; if ($depth == 0) { $open = $i; last } }
        }
        last if $open <= 0;                       # unbalanced, or the whole text
        my $before = substr($t, 0, $open);
        last unless $before =~ /\S\s$/;           # a gloss is set off by space
        $before =~ s/\s+$//;
        # what remains must itself be balanced, or we just cut an argument list
        my $bal = 0;
        for my $c (split //, $before) { $bal++ if $c eq '('; $bal-- if $c eq ')' }
        last if $bal != 0 || !length $before;
        unshift @gloss, substr($t, $open + 1, length($t) - $open - 2);
        $t = $before;
    }
    return ($t, @gloss);
}

#-----------------------------------------------------------------------
# ascii_fold($text) - flatten the PDF's typography to ASCII.

sub ascii_fold {
    my ($t) = @_;
    $t =~ s/\x{02C6}/^/g;                        # hx's iteration operator
    $t =~ tr/\x{2010}-\x{2015}\x{2212}/-/;        # hyphens, dashes, minus
    $t =~ tr/\x{2018}\x{2019}/'/;
    $t =~ tr/\x{201C}\x{201D}/"/;
    $t =~ s/\x{2026}/.../g;
    $t =~ s/\x{00A0}/ /g;
    return $t;
}

#-----------------------------------------------------------------------
# parse_appendix($path) -> { TYPENAME => { index, expr, raw, gloss } }
#
# 'raw' is the line as extracted, 'expr' is it with the glosses removed and
# U+02C6 normalised, 'gloss' is the arrayref of what was removed.

sub parse_appendix {
    my ($path) = @_;
    open my $fh, '<:encoding(UTF-8)', $path or die "RosettaHx: $path: $!\n";
    my %hx;
    while (my $line = <$fh>) {
        next unless $line =~ /^(e\d+)\s+(\S+)\s+(.+?)\s*$/;
        my ($idx, $name, $raw) = ($1, $2, $3);
        my ($expr, @gloss) = strip_gloss(ascii_fold($raw));
        $hx{$name} = { index => $idx, expr => $expr, raw => ascii_fold($raw),
                       gloss => \@gloss };
    }
    close $fh;
    return \%hx;
}

#-----------------------------------------------------------------------
# translate_hx($expr) -> ($repo_expression, $reason)
#
# Exactly one of the two is defined. $reason names why a refusal happened, so
# a caller can bucket its residue instead of printing one undifferentiated
# label -- which is what hid the two parse defects above for a whole session.
#
# 'unknown-token' additionally returns the offending tokens, comma-joined, as
# a third value: that list is the evidence denote-hx.pl writes into the entry.

sub translate_hx {
    my ($e) = @_;
    return (undef, 'no-expression') unless defined $e && length $e;
    return (undef, 'appendix-declines') if $e =~ /^\(/;
    return (undef, 'multi-emit')        if $e =~ /\bemit\b/;

    # hx binds a repeated subexpression: "h=md5(md5(pass)); md5(h . h)".
    # Inline it; the meaning is identical and this repository has no variables
    # in the expression field.
    my $orig = $e;
    if ($e =~ /^\s*(\w+)\s*=\s*(.+?)\s*;\s*(.+)$/) {
        my ($var, $val, $body) = ($1, $2, $3);
        return (undef, 'multi-statement') if $val =~ /[;=]/;
        $body =~ s/\b\Q$var\E\b/$val/g;
        $e = $body;
    }
    return (undef, 'multi-statement') if $e =~ /[;=]/;

    $e =~ s/\s+//g;
    # Operands. hx's `user` is this repository's $s wherever an entry stores
    # the userid in the salt field, which is every such entry here today --
    # but ONLY where the expression does not also name `salt`. POSTGRESCRAM is
    # md5(md5(pass . user) . fromhex(salt)): two different fields, and
    # collapsing both onto $s would claim the username and the 8-hex challenge
    # are the same string. That is a false expression, not an approximate one.
    return (undef, 'user-and-salt') if $e =~ /\buser\b/ && $e =~ /\bsalt\b/;
    $e =~ s/\bpass\b/\$p/g;
    $e =~ s/\bsalt\b/\$s/g;
    $e =~ s/\buser\b/\$s/g;

    # every function token must be known, and the misses are the answer
    my @tok = $e =~ /([A-Za-z][A-Za-z0-9_]*)\s*\(/g;
    my (%miss, @order);
    for my $t (@tok) { push @order, $t unless $FUNC{$t} || $miss{$t}++ }
    return (undef, 'unknown-token', join(',', @order)) if @order;
    $e =~ s/([A-Za-z][A-Za-z0-9_]*)\s*\(/$FUNC{$1}."("/ge;

    # Every BARE identifier left must be an operand this repository can spell.
    # hx has more of them than john's dynamic does -- salt2, s1, s2, site_key,
    # cost, and the iteration count N -- and the first version of this check
    # only looked at function tokens, so those walked straight through into
    # expression: as themselves. Four entries were carrying the result on
    # 2026-08-31. Refuse rather than guess which john operand a second salt is:
    # john has $s2, but which of hx's two salt fields it denotes is a claim
    # about field order that nothing here can check.
    my (%bad, @badorder);
    while ($e =~ /(?<![\$\w])([A-Za-z][A-Za-z0-9_]*)(\(?)/g) {
        next if $2 eq '(';                       # a function, already checked
        push @badorder, $1 unless $bad{$1}++;
    }
    return (undef, 'unknown-operand', join(',', @badorder)) if @badorder;

    # must actually mention the password: a candidate that never uses $p is
    # the tokeniser having lost an operand, not an algorithm.
    return (undef, 'no-password') unless $e =~ /\$p/;
    return (undef, 'stray-literal') if $e =~ /[^A-Za-z0-9_\$\(\)\.,]/;
    return ($e, undef);
}

1;
