#!/usr/bin/perl
#-----------------------------------------------------------------------
#
# Name: audit-iterations.pl
# Description: check that an entry's vector really is at the iteration count
#              the entry declares, and repair it when it is not
# Category: cracking-rosetta verifier
#
# Project: cracking-rosetta | Phase: 6 - close the john gap
#
#-----------------------------------------------------------------------
# METHODOLOGY AND WHY THIS EXISTS
#
# HOW THE DEFECT WAS FOUND
#
# discover-john.pl reported that entry hav160-5-x2 -- "HAV160-5, 2 iterations"
# -- was cracked by john's dynamic_210, which is haval160_5($p) applied ONCE.
# That cannot be true of a twice-iterated digest, so either the mapping or the
# vector was wrong. mdxfind settled it: pinned to HAV160-5 the vector came back
# tagged "x01". The vector was the type's single-iteration self-test hash, and
# 42 entries carry one.
#
# The seeding step attached each mdxfind type's base self-test vector to every
# entry derived from that type, including the entries whose whole identity is
# that the type is applied more than once. CLAUDE.md's own pitfall list says
# the iteration suffix IS the identity; the vector quietly ignored it.
#
# WHY verify-vectors.pl DID NOT CATCH IT
#
# It matched mdxfind output with (?:x\d+)? -- any iteration suffix at all. So a
# vector that cracked at x01 satisfied an entry declaring x02 and was promoted
# to tier 'vector'. That regex is tightened as part of this work; this script
# is what proves the tightening was needed.
#
# THE MEASUREMENT
#
# mdxfind computes every iteration up to -i N and names the one that matched in
# its output suffix. Run each vector at a couple past its declared count and
# the suffix is the answer -- a measurement, not an inference. Running past the
# declared count is what makes an over-count visible as well as an under-count.
#
# THE REPAIR, AND WHY IT IS NOT CIRCULAR
#
# A wrong vector is deleted, not re-labelled: it belongs to a different entry
# that already exists. That leaves entries with no vector at all, so a
# replacement is taken from john's own regression corpus --
# "john --format=dynamic_213 --list=format-tests" ships ciphertext and
# plaintext together for every format, disabled dynamics included.
#
# Taking john's vector to prove a john mapping would be circular, so the
# replacement is only accepted when MDXFIND independently reproduces it at the
# declared iteration count. john says "this is haval160_5 twice"; mdxfind says
# "this is HAV160-5 at iteration 2"; two implementations that share no code
# agree, and only then is it written down.
#
# DEMOTION IS CORRECT HERE, AND ONLY HERE
#
# CLAUDE.md's rule is that a failed run never demotes, because a failure has
# many innocent explanations. This is not that. A vector measured at x01 under
# an entry declaring x02 is positive evidence that the recorded proof was of
# something else. If no replacement can be proven, the tier that rested on that
# proof goes back to 'asserted' and says why. Leaving 'vector' there would be
# the one thing the project cannot do.
#
#-----------------------------------------------------------------------
# Generated by Claude Opus 5 on 2026-08-29

use strict;
use warnings;

use File::Basename qw(basename);
use File::Path qw(make_path);
use FindBin qw($RealBin);
use Getopt::Long qw(GetOptions);
use POSIX qw(strftime);
use YAML::XS ();

use lib "$RealBin/lib";
use RosettaEmit qw(emit_entry);
use RosettaTools qw(tool_path tool_env_help);

my $PROG = basename($0);
my $ROOT = "$RealBin/..";

sub usage {
    print STDERR <<"END_USAGE";

Usage: $PROG [options]

   --mdxfind PATH    mdxfind binary  (default: @{[tool_env_help('mdxfind')]})
   --john PATH       john binary     (default: @{[tool_env_help('john')]})
   --algorithms DIR  curated entries (default: data/algorithms)
   --work DIR        scratch         (default: tmp/audit-iterations)
   --timeout SECS    per invocation  (default: 120)
   --headroom N      run this many iterations past the declared count
                     so an over-count is visible too (default: 2)
   --only ID         audit just this entry
   --no-repair       report only; do not look for replacement vectors
   --apply           write repairs into data/algorithms
   -v, --verbose     per-vector detail (repeatable)
   -h, --help        this help

   Without --apply nothing is written. Exit 0 success, 1 error, 2 usage.

END_USAGE
    return;
}

my ($mdxfind, $john, $algdir, $workdir, $only, $help, $apply, $no_repair);
my $timeout  = 120;
my $headroom = 2;
my $verbose  = 0;
my $had_args = scalar @ARGV;

GetOptions(
    'mdxfind=s'    => \$mdxfind,
    'john=s'       => \$john,
    'algorithms=s' => \$algdir,
    'work=s'       => \$workdir,
    'timeout=i'    => \$timeout,
    'headroom=i'   => \$headroom,
    'only=s'       => \$only,
    'no-repair'    => \$no_repair,
    'apply'        => \$apply,
    'v|verbose+'   => \$verbose,
    'h|help'       => \$help,
) or do { usage(); exit 2 };

if ($help)      { usage(); exit 0 }
if (!$had_args) { usage(); exit 2 }

$mdxfind = tool_path('mdxfind', $mdxfind);
$john = tool_path('john', $john);
$algdir  //= "$ROOT/data/algorithms";
$workdir //= "$ROOT/tmp/audit-iterations";

make_path($workdir) unless -d $workdir;
my $today = strftime('%Y-%m-%d', localtime);

#-----------------------------------------------------------------------
# Which mdxfind types carry an extra field inline -- a salt ('s') or a userid
# ('u', how the HMAC types take their key). Both need -F, not -f.

my $inv = eval { YAML::XS::LoadFile("$ROOT/data/tools/mdxfind.yaml") }
    or do { print STDERR "$PROG: cannot load the mdxfind inventory: $@\n"; exit 1 };
my %salted = map { $_->{name} => 1 }
             grep { grep { $_ eq 's' || $_ eq 'u' } @{ $_->{flags} || [] } }
             @{ $inv->{types} || [] };

#-----------------------------------------------------------------------
# Entries.

opendir(my $dh, $algdir) or do { print STDERR "$PROG: cannot read $algdir: $!\n"; exit 1 };
my @files = sort grep { /\.yaml$/ } readdir $dh;
closedir $dh;

my (%entry, %path);
for my $f (@files) {
    my $p = "$algdir/$f";
    my $e = eval { YAML::XS::LoadFile($p) };
    next unless $e && $e->{id};
    next if defined $only && $e->{id} ne $only;
    $entry{ $e->{id} } = $e;
    $path{  $e->{id} } = $p;
}

#-----------------------------------------------------------------------
# Helpers.

sub write_file {
    my ($p, @lines) = @_;
    open my $fh, '>', $p or die "cannot write $p: $!\n";
    print {$fh} "$_\n" for @lines;
    close $fh;
    return $p;
}

sub run_capture {
    my ($secs, @argv) = @_;
    my $out = '';
    my $pid = open(my $fh, '-|');
    defined $pid or return (-1, '');
    if (!$pid) {
        open STDERR, '>&', \*STDOUT;
        exec { $argv[0] } @argv or exit 127;
    }
    my $killed = 0;
    eval {
        local $SIG{ALRM} = sub { $killed = 1; kill 'KILL', $pid; die "timeout\n" };
        alarm $secs;
        local $/;
        $out = <$fh> // '';
        alarm 0;
    };
    alarm 0;
    close $fh;
    return ($killed ? -2 : ($? >> 8), $out);
}

# mdx_iterations($type, [{hash,pass},...], $max)
#   -> { "hash\0pass" => iteration mdxfind matched at }
# The suffix in "HAV160-5x02 <hash>:<pass>" is the measurement; a type that
# prints no suffix reports 0, which the caller reads as "cannot tell".
sub mdx_iterations {
    my ($type, $vecs, $max) = @_;
    return {} unless @$vecs;

    (my $safe = $type) =~ s/[^A-Za-z0-9]/_/g;
    my $hf = write_file("$workdir/$safe.$max.hash", map { $_->{hash} } @$vecs);
    my $wf = write_file("$workdir/$safe.$max.word", map { $_->{pass} } @$vecs);

    my $flag = $salted{$type} ? '-F' : '-f';
    my ($code, $out) = run_capture($timeout, $mdxfind,
        '-h', "^\Q$type\E\$", $flag, $hf, '-i', $max, $wf);

    my %seen;
    for my $line (split /\n/, $out) {
        # "<TYPE>[xNN] <hash>:<pass>"; the hash may itself contain colons for
        # a salted type, so anchor on the trailing plaintext instead.
        next unless $line =~ /^\Q$type\E(?:x(\d+))?\s+(.+)$/;
        my ($it, $rest) = ($1, $2);
        for my $v (@$vecs) {
            next unless $rest eq "$v->{hash}:$v->{pass}";
            $seen{"$v->{hash}\0$v->{pass}"} = defined $it ? $it + 0 : 0;
        }
    }
    return \%seen;
}

# john_tests($label) -> ( {hash, pass}, ... ) from john's own regression corpus.
# The ciphertext comes back in john's encoding, so a "$dynamic_N$" tag is
# stripped: every tool here stores the bare digest.
sub john_tests {
    my ($label) = @_;
    my $jdir = $john; $jdir =~ s{/[^/]+$}{};
    my $jbin = basename($john);
    my ($code, $out) = run_capture($timeout, '/bin/sh', '-c',
        sprintf('cd %s && exec ./%s --format=%s --list=format-tests 2>/dev/null',
                quotemeta($jdir), quotemeta($jbin), quotemeta($label)));
    my @t;
    my %seen;
    for my $line (split /\n/, $out) {
        my (undef, undef, $ct, $pw) = split /\t/, $line, 4;
        next unless defined $ct && defined $pw && length $pw;
        $ct =~ s/^\$dynamic_\d+\$//;
        next if $seen{"$ct\0$pw"}++;
        push @t, { hash => $ct, pass => $pw };
    }
    return @t;
}

#-----------------------------------------------------------------------
# Measure. One mdxfind run per (type, headroom-adjusted ceiling).

my %group;   # type -> max ceiling -> [ {id, hash, pass, declared} ]
for my $id (sort keys %entry) {
    my $e = $entry{$id};
    my $m = $e->{tools}{mdxfind} or next;
    my $declared = $m->{iterations} // 1;
    for my $v (@{ $e->{vectors} || [] }) {
        next unless defined $v->{hash} && defined $v->{pass};
        push @{ $group{$_} }, { id => $id, hash => $v->{hash},
                                pass => $v->{pass}, declared => $declared }
            for @{ $m->{types} || [] };
    }
}

my (@wrong, @nocrack, @untagged);
my $checked = 0;

for my $type (sort keys %group) {
    my @v = @{ $group{$type} };
    my $max = 0;
    for (@v) { $max = $_->{declared} if $_->{declared} > $max }
    $max += $headroom;

    my $got = mdx_iterations($type, \@v, $max);

    for my $v (@v) {
        $checked++;
        my $it = $got->{"$v->{hash}\0$v->{pass}"};
        if    (!defined $it) { push @nocrack,  [$v, $type, undef] }
        elsif ($it == 0)     { push @untagged, [$v, $type, undef] }
        elsif ($it != $v->{declared}) { push @wrong, [$v, $type, $it] }
    }
    printf STDERR "-   %-24s %3d vector(s) at -i %d\n", $type, scalar @v, $max
        if $verbose > 1;
}

printf STDERR "- checked %d vector(s) across %d type(s)\n", $checked, scalar keys %group;
printf STDERR "-   wrong iteration count %d, did not crack %d, no suffix reported %d\n",
    scalar @wrong, scalar @nocrack, scalar @untagged;

for my $w (@wrong) {
    my ($v, $type, $it) = @$w;
    printf "WRONG    %-28s %-14s declared x%d, measured x%d  %s\n",
        $v->{id}, $type, $v->{declared}, $it, $v->{hash};
}
if ($verbose) {
    for my $w (@nocrack) {
        my ($v, $type) = @$w;
        printf "NOCRACK  %-28s %-14s declared x%d  %s\n",
            $v->{id}, $type, $v->{declared}, $v->{hash};
    }
}

exit 0 unless $apply;

#-----------------------------------------------------------------------
# Repair. Drop the vectors that measured wrong, then try to give any entry
# left empty a replacement that BOTH tools agree on.

my %drop;                          # id -> { "hash\0pass" => 1 }
$drop{ $_->[0]{id} }{ "$_->[0]{hash}\0$_->[0]{pass}" } = 1 for @wrong;

my ($rewritten, $replaced, $demoted) = (0, 0, 0);

for my $id (sort keys %drop) {
    my $e = $entry{$id};
    my $m = $e->{tools}{mdxfind};
    my $declared = $m->{iterations} // 1;

    my @keep = grep { !$drop{$id}{"$_->{hash}\0$_->{pass}"} } @{ $e->{vectors} || [] };
    my $lost = scalar(@{ $e->{vectors} || [] }) - scalar @keep;

    # A replacement is only sought when nothing verifiable is left.
    if (!@keep && !$no_repair) {
        my @labels = @{ $e->{tools}{john}{cpu} || [] };
        CANDIDATE: for my $label (@labels) {
            for my $t (john_tests($label)) {
                for my $type (@{ $m->{types} || [] }) {
                    my $got = mdx_iterations($type, [$t], $declared + $headroom);
                    next unless ($got->{"$t->{hash}\0$t->{pass}"} // 0) == $declared;
                    push @keep, { hash => $t->{hash}, pass => $t->{pass},
                                  source => 'john' };
                    $replaced++;
                    printf STDERR "-   %-24s replaced from %s, confirmed as %s x%d\n",
                        $id, $label, $type, $declared;
                    last CANDIDATE;
                }
            }
        }
    }

    $e->{vectors} = \@keep;

    if (@keep) {
        # The surviving or replacement vector still has to be re-proven; that
        # is verify-vectors.pl's job, so drop back to a tier that says so.
        for my $tool (qw(hashcat mdxfind john)) {
            my $blk = $e->{tools}{$tool} or next;
            next unless ($blk->{verified} // '') eq 'vector';
            $blk->{verified}    = 'asserted';
            $blk->{verified_at} = $today;
            $blk->{note}        = 'vector replaced; re-run verify-vectors.pl';
        }
    }
    else {
        delete $e->{vectors};
        for my $tool (qw(hashcat mdxfind john)) {
            my $blk = $e->{tools}{$tool} or next;
            next unless ($blk->{verified} // '') eq 'vector';
            $blk->{verified}    = 'asserted';
            $blk->{verified_at} = $today;
            $blk->{note} = "tier 'vector' rested on a vector measured at the "
                         . 'wrong iteration count; no replacement proven';
            $demoted++;
        }
        printf STDERR "-   %-24s left with no vector (%d dropped)\n", $id, $lost;
    }

    $rewritten += emit_entry($path{$id}, $e);
}

printf STDERR "- repaired: %d file(s) rewritten, %d vector(s) replaced, %d block(s) demoted\n",
    $rewritten, $replaced, $demoted;
printf STDERR "- now re-run: tools/verify-vectors.pl --tool all\n" if $rewritten;

exit 0;
