#!/usr/bin/perl
#-----------------------------------------------------------------------
#
# Name: check-numbers.pl
# Description: fail a count in documentation or help text that carries no
#              measurement date
# Category: cracking-rosetta gate
#
# Project: cracking-rosetta | Phase: publication prep
#
#-----------------------------------------------------------------------
# METHODOLOGY AND WHY THESE CHOICES
#
# THE PROBLEM: A COUNT IN PROSE IS WRONG THE DAY AFTER IT IS WRITTEN
#
# This repository regenerates its inventories, derives its own fields and
# shrinks its own queues, so any number stated in hand-written text starts
# decaying the moment it is typed. Measured 2026-09-02, before this gate
# existed: MAINTAINING.md offered a reader "772 entries with no category:",
# curate.pl said "(772 open)" in its --help, and the live figure was 483. Two
# surfaces, one field, both confidently wrong. Nobody had been careless -- the
# number was simply true when it was written.
#
# STATE.md had already written the rule down: a number belongs in prose only
# if it is evidence for a decision, is dated, and would not change by
# re-running a tool. Nothing enforced it, so it held where someone remembered
# and lapsed everywhere else. This is the enforcement.
#
# THE RULE
#
# A count bound to one of this project's moving nouns -- entries, modes,
# formats, types, rows, questions, vectors -- must have an ISO date in its own
# paragraph.
#
# Dating rather than banning, because some counts are exactly what a reader
# needs: "181 of 593 modes were recorded truncated" is the evidence for a
# pitfall and deleting it would leave the pitfall unsupported. A date turns a
# claim that rots silently into one a reader can weigh. Without it the two
# kinds are indistinguishable, which is the whole failure.
#
# WHAT IS CHECKED, AND WHY NOT EVERYTHING
#
# Two surfaces, because both claim to describe the repository AS IT IS NOW:
#
#   documents     tracked Markdown outside vendor/, data/ and dist/
#   help text     the usage heredocs tools print for --help and for no
#                 arguments, found by the delimiter convention every tool in
#                 this tree already follows (END_USAGE, USAGE, ...)
#
# A design-rationale comment in a tool is a THIRD genre and is exempt by
# default. "1251 of 1560 entries have none, so nobody will answer 1251
# questions" is not a claim about today; it is the reasoning that produced the
# tool, sitting beside the commit that made it, and a reader reaches it
# through git history rather than as current documentation. Dating all of them
# would mean either inventing measurement dates nobody took or churning fifty
# paragraphs to restate what git already records. Run --comments to check them
# anyway; measured 2026-09-02 that reports 58, and none of them is a statement
# a reader would mistake for a live figure.
#
# WHAT IS DELIBERATELY NOT FLAGGED
#
#   ~403 formats      A leading '~' is the author already marking the figure
#                     approximate, which is a different claim from a count.
#   v7.1.2-549        Version strings: the noun test never matches them.
#   mode 593          'N <noun>' only. A number AFTER the noun is an
#                     identifier, not a count.
#   generated files   Anything carrying the repository's GENERATED banner is
#                     rewritten on every render, so it cannot go stale.
#   frozen files      A file may declare 'check-numbers: frozen <date>' near
#                     the top. That is for a document which is a RECORD of a
#                     moment -- ACTION-PLAN.md is the proposal as it stood --
#                     where every number is historical by definition. The
#                     marker sits in the file rather than in this tool's
#                     exclude list so a reader opening it learns that too.
#
# TWO THINGS THIS GOT WRONG FIRST, BOTH WORTH KEEPING IN MIND
#
# It matched per paragraph and reported per line, so "772\nentries" -- a count
# whose number and noun wrapped onto different lines, and the exact sentence
# this gate was written for -- was detected and then reported as nothing.
# Findings are anchored on the match position now.
#
# And it split paragraphs on blank lines only. A Perl header is one unbroken
# run of '#' lines, so the whole header became one paragraph and a single date
# anywhere in it exempted every count below. A bare comment marker is treated
# as the blank line it visually is.
#
#-----------------------------------------------------------------------
# Generated by Claude Opus 5 on 2026-09-02

use strict;
use warnings;

use File::Basename qw(basename);
use FindBin qw($RealBin);
use Getopt::Long qw(GetOptions);

my $PROG = basename($0);
my $ROOT = "$RealBin/..";

sub usage {
    print STDERR <<"END_USAGE";

Usage: $PROG [options] [FILE...]

   --tracked         check the tracked documents and help text (the default
                     set; see below)
   --comments        also check design-rationale comments in tool source,
                     which are exempt by default
   -v, --verbose     also report which files were skipped, and why
   -h, --help        this help

   A count bound to a moving noun -- entries, modes, formats, types, rows,
   questions, vectors -- must carry an ISO date in the same paragraph, so a
   reader can tell a dated measurement from a number that has gone stale.

   Checked: tracked Markdown outside vendor/, data/ and dist/, and the usage
   text tools print for --help.

   A file that is a record of one moment may opt out by carrying the line
   'check-numbers: frozen YYYY-MM-DD' near the top, in whatever comment
   syntax it uses.

   Exit 0 clean, 1 findings, 2 usage.

END_USAGE
    return;
}

my ($tracked, $comments, $help);
my $verbose  = 0;
my $had_args = scalar @ARGV;      # house rule: no arguments means show usage

GetOptions(
    'tracked'    => \$tracked,
    'comments'   => \$comments,
    'v|verbose+' => \$verbose,
    'h|help'     => \$help,
) or do { usage(); exit 2 };

if ($help)      { usage(); exit 0 }
if (!$had_args) { usage(); exit 2 }

#-----------------------------------------------------------------------
# The patterns.

# Nouns whose counts move when a tool is re-run or an entry is added.
my $NOUN = qr/(?:entry|entries|modes?|formats?|types?|rows?|files?|
                 questions?|vectors?|dynamics?|algorithms?|open)/x;

# A number bound to one of them. The lookbehind drops '~403' (already marked
# approximate) and anything glued to a word or a dot, which is a version.
my $COUNT = qr/(?<![~\w.])\b([0-9]{1,5})\s+$NOUN\b/;

# Any ISO date in the paragraph satisfies the rule.
my $DATED = qr/\b20[0-9]{2}-[01][0-9]-[0-3][0-9]\b/;

# The two opt-outs, both read from the head of the file.
my $GENERATED = qr/GENERATED by/;
my $FROZEN    = qr/check-numbers:\s*frozen\s+(20[0-9]{2}-[01][0-9]-[0-3][0-9])/;

#-----------------------------------------------------------------------
# Paragraph grouping. Returns [start_line, text] pairs.
#
# Grouped by walking lines rather than splitting the text, for two reasons:
# the line numbers stay exact, and a BARE COMMENT MARKER counts as a
# separator, so a Perl header is many paragraphs rather than one.

sub paragraphs {
    my ($text, $first_line) = @_;
    $first_line //= 1;

    my @lines = split /\n/, $text, -1;
    my (@out, @cur);
    my $start = $first_line;

    for my $i (0 .. $#lines) {
        my $l = $lines[$i];
        my $sep = $l !~ /\S/ || $l =~ m{^\s*(?:\#|//|--)\s*$};
        if ($sep) {
            push @out, [$start, join("\n", @cur)] if @cur;
            @cur   = ();
            $start = $first_line + $i + 1;
        }
        else {
            $start = $first_line + $i unless @cur;
            push @cur, $l;
        }
    }
    push @out, [$start, join("\n", @cur)] if @cur;
    return @out;
}

#-----------------------------------------------------------------------
# The regions of a file that count as documentation.
#
# For Markdown that is the whole file. For a tool it is the usage heredoc --
# what the reader sees from --help -- located by the delimiter convention this
# tree already follows. --comments widens it to the entire source.

sub regions {
    my ($rel, $text) = @_;

    return paragraphs($text) if $rel =~ /\.md$/i;
    return paragraphs($text) if $comments;

    my @out;
    while ($text =~ /<<["']?(\w*(?:USAGE|HELP|HINT)\w*)["']?\s*;(.*?)\n\1/gs) {
        my ($body, $at) = ($2, $-[0]);
        my $before = substr($text, 0, $at);
        my $line   = 1 + (() = $before =~ /\n/g);
        push @out, paragraphs($body, $line + 1);
    }
    return @out;
}

#-----------------------------------------------------------------------
# The file set.

sub tracked_files {
    my @out = `git -C \Q$ROOT\E ls-files`;
    chomp @out;
    die "$PROG: git ls-files failed\n" if $?;
    return grep {
        !m{^(?:vendor|data|dist)/}       # generated or third-party trees
        && m{\.(?:md|pl|pm)$}
    } @out;
}

my @files = $tracked ? tracked_files() : grep { -f } @ARGV;
unless (@files) {
    print STDERR "$PROG: no files to check\n";
    exit 2;
}

#-----------------------------------------------------------------------
# Walk.

my ($checked, $skipped, $paras, $findings) = (0, 0, 0, 0);

for my $rel (@files) {
    my $path = $rel =~ m{^/} ? $rel : "$ROOT/$rel";
    open(my $fh, '<', $path) or do {
        print STDERR "$PROG: cannot read $rel: $!\n";
        next;
    };
    my $text = do { local $/; <$fh> };
    close $fh;

    my @head = split /\n/, $text;
    my $head = join "\n", @head[0 .. ($#head < 19 ? $#head : 19)];
    if ($head =~ $GENERATED) {
        $skipped++;
        print STDERR "-   skip $rel: generated\n" if $verbose;
        next;
    }
    if ($head =~ $FROZEN) {
        $skipped++;
        print STDERR "-   skip $rel: frozen $1\n" if $verbose;
        next;
    }
    $checked++;

    for my $p (regions($rel, $text)) {
        my ($start, $block) = @$p;
        $paras++;
        next unless $block =~ $COUNT;
        next if $block =~ $DATED;

        # Anchor on the MATCH POSITION, never by re-testing each line: prose
        # wraps, and a count whose number and noun land on different lines
        # matches no single line at all.
        my @lines = split /\n/, $block, -1;
        while ($block =~ /$COUNT/g) {
            $findings++;
            my $before = substr($block, 0, $-[1]);
            my $nl     = () = $before =~ /\n/g;
            my $t      = $lines[$nl] // '';
            $t =~ s/^\s+//;
            printf "%s:%d: undated count: %s\n", $rel, $start + $nl, $t;
        }
    }
}

printf STDERR "- %d file(s) checked, %d skipped, %d paragraph(s)%s\n",
    $checked, $skipped, $paras,
    ($comments ? ' (including design-rationale comments)' : '');

if ($findings) {
    printf STDERR "- %d undated count(s)\n", $findings;
    print STDERR <<"END_HINT";
-
- A count in documentation or help text needs an ISO date in the same
- paragraph, so a reader can tell a measurement from a number that has quietly
- gone stale. Either date it, or drop it and name the command that prints the
- live figure. If the whole file is a record of one moment, add near the top:
-     check-numbers: frozen YYYY-MM-DD
END_HINT
    exit 1;
}

print STDERR "- OK: every count is dated\n";
exit 0;
