#!/usr/bin/perl
#-----------------------------------------------------------------------
#
# Name: check-upstream.pl
# Description: execute data/upstream-disagreements.yaml -- fail when a
#              recorded disagreement with a vendored upstream changes state
# Category: cracking-rosetta gate
#
# Project: cracking-rosetta | Phase: upstream drift
#
#-----------------------------------------------------------------------
# METHODOLOGY AND WHY THESE CHOICES
#
# THE PROBLEM: A DISAGREEMENT NOBODY EXECUTES
#
# vendor/ holds upstream's documents byte for byte and is never edited. That
# rule is right: the re-fetch diff is the entire drift signal, and one local
# "fix" inverts it -- a re-fetch would then raise a false alarm every time
# upstream had NOT changed (our edit being reverted) and go silent on the day
# it finally did (the local value already matching). Alarm when nothing
# happened, silence when it did.
#
# So where this repository has disproved a published value, the correction
# lives in data/algorithms/ with its evidence and the two layers hold
# different strings on purpose. Measured 2026-09-02, that was true in two
# places and NOTHING connected them: the relationship was a prose paragraph
# in vendor/cynosureprime/PROVENANCE.md, which no program reads.
#
# THREE FAILURE MODES, AND THE THIRD IS THE POINT
#
#   1. upstream no longer matches what the register recorded -- upstream
#      moved, go look. Today this is only caught if a human reads the
#      re-fetch diff.
#   2. our side no longer matches -- somebody re-seeded upstream's value over
#      a proven one. That is exactly how the bad e607 vector arrived here in
#      the first place, and the prose note was the only guard against it.
#   3. the two have CONVERGED -- upstream fixed it, so the record is spent and
#      should be deleted. A register with no way to shrink becomes a
#      graveyard, and this is the state change nothing could detect at all:
#      today it looks exactly like "nothing happened".
#
# (3) is what turns a re-fetch that changes nothing into a PASSING TEST rather
# than an absence of evidence.
#
# WHY THIS IS NOT PART OF validate.pl
#
# validate.pl answers one question -- is a curated entry well formed, and does
# every identifier it names exist in the committed inventories. It reads
# data/algorithms and data/tools and deliberately nothing else. This reads
# vendor/, which is a different layer with a different rule attached to it
# (never edit), and it is the natural thing to run straight after
# tools/fetch-upstream.sh. Two gates, two questions.
#
# WHY THE KINDS ARE HARD-CODED
#
# A register that needs a plugin architecture has stopped being a list of
# specific evidenced disagreements. There are three kinds, each with a fixed
# pair of accessors written out below, and adding a fourth should feel
# expensive enough that somebody asks whether the disagreement is real first.
#
# The third was added 2026-09-02 and paid that price: the alias assertion in
# catalog-index-set checks the NAME and the HASHCAT MAPPING of every shared
# index, and it passed while hashpipe and mdxfind were reporting different
# ITERATION SUFFIXES for the same computation. The suffix is not in
# HASH_TYPES.md at all, so no amount of checking that file could have found
# it. See check_john_map.
#
# WHAT DID NOT GENERALIZE, RECORDED RATHER THAN PAPERED OVER
#
# The register was sketched as (upstream publishes X, we assert Y) and the
# second seed record does not fit that shape: a catalog that lags a binary is
# a SET DIFFERENCE, not one string against another, and forcing it into
# publishes:/we_assert: would have meant writing a thousand indices into a
# field. What did generalize is the core -- id, kind, upstream, inventory,
# because, recorded -- and the three failure modes, which both kinds have.
#
# THE SECOND RECORD ALSO ABSORBS A FICTIONAL TOOL
#
# CLAUDE.md records hashpipe as an ALIAS of mdxfind rather than a fourth
# column "until that stops being true", and says tools/extract-hashpipe.pl
# exists to detect the divergence. Verified 2026-09-02: it does not exist, so
# the documented detector was a human remembering to read a diff. The
# catalog-index-set check is that detector -- on every shared index the
# catalog and the binary must agree on the name and on the hashcat mapping.
#
# ONE ORDERING RULE THAT MATTERS
#
# When upstream fixes a value, mode 1 and mode 3 are BOTH true: upstream no
# longer matches what we recorded, and the two sides now agree. Convergence is
# reported alone, because "delete this record" is the whole action and
# "upstream moved" underneath it would send a reader looking for a second
# problem that is not there.
#
#-----------------------------------------------------------------------
# Generated by Claude Opus 5 on 2026-09-02

use strict;
use warnings;

use File::Basename qw(basename);
use FindBin qw($RealBin);
use Getopt::Long qw(GetOptions);
use YAML::XS ();

my $PROG = basename($0);
my $ROOT = "$RealBin/..";

sub usage {
    print STDERR <<"END_USAGE";

Usage: $PROG --check [options]

   --check           execute the register (the gate; this or --list is
                     required, so a bare invocation cannot look like a pass)
   --list            print the register and what each record claims, and
                     check nothing
   --register FILE   the register (default: data/upstream-disagreements.yaml)
   --algorithms DIR  curated entries (default: data/algorithms). Only a
                     test harness has any reason to move these; see
                     tools/test-check-upstream.pl
   -v, --verbose     say what each record resolved to, not just the failures
   -h, --help        this help

   Executes data/upstream-disagreements.yaml: a list of specific, evidenced
   places where this repository disagrees with a vendored upstream document.
   Each record fails three ways -- upstream moved, our side moved, or the two
   converged and the record is spent and should be deleted.

   Run it after tools/fetch-upstream.sh, and in CI.

   Exit 0 clean, 1 a record changed state, 2 usage or an unreadable file.

END_USAGE
    return;
}

my ($check, $list, $regfile, $algdir, $help);
my $verbose  = 0;
my $had_args = scalar @ARGV;      # house rule: no arguments means show usage

GetOptions(
    'check'      => \$check,
    'list'       => \$list,
    'register=s'   => \$regfile,
    'algorithms=s' => \$algdir,
    'v|verbose+' => \$verbose,
    'h|help'     => \$help,
) or do { usage(); exit 2 };

if ($help || !$had_args) { usage(); exit($help ? 0 : 2) }
if (!$check && !$list)   { usage(); exit 2 }

$regfile //= "$ROOT/data/upstream-disagreements.yaml";
$algdir  //= "$ROOT/data/algorithms";

#-----------------------------------------------------------------------
# Findings. Each carries the record id, so a failure names the record a reader
# has to go and edit rather than only the value that moved.

my @findings;
sub finding {
    my ($id, $mode, $fmt, @args) = @_;
    push @findings, { id => $id, mode => $mode, msg => sprintf($fmt, @args) };
    return;
}

sub fatal {
    my ($fmt, @args) = @_;
    printf STDERR "$PROG: $fmt\n", @args;
    exit 2;
}

sub slurp_yaml {
    my ($path) = @_;
    -r $path or fatal("cannot read %s", $path);
    my $d = eval { YAML::XS::LoadFile($path) };
    fatal("%s did not parse as YAML: %s", $path, $@ // 'unknown error')
        if !$d || $@;
    return $d;
}

#-----------------------------------------------------------------------
# Parse a vendored HASH_TYPES.md catalog.
#
# Read RAW. The file is upstream's and contains non-ASCII prose (an em-dash in
# its own title); decoding and re-encoding it is how a byte-for-byte copy stops
# being one, and nothing here needs the characters, only the bytes.
#
# A row is:  | e607 | SHA1MD5SALTPASSPEPPER | n/a | `hash[:salt]:password` |
#
# The example cell is matched greedily up to the LAST pipe on the line, so a
# salt containing a pipe cannot silently truncate the vector we compare. The
# index cell must look like eN, which skips the header, the separator row and
# any other table in the document.

sub parse_catalog {
    my ($path) = @_;
    open my $fh, '<:raw', $path or fatal("cannot read %s: %s", $path, $!);
    my (%by_index, %by_name);
    while (my $line = <$fh>) {
        chomp $line;
        next unless $line =~ /^\|([^|]*)\|([^|]*)\|([^|]*)\|(.*)\|\s*$/;
        my ($idx, $name, $modes, $example) = ($1, $2, $3, $4);
        for ($idx, $name, $modes, $example) { s/^\s+//; s/\s+$// }
        next unless $idx =~ /^e\d+$/;
        $example =~ s/^`//;                       # the cell is code-quoted
        $example =~ s/`$//;
        my $rec = {
            index   => $idx,
            name    => $name,
            modes   => $modes,
            example => $example,
        };
        $by_index{$idx} = $rec;
        # A name can in principle repeat; keep the first, which is the lowest
        # index, matching the tie-break rule the rest of this repository uses.
        $by_name{$name} //= $rec;
    }
    close $fh;
    fatal("%s yielded no catalog rows -- has its table format changed?", $path)
        unless %by_index;
    return (\%by_index, \%by_name);
}

# The catalog writes 'n/a' where a type has no hashcat mapping; the inventory
# writes an absent list. Normalize both to one comparable string.
sub norm_modes_catalog {
    my ($s) = @_;
    return '' if !defined $s || $s eq '' || lc $s eq 'n/a';
    return $s;
}
sub norm_modes_inventory {
    my ($rec) = @_;
    return join(',', @{ $rec->{hashcat_modes} || [] });
}

#-----------------------------------------------------------------------
# The two kinds.

# catalog-row-value: one catalog row publishes a value this repository has
# disproved, and the correction lives on a data/algorithms entry.
#
# Our side is the entry's own vectors, rendered in the catalog's own
# serialization -- `hash:password`, where the entry's hash field already
# carries any salt. That is a comparison of the two strings as published,
# not of a digest we re-derive, so nothing here can launder a value.
sub check_row_value {
    my ($r) = @_;
    my $id = $r->{id};

    for my $k (qw(key entry publishes we_assert)) {
        finding($id, 'malformed', "record has no %s:", $k), return
            unless defined $r->{$k} && length $r->{$k};
    }

    my ($by_index, $by_name) = parse_catalog("$ROOT/$r->{upstream}");
    my $row = $by_name->{ $r->{key} };

    unless ($row) {
        finding($id, 'upstream-moved',
            "%s no longer has a row for %s. Upstream may have renamed or "
          . "retired the type; re-measure and update or delete this record.",
            $r->{upstream}, $r->{key});
        return;
    }

    my $live_up = $row->{example};

    # Our side. The entry is the authority; a record naming one that does not
    # exist is a broken register, not a passing one.
    my $epath = "$algdir/$r->{entry}.yaml";
    unless (-r $epath) {
        finding($id, 'malformed',
            "entry: names '%s', which is not a file in %s",
            $r->{entry}, $algdir);
        return;
    }
    my $entry = slurp_yaml($epath);
    my @ours = map { join(':', $_->{hash} // '', $_->{pass} // '') }
               @{ $entry->{vectors} || [] };

    # 3 first: convergence is reported alone. See the ordering note above.
    if (grep { $_ eq $live_up } @ours) {
        finding($id, 'converged',
            "%s now publishes the value %s asserts (%s). Upstream fixed it -- "
          . "delete this record from the register and drop the 'known stale "
          . "rows' paragraph for it in vendor/cynosureprime/PROVENANCE.md.",
            $r->{upstream}, $r->{entry}, $live_up);
        return;
    }

    # 1: upstream moved.
    if ($live_up ne $r->{publishes}) {
        finding($id, 'upstream-moved',
            "%s now publishes\n      %s\n    for %s, but this record was "
          . "written against\n      %s\n    Upstream changed it to something "
          . "that is still not our value: re-measure before touching %s.",
            $r->{upstream}, $live_up, $r->{key}, $r->{publishes}, $r->{entry});
    }

    # 2: our side moved.
    unless (grep { $_ eq $r->{we_assert} } @ours) {
        finding($id, 'ours-moved',
            "%s no longer carries the vector this record asserts\n      %s\n"
          . "    It has %s. If a re-seed overwrote a proven value with "
          . "upstream's, that is the defect this record exists to catch; if "
          . "the entry was corrected again, update we_assert: and say why in "
          . "because:.",
            $r->{entry}, $r->{we_assert},
            @ours ? "\n      " . join("\n      ", @ours) : "no vectors at all");
    }

    # And the generated layer. data/tools/*.yaml is generated FROM the
    # vendored catalog, so it necessarily carries upstream's value. Checking
    # it is what joins the two layers that were previously unconnected: if it
    # stops matching, either the extractor changed or a GENERATED file was
    # hand-edited, and both are worth hearing about here.
    my $inv = slurp_yaml("$ROOT/$r->{inventory}");
    my ($ir) = grep { ($_->{name} // '') eq $r->{key} } @{ $inv->{types} || [] };
    if (!$ir) {
        finding($id, 'inventory-moved',
            "%s has no type named %s", $r->{inventory}, $r->{key});
    }
    elsif (($ir->{example_vector} // '') ne $live_up) {
        finding($id, 'inventory-moved',
            "%s carries\n      %s\n    for %s, but the catalog it is "
          . "generated from now says\n      %s\n    Re-run "
          . "tools/extract-mdxfind.pl, or find out who edited a GENERATED "
          . "file.",
            $r->{inventory}, $ir->{example_vector} // '(none)', $r->{key},
            $live_up);
    }

    return;
}

# catalog-index-set: the vendored catalog does not cover every type the local
# binary has. The disagreement is a set difference rather than a value, and
# the record also asserts the agreement that lets hashpipe be an ALIAS of
# mdxfind rather than a fourth column.
sub check_index_set {
    my ($r) = @_;
    my $id = $r->{id};

    finding($id, 'malformed', "record has no absent_upstream:"), return
        unless ref $r->{absent_upstream} eq 'ARRAY';

    my ($by_index) = parse_catalog("$ROOT/$r->{upstream}");
    my $inv = slurp_yaml("$ROOT/$r->{inventory}");
    my %inv_by_index = map { ($_->{index} // '') => $_ } @{ $inv->{types} || [] };

    my @absent  = sort grep { !$by_index->{$_}    } keys %inv_by_index;
    my @extra   = sort grep { !$inv_by_index{$_}  } keys %$by_index;
    my $recorded = join(',', sort @{ $r->{absent_upstream} });
    my $live     = join(',', @absent);

    # 3 first, again: an empty difference is the record being spent.
    if (!@absent && !@extra) {
        finding($id, 'converged',
            "%s now covers every type in %s. Upstream caught up -- delete "
          . "this record and the matching paragraph in "
          . "vendor/cynosureprime/PROVENANCE.md.",
            $r->{upstream}, $r->{inventory});
        return;
    }

    # 1 and 2 are not separable here: either side moving changes the same set.
    # Say which direction it moved rather than pretending otherwise.
    if ($live ne $recorded) {
        my %rec = map { $_ => 1 } @{ $r->{absent_upstream} };
        my @new  = grep { !$rec{$_} } @absent;
        my %now  = map { $_ => 1 } @absent;
        my @gone = grep { !$now{$_} } sort @{ $r->{absent_upstream} };
        finding($id, 'set-moved',
            "the types %s has and %s lacks are now [%s]; this record was "
          . "written against [%s].%s%s Re-measure and update "
          . "absent_upstream:, or delete the record if it is spent.",
            $r->{inventory}, $r->{upstream}, $live, $recorded,
            @new  ? sprintf(' Newly absent upstream: %s.', join(',', @new))  : '',
            @gone ? sprintf(' Upstream picked up: %s.',   join(',', @gone))  : '');
    }

    # Upstream having a type the local binary does not is the other direction
    # entirely: the binary is behind, or the catalog is describing a different
    # program.
    if (@extra) {
        finding($id, 'upstream-ahead',
            "%s lists %d index/indices that %s has no type for: %s. The "
          . "local binary is behind the catalog, which is the reverse of what "
          . "this record describes.",
            $r->{upstream}, scalar @extra, $r->{inventory},
            join(',', @extra[0 .. ($#extra > 9 ? 9 : $#extra)])
              . (@extra > 10 ? sprintf(' ... (+%d)', @extra - 10) : ''));
    }

    # The alias assertion. On every shared index the two must agree on the
    # name and on the hashcat mapping; this is the divergence detector
    # CLAUDE.md attributes to a tools/extract-hashpipe.pl that does not exist.
    my (@name_bad, %mlive);
    for my $i (sort keys %$by_index) {
        my $ir = $inv_by_index{$i} or next;
        my $cr = $by_index->{$i};
        push @name_bad, sprintf('%s (catalog %s / binary %s)',
                                $i, $cr->{name}, $ir->{name} // '(none)')
            if ($ir->{name} // '') ne $cr->{name};
        my ($cm, $im) = (norm_modes_catalog($cr->{modes}),
                         norm_modes_inventory($ir));
        # kept as the two normalized strings, not as a formatted sentence:
        # a record is compared against these, and re-parsing a message is how
        # a check starts agreeing with itself rather than with the data
        $mlive{$i} = { publishes => $cm, we_assert => $im } if $cm ne $im;
    }
    # A NAME disagreement is the alias rule expiring outright and has no
    # recorded-exception path: the two tools would be calling different things
    # by one identifier, which is the thing this repository joins on.
    if (@name_bad) {
        finding($id, 'alias-broken',
            "%s and %s disagree on the name of %d shared index/indices: %s. "
          . "CLAUDE.md records hashpipe as an alias of mdxfind 'until that "
          . "stops being true'. This is that.",
            $r->{upstream}, $r->{inventory}, scalar @name_bad,
            join('; ', @name_bad[0 .. ($#name_bad > 4 ? 4 : $#name_bad)])
              . (@name_bad > 5 ? sprintf(' ... (+%d)', @name_bad - 5) : ''));
    }

    # A HASHCAT MAPPING disagreement can be recorded, because the two sides
    # are not answering the same question. mdxfind's -h prints, per type,
    # every mode that type can serve; hashpipe's catalog column is generated
    # by INVERTING Maphashcat[], which maps each hashcat mode to ONE canonical
    # index. Where several synonymous types can serve a mode, the two spellings
    # differ without either being wrong -- and that is a fact worth carrying in
    # the record rather than a reason to fail every build. An UNRECORDED one is
    # still the alias rule expiring.
    my %mrec = map { ($_->{index} // '') => $_ }
               @{ ref $r->{mode_differs} eq 'ARRAY' ? $r->{mode_differs} : [] };
    for my $i (sort keys %mlive) {
        unless ($mrec{$i}) {
            finding($id, 'alias-broken',
                "%s and %s disagree on the hashcat mapping of %s, which this "
              . "record does not list: catalog [%s], binary [%s]. CLAUDE.md "
              . "records hashpipe as an alias of mdxfind 'until that stops "
              . "being true'. Measure it, then add it to mode_differs: or fix "
              . "the inventory.",
                $r->{upstream}, $r->{inventory}, $i,
                $mlive{$i}{publishes}, $mlive{$i}{we_assert});
            next;
        }
        my $e = $mrec{$i};
        finding($id, 'upstream-moved',
            "%s: this record says the catalog publishes [%s], but it now "
          . "publishes [%s].", $i, $e->{publishes} // '(unset)',
            $mlive{$i}{publishes})
            if ($e->{publishes} // '') ne $mlive{$i}{publishes};
        finding($id, 'ours-moved',
            "%s: this record says the inventory has [%s], but it now has "
          . "[%s]. If that was a re-extraction from a different binary, say "
          . "which one.", $i, $e->{we_assert} // '(unset)',
            $mlive{$i}{we_assert})
            if ($e->{we_assert} // '') ne $mlive{$i}{we_assert};
    }
    for my $i (sort keys %mrec) {
        next if $mlive{$i};
        finding($id, 'row-converged',
            "%s: this record lists a hashcat-mapping disagreement here, but "
          . "the two now agree. Drop that row from mode_differs:.", $i);
    }

    if ($verbose) {
        my $shared = scalar grep { $inv_by_index{$_} } keys %$by_index;
        printf STDERR "-   %s: %d catalog row(s), %d inventory type(s), "
                    . "%d shared, %d name mismatch(es), %d hashcat-mapping "
                    . "mismatch(es) of which %d recorded\n",
            $id, scalar(keys %$by_index), scalar(keys %inv_by_index),
            $shared, scalar(@name_bad), scalar(keys %mlive),
            scalar(grep { $mrec{$_} } keys %mlive);
    }
    return;
}

#-----------------------------------------------------------------------
# john-map-agreement: hashpipe's john_map.h states, for a john dynamic, the
# hashpipe type that reproduces john's own test vector. This repository states
# the same thing independently, from the LOCAL john and the LOCAL mdxfind. On
# every dynamic both name, the two must agree -- except for a recorded set,
# which must be exactly as recorded.
#
# WHY THIS KIND EXISTS, when adding one is supposed to feel expensive
#
# catalog-index-set already carries the alias assertion, and it checks the
# NAME and the HASHCAT MAPPING of every shared index. It passed on 2026-09-02
# while hashpipe and mdxfind were reporting DIFFERENT ITERATION SUFFIXES for
# the same computation -- mdxfind says SHA256RAWx02 where hashpipe says
# SHA256RAWx01, reproduced on five types with the same hash and the same
# plaintext. CLAUDE.md is explicit that the suffix is part of the identity, so
# that is the alias rule breaking, and nothing could have seen it: the suffix
# is not in HASH_TYPES.md at all. It is in john_map.h, which nothing read.
#
# ONLY THE FIRST TABLE IS READ, AND THAT IS NOT AN OVERSIGHT
#
# v1.189 added a second table, JohnMapLocal[]. Upstream's own comment says its
# NUMBERING IS LOCAL to the machine that generated it and that it is consulted
# on input only. Measured here 2026-09-02, that warning is correct and
# demonstrable: upstream's dynamic_1013 is MD5PASSSALT and its dynamic_1014 is
# POSTGRESQL, while this host's john has them the other way round. Reading
# that table would import another machine's dynamic.conf numbering as though
# it were a fact about an algorithm.
sub parse_john_map {
    my ($path) = @_;
    open my $fh, '<:raw', $path or fatal("cannot read %s: %s", $path, $!);
    my (%row, $in, $done);
    while (my $line = <$fh>) {
        next if $done;
        # Enter on the first table only, and stop at its closing brace, so
        # JohnMapLocal[] below it is never read.
        $in = 1 if !$in && $line =~ /\bJohnMap\s*\[\s*\]\s*=/;
        next unless $in;
        if ($line =~ /^\s*\}\s*;/) { $done = 1; next }
        $row{$1} = $2 if $line =~ /\{\s*"(dynamic_\d+)"\s*,\s*"([^"]+)"\s*\}/;
    }
    close $fh;
    fatal("%s yielded no JohnMap[] rows -- has its shape changed?", $path)
        unless %row;
    return \%row;
}

# Upstream writes MD5x02. This repository writes type "MD5" with
# `iterations: 2` beside it (CLAUDE.md, "Iteration suffix is identity"), so
# the two halves are compared separately. An absent iterations: means 1,
# which is what an unsuffixed upstream name means too.
sub split_iter {
    my ($t) = @_;
    return ($1, $2 + 0) if $t =~ /^(.*?)x(\d+)$/;
    return ($t, 1);
}
# CLAUDE.md, "Name separator drift": HAV128_4 and HAV128-4 are one name.
sub norm_type { my $s = uc($_[0] // ''); $s =~ s/[^A-Z0-9]//g; return $s }

sub check_john_map {
    my ($r) = @_;
    my $id = $r->{id};

    finding($id, 'malformed', "record has no differs: list"), return
        unless ref $r->{differs} eq 'ARRAY';

    my $up = parse_john_map("$ROOT/$r->{upstream}");

    # This repository's side: every entry naming a john dynamic, with the
    # mdxfind type and iteration count it also names. The directory comes from
    # $algdir, not from inventory:, so --algorithms overrides it the way it
    # does for catalog-row-value -- which is what lets the gate be tested
    # against a fixture tree instead of the real corpus.
    my $dir = $algdir;
    opendir(my $dh, $dir) or fatal("cannot read %s: %s", $dir, $!);
    my @files = sort grep { /\.yaml$/ } readdir $dh;
    closedir $dh;
    my %ours;
    for my $file (@files) {
        my $d = eval { YAML::XS::LoadFile("$dir/$file") } or next;
        next unless ref $d eq 'HASH';
        next if ($d->{status} // '') eq 'merged';
        my $j = $d->{tools}{john} or next;
        my @dyn = grep { /^dynamic_\d+$/ } @{ $j->{cpu} || [] };
        next unless @dyn;
        my $mx = $d->{tools}{mdxfind} || {};
        next unless @{ $mx->{types} || [] };
        push @{ $ours{$_} }, { id   => $d->{id},
                               types => $mx->{types},
                               iter  => $mx->{iterations} // 1 } for @dyn;
    }

    # The live disagreement set, keyed by john dynamic. A dynamic several
    # entries name agrees if ANY of them matches: the tools publish more than
    # one identifier for one computation and each entry is a different name
    # for it.
    my (%live, $shared);
    for my $dy (sort keys %$up) {
        my $rows = $ours{$dy} or next;
        $shared++;
        my ($ubase, $uiter) = split_iter($up->{$dy});
        my $ok = 0;
        for my $row (@$rows) {
            for my $ty (@{ $row->{types} }) {
                $ok = 1 if norm_type($ty) eq norm_type($ubase)
                        && $row->{iter} == $uiter;
            }
        }
        next if $ok;
        my $row = $rows->[0];
        $live{$dy} = sprintf('%s x%02d', join(',', @{ $row->{types} }),
                             $row->{iter});
    }

    my %rec = map { ($_->{john} // '') => $_ } @{ $r->{differs} };

    # 3 first: an empty difference is the record being spent.
    unless (%live) {
        finding($id, 'converged',
            "every one of the %d john dynamic(s) that %s and %s both name now "
          . "agrees on the hashpipe type AND the iteration count. Upstream and "
          . "this repository have converged -- delete this record and the "
          . "matching paragraph in vendor/cynosureprime/PROVENANCE.md.",
            $shared, $r->{upstream}, $r->{inventory});
        return;
    }

    # 1: upstream moved, or a disagreement appeared that is not recorded.
    for my $dy (sort keys %live) {
        unless ($rec{$dy}) {
            finding($id, 'set-moved',
                "%s and %s disagree about %s, which this record does not "
              . "list: upstream publishes '%s', we assert '%s'. Either "
              . "upstream changed a row or this repository did. Measure it, "
              . "then add it to differs: or fix the entry.",
                $r->{upstream}, $r->{inventory}, $dy, $up->{$dy}, $live{$dy});
            next;
        }
        my $e = $rec{$dy};
        finding($id, 'upstream-moved',
            "%s: this record says upstream publishes '%s', but it now "
          . "publishes '%s'.", $dy, $e->{publishes} // '(unset)', $up->{$dy})
            if ($e->{publishes} // '') ne $up->{$dy};
        # 2: our side moved -- a re-seed to upstream's value, or the entry
        # changed under us.
        finding($id, 'ours-moved',
            "%s: this record says we assert '%s', but the entries now say "
          . "'%s'. If that was a re-seed from upstream, it undid a measured "
          . "correction.", $dy, $e->{we_assert} // '(unset)', $live{$dy})
            if ($e->{we_assert} // '') ne $live{$dy};
    }

    # A recorded disagreement that is no longer live: partly spent.
    for my $dy (sort keys %rec) {
        next if $live{$dy};
        finding($id, 'row-converged',
            "%s: this record lists a disagreement here, but the two now "
          . "agree. Drop that row from differs:.", $dy);
    }

    if ($verbose) {
        printf STDERR "-   %s: %d JohnMap[] row(s), %d shared with the "
                    . "entries, %d disagree, %d recorded\n",
            $id, scalar(keys %$up), $shared, scalar(keys %live),
            scalar(keys %rec);
    }
    return;
}

my %KIND = (
    'catalog-row-value'  => \&check_row_value,
    'catalog-index-set'  => \&check_index_set,
    'john-map-agreement' => \&check_john_map,
);

#-----------------------------------------------------------------------
# Run.

my $reg = slurp_yaml($regfile);
my $records = $reg->{disagreements};
fatal("%s has no 'disagreements:' list", $regfile)
    unless ref $records eq 'ARRAY';

if ($list) {
    for my $r (@$records) {
        printf "%s  [%s]\n", $r->{id} // '(no id)', $r->{kind} // '(no kind)';
        printf "  upstream:  %s\n", $r->{upstream}  // '-';
        printf "  inventory: %s\n", $r->{inventory} // '-';
        printf "  entry:     %s\n", $r->{entry} if defined $r->{entry};
        printf "  key:       %s\n", $r->{key}   if defined $r->{key};
        printf "  publishes: %s\n", $r->{publishes} if defined $r->{publishes};
        printf "  we assert: %s\n", $r->{we_assert} if defined $r->{we_assert};
        printf "  absent:    %s\n", join(', ', @{ $r->{absent_upstream} })
            if ref $r->{absent_upstream} eq 'ARRAY';
        printf "  recorded:  %s\n", $r->{recorded} // '-';
        print  "\n";
    }
    exit 0;
}

my $n = 0;
for my $r (@$records) {
    my $id = $r->{id} // '(no id)';
    $n++;

    # The core every kind needs. A record missing it is a defect in the
    # register itself and fails like any other finding, rather than being
    # skipped into a false pass.
    my @missing = grep { !defined $r->{$_} || !length $r->{$_} }
                  qw(id kind upstream inventory because recorded);
    if (@missing) {
        finding($id, 'malformed', "record is missing: %s", join(', ', @missing));
        next;
    }
    for my $f (qw(upstream inventory)) {
        next if -r "$ROOT/$r->{$f}";
        finding($id, 'malformed', "%s: names '%s', which is not readable",
                $f, $r->{$f});
    }
    next if grep { $_->{id} eq $id && $_->{mode} eq 'malformed' } @findings;

    my $fn = $KIND{ $r->{kind} };
    unless ($fn) {
        finding($id, 'malformed',
            "kind '%s' is not one this tool implements (%s). The kinds are "
          . "hard-coded on purpose; adding one is a code change with a "
          . "reason attached.",
            $r->{kind}, join(', ', sort keys %KIND));
        next;
    }
    $fn->($r);
}

#-----------------------------------------------------------------------
# Report.

for my $f (@findings) {
    printf STDERR "- %s [%s]: %s\n", $f->{id}, $f->{mode}, $f->{msg};
}

printf STDERR "- %d record(s) in %s\n", $n, $regfile if $verbose;
printf STDERR "- %s\n", @findings
    ? sprintf('FAILED: %d record(s) changed state', scalar @findings)
    : sprintf('OK: %d recorded disagreement(s), all still exactly as recorded',
              $n);

exit(@findings ? 1 : 0);
