#!/usr/bin/perl
#-----------------------------------------------------------------------
#
# Name: curate.pl
# Description: work through the decisions only a human can make, one question
#              at a time, and write the answers down where they can be applied
# Category: cracking-rosetta curator
#
# Project: cracking-rosetta | Phase: 6 - the human curation loop
#
#-----------------------------------------------------------------------
# METHODOLOGY AND WHY THESE CHOICES
#
# WHAT IS ACTUALLY LEFT
#
# The machine passes have gone as far as they go. 265 expressions were proven
# by round-trip; the remainder is a long tail of 289 distinct unguessable
# mdxfind type names across 306 entries -- roughly one construction per entry,
# with no lever left to pull. Meanwhile 772 entries have no category:, which
# is the sheet's own 'class' column that was defined in 2023 and never filled.
#
# None of that is a tooling problem any more. It is a person knowing things,
# and the bottleneck is how expensive it is to ASK them. Opening 772 files to
# type one word in each is the expensive way.
#
# SO THIS IS A QUESTION QUEUE, NOT AN EDITOR
#
# One question at a time, with every fact the repository already knows printed
# above it, and an answer that is usually one keystroke. Questions are grouped
# by kind so a session can be "twenty categories" rather than a lucky dip, and
# --limit means ten minutes is a useful amount of time to spend.
#
# ANSWERS GO TO A JOURNAL, NOT INTO THE DATA
#
# Nothing is written to data/algorithms while you are answering. Every answer
# is appended to a plain TSV as it is given, so a crash, a Ctrl-C or a change
# of mind costs nothing, and re-running skips what is already answered.
#
# --apply then writes the journal into the entries, and deliberately writes
# only the two kinds it can write honestly:
#
#   category    a closed vocabulary; the answer IS the value.
#   denotation  free text plus source: human, which is exactly what the field
#               is for -- it is untiered because nothing can round-trip it.
#
# The other kinds are recorded and REPORTED, never applied. A duplicate merge
# needs an id-resolution policy this repository has not decided. An expression
# must be proven by john before it is written, never accepted because someone
# typed it. Recording a human's belief and acting on it are different things,
# and this repository's whole premise is the distinction.
#
# --report PRINTS THE JOURNAL AS MARKDOWN
#
# Because the other half of this workflow is handing the answers to someone --
# or something -- that will act on them. The report is grouped by kind and
# reads as prose, so it can be pasted into a conversation without editing.
#
# DEPENDENCIES
#
#   perl, YAML::XS, tools/lib/RosettaEmit.pm. No terminal library: answers are
#   typed and entered, because Term::ReadKey is not core and this repository
#   has exactly one non-core dependency.
#
#-----------------------------------------------------------------------
# Generated by Claude Opus 5 on 2026-08-30

use strict;
use warnings;

use File::Basename qw(basename);
use FindBin qw($RealBin);
use Getopt::Long qw(GetOptions);
use YAML::XS ();

use lib "$RealBin/lib";
use RosettaEmit qw(emit_entry);

my $PROG = basename($0);
my $ROOT = "$RealBin/..";
my $TODAY = do { my @t = localtime; sprintf '%04d-%02d-%02d',
                 $t[5] + 1900, $t[4] + 1, $t[3] };

my @KINDS = qw(category denotation duplicate unproven token);

sub usage {
    print STDERR <<"END_USAGE";

Usage: $PROG [options]

   --kind K          only questions of this kind (repeatable). One of:
                       category    which axis does this entry sit on (772 open)
                       denotation  what do people call this, when there is no
                                   provable expression
                       duplicate   two entries propose a merge; which survives
                       unproven    a recorded expression that does not
                                   reproduce its own vector
                       token       what does this mdxfind name fragment mean
   --limit N         stop after N questions (default 20; 0 for no limit)
   --only ID         just this entry
   --journal FILE    where answers live (default tmp/curation.tsv)
   --min-group N     'token' questions covering at least N entries (default 2)
   --list            print the queue and the counts; ask nothing
   --again           re-ask questions previously skipped
   --report          print the journal as Markdown and exit
   --apply           write the journal's category and denotation answers into
                     data/algorithms; report the rest
   -v, --verbose
   -h, --help

   Answering writes nothing but the journal. Exit 0 success, 1 error, 2 usage.

END_USAGE
    return;
}

my ($algdir, $journal, $help, $list, $report, $apply, $again, $only);
my @kind;
my $limit     = 20;
my $min_group = 2;
my $verbose   = 0;

GetOptions(
    'algorithms=s' => \$algdir,
    'journal=s'    => \$journal,
    'kind=s'       => \@kind,
    'only=s'       => \$only,
    'limit=i'      => \$limit,
    'min-group=i'  => \$min_group,
    'list'         => \$list,
    'again'        => \$again,
    'report'       => \$report,
    'apply'        => \$apply,
    'v|verbose+'   => \$verbose,
    'h|help'       => \$help,
) or do { usage(); exit 2 };

if ($help) { usage(); exit 0 }

$algdir  //= "$ROOT/data/algorithms";
$journal //= "$ROOT/tmp/curation.tsv";

my %want_kind = map { $_ => 1 } @kind;
for my $k (keys %want_kind) {
    next if grep { $_ eq $k } @KINDS;
    print STDERR "$PROG: unknown --kind '$k'; known: @KINDS\n";
    exit 2;
}

#-----------------------------------------------------------------------
# The journal.

sub read_journal {
    my %seen;   # "kind\0target" -> { answer, note, when }
    my @rows;
    return (\%seen, \@rows) unless -r $journal;
    open my $fh, '<', $journal or return (\%seen, \@rows);
    while (my $l = <$fh>) {
        chomp $l;
        next if $l =~ /^\s*(?:#|$)/;
        my ($when, $kind, $target, $answer, $note) = split /\t/, $l, 5;
        next unless defined $answer;
        my $r = { when => $when, kind => $kind, target => $target,
                  answer => $answer, note => ($note // '') };
        $seen{"$kind\0$target"} = $r;
        push @rows, $r;
    }
    close $fh;
    return (\%seen, \@rows);
}

sub append_journal {
    my ($kind, $target, $answer, $note) = @_;
    my $new = !-e $journal;
    open my $fh, '>>', $journal
        or die "$PROG: cannot append to $journal: $!\n";
    if ($new) {
        print {$fh} "# cracking-rosetta curation journal\n"
                  . "# when\tkind\ttarget\tanswer\tnote\n"
                  . "# Answers only. Nothing here is in data/algorithms until\n"
                  . "# tools/curate.pl --apply writes the kinds it can write.\n";
    }
    $_ = defined $_ ? $_ : '' for $answer, $note;
    s/\t/ /g, s/\n/ /g for $answer, $note;
    printf {$fh} "%s\t%s\t%s\t%s\t%s\n", $TODAY, $kind, $target, $answer, $note;
    close $fh;
    return;
}

my ($answered, $rows) = read_journal();

#-----------------------------------------------------------------------
# Load the corpus.

opendir(my $dh, $algdir)
    or do { print STDERR "$PROG: cannot read $algdir: $!\n"; exit 1 };
my @files = sort grep { /\.yaml$/ } readdir $dh;
closedir $dh;

my (%entry, %path);
for my $f (@files) {
    my $p = "$algdir/$f";
    my $e = eval { YAML::XS::LoadFile($p) } or next;
    next unless $e->{id};
    $entry{ $e->{id} } = $e;
    $path{  $e->{id} } = $p;
}

#-----------------------------------------------------------------------
# --report: the journal as something you can paste into a conversation.

if ($report) {
    unless (@$rows) {
        print "No curation answers recorded yet ($journal).\n";
        exit 0;
    }
    my %by;
    push @{ $by{ $_->{kind} } }, $_ for @$rows;
    printf "# Curation answers\n\nFrom `%s`, %d answer(s).\n",
        $journal, scalar @$rows;
    for my $k (@KINDS) {
        my @r = grep { ($_->{answer} // '') ne '(skipped)' } @{ $by{$k} || [] };
        next unless @r;
        printf "\n## %s (%d)\n\n", $k, scalar @r;
        for my $r (@r) {
            printf "- **%s** -> `%s`%s\n", $r->{target}, $r->{answer},
                (length $r->{note} ? "  \n  $r->{note}" : '');
        }
    }
    my @skipped = grep { ($_->{answer} // '') eq '(skipped)' } @$rows;
    printf "\n## skipped (%d)\n\n%s\n", scalar @skipped,
        join(', ', map { $_->{target} } @skipped) if @skipped;
    exit 0;
}

#-----------------------------------------------------------------------
# Build the queue.
#
# One sub per kind. Each returns a list of questions:
#   { kind, target, prompt, context => [lines], options => [[key,label],...],
#     free => 1 }

my @CATEGORY = (
    ['1', 'primitive',   'one hash function over the plaintext'],
    ['2', 'composite',   'a construction over several'],
    ['3', 'iterated',    'another entry applied N times'],
    ['4', 'encoding',    "another entry's digest written differently"],
    ['5', 'application', "a product's use of a computation another entry names"],
    ['6', 'protocol',    'a challenge-response or wire format'],
    ['7', 'kdf',         'a deliberately slow derivation'],
);

# describe($e) - the facts a person needs in order to answer anything.
sub describe {
    my ($e) = @_;
    my @l;
    push @l, sprintf('%-12s %s', 'name', $e->{name} // '');
    push @l, sprintf('%-12s %s  [%s]', 'expression', $e->{expression},
        (ref $e->{expression_proof} eq 'HASH'
         ? ($e->{expression_proof}{verified} // '?') : 'untiered'))
        if defined $e->{expression} && length $e->{expression};
    push @l, sprintf('%-12s %s  (%s)', 'denotation', $e->{denotation}{text},
        $e->{denotation}{source} // '?')
        if ref $e->{denotation} eq 'HASH';
    for my $t (qw(hashcat john mdxfind)) {
        my $b = $e->{tools}{$t} or next;
        my @ids = map { @{ $b->{$_} || [] } }
                  ($t eq 'hashcat' ? 'modes' : $t eq 'john' ? ('cpu','gpu') : 'types');
        push @l, sprintf('%-12s %s  [%s]', $t,
            (@ids ? join(', ', @ids) : '-'), $b->{verified} // '?');
    }
    push @l, sprintf('%-12s %d', 'vectors', scalar @{ $e->{vectors} || [] });
    push @l, sprintf('%-12s %s', 'relations',
        join('; ', map { "$_->{kind} -> $_->{entry}" } @{ $e->{relations} }))
        if ref $e->{relations} eq 'ARRAY' && @{ $e->{relations} };
    push @l, sprintf('%-12s %s', 'application', $e->{application})
        if defined $e->{application};
    push @l, sprintf('%-12s %s', 'notes', substr($e->{notes}, 0, 100))
        if defined $e->{notes} && length $e->{notes};
    return @l;
}

# proven_count($e) - how many tool blocks reached tier vector. Used only to
# order the queue: a row three tools agree on is more worth classifying than
# one nobody has touched.
sub proven_count {
    my ($e) = @_;
    return scalar grep { (($e->{tools}{$_} || {})->{verified} // '') eq 'vector' }
                  qw(hashcat john mdxfind);
}

my @queue;

# --- category ---------------------------------------------------------
unless (%want_kind && !$want_kind{category}) {
    my @c = grep { !defined $entry{$_}{category} } keys %entry;
    for my $id (sort { proven_count($entry{$b}) <=> proven_count($entry{$a})
                    || $a cmp $b } @c) {
        push @queue, {
            kind => 'category', target => $id,
            prompt  => 'Which axis does this entry sit on?',
            context => [ describe($entry{$id}) ],
            options => [ map { [$_->[0], $_->[1], $_->[2]] } @CATEGORY ],
        };
    }
}

# --- denotation -------------------------------------------------------
# Only entries with no expression and no settled 'absent': the ones whose
# expression column is blank with nothing said about why.
unless (%want_kind && !$want_kind{denotation}) {
    for my $id (sort keys %entry) {
        my $e = $entry{$id};
        next if defined $e->{expression} && length $e->{expression};
        next if ref $e->{expression_proof} eq 'HASH';
        next if ref $e->{denotation} eq 'HASH';
        my @sug;
        push @sug, ['1', $e->{name}, 'the name as recorded']
            if defined $e->{name} && length $e->{name};
        my ($mx) = @{ ($e->{tools}{mdxfind} || {})->{types} || [] };
        push @sug, ['2', $mx, "mdxfind's label"]
            if defined $mx && (!defined $e->{name} || $mx ne $e->{name});
        push @queue, {
            kind => 'denotation', target => $id,
            prompt  => 'How do people refer to this algorithm? '
                     . '(a number, or type your own wording)',
            context => [ describe($e) ],
            options => \@sug, free => 1,
        };
    }
}

# --- duplicate --------------------------------------------------------
unless (%want_kind && !$want_kind{duplicate}) {
    my %pair;
    for my $id (sort keys %entry) {
        for my $r (@{ $entry{$id}{relations} || [] }) {
            next unless ($r->{kind} // '') eq 'duplicate-of';
            next unless ($r->{distinction} // '') eq 'none';
            my $k = join '+', sort ($id, $r->{entry});
            $pair{$k} = [sort ($id, $r->{entry})];
        }
    }
    for my $k (sort keys %pair) {
        my ($a, $b) = @{ $pair{$k} };
        next unless $entry{$a} && $entry{$b};
        push @queue, {
            kind => 'duplicate', target => $k,
            prompt  => 'These propose a merge. Which id should survive?',
            context => [ "-- $a", (map { "   $_" } describe($entry{$a})),
                         "-- $b", (map { "   $_" } describe($entry{$b})) ],
            options => [ ['1', $a, 'keep this one'],
                         ['2', $b, 'keep this one'],
                         ['3', 'neither', 'they are genuinely different; '
                                        . 'the edge is wrong'] ],
        };
    }
}

# --- unproven ---------------------------------------------------------
unless (%want_kind && !$want_kind{unproven}) {
    for my $id (sort keys %entry) {
        my $e = $entry{$id};
        next unless ref $e->{expression_proof} eq 'HASH';
        next unless ($e->{expression_proof}{verified} // '') eq 'upstream';
        next unless defined $e->{expression} && length $e->{expression};
        push @queue, {
            kind => 'unproven', target => $id,
            prompt  => 'This expression does not reproduce the entry\'s own '
                     . 'vector. What is wrong?',
            context => [ describe($e) ],
            options => [ ['1', 'expression-wrong', 'the expression is wrong'],
                         ['2', 'vector-wrong', 'the vector is of a different '
                                             . 'algorithm, or has a bad plaintext'],
                         ['3', 'john-cannot', "john's compiler cannot express "
                                            . 'this, though the expression is right'],
                         ['4', 'unknown', 'needs investigation'] ],
            free => 1,
        };
    }
}

# --- token ------------------------------------------------------------
# Grouped: one answer explains every entry blocked by the same fragment.
unless (%want_kind && !$want_kind{token}) {
    my @KNOWN = sort { length($b) <=> length($a) || $a cmp $b } qw(
      SHA3-224 SHA3-256 SHA3-384 SHA3-512 KECCAK224 KECCAK256 KECCAK384
      KECCAK512 SKEIN224 SKEIN256 SKEIN384 SKEIN512 RMD128 RMD160 RMD256 RMD320
      SHA224 SHA256 SHA384 SHA512 SHA1 MD2 MD4 MD5 WRL GOST TIGER SM3 PANAMA
      HAV128-3 HAV128-4 HAV128-5 HAV160-3 HAV160-4 HAV160-5 HAV192-3 HAV192-4
      HAV192-5 HAV224-3 HAV224-4 HAV224-5 HAV256-3 HAV256-4 HAV256-5
      HAV128 HAV256 PASS SALT USER UC LC UTF16 UTF16LE UTF16BE RAW
    );
    my %group;
    for my $id (sort keys %entry) {
        my $e = $entry{$id};
        next if defined $e->{expression} && length $e->{expression};
        next if ref $e->{expression_proof} eq 'HASH';
        my ($t) = @{ ($e->{tools}{mdxfind} || {})->{types} || [] };
        next unless defined $t;
        my $s = uc $t;
        POS: while (length $s) {
            for my $k (@KNOWN) {
                if (index($s, $k) == 0) { substr($s, 0, length $k) = ''; next POS }
            }
            last;
        }
        next unless length $s;
        push @{ $group{$s} }, $id;
    }
    for my $frag (sort { @{ $group{$b} } <=> @{ $group{$a} } || $a cmp $b }
                  keys %group) {
        my @ids = @{ $group{$frag} };
        next if @ids < $min_group;
        push @queue, {
            kind => 'token', target => "TOKEN:$frag",
            prompt  => "What does the mdxfind name fragment '$frag' mean?",
            context => [ sprintf('%-12s %d', 'entries', scalar @ids),
                         sprintf('%-12s %s', 'examples',
                                 join(', ', @ids[0 .. ($#ids > 4 ? 4 : $#ids)])),
                         sprintf('%-12s %s', 'types', join(', ',
                             map { ($entry{$_}{tools}{mdxfind}{types}[0] // '') }
                             @ids[0 .. ($#ids > 2 ? 2 : $#ids)])) ],
            free => 1,
        };
    }
}

# Filters that apply to every kind.
@queue = grep { !defined $only || $_->{target} eq $only
                || $_->{target} =~ /(?:^|\+)\Q$only\E(?:\+|$)/ } @queue
    if defined $only;

my $total_open = scalar @queue;
@queue = grep {
    my $a = $answered->{"$_->{kind}\0$_->{target}"};
    !$a || ($again && ($a->{answer} // '') eq '(skipped)');
} @queue;

#-----------------------------------------------------------------------
# --apply: write the two kinds that can be written honestly.

if ($apply) {
    my %IS_CAT = map { $_->[1] => 1 } @CATEGORY;
    my ($wrote, $held) = (0, 0);
    for my $r (@$rows) {
        next if ($r->{answer} // '') eq '(skipped)';
        my $id = $r->{target};

        if ($r->{kind} eq 'category') {
            my $e = $entry{$id} or next;
            unless ($IS_CAT{ $r->{answer} }) {
                printf STDERR "- %s: '%s' is not a category; skipped\n",
                    $id, $r->{answer};
                next;
            }
            next if ($e->{category} // '') eq $r->{answer}
                 && (!length $r->{note} || ($e->{application} // '') eq $r->{note});
            $e->{category} = $r->{answer};
            $e->{application} = $r->{note}
                if $r->{answer} eq 'application' && length $r->{note};
            $wrote += emit_entry($path{$id}, $e);
            printf "%-34s category: %s%s\n", $id, $r->{answer},
                ($e->{application} ? "  application: $e->{application}" : '');
        }
        elsif ($r->{kind} eq 'denotation') {
            my $e = $entry{$id} or next;
            if (defined $e->{expression} && length $e->{expression}) {
                printf STDERR "- %s: now has an expression; denotation not "
                            . "written\n", $id;
                next;
            }
            $e->{denotation} = { text => $r->{answer}, source => 'human' };
            $e->{expression_proof} = {
                verified    => 'absent',
                verified_at => $TODAY,
                note        => 'no expression recorded; the denotation is how '
                             . 'this algorithm is referred to (curation)',
            };
            $wrote += emit_entry($path{$id}, $e);
            printf "%-34s denotation: %s\n", $id, $r->{answer};
        }
        else {
            $held++;
        }
    }
    printf STDERR "- %d file(s) written; %d answer(s) held for a human "
                . "(see --report)\n", $wrote, $held;
    printf STDERR "- now run: tools/validate.pl && tools/fmt.pl --all --check\n"
        if $wrote;
    exit 0;
}

#-----------------------------------------------------------------------
# --list, or ask.

my %count;
$count{ $_->{kind} }++ for @queue;

if ($list || !@queue) {
    printf "Open curation questions (%d of %d not yet answered):\n\n",
        scalar @queue, $total_open;
    printf "  %-12s %5d\n", $_, ($count{$_} // 0) for @KINDS;
    printf "\nJournal: %s\n", $journal;
    print  "\nNothing left to ask with these filters.\n" unless @queue;
    exit 0;
}

unless (-t STDIN) {
    print STDERR "$PROG: stdin is not a terminal; use --list, --report "
               . "or --apply.\n";
    exit 2;
}

printf "%d question(s) queued", scalar @queue;
printf ", asking %d", $limit if $limit && $limit < @queue;
printf ".  Answers go to %s\n", $journal;
print  "Enter to skip, 'q' to stop. Nothing is written to data/algorithms.\n\n";

my $asked = 0;
QUESTION: for my $q (@queue) {
    last if $limit && $asked >= $limit;
    $asked++;

    printf "[%d/%d] %s  %s\n", $asked,
        ($limit && $limit < @queue ? $limit : scalar @queue),
        $q->{kind}, $q->{target};
    print  "  $_\n" for @{ $q->{context} };
    print  "\n  $q->{prompt}\n";
    for my $o (@{ $q->{options} || [] }) {
        printf "    %s  %-14s %s\n", $o->[0], $o->[1], ($o->[2] // '');
    }
    print  "    (type your own)\n" if $q->{free};
    print  "    Enter skip   q quit\n";
    print  "> ";

    my $in = <STDIN>;
    unless (defined $in) { print "\n"; last QUESTION }
    chomp $in;
    $in =~ s/^\s+|\s+$//g;

    last QUESTION if lc $in eq 'q';

    if ($in eq '') {
        append_journal($q->{kind}, $q->{target}, '(skipped)', '');
        print "  skipped\n\n";
        next;
    }

    # A bare option key resolves to that option's value.
    my $answer = $in;
    for my $o (@{ $q->{options} || [] }) {
        if ($in eq $o->[0]) { $answer = $o->[1]; last }
    }
    if (!$q->{free} && $answer eq $in
        && @{ $q->{options} || [] }
        && !grep { $_->[1] eq $in } @{ $q->{options} }) {
        print "  not one of the options; skipping. Re-run with --again to "
            . "revisit.\n\n";
        append_journal($q->{kind}, $q->{target}, '(skipped)', '');
        next;
    }

    # One follow-up: an application row wants to name the product, because
    # that is the whole distinction the category is asserting.
    my $note = '';
    if ($q->{kind} eq 'category' && $answer eq 'application') {
        print "  Which product? (Enter to leave blank)\n> ";
        my $p = <STDIN>;
        if (defined $p) { chomp $p; $p =~ s/^\s+|\s+$//g; $note = $p }
    }
    elsif ($q->{kind} eq 'duplicate' || $q->{kind} eq 'unproven'
        || $q->{kind} eq 'token') {
        print "  Anything to add? (Enter for nothing)\n> ";
        my $p = <STDIN>;
        if (defined $p) { chomp $p; $p =~ s/^\s+|\s+$//g; $note = $p }
    }

    append_journal($q->{kind}, $q->{target}, $answer, $note);
    printf "  recorded: %s%s\n\n", $answer, (length $note ? "  ($note)" : '');
}

printf STDERR "- %d question(s) answered this session; %d still open\n",
    $asked, scalar(@queue) - $asked;
printf STDERR "- review with: %s --report\n", $PROG;
printf STDERR "- apply the category and denotation answers with: %s --apply\n",
    $PROG;

exit 0;
