#!/usr/bin/perl
#-----------------------------------------------------------------------
#
# Name: curate.pl
# Description: work through the decisions only a human can make, one question
#              at a time, and write the answers down where they can be applied
# Category: cracking-rosetta curator
#
# Project: cracking-rosetta | Phase: 6 - the human curation loop
#
#-----------------------------------------------------------------------
# METHODOLOGY AND WHY THESE CHOICES
#
# WHAT IS ACTUALLY LEFT
#
# The machine passes have gone as far as they go. Measured 2026-08-30, the day
# this tool was written: 265 expressions were proven by round-trip; the
# remainder was a long tail of 289 distinct unguessable mdxfind type names
# across 306 entries -- roughly one construction per entry, with no lever left
# to pull. Meanwhile 772 entries had no category:, the sheet's own 'class'
# column that was defined in 2023 and never filled. Run `--list` for what is
# open now; those figures are the reason this tool exists, not a current
# report, and the category one in particular has since moved a long way.
#
# None of that is a tooling problem any more. It is a person knowing things,
# and the bottleneck is how expensive it is to ASK them. Opening hundreds of
# files to type one word in each is the expensive way.
#
# SO THIS IS A QUESTION QUEUE, NOT AN EDITOR
#
# One question at a time, with every fact the repository already knows printed
# above it, and an answer that is usually one keystroke. Questions are grouped
# by kind so a session can be "twenty categories" rather than a lucky dip, and
# --limit means ten minutes is a useful amount of time to spend.
#
# ANSWERS GO TO A JOURNAL, NOT INTO THE DATA
#
# Nothing is written to data/algorithms while you are answering. Every answer
# is appended to a plain TSV as it is given, so a crash, a Ctrl-C or a change
# of mind costs nothing, and re-running skips what is already answered.
#
# --apply then writes the journal into the entries, and deliberately writes
# only the two kinds it can write honestly:
#
#   category    a closed vocabulary; the answer IS the value.
#   denotation  free text plus source: human, which is exactly what the field
#               is for -- it is untiered because nothing can round-trip it.
#
# The other kinds are recorded and REPORTED, never applied. A duplicate merge
# needs an id-resolution policy this repository has not decided. An expression
# must be proven by john before it is written, never accepted because someone
# typed it. Recording a human's belief and acting on it are different things,
# and this repository's whole premise is the distinction.
#
# 'x' -- THE ANSWER THAT IS NOT ONE OF THE OPTIONS
#
# Every closed question here is a guess about the shape of the answer, and a
# curator who knows the subject will hit questions where none of the options
# is true -- two entries that are neither the same nor different, an
# expression that is right for one vector and wrong for another. The old
# choices were to force one of the options, which puts a false answer in the
# journal, or to skip, which throws the knowledge away and asks again next
# session.
#
# So 'x' takes MULTI-LINE free text, ends on a lone '.', and records the
# answer 'complicated'. It is never applied to data/algorithms whatever the
# kind -- including denotation, which is otherwise free text -- and --again
# re-asks it, because it is a deferral with its reasons attached rather than a
# decision. It leads the --report for the same reason: it is the pile that
# needs a conversation.
#
# --report PRINTS THE JOURNAL AS MARKDOWN
#
# Because the other half of this workflow is handing the answers to someone --
# or something -- that will act on them. The report is grouped by kind and
# reads as prose, so it can be pasted into a conversation without editing.
#
# DEPENDENCIES
#
#   perl, YAML::XS, tools/lib/RosettaEmit.pm. No terminal library: answers are
#   typed and entered, because Term::ReadKey is not core and this repository
#   has exactly one non-core dependency.
#
#-----------------------------------------------------------------------
# Generated by Claude Opus 5 on 2026-08-30

use strict;
use warnings;

use File::Basename qw(basename);
use FindBin qw($RealBin);
use Getopt::Long qw(GetOptions);
use YAML::XS ();

use lib "$RealBin/lib";
use RosettaEmit qw(emit_entry);

my $PROG = basename($0);
my $ROOT = "$RealBin/..";
my $TODAY = do { my @t = localtime; sprintf '%04d-%02d-%02d',
                 $t[5] + 1900, $t[4] + 1, $t[3] };

my @KINDS = qw(category denotation duplicate unproven token form);

sub usage {
    print STDERR <<"END_USAGE";

Usage: $PROG [options]

   --kind K          only questions of this kind (repeatable). One of:
                       category    which axis does this entry sit on
                       denotation  what do people call this, when there is no
                                   provable expression
                       duplicate   two entries propose a merge; which survives
                       unproven    a recorded expression that does not
                                   reproduce its own vector
                       token       what does this mdxfind name fragment mean
   --limit N         stop after N questions (default 20; 0 for no limit)
   --only ID         just this entry
   --journal FILE    where answers live (default tmp/curation.tsv)
   --min-group N     'token' questions covering at least N entries (default 2)
   --list            print the queue and the counts; ask nothing
   --again           re-ask questions previously skipped or answered 'x'
   --issues          print the open questions as 'gh issue create' commands
                     and exit; the queue as something other people can answer
   --report          print the journal as Markdown and exit
   --apply           write the journal's category and denotation answers into
                     data/algorithms; report the rest
   -v, --verbose
   -h, --help

   'x' at any question takes multi-line free text -- why none of the offered
   answers is true -- ending on a lone '.'. It records 'complicated', leads
   --report, and is never applied to data/algorithms.

   Answering writes nothing but the journal. Exit 0 success, 1 error, 2 usage.

END_USAGE
    return;
}

my ($algdir, $journal, $help, $list, $report, $apply, $again, $only, $issues);
my @kind;
my $limit     = 20;
my $min_group = 2;
my $verbose   = 0;

GetOptions(
    'algorithms=s' => \$algdir,
    'journal=s'    => \$journal,
    'kind=s'       => \@kind,
    'only=s'       => \$only,
    'limit=i'      => \$limit,
    'min-group=i'  => \$min_group,
    'list'         => \$list,
    'issues' => \$issues, 'again'        => \$again,
    'report'       => \$report,
    'apply'        => \$apply,
    'v|verbose+'   => \$verbose,
    'h|help'       => \$help,
) or do { usage(); exit 2 };

if ($help) { usage(); exit 0 }

$algdir  //= "$ROOT/data/algorithms";
$journal //= "$ROOT/tmp/curation.tsv";

my %want_kind = map { $_ => 1 } @kind;
for my $k (keys %want_kind) {
    next if grep { $_ eq $k } @KINDS;
    print STDERR "$PROG: unknown --kind '$k'; known: @KINDS\n";
    exit 2;
}

#-----------------------------------------------------------------------
# The journal.

sub read_journal {
    my %seen;   # "kind\0target" -> { answer, note, when }
    my @rows;
    return (\%seen, \@rows) unless -r $journal;
    open my $fh, '<', $journal or return (\%seen, \@rows);
    while (my $l = <$fh>) {
        chomp $l;
        next if $l =~ /^\s*(?:#|$)/;
        my ($when, $kind, $target, $answer, $note) = split /\t/, $l, 5;
        next unless defined $answer;
        my $r = { when => $when, kind => $kind, target => $target,
                  answer => $answer, note => ($note // '') };
        # One pass, so an escaped backslash cannot be re-read as an escape.
        s{\\(.)}{ $1 eq 'n' ? "\n" : $1 eq 't' ? "\t" : $1 }ge
            for $r->{answer}, $r->{note};
        $seen{"$kind\0$target"} = $r;
        push @rows, $r;
    }
    close $fh;
    return (\%seen, \@rows);
}

sub append_journal {
    my ($kind, $target, $answer, $note) = @_;
    my $new = !-e $journal;
    open my $fh, '>>', $journal
        or die "$PROG: cannot append to $journal: $!\n";
    if ($new) {
        print {$fh} "# cracking-rosetta curation journal\n"
                  . "# when\tkind\ttarget\tanswer\tnote\n"
                  . "# Answers only. Nothing here is in data/algorithms until\n"
                  . "# tools/curate.pl --apply writes the kinds it can write.\n";
    }
    # Escaped rather than flattened: an 'x' note is multi-line prose and its
    # paragraphs are the point. Backslash first, so the unescape in
    # read_journal is unambiguous.
    for ($answer, $note) {
        $_ = defined $_ ? $_ : '';
        s/\\/\\\\/g;
        s/\t/\\t/g;
        s/\r?\n/\\n/g;
    }
    printf {$fh} "%s\t%s\t%s\t%s\t%s\n", $TODAY, $kind, $target, $answer, $note;
    close $fh;
    return;
}

my ($answered, $rows) = read_journal();

#-----------------------------------------------------------------------
# Load the corpus.

opendir(my $dh, $algdir)
    or do { print STDERR "$PROG: cannot read $algdir: $!\n"; exit 1 };
my @files = sort grep { /\.yaml$/ } readdir $dh;
closedir $dh;

my (%entry, %path);
for my $f (@files) {
    my $p = "$algdir/$f";
    my $e = eval { YAML::XS::LoadFile($p) } or next;
    next unless $e->{id};
    # A tombstone is a redirect, not an algorithm: CLAUDE.md excludes it from
    # every count and denominator, and there is nothing to curate about one --
    # it has no category, no expression and no tool identifiers by design.
    # Skipping it here rather than in each builder is what keeps the five
    # question kinds from having to remember. The duplicate builder already
    # refused a pair with a tombstone in it; that check is now redundant but
    # harmless.
    next if ($e->{status} // q()) eq q(merged);
    $entry{ $e->{id} } = $e;
    $path{  $e->{id} } = $p;
}

#-----------------------------------------------------------------------
# --report: the journal as something you can paste into a conversation.

if ($report) {
    unless (@$rows) {
        print "No curation answers recorded yet ($journal).\n";
        exit 0;
    }
    my %by;
    push @{ $by{ $_->{kind} } }, $_ for @$rows;
    printf "# Curation answers\n\nFrom `%s`, %d answer(s).\n",
        $journal, scalar @$rows;

    # Markdown swallows a single newline, so a multi-line note is indented and
    # its breaks are made hard. Without this an 'x' answer arrives as one run-
    # on paragraph, which is the opposite of why it was typed at length.
    my $body = sub {
        my ($t) = @_;
        return '' unless defined $t && length $t;
        $t =~ s/\n/  \n  /g;
        return "  \n  $t";
    };

    # The complicated ones lead: they are the pile that needs a conversation,
    # and they are never applied, so nothing else in this report acts on them.
    my @hard = grep { ($_->{answer} // '') eq 'complicated' } @$rows;
    if (@hard) {
        printf "\n## it's complicated (%d)\n\n"
             . "None of the offered answers was true. Nothing here is applied.\n\n",
            scalar @hard;
        printf "- **%s** (%s)%s\n", $_->{target}, $_->{kind}, $body->($_->{note})
            for @hard;
    }

    for my $k (@KINDS) {
        my @r = grep { ($_->{answer} // '') ne '(skipped)'
                    && ($_->{answer} // '') ne 'complicated' } @{ $by{$k} || [] };
        next unless @r;
        printf "\n## %s (%d)\n\n", $k, scalar @r;
        for my $r (@r) {
            printf "- **%s** -> `%s`%s\n", $r->{target}, $r->{answer},
                $body->($r->{note});
        }
    }
    my @skipped = grep { ($_->{answer} // '') eq '(skipped)' } @$rows;
    printf "\n## skipped (%d)\n\n%s\n", scalar @skipped,
        join(', ', map { $_->{target} } @skipped) if @skipped;
    exit 0;
}

#-----------------------------------------------------------------------
# Build the queue.
#
# One sub per kind. Each returns a list of questions:
#   { kind, target, prompt, context => [lines], options => [[key,label],...],
#     free => 1 }

my @CATEGORY = (
    ['1', 'primitive',   'one hash function over the plaintext'],
    ['2', 'composite',   'a construction over several'],
    ['3', 'iterated',    'another entry applied N times'],
    ['4', 'encoding',    "another entry's digest written differently"],
    ['5', 'application', "a product's use of a computation another entry names"],
    ['6', 'protocol',    'a challenge-response or wire format'],
    ['7', 'kdf',         'a deliberately slow derivation'],
);

# describe($e) - the facts a person needs in order to answer anything.
sub describe {
    my ($e) = @_;
    my @l;
    push @l, sprintf('%-12s %s', 'name', $e->{name} // '');
    push @l, sprintf('%-12s %s  [%s]', 'expression', $e->{expression},
        (ref $e->{expression_proof} eq 'HASH'
         ? ($e->{expression_proof}{verified} // '?') : 'untiered'))
        if defined $e->{expression} && length $e->{expression};
    push @l, sprintf('%-12s %s  (%s)', 'denotation', $e->{denotation}{text},
        $e->{denotation}{source} // '?')
        if ref $e->{denotation} eq 'HASH';
    for my $t (qw(hashcat john mdxfind)) {
        my $b = $e->{tools}{$t} or next;
        my @ids = map { @{ $b->{$_} || [] } }
                  ($t eq 'hashcat' ? 'modes' : $t eq 'john' ? ('cpu','gpu') : 'types');
        push @l, sprintf('%-12s %s  [%s]', $t,
            (@ids ? join(', ', @ids) : '-'), $b->{verified} // '?');
    }
    push @l, sprintf('%-12s %d', 'vectors', scalar @{ $e->{vectors} || [] });
    push @l, sprintf('%-12s %s', 'relations',
        join('; ', map { "$_->{kind} -> $_->{entry}" } @{ $e->{relations} }))
        if ref $e->{relations} eq 'ARRAY' && @{ $e->{relations} };
    push @l, sprintf('%-12s %s', 'application', $e->{application})
        if defined $e->{application};
    push @l, sprintf('%-12s %s', 'notes', substr($e->{notes}, 0, 100))
        if defined $e->{notes} && length $e->{notes};
    return @l;
}

# proven_count($e) - how many tool blocks reached tier vector. Used only to
# order the queue: a row three tools agree on is more worth classifying than
# one nobody has touched.
sub proven_count {
    my ($e) = @_;
    return scalar grep { (($e->{tools}{$_} || {})->{verified} // '') eq 'vector' }
                  qw(hashcat john mdxfind);
}

my @queue;

# --- category ---------------------------------------------------------
unless (%want_kind && !$want_kind{category}) {
    my @c = grep { !defined $entry{$_}{category} } keys %entry;
    for my $id (sort { proven_count($entry{$b}) <=> proven_count($entry{$a})
                    || $a cmp $b } @c) {
        push @queue, {
            kind => 'category', target => $id,
            prompt  => 'Which axis does this entry sit on?',
            context => [ describe($entry{$id}) ],
            options => [ map { [$_->[0], $_->[1], $_->[2]] } @CATEGORY ],
        };
    }
}

# --- denotation -------------------------------------------------------
# Only entries with no expression and no settled 'absent': the ones whose
# expression column is blank with nothing said about why.
unless (%want_kind && !$want_kind{denotation}) {
    for my $id (sort keys %entry) {
        my $e = $entry{$id};
        next if defined $e->{expression} && length $e->{expression};
        next if ref $e->{expression_proof} eq 'HASH';
        next if ref $e->{denotation} eq 'HASH';
        my @sug;
        push @sug, ['1', $e->{name}, 'the name as recorded']
            if defined $e->{name} && length $e->{name};
        my ($mx) = @{ ($e->{tools}{mdxfind} || {})->{types} || [] };
        push @sug, ['2', $mx, "mdxfind's label"]
            if defined $mx && (!defined $e->{name} || $mx ne $e->{name});
        push @queue, {
            kind => 'denotation', target => $id,
            prompt  => 'How do people refer to this algorithm? '
                     . '(a number, or type your own wording)',
            context => [ describe($e) ],
            options => \@sug, free => 1,
        };
    }
}

# --- form -------------------------------------------------------------
# Which of these strings is the form the producing system actually stores?
#
# Only asked where the tools SPLIT -- no single string is read by every tool
# that reads anything on the entry -- because that is where a reader holding
# one string genuinely cannot tell which of them is the real credential and
# which is a cracker's re-encoding of it. derive-forms.pl has already set the
# TOOL forms from reads_in, which is measurement; this is the half nothing in
# a string can answer. Both answers are useful and the tool says so: "none of
# them" is a real result for a credential that only ever existed as a wire
# message, and it stops the question being re-asked.
unless (%want_kind && !$want_kind{form}) {
    for my $id (sort keys %entry) {
        my $e = $entry{$id};
        my @v = @{ $e->{vectors} || [] };
        next unless @v;
        next if grep { ($_->{form} // '') eq 'native' } @v;

        my %tools;
        for my $v (@v) {
            next unless ref $v->{reads_in} eq 'ARRAY';
            $tools{$_} = 1 for @{ $v->{reads_in} };
        }
        next unless keys %tools > 1;
        my $all = join ',', sort keys %tools;
        next if grep { ref $_->{reads_in} eq 'ARRAY'
                    && join(',', sort @{ $_->{reads_in} }) eq $all } @v;

        # The strings themselves are the options: a curator picks one, or says
        # none of them is native. Truncated for the terminal; the entry file
        # has them whole.
        my ($n, @opt) = (0);
        for my $v (@v) {
            $n++;
            my $h = $v->{hash};
            $h = substr($h, 0, 72) . '...' if length $h > 75;
            my $who = ref $v->{reads_in} eq 'ARRAY' && @{ $v->{reads_in} }
                    ? join('+', sort @{ $v->{reads_in} }) : 'nothing';
            push @opt, [ $n, "vector $n", "$h  (read by $who)" ];
        }
        push @opt, [ $n + 1, 'none',
                     'no string here is native -- the credential exists only '
                   . 'as a wire message or a binary field, and every form '
                   . 'here is a cracker\'s invention' ];

        push @queue, {
            kind => 'form', target => $id, ids => [$id],
            prompt  => 'The tools here disagree about the string. Which of '
                     . 'these is the form the producing system itself stores '
                     . 'or emits? That form is the primary one, even though '
                     . 'the tools rewrite it.',
            context => [ describe($e) ],
            options => \@opt, free => 1,
        };
    }
}

# --- duplicate --------------------------------------------------------
unless (%want_kind && !$want_kind{duplicate}) {
    my %pair;
    for my $id (sort keys %entry) {
        for my $r (@{ $entry{$id}{relations} || [] }) {
            next unless ($r->{kind} // '') eq 'duplicate-of';
            next unless ($r->{distinction} // '') eq 'none';
            my $k = join '+', sort ($id, $r->{entry});
            $pair{$k} = [sort ($id, $r->{entry})];
        }
    }
    for my $k (sort keys %pair) {
        my ($a, $b) = @{ $pair{$k} };
        next unless $entry{$a} && $entry{$b};
        # A pair where one side is a tombstone is a merge that was already
        # carried out: the surviving entry keeps the duplicate-of edge as the
        # record of it. Re-asking would put a settled decision back in front
        # of a human, and --issues would file it as a question to strangers.
        next if ($entry{$a}{status} // '') eq 'merged'
             || ($entry{$b}{status} // '') eq 'merged';
        push @queue, {
            kind => 'duplicate', target => $k, ids => [$a, $b],
            prompt  => 'These propose a merge. Which id should survive?',
            context => [ "-- $a", (map { "   $_" } describe($entry{$a})),
                         "-- $b", (map { "   $_" } describe($entry{$b})) ],
            options => [ ['1', $a, 'keep this one'],
                         ['2', $b, 'keep this one'],
                         ['3', 'neither', 'they are genuinely different; '
                                        . 'the edge is wrong'] ],
        };
    }
}

# --- unproven ---------------------------------------------------------
unless (%want_kind && !$want_kind{unproven}) {
    for my $id (sort keys %entry) {
        my $e = $entry{$id};
        next unless ref $e->{expression_proof} eq 'HASH';
        next unless ($e->{expression_proof}{verified} // '') eq 'upstream';
        next unless defined $e->{expression} && length $e->{expression};

        # triage-expressions.pl records WHY the expression does not reproduce.
        # Most of the verdicts are about john -- its compiler cannot execute a
        # string it printed, the format encodes its ciphertext its own way, it
        # truncates, it will not take a long salt -- and no contributor can
        # answer those. Asking anyway is how a queue of real questions gets
        # buried. Three verdicts do need a human: a wrong expression, an
        # anomalous vector, and a PARTIAL reproduction -- an expression that
        # reproduces some of an entry's vectors and not others is what a
        # multi-emit mdxfind type looks like (CLAUDE.md, "Some mdxfind types
        # are MULTI-EMIT"), and deciding that is curation.
        my $tnote = $e->{expression_proof}{note} // '';
        if ($tnote =~ /TRIAGE \d{4}-\d{2}-\d{2} \[([a-z-]+)\]:/) {
            my $verdict = $1;
            next unless $verdict eq 'vector-anomalous'
                     || $verdict eq 'expression-wrong'
                     || $verdict eq 'partial';
        }
        push @queue, {
            kind => 'unproven', target => $id, ids => [$id],
            prompt  => 'This expression is recorded at tier upstream and has '
                     . 'not been proven. Where triage could test it, it did '
                     . 'not reproduce the entry\'s own vector. What is wrong?',
            context => [ describe($e) ],
            options => [ ['1', 'expression-wrong', 'the expression is wrong'],
                         ['2', 'vector-wrong', 'the vector is of a different '
                                             . 'algorithm, or has a bad plaintext'],
                         ['3', 'john-cannot', "john's compiler cannot express "
                                            . 'this, though the expression is right'],
                         ['4', 'unknown', 'needs investigation'] ],
            free => 1,
        };
    }
}

# --- token ------------------------------------------------------------
# Grouped: one answer explains every entry blocked by the same fragment.
unless (%want_kind && !$want_kind{token}) {
    my @KNOWN = sort { length($b) <=> length($a) || $a cmp $b } qw(
      SHA3-224 SHA3-256 SHA3-384 SHA3-512 KECCAK224 KECCAK256 KECCAK384
      KECCAK512 SKEIN224 SKEIN256 SKEIN384 SKEIN512 RMD128 RMD160 RMD256 RMD320
      SHA224 SHA256 SHA384 SHA512 SHA1 MD2 MD4 MD5 WRL GOST TIGER SM3 PANAMA
      HAV128-3 HAV128-4 HAV128-5 HAV160-3 HAV160-4 HAV160-5 HAV192-3 HAV192-4
      HAV192-5 HAV224-3 HAV224-4 HAV224-5 HAV256-3 HAV256-4 HAV256-5
      HAV128 HAV256 PASS SALT USER UC LC UTF16 UTF16LE UTF16BE RAW
    );
    my %group;
    for my $id (sort keys %entry) {
        my $e = $entry{$id};
        next if defined $e->{expression} && length $e->{expression};
        next if ref $e->{expression_proof} eq 'HASH';
        my ($t) = @{ ($e->{tools}{mdxfind} || {})->{types} || [] };
        next unless defined $t;
        my $s = uc $t;
        POS: while (length $s) {
            for my $k (@KNOWN) {
                if (index($s, $k) == 0) { substr($s, 0, length $k) = ''; next POS }
            }
            last;
        }
        next unless length $s;
        push @{ $group{$s} }, $id;
    }
    for my $frag (sort { @{ $group{$b} } <=> @{ $group{$a} } || $a cmp $b }
                  keys %group) {
        my @ids = @{ $group{$frag} };
        next if @ids < $min_group;
        push @queue, {
            kind => 'token', target => "TOKEN:$frag", ids => [@ids],
            prompt  => "What does the mdxfind name fragment '$frag' mean?",
            context => [ sprintf('%-12s %d', 'entries', scalar @ids),
                         sprintf('%-12s %s', 'examples',
                                 join(', ', @ids[0 .. ($#ids > 4 ? 4 : $#ids)])),
                         sprintf('%-12s %s', 'types', join(', ',
                             map { ($entry{$_}{tools}{mdxfind}{types}[0] // '') }
                             @ids[0 .. ($#ids > 2 ? 2 : $#ids)])) ],
            free => 1,
        };
    }
}

# Filters that apply to every kind.
@queue = grep { !defined $only || $_->{target} eq $only
                || $_->{target} =~ /(?:^|\+)\Q$only\E(?:\+|$)/ } @queue
    if defined $only;

my $total_open = scalar @queue;
@queue = grep {
    my $a = $answered->{"$_->{kind}\0$_->{target}"};
    # 'complicated' is a deferral with its reasons attached, not a decision,
    # so --again brings it back alongside the skips.
    !$a || ($again && ( ($a->{answer} // '') eq '(skipped)'
                     || ($a->{answer} // '') eq 'complicated' ));
} @queue;

#-----------------------------------------------------------------------
# --apply: write the two kinds that can be written honestly.

if ($apply) {
    my %IS_CAT = map { $_->[1] => 1 } @CATEGORY;
    my ($wrote, $held) = (0, 0);
    for my $r (@$rows) {
        next if ($r->{answer} // '') eq '(skipped)';
        my $id = $r->{target};

        # 'complicated' says none of the options was true. It is a note to a
        # human, never a value -- and denotation would otherwise write the
        # word into the data, since that kind takes free text.
        if ($r->{answer} eq 'complicated') { $held++; next }

        if ($r->{kind} eq 'category') {
            my $e = $entry{$id} or next;
            unless ($IS_CAT{ $r->{answer} }) {
                printf STDERR "- %s: '%s' is not a category; skipped\n",
                    $id, $r->{answer};
                next;
            }
            next if ($e->{category} // '') eq $r->{answer}
                 && (!length $r->{note} || ($e->{application} // '') eq $r->{note});
            $e->{category} = $r->{answer};
            $e->{application} = $r->{note}
                if $r->{answer} eq 'application' && length $r->{note};
            $wrote += emit_entry($path{$id}, $e);
            printf "%-34s category: %s%s\n", $id, $r->{answer},
                ($e->{application} ? "  application: $e->{application}" : '');
        }
        elsif ($r->{kind} eq 'denotation') {
            my $e = $entry{$id} or next;
            if (defined $e->{expression} && length $e->{expression}) {
                printf STDERR "- %s: now has an expression; denotation not "
                            . "written\n", $id;
                next;
            }
            $e->{denotation} = { text => $r->{answer}, source => 'human' };
            $e->{expression_proof} = {
                verified    => 'absent',
                verified_at => $TODAY,
                note        => 'no expression recorded; the denotation is how '
                             . 'this algorithm is referred to (curation)',
            };
            $wrote += emit_entry($path{$id}, $e);
            printf "%-34s denotation: %s\n", $id, $r->{answer};
        }
        else {
            $held++;
        }
    }
    printf STDERR "- %d file(s) written; %d answer(s) held for a human "
                . "(see --report)\n", $wrote, $held;
    printf STDERR "- now run: tools/validate.pl && tools/fmt.pl --all --check\n"
        if $wrote;
    exit 0;
}

#-----------------------------------------------------------------------
# --issues: the queue as something other people can answer.
#
# WHY THIS EXISTS
#
# The journal is one person's terminal session. Most of what is left in the
# queue cannot be answered from the data at all -- whether two rows are one
# algorithm, what a tool really computes, whether an expression or a vector is
# the wrong one -- and the people who can answer have never seen this file.
# So the queue has to leave the machine it was generated on.
#
# WHY SHELL COMMANDS RATHER THAN AN API CALL
#
# This writes to stdout and nothing else. Creating issues is outward-facing
# and irreversible-ish -- 40 issues cannot be quietly unsent -- so the person
# running it should read the batch, cut the ones they do not want, and run it
# themselves. It is also the only form that works with no token in this
# process and no network.
#
# The category and denotation kinds are deliberately excluded by default:
# 1100 of them are open, they are derivable rather than knowledge, and filing
# them as issues would bury the ~25 questions that genuinely need a person.
# 'form' is included: which string a system actually stores is exactly the
# knowledge someone who runs that system has and this repository does not.

if ($issues) {
    # Shell-quote for single quotes: end the quote, escape one, reopen.
    my $q = sub { my $t = shift // ''; $t =~ s/'/'\\''/g; return "'$t'" };

    my %ASK_KIND = map { $_ => 1 } qw(duplicate unproven token form);
    my @ask = grep { $ASK_KIND{ $_->{kind} } }
              grep { !%want_kind || $want_kind{ $_->{kind} } } @queue;

    printf "#!/bin/sh\n# %d open question(s) as GitHub issues, generated by "
         . "tools/%s on %s.\n", scalar @ask, $PROG, $TODAY;
    print  "# Read this before running it: every line files an issue.\n"
         . "# Cut the ones you do not want, then: sh thisfile\n"
         . "set -e\n\n"
         # gh refuses --label for a label that does not exist, and set -e
         # would then abort the batch on its first line. Creating it here is
         # idempotent and costs nothing on a repository that already has it.
         . "gh label create curation --color 0e8a16 \\\n"
         . "    --description 'A question the data cannot answer' 2>/dev/null || true\n\n";

    # An issue is worth opening only if it saves the reader the work we have
    # already done. So each one carries what this repository knows about the
    # entry -- its vectors, its identifiers, the triage verdict if there is one
    # -- and the exact commands that would settle it, pinned to the entry's own
    # identifiers. Everything below is read from the data; nothing is typed.
    my $REPO = 'https://github.com/roycewilliams/cracking-rosetta';

    # vectors_block($id) - the test vectors, ready to paste into a hash file.
    my $vectors_block = sub {
        my ($id) = @_;
        my $e = $entry{$id} or return ();
        my @v = @{ $e->{vectors} || [] } or return ();
        my @out = ("Test vectors on `$id` (hash, then plaintext):", '', '```');
        push @out, sprintf('%-72s %s', $_->{hash} // '', $_->{pass} // '') for @v;
        push @out, '```', '';
        return @out;
    };

    # commands($id) - what to run, with this entry's identifiers already in it.
    # A reader who owns the tool should not have to look up the pinning rules
    # (mdxfind needs -F for a vector carrying its salt, and the iteration count
    # is part of the identity).
    my $commands = sub {
        my ($id) = @_;
        my $e = $entry{$id} or return ();
        my @c;
        my ($v) = @{ $e->{vectors} || [] };
        my $salted = $v && ($v->{hash} // '') =~ /:/ ? 1 : 0;
        if (my @t = @{ ($e->{tools}{mdxfind} || {})->{types} || [] }) {
            my $it = ($e->{tools}{mdxfind}{iterations} || 1);
            push @c, sprintf("mdxfind -h '^%s\$' %s hashes -i %d wordlist",
                             $t[0], ($salted ? '-F' : '-f'), $it);
        }
        if (my @m = @{ ($e->{tools}{hashcat} || {})->{modes} || [] }) {
            push @c, sprintf('hashcat -m %d -a 0 hashes wordlist', $m[0]);
        }
        if (my @j = @{ ($e->{tools}{john} || {})->{cpu} || [] }) {
            push @c, sprintf("john --format=%s hashes --wordlist=wordlist", $j[0]);
        }
        if (my $x = $e->{expression}) {
            push @c, sprintf("john --format=dynamic='%s' hashes --wordlist=wordlist", $x);
        }
        return () unless @c;
        return ('Commands, with this entry\'s own identifiers:', '', '```sh', @c, '```', '');
    };

    # triage($id) - the diagnosis triage-expressions.pl recorded, if any. It
    # is the difference between "this does not work" and "here is what is
    # wrong with it", and it is what stops a reader repeating the analysis.
    my $triage = sub {
        my ($id) = @_;
        my $e = $entry{$id} or return ();
        my $n = ($e->{expression_proof} || {})->{note} // '';
        return () unless $n =~ /TRIAGE \d{4}-\d{2}-\d{2}(?: \[([a-z-]+)\])?: (.+)$/s;
        my ($verdict, $text) = ($1 // 'triaged', $2);
        $text =~ s/\s+/ /g;
        return ("**Already established** (`$verdict`): $text", '');
    };

    # ruled_out($id) - work already done and recorded on the entry, so nobody
    # repeats it. notes: is where a tool or a person leaves that.
    my $ruled_out = sub {
        my ($id) = @_;
        my $e = $entry{$id} or return ();
        my $n = $e->{notes} // '';
        return () unless length $n;
        $n =~ s/\s+/ /g;
        return ("**Already ruled out**: $n", '');
    };

    for my $item (@ask) {
        my @ids = @{ $item->{ids} || [] };
        my $title = $item->{kind} eq 'duplicate'
            ? sprintf('Are %s one algorithm or two?',
                      join(' and ', split /\+/, $item->{target}))
            : $item->{kind} eq 'token'
            ? sprintf('What does the mdxfind name fragment %s mean?',
                      ($item->{target} =~ /^TOKEN:(.+)$/)[0] // $item->{target})
            : $item->{kind} eq 'form'
            ? sprintf('%s: which of these strings does the real system store?',
                      $ids[0] // $item->{target})
            : sprintf('%s: what is this vector, if not %s?', $ids[0] // $item->{target},
                      ($entry{ $ids[0] // '' } || {})->{expression} // 'the recorded expression');

        my @body = ($item->{prompt}, '');
        push @body, $triage->($_)    for @ids;
        push @body, $ruled_out->($_) for @ids;

        push @body, 'What the repository already records:', '', '```';
        push @body, @{ $item->{context} };
        push @body, '```', '';

        push @body, $vectors_block->($_) for @ids;
        push @body, $commands->($_)      for @ids;

        push @body, 'Any of these would settle it:', '';
        push @body, sprintf('* **%s** - %s', $_->[1], $_->[2])
            for @{ $item->{options} };

        push @body, '',
            'A comment saying which, and why, is a complete answer - no pull '
          . 'request needed, and you do not have to be certain. "I have seen '
          . 'this format do X" is information this repository cannot derive.',
            '';
        push @body, sprintf('Entry: [`%s`](%s/blob/main/data/algorithms/%s.yaml) '
                          . '&middot; [row](%s/blob/main/docs/ROSETTA.md)', $_,
                            $REPO, $_, $REPO) for @ids;
        push @body, '', 'Generated from the curation queue (`tools/curate.pl --issues`).';

        printf "gh issue create --label %s --title %s --body %s\n\n",
            $q->('curation'), $q->($title), $q->(join "\n", @body);
    }

    printf STDERR "- %d question(s) of kind duplicate/unproven/token; "
                . "%d in the queue overall\n", scalar @ask, scalar @queue;
    print  STDERR "- nothing was filed; pipe this to a file, read it, then run it\n";
    exit 0;
}

#-----------------------------------------------------------------------
# --list, or ask.

my %count;
$count{ $_->{kind} }++ for @queue;

if ($list || !@queue) {
    printf "Open curation questions (%d of %d not yet answered):\n\n",
        scalar @queue, $total_open;
    printf "  %-12s %5d\n", $_, ($count{$_} // 0) for @KINDS;
    printf "\nJournal: %s\n", $journal;
    print  "\nNothing left to ask with these filters.\n" unless @queue;
    exit 0;
}

unless (-t STDIN) {
    print STDERR "$PROG: stdin is not a terminal; use --list, --report "
               . "or --apply.\n";
    exit 2;
}

printf "%d question(s) queued", scalar @queue;
printf ", asking %d", $limit if $limit && $limit < @queue;
printf ".  Answers go to %s\n", $journal;
print  "Enter to skip, 'q' to stop. Nothing is written to data/algorithms.\n\n";

# read_long_text() - as many lines as it takes, ending on a lone '.'.
#
# A blank line would be the obvious terminator and is the wrong one: prose
# with a paragraph break in it is exactly what this is for. End of input ends
# the answer too, which also ends the session -- the loop below reads undef
# and stops -- so the '.' is the way to carry on answering.
sub read_long_text {
    print "  Explain. Finish with a single '.' on a line of its own.\n";
    my @lines;
    while (defined(my $l = <STDIN>)) {
        chomp $l;
        last if $l eq '.';
        push @lines, $l;
    }
    my $text = join "\n", @lines;
    $text =~ s/\A\s+|\s+\z//g;
    return $text;
}

my $asked = 0;
QUESTION: for my $q (@queue) {
    last if $limit && $asked >= $limit;
    $asked++;

    printf "[%d/%d] %s  %s\n", $asked,
        ($limit && $limit < @queue ? $limit : scalar @queue),
        $q->{kind}, $q->{target};
    print  "  $_\n" for @{ $q->{context} };
    print  "\n  $q->{prompt}\n";
    for my $o (@{ $q->{options} || [] }) {
        printf "    %s  %-14s %s\n", $o->[0], $o->[1], ($o->[2] // '');
    }
    print  "    (type your own)\n" if $q->{free};
    print  "    x  it's complicated -- explain at length; never applied\n";
    print  "    Enter skip   q quit\n";
    print  "> ";

    my $in = <STDIN>;
    unless (defined $in) { print "\n"; last QUESTION }
    chomp $in;
    $in =~ s/^\s+|\s+$//g;

    last QUESTION if lc $in eq 'q';

    if (lc $in eq 'x') {
        my $text = read_long_text();
        unless (length $text) {
            print "  nothing written; skipped\n\n";
            append_journal($q->{kind}, $q->{target}, '(skipped)', '');
            next;
        }
        append_journal($q->{kind}, $q->{target}, 'complicated', $text);
        printf "  recorded: complicated (%d line(s)); it will lead --report "
             . "and is never applied\n\n", scalar(split /\n/, $text);
        next;
    }

    if ($in eq '') {
        append_journal($q->{kind}, $q->{target}, '(skipped)', '');
        print "  skipped\n\n";
        next;
    }

    # A bare option key resolves to that option's value.
    my $answer = $in;
    for my $o (@{ $q->{options} || [] }) {
        if ($in eq $o->[0]) { $answer = $o->[1]; last }
    }
    if (!$q->{free} && $answer eq $in
        && @{ $q->{options} || [] }
        && !grep { $_->[1] eq $in } @{ $q->{options} }) {
        print "  not one of the options; skipping. Re-run with --again to "
            . "revisit.\n\n";
        append_journal($q->{kind}, $q->{target}, '(skipped)', '');
        next;
    }

    # One follow-up: an application row wants to name the product, because
    # that is the whole distinction the category is asserting.
    my $note = '';
    if ($q->{kind} eq 'category' && $answer eq 'application') {
        print "  Which product? (Enter to leave blank)\n> ";
        my $p = <STDIN>;
        if (defined $p) { chomp $p; $p =~ s/^\s+|\s+$//g; $note = $p }
    }
    elsif ($q->{kind} eq 'duplicate' || $q->{kind} eq 'unproven'
        || $q->{kind} eq 'token') {
        print "  Anything to add? (Enter for nothing)\n> ";
        my $p = <STDIN>;
        if (defined $p) { chomp $p; $p =~ s/^\s+|\s+$//g; $note = $p }
    }

    append_journal($q->{kind}, $q->{target}, $answer, $note);
    printf "  recorded: %s%s\n\n", $answer, (length $note ? "  ($note)" : '');
}

printf STDERR "- %d question(s) answered this session; %d still open\n",
    $asked, scalar(@queue) - $asked;
printf STDERR "- review with: %s --report\n", $PROG;
printf STDERR "- apply the category and denotation answers with: %s --apply\n",
    $PROG;

exit 0;
