#!/usr/bin/perl
#-----------------------------------------------------------------------
#
# Name: dedupe.pl
# Description: merge algorithm entries that describe the same algorithm
# Category: cracking-rosetta maintenance
#
# Project: cracking-rosetta | Phase: 5b - remove duplicate entries
#
#-----------------------------------------------------------------------
# METHODOLOGY AND WHY THESE CHOICES
#
# WHERE THE DUPLICATES CAME FROM
#
# The source spreadsheet carried two rows for the same algorithm more often
# than anyone realized: one with a name in the Algorithm column, one with that
# cell blank and only the mdxfind and hashes.org columns filled. The importer
# names a blank row after its mdxfind type, so "IPB2+, MyBB1.2+" and
# "MD5-MD5SALTMD5PASS" became two entries describing one thing. This was
# invisible in the sheet and only became visible once identifiers were
# normalized and cross-referenced. Measured 2026-08-29: 54 collisions covering
# 114 redundant entries.
#
# THE KEY IS THE mdxfind IDENTITY, INCLUDING ITERATIONS
#
# Type name plus -i value. MD5 at 2 iterations is a different algorithm from
# MD5 at 1, so the pair is the key and the type alone is not.
#
# A DISJOINT MAPPING MEANS "DIFFERENT", NOT "DUPLICATE"
#
# Two entries sharing an mdxfind type are only merged when, for every tool,
# their identifier lists overlap or one of them is empty. If both name hashcat
# modes and share none, they are describing different things that mdxfind
# happens to reach through one type -- exactly the coarseness that made
# mdxfind's own hashcat column unusable as an equivalence. Those groups are
# reported for a human and left completely alone.
#
# NOTHING IS LOST IN A MERGE
#
# The loser's identifiers, vectors, legacy names and notes are folded into the
# survivor, and its name is kept as an alias. The survivor is the entry a
# person would recognize: one with a real name rather than a name the importer
# generated from a tool's internal label.
#
# DRY RUN IS THE DEFAULT
#
# This deletes files. It previews by default and needs --apply to act. Every
# entry is committed to git before this runs, so a bad merge is recoverable
# with git checkout -- but recoverable is not the same as reversible, so the
# preview shows counts and a sample first.
#
#-----------------------------------------------------------------------
# Generated by Claude Opus 5 on 2026-08-29

use strict;
use warnings;

use File::Basename qw(basename);
use FindBin qw($RealBin);
use Getopt::Long qw(GetOptions);
use YAML::XS ();

use lib "$RealBin/lib";
use RosettaEmit qw(emit_entry);

my $PROG = basename($0);
my $ROOT = "$RealBin/..";

sub usage {
    print STDERR <<"END_USAGE";

Usage: $PROG [--apply] [options]

   --apply           actually merge and delete; without it, preview only
   --algorithms DIR  curated entries (default: data/algorithms)
   -v, --verbose     show every merge, not a sample
   -h, --help        this help

   Merges entries that share an mdxfind identity (type plus iteration count)
   when their tool mappings do not conflict. Groups whose mappings are
   disjoint are reported and left alone.

   Exit 0 success, 1 error, 2 usage.

END_USAGE
    return;
}

my ($apply, $algdir, $help);
my $verbose = 0;

GetOptions(
    'apply'        => \$apply,
    'algorithms=s' => \$algdir,
    'v|verbose+'   => \$verbose,
    'h|help'       => \$help,
) or do { usage(); exit 2 };

if ($help) { usage(); exit 0 }
$algdir //= "$ROOT/data/algorithms";

#-----------------------------------------------------------------------
# Load.

opendir(my $dh, $algdir) or do { print STDERR "$PROG: cannot read $algdir: $!\n"; exit 1 };
my @files = sort grep { /\.yaml$/ } readdir $dh;
closedir $dh;

my (%entry, %path);
for my $f (@files) {
    my $e = eval { YAML::XS::LoadFile("$algdir/$f") } or next;
    next unless $e->{id};
    $entry{ $e->{id} } = $e;
    $path{  $e->{id} } = "$algdir/$f";
}

#-----------------------------------------------------------------------
# Group by mdxfind identity.

my %group;
for my $id (sort keys %entry) {
    my $m = $entry{$id}{tools}{mdxfind} or next;
    my $it = $m->{iterations} // 1;
    for my $t (@{ $m->{types} || [] }) {
        push @{ $group{ uc($t) . '#' . $it } }, $id;
    }
}

#-----------------------------------------------------------------------
# Helpers.

my %TIER_RANK = (absent => 0, asserted => 1, upstream => 2, vector => 3);

# idents($entry, $tool) - the identifier list for a tool, as a flat list.
sub idents {
    my ($e, $tool) = @_;
    my $b = $e->{tools}{$tool} or return ();
    return @{ $b->{modes} || [] } if $tool eq 'hashcat';
    return @{ $b->{types} || [] } if $tool eq 'mdxfind';
    return (@{ $b->{cpu} || [] }, @{ $b->{gpu} || [] }) if $tool eq 'john';
    return ();
}

# conflicts($a, $b) - true when some tool names identifiers in both entries
# with nothing in common. See methodology.
sub conflicts {
    my ($x, $y) = @_;
    for my $tool (qw(hashcat mdxfind john)) {
        my @a = idents($x, $tool);
        my @b = idents($y, $tool);
        next unless @a && @b;
        my %in = map { lc($_) => 1 } @a;
        return $tool unless grep { $in{ lc $_ } } @b;
    }
    return '';
}

# generated_name($entry) - true when the name is just a tool's own label,
# which is what the importer produced for a row with a blank Algorithm cell.
sub generated_name {
    my ($e) = @_;
    my $n = uc($e->{name} // '');
    $n =~ s/[^A-Z0-9]//g;
    for my $t (@{ $e->{tools}{mdxfind}{types} || [] }) {
        (my $c = uc $t) =~ s/[^A-Z0-9]//g;
        return 1 if $n eq $c;
    }
    return 0;
}

# score($entry) - how good a survivor this entry is. Higher wins.
sub score {
    my ($e) = @_;
    my $s = 0;
    $s += 1000 unless generated_name($e);           # a name a person would use
    for my $tool (qw(hashcat mdxfind john)) {
        my $b = $e->{tools}{$tool} or next;
        $s += 10 * ($TIER_RANK{ $b->{verified} // 'asserted' } // 1);
        $s += scalar idents($e, $tool);
    }
    $s += 5 if $e->{legacy};
    $s += 2 if $e->{notes};
    return $s;
}

# merge_into($survivor, $loser) - fold everything the loser knows into the
# survivor. Nothing is dropped; see methodology.
sub merge_into {
    my ($s, $l) = @_;

    for my $tool (qw(hashcat mdxfind john crack)) {
        my $lb = $l->{tools}{$tool} or next;
        my $sb = $s->{tools}{$tool};

        if (!$sb) { $s->{tools}{$tool} = $lb; next }

        for my $key (qw(modes types cpu gpu)) {
            next unless $lb->{$key};
            my %have = map { lc($_) => 1 } @{ $sb->{$key} || [] };
            push @{ $sb->{$key} }, grep { !$have{ lc $_ }++ } @{ $lb->{$key} };
            @{ $sb->{$key} } = $key eq 'modes'
                ? sort { $a <=> $b } @{ $sb->{$key} }
                : sort @{ $sb->{$key} };
        }

        # Keep the better-evidenced tier, and carry its provenance with it.
        my $sr = $TIER_RANK{ $sb->{verified} // 'asserted' } // 1;
        my $lr = $TIER_RANK{ $lb->{verified} // 'asserted' } // 1;
        if ($lr > $sr) {
            $sb->{$_} = $lb->{$_} for grep { defined $lb->{$_} }
                qw(verified verified_at verified_with note);
        }

        # 'absent' cannot stand once identifiers are present.
        delete $sb->{verified}
            if ($sb->{verified} // '') eq 'absent' && idents($s, $tool);

        $sb->{iterations} //= $lb->{iterations} if $lb->{iterations};
    }

    # The loser's name survives as an alias so searches still find it.
    if (($l->{name} // '') ne ($s->{name} // '')) {
        my %have = map { lc($_) => 1 } @{ $s->{aliases} || [] };
        push @{ $s->{aliases} }, $l->{name}
            unless $have{ lc $l->{name} } || generated_name($l);
    }

    for my $vec (@{ $l->{vectors} || [] }) {
        my $k = ($vec->{hash} // '') . '|' . ($vec->{pass} // '');
        next if grep { (($_->{hash} // '') . '|' . ($_->{pass} // '')) eq $k }
                     @{ $s->{vectors} || [] };
        push @{ $s->{vectors} }, $vec;
    }

    for my $k (qw(hashes_org hashkiller)) {
        $s->{legacy}{$k} //= $l->{legacy}{$k} if defined $l->{legacy}{$k};
    }

    for my $k (qw(expression john_dynamic_expr category)) {
        $s->{$k} //= $l->{$k} if defined $l->{$k};
    }

    if (defined $l->{notes} && length $l->{notes}) {
        my $n = $s->{notes} // '';
        $s->{notes} = length $n ? "$n; $l->{notes}" : $l->{notes}
            unless index($n, $l->{notes}) >= 0;
    }

    return;
}

#-----------------------------------------------------------------------
# Plan the merges.

my (@merges, @conflicted, %gone);

for my $key (sort keys %group) {
    my @ids = grep { !$gone{$_} } @{ $group{$key} };
    next unless @ids > 1;

    # Best survivor first; ties broken by id so the result is deterministic.
    @ids = sort { score($entry{$b}) <=> score($entry{$a}) || $a cmp $b } @ids;
    my $keep = shift @ids;

    for my $id (@ids) {
        if (my $tool = conflicts($entry{$keep}, $entry{$id})) {
            push @conflicted, sprintf('%s vs %s: %s mappings are disjoint (%s | %s)',
                $keep, $id, $tool,
                join(',', idents($entry{$keep}, $tool)) || '-',
                join(',', idents($entry{$id},  $tool)) || '-');
            next;
        }
        push @merges, [$keep, $id, $key];
        $gone{$id} = 1;
    }
}

#-----------------------------------------------------------------------
# Preview or apply.

if (!$apply) {
    print STDERR "\n";
    print STDERR "  ##  PREVIEW ONLY - nothing has been changed  ##\n\n";
    printf STDERR "- %d entr%s would be merged away, out of %d\n",
        scalar @merges, (@merges == 1 ? 'y' : 'ies'), scalar keys %entry;
    printf STDERR "- %d group(s) would remain after merging\n",
        scalar(keys %entry) - scalar(@merges);
    printf STDERR "- %d file(s) would be DELETED from %s\n", scalar @merges, $algdir;
    print  STDERR "- every entry is committed to git, so a bad merge is recoverable\n";
    print  STDERR "  with 'git checkout -- data/algorithms'\n\n";

    my $n = 0;
    for my $m (@merges) {
        printf STDERR "-   keep %-34s <- merge %-34s [%s]\n",
            $m->[0], $m->[1], $m->[2];
        last if ++$n >= ($verbose ? scalar @merges : 15);
    }
    printf STDERR "-   ... and %d more\n", scalar(@merges) - $n if @merges > $n;
}
else {
    for my $m (@merges) {
        my ($keep, $drop) = @$m;
        merge_into($entry{$keep}, $entry{$drop});
    }
    my $written = 0;
    my %touched = map { $_->[0] => 1 } @merges;
    $written += emit_entry($path{$_}, $entry{$_}) for sort keys %touched;

    my $deleted = 0;
    for my $m (@merges) {
        $deleted += unlink $path{ $m->[1] };
    }

    printf STDERR "- merged %d entr%s into %d survivor(s)\n",
        scalar @merges, (@merges == 1 ? 'y' : 'ies'), scalar keys %touched;
    printf STDERR "- rewrote %d file(s), deleted %d\n", $written, $deleted;
    printf STDERR "- entries remaining: %d\n", scalar(keys %entry) - scalar(@merges);
}

if (@conflicted) {
    printf STDERR "\n- %d pair(s) share an mdxfind identity but have disjoint mappings.\n",
        scalar @conflicted;
    print  STDERR "  These are NOT duplicates and were left alone; a human should look:\n";
    my $n = 0;
    for (@conflicted) { print STDERR "-   $_\n"; last if ++$n >= ($verbose ? @conflicted : 10) }
    printf STDERR "-   ... and %d more\n", scalar(@conflicted) - $n if @conflicted > $n;
}

exit 0;
