#!/usr/bin/perl
#
# denote-hx.pl -- record how mdxfind's own specification denotes the types
#                 that have no expression in john's dynamic language
#
# PURPOSE
#
# seed-hx.pl transcribes Appendix A of the hx Language Specification into
# expression: wherever the construction can be written in this repository's
# notation. It refuses far more types than it accepts, and until now the
# refusals left the entry's expression column simply empty -- which tells a
# reader nothing, and re-poses the same question to every future run.
#
# This is the other side of that boundary. Where the refusal is a CHECKABLE
# FACT -- upstream names a function that john's dynamic expression language
# does not have, or the type emits several candidate digests per input -- the
# entry can say so once, permanently, and carry upstream's own wording as the
# answer to "what is this algorithm".
#
#     expression_proof:
#       verified: "absent"
#       note: "... names pbkdf2_sha256(), which john's dynamic expression
#              vocabulary does not have ..."
#     denotation:
#       text: "pbkdf2_sha256(pass, salt, 20000, 32)"
#       source: "mdxfind"
#
# WHY THIS IS BETTER EVIDENCE THAN derive-expressions.pl --denote
#
# That pass reads the entry's own name: field, so its denotation is only as
# good as whatever the sheet happened to write in it -- and for most of these
# entries the name is just the mdxfind type name, which denotes nothing. Here
# the text comes from the tool's own specification of its own type, so
# source: "mdxfind" is literally true: the schema says a tool name means the
# denotation restates that tool's own label, and the type is already in
# tools.mdxfind.types. It is attributed, not asserted.
#
# WHAT "ABSENT" IS AND IS NOT
#
# It says: this construction cannot be written in john's dynamic EXPRESSION
# language. It emphatically does NOT say john cannot crack it -- john has
# formats for bcrypt, for PBKDF2-HMAC-SHA1 and for descrypt, and where it
# does they are already in tools.john.cpu. Two different sentences, and the
# note written on each entry says so.
#
# THE VOCABULARY IS LOOKED UP, NEVER ASSERTED
#
# A token qualifies only if it is outside BOTH boundaries: RosettaHx's %FUNC,
# which is what this repository can spell in an expression, and the function
# vocabulary harvested from john's own --list=subformats, which is what john
# has demonstrated it can compile. Checking both is the point -- %FUNC admits
# cut() and pad() deliberately, because an hx-style expression may carry them
# at tier upstream, so %FUNC alone would call them grounds for `absent` and
# contradict seed-hx.pl on the same type. A token in one boundary but not the
# other is reported and never written.
#
# WHAT IT WILL NOT TOUCH
#
# - An entry that already has an expression: (except under --repair, below)
#   or an existing denotation:. Both are somebody's answer already.
# - A type whose appendix text is prose rather than an expression --
#   "Note [20]", "(complex: iterates single-char salts)". There the appendix
#   declines to state the construction, so "no expression exists" is a shrug
#   and not a lookup, and a human should answer it.
# - A type refused for stray-literal, unknown-operand or multi-statement.
#   Those MIGHT be expressible -- john's dynamic has $c1..$c8 constants and
#   $s2 -- and denoting them now would foreclose an expression later, which
#   validate.pl then forbids from ever being added.
#
# --repair: THE NINE MALFORMED EXPRESSIONS
#
# seed-hx.pl's earlier parser wrote expressions that are not well-formed in
# this repository's notation: two with a prose gloss glued on the end
# ("sha256($s.$p)(hMailServer)"), six carrying a bare hx operand (salt2,
# pepper), one carrying an hx function this repository has no spelling for.
# --repair finds them with the same boundary check and removes the claim,
# leaving the entry for seed-hx.pl to re-transcribe correctly or for the
# normal pass here to denote. It never silently rewrites one into something
# else: an expression nobody can compile is a claim, and a wrong claim gets
# withdrawn rather than adjusted.
#
# The specification is NOT vendored: this repository is MIT throughout and
# the PDF carries no licence grant. Re-fetch it to tmp/hx/ to re-run this.
#
# Usage: denote-hx.pl [--appendix FILE] [--repair] [--apply] [-v]
#
# Generated by Claude Opus 5 on 2026-08-31

use strict;
use warnings;
use FindBin qw($RealBin);
use lib "$RealBin/lib";
use Getopt::Long qw(GetOptions);
use File::Basename qw(basename);
use YAML::XS qw(LoadFile);
use RosettaEmit qw(emit_entry);
use RosettaHx qw(parse_appendix translate_hx is_multi_emit %FUNC);

# verified_at is an AUDIT field: it says when the check ran, so it has to be
# today's date and never a literal. seed-hx.pl carried '2026-08-31' hardcoded
# and stamped it on work done two days later until 989e06f; this tool had the
# identical bug in three places and stamped 2026-08-31 on ten entries denoted
# on 2026-09-02 before it was found. Same class as the prose staleness gate,
# one layer down in the data.
my $TODAY = do { my @t = localtime; sprintf '%04d-%02d-%02d',
                 $t[5] + 1900, $t[4] + 1, $t[3] };
use RosettaTools qw(tool_path tool_env_help);

my $PROG = basename($0);

# Types whose multi-emit status comes from mdxfind's SOURCE and a measurement
# rather than from a document, with the sentence that says so. RosettaHx's
# %MULTI_SOURCE decides membership; this only supplies the citation, so the
# two cannot drift about WHICH types -- only about the wording.
my $ONESALT_CITE =
    'Established from mdxfind\'s own source and a measurement, not from a '
  . 'document: Appendix A writes only the prose "(complex: iterates over '
  . 'single-char salts)" for this family and Note [24] does not name it. '
  . 'mdxfind.c sweeps a single salt byte over 9 and 32..126 -- 96 values -- '
  . 'and emits five placements at each (s.d, d.s, s.d.s, s.s.d and d.s.s, '
  . 'where d is the hex inner digest); "mdxfind -z" prints 480 candidates per '
  . 'password, which is 5 x 96. Measured 2026-09-02 against RCS 1.545. The '
  . 'name and aliases on this entry are those five placements.';
my %MULTI_SOURCE_TEXT = map { $_ => $ONESALT_CITE }
  qw(MD51SALTMD5 MD51SALTMD5UC MD51SALTMD5MD5 MD51SALTMD5MD5MD5
     MD51SALTMD5MD5MD5MD5 MD51SALTMD5MD5MD5MD5MD5
     SHA11SALTMD5 SHA11SALTMD5UC SHA11SALTMD5SHA256 SHA1MD51SALTMD5);
my $ROOT = "$RealBin/..";

my $appendix = "$ROOT/tmp/hx/appA.txt";
my $algdir   = "$ROOT/data/algorithms";
my $subfile;
my $john;
my ($apply, $repair, $verbose, $help) = (0, 0, 0, 0);
my $had_args = scalar @ARGV;

sub usage {
    print STDERR <<"USAGE";

Usage: $PROG [options]

   --appendix FILE   parsed Appendix A text  (default: tmp/hx/appA.txt)
   --algorithms DIR  curated entries         (default: data/algorithms)
   --john PATH       john binary             (default: @{[tool_env_help('john')]})
   --subformats PATH read john's listing from a file instead of running it
   --repair          also withdraw expressions that are not well-formed in
                     this repository's notation, so seed-hx.pl can
                     re-transcribe them or this tool can denote them
   --apply           write; without it, report only
   -v, --verbose     per-entry detail on stderr (repeatable)
   -h, --help        this help

   Writes denotation: + expression_proof verified:absent, and only where the
   appendix states an expression whose function tokens john's dynamic
   language does not have, or where the type is multi-emit. Never touches an
   entry that already has an expression: or a denotation:.

   Exit 0 success, 1 error, 2 usage.

USAGE
    exit 2;
}

GetOptions(
    'appendix=s'   => \$appendix,
    'algorithms=s' => \$algdir,
    'john=s'       => \$john,
    'subformats=s' => \$subfile,
    'repair'       => \$repair,
    'apply'        => \$apply,
    'verbose|v+'   => \$verbose,
    'help|h'       => \$help,
) or usage();
usage() if $help || !$had_args;
unless (-f $appendix) {
    print STDERR "$PROG: no appendix at $appendix; re-fetch hx.pdf (see STATE.md)\n";
    exit 1;
}

#-----------------------------------------------------------------------
# john's vocabulary, harvested rather than hand-listed. Same method
# derive-expressions.pl uses: every function name appearing in one of the
# ~474 worked examples --list=subformats prints is a function this build has.

my $listing;
if (defined $subfile) {
    open my $fh, '<', $subfile or do {
        print STDERR "$PROG: cannot read $subfile: $!\n"; exit 1 };
    local $/; $listing = <$fh>; close $fh;
}
else {
    $john //= tool_path('john');
    my $jd = $john; $jd =~ s{/[^/]+$}{};
    my $jb = basename($john);
    $listing = qx{cd @{[quotemeta $jd]} && ./@{[quotemeta $jb]} --list=subformats 2>/dev/null};
}
my %JOHN_FN;
$JOHN_FN{$1} = 1 while ($listing // '') =~ /([a-z][a-z0-9_]*)\(/g;
$JOHN_FN{"${_}_raw"} = 1 for grep { !/_raw$/ } keys %JOHN_FN;
unless (keys %JOHN_FN > 20) {
    print STDERR "$PROG: john's subformat listing yielded no vocabulary.\n";
    exit 1;
}
printf STDERR "- john vocabulary: %d function name(s)\n", scalar keys %JOHN_FN;

sub john_version {
    my $y = eval { YAML::XS::LoadFile("$ROOT/data/tools/john.yaml") };
    my $v = $y && $y->{version};
    return (defined $v && length $v) ? "john $v" : 'john';
}
my $JVER = john_version();

my $hx = parse_appendix($appendix);
printf STDERR "- appendix: %d type(s)\n", scalar keys %$hx;

my $HXCITE = 'hx Language Specification $Revision: 1.15$ (Waffle, Aug 2026), Appendix A';

#-----------------------------------------------------------------------
# ill_formed($expression) - the reasons an expression: already in the corpus
# cannot be what this repository says it is, or () if it is fine. The legal
# vocabulary is the IMAGE of %FUNC -- this repository's spelling of what hx
# offers -- widened by everything john demonstrates.

my %LEGAL = map { $_ => 1 } values %FUNC;
$LEGAL{"${_}_raw"} = 1 for grep { !/_raw$/ } keys %LEGAL;
$LEGAL{$_} = 1 for keys %JOHN_FN;

sub ill_formed {
    my ($x) = @_;
    return () unless defined $x && length $x;
    my @why;
    my $bal = 0;
    for my $c (split //, $x) { $bal++ if $c eq '('; $bal-- if $c eq ')' }
    push @why, 'has unbalanced parentheses' if $bal != 0;
    # ")(" is a prose gloss that was concatenated onto a finished expression
    push @why, 'carries a parenthesised group after what is already a complete '
             . 'expression, which is how a prose gloss reaches the data' if $x =~ /\)\(/;
    my (%seen, @unk, @bare);
    while ($x =~ /(?<![\$\w])([A-Za-z][A-Za-z0-9_]*)(\(?)/g) {
        my ($t, $isfn) = ($1, $2);
        next if $seen{"$t$isfn"}++;
        if ($isfn eq '(') { push @unk,  $t unless $LEGAL{$t} }
        else              { push @bare, $t }
    }
    push @why, 'names ' . join(', ', map {"$_()"} @unk)
             . ', which this repository has no expression spelling for' if @unk;
    push @why, 'carries the bare operand' . (@bare > 1 ? 's ' : ' ')
             . join(', ', @bare) . ', which john\'s dynamic language cannot bind' if @bare;
    return @why;
}

#-----------------------------------------------------------------------

opendir my $dh, $algdir or do { print STDERR "$PROG: $algdir: $!\n"; exit 1 };
my @files = sort grep { /\.yaml$/ } readdir $dh;
closedir $dh;

my ($seen, $denoted, $repaired, %skip, @disagree) = (0, 0, 0);

for my $f (@files) {
    my $path = "$algdir/$f";
    my $e = eval { LoadFile($path) } or next;
    next unless $e->{id};
    next if ($e->{status} // '') eq 'merged';

    my $types = $e->{tools}{mdxfind}{types};
    next unless ref $types eq 'ARRAY' && @$types;
    my ($type) = grep { $hx->{$_} } @$types;
    next unless $type;
    $seen++;

    #-- --repair: withdraw a claim this repository cannot honour -----------
    if (defined $e->{expression} && length $e->{expression}) {
        my @why = ill_formed($e->{expression});
        if (@why && $repair) {
            printf STDERR "REPAIR %-34s %s\n         %s\n",
                $e->{id}, $e->{expression}, join('; ', @why);
            $repaired++;
            if ($apply) {
                my $was = $e->{expression};
                delete $e->{expression};
                delete $e->{john_dynamic_expr};
                $e->{expression_proof} = {
                    verified   => 'absent',
                    verified_at=> $TODAY,
                    verified_with => $JVER,
                    note => "Withdrawn $TODAY. This entry carried the expression "
                          . "\"$was\", transcribed from the $HXCITE entry for mdxfind "
                          . "type $type ($hx->{$type}{index}) by a parser that has since "
                          . "been corrected: it " . join('; and it ', @why) . ". Nothing "
                          . "can compile that string, so it was a claim rather than a "
                          . "fact, and it is withdrawn rather than adjusted -- guessing "
                          . "what upstream meant is exactly what the expression field "
                          . "exists to stop. Re-run seed-hx.pl and denote-hx.pl to "
                          . "settle this entry from the corrected parse.",
                };
                emit_entry($path, $e);
            }
            next;
        }
        elsif (@why) {
            $skip{'ill-formed expression (use --repair)'}++;
            printf STDERR "  ILL-FORMED %-28s %s\n", $e->{id}, $e->{expression} if $verbose;
            next;
        }
        $skip{'already has an expression'}++;
        next;
    }
    if ($e->{denotation}) { $skip{'already has a denotation'}++; next }

    #-- the two qualifying facts ------------------------------------------
    my ($expr, $why, $tokens) = translate_hx($hx->{$type}{expr});
    my $multi = is_multi_emit($type, $hx->{$type});

    # The deferral to seed-hx.pl must come AFTER the multi-emit test, not
    # before it. A multi-emit type's appendix row is often perfectly
    # expressible -- GOSTHEXSALT reads gost(pass . salt), SHA1RMD160TRUNC
    # reads sha1(cut(rmd160(pass),0,32)) -- so testing expressibility first
    # sent it to seed-hx.pl, which then refused it BECAUSE it is multi-emit,
    # and nothing wrote anything. Measured 2026-09-02: seed-hx.pl was skipping
    # 61 types as multi-emit while this tool was deferring to it, and the
    # HEXSALT and TRUNC families sat with no expression and no denotation
    # because each tool believed the other had them. CLAUDE.md is explicit
    # that such a type gets a denotation and never an expression, so this is
    # where they belong.
    if (defined $expr && !$multi) {
        $skip{'expressible: seed-hx.pl writes this one'}++;
        next;
    }

    # THE PASSWORD GUARD, and it is not paranoia. Appendix A's rows for e308
    # SHA1MD5USER, e354 MD5CAPMD5USER and e355 MD5CAPMD5MD5USER read
    # "sha1(md5(user))" and "md5(cap(md5(user)))" -- the password operand is
    # simply missing, and Note [24] gives the real forms as
    # H(hex32(md5(pass)) . user) and H(hex32(md5(pass)) . ":" . user).
    # Compare e286 MD5MD5USER, which upstream writes correctly. Transcribing
    # a row that never mentions the password would publish upstream's slip as
    # this repository's answer to "what is this algorithm", so those go to a
    # person instead. Same rule seed-hx.pl applies to expression:.
    # The password guard is a check on APPENDIX A's text, so it applies only
    # where the text being transcribed is Appendix A's. For a type RosettaHx
    # knows is multi-emit from mdxfind's own source and a measurement,
    # Appendix A is not the source being used -- the 1SALT family's row is the
    # prose "(complex: iterates over single-char salts)", which names no
    # password because upstream declined to state the construction at all. The
    # entry's own name does state it, and for these types it states it
    # correctly: MD51SALTMD5 carries md5(md5($plain).$salt) plus four aliases,
    # which are exactly the five placements the source emits.
    my $from_source = $MULTI_SOURCE_TEXT{$type} ? 1 : 0;

    unless ($from_source || $hx->{$type}{expr} =~ /\bpass\b/) {
        $skip{'appendix row never mentions the password'}++;
        printf STDERR "  NO-PASS %-30s %-22s %s\n", $e->{id}, $type,
            $hx->{$type}{raw};
        next;
    }

    my ($text, $note, $proofnote);

    if ($multi) {
        # Appendix A's expression where it states one; the entry's own name
        # where upstream wrote prose instead and the source settled it.
        $text = $from_source ? ($e->{name} // $type) : $hx->{$type}{expr};
        $proofnote = ($from_source ? "$MULTI_SOURCE_TEXT{$type} " : '') .
            "mdxfind type $type ($hx->{$type}{index}) is MULTI-EMIT: it computes "
          . "several candidate digests per input and matches if any one reproduces "
          . "the stored hash. There is therefore no single expression to record, and "
          . "writing one of the emitted forms into expression: would be a false claim "
          . "even though the string itself is correct. This is also why two vectors of "
          . "such a type can disagree with each other, and why a tool matching one of "
          . "them is not evidence about the other.";
        $note =
            "$HXCITE, entry for mdxfind type $type ($hx->{$type}{index}), which states "
          . "$hx->{$type}{raw}. This is what the type emits, not a single construction "
          . "-- see expression_proof.";
    }
    elsif (($why // '') eq 'unknown-token') {
        my @tok = split /,/, ($tokens // '');
        # Both boundaries must agree, or this is not a lookup.
        my @injohn = grep { $JOHN_FN{$_} } @tok;
        if (@injohn) {
            push @disagree, sprintf "%-34s %-22s %s", $e->{id}, $type, join(',', @injohn);
            $skip{'boundaries disagree: john has the token, %FUNC does not'}++;
            next;
        }
        $text = $hx->{$type}{expr};
        my $list = join(', ', map { "$_()" } @tok);
        $proofnote =
            "the construction upstream states for mdxfind type $type "
          . "($hx->{$type}{index}) names $list, which john's dynamic EXPRESSION "
          . "vocabulary does not have -- checked against the function names appearing "
          . "in john's own --list=subformats, so this is a lookup and not an opinion. "
          . "It says nothing about whether john can CRACK this: john has formats for "
          . "plenty of these constructions, and where it does they are in "
          . "tools.john.cpu. The wording upstream uses is kept in denotation:.";
        $note =
            "$HXCITE, entry for mdxfind type $type ($hx->{$type}{index}), which states "
          . "$hx->{$type}{raw}.";
    }
    elsif (($why // '') eq 'multi-statement') {
        # An hx PROGRAM, not an expression: MD5HESK is
        # h=""; for i=0 to length(pass)-1 { h=h.md5(cut(pass,i,1)) }; md5(h)
        # -- a loop over the password's characters. This IS a checkable
        # absence, and a stronger one than a missing function: john's dynamic
        # grammar admits a SINGLE outer hash expression and has no statements,
        # no assignment and no iteration over a string at all
        # (doc/DYNAMIC_EXPRESSIONS, "The expression MUST be a single crypt-hash
        # expression"). No vocabulary could close that gap, so nothing is
        # foreclosed by saying so. Confirmed against mdxfind's source
        # 2026-09-02: mdxfind.c's JOB_MD5HESK loops md5 over each character,
        # stages each as 32 hex, and hashes the concatenation, which is
        # upstream's statement exactly; "mdxfind -z" prints one candidate, so
        # it is single-emit and the construction is genuinely singular.
        $text = $hx->{$type}{expr};
        $proofnote =
            "the construction upstream states for mdxfind type $type "
          . "($hx->{$type}{index}) is a multi-statement hx PROGRAM -- it "
          . "assigns to a variable and loops over the characters of the "
          . "password. john's dynamic expression language has no statements, "
          . "no assignment and no iteration: doc/DYNAMIC_EXPRESSIONS requires "
          . "a SINGLE outer crypt-hash expression, so this is not a gap a "
          . "wider function vocabulary could ever close. Verified against "
          . "mdxfind's own source on 2026-09-02 (RCS 1.545), which implements "
          . "exactly the loop upstream describes and emits one candidate. It "
          . "says nothing about whether john can CRACK this.";
        $note =
            "$HXCITE, entry for mdxfind type $type ($hx->{$type}{index}), which states "
          . "$hx->{$type}{raw}.";
    }
    elsif (($why // '') eq 'unknown-operand'
           && ($tokens // '') =~ /(?:^|,)pepper(?:,|$)/) {
        # 'pepper' is not a missing FUNCTION, it is a missing INPUT. hx makes
        # it a built-in variable beside pass, salt and salt2 (hx.y line 19)
        # with its own VM slot, and mdxfind reads it from a file: -j for the
        # global array, -P for the per-type set. john's dynamic language has
        # no site-wide-secret variable. $s2 is not one -- it is a second
        # PER-HASH salt -- and a $c1 constant is not one either, because a
        # constant has to be written into the expression and the whole point
        # of a pepper is that its value is not in any hash. So this absence is
        # checkable in the strong sense: it holds for every possible value.
        #
        # This is the one case where denoting an unknown-operand type is
        # right. The general rule stands and the residue is still left alone,
        # because john HAS constants and a second salt, so most of what
        # translate_hx calls an unknown operand might yet be provable.
        $text = $hx->{$type}{expr};
        $proofnote =
            "the construction upstream states for mdxfind type $type "
          . "($hx->{$type}{index}) uses a PEPPER: a site-wide secret that "
          . "appears in no hash and cannot be derived from one. hx makes it a "
          . "built-in variable beside pass, salt and salt2, with its own slot "
          . "in the VM, and mdxfind reads it from a file (-j global array, -P "
          . "per-type). john's dynamic expression language has no equivalent: "
          . "\$s2 is a second PER-HASH salt, not a site secret, and a \$c1 "
          . "constant would have to carry the value, which is exactly what a "
          . "pepper does not publish. The absence therefore holds for every "
          . "possible pepper rather than for this vector, which is what makes "
          . "it a lookup. It says nothing about whether john can CRACK this. "
          . "Established from mdxfind's source (hx.y line 19, hx_vm.c "
          . "HX_SLOT_PEPPER) on 2026-09-02.";
        $note =
            "$HXCITE, entry for mdxfind type $type ($hx->{$type}{index}), which states "
          . "$hx->{$type}{raw}.";
    }
    else {
        $skip{"not a checkable absence: $why"}++;
        printf STDERR "  pass %-34s %-22s %-18s %s\n", $e->{id}, $type, $why,
            $hx->{$type}{expr} if $verbose > 1;
        next;
    }

    printf STDERR "+ %-34s %-22s %s%s\n", $e->{id}, $type, $text,
        ($multi ? '   [multi-emit]' : '') if $verbose;
    $denoted++;
    next unless $apply;

    # A --repair pass on an earlier run may have left a withdrawal note here.
    # Keep it: "this entry once claimed an expression nobody could compile" is
    # exactly the kind of thing a reader of a curated row wants to know, and
    # overwriting it would leave only git blame to say so.
    my $prior = $e->{expression_proof}{note} // '';
    $proofnote = "$prior Settled here: " . $proofnote if $prior =~ /^Withdrawn/;

    $e->{expression_proof} = {
        verified      => 'absent',
        verified_at   => $TODAY,
        verified_with => $JVER,
        note          => $proofnote,
    };
    $e->{denotation} = { text => $text, source => 'mdxfind', note => $note };
    emit_entry($path, $e);
}

printf STDERR "\n%s: %d entry/entries with an appendix type, %d %s%s\n",
    $PROG, $seen, $denoted,
    ($apply ? 'denoted' : 'would be denoted (no --apply)'),
    ($repair ? sprintf(', %d expression(s) %s', $repaired,
                       $apply ? 'withdrawn' : 'would be withdrawn') : '');
printf STDERR "  skipped %-52s %d\n", $_, $skip{$_} for sort keys %skip;
if (@disagree) {
    print STDERR "\n  john HAS these tokens but RosettaHx cannot spell them -- the two\n"
               . "  boundaries disagree, so nothing was written. Widen %FUNC or say why:\n";
    print STDERR "    $_\n" for @disagree;
}
exit 0;
