#!/usr/bin/perl
#-----------------------------------------------------------------------
#
# Name: derive-forms.pl
# Description: set vectors[].form from reads_in where the measurement already
#              settles it, and report the native forms only a person can name
# Category: cracking-rosetta data derivation
#
# Project: cracking-rosetta | Phase: 7 - pre-publication readiness
#
#-----------------------------------------------------------------------
# METHODOLOGY AND WHY THIS EXISTS
#
# A credential has a form the producing system stores, and the crackers each
# have a form they will parse. Those are not the same claim and the repository
# now says which is which: vectors[].form. The native form is PRIMARY over any
# tool's rewriting of it -- a tool that reshapes a credential to suit its
# parser has not changed what the credential is -- and primacy is DERIVED from
# that rather than asserted, so there is no flag to fall out of step.
#
# WHAT THIS TOOL MAY DECIDE, AND WHAT IT MAY NOT
#
# It may name a TOOL form, because that is already measured. On an entry whose
# tools SPLIT -- no single string is read by every tool that reads anything --
# a vector read by exactly one tool is that tool's spelling, and reads_in is a
# measurement rather than an opinion: verify-vectors.pl runs every tool against
# every vector with every plaintext the entry carries, so a tool missing from
# the list declined rather than went unasked.
#
# It may NOT name the native form. Nothing in a string says what the producing
# system stores; MediaWiki's $B$<salt>$<hash> is recognisable only if you know
# MediaWiki. So 'native' is curator-set, and this tool's other half is the
# queue: entries whose tools split and where nobody has said which form, if
# any, is the real one.
#
# It also may not label a string read by TWO tools but not all three. scrypt's
# hashcat vector is read by mdxfind as well while john wants $7$86....NaCl$ of
# its own; that string is the spelling two tools share, and form: is
# single-valued on purpose. Measured 2026-09-02: of the 16 entries whose tools
# split, 7 have vectors this rule can label and 14 vectors get a form, with
# nothing ambiguous. The other 9 need the same curator as the native question.
#
# USAGE
#   tools/derive-forms.pl [--apply] [-v]
#   Without --apply nothing is written. Exit 0 success, 1 error, 2 usage.
#
# DEPENDENCIES
#   perl, YAML::XS, tools/lib/RosettaEmit.pm
#
#-----------------------------------------------------------------------
# Generated by Claude Opus 5 on 2026-09-02

use strict;
use warnings;

use FindBin qw($RealBin);
use Getopt::Long qw(GetOptions);
use YAML::XS ();

use lib "$RealBin/lib";
use RosettaEmit qw(emit_entry);

my $PROG = 'derive-forms.pl';
my ($algdir, $apply, $verbose, $help) = ("$RealBin/../data/algorithms", 0, 0, 0);

GetOptions('algorithms=s' => \$algdir, 'apply' => \$apply,
           'verbose|v+' => \$verbose, 'help|h' => \$help)
    or do { usage(); exit 2 };

sub usage {
    print <<"USAGE";
Usage: $PROG [options]

   --algorithms DIR    curated entries   (default: data/algorithms)
   --apply             write vectors[].form
   -v, --verbose       per-entry detail
   -h, --help          this help

   Sets form: to a TOOL name where reads_in already settles it. Never sets
   form: native -- nothing in a string says what the producing system stores,
   so that one is a curator's, and the entries waiting on it are listed.

   Without --apply nothing is written. Exit 0 success, 1 error, 2 usage.
USAGE
}

if ($help) { usage(); exit 0 }
if (!@ARGV && !$apply && !$verbose) { usage(); exit 2 }

opendir(my $dh, $algdir)
    or do { print STDERR "$PROG: cannot read $algdir: $!\n"; exit 1 };
my @files = sort grep { /\.yaml$/ } readdir $dh;
closedir $dh;

my ($seen, $wrote, $entries) = (0, 0, 0);
my (@need_native, @unlabellable);

for my $f (@files) {
    my $path = "$algdir/$f";
    my $e = eval { YAML::XS::LoadFile($path) } or next;
    next unless $e->{id};
    next if ($e->{status} // '') eq 'merged';       # a tombstone is a redirect
    my @v = @{ $e->{vectors} || [] };
    next unless @v;
    $seen++;

    # Do the tools split? Same test render.pl uses for the serialization
    # column, and for the same reason: the question a reader has is not
    # whether SOME pair agrees, it is whether one string serves everything
    # that reads anything here.
    my %tools;
    for my $v (@v) {
        next unless ref $v->{reads_in} eq 'ARRAY';
        $tools{$_} = 1 for @{ $v->{reads_in} };
    }
    next unless keys %tools > 1;
    my $all = join ',', sort keys %tools;
    for my $v (@v) {
        next unless ref $v->{reads_in} eq 'ARRAY';
        next unless join(',', sort @{ $v->{reads_in} }) eq $all;
        %tools = ();                                # one string serves all
        last;
    }
    next unless keys %tools;                        # shared, nothing to say

    my ($changed, @label, @skip) = (0);
    for my $v (@v) {
        next if defined $v->{form};                 # never overwrite, least
                                                    # of all a curator's native
        my @r = ref $v->{reads_in} eq 'ARRAY' ? @{ $v->{reads_in} } : ();
        if (@r == 1) {
            push @label, "$r[0]: $v->{hash}";
            if ($apply) { $v->{form} = $r[0]; $changed = 1 }
            $wrote++;
        }
        elsif (@r > 1) {
            push @skip, sprintf('read by %s, so no single tool owns it',
                                join('+', sort @r));
        }
    }

    push @need_native, $e->{id}
        unless grep { ($_->{form} // '') eq 'native' } @v;
    push @unlabellable, sprintf('%-28s %s', $e->{id}, $_) for @skip;

    if (@label) {
        $entries++;
        printf "%-28s %s\n", $e->{id}, join('  |  ', @label)
            if $verbose || !$apply;
        emit_entry($path, $e) if $apply && $changed;
    }
}

printf STDERR "- %d entry/entries with vectors; %d form(s) on %d entry/entries\n",
    $seen, $wrote, $entries;
printf STDERR "-   nothing written; re-run with --apply\n" unless $apply;

if (@unlabellable) {
    printf "\n# %d vector(s) read by more than one tool but not by all of\n"
         . "# them. form: is single-valued, so the string these tools share\n"
         . "# has no one owner and is left alone.\n", scalar @unlabellable;
    print "# $_\n" for @unlabellable;
}

if (@need_native) {
    printf "\n# %d entry/entries where the tools split and NO native form is\n"
         . "# recorded. Each needs a person to say what the producing system\n"
         . "# actually stores -- or that it stores nothing, because the\n"
         . "# credential only ever existed as a wire message and every string\n"
         . "# here is a cracker's invention. Both answers are useful; the\n"
         . "# missing one is not.\n", scalar @need_native;
    print "# $_\n" for @need_native;
}

exit 0;
