#!/usr/bin/perl
#-----------------------------------------------------------------------
#
# Name: derive-categories.pl
# Description: write category: where a rule can defend it, and leave the rest
#              in the curation queue
# Category: cracking-rosetta deriver
#
# Project: cracking-rosetta | Phase: 7 - fill the largest empty column
#
#-----------------------------------------------------------------------
# METHODOLOGY AND WHY THESE CHOICES
#
# THE PROBLEM IS THE SIZE OF THE ASK, NOT THE DIFFICULTY OF EACH ANSWER
#
# category: is the sheet's old 'class' column: which axis an entry sits on.
# 1251 of 1560 entries have none, and curate.pl duly offers all 1251 as
# questions. Nobody is going to answer 1251 questions, so the column stays
# empty and the CSV ships with its largest field blank.
#
# But most of those answers are already IN the entry. An entry whose proven
# expression is md5($p) is a primitive; one whose mdxfind block declares two
# iterations is iterated. Asking a person for those is asking them to restate
# what the file says. So this derives what a rule can defend, and leaves
# everything else in the queue -- which is the point: a human answering the
# residue is answering the questions that actually need a human.
#
# EVERY RULE WAS CHECKED AGAINST THE ANSWERS A HUMAN ALREADY GAVE
#
# 309 entries were categorised by hand before this existed, and that is a test
# set nobody had to build. Run against them, this ruleset agrees on every entry
# it fires on and contradicts none (measured 2026-09-01). A rule that
# contradicted a curator would be wrong by definition: the curator is the
# authority this tool is trying not to waste.
#
# THE RULES, IN ORDER, AND WHY EACH IS DEFENSIBLE
#
#   1. application: is set            -> application
#      The schema's own definition of the field: it names the product a row is
#      about, which is what category 'application' means.
#
#   2. an encodes/input-encoding edge -> HELD, no category written
#      This is the guard, and it is here because of a real defect. md5uc's
#      expression is md5($p) -- the uppercase hex is not expressible -- so the
#      primitive rule fires on it, and md5uc is an encoding. The relation is
#      what distinguishes them, and it is SYMMETRIC, so it cannot say which
#      side is the encoding: md5 carries the same edge. Both are therefore
#      held. Three entries, and holding them is correct: 'which of these two is
#      the encoded one' is exactly a curator's question.
#
#   3. mdxfind iterations > 1         -> iterated
#      CLAUDE.md: the iteration suffix is identity, MD5x02 is john's dynamic_2.
#      A block declaring N > 1 IS the statement that this is another algorithm
#      applied N times, which is the schema's definition of 'iterated'. It is
#      checked before the expression rules because it says more: an entry with
#      both is iterated, not merely composite.
#
#   4. proven expression, exactly F($p)  -> primitive
#   5. proven expression, anything else  -> composite
#      'primitive: one hash function over the plaintext' is literally the shape
#      F($p). Everything else with an expression is a construction. Where the
#      line falls between them was NOT decided here: md5-pass-salt (md5($p.$s))
#      and md5-salt-pass (md5($s.$p)) were already categorised 'composite' by a
#      curator, so a single hash over a salted concatenation is composite in
#      this repository, and rule 5 follows that rather than inventing a rule.
#
#      Only tier 'vector' or 'upstream' counts. An 'asserted' expression is a
#      human's claim, and deriving a category from it would launder that claim
#      into a second field at a strength it never had.
#
# WHAT IS DELIBERATELY NOT DERIVED
#
# kdf and protocol. The tempting rule is to read denotation: and call anything
# containing pbkdf2(), scrypt() or argon2() a kdf. Measured 2026-09-01 against
# the human answers, it fires on keepass-argon2-kdbx-v4,
# scryptcrypt-scrypt-unix and terra-station-wallet-...-pbkdf2-pass, all three
# of which a curator called 'application' -- correctly, because they are
# products that USE a KDF. Distinguishing "is a KDF" from "is a product built
# on one" is judgement, not a lookup, so it stays a question. That leaves ~675
# entries in the queue, and that number is the honest one.
#
# NOTHING IS EVER OVERWRITTEN
#
# An entry that already has a category: is never touched, in either direction.
# --check reports where a rule disagrees with an existing value, because that
# is either a bad rule or a bad entry and both are worth knowing, but it is a
# report and never an edit.
#
#-----------------------------------------------------------------------
# Generated by Claude Opus 5 on 2026-09-01

use strict;
use warnings;

use File::Basename qw(basename);
use FindBin qw($RealBin);
use Getopt::Long qw(GetOptions);
use YAML::XS ();

use lib "$RealBin/lib";
use RosettaEmit qw(emit_entry);

my $PROG = basename($0);
my $ROOT = "$RealBin/..";

sub usage {
    print STDERR <<"END_USAGE";

Usage: $PROG [options]

   --algorithms DIR  curated entries (default: data/algorithms)
   --only ID         consider just this entry (repeatable)
   --check           also report where a rule disagrees with a category a
                     human already wrote; never edits either way
   --apply           write the derived categories into data/algorithms
   -v, --verbose     one line per derivation (repeatable: also the held ones)
   -h, --help        this help

   Without --apply nothing is written: the run reports what it would derive.
   Exit 0 success, 1 error, 2 usage.

END_USAGE
    return;
}

my ($algdir, $apply, $check, $help);
my @only;
my $verbose  = 0;
my $had_args = scalar @ARGV;      # house rule: no arguments means show usage

GetOptions(
    'algorithms=s' => \$algdir,
    'only=s'       => \@only,
    'check'        => \$check,
    'apply'        => \$apply,
    'v|verbose+'   => \$verbose,
    'h|help'       => \$help,
) or do { usage(); exit 2 };

if ($help)     { usage(); exit 0 }
if (!$had_args) { usage(); exit 2 }

$algdir //= "$ROOT/data/algorithms";
my %only = map { $_ => 1 } @only;

#-----------------------------------------------------------------------
# The ruleset. Returns (category, why) or (undef, why); the 'why' is printed
# under --verbose and is the whole audit trail, so it names the evidence
# rather than the rule number.

sub derive {
    my ($e) = @_;

    # 1. The field exists precisely to say this.
    return ('application', 'application: names a product')
        if defined $e->{application};

    # 2. The guard. See the methodology note on md5uc.
    for my $r (@{ $e->{relations} || [] }) {
        next unless $r->{kind} eq 'encodes' || $r->{kind} eq 'input-encoding';
        return (undef, "held: a $r->{kind} edge to $r->{entry} means the "
                     . 'expression cannot tell this row from the one it encodes');
    }

    # 3. An iteration count IS the claim that this is another entry applied N
    #    times, and it outranks the expression rules because it says more.
    my $it = $e->{tools}{mdxfind}{iterations} // 1;
    return ('iterated', "tools.mdxfind.iterations = $it")
        if $it > 1;

    # 4/5. Only a proven expression counts; see the methodology note.
    my $tier = $e->{expression_proof}{verified} // '';
    my $x    = $e->{expression};
    if (defined $x && length $x && ($tier eq 'vector' || $tier eq 'upstream')) {
        # ^ one function name, then $p alone, then close: md5($p), haval128_3($p).
        return ('primitive', "expression $x is one function of \$p alone (tier $tier)")
            if $x =~ /^\w[\w.-]*\(\s*\$p\s*\)$/;
        return ('composite', "expression $x is a construction, not one function "
                           . "of \$p alone (tier $tier)");
    }

    return (undef, 'no rule: no application:, no iteration count and no proven '
                 . 'expression');
}

#-----------------------------------------------------------------------
# Walk.

opendir(my $dh, $algdir) or do { print STDERR "$PROG: cannot read $algdir: $!\n"; exit 1 };
my @files = sort grep { /\.yaml$/ } readdir $dh;
closedir $dh;

my (%yield, %held_why, @disagree, @write);
my ($seen, $tombstone, $already, $held, $norule) = (0, 0, 0, 0, 0);

for my $f (@files) {
    my $p = "$algdir/$f";
    my $e = eval { YAML::XS::LoadFile($p) };
    unless ($e && $e->{id}) { print STDERR "$PROG: cannot load $p\n"; next }
    next if @only && !$only{ $e->{id} };
    # A tombstone is not an algorithm and validate.pl forbids a category on it.
    if (($e->{status} // '') eq 'merged') { $tombstone++; next }
    $seen++;

    my ($cat, $why) = derive($e);

    if (defined $e->{category}) {
        $already++;
        push @disagree, [$e->{id}, $e->{category}, $cat, $why]
            if $check && defined $cat && $cat ne $e->{category};
        next;
    }

    unless (defined $cat) {
        $why =~ /^held/ ? $held++ : $norule++;
        $held_why{ $e->{id} } = $why if $why =~ /^held/;
        printf STDERR "-   %-46s %s\n", $e->{id}, $why if $verbose > 1;
        next;
    }

    $yield{$cat}++;
    push @write, [$p, $e, $cat];
    printf STDERR "-   %-46s %-11s %s\n", $e->{id}, $cat, $why if $verbose;
}

#-----------------------------------------------------------------------
# Report on stdout so it can be redirected; counts on stderr per the house
# convention.

printf "%-46s %s\n", $_->[1]{id}, $_->[2] for @write;

if ($check) {
    if (@disagree) {
        print "\n# a rule disagrees with a category a human wrote -- one of the\n"
            . "# two is wrong, and neither is edited here\n";
        printf "# %-44s have=%-11s rule=%-11s %s\n", @$_ for @disagree;
    }
    else {
        print STDERR "- --check: no rule contradicts any of the $already "
                   . "category/categories already written\n";
    }
}

printf STDERR "- %d entry/entries (%d tombstone(s) skipped); %d already had a "
            . "category\n", $seen, $tombstone, $already;
printf STDERR "-   derived %d: %s\n", scalar @write,
    join('  ', map { "$_ $yield{$_}" } sort keys %yield) || '(none)';
printf STDERR "-   left for a curator: %d with no rule, %d held by an "
            . "encoding edge (%s)\n", $norule, $held,
    join(' ', sort keys %held_why) || '-';

#-----------------------------------------------------------------------
# Apply.

if ($apply) {
    my $changed = 0;
    for my $w (@write) {
        my ($p, $e, $cat) = @$w;
        $e->{category} = $cat;
        $changed += emit_entry($p, $e);
    }
    printf STDERR "-   files rewritten: %d\n", $changed;
}
elsif (@write) {
    print STDERR "-   nothing written; re-run with --apply to record these\n";
}

exit 0;
