#!/usr/bin/perl
#-----------------------------------------------------------------------
#
# Name: expressions.pl
# Description: populate the expression fields from john's own subformat list,
#              and report entries that turn out to share an expression
# Category: cracking-rosetta curator
#
# Project: cracking-rosetta | Phase: 6 - make the semantic join key real
#
#-----------------------------------------------------------------------
# METHODOLOGY AND WHY THESE CHOICES
#
# WHAT THE FIELD IS FOR
#
# CLAUDE.md settled the expression language question by refusing to invent one:
# mdxfind ships an hx compiler and john has --format=dynamic='EXPR', so the
# repository records theirs. Both fields have been in the schema since the
# start and both have been empty, which means the semantic join key -- the
# thing that lets a validator say two tools' identifiers really do denote the
# same algorithm -- has never done any work.
#
# WHERE THE TEXT COMES FROM
#
# Not from a human reading a name. "john --list=subformats" prints, for all 474
# dynamics this build has:
#
#     Format = dynamic_1   type = dynamic_1: md5($p.$s) (joomla)
#
# That is john's own statement of what it computes, in john's own syntax, which
# is the syntax --format=dynamic='...' takes back. So john_dynamic_expr is
# transcription, not interpretation, and expression is the same string with the
# prefix dropped -- hx and john's dynamic language spell these the same way.
#
# ONLY FOR A PROVEN BLOCK, AND ONLY ON AGREEMENT
#
# An expression is a strong claim: it says what the algorithm IS, not merely
# what identifier some tool uses. So it is written only where the john block
# reached tier 'vector' -- the entry's own vector was round-tripped under that
# identifier -- and only when every dynamic the block names prints the SAME
# expression. Entries naming dynamic_6, dynamic_1007 and dynamic_2006 agree
# (all md5(md5($p).$s); the differences are length limits, not algorithm) and
# get it. An entry whose identifiers disagree is reported, because a
# disagreement means either the mapping or john's list is wrong and neither is
# for this script to decide.
#
# THE TRAILING COMMENT IS NOT PART OF THE EXPRESSION
#
# john appends a human note: "md5($p.$s) (joomla)", "sha1(sha1_raw($p)) (hash
# truncated to length 32)". Stripping "the last parenthesized group" would
# mangle an expression that legitimately ends in a paren. So the expression is
# taken as the text up to the first space at paren-depth zero, which is exactly
# where john's own note begins.
#
# COLLISIONS ARE THE POINT
#
# Once entries carry expressions, two entries with the same expression are
# either duplicates or a distinction the table has not explained. That is the
# first thing this key can be used for, so it is reported. It is not acted on:
# merging entries is curation, and dedupe.pl already holds those decisions for
# a human.
#
#-----------------------------------------------------------------------
# Generated by Claude Opus 5 on 2026-08-29

use strict;
use warnings;

use File::Basename qw(basename);
use FindBin qw($RealBin);
use Getopt::Long qw(GetOptions);
use YAML::XS ();

use lib "$RealBin/lib";
use RosettaEmit qw(emit_entry);
use RosettaTools qw(tool_path tool_env_help);

my $PROG = basename($0);
my $ROOT = "$RealBin/..";
my $TODAY = do { my @t = localtime; sprintf '%04d-%02d-%02d',
                 $t[5] + 1900, $t[4] + 1, $t[3] };

# The john build string, taken from the extracted inventory rather than probed
# again, so every tier this run writes names exactly the build data/tools was
# generated from.
sub john_version {
    my $y = eval { YAML::XS::LoadFile("$ROOT/data/tools/john.yaml") };
    my $v = $y && $y->{version};
    return (defined $v && length $v) ? "john $v" : 'john';
}

sub usage {
    print STDERR <<"END_USAGE";

Usage: $PROG [options]

   --john PATH       john binary      (default: @{[tool_env_help('john')]})
   --algorithms DIR  curated entries  (default: data/algorithms)
   --subformats PATH read the listing from this file instead of running john
   --only ID         just this entry
   --overwrite       replace an expression that is already recorded
   --apply           write the expressions into data/algorithms
   -v, --verbose     per-entry detail
   -h, --help        this help

   Without --apply nothing is written. Exit 0 success, 1 error, 2 usage.

END_USAGE
    return;
}

my ($john, $algdir, $subfile, $only, $help, $apply, $overwrite);
my $verbose  = 0;
my $had_args = scalar @ARGV;

GetOptions(
    'john=s'       => \$john,
    'algorithms=s' => \$algdir,
    'subformats=s' => \$subfile,
    'only=s'       => \$only,
    'overwrite'    => \$overwrite,
    'apply'        => \$apply,
    'v|verbose+'   => \$verbose,
    'h|help'       => \$help,
) or do { usage(); exit 2 };

if ($help)      { usage(); exit 0 }
if (!$had_args) { usage(); exit 2 }

$john = tool_path('john', $john);
$algdir //= "$ROOT/data/algorithms";

#-----------------------------------------------------------------------
# john's subformat list: label -> expression.

my $listing;
if (defined $subfile) {
    open my $fh, '<', $subfile or do {
        print STDERR "$PROG: cannot read $subfile: $!\n"; exit 1 };
    local $/;
    $listing = <$fh>;
    close $fh;
}
else {
    my $jdir = $john; $jdir =~ s{/[^/]+$}{};
    my $jbin = basename($john);
    $listing = qx{cd @{[quotemeta $jdir]} && ./@{[quotemeta $jbin]} --list=subformats 2>/dev/null};
}

# expr_of($text) - the expression, i.e. everything before john's trailing note.
# The note always starts at a space that is outside every paren, so depth is
# tracked rather than trusting the last "(...)" to be the note.
sub expr_of {
    my ($text) = @_;
    my $depth = 0;
    for my $i (0 .. length($text) - 1) {
        my $c = substr $text, $i, 1;
        if    ($c eq '(') { $depth++ }
        elsif ($c eq ')') { $depth-- }
        elsif ($c eq ' ' && $depth == 0) { return substr $text, 0, $i }
    }
    return $text;
}

my %expr;
for my $line (split /\n/, $listing // '') {
    # "Format = dynamic_1   type = dynamic_1: md5($p.$s) (joomla)"
    next unless $line =~ /^\s*(?:User)?Format\s*=\s*(\S+)\s+type\s*=\s*\S+?:\s*(.+)$/;
    my ($label, $rest) = ($1, $2);
    my $e = expr_of($rest);
    next unless length $e;
    $expr{$label} = $e;
}

unless (%expr) {
    print STDERR "$PROG: john's subformat listing yielded no expressions.\n";
    exit 1;
}
printf STDERR "- john lists %d subformat expression(s)\n", scalar keys %expr;

#-----------------------------------------------------------------------
# Entries.

opendir(my $dh, $algdir) or do { print STDERR "$PROG: cannot read $algdir: $!\n"; exit 1 };
my @files = sort grep { /\.yaml$/ } readdir $dh;
closedir $dh;

my ($written, $skipped, $already) = (0, 0, 0);
my (@disagree, %by_expr);

for my $f (@files) {
    my $p = "$algdir/$f";
    my $e = eval { YAML::XS::LoadFile($p) } or next;
    next unless $e->{id};
    next if defined $only && $e->{id} ne $only;

    my $blk = $e->{tools}{john} or next;
    next unless ($blk->{verified} // '') eq 'vector';

    my @dyn = grep { exists $expr{$_} } @{ $blk->{cpu} || [] };
    next unless @dyn;

    my %seen = map { $expr{$_} => 1 } @dyn;
    if (keys %seen > 1) {
        push @disagree, sprintf('%-34s %s', $e->{id},
            join(' | ', map { "$_=$expr{$_}" } @dyn));
        $skipped++;
        next;
    }
    my ($x) = keys %seen;
    push @{ $by_expr{$x} }, $e->{id};

    # An entry that already carries this expression AND a tier for it is
    # finished. One that carries the expression but no tier is not: it
    # predates expression_proof: and is exactly what this pass now backfills.
    my $has_expr  = defined $e->{expression} && length $e->{expression};
    my $has_proof = ref $e->{expression_proof} eq 'HASH'
                    && defined $e->{expression_proof}{verified};
    if (!$overwrite && $has_expr && $has_proof) {
        $already++;
        next;
    }

    printf "%-34s %-46s %s\n", $e->{id}, $x,
        ($has_expr && !$has_proof ? '[tier only]' : '') if $verbose || !$apply;

    next unless $apply;
    $e->{expression}        = $x;
    $e->{john_dynamic_expr} = "dynamic=$x";

    # Tier 'upstream', not 'vector'. What was round-tripped locally is the
    # IDENTIFIER -- the john block reached 'vector' before this pass would
    # touch the entry. The expression itself is john's own statement about
    # that identifier, i.e. a claim by a project that verifies by
    # recomputation, which is precisely what 'upstream' means. Only
    # derive-expressions.pl, which compiles the string and cracks with it,
    # may write 'vector' here.
    $e->{expression_proof} = {
        verified      => 'upstream',
        verified_at   => $TODAY,
        verified_with => john_version(),
        note          => 'transcribed from john --list=subformats for an '
                       . 'identifier this entry proved by round-trip',
    };
    delete $e->{denotation};   # an expression supersedes the fallback wording
    $written += emit_entry($p, $e);
}

#-----------------------------------------------------------------------
# Report.

printf STDERR "-   entries given an expression %d, already had one %d, "
            . "identifiers disagreed %d\n",
    $written, $already, $skipped;

if (@disagree) {
    print "\n# the john identifiers on these entries do not agree on one expression\n";
    print "# $_\n" for @disagree;
}

my @collide = grep { @{ $by_expr{$_} } > 1 } sort keys %by_expr;
if (@collide) {
    printf "\n# %d expression(s) are claimed by more than one entry\n", scalar @collide;
    for my $x (@collide) {
        printf "# %-34s %s\n", $x, join(' ', @{ $by_expr{$x} });
    }
}

printf STDERR "-   nothing written; re-run with --apply\n" unless $apply;

exit 0;
