#!/usr/bin/perl
#-----------------------------------------------------------------------
#
# Name: extract-mdxfind.pl
# Description: turn "mdxfind -h" plus the upstream HASH_TYPES.md into
#              data/tools/mdxfind.yaml
# Category: cracking-rosetta extractor
#
# Project: cracking-rosetta | Phase: 1 - tool inventories
#
#-----------------------------------------------------------------------
# METHODOLOGY AND WHY THESE CHOICES
#
# TWO SOURCES, AND WHICH ONE WINS
#
# The binary knows what it supports; the catalog knows what each type's test
# vector is. Neither alone is enough:
#
#   mdxfind -h    index, options, name, and mdxfind's OWN hashcat mapping.
#                 Authoritative for the type list - it is the build that will
#                 actually run. Measured 2026-08-29: 1001 types, RCS 1.540.
#   HASH_TYPES.md the same table PLUS a complete self-test vector per type.
#                 Measured: 1000 rows, 0 truncated, 31 with no vector (which
#                 upstream documents - they share a compute function with
#                 another type and have no dedicated vector).
#
# So the binary is the spine and the catalog is joined onto it by index. A
# type present in the binary but not the catalog keeps its entry and simply
# has no vector; a type in the catalog but not the binary is REPORTED, never
# silently carried, because that means the catalog is ahead of the build and
# any vector taken from it would be unverifiable here.
#
# WHY hashpipe's COPY OF THE CATALOG
#
# Both repos ship HASH_TYPES.md and they are not equally current. Measured
# 2026-08-29: mdxfind's copy is v1.76 / 988 types, hashpipe's is v1.102 / 1000
# types, and the local mdxfind binary is newer still at 1001. On the 1000
# shared indices hashpipe's copy agrees with the local binary on every name
# and every hashcat mapping, while mdxfind's copy does not (e1 alone differs:
# 0,2600,5100 against the binary's 0,2600,3500,5100). Use hashpipe's.
#
# THE VECTOR IS KEPT WHOLE
#
# Upstream writes vectors as "hash[:salt]:password". The password is the field
# after the LAST colon, but the hash itself can contain colons and there is no
# reliable way to tell a salt from part of a hash by looking. So the raw
# vector is stored verbatim and only the password is split off. Deciding how
# to feed a given type to mdxfind - embedded salt, -s saltfile, -u userfile -
# is per-type knowledge that belongs in verify-vectors.pl, not here.
#
#-----------------------------------------------------------------------
# Generated by Claude Opus 5 on 2026-08-29

use strict;
use warnings;

use File::Basename qw(basename);
use FindBin qw($RealBin);
use Getopt::Long qw(GetOptions);
use POSIX qw(strftime);

use lib "$RealBin/lib";
use RosettaEmit qw(yaml_scalar emit_header emit_records);

my $PROG = basename($0);

sub usage {
    print STDERR <<"END_USAGE";

Usage: $PROG --binary PATH [--catalog FILE]

   --binary PATH    run "PATH -h" and parse the type list
   --from FILE      parse previously captured "-h" output; "stdin" reads stdin
   --catalog FILE   HASH_TYPES.md to join example vectors from (optional)
   -o, --out FILE   write here instead of stdout
   -v, --verbose    progress and counts on stderr (repeatable)
   -h, --help       this help

   Writes data/tools/mdxfind.yaml content to stdout.

   Regenerate the committed inventory with:
     $PROG --binary /usr/local/bin/mdxfind \\
           --catalog vendor/cynosureprime/hashpipe-HASH_TYPES.md \\
           > data/tools/mdxfind.yaml

   Prefer hashpipe's copy of HASH_TYPES.md over mdxfind's; it tracks the
   binary more closely. See the methodology block in this file.

   Exit 0 success, 1 error, 2 usage.

END_USAGE
    return;
}

# Emission order: identity, then classification, then the vector.
my @ORDER = qw(index index_num name flags hashcat_modes example_vector example_pass);

my ($binary, $from, $catalog, $outfile, $help);
my $verbose = 0;

GetOptions(
    'binary=s'   => \$binary,
    'from=s'     => \$from,
    'catalog=s'  => \$catalog,
    'o|out=s'    => \$outfile,
    'v|verbose+' => \$verbose,
    'h|help'     => \$help,
) or do { usage(); exit 2 };

if ($help) { usage(); exit 0 }
if (!defined $binary && !defined $from) { usage(); exit 2 }
if (defined $binary && defined $from) {
    print STDERR "$PROG: --binary and --from are mutually exclusive.\n";
    exit 2;
}

my $started = time;

#-----------------------------------------------------------------------
# Source 1: the binary's own type list.

my @lines;

if (defined $binary) {
    -x $binary or do { print STDERR "$PROG: $binary is not executable.\n"; exit 1 };
    print STDERR "- Running $binary -h ...\n" if $verbose;
    open my $fh, '-|', "$binary -h 2>&1 </dev/null"
        or do { print STDERR "$PROG: cannot run $binary: $!\n"; exit 1 };
    @lines = <$fh>;
    close $fh;
}
else {
    my $fh;
    if ($from eq 'stdin') { $fh = \*STDIN }
    else {
        open $fh, '<', $from
            or do { print STDERR "$PROG: cannot read $from: $!\n"; exit 1 };
    }
    @lines = <$fh>;
    close $fh unless $from eq 'stdin';
}

my $version = 'unknown';
my @types;

for my $line (@lines) {
    chomp $line;

    # "e1        f        MD5                                  0,2600,3500,5100"
    # Four whitespace-separated columns; no mdxfind type name contains a space.
    next unless $line =~ /^e(\d+)\s+(\S+)\s+(\S+)\s+(\S+)\s*$/;
    my ($num, $flags, $name, $modes) = ($1, $2, $3, $4);

    my $rec = {
        index     => "e$num",
        index_num => $num + 0,
        name      => $name,
        flags     => [ split /,/, $flags ],
    };

    # "na" is mdxfind saying "hashcat has no equivalent" - absent, not "na".
    if ($modes ne 'na') {
        $rec->{hashcat_modes} = [ map { $_ + 0 } grep { /^\d+$/ } split /,/, $modes ];
    }

    push @types, $rec;
}

@types or do {
    print STDERR "$PROG: parsed no types -- is this 'mdxfind -h' output?\n";
    exit 1;
};

# The RCS header line carries the only version identity mdxfind offers.
# "$Header: /Users/dlr/src/mdfind/RCS/mdxfind.c,v 1.540 2026/08/22 ..."
for my $line (@lines) {
    if ($line =~ m{RCS/mdxfind\.c,v\s+(\S+)\s+(\S+)}) {
        $version = "RCS $1 ($2)";
        last;
    }
}
if ($version eq 'unknown' && defined $binary) {
    my $v = `$binary -V 2>&1 </dev/null`;
    $version = "RCS $1 ($2)" if $v =~ m{RCS/mdxfind\.c,v\s+(\S+)\s+(\S+)};
}

#-----------------------------------------------------------------------
# Source 2: the catalog, joined on index. Optional.

my (%vector, $catalog_version, $catalog_rows);
my @catalog_only;

if (defined $catalog) {
    open my $fh, '<', $catalog
        or do { print STDERR "$PROG: cannot read $catalog: $!\n"; exit 1 };

    while (my $line = <$fh>) {
        chomp $line;

        # "**1000 types** as of v1.102."
        # Anchored on the trailing period, not a non-greedy run: "as of v1.102."
        # against /(\S+?)\./ stops at the first dot and yields "v1".
        if (!defined $catalog_version && $line =~ /\*\*(\d+) types\*\* as of (v[\w.-]+?)\.?$/) {
            $catalog_version = $2;
            next;
        }

        # "| e1 | MD5 | 0,2600,5100 | `482c81...:password123` |"
        next unless $line =~ /^\|\s*e(\d+)\s*\|([^|]*)\|([^|]*)\|(.*)\|\s*$/;
        my ($num, $vec) = ($1, $4);
        $catalog_rows++;

        # The example is fenced in backticks; an empty cell means no vector.
        next unless $vec =~ /`([^`]+)`/;
        $vector{"e$num"} = $1;
    }
    close $fh;
}

#-----------------------------------------------------------------------
# Join.

my %have = map { $_->{index} => 1 } @types;
my $with_vector = 0;

for my $rec (@types) {
    my $vec = $vector{ $rec->{index} };
    next unless defined $vec;

    $rec->{example_vector} = $vec;

    # Password is the field after the LAST colon; see methodology.
    my $pos = rindex($vec, ':');
    $rec->{example_pass} = substr($vec, $pos + 1) if $pos >= 0;

    $with_vector++;
}

# A catalog entry with no matching type means the catalog is ahead of this
# build. Report it - a vector for a type this mdxfind cannot run is not usable
# evidence, and silently dropping it would hide a version skew worth knowing.
@catalog_only = sort grep { !$have{$_} } keys %vector;

#-----------------------------------------------------------------------
# Emit.

my $out = \*STDOUT;
if (defined $outfile) {
    open $out, '>', $outfile
        or do { print STDERR "$PROG: cannot write $outfile: $!\n"; exit 1 };
}

my $today  = strftime('%Y-%m-%d', localtime);
my $source = defined $binary ? "$binary -h" : "captured: $from";

emit_header($out, [
    "GENERATED by tools/$PROG -- do not edit by hand; regenerate.",
    "",
    "Source:     $source",
    "Tool:       mdxfind $version",
    "Catalog:    " . (defined $catalog
                        ? "$catalog (" . ($catalog_version // 'version unknown') . ")"
                        : 'none - no example vectors joined'),
    "Extracted:  $today",
    "Types:      " . scalar(@types),
    "Vectors:    $with_vector",
    "",
    "hashpipe shares this type list: verified 2026-08-29, 1000 of 1001 indices",
    "identical in name and hashcat mapping. It is not a separate inventory.",
    "",
    "This is an inventory of what mdxfind supports, not a mapping. Mappings",
    "between tools live in data/algorithms/ and are curated by hand.",
]);

printf {$out} "tool: %s\n",      yaml_scalar('mdxfind');
printf {$out} "version: %s\n",   yaml_scalar($version);
printf {$out} "extracted: %s\n", yaml_scalar($today);
printf {$out} "count: %d\n",     scalar(@types);
emit_records($out, 'types', \@types, \@ORDER);

close $out if defined $outfile;

#-----------------------------------------------------------------------
# Report.

my $elapsed = time - $started;
printf STDERR "- mdxfind %s: %d types in %ds\n", $version, scalar(@types), $elapsed;

if ($verbose) {
    my $mapped = grep { $_->{hashcat_modes} } @types;
    my %modes;
    $modes{$_}++ for map { @{ $_->{hashcat_modes} } } grep { $_->{hashcat_modes} } @types;
    printf STDERR "-   with a hashcat mapping: %d\n", $mapped;
    printf STDERR "-   distinct hashcat modes: %d\n", scalar(keys %modes);
    printf STDERR "-   with an example vector: %d\n", $with_vector;
    printf STDERR "-   catalog rows read:      %d\n", $catalog_rows // 0;
}

if (@catalog_only) {
    printf STDERR "- Note: %d catalog type(s) absent from this mdxfind build: %s\n",
        scalar(@catalog_only), join(', ', @catalog_only[0 .. ($#catalog_only > 9 ? 9 : $#catalog_only)]);
    print STDERR "-   The catalog is ahead of the binary; those vectors are not usable here.\n";
}

exit 0;
