#!/usr/bin/perl
#-----------------------------------------------------------------------
#
# Name: extract-hashcat.pl
# Description: turn "hashcat --hash-info" into data/tools/hashcat.yaml
# Category: cracking-rosetta extractor
#
# Project: cracking-rosetta | Phase: 1 - tool inventories
#
#-----------------------------------------------------------------------
# METHODOLOGY AND WHY THESE CHOICES
#
# WHY --hash-info AND NOT -hh
#
# "hashcat -hh" prints a mode table that is easy to parse and tells you almost
# nothing: number, name, category. "--hash-info" prints the same 593 modes with
# the fields that actually matter to a cross-reference -- crucially
# Example.Hash and Example.Pass, which are hashcat's own self-test vectors and
# therefore the corpus that lets a mapping be PROVEN rather than asserted.
# Verified 2026-08-29: 593 mode blocks, and every one of them carries all 20
# always-present fields.
#
# WHY --machine-readable
#
# The human-readable form ELIDES a long example hash, printing
# "48435058...00000 [Truncated, use --mach for full length]". The first run of
# this extractor recorded the elision verbatim for 181 of 593 modes, and the
# damage was invisible until something tried to USE one: hashcat refuses its
# own truncated example with "Separator unmatched", so those modes could never
# be round-tripped and their entries stayed at tier 'upstream' for a reason
# nothing in the data explained. --machine-readable emits JSON with the full
# value, so it is the source now; the text parser is kept for --from on a
# previously captured human-readable dump, and the input shape is detected
# rather than declared.
#
# The JSON says some things differently and the inventory follows it rather
# than reshaping to match the old output: salt_type is "generic" where the
# text said "Generic", and kernel_type / plaintext_encoding are real lists
# rather than a comma-joined string. Nothing reads those fields; they are
# recorded because an inventory that drops what it does not currently use is
# an inventory that has to be regenerated to answer a new question.
#
# THE FIELD MAP IS EXPLICIT, NOT DERIVED
#
# It would be shorter to mangle "Example.Hash.Format." into example_hash_format
# with a regex. It would also silently invent a key the moment hashcat adds a
# field, and "Kernel.Type(s)......" shows how badly that mangling can go. So
# the fields wanted are named below and anything else hashcat prints is
# ignored on purpose -- and counted, so that "hashcat added a field" surfaces
# as a number in the -v output instead of as silence.
#
# N/A BECOMES ABSENT
#
# hashcat writes "N/A" for a field that does not apply. Carrying that string
# into the data would make every consumer test for it. The field is dropped
# instead, so absent means absent.
#
# THE SOURCE CAN BE A FILE
#
# --from takes captured output (or "stdin"), so the weekly drift job can diff
# a new capture against the committed one without needing the binary, and so
# this is testable without a GPU host.
#
#-----------------------------------------------------------------------
# Generated by Claude Opus 5 on 2026-08-29

use strict;
use warnings;

use File::Basename qw(basename);
use FindBin qw($RealBin);
use Getopt::Long qw(GetOptions);
use POSIX qw(strftime);
use JSON::PP ();

use lib "$RealBin/lib";
use RosettaEmit qw(yaml_scalar emit_header emit_records);

my $PROG = basename($0);

sub usage {
    print STDERR <<"END_USAGE";

Usage: $PROG --binary PATH | --from FILE

   --binary PATH   run "PATH --hash-info" and parse it
   --from FILE     parse previously captured output; "stdin" reads stdin
   -o, --out FILE  write here instead of stdout
   -v, --verbose   progress and counts on stderr (repeatable)
   -h, --help      this help

   Writes data/tools/hashcat.yaml content to stdout.

   Regenerate the committed inventory with:
     $PROG --binary /usr/local/bin/hashcat > data/tools/hashcat.yaml

   Exit 0 success, 1 error, 2 usage.

END_USAGE
    return;
}

# The fields worth keeping, mapped to the key they get in the YAML. Anything
# hashcat prints that is not named here is deliberately dropped; see above.
my %FIELD = (
    'Name'                => 'name',
    'Category'            => 'category',
    'Slow.Hash'           => 'slow',
    'Deprecated'          => 'deprecated',
    'Deprecated.Notice'   => 'deprecated_notice',
    'Usage.Notice'        => 'usage_notice',
    'Password.Type'       => 'password_type',
    'Password.Len.Min'    => 'password_len_min',
    'Password.Len.Max'    => 'password_len_max',
    'Salt.Type'           => 'salt_type',
    'Salt.Len.Min'        => 'salt_len_min',
    'Salt.Len.Max'        => 'salt_len_max',
    'Kernel.Type(s)'      => 'kernel_types',
    'Example.Hash.Format' => 'example_hash_format',
    'Example.Hash'        => 'example_hash',
    'Example.Pass'        => 'example_pass',
    'Autodetect.Enabled'  => 'autodetect',
    'Self.Test.Enabled'   => 'self_test',
    'Plaintext.Encoding'  => 'plaintext_encoding',
);

# The same choice again for --machine-readable, whose key names are hashcat's
# own and differ from the text labels. Kept as a separate table rather than
# derived from %FIELD: the two are hashcat's decisions, not ours, and a rule
# that mapped one onto the other would break silently the first time they
# diverged.
my %JFIELD = (
    name                => 'name',
    category            => 'category',
    slow_hash           => 'slow',
    is_deprecated       => 'deprecated',
    deprecated_notice   => 'deprecated_notice',
    usage_notice        => 'usage_notice',
    password_type       => 'password_type',
    password_len_min    => 'password_len_min',
    password_len_max    => 'password_len_max',
    salt_type           => 'salt_type',
    salt_len_min        => 'salt_len_min',
    salt_len_max        => 'salt_len_max',
    kernel_type         => 'kernel_types',
    example_hash_format => 'example_hash_format',
    example_hash        => 'example_hash',
    example_pass        => 'example_pass',
    autodetect_enabled  => 'autodetect',
    self_test_enabled   => 'self_test',
    plaintext_encoding  => 'plaintext_encoding',
);

my %JIGNORED = map { $_ => 1 } (
    'advice_notice', 'benchmark_mask', 'benchmark_charset1',
    'custom_plugin', 'keep_guessing', 'potfile_enabled',
    'is_salted',          # implied by the presence of salt_len_min/max
);

# Fields hashcat prints that are deliberately NOT carried into the inventory.
# Named explicitly so that the "unmapped field" warning below means "hashcat
# added something new", not "here are the five you already decided to drop".
# A warning that fires every run is a warning nobody reads.
my %IGNORED = map { $_ => 1 } (
    'Advice.Notice',      # multi-line prose about optimized-kernel caveats
    'Benchmark.Mask',     # benchmarking concern, not an identity
    'Custom.Plugin',      # build detail
    'Keep.Guessing',      # runtime behaviour
    'Potfile.Enabled',    # runtime behaviour
);

# Fields whose Yes/No hashcat prints should become a real YAML boolean.
my %BOOLEAN = map { $_ => 1 } qw(slow deprecated autodetect self_test);

# Emission order. Chosen so a person reading the diff sees identity first,
# then classification, then the verification vector. See RosettaEmit.
my @ORDER = qw(
    mode name category
    slow deprecated deprecated_notice usage_notice
    password_type password_len_min password_len_max
    salt_type salt_len_min salt_len_max
    kernel_types plaintext_encoding
    example_hash_format example_hash example_pass
    autodetect self_test
);

my ($binary, $from, $outfile, $help);
my $verbose = 0;

GetOptions(
    'binary=s'  => \$binary,
    'from=s'    => \$from,
    'o|out=s'   => \$outfile,
    'v|verbose+' => \$verbose,
    'h|help'    => \$help,
) or do { usage(); exit 2 };

if ($help) { usage(); exit 0 }

# No arguments at all is a request for help, not an invitation to block on
# stdin -- see the project conventions.
if (!defined $binary && !defined $from) { usage(); exit 2 }
if (defined $binary && defined $from) {
    print STDERR "$PROG: --binary and --from are mutually exclusive.\n";
    exit 2;
}

my $started = time;

#-----------------------------------------------------------------------
# Read the source.

my @lines;

if (defined $binary) {
    -x $binary or do {
        print STDERR "$PROG: $binary is not executable.\n";
        exit 1;
    };
    print STDERR "- Running $binary --hash-info --machine-readable ...\n" if $verbose;
    # </dev/null so a readable stdin cannot leave hashcat waiting.
    open my $fh, '-|', "$binary --hash-info --machine-readable 2>&1 </dev/null"
        or do { print STDERR "$PROG: cannot run $binary: $!\n"; exit 1 };
    @lines = <$fh>;
    close $fh;
}
else {
    my $fh;
    if ($from eq 'stdin') {
        $fh = \*STDIN;
    }
    else {
        open $fh, '<', $from
            or do { print STDERR "$PROG: cannot read $from: $!\n"; exit 1 };
    }
    @lines = <$fh>;
    close $fh unless $from eq 'stdin';
}

@lines or do { print STDERR "$PROG: no input.\n"; exit 1 };

#-----------------------------------------------------------------------
# Parse. Either hashcat's JSON or its human-readable blocks -- detected from
# the input, because --from may hand us either and a wrong guess would produce
# an empty inventory rather than an error.

my $version = 'unknown';
my (@modes, $cur);
my ($unknown_fields, $skipped_lines) = (0, 0);
my %unknown_seen;

# The banner precedes the JSON, so version comes from the same scan either way.
for my $line (@lines) {
    next unless $line =~ /^hashcat \(([^)]+)\)/;
    $version = $1;
    last;
}

my $json_text = join '', grep { !/^hashcat \(/ } @lines;
if ($json_text =~ /\A\s*\{/) {
    my $doc = eval { JSON::PP->new->decode($json_text) };
    unless (ref $doc eq 'HASH') {
        print STDERR "$PROG: input looks like JSON but does not decode: $@\n";
        exit 1;
    }

    for my $mode (keys %$doc) {
        my $rec = $doc->{$mode};
        next unless ref $rec eq 'HASH';
        my $out = { mode => $mode + 0 };

        for my $jk (sort keys %$rec) {
            my $key = $JFIELD{$jk};
            if (!defined $key) {
                next if $JIGNORED{$jk};
                $unknown_fields++;
                $unknown_seen{$jk}++;
                next;
            }
            my $value = $rec->{$jk};
            next unless defined $value;

            # JSON::PP hands back its own boolean objects; the emitter wants a
            # scalar ref. Done by ref type rather than by field name so a field
            # hashcat turns from string to boolean cannot slip through as the
            # string "1".
            if (ref $value eq 'JSON::PP::Boolean') {
                $out->{$key} = $value ? \1 : \0;
                next;
            }
            if (ref $value eq 'ARRAY') {
                my @v = grep { defined && $_ ne 'N/A' && $_ ne '' } @$value;
                $out->{$key} = [@v] if @v;
                next;
            }
            # N/A means the field does not apply; absent is the honest encoding.
            next if $value eq 'N/A' || $value eq '';
            $out->{$key} = $value;
        }
        push @modes, $out;
    }
}
else {

for my $line (@lines) {
    chomp $line;

    # "hashcat (v7.1.2-549-g8a15e210b) starting in autodetect mode"
    if ($version eq 'unknown' && $line =~ /^hashcat \(([^)]+)\)/) {
        $version = $1;
        next;
    }

    if ($line =~ /^Hash mode \#(\d+)\s*$/) {
        push @modes, $cur if $cur;
        $cur = { mode => $1 + 0 };
        next;
    }

    # "  Name................: MD5"  - the dots are padding, not the name.
    if ($cur && $line =~ /^\s{2}([A-Za-z][A-Za-z.()]*?)\.*\s*:\s*(.*)$/) {
        my ($raw, $value) = ($1, $2);
        $value =~ s/\s+$//;

        my $key = $FIELD{$raw};
        if (!defined $key) {
            next if $IGNORED{$raw};
            $unknown_fields++;
            $unknown_seen{$raw}++;
            next;
        }

        # N/A means the field does not apply; absent is the honest encoding.
        next if $value eq 'N/A' || $value eq '';

        if ($BOOLEAN{$key}) {
            # Scalar ref tells the emitter this is a boolean, not a string.
            $cur->{$key} = ($value eq 'Yes') ? \1 : \0;
        }
        else {
            $cur->{$key} = $value;
        }
        next;
    }

    $skipped_lines++ if $line =~ /\S/;
}

push @modes, $cur if $cur;

}

@modes or do {
    print STDERR "$PROG: parsed no hash modes -- is this --hash-info output?\n";
    exit 1;
};

# hashcat already emits these in order, but sorting makes the output
# independent of that promise, which matters for a file compared by diff.
@modes = sort { $a->{mode} <=> $b->{mode} } @modes;

#-----------------------------------------------------------------------
# Emit.

my $out = \*STDOUT;
if (defined $outfile) {
    open $out, '>', $outfile
        or do { print STDERR "$PROG: cannot write $outfile: $!\n"; exit 1 };
}

my $today = strftime('%Y-%m-%d', localtime);
my $source = defined $binary ? "$binary --hash-info --machine-readable"
                            : "captured: $from";

emit_header($out, [
    "GENERATED by tools/$PROG -- do not edit by hand; regenerate.",
    "",
    "Source:     $source",
    "Tool:       hashcat $version",
    "Extracted:  $today",
    "Modes:      " . scalar(@modes),
    "",
    "This is an inventory of what hashcat supports, not a mapping. Mappings",
    "between tools live in data/algorithms/ and are curated by hand.",
]);

printf {$out} "tool: %s\n",       yaml_scalar('hashcat');
printf {$out} "version: %s\n",    yaml_scalar($version);
printf {$out} "extracted: %s\n",  yaml_scalar($today);
printf {$out} "count: %d\n",      scalar(@modes);
emit_records($out, 'modes', \@modes, \@ORDER);

close $out if defined $outfile;

#-----------------------------------------------------------------------
# Report.

my $elapsed = time - $started;

printf STDERR "- hashcat %s: %d modes in %ds\n", $version, scalar(@modes), $elapsed;

if ($verbose) {
    my $with_vector = grep { defined $_->{example_hash} && defined $_->{example_pass} } @modes;
    my $deprecated  = grep { ref $_->{deprecated} eq 'SCALAR' && ${$_->{deprecated}} } @modes;
    my $slow        = grep { ref $_->{slow} eq 'SCALAR' && ${$_->{slow}} } @modes;
    printf STDERR "-   with an example vector: %d\n", $with_vector;
    printf STDERR "-   deprecated:             %d\n", $deprecated;
    printf STDERR "-   slow hashes:            %d\n", $slow;
    printf STDERR "-   non-field lines seen:   %d\n", $skipped_lines;
}

# A field hashcat prints that this script does not know about is how a new
# hashcat release announces itself. Say so; do not fail on it.
if (%unknown_seen) {
    printf STDERR "- Note: %d unmapped field name(s) in --hash-info output: %s\n",
        scalar(keys %unknown_seen), join(', ', sort keys %unknown_seen);
    print STDERR "-   Add them to \%FIELD in $PROG if they belong in the inventory.\n";
}

exit 0;
