#!/usr/bin/perl
#-----------------------------------------------------------------------
#
# Name: extract-hashpipe.pl
# Description: inventory what hashpipe supports, from the binary itself
# Category: cracking-rosetta extractor
#
# Project: cracking-rosetta | Phase: 6 - drift detection
#
#-----------------------------------------------------------------------
# METHODOLOGY AND WHY THIS EXISTS
#
# WHY hashpipe IS A COLUMN NOW AND WAS NOT BEFORE
#
# It was treated as an alias of mdxfind: same catalog, and a diff on
# 2026-08-29 found zero name mismatches and zero hashcat-mode mismatches. The
# 25 names hashpipe had and mdxfind did not were understood to be transient,
# on upstream's own account, and the argument for a separate column rested on
# FINDABILITY -- can a reader arriving by a hashpipe name land somewhere --
# which was answered: all but QAS-VASAUTH could.
#
# That is not the question that broke it. Measured 2026-09-03: TEN entries in
# this corpus have an algorithm hashpipe supports under a type mdxfind has no
# equivalent of -- ORACLE11, SUNMD5, H3C, MONGODB, GOST94CRYPT,
# GOST12256CRYPT and the four DRAGONFLY variants. Each publishes "mdxfind: no"
# in dist/rosetta.csv while an installed tool supports it, and the schema had
# nowhere to say so. That is EXPRESSIVENESS, not findability, and it is a
# defect that actually happened rather than an argument. Royce decided on
# 2026-09-03 to give hashpipe its own column, noting that some hashpipe types
# may never reach mdxfind at all, which makes the divergence permanent rather
# than a backlog.
#
# WHAT THE BINARY WILL TELL US, AND WHAT IT WILL NOT
#
# hashpipe has no --hash-info and no -h listing. -T runs the self-test over
# every registered type and prints one line each:
#
#     e1    MD5                            Pass
#     e56   BMW224                         FAIL (got d0ec78...)
#     e0    none                           SKIP (no test vector)
#
# v1.190 CHANGED THIS OUTPUT, and the guard below is what caught it. The
# failures are recapped in a "Failed:" block, which used to sit after the
# summary line and now sits before it, so stopping the scan at the summary
# no longer excludes the recap and the two failing types were inventoried
# twice. v1.190 also states a skip count -- "1024 passed, 2 failed, 2
# skipped" -- for the two registered types with no built-in vector, which
# earlier builds printed as SKIP lines that this parser silently dropped.
# Measured 2026-09-04: the TYPE SET itself did not move at all, 1026 types
# with no index added, removed or renamed.
#
# so the inventory is index, name, and whether the type reproduces its OWN
# built-in vector. That last field is something neither of the other two
# inventories carries, and it is not decoration: 2 of 1026 types FAIL on this
# build (BMW224 and BMW256), on constructions this corpus holds at tier
# 'vector' for mdxfind. A type that cannot reproduce its own vector cannot be
# used to prove anything, so validate.pl and any seeding pass need to see it.
#
# Those two are a LOCAL BUILD defect and the header below says so. The first
# reading here was that they showed uninitialised state worth reporting
# upstream; Waffle's answer, relayed 2026-09-04, is that sphlib's bmw.c
# violates strict aliasing and GCC 12+ miscompiles it, which is why the
# 32-bit BMW core fails and the 64-bit one does not. Worth keeping as a
# lesson about this field: a self-test failure is evidence about the BUILD,
# and only sometimes about the tool.
#
# -G is documented as "-T, but also emit the generated example vectors" and
# emits none on this build, to stdout or through -O. So there is no
# example_vector column here, where mdxfind's inventory has one. Recorded
# rather than worked around: it is a fact about the build.
#
# Nor are hashcat modes listed. hashpipe ACCEPTS them (-m takes a bare number
# as a hashcat mode) so the mapping exists internally, but nothing prints it.
# data/algorithms is where the cross-reference lives anyway.
#
# DEPENDENCIES
#
#   perl, tools/lib/RosettaEmit.pm, tools/lib/RosettaTools.pm, a hashpipe
#   binary
#
#-----------------------------------------------------------------------
# Generated by Claude Opus 5 on 2026-09-03

use strict;
use warnings;

use File::Basename qw(basename);
use FindBin qw($RealBin);
use Getopt::Long qw(GetOptions);
use POSIX qw(strftime);
use Time::HiRes qw(time);

use lib "$RealBin/lib";
use RosettaEmit qw(yaml_scalar emit_header emit_records);
use RosettaTools qw(tool_path tool_env_help);

my $PROG = basename($0);
my $ROOT = "$RealBin/..";

my @ORDER = qw(index index_num name selftest selftest_detail);

sub usage {
    print STDERR <<"END_USAGE";
Usage: $PROG [options]

   --hashpipe PATH   hashpipe binary (default: @{[tool_env_help('hashpipe')]})
   --out PATH        where to write  (default: data/tools/hashpipe.yaml,
                     '-' for stdout)
   --timeout SECS    for the self-test run (default: 600)
   -v, --verbose     counts to stderr
   -h, --help        this help

   Runs hashpipe -T, which self-tests every registered type. Exit 0 success,
   1 error, 2 usage.
END_USAGE
    return;
}

my ($hashpipe, $outfile, $timeout, $verbose, $help);
$timeout = 600;
GetOptions(
    'hashpipe=s' => \$hashpipe,
    'out=s'      => \$outfile,
    'timeout=i'  => \$timeout,
    'verbose+'   => \$verbose,
    'help|h'     => \$help,
) or do { usage(); exit 2 };
if ($help) { usage(); exit 0 }

$hashpipe = tool_path('hashpipe', $hashpipe);
$outfile //= "$ROOT/data/tools/hashpipe.yaml";

my $started = time;

#-----------------------------------------------------------------------
# Version: the RCS header, which is the only identity hashpipe offers, and
# the same shape mdxfind's extractor records.

my $version = 'unknown';
{
    my $v = `$hashpipe -V 2>&1` // '';
    $version = "RCS $1 ($2)" if $v =~ m{RCS/hashpipe\.c,v\s+(\S+)\s+(\S+)};
}

#-----------------------------------------------------------------------
# The type list.

my $out_text = '';
{
    my $pid = open(my $fh, '-|');
    die "$PROG: fork failed: $!\n" unless defined $pid;
    if (!$pid) {
        # -T writes to stdout; stderr carries nothing on this build but is
        # merged so a future diagnostic is not lost silently.
        open STDERR, '>&', \*STDOUT;
        exec { $hashpipe } $hashpipe, '-T';
        exit 127;
    }
    eval {
        local $SIG{ALRM} = sub { kill 'KILL', $pid; die "timeout\n" };
        alarm $timeout;
        local $/;
        $out_text = <$fh> // '';
        alarm 0;
        1;
    } or do { alarm 0; print STDERR "$PROG: hashpipe -T timed out\n"; exit 1 };
    close $fh;
}

my (@types, @skipped, $passed, $failed, $summary, $in_recap);
for my $line (split /\n/, $out_text) {
    # The failures are printed TWICE: once in sequence, and again in a recap
    # block headed "Failed:". Inventorying both disagrees with hashpipe's own
    # count. Where that recap sits relative to the summary CHANGED in v1.190
    # -- it used to follow the summary, so stopping at the summary was
    # enough; it now precedes it. So the recap is skipped explicitly and the
    # scan continues, because the summary is what the guard below needs.
    $in_recap = 1 if $line =~ /^Failed:/;
    if ($line =~ /^\s*(\d+) passed, (\d+) failed(?:, (\d+) skipped)?/) {
        $summary = [ $1, $2, $3 ];      # skipped is undef before v1.190
        next;
    }
    # "e0    none                           SKIP (no test vector)"
    # A registered type with no built-in vector. v1.190 states these; before
    # it, they were silently dropped by the Pass|FAIL match below. They are
    # NOT inventoried as types -- e0 is 'none' and neither is a construction
    # anything here maps -- but the count is checked and recorded, so a
    # future type arriving with no vector cannot pass unnoticed.
    if (!$in_recap && $line =~ /^e(\d+)\s+(\S+)\s+SKIP\s*(.*)$/) {
        push @skipped, "e$1 $2";
        next;
    }
    # "e1    MD5                            Pass"
    # "e56   BMW224                         FAIL (got d0ec78...)"
    next if $in_recap;
    next unless $line =~ /^e(\d+)\s+(\S+)\s+(Pass|FAIL)\s*(.*)$/;
    my ($num, $name, $result, $detail) = ($1, $2, $3, $4);
    $detail =~ s/^\s+|\s+$//g;
    $result eq 'Pass' ? $passed++ : $failed++;
    push @types, {
        index           => "e$num",
        index_num       => $num + 0,
        name            => $name,
        selftest        => lc $result,
        # Only on a failure: the digest hashpipe computed, which is what makes
        # the failure reportable upstream rather than merely noted.
        ($result eq 'FAIL' && length $detail
            ? (selftest_detail => $detail) : ()),
    };
}

unless (@types) {
    print STDERR "$PROG: hashpipe -T produced no type lines; refusing to write "
               . "an empty inventory\n";
    exit 1;
}

# Make a near miss fatal. hashpipe states its own totals, and a parse that
# disagrees with them has misread the output -- which is exactly what reading
# past the summary did, and what caught v1.190's reordered recap.
if ($summary && ($summary->[0] != ($passed // 0) || $summary->[1] != ($failed // 0))) {
    printf STDERR "%s: parsed %d pass / %d fail, but hashpipe says %d / %d. "
                . "Refusing to write an inventory that disagrees with the binary.\n",
        $PROG, $passed // 0, $failed // 0, @$summary[0, 1];
    exit 1;
}
# The same rule for the skip count, where the binary states one.
if ($summary && defined $summary->[2] && $summary->[2] != scalar @skipped) {
    printf STDERR "%s: parsed %d skipped, but hashpipe says %d. Refusing to "
                . "write an inventory that disagrees with the binary.\n",
        $PROG, scalar @skipped, $summary->[2];
    exit 1;
}

#-----------------------------------------------------------------------
# Emit.

my $today = strftime('%Y-%m-%d', localtime);
my $out;
if (defined $outfile && $outfile ne '-') {
    open $out, '>', $outfile or die "$PROG: cannot write $outfile: $!\n";
}
else { $out = \*STDOUT }

emit_header($out, [
    'GENERATED by tools/extract-hashpipe.pl -- do not edit by hand; regenerate.',
    '',
    "Source:     $hashpipe -T",
    "Tool:       hashpipe $version",
    "Extracted:  $today",
    sprintf('Types:      %d (%d self-test pass, %d fail)',
            scalar @types, $passed // 0, $failed // 0),
    (@skipped
        ? sprintf('Skipped:    %d registered type(s) with no built-in test '
                . 'vector, not inventoried: %s', scalar @skipped,
                  join(', ', @skipped))
        : ()),
    '',
    'This is an inventory of what hashpipe supports, not a mapping. Mappings',
    'between tools live in data/algorithms/ and are curated by hand.',
    '',
    'selftest is hashpipe reproducing its OWN built-in vector for that type.',
    'A type that cannot do that cannot prove anything about an entry here, so',
    'the field is carried rather than assumed.',
    '',
    ($failed
      ? ('Some types FAIL. If BMW224 or BMW256 are among them, suspect the',
         'LIBRARY and not hashpipe: sphlib bmw.c violates strict aliasing and',
         'GCC 12+ miscompiles it at -O2 and above, so the 32-bit core',
         '(BMW224/BMW256) comes out wrong while the 64-bit core',
         '(BMW384/BMW512) is unaffected -- upstream sphlib issue 3. Rebuild',
         "libsph.a with -fno-strict-aliasing, which hashpipe's own",
         '`make deps` already passes, and re-run this extractor.')
      : ('Every type reproduces its own vector on this build. It was not',
         'always so: BMW224 and BMW256 failed here from 2026-09-03 to',
         '2026-09-04, returning a different digest on every invocation, and',
         'the cause was a libsph.a built without -fno-strict-aliasing --',
         'sphlib bmw.c violates strict aliasing and GCC 12+ miscompiles its',
         '32-bit core (upstream sphlib issue 3). Rebuilding from a fresh',
         "clone with hashpipe's own `make deps` fixed it, and this file is",
         'the measurement that says so. The lesson generalises: a self-test',
         'failure is evidence about the BUILD, and only sometimes about the',
         'tool.')),
]);

printf {$out} "tool: %s\n",      yaml_scalar('hashpipe');
printf {$out} "version: %s\n",   yaml_scalar($version);
printf {$out} "extracted: %s\n", yaml_scalar($today);
printf {$out} "count: %d\n",     scalar(@types);
emit_records($out, 'types', \@types, \@ORDER);

close $out if defined $outfile && $outfile ne '-';

printf STDERR "- hashpipe %s: %d types in %ds\n",
    $version, scalar @types, time - $started;
if ($failed) {
    printf STDERR "- %d type(s) FAIL their own self-test: %s\n", $failed,
        join(', ', map { $_->{name} } grep { $_->{selftest} eq 'fail' } @types);
    print STDERR "-   Those cannot be used as evidence. If they are BMW224 and "
               . "BMW256, this is\n-   a MISCOMPILED libsph.a, not a hashpipe "
               . "defect: sphlib's bmw.c violates\n-   strict aliasing and GCC "
               . "12+ gets it wrong at -O2. Rebuild the library\n-   with "
               . "-fno-strict-aliasing (hashpipe's own 'make deps' already "
               . "does).\n";
}
exit 0;
