#!/usr/bin/perl
#-----------------------------------------------------------------------
#
# Name: extract-john.pl
# Description: turn "john --list=format-details" into data/tools/john.yaml
# Category: cracking-rosetta extractor
#
# Project: cracking-rosetta | Phase: 1 - tool inventories
#
#-----------------------------------------------------------------------
# METHODOLOGY AND WHY THESE CHOICES
#
# WHY format-details AND NOT format-all-details
#
# Both carry the same facts. format-all-details is self-labeling and needs no
# positional assumptions, but it is 16812 lines of column-aligned prose whose
# alignment is a display choice. format-details is one tab-separated record
# per format, 552 of them, and tabs do not drift. The field ORDER was pinned
# against format-all-details on 2026-08-29 rather than assumed - see %FIELD
# below, where field 14 is recorded as min password length because bfegg
# reports 1, BitLocker and WoWSRP 8, and descrypt 0, matching all-details
# exactly. Nothing here is guessed from position alone.
#
# WHY 552 RECORDS AND NOT THE 402 THAT --list=formats PRINTS
#
# --list=formats collapses the built-in dynamic formats; format-details
# enumerates every dynamic_N separately. Those extra ~150 entries are exactly
# the ones this project needs: the source spreadsheet's John column is written
# almost entirely in dynamic_N, and hashpipe's john_map.h maps 125 of them.
# Collapsing them would throw away the join key.
#
# algorithm_name IS HOST-SPECIFIC, ON PURPOSE
#
# John reports the kernel it actually built - "DES 512/512 AVX512F" here,
# something else on a host without AVX-512. It is kept verbatim because it is
# true of this build, but it means this one field can differ between hosts
# that are otherwise identical. Anything comparing two extractions for real
# upstream drift should compare label, format_name and example_ciphertext, and
# treat an algorithm_name change on its own as a host difference, not news.
#
# DISABLED DYNAMICS ARE RECORDED, NOT DROPPED
#
# john.conf includes dynamic_disabled.conf, a STOCK upstream file that switches
# off ~521 dynamic formats it calls "academic formats, and test cases, and not
# ITW formats". Those formats exist in the build and a host that edits one line
# gets them back, so --list=format-details not showing them is a statement
# about configuration, not about capability.
#
# That distinction is not academic here. hashpipe's john_map.h - generated
# against this exact commit, 9a336d800a - maps 125 john dynamics to mdxfind
# types, and 57 of them are disabled on this host. Treating those as
# nonexistent would throw away 57 upstream-VERIFIED mappings and would make the
# committed inventory depend on one machine's john.conf, which is intolerable
# for a file the whole fleet and every contributor share.
#
# They are emitted as a separate disabled_dynamic list rather than as format
# records, because --list cannot report a format name, salt size or example
# ciphertext for a format it is not loading. A thin honest list beats 521
# records of invented metadata.
#
# device IS DERIVED, AND IT MAPS ONTO THE OLD SHEET
#
# The source spreadsheet had separate "John CPU" and "John GPU" columns. John
# encodes the same thing in the label suffix, so device is derived from it:
# -opencl and -ztex are accelerator builds of a format that also exists on
# CPU. Deriving it here means the import does not have to.
#
#-----------------------------------------------------------------------
# Generated by Claude Opus 5 on 2026-08-29

use strict;
use warnings;

use File::Basename qw(basename);
use FindBin qw($RealBin);
use Getopt::Long qw(GetOptions);
use POSIX qw(strftime);

use lib "$RealBin/lib";
use RosettaEmit qw(yaml_scalar emit_header emit_records);

my $PROG = basename($0);

sub usage {
    print STDERR <<"END_USAGE";

Usage: $PROG --binary PATH | --from FILE

   --binary PATH   run "PATH --list=format-details" and parse it
   --from FILE     parse previously captured output; "stdin" reads stdin
   --disabled FILE dynamic_disabled.conf (default: beside the binary)
   -o, --out FILE  write here instead of stdout
   -v, --verbose   progress and counts on stderr (repeatable)
   -h, --help      this help

   Writes data/tools/john.yaml content to stdout.

   john resolves john.conf relative to its working directory, so --binary
   chdirs to the binary's directory before running it -- the same reason the
   johnl wrapper exists.

   Regenerate the committed inventory with:
     $PROG --binary /usr/local/src/sec/crack/john-latest/run/john \\
           > data/tools/john.yaml

   Exit 0 success, 1 error, 2 usage.

END_USAGE
    return;
}

# Field order of --list=format-details, pinned against --list=format-all-details
# on 2026-08-29. Index is 0-based into the tab-split record.
my @FIELD = (
    [ 0,  'label'               ],
    [ 1,  'password_len_max'    ],
    [ 2,  'min_keys_per_crypt'  ],
    [ 3,  'max_keys_per_crypt'  ],
    [ 4,  'flags'               ],
    [ 5,  'test_vectors'        ],
    [ 6,  'algorithm_name'      ],
    [ 7,  'format_name'         ],
    [ 8,  'benchmark_comment'   ],
    [ 9,  'benchmark_length'    ],
    [ 10, 'binary_size'         ],
    [ 11, 'salt_size'           ],
    [ 12, 'tunable_cost'        ],
    [ 13, 'password_len_min'    ],
    [ 14, 'example_ciphertext'  ],
);

my @ORDER = qw(
    label format_name algorithm_name device dynamic
    password_len_min password_len_max
    salt_size binary_size tunable_cost
    test_vectors flags
    example_ciphertext
);

my ($binary, $from, $disabled_file, $outfile, $help);
my $verbose = 0;

GetOptions(
    'binary=s'   => \$binary,
    'from=s'     => \$from,
    'disabled=s' => \$disabled_file,
    'o|out=s'    => \$outfile,
    'v|verbose+' => \$verbose,
    'h|help'     => \$help,
) or do { usage(); exit 2 };

if ($help) { usage(); exit 0 }
if (!defined $binary && !defined $from) { usage(); exit 2 }
if (defined $binary && defined $from) {
    print STDERR "$PROG: --binary and --from are mutually exclusive.\n";
    exit 2;
}

my $started = time;

#-----------------------------------------------------------------------
# Read the source.

my (@lines, $version);

if (defined $binary) {
    -x $binary or do { print STDERR "$PROG: $binary is not executable.\n"; exit 1 };

    # john reads john.conf relative to cwd, so run it from its own directory.
    my $dir  = $binary; $dir =~ s{/[^/]+$}{};
    my $base = basename($binary);

    print STDERR "- Running $binary --list=format-details ...\n" if $verbose;
    open my $fh, '-|', "cd \Q$dir\E && ./\Q$base\E --list=format-details 2>/dev/null </dev/null"
        or do { print STDERR "$PROG: cannot run $binary: $!\n"; exit 1 };
    @lines = <$fh>;
    close $fh;

    my $bi = `cd \Q$dir\E && ./\Q$base\E --list=build-info 2>/dev/null </dev/null`;
    $version = $1 if $bi =~ /^Version:\s*(.+?)\s*$/m;
}
else {
    my $fh;
    if ($from eq 'stdin') { $fh = \*STDIN }
    else {
        open $fh, '<', $from
            or do { print STDERR "$PROG: cannot read $from: $!\n"; exit 1 };
    }
    @lines = <$fh>;
    close $fh unless $from eq 'stdin';
}

$version = 'unknown' unless defined $version && length $version;

# Disabled dynamics. Defaults to the file john itself includes, beside the
# binary. Absent is not an error: --from captures have no conf to read.
if (!defined $disabled_file && defined $binary) {
    my $dir = $binary; $dir =~ s{/[^/]+$}{};
    $disabled_file = "$dir/dynamic_disabled.conf";
}

my %disabled;
if (defined $disabled_file && -r $disabled_file) {
    open my $dfh, '<', $disabled_file
        or do { print STDERR "$PROG: cannot read $disabled_file: $!\n"; exit 1 };
    while (my $l = <$dfh>) {
        # "dynamic_81 = Y" disables; "dynamic_82 = N" explicitly does not.
        next unless $l =~ /^\s*(dynamic_\d+)\s*=\s*([YN])\s*$/i;
        $disabled{$1} = 1 if uc($2) eq 'Y';
    }
    close $dfh;
}

#-----------------------------------------------------------------------
# Parse.

my @formats;
my $malformed = 0;

for my $line (@lines) {
    chomp $line;
    next unless length $line;

    my @f = split /\t/, $line, -1;

    # Every record has exactly 15 fields. A short record means the output
    # shape changed, which is worth counting rather than silently accepting.
    if (@f != scalar @FIELD) { $malformed++; next }

    my %rec;
    for my $spec (@FIELD) {
        my ($i, $key) = @$spec;
        my $v = $f[$i];
        $v =~ s/^\s+|\s+$//g;
        $rec{$key} = length($v) ? $v : undef;
    }

    next unless defined $rec{label};

    # Derived: which device this build of the format runs on. See methodology.
    $rec{device} = $rec{label} =~ /-opencl$/ ? 'opencl'
                 : $rec{label} =~ /-ztex$/   ? 'ztex'
                 :                             'cpu';

    # Derived: is this one of the dynamic compiler formats? Scalar ref so the
    # emitter writes a real YAML boolean.
    $rec{dynamic} = ($rec{label} =~ /^dynamic[_=]/) ? \1 : \0;

    push @formats, \%rec;
}

@formats or do {
    print STDERR "$PROG: parsed no formats -- is this --list=format-details output?\n";
    exit 1;
};

# Sorted so the file is independent of john's enumeration order.
@formats = sort { $a->{label} cmp $b->{label} } @formats;

#-----------------------------------------------------------------------
# Emit.

my $out = \*STDOUT;
if (defined $outfile) {
    open $out, '>', $outfile
        or do { print STDERR "$PROG: cannot write $outfile: $!\n"; exit 1 };
}

my $today  = strftime('%Y-%m-%d', localtime);
my $source = defined $binary ? "$binary --list=format-details" : "captured: $from";

my %loaded_pre = map { $_->{label} => 1 } @formats;

my $cpu     = grep { $_->{device} eq 'cpu' }    @formats;
my $opencl  = grep { $_->{device} eq 'opencl' } @formats;
my $ztex    = grep { $_->{device} eq 'ztex' }   @formats;
my $dynamic = grep { ${ $_->{dynamic} } }       @formats;

emit_header($out, [
    "GENERATED by tools/$PROG -- do not edit by hand; regenerate.",
    "",
    "Source:     $source",
    "Tool:       john $version",
    "Extracted:  $today",
    "Formats:    " . scalar(@formats) . "  (cpu $cpu, opencl $opencl, ztex $ztex)",
    "Dynamic:    $dynamic active",
    "Disabled:   " . scalar(grep { !$loaded_pre{$_} } keys %disabled)
                   . " dynamic format(s) switched off by dynamic_disabled.conf,",
    "            listed under disabled_dynamic. They exist in this build; a",
    "            host that edits that file gets them back.",
    "",
    "algorithm_name reports the kernel THIS host built (SIMD width and all),",
    "so it can differ between hosts that are otherwise identical. Compare",
    "label, format_name and example_ciphertext when looking for real drift.",
    "",
    "This is an inventory of what john supports, not a mapping. Mappings",
    "between tools live in data/algorithms/ and are curated by hand.",
]);

printf {$out} "tool: %s\n",      yaml_scalar('john');
printf {$out} "version: %s\n",   yaml_scalar($version);
printf {$out} "extracted: %s\n", yaml_scalar($today);
printf {$out} "count: %d\n",     scalar(@formats);

# Only those john did NOT load: a dynamic listed as disabled but present in
# format-details was re-enabled locally, and the format record is the truth.
my %loaded = map { $_->{label} => 1 } @formats;
my @off = sort grep { !$loaded{$_} } keys %disabled;
if (@off) {
    printf {$out} "disabled_dynamic_count: %d\n", scalar(@off);
    print  {$out} "disabled_dynamic:\n";
    printf {$out} "  - %s\n", yaml_scalar($_) for @off;
}

emit_records($out, 'formats', \@formats, \@ORDER);

close $out if defined $outfile;

#-----------------------------------------------------------------------
# Report.

my $elapsed = time - $started;
printf STDERR "- john %s: %d formats in %ds\n", $version, scalar(@formats), $elapsed;

if ($verbose) {
    my $with_example = grep { defined $_->{example_ciphertext} } @formats;
    printf STDERR "-   cpu / opencl / ztex:    %d / %d / %d\n", $cpu, $opencl, $ztex;
    printf STDERR "-   dynamic formats:        %d\n", $dynamic;
    printf STDERR "-   with example ciphertext:%d\n", $with_example;
}

if ($malformed) {
    printf STDERR "- Note: %d line(s) did not have %d tab-separated fields and were skipped.\n",
        $malformed, scalar @FIELD;
    print STDERR "-   The --list=format-details shape may have changed; check \@FIELD in $PROG.\n";
}

exit 0;
