#!/usr/bin/perl
#-----------------------------------------------------------------------
#
# Name: extract-hashpipe.pl
# Description: inventory what hashpipe supports, from the binary itself
# Category: cracking-rosetta extractor
#
# Project: cracking-rosetta | Phase: 6 - drift detection
#
#-----------------------------------------------------------------------
# METHODOLOGY AND WHY THIS EXISTS
#
# WHY hashpipe IS A COLUMN NOW AND WAS NOT BEFORE
#
# It was treated as an alias of mdxfind: same catalog, and a diff on
# 2026-08-29 found zero name mismatches and zero hashcat-mode mismatches. The
# 25 names hashpipe had and mdxfind did not were understood to be transient,
# on upstream's own account, and the argument for a separate column rested on
# FINDABILITY -- can a reader arriving by a hashpipe name land somewhere --
# which was answered: all but QAS-VASAUTH could.
#
# That is not the question that broke it. Measured 2026-09-03: TEN entries in
# this corpus have an algorithm hashpipe supports under a type mdxfind has no
# equivalent of -- ORACLE11, SUNMD5, H3C, MONGODB, GOST94CRYPT,
# GOST12256CRYPT and the four DRAGONFLY variants. Each publishes "mdxfind: no"
# in dist/rosetta.csv while an installed tool supports it, and the schema had
# nowhere to say so. That is EXPRESSIVENESS, not findability, and it is a
# defect that actually happened rather than an argument. Royce decided on
# 2026-09-03 to give hashpipe its own column, noting that some hashpipe types
# may never reach mdxfind at all, which makes the divergence permanent rather
# than a backlog.
#
# WHAT THE BINARY WILL TELL US, AND WHAT IT WILL NOT
#
# hashpipe has no --hash-info and no -h listing. -T runs the self-test over
# every registered type and prints one line each:
#
#     e1    MD5                            Pass
#     e56   BMW224                         FAIL (got d0ec78...)
#
# so the inventory is index, name, and whether the type reproduces its OWN
# built-in vector. That last field is something neither of the other two
# inventories carries, and it is not decoration: 2 of 1026 types FAIL on this
# build (BMW224 and BMW256), on constructions this corpus holds at tier
# 'vector' for mdxfind. A type that cannot reproduce its own vector cannot be
# used to prove anything, so validate.pl and any seeding pass need to see it.
#
# -G is documented as "-T, but also emit the generated example vectors" and
# emits none on this build, to stdout or through -O. So there is no
# example_vector column here, where mdxfind's inventory has one. Recorded
# rather than worked around: it is a fact about the build.
#
# Nor are hashcat modes listed. hashpipe ACCEPTS them (-m takes a bare number
# as a hashcat mode) so the mapping exists internally, but nothing prints it.
# data/algorithms is where the cross-reference lives anyway.
#
# DEPENDENCIES
#
#   perl, tools/lib/RosettaEmit.pm, tools/lib/RosettaTools.pm, a hashpipe
#   binary
#
#-----------------------------------------------------------------------
# Generated by Claude Opus 5 on 2026-09-03

use strict;
use warnings;

use File::Basename qw(basename);
use FindBin qw($RealBin);
use Getopt::Long qw(GetOptions);
use POSIX qw(strftime);
use Time::HiRes qw(time);

use lib "$RealBin/lib";
use RosettaEmit qw(yaml_scalar emit_header emit_records);
use RosettaTools qw(tool_path tool_env_help);

my $PROG = basename($0);
my $ROOT = "$RealBin/..";

my @ORDER = qw(index index_num name selftest selftest_detail);

sub usage {
    print STDERR <<"END_USAGE";
Usage: $PROG [options]

   --hashpipe PATH   hashpipe binary (default: @{[tool_env_help('hashpipe')]})
   --out PATH        where to write  (default: data/tools/hashpipe.yaml,
                     '-' for stdout)
   --timeout SECS    for the self-test run (default: 600)
   -v, --verbose     counts to stderr
   -h, --help        this help

   Runs hashpipe -T, which self-tests every registered type. Exit 0 success,
   1 error, 2 usage.
END_USAGE
    return;
}

my ($hashpipe, $outfile, $timeout, $verbose, $help);
$timeout = 600;
GetOptions(
    'hashpipe=s' => \$hashpipe,
    'out=s'      => \$outfile,
    'timeout=i'  => \$timeout,
    'verbose+'   => \$verbose,
    'help|h'     => \$help,
) or do { usage(); exit 2 };
if ($help) { usage(); exit 0 }

$hashpipe = tool_path('hashpipe', $hashpipe);
$outfile //= "$ROOT/data/tools/hashpipe.yaml";

my $started = time;

#-----------------------------------------------------------------------
# Version: the RCS header, which is the only identity hashpipe offers, and
# the same shape mdxfind's extractor records.

my $version = 'unknown';
{
    my $v = `$hashpipe -V 2>&1` // '';
    $version = "RCS $1 ($2)" if $v =~ m{RCS/hashpipe\.c,v\s+(\S+)\s+(\S+)};
}

#-----------------------------------------------------------------------
# The type list.

my $out_text = '';
{
    my $pid = open(my $fh, '-|');
    die "$PROG: fork failed: $!\n" unless defined $pid;
    if (!$pid) {
        # -T writes to stdout; stderr carries nothing on this build but is
        # merged so a future diagnostic is not lost silently.
        open STDERR, '>&', \*STDOUT;
        exec { $hashpipe } $hashpipe, '-T';
        exit 127;
    }
    eval {
        local $SIG{ALRM} = sub { kill 'KILL', $pid; die "timeout\n" };
        alarm $timeout;
        local $/;
        $out_text = <$fh> // '';
        alarm 0;
        1;
    } or do { alarm 0; print STDERR "$PROG: hashpipe -T timed out\n"; exit 1 };
    close $fh;
}

my (@types, $passed, $failed, $summary);
for my $line (split /\n/, $out_text) {
    # The failures are printed twice: once in sequence, and again in a block
    # after the summary. Reading past the summary inventories them twice and
    # disagrees with hashpipe's own count.
    if ($line =~ /^\s*(\d+) passed, (\d+) failed/) { $summary = [$1, $2]; last }
    # "e1    MD5                            Pass"
    # "e56   BMW224                         FAIL (got d0ec78...)"
    next unless $line =~ /^e(\d+)\s+(\S+)\s+(Pass|FAIL)\s*(.*)$/;
    my ($num, $name, $result, $detail) = ($1, $2, $3, $4);
    $detail =~ s/^\s+|\s+$//g;
    $result eq 'Pass' ? $passed++ : $failed++;
    push @types, {
        index           => "e$num",
        index_num       => $num + 0,
        name            => $name,
        selftest        => lc $result,
        # Only on a failure: the digest hashpipe computed, which is what makes
        # the failure reportable upstream rather than merely noted.
        ($result eq 'FAIL' && length $detail
            ? (selftest_detail => $detail) : ()),
    };
}

unless (@types) {
    print STDERR "$PROG: hashpipe -T produced no type lines; refusing to write "
               . "an empty inventory\n";
    exit 1;
}

# Make a near miss fatal. hashpipe states its own totals, and a parse that
# disagrees with them has misread the output -- which is exactly what reading
# past the summary did.
if ($summary && ($summary->[0] != ($passed // 0) || $summary->[1] != ($failed // 0))) {
    printf STDERR "%s: parsed %d pass / %d fail, but hashpipe says %d / %d. "
                . "Refusing to write an inventory that disagrees with the binary.\n",
        $PROG, $passed // 0, $failed // 0, @$summary;
    exit 1;
}

#-----------------------------------------------------------------------
# Emit.

my $today = strftime('%Y-%m-%d', localtime);
my $out;
if (defined $outfile && $outfile ne '-') {
    open $out, '>', $outfile or die "$PROG: cannot write $outfile: $!\n";
}
else { $out = \*STDOUT }

emit_header($out, [
    'GENERATED by tools/extract-hashpipe.pl -- do not edit by hand; regenerate.',
    '',
    "Source:     $hashpipe -T",
    "Tool:       hashpipe $version",
    "Extracted:  $today",
    sprintf('Types:      %d (%d self-test pass, %d fail)',
            scalar @types, $passed // 0, $failed // 0),
    '',
    'This is an inventory of what hashpipe supports, not a mapping. Mappings',
    'between tools live in data/algorithms/ and are curated by hand.',
    '',
    'selftest is hashpipe reproducing its OWN built-in vector for that type.',
    'A type that cannot do that cannot prove anything about an entry here, so',
    'the field is carried rather than assumed.',
    '',
    'BMW224 and BMW256 fail, and selftest_detail records ONE run: measured',
    '2026-09-03, they return a DIFFERENT digest on every invocation, which is',
    'uninitialised state rather than a wrong constant. mdxfind computes both',
    'deterministically and correctly. Do not treat the recorded digest as',
    'stable.',
]);

printf {$out} "tool: %s\n",      yaml_scalar('hashpipe');
printf {$out} "version: %s\n",   yaml_scalar($version);
printf {$out} "extracted: %s\n", yaml_scalar($today);
printf {$out} "count: %d\n",     scalar(@types);
emit_records($out, 'types', \@types, \@ORDER);

close $out if defined $outfile && $outfile ne '-';

printf STDERR "- hashpipe %s: %d types in %ds\n",
    $version, scalar @types, time - $started;
if ($failed) {
    printf STDERR "- %d type(s) FAIL their own self-test: %s\n", $failed,
        join(', ', map { $_->{name} } grep { $_->{selftest} eq 'fail' } @types);
    print STDERR "-   Those cannot be used as evidence, and are worth reporting "
               . "upstream.\n";
}
exit 0;
