#!/bin/sh
# Project: cracking-rosetta | Phase: 3 - upstream seed data
# Refresh vendor/cynosureprime/ from GitHub and record the commit it came from.
#
# WHY THE SCRIPT WRITES PROVENANCE.md RATHER THAN ASKING
#
# It used to print "Update the commit and Fetched columns in PROVENANCE.md"
# and rely on the operator. It knew the SHA; handing a fact the machine had to
# a human to transcribe is the same class of defect as a drift register that
# only exists as prose. So it patches the table itself, on whole-line anchors
# that must match exactly once, and refuses rather than guessing.
#
# WHAT IT DELIBERATELY DOES NOT DO
#
# It does not touch the vendored files after fetching them. They are upstream's
# bytes and the diff is the entire drift signal; a local "fix" would make a
# re-fetch raise a false alarm when nothing changed and go silent when
# something did.
#
# POSIX sh; needs curl and python3. Run from anywhere.
# Generated by Claude Opus 5 on 2026-08-29
set -e

root=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
dest="$root/vendor/cynosureprime"
today=$(date -u +%Y-%m-%d)

mkdir -p "$dest"

# repo:remote-path:local-name -- two upstreams, because the specification is
# its own repository. hx.8 is Appendix A, the statement of what each mdxfind
# type computes; tools/extract-hx.pl renders it into data/hx-appendix-a.txt.
set -- \
    "Cynosureprime/hashpipe:HASH_TYPES.md:hashpipe-HASH_TYPES.md" \
    "Cynosureprime/hashpipe:john_map.h:john_map.h" \
    "Cynosureprime/hx:hx.8:hx.8"

for spec in "$@"; do
    repo=${spec%%:*}; rest=${spec#*:}
    remote=${rest%%:*}; local_name=${rest##*:}
    printf -- '- fetching %s from %s\n' "$remote" "$repo" >&2
    curl -fsS -m 60 -o "$dest/$local_name" \
        "https://raw.githubusercontent.com/$repo/HEAD/$remote"
done

# One HEAD per repo, so each vendored file records the commit of the
# repository it actually came from rather than of whichever was asked last.
head_of() {
    curl -fsS -m 30 "https://api.github.com/repos/$1/commits?per_page=1" \
      | python3 -c 'import json,sys
c = json.load(sys.stdin)[0]
print(c["sha"], c["commit"]["committer"]["date"][:10])'
}

hp_meta=$(head_of Cynosureprime/hashpipe)
hx_meta=$(head_of Cynosureprime/hx)

sha=${hp_meta%% *};    cdate=${hp_meta##* }
hx_sha=${hx_meta%% *}; hx_cdate=${hx_meta##* }

printf -- '- Cynosureprime/hashpipe is now at %s (%s)\n' "$sha" "$cdate" >&2
printf -- '- Cynosureprime/hx is now at %s (%s)\n' "$hx_sha" "$hx_cdate" >&2

# Patch the Commit and Fetched columns. Whole-line anchors, exactly-once or
# fail: a patch that silently changes nothing is indistinguishable from one
# that worked, which is the whole failure mode. Bytes in, bytes out -- the
# table sits in a file that is pure ASCII today but nothing here should be
# what changes that.
PROV="$dest/PROVENANCE.md" SHA="$sha" CDATE="$cdate" TODAY="$today" \
HX_SHA="$hx_sha" HX_CDATE="$hx_cdate" python3 <<'PYPATCH'
import os, re, sys, tempfile

prov  = os.environ["PROV"]
sha   = os.environ["SHA"]
cdate = os.environ["CDATE"]
today = os.environ["TODAY"]

with open(prov, "rb") as fh:
    text = fh.read()

hx_sha   = os.environ["HX_SHA"]
hx_cdate = os.environ["HX_CDATE"]

# Each file is stamped with ITS OWN repository's HEAD.
for name, s, d in ((b"hashpipe-HASH_TYPES.md", sha, cdate),
                   (b"john_map.h",             sha, cdate),
                   (b"hx.8",                   hx_sha, hx_cdate)):
    # The whole row, start of line through end of line, so the newline sits
    # inside both the old and the new block and cancels out.
    pat = re.compile(rb"^\| `" + re.escape(name) + rb"` \|([^|]*)\|[^|]*\|[^|]*\|[ \t]*$",
                     re.M)
    found = pat.findall(text)
    if len(found) != 1:
        sys.exit("fetch-upstream: %s matched %d row(s) in %s, refusing to patch"
                 % (name.decode(), len(found), prov))
    row = b"| `%s` |%s| `%s` (%s) | %s |" % (
        name, found[0], s.encode(), d.encode(), today.encode())
    text = pat.sub(lambda _m: row, text, count=1)

# Write complete, then rename, preserving the mode. Never truncate the target
# before the new content is on disk.
mode = os.stat(prov).st_mode
fd, tmp = tempfile.mkstemp(dir=os.path.dirname(prov), prefix=".prov.")
try:
    with os.fdopen(fd, "wb") as fh:
        fh.write(text)
    os.chmod(tmp, mode & 0o7777)
    os.replace(tmp, prov)
except BaseException:
    os.unlink(tmp)
    raise
print("- PROVENANCE.md now records %s, fetched %s" % (sha[:8], today))
PYPATCH

printf -- '- next: tools/extract-hx.pl, the other extractors and\n' >&2
printf -- '-       tools/seed-upstream.pl, then\n' >&2
printf -- '-       %s/tools/check-upstream.pl --check -v\n' "$root" >&2
printf -- '-       which is what tells you whether a recorded disagreement with\n' >&2
printf -- '-       upstream moved, or was fixed and can be deleted.\n' >&2
