#!/usr/bin/perl
#-----------------------------------------------------------------------
#
# Name: fmt.pl
# Description: put a curated entry into the repository's canonical YAML form,
#              and refuse to do it silently if anything would be lost
# Category: cracking-rosetta contributor tool
#
# Project: cracking-rosetta | Phase: 6 - contribution ergonomics
#
#-----------------------------------------------------------------------
# METHODOLOGY AND WHY THESE CHOICES
#
# THE PROBLEM A CONTRIBUTOR ACTUALLY HITS
#
# Every generated and curated file here is written by RosettaEmit: explicit
# key order, every string double-quoted, lists inline. A human editing
# data/algorithms/foo.yaml by hand will not reproduce that byte for byte, and
# nothing tells them. Their PR looks fine, gets merged, and then the next tool
# that touches the entry -- relate.pl, verify-vectors.pl, anything -- rewrites
# the whole file. The reviewer of THAT change sees a one-line edit buried in a
# forty-line reformat, which is exactly the reviewability the two-layer split
# was designed to protect.
#
# So: run this before opening a PR and the diff stays the size of the change.
#
# THE TRAP IT IS REALLY THERE FOR
#
# RosettaEmit's key order is an ALLOWLIST. A key it does not know is not an
# error -- it is simply not emitted. A contributor who writes "verifed:" for
# "verified:", or "passs:" inside a vector, loses that line the first time a
# tool rewrites the file, with no message at any point. validate.pl catches
# some of these by name, but only the ones somebody remembered to enumerate;
# vector keys, for instance, are not checked anywhere.
#
# This tool catches all of them structurally instead. It loads the file,
# renders it, re-loads the rendering, and compares the two data structures
# path by path. Anything present before and absent after is data the
# repository would have thrown away, and that is a hard error rather than a
# reformat. The check costs one extra parse and needs no list of known keys,
# so it cannot fall behind the schema.
#
# --check IS THE PR-TIME MODE
#
# It writes nothing and exits 1 if any file is not already canonical, which is
# what CI and a pre-commit hook want. Without it the files are rewritten in
# place. Neither mode ever changes MEANING: if the round-trip is not faithful
# the file is reported and left exactly as it was.
#
# WHY NOT JUST HAVE validate.pl DO IT
#
# Because validate.pl is the gate and must stay read-only -- it runs on
# pull_request in CI, where a formatter that writes would either fail on a
# read-only checkout or silently commit for the contributor. Different jobs,
# different tools.
#
# DEPENDENCIES
#
#   perl, YAML::XS, tools/lib/RosettaEmit.pm
#
#-----------------------------------------------------------------------
# Generated by Claude Opus 5 on 2026-08-30

use strict;
use warnings;

use File::Basename qw(basename);
use FindBin qw($RealBin);
use Getopt::Long qw(GetOptions);
use YAML::XS ();

use lib "$RealBin/lib";
use RosettaEmit qw(entry_text);

my $PROG = basename($0);
my $ROOT = "$RealBin/..";

sub usage {
    print STDERR <<"END_USAGE";

Usage: $PROG [options] [FILE...]

   --all             every entry in data/algorithms, not just the named files
   --algorithms DIR  where the entries live (default: data/algorithms)
   --check           report what is not canonical; write nothing, exit 1
   -q, --quiet       only report problems
   -v, --verbose     name every file examined
   -h, --help        this help

   With no FILE and no --all, prints this. Exit 0 clean, 1 something to fix
   (or, with --check, something not yet formatted), 2 usage.

   Rewrites an entry into the repository's canonical YAML form so that your
   diff stays the size of your change. It refuses, loudly, if rendering the
   file would lose anything you wrote -- a misspelled key is dropped in
   silence otherwise.

END_USAGE
    return;
}

my ($algdir, $check, $all, $help, $quiet);
my $verbose  = 0;
my $had_args = scalar @ARGV;

GetOptions(
    'algorithms=s' => \$algdir,
    'check'        => \$check,
    'all'          => \$all,
    'q|quiet'      => \$quiet,
    'v|verbose+'   => \$verbose,
    'h|help'       => \$help,
) or do { usage(); exit 2 };

if ($help)      { usage(); exit 0 }
if (!$had_args) { usage(); exit 2 }

$algdir //= "$ROOT/data/algorithms";

my @files = @ARGV;
if ($all) {
    opendir(my $dh, $algdir)
        or do { print STDERR "$PROG: cannot read $algdir: $!\n"; exit 2 };
    push @files, map { "$algdir/$_" } sort grep { /\.yaml$/ } readdir $dh;
    closedir $dh;
}
unless (@files) { usage(); exit 2 }

#-----------------------------------------------------------------------
# Structural comparison.
#
# Deliberately compares the LOADED structures rather than the text: quoting,
# key order and list style are exactly what this tool is allowed to change,
# and only the data underneath must survive untouched.

# paths($data) - every leaf of a structure as "a.b.0.c" => scalar.
sub paths {
    my ($d, $prefix, $out) = @_;
    $out    //= {};
    $prefix //= '';
    if (ref $d eq 'HASH') {
        paths($d->{$_}, ($prefix eq '' ? $_ : "$prefix.$_"), $out) for keys %$d;
    }
    elsif (ref $d eq 'ARRAY') {
        paths($d->[$_], "$prefix.$_", $out) for 0 .. $#$d;
    }
    else {
        # YAML::XS has no boolean type: 'true' arrives as 1 and 'false' as the
        # empty string. Both survive a round trip as themselves, so a plain
        # stringify is a fair comparison.
        $out->{$prefix} = defined $d ? "$d" : "\0undef";
    }
    return $out;
}

my ($changed, $problems, $seen) = (0, 0, 0);

for my $path (@files) {
    unless (-r $path) {
        printf STDERR "%s: cannot read %s\n", $PROG, $path;
        $problems++;
        next;
    }
    $seen++;

    my $before = eval { YAML::XS::LoadFile($path) };
    if ($@ || !defined $before) {
        my $why = $@ || 'empty file';
        $why =~ s/\s+/ /g;
        printf "%-46s DOES NOT PARSE: %s\n", basename($path), substr($why, 0, 140);
        $problems++;
        next;
    }
    if (ref $before ne 'HASH') {
        printf "%-46s top level is not a mapping\n", basename($path);
        $problems++;
        next;
    }

    my $text  = entry_text($before);
    my $after = eval { YAML::XS::Load($text) };
    if ($@ || ref $after ne 'HASH') {
        printf "%-46s renders to something that will not parse back\n",
            basename($path);
        $problems++;
        next;
    }

    # The check this tool exists for: did rendering drop anything?
    my $p_before = paths($before);
    my $p_after  = paths($after);
    my @lost    = grep { !exists $p_after->{$_} }  sort keys %$p_before;
    my @altered = grep {  exists $p_after->{$_}
                       && $p_after->{$_} ne $p_before->{$_} } sort keys %$p_before;

    if (@lost || @altered) {
        printf "%s\n", basename($path);
        printf "    WOULD LOSE     %s\n", $_ for @lost;
        printf "    WOULD CHANGE   %s: %s -> %s\n",
            $_, $p_before->{$_}, $p_after->{$_} for @altered;
        print  "    Not rewritten. A key the emitter does not know is dropped "
             . "in silence,\n    so this is an error rather than a reformat: "
             . "check the spelling against\n    schema/algorithm.schema.json.\n";
        $problems++;
        next;
    }

    open my $fh, '<', $path or do {
        printf STDERR "%s: cannot read %s: %s\n", $PROG, $path, $!;
        $problems++;
        next;
    };
    my $old = do { local $/; <$fh> };
    close $fh;

    if (defined $old && $old eq $text) {
        printf "%-46s ok\n", basename($path) if $verbose;
        next;
    }

    $changed++;
    if ($check) {
        printf "%-46s not canonical\n", basename($path) unless $quiet;
        next;
    }
    open my $out, '>', $path or do {
        printf STDERR "%s: cannot write %s: %s\n", $PROG, $path, $!;
        $problems++;
        next;
    };
    print {$out} $text;
    close $out;
    printf "%-46s reformatted\n", basename($path) unless $quiet;
}

unless ($quiet) {
    printf STDERR "- %d file(s) examined, %d %s, %d problem(s)\n",
        $seen, $changed, ($check ? 'not canonical' : 'rewritten'), $problems;
}

exit(($problems || ($check && $changed)) ? 1 : 0);
