#!/usr/bin/env python3
"""One-shot migration of the Google Sheet "Rosetta" tab into data/algorithms/.

Project: cracking-rosetta | Phase: 2 - migrate the curated rows

METHODOLOGY AND WHY THESE CHOICES

EVERY IMPORTED IDENTIFIER IS CHECKED BEFORE IT IS WRITTEN.
The sheet is three years stale and was never machine-checked, so a cell saying
"2811" or "dynamic_12" or "MD5-MD5SALTMD5PASS" is a claim, not a fact. Each is
resolved against the generated inventories first. What resolves is written;
what does not is dropped from the entry AND recorded in the report, never
silently discarded and never written out to fail validation later.

NOTHING IMPORTED IS TIER 'vector'.
The sheet is human assertion with no reproduction on record, so every mapping
lands at tier 'asserted' regardless of how confident the cell looked. Promotion
is verify-vectors.pl's job and requires an actual round-trip. Importing at a
higher tier would launder unverified data into the one field the whole design
asks people to trust.

NAME DRIFT IS NORMALIZED, SPELLING IS NOT INVENTED.
The sheet writes HAV128_4 where mdxfind writes HAV128-4. Matching strips every
non-alphanumeric and uppercases; what gets WRITTEN is the inventory's exact
spelling, so the repo speaks the tool's language rather than the sheet's.

ROWS WITH NO ALGORITHM NAME ARE STILL DATA.
200 rows carry a mdxfind type and an example hash but an empty name cell -
they are continuation rows, not blanks. They get an entry named after whatever
identifier they do carry rather than being dropped.

THE ID IS HUMAN-FIRST.
Slug priority is the algorithm name, then the mdxfind type, then the hashcat
mode, because ids are permanent and public and should read as the algorithm,
not as one tool's internal label. Collisions take a numeric suffix in a
deterministic order; the sheet has real duplicates (md5(md5($plain).$salt)
appears three times) which are distinct variants, not repeats.

Dependencies: python3-openpyxl, python3-yaml (both Debian-packaged).
Generated by Claude Opus 5 on 2026-08-29
"""

import argparse
import re
import sys
from pathlib import Path
from typing import Any

import openpyxl
import yaml

TIER = "asserted"  # see methodology: nothing from the sheet is proven

# Sheet columns, by position in the header row.
COL = {
    "algorithm": 0, "hashkiller": 1, "hashcat": 2, "hashcat_legacy": 3,
    "mdxfind": 4, "mdxfind_extra": 5, "john_cpu": 6, "john_gpu": 7,
    "hashes_org": 8, "hashes_org_comment": 9, "class": 10,
    "example": 11, "notes": 12,
}

# Cell text meaning "this tool cannot do it" rather than naming an identifier.
NEGATIVE = re.compile(r"^\s*(not\s+supported|unsupported|no|none|n/?a)\??\s*$", re.I)

# mdxfind values in the sheet that are not types at all; see the survey.
JUNK_MDXFIND = {"NOTSUPPORTED", "MD5AUTOMATICPARTIALMATCH", "MD5UCWITHI2MD5UCX2", "WLR1"}


def norm(s: str) -> str:
    """Collapse a name to its comparable core: HAV128_4 and HAV128-4 both -> HAV1284."""
    return re.sub(r"[^A-Z0-9]", "", s.upper())


def slugify(s: str) -> str:
    """Turn an algorithm name into a permanent, readable id."""
    s = s.lower().replace("$", "")
    s = re.sub(r"[^a-z0-9]+", "-", s)
    return s.strip("-")


def cell(row: list, key: str) -> str:
    """Read one cell as trimmed text, undoing xlsx's float coercion of integers."""
    i = COL[key]
    if i >= len(row) or row[i] is None:
        return ""
    v = row[i]
    if isinstance(v, float) and v.is_integer():
        return str(int(v))
    return str(v).strip()


class Emitter:
    """Minimal YAML writer matching tools/lib/RosettaEmit.pm's conventions.

    Hand-rolled rather than yaml.dump for the same reason the Perl side is:
    deterministic key order and unconditional quoting. These files are the PR
    surface, so they must read the same as the generated ones.
    """

    @staticmethod
    def scalar(v: Any) -> str:
        if v is None:
            return "null"
        if isinstance(v, bool):
            return "true" if v else "false"
        if isinstance(v, int):
            return str(v)
        if isinstance(v, list):
            return "[" + ", ".join(Emitter.scalar(x) for x in v) + "]"
        s = str(v).replace("\\", "\\\\").replace('"', '\\"')
        return f'"{s}"'

    @staticmethod
    def dump(d: dict, indent: int = 0) -> str:
        out = []
        pad = " " * indent
        for k, v in d.items():
            if v is None or v == [] or v == {}:
                continue
            if isinstance(v, dict):
                out.append(f"{pad}{k}:")
                out.append(Emitter.dump(v, indent + 2))
            elif isinstance(v, list) and v and isinstance(v[0], dict):
                out.append(f"{pad}{k}:")
                for item in v:
                    # Render the item at indent 0 so its own nesting stays
                    # relative, then shift every line. Rendering it at the
                    # final indent and shifting again double-indents the
                    # continuation lines and produces YAML that will not load.
                    lines = Emitter.dump(item, 0).split("\n")
                    out.append(f"{pad}  - {lines[0]}")
                    out.extend(f"{pad}    {ln}" for ln in lines[1:] if ln.strip())
            else:
                out.append(f"{pad}{k}: {Emitter.scalar(v)}")
        return "\n".join(out)


def load_inventories(tooldir: Path) -> dict:
    """Build the lookup tables every imported identifier is checked against."""
    inv = {}
    for name, listkey, idkey in (
        ("hashcat", "modes", "mode"),
        ("john", "formats", "label"),
        ("mdxfind", "types", "name"),
    ):
        path = tooldir / f"{name}.yaml"
        if not path.is_file():
            sys.exit(f"error: {path} not found -- run the extractors first (exit 2)")
        doc = yaml.safe_load(path.read_text())
        inv[name] = {"doc": doc, "records": {r[idkey]: r for r in doc[listkey]}}
        # Normalized index, so sheet spelling drift still resolves.
        inv[name]["byNorm"] = {norm(str(k)): k for k in inv[name]["records"]}
        # Case-folded index. John is genuinely inconsistent with itself -
        # "Raw-MD5" on CPU but "raw-MD5-opencl" on GPU - and john's own
        # --format= matching is case-insensitive, so ours has to be too.
        inv[name]["byLower"] = {str(k).lower(): k for k in inv[name]["records"]}
    return inv


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--xlsx", required=True, help="exported workbook")
    ap.add_argument("--sheet", default="Rosetta", help="tab to import (default: Rosetta)")
    ap.add_argument("--tools", default="data/tools", help="generated inventories")
    ap.add_argument("--out", default="data/algorithms", help="where entries are written")
    ap.add_argument("--report", default="tmp/import-report.txt", help="what was dropped, and why")
    ap.add_argument("-n", "--dry-run", action="store_true", help="write nothing; report only")
    ap.add_argument("-v", "--verbose", action="count", default=0)
    args = ap.parse_args()

    inv = load_inventories(Path(args.tools))
    outdir = Path(args.out)

    wb = openpyxl.load_workbook(args.xlsx, data_only=True)
    if args.sheet not in wb.sheetnames:
        sys.exit(f"error: no tab named {args.sheet!r} (have: {', '.join(wb.sheetnames)})")
    rows = list(wb[args.sheet].iter_rows(values_only=True))[1:]

    dropped: list[str] = []
    entries: list[dict] = []
    stats = {"rows": 0, "blank": 0, "named": 0, "unnamed": 0, "junk": 0}

    for n, raw in enumerate(rows, start=2):
        row = list(raw)
        if not any(str(c).strip() for c in row if c is not None):
            stats["blank"] += 1
            continue
        stats["rows"] += 1

        name = cell(row, "algorithm")
        tools: dict[str, dict] = {}

        # --- hashcat: keep the modes that exist in this hashcat -------
        modes, hc_txt = [], cell(row, "hashcat")
        if hc_txt and not NEGATIVE.match(hc_txt):
            for tok in re.split(r"[^0-9]+", hc_txt):
                if tok and int(tok) in inv["hashcat"]["records"]:
                    modes.append(int(tok))
                elif tok:
                    dropped.append(f"row {n}: hashcat mode {tok} not in inventory ({name or '-'})")
        if modes:
            tools["hashcat"] = {"modes": sorted(set(modes)), "verified": TIER}
        elif hc_txt and NEGATIVE.match(hc_txt):
            tools["hashcat"] = {"verified": "absent"}

        # --- mdxfind: normalize, then write the tool's own spelling ---
        mx_txt = cell(row, "mdxfind")
        if mx_txt and not NEGATIVE.match(mx_txt):
            key = norm(mx_txt)
            if key in JUNK_MDXFIND:
                stats["junk"] += 1
                dropped.append(f"row {n}: mdxfind {mx_txt!r} is not a type ({name or '-'})")
            elif key in inv["mdxfind"]["byNorm"]:
                tools["mdxfind"] = {
                    "types": [inv["mdxfind"]["byNorm"][key]],
                    "verified": TIER,
                }
            else:
                dropped.append(f"row {n}: mdxfind type {mx_txt!r} not in inventory ({name or '-'})")

        # --- john: pull candidate labels out of free text -------------
        jn: dict[str, Any] = {}
        for sheet_key, out_key in (("john_cpu", "cpu"), ("john_gpu", "gpu")):
            txt = cell(row, sheet_key)
            if not txt or NEGATIVE.match(txt):
                continue
            found = []
            # Cells read like "dynamic_1 (len 1-23); dynamic_2001 (len >23)".
            misplaced = []
            for tok in re.findall(r"[A-Za-z0-9_.\-]+", txt):
                label = inv["john"]["byLower"].get(tok.lower())
                if label is None:
                    continue
                dev = inv["john"]["records"][label].get("device", "cpu")
                want_cpu = out_key == "cpu"
                if want_cpu != (dev == "cpu"):
                    # Real format, wrong column. Worth naming precisely: the
                    # sheet routinely put "bcrypt" under GPU when it meant
                    # bcrypt-opencl, and that is a human call, not a rename.
                    misplaced.append(f"{label} is a {dev} format")
                    continue
                found.append(label)
            if found:
                jn[out_key] = sorted(set(found))
            elif misplaced:
                dropped.append(f"row {n}: {sheet_key} {txt!r}: "
                               + ", ".join(misplaced) + f" ({name or '-'})")
            else:
                dropped.append(f"row {n}: no known john format in {sheet_key} {txt!r} ({name or '-'})")
        if jn:
            jn["verified"] = TIER
            tools["john"] = jn

        # --- the entry ------------------------------------------------
        if not name:
            # Continuation row: name it after whatever identifier it carries.
            if "mdxfind" in tools:
                name = tools["mdxfind"]["types"][0]
            elif cell(row, "hashes_org"):
                name = cell(row, "hashes_org")
            elif modes:
                name = f"hashcat mode {modes[0]}"
            else:
                dropped.append(f"row {n}: no name and no resolvable identifier; skipped")
                continue
            stats["unnamed"] += 1
        else:
            stats["named"] += 1

        entry: dict[str, Any] = {"id": None, "name": name}
        if tools:
            entry["tools"] = tools

        example = cell(row, "example")
        if example:
            # The column header states the plaintext is "rosetta" unless said
            # otherwise; we cannot know the exceptions, so record the stated
            # default and let verify-vectors.pl demote what fails.
            entry["vectors"] = [{"hash": example, "pass": "rosetta", "source": "sheet"}]

        legacy = {}
        if cell(row, "hashes_org"):
            legacy["hashes_org"] = cell(row, "hashes_org")
        if cell(row, "hashkiller"):
            legacy["hashkiller"] = cell(row, "hashkiller")
        if legacy:
            entry["legacy"] = legacy

        notes = "; ".join(t for t in (cell(row, "notes"), cell(row, "hashes_org_comment"),
                                      cell(row, "mdxfind_extra")) if t)
        if notes:
            entry["notes"] = notes

        entry["status"] = "needs-review"
        entries.append(entry)

    # --- ids: human-first, deterministic on collision -----------------
    used: dict[str, int] = {}
    for e in entries:
        base = slugify(e["name"])
        if not base:
            tools_blk = e.get("tools", {})
            base = (slugify(tools_blk.get("mdxfind", {}).get("types", [""])[0])
                    or f"hashcat-{tools_blk.get('hashcat', {}).get('modes', ['x'])[0]}")
        used[base] = used.get(base, 0) + 1
        e["id"] = base if used[base] == 1 else f"{base}-{used[base]}"

    # --- emit ---------------------------------------------------------
    order = ["id", "name", "aliases", "expression", "john_dynamic_expr",
             "category", "status", "tools", "vectors", "legacy", "notes"]

    if not args.dry_run:
        outdir.mkdir(parents=True, exist_ok=True)
        for e in entries:
            ordered = {k: e[k] for k in order if k in e}
            (outdir / f"{e['id']}.yaml").write_text(Emitter.dump(ordered) + "\n")

        rp = Path(args.report)
        rp.parent.mkdir(parents=True, exist_ok=True)
        rp.write_text(
            f"cracking-rosetta sheet import report\n"
            f"source: {args.xlsx} [{args.sheet}]\n"
            f"entries written: {len(entries)}\n"
            f"dropped identifiers: {len(dropped)}\n\n" + "\n".join(dropped) + "\n"
        )

    print(f"- rows read: {stats['rows']} ({stats['blank']} blank skipped)", file=sys.stderr)
    print(f"- entries:   {len(entries)}  (named {stats['named']}, unnamed {stats['unnamed']})",
          file=sys.stderr)
    print(f"- dropped:   {len(dropped)} identifier(s); {stats['junk']} known-junk mdxfind value(s)",
          file=sys.stderr)
    if not args.dry_run:
        print(f"- report:    {args.report}", file=sys.stderr)
    if args.verbose:
        for d in dropped[:20]:
            print(f"-   {d}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
