#!/usr/bin/perl
#-----------------------------------------------------------------------
#
# Name: merge.pl
# Project: cracking-rosetta
# Phase: curation -- resolving the `duplicate` queue from tools/curate.pl
# Task: merge two entries that name one computation, leaving the loser as a
#       tombstone rather than deleting it.
#
#-----------------------------------------------------------------------
# METHODOLOGY AND WHY THESE CHOICES
#
# WHY THIS EXISTS WHEN tools/dedupe.pl ALREADY MERGES
#
# dedupe.pl predates the 2026-08-30 tombstone decision: it merges and DELETES.
# An id in this repository is a filename stem, a URL fragment in
# docs/index.html and the key in dist/rosetta.csv, and README promises it never
# goes away. Deleting one breaks every consumer that stored it. So a merge here
# empties the loser of every claim and leaves behind a redirect --
# `status: merged`, `merged_into:`, and a mirrored `duplicate-of` edge -- which
# is the shape validate.pl and render.pl already understand.
#
# dedupe.pl also chooses the survivor itself, from mdxfind identity. Which id
# survives is curation: it is the name a reader is most likely to arrive by,
# and no rule in the data decides it. So the survivor is an argument here.
#
# WHY A TIER IS NEVER RAISED BY A MERGE
#
# A tool block carries ONE tier for the whole block, so unioning the loser's
# identifiers into the winner's block silently extends the winner's tier over
# identifiers that were never proven at that strength. Where the loser's tier
# is weaker than the winner's, that is a false claim -- exactly the thing the
# prime directive forbids -- so this script REFUSES the merge and says so,
# rather than resolving it in whichever direction is convenient. Equal tiers
# union freely; a stronger loser tier is absorbed at the winner's weaker tier,
# which loses information but cannot assert anything untrue.
#
# WHY THE WINNER'S BLOCK NOTE IS APPENDED TO
#
# Those notes say how the identifiers in the block were established ("mode
# discovered by round-trip search, not by name"). After a union that sentence
# no longer covers everything in the list, so the merge records which
# identifiers arrived from where. Without it the provenance of half the list is
# lost in the git history of a different file.
#
# WHAT IS DELIBERATELY NOT DONE
#
# Nothing is invented. The loser's expression, category, aliases, legacy names
# and vectors move only into fields the winner does not already fill; where
# both fill a field with different content the script reports and refuses. It
# does not touch `status:`, because "needs-review" is a statement about the
# entry that merging does not answer.
#
# DEPENDENCIES
#
#   YAML::XS       (reading; the repo's emitter is used for writing, because
#                   YAML::XS chooses its own key order -- see RosettaEmit)
#   tools/lib/RosettaEmit.pm
#
# Run tools/validate.pl afterwards: it owns the tombstone rules and this
# script deliberately does not re-implement them.
#
#-----------------------------------------------------------------------
# Generated by Claude Opus 5 on 2026-09-01

use strict;
use warnings;

use FindBin ();
use lib "$FindBin::Bin/lib";

use Getopt::Long qw(GetOptions);
use File::Basename qw(basename);
use YAML::XS ();
use RosettaEmit qw(entry_text);

my $ALGDIR  = "$FindBin::Bin/../data/algorithms";
my $TODAY   = do { my @t = localtime; sprintf('%04d-%02d-%02d', $t[5]+1900, $t[4]+1, $t[3]) };

my (@pairs, $from, $note, $apply, $verbose, $help);
GetOptions(
    'merge=s'      => \@pairs,
    'from=s'       => \$from,
    'note=s'       => \$note,
    'algorithms=s' => \$ALGDIR,
    'apply'        => \$apply,
    'v|verbose+'   => \$verbose,
    'h|help'       => \$help,
) or usage(2);

usage(0) if $help;
usage(2) unless @pairs || $from;

sub usage {
    my ($code) = @_;
    my $fh = $code ? *STDERR : *STDOUT;
    print {$fh} <<'USAGE';

Usage: merge.pl --merge LOSER:WINNER [--merge ...] [options]
       merge.pl --from FILE [options]

   --merge L:W       merge entry L into entry W. L becomes a tombstone
                     redirecting to W; every claim L carried moves to W.
                     Repeatable.
   --from FILE       batch: one merge per line, tab separated,
                     loser<TAB>winner<TAB>note
                     ('#' comments and blank lines are skipped)
   --note TEXT       why this merge was decided; recorded on both sides.
                     Required, since a tombstone with no rationale is the
                     thing this repository exists to avoid.
   --algorithms DIR  curated entries (default: data/algorithms)
   --apply           write; without it the result is only described
   -v, --verbose     show each field as it moves (repeatable)
   -h, --help        this help

   A merge is REFUSED, not resolved, when the loser's tool block is at a
   weaker tier than the winner's (unioning would extend the winner's tier
   over unproven identifiers), or when both entries fill a single-valued
   field with different content.

   Run tools/validate.pl and tools/fmt.pl --all --check afterwards.

   Exit 0 success, 1 error, 2 usage.
USAGE
    exit $code;
}

#-----------------------------------------------------------------------
# The merge list.

my @jobs;
for my $p (@pairs) {
    my ($l, $w) = split /:/, $p, 2;
    die "--merge wants LOSER:WINNER, got '$p'\n" unless defined $w && length $l && length $w;
    push @jobs, { loser => $l, winner => $w, note => $note };
}
if ($from) {
    open my $fh, '<', $from or die "cannot read $from: $!\n";
    while (my $line = <$fh>) {
        chomp $line;
        next if $line =~ /^\s*(#|$)/;          # comment or blank
        my ($l, $w, $n) = split /\t/, $line, 3;
        die "$from line $.: want loser<TAB>winner\n" unless defined $w;
        push @jobs, { loser => $l, winner => $w, note => ($n // $note) };
    }
    close $fh;
}

for my $j (@jobs) {
    die "no --note for $j->{loser} -> $j->{winner}; a tombstone needs a reason\n"
        unless defined $j->{note} && length $j->{note};
}

#-----------------------------------------------------------------------
# Load, and self-test the emitter against every file we are about to touch.
#
# seed-upstream.pl does the same thing for the same reason: if entry_text()
# and whatever wrote the file disagree about key order or quoting by one
# character, this script reformats files it did not mean to change and the
# diff stops showing the merge. Refuse up front rather than discover it in
# review.

sub path_of { my ($id) = @_; return "$ALGDIR/$id.yaml" }

sub load_entry {
    my ($id) = @_;
    my $p = path_of($id);
    die "no such entry: $id ($p)\n" unless -r $p;
    my $e = eval { YAML::XS::LoadFile($p) };
    die "cannot parse $p: $@" unless ref $e eq 'HASH';
    return $e;
}

sub file_text {
    my ($id) = @_;
    open my $fh, '<', path_of($id) or die "cannot read " . path_of($id) . ": $!\n";
    local $/;
    my $t = <$fh>;
    close $fh;
    return $t;
}

for my $j (@jobs) {
    for my $id ($j->{loser}, $j->{winner}) {
        my $e   = load_entry($id);
        my $now = file_text($id);
        my $re  = entry_text($e);
        next if $re eq $now;
        die "emitter self-test failed on $id: re-emitting the untouched file\n"
          . "changes it, so this script cannot write it without reformatting.\n"
          . "Fix RosettaEmit or the file before merging.\n";
    }
}

#-----------------------------------------------------------------------
# Field movers.
#
# Tiers, strongest first. A block's tier covers every identifier in it, which
# is why a weaker loser cannot be folded into a stronger winner.

my %TIER_RANK = (vector => 3, upstream => 2, asserted => 1, absent => 0);
my %ID_KEYS   = (hashcat => ['modes'], mdxfind => ['types'], john => ['cpu', 'gpu']);

# union_ids($winner_list, $loser_list) - ordered union, winner's order kept.
# Modes are integers and identifiers are strings; compare stringified so
# 1300 and "1300" cannot both land in the list.
sub union_ids {
    my ($w, $l) = @_;
    my @out  = @{ $w // [] };
    my %seen = map {; "$_" => 1 } @out;
    my $added = 0;
    for my $id (@{ $l // [] }) {
        next if $seen{"$id"}++;
        push @out, $id;
        $added++;
    }
    return (\@out, $added);
}

# merge_tools($winner, $loser, $ctx) - fold the loser's tool blocks into the
# winner's. Returns a list of human-readable descriptions of what moved, or
# dies with the reason a merge is refused.
sub merge_tools {
    my ($W, $L, $ctx) = @_;
    my @moved;

    my $lt = $L->{tools} or return @moved;
    $W->{tools} //= {};

    for my $tool (sort keys %$lt) {
        my $lb = $lt->{$tool};
        next unless ref $lb eq 'HASH';

        # The winner has no block for this tool at all: take the loser's
        # whole block, tier and all. Nothing is being extended over anything.
        if (!$W->{tools}{$tool}) {
            $W->{tools}{$tool} = { %$lb };
            push @moved, "tools.$tool: whole block (tier $lb->{verified})";
            next;
        }

        my $wb = $W->{tools}{$tool};

        # crack: has no identifier list, only a boolean. Disagreement is a
        # real contradiction about the same computation; report it.
        if ($tool eq 'crack') {
            my $ws = $wb->{supported} ? 1 : 0;
            my $ls = $lb->{supported} ? 1 : 0;
            die "$ctx: tools.crack.supported disagrees ($ws vs $ls); "
              . "one of the two entries is wrong and a merge would hide it\n"
                if $ws != $ls;
            next;
        }

        my $wr = $TIER_RANK{ $wb->{verified} // 'asserted' };
        my $lr = $TIER_RANK{ $lb->{verified} // 'asserted' };

        my $has_new = 0;
        for my $k (@{ $ID_KEYS{$tool} // [] }) {
            my (undef, $n) = union_ids($wb->{$k}, $lb->{$k});
            $has_new ||= $n;
        }
        next unless $has_new;   # nothing to move; tier mismatch is then moot

        die "$ctx: tools.$tool would take identifiers proven only at tier "
          . "'$lb->{verified}' into a block claiming '$wb->{verified}'. "
          . "Re-verify them on the winner, or keep both entries.\n"
            if $lr < $wr;

        my @gained;
        for my $k (@{ $ID_KEYS{$tool} // [] }) {
            my ($u, $n) = union_ids($wb->{$k}, $lb->{$k});
            next unless $n;
            # Record what arrived before overwriting, for the note.
            my %was = map {; "$_" => 1 } @{ $wb->{$k} // [] };
            push @gained, grep { !$was{"$_"} } @{ $lb->{$k} // [] };
            $wb->{$k} = $u;
        }
        next unless @gained;

        my $sentence = sprintf(
            '%s came from %s in the %s merge, proven there at tier %s.',
            join(', ', @gained), $L->{id}, $TODAY, $lb->{verified} // 'asserted');
        $wb->{note} = length($wb->{note} // '')
                    ? "$wb->{note} $sentence"
                    : $sentence;
        push @moved, "tools.$tool: " . join(', ', @gained);
    }

    return @moved;
}

# merge_scalars($winner, $loser, $ctx) - move single-valued fields the winner
# does not fill. A field both fill with different content is a disagreement,
# not something to pick a side on.
sub merge_scalars {
    my ($W, $L, $ctx) = @_;
    my @moved;

    for my $k (qw(expression john_dynamic_expr category application
                  application_version)) {
        next unless defined $L->{$k} && length $L->{$k};
        if (!defined $W->{$k} || !length $W->{$k}) {
            $W->{$k} = $L->{$k};
            # expression: and its proof are one claim; never separate them.
            if ($k eq 'expression' && $L->{expression_proof}) {
                $W->{expression_proof} = { %{ $L->{expression_proof} } };
                push @moved, 'expression_proof';
            }
            push @moved, "$k = $L->{$k}";
            next;
        }
        die "$ctx: $k disagrees ('$W->{$k}' vs '$L->{$k}'); if both are true "
          . "these are not one computation\n"
            if $W->{$k} ne $L->{$k};
    }

    # denotation: is illegal beside expression:, so it moves only into an
    # entry that ends the merge without one.
    if ($L->{denotation} && !$W->{denotation} && !defined $W->{expression}) {
        $W->{denotation} = { %{ $L->{denotation} } };
        push @moved, 'denotation';
    }

    return @moved;
}

# merge_lists($winner, $loser, $ctx) - aliases, legacy names and vectors.
sub merge_lists {
    my ($W, $L, $ctx) = @_;
    my @moved;

    # The loser's NAME is the thing a reader searched for. It is the single
    # most important item to carry across: without it the merge makes a name
    # unfindable, which is the opposite of what this repository is for.
    my @alias = @{ $W->{aliases} // [] };
    my %seen  = map {; lc $_ => 1 } @alias, ($W->{name} // ());
    for my $a (($L->{name} // ()), @{ $L->{aliases} // [] }) {
        next unless defined $a && length $a;
        next if $seen{ lc $a }++;
        push @alias, $a;
        push @moved, "alias '$a'";
    }
    $W->{aliases} = \@alias if @alias;

    if ($L->{legacy}) {
        $W->{legacy} //= {};
        for my $k (qw(hashes_org hashkiller)) {
            my $v = $L->{legacy}{$k};
            next unless defined $v && length $v;
            if (!defined $W->{legacy}{$k} || !length $W->{legacy}{$k}) {
                $W->{legacy}{$k} = $v;
                push @moved, "legacy.$k = $v";
                next;
            }
            die "$ctx: legacy.$k disagrees ('$W->{legacy}{$k}' vs '$v')\n"
                if $W->{legacy}{$k} ne $v;
        }
        delete $W->{legacy} unless %{ $W->{legacy} };
    }

    # Vectors are evidence and every one of them is worth keeping: an entry
    # with two independent vectors is one derive-expressions.pl cannot fool
    # with a coincidence. Deduplicate on the hash, case-folded, because the
    # same digest turns up in both cases across sources.
    my @vec  = @{ $W->{vectors} // [] };
    my %have = map {; lc($_->{hash} // '') => 1 } @vec;
    for my $v (@{ $L->{vectors} // [] }) {
        next if $have{ lc($v->{hash} // '') }++;
        push @vec, { %$v };
        push @moved, "vector $v->{hash}";
    }
    $W->{vectors} = \@vec if @vec;

    if (defined $L->{notes} && length $L->{notes}) {
        $W->{notes} = length($W->{notes} // '')
                    ? "$W->{notes} From $L->{id}: $L->{notes}"
                    : $L->{notes};
        push @moved, 'notes';
    }

    return @moved;
}

# merge_relations($winner, $loser) - the loser's edges become the winner's,
# except the edge between the two, which becomes the merge record. Edges the
# loser had pointing elsewhere are RETARGETED at the winner, and the far end
# is fixed up too -- an edge only one side states is the defect relate.pl
# exists to prevent.
sub merge_relations {
    my ($W, $L) = @_;
    my (@moved, @repoint);

    my @rel  = grep { ($_->{entry} // '') ne $L->{id} } @{ $W->{relations} // [] };
    my %seen = map {; "$_->{kind}\0$_->{entry}" => 1 } @rel;

    for my $r (@{ $L->{relations} // [] }) {
        next if ($r->{entry} // '') eq $W->{id};      # the merge edge itself
        next if $seen{ "$r->{kind}\0$r->{entry}" }++;
        push @rel, { %$r };
        push @repoint, $r->{entry};
        push @moved, "relation $r->{kind} -> $r->{entry}";
    }

    # Unconditionally, NOT "if @rel": @rel is the winner's list with its old
    # edge to the loser REMOVED, so an empty @rel is the normal case for a
    # winner whose only relation was the duplicate-of that this merge is
    # replacing. Guarding the assignment left that stale edge in place beside
    # the new merge record, and validate.pl does not catch a repeated edge.
    $W->{relations} = \@rel;
    return (\@moved, \@repoint);
}

#-----------------------------------------------------------------------
# Do it.

my %writes;     # id -> entry hash, accumulated so a batch is one write pass
my $refused = 0;

sub current {
    my ($id) = @_;
    return $writes{$id} //= load_entry($id);
}

for my $j (@jobs) {
    my ($lid, $wid) = ($j->{loser}, $j->{winner});
    my $ctx = "$lid -> $wid";

    die "$ctx: an entry cannot be merged into itself\n" if $lid eq $wid;

    my $L = current($lid);
    my $W = current($wid);

    die "$ctx: $lid is already a tombstone (redirects to $L->{merged_into})\n"
        if ($L->{status} // '') eq 'merged';
    die "$ctx: $wid is a tombstone; repoint the merge at $W->{merged_into} "
      . "rather than building a chain\n"
        if ($W->{status} // '') eq 'merged';

    my @moved;
    push @moved, merge_scalars($W, $L, $ctx);
    push @moved, merge_tools($W, $L, $ctx);
    push @moved, merge_lists($W, $L, $ctx);
    my ($rmoved, $repoint) = merge_relations($W, $L);
    push @moved, @$rmoved;

    # Fix up the far end of every edge the loser had pointing elsewhere.
    for my $far (@$repoint) {
        next unless -r path_of($far);
        my $F = current($far);
        for my $r (@{ $F->{relations} // [] }) {
            $r->{entry} = $wid if ($r->{entry} // '') eq $lid;
        }
        # Retargeting can produce two identical edges where the far entry
        # already pointed at the winner; collapse them.
        my (%s, @keep);
        for my $r (@{ $F->{relations} // [] }) {
            next if $s{ "$r->{kind}\0$r->{entry}" }++;
            push @keep, $r;
        }
        $F->{relations} = \@keep;
    }

    # The winner's edge to the loser, rewritten as the merge record.
    my $merge_note = "merged $TODAY: $j->{note}";
    push @{ $W->{relations} }, {
        kind        => 'duplicate-of',
        entry       => $lid,
        distinction => 'none',
        note        => $merge_note,
    };

    # The loser, emptied. Everything except the redirect is dropped: a
    # tombstone that still carried a mode would be counted twice by every
    # consumer that joins on it, and validate.pl fails on any of them.
    my $notes = sprintf(
        'Tombstone. This id is kept so links and dist/rosetta.csv keys still '
      . 'resolve; every claim it made now lives in %s.yaml. %s',
        $wid, ucfirst($j->{note}));

    %$L = (
        id          => $lid,
        name        => $L->{name},
        status      => 'merged',
        merged_into => $wid,
        relations   => [ {
            kind        => 'duplicate-of',
            entry       => $wid,
            distinction => 'none',
            note        => $merge_note,
        } ],
        notes       => $notes,
    );

    printf "%-46s %d field(s) moved\n", $ctx, scalar @moved;
    if ($verbose) { print "    - $_\n" for @moved }
}

#-----------------------------------------------------------------------
# Write.

if (!$apply) {
    printf STDERR "\n- %d merge(s), %d file(s) would change. Nothing written (no --apply).\n",
        scalar @jobs, scalar keys %writes;
    exit($refused ? 1 : 0);
}

my $changed = 0;
for my $id (sort keys %writes) {
    my $p    = path_of($id);
    my $text = entry_text($writes{$id});

    # Preserve the file mode across the rename, and never truncate the target
    # before the new content is complete on disk.
    my $mode = (stat $p)[2] & 07777;
    my $tmp  = "$p.tmp$$";
    open my $fh, '>', $tmp or die "cannot write $tmp: $!\n";
    print {$fh} $text or die "write failed on $tmp: $!\n";
    close $fh or die "close failed on $tmp: $!\n";
    chmod $mode, $tmp;
    die "refusing to install an empty $p\n" unless -s $tmp;
    rename $tmp, $p or die "cannot rename $tmp to $p: $!\n";
    $changed++;
}

printf STDERR "\n- %d merge(s), %d file(s) written. Run tools/validate.pl next.\n",
    scalar @jobs, $changed;
exit 0;
