#!/usr/bin/perl
#-----------------------------------------------------------------------
#
# Name: normalize-vectors.pl
# Description: put a test vector into the shape every tool here can read, and
#              report the ones that are not vectors at all
# Category: cracking-rosetta curator
#
# Project: cracking-rosetta | Phase: 7 - pre-publication readiness
#
#-----------------------------------------------------------------------
# METHODOLOGY AND WHY THIS EXISTS
#
# WHAT WENT WRONG
#
# The repository's vector convention is a bare digest, with ':salt' appended
# when there is a salt. Some vectors harvested from john instead carry john's
# own ciphertext tag -- "$dynamic_1518$065c78..." and, when salted,
# "$dynamic_1501$<digest>$<salt>". That is a perfectly good john ciphertext
# and unreadable to everything else: hashcat rejects it, mdxfind rejects it,
# and john's own ad-hoc --format=dynamic='EXPR' rejects it too, because the
# tag names a DIFFERENT format from the one being compiled.
#
# The effect was invisible and expensive. derive-expressions.pl requires every
# vector of an entry to fall before it will write an expression, so one tagged
# vector sank an entry whose other vectors were fine, and the entry came out
# the far end as "john states this expression and it does not reproduce our
# data" -- an open question about an algorithm, when it was a question about
# a string.
#
# A separate shape is worse: a hash field that is not a hash. The sheet import
# carried through a literal "--" on one entry. Nothing rejected it, because
# the schema asks only for a non-empty string.
#
# WHY IT VERIFIES BEFORE IT WRITES
#
# Rewriting a vector is rewriting evidence. So a normalized candidate is
# offered to a tool the entry ALREADY names at tier vector, pinned to that
# identifier, and is written only if that tool recovers the entry's own
# plaintext from it. If nothing verifies, the entry is reported and left
# exactly as it was: a failure here is a finding about the entry, not a
# license to guess.
#
# Tiers are never touched. Making a vector readable does not prove anything
# new -- it lets the tools that do the proving see it. Run
# derive-expressions.pl and verify-vectors.pl afterwards.
#
# WHY JUNK IS NOT DELETED BY DEFAULT
#
# Dropping a vector destroys the only copy of something a person once typed.
# --drop-junk is required, it never leaves an entry with no vectors at all,
# and both the count and every affected line are printed first.
#
# DEPENDENCIES
#   perl, YAML::XS, tools/lib/RosettaEmit.pm, and the tools it verifies with
#
#-----------------------------------------------------------------------
# Generated by Claude Opus 5 on 2026-08-30

use strict;
use warnings;

use File::Basename qw(basename);
use FindBin qw($RealBin);
use Getopt::Long qw(GetOptions);
use YAML::XS ();

use lib "$RealBin/lib";
use RosettaEmit qw(emit_entry);
use RosettaTools qw(tool_path tool_env_help);

my $PROG = basename($0);
my $ROOT = "$RealBin/..";
my $TODAY = do { my @t = localtime; sprintf '%04d-%02d-%02d',
                 $t[5]+1900, $t[4]+1, $t[3] };

sub usage {
    print STDERR <<"END_USAGE";

Usage: $PROG [options]

   --algorithms DIR  curated entries (default: data/algorithms)
   --only ID         just this entry (repeatable)
   --work DIR        scratch for hash/word/pot files (default: tmp/normalize)
   --john PATH       john binary    (default: @{[tool_env_help('john')]})
   --mdxfind PATH    mdxfind binary (default: @{[tool_env_help('mdxfind')]})
   --hashcat PATH    hashcat binary (default: @{[tool_env_help('hashcat')]})
   --drop-junk       also remove vectors whose hash cannot be a hash
   --apply           write; without it nothing is changed
   -v, --verbose     per-vector detail
   -h, --help        this help

   Rewrites a vector carrying john's \$dynamic_N\$ ciphertext tag into this
   repository's shape (digest, or digest:salt), but only when a tool the entry
   already names verifies the rewritten form. Reports vectors that are not
   hashes at all; --drop-junk removes them, never leaving an entry empty.

   Tiers are never changed. Exit 0 success, 1 error, 2 usage.

END_USAGE
    return;
}

my ($algdir, $workdir, $john, $mdxfind, $hashcat, $apply, $drop, $help);
my @only;
my $verbose = 0;
GetOptions(
    'algorithms=s' => \$algdir, 'only=s' => \@only, 'work=s' => \$workdir,
    'john=s' => \$john, 'mdxfind=s' => \$mdxfind, 'hashcat=s' => \$hashcat,
    'drop-junk' => \$drop, 'apply' => \$apply,
    'v|verbose+' => \$verbose, 'h|help' => \$help,
) or do { usage(); exit 2 };
if ($help) { usage(); exit 0 }
if (!@only && !$apply && !$verbose && !$drop) { usage(); exit 2 }

$algdir  //= "$ROOT/data/algorithms";
$workdir //= "$ROOT/tmp/normalize";
$john    = tool_path('john',    $john);
$mdxfind = tool_path('mdxfind', $mdxfind);
$hashcat = tool_path('hashcat', $hashcat);
mkdir $workdir unless -d $workdir;
my %scope = map { $_ => 1 } @only;

my ($jdir, $jbin) = $john =~ m{^(.*)/([^/]+)$} ? ($1, $2) : ('.', $john);

#-----------------------------------------------------------------------
# Shape tests.
#
# looks_tagged: john's own ciphertext for a dynamic format. The tag is what
# makes it unreadable elsewhere; everything after it is ours to reshape.
sub looks_tagged { return $_[0] =~ /^\$dynamic_\d+\$/ }

# looks_like_junk: not a hash by any encoding this repository uses.
#
# Deliberately narrow, and narrowed once already after a false positive worth
# remembering: netntlmv1's vector is "::WG:aaaa...:3a29...:1122334455667788",
# whose FIRST colon-separated field is empty. Judging fields made a perfectly
# good challenge-response ciphertext look like junk, and --drop-junk would
# have deleted it. So the test is on the whole string: junk is short AND
# carries no hash characters at all, which is true of "--" and of nothing
# legitimate here.
sub looks_like_junk {
    my ($h) = @_;
    return 0 if $h =~ /^\$/;                 # tagged ciphertext: fine
    return 0 if length($h) >= 8;
    return 1 if $h !~ /[0-9a-zA-Z]/;         # '--', '...', ''
    return 0;
}

#-----------------------------------------------------------------------
# Verification, pinned to an identifier the entry already names.

sub run_quiet {
    my ($cmd) = @_;
    return system("$cmd >/dev/null 2>&1") == 0;
}

# verify_with_john($label, $hash, $pass) - does john, as that format, recover
# that plaintext from that vector? The vector is offered both bare and in
# john's tagged form, because which one a dynamic accepts depends on the
# format, and either answer proves the same thing.
sub verify_with_john {
    my ($label, $hash, $pass) = @_;
    (my $safe = "$label-$hash") =~ s/[^A-Za-z0-9]/_/g;
    $safe = substr($safe, 0, 60);
    my ($h, $salt) = split /:/, $hash, 2;
    my @lines = ("v0\t$hash");
    push @lines, "v0\t\$$label\$$h\$$salt"
        if $label =~ /^dynamic_\d+$/ && defined $salt && length $salt;
    push @lines, "v0\t\$$label\$$h"
        if $label =~ /^dynamic_\d+$/ && !(defined $salt && length $salt);

    open my $fh, '>', "$workdir/$safe.hash" or return 0;
    print {$fh} join("\n", @lines), "\n"; close $fh;
    open my $wf, '>', "$workdir/$safe.word" or return 0;
    print {$wf} "$pass\n"; close $wf;
    unlink "$workdir/$safe.pot";

    run_quiet(sprintf('cd %s && ./%s --format=%s --field-separator-char=tab '
                    . '--wordlist=%s --pot=%s --session=%s %s',
        quotemeta($jdir), quotemeta($jbin), quotemeta($label),
        quotemeta("$workdir/$safe.word"), quotemeta("$workdir/$safe.pot"),
        quotemeta("$workdir/$safe"), quotemeta("$workdir/$safe.hash")));
    my $shown = `cd \Q$jdir\E && ./\Q$jbin\E --show --format=\Q$label\E --field-separator-char=tab --pot=\Q$workdir/$safe.pot\E \Q$workdir/$safe.hash\E 2>/dev/null`;
    return $shown =~ /^v0\t\Q$pass\E$/m ? 1 : 0;
}

# verify_with_mdxfind($type, $iters, $hash, $pass) - pinned to one type, which
# is the only way to read an mdxfind result (gotcha: it reports the FIRST
# internal type that reproduces a digest).
sub verify_with_mdxfind {
    my ($type, $iters, $hash, $pass) = @_;
    (my $safe = "$type-$hash") =~ s/[^A-Za-z0-9]/_/g;
    $safe = substr($safe, 0, 60);
    open my $fh, '>', "$workdir/$safe.hash" or return 0;
    print {$fh} "$hash\n"; close $fh;
    open my $wf, '>', "$workdir/$safe.word" or return 0;
    print {$wf} "$pass\n"; close $wf;
    # -F for a vector carrying its salt inline, -f otherwise.
    my $flag = $hash =~ /:/ ? '-F' : '-f';
    my $out = `\Q$mdxfind\E -h '^\Q$type\E\$' $flag \Q$workdir/$safe.hash\E -i \Q$iters\E \Q$workdir/$safe.word\E 2>/dev/null`;
    return $out =~ /\Q$pass\E\s*$/m ? 1 : 0;
}

# verify_with_hashcat($mode, $hash, $pass)
sub verify_with_hashcat {
    my ($mode, $hash, $pass) = @_;
    (my $safe = "hc$mode-$hash") =~ s/[^A-Za-z0-9]/_/g;
    $safe = substr($safe, 0, 60);
    open my $fh, '>', "$workdir/$safe.hash" or return 0;
    print {$fh} "$hash\n"; close $fh;
    open my $wf, '>', "$workdir/$safe.word" or return 0;
    print {$wf} "$pass\n"; close $wf;
    my $out = `\Q$hashcat\E -m \Q$mode\E -a 0 --quiet --potfile-disable --self-test-disable \Q$workdir/$safe.hash\E \Q$workdir/$safe.word\E 2>/dev/null`;
    return $out =~ /\Q$pass\E\s*$/m ? 1 : 0;
}

# verified_by($entry, $hash, $pass) - the first identifier the entry already
# holds at tier vector that reproduces this candidate, or undef.
sub verified_by {
    my ($e, $hash, $pass) = @_;

    my $mx = $e->{tools}{mdxfind};
    if (ref $mx eq 'HASH' && ($mx->{verified} // '') eq 'vector') {
        my $it = $mx->{iterations} || 1;
        for my $t (@{ $mx->{types} || [] }) {
            return "mdxfind $t" if verify_with_mdxfind($t, $it, $hash, $pass);
        }
    }
    my $hc = $e->{tools}{hashcat};
    if (ref $hc eq 'HASH' && ($hc->{verified} // '') eq 'vector') {
        for my $m (@{ $hc->{modes} || [] }) {
            return "hashcat $m" if verify_with_hashcat($m, $hash, $pass);
        }
    }
    my $jn = $e->{tools}{john};
    if (ref $jn eq 'HASH' && ($jn->{verified} // '') eq 'vector') {
        for my $l (@{ $jn->{cpu} || [] }) {
            return "john $l" if verify_with_john($l, $hash, $pass);
        }
    }
    return undef;
}

#-----------------------------------------------------------------------
# Walk.

opendir(my $dh, $algdir) or do {
    print STDERR "$PROG: cannot read $algdir: $!\n"; exit 1;
};
my @files = sort grep { /\.yaml$/ } readdir $dh;
closedir $dh;

my $start = time;
my ($seen, $tagged, $rewrote, $failed, $junk, $dropped) = (0) x 6;
my (@junk_list, @fail_list);

for my $file (@files) {
    my $stem = $file; $stem =~ s/\.yaml$//;
    next if %scope && !$scope{$stem};
    my $path = "$algdir/$file";
    my $d = eval { YAML::XS::LoadFile($path) } or next;
    next unless ref $d eq 'HASH';
    next if ($d->{status} // '') eq 'merged';
    next unless ref $d->{vectors} eq 'ARRAY' && @{ $d->{vectors} };
    $seen++;

    my $changed = 0;
    my @keep;
    for my $v (@{ $d->{vectors} }) {
        my $hash = $v->{hash} // '';

        if (looks_like_junk($hash)) {
            $junk++;
            push @junk_list, sprintf('%-40s %-12s pass=%s', $stem, "'$hash'", $v->{pass} // '');
            # Never leave an entry with nothing: a junk vector is better than
            # no vector at all, because the entry still says what it is about.
            if ($drop && @{ $d->{vectors} } > 1) { $dropped++; $changed = 1; next }
            push @keep, $v;
            next;
        }

        unless (looks_tagged($hash)) { push @keep, $v; next }
        $tagged++;

        # $dynamic_N$digest  or  $dynamic_N$digest$salt
        my (undef, $tag, @rest) = split /\$/, $hash;
        my $cand = $rest[0] // '';
        $cand .= ':' . $rest[1] if defined $rest[1] && length $rest[1];
        unless (length $cand) { push @keep, $v; next }

        my $by = verified_by($d, $cand, $v->{pass} // '');
        if ($by) {
            printf STDERR "-   %-38s %s -> %s  (%s)\n", $stem,
                substr($hash, 0, 28), substr($cand, 0, 28), $by if $verbose;
            $v->{hash} = $cand;
            $rewrote++;
            $changed = 1;
        }
        else {
            $failed++;
            push @fail_list, sprintf('%-40s %s', $stem, substr($hash, 0, 60));
        }
        push @keep, $v;
    }

    next unless $changed;
    $d->{vectors} = \@keep;
    emit_entry($path, $d) if $apply;
}

#-----------------------------------------------------------------------
# Report.

if (@junk_list) {
    printf STDERR "- %d vector(s) whose hash cannot be a hash%s:\n", scalar @junk_list,
        ($drop ? '' : ' (use --drop-junk to remove)');
    printf STDERR "    %s\n", $_ for @junk_list;
}
if (@fail_list) {
    printf STDERR "- %d tagged vector(s) that NO identifier this entry names could verify;\n"
                . "  left alone. Each is a question about the entry:\n", scalar @fail_list;
    printf STDERR "    %s\n", $_ for @fail_list;
}
printf STDERR "- %d entr(ies) with vectors examined in %ds\n", $seen, time - $start;
printf STDERR "-   tagged %d, rewritten %d, unverifiable %d, junk %d, dropped %d\n",
    $tagged, $rewrote, $failed, $junk, $dropped;
print  STDERR "- nothing written; re-run with --apply\n"
    if !$apply && ($rewrote || $dropped);
print  STDERR "- now run: tools/derive-expressions.pl, tools/verify-vectors.pl, tools/validate.pl\n"
    if $apply && ($rewrote || $dropped);
exit 0;
