#!/usr/bin/perl
#-----------------------------------------------------------------------
#
# Name: probe-gpu.pl
# Description: prove (or refute) a stated GPU-format-to-entry mapping by
#              round-tripping the entry's own vectors, and record it in
#              tools.john.gpu
#
#-----------------------------------------------------------------------
# METHODOLOGY AND WHY THESE CHOICES
#
# WHAT THIS IS FOR, AND WHY discover-john.pl DOES NOT COVER IT
#
# discover-john.pl --mirror-gpu populates tools.john.gpu by looking up the CPU
# format a row already names and mirroring its -opencl/-ztex twin onto the same
# row. That is a lookup, and it is right for the ~96 GPU builds that have one.
# Ten do not: john ships KeePass-Argon2-opencl, TrueCrypt-opencl,
# diskcryptor-aes-opencl, axcrypt2-opencl, electrum-modern-opencl,
# ethereum-presale-opencl, krb5asrep-aes-opencl, ntlmv2-opencl,
# XSHA512-free-opencl and raw-SHA512-free-opencl with no CPU format of the same
# name, so --mirror-gpu reports them and refuses to guess -- correctly, because
# choosing the row is curation.
#
# This tool takes that choice as an ARGUMENT and then removes the guessing from
# what follows. Given "this GPU build belongs on that entry", it hands john the
# ENTRY's own hashes under the GPU format with a wordlist of the ENTRY's own
# plaintexts, and either john recovers them or it does not. A pass is a round
# trip under the exact identifier and reaches tier vector; a failure is
# reported as a failure and nothing is written. The hypothesis is a person's;
# the verdict is john's.
#
# WHY THE WORDLIST IS THE ENTRY'S OWN PLAINTEXTS AND NOTHING ELSE
#
# So that a crack cannot be a coincidence with some other word. john is not
# being asked "what is the password", it is being asked "is THIS the password",
# and the only answers available to it are ones the entry already asserts.
#
# WHY NO CANARY
#
# discover-john.pl skips the canary under --mirror-gpu because a GPU build of
# an algorithm a row already names makes no new ALGORITHMIC claim. The same
# reasoning applies here with one caveat worth stating: these rows have no CPU
# twin, so the row itself is what is being tested. Every one of them is a KDF,
# a container or a challenge-response protocol rather than a truncated or
# masked digest, which is the family the canary exists for. That is an
# argument, not a measurement -- do not extend it to a raw-digest row without
# running discover-john.pl's canary.
#
# WHY --session IS NOT OPTIONAL
#
# john writes john.log and john.rec next to its binary, and on a host where
# that directory belongs to another user the chmod fails and john exits before
# it hashes anything. That reads exactly like "the format did not crack it",
# which is the worst possible failure mode for a tool whose entire output is
# did-it-crack. Every invocation here passes --session into the work dir.
# --field-separator-char=tab for the same class of reason: a $krb5asrep$ or
# NTLMv2 line is full of colons and --show would otherwise be split wrong.
#
# WHY A TIER IS NEVER RAISED
#
# tools.john carries ONE tier for cpu and gpu together. Adding a proven GPU
# identifier to a block whose tier is weaker leaves the tier alone: it
# understates the new claim, which is safe, where raising it would extend the
# stronger tier over CPU identifiers nothing proved at that strength.
#
# DEPENDENCIES: YAML::XS, tools/lib/RosettaEmit.pm, a john with GPU support.
#
#-----------------------------------------------------------------------
# Generated by Claude Opus 5 on 2026-09-01

use strict;
use warnings;

use FindBin ();
use lib "$FindBin::Bin/lib";

use Getopt::Long qw(GetOptions);
use File::Path qw(make_path);
use YAML::XS ();
use RosettaEmit qw(entry_text);

my $PROG   = 'probe-gpu.pl';
my $JOHN   = $ENV{JOHN} || '/usr/local/scripts/johnl';
my $ALGDIR = "$FindBin::Bin/../data/algorithms";
my $WORK   = "$FindBin::Bin/../tmp/probe-gpu";
my $TODAY  = do { my @t = gmtime; sprintf('%04d-%02d-%02d', $t[5]+1900, $t[4]+1, $t[3]) };

my (@pairs, $from, $timeout, $apply, $reuse, $verbose, $help);
$timeout = 900;

GetOptions(
    'pair=s'       => \@pairs,
    'from=s'       => \$from,
    'john=s'       => \$JOHN,
    'algorithms=s' => \$ALGDIR,
    'work=s'       => \$WORK,
    'timeout=i'    => \$timeout,
    'reuse'        => \$reuse,
    'apply'        => \$apply,
    'v|verbose+'   => \$verbose,
    'h|help'       => \$help,
) or usage(2);

usage(0) if $help;
usage(2) unless @pairs || $from;

sub usage {
    my ($code) = @_;
    my $fh = $code ? *STDERR : *STDOUT;
    print {$fh} <<'USAGE';

Usage: probe-gpu.pl --pair GPUFORMAT:ENTRY [--pair ...] [options]
       probe-gpu.pl --from FILE [options]

   --pair G:E        test the hypothesis that john's GPU format G computes
                     what entry E describes, by cracking E's own vectors
                     under G. Repeatable.
   --from FILE       batch: one pair per line, tab separated,
                     gpuformat<TAB>entry  ('#' comments and blanks skipped)
   --john PATH       john binary (default: $JOHN, else /usr/local/scripts/johnl)
   --algorithms DIR  curated entries (default: data/algorithms)
   --work DIR        scratch (default: tmp/probe-gpu)
   --timeout SECS    per john run (default: 900; some of these are Argon2)
   --reuse           re-read a non-empty pot from an earlier run instead of
                     cracking again
   --apply           write the proven mappings into tools.john.gpu
   -v, --verbose     john's output for a pair that did not crack
   -h, --help        this help

   An entry with no vector cannot be tested and is reported as unprovable,
   never assumed. Without --apply nothing is written.

   Exit 0 success, 1 error, 2 usage.
USAGE
    exit $code;
}

#-----------------------------------------------------------------------
# The hypotheses.

my @jobs;
for my $p (@pairs) {
    my ($g, $e) = split /:/, $p, 2;
    die "$PROG: --pair wants GPUFORMAT:ENTRY, got '$p'\n"
        unless defined $e && length $g && length $e;
    push @jobs, [$g, $e];
}
if ($from) {
    open my $fh, '<', $from or die "$PROG: cannot read $from: $!\n";
    while (my $l = <$fh>) {
        chomp $l;
        next if $l =~ /^\s*(#|$)/;
        my ($g, $e) = split /\t/, $l;
        die "$PROG: $from line $.: want gpuformat<TAB>entry\n" unless defined $e;
        push @jobs, [$g, $e];
    }
    close $fh;
}

make_path($WORK) unless -d $WORK;

#-----------------------------------------------------------------------

sub path_of { my ($id) = @_; return "$ALGDIR/$id.yaml" }

sub load_entry {
    my ($id) = @_;
    my $p = path_of($id);
    return undef unless -r $p;
    my $e = eval { YAML::XS::LoadFile($p) };
    return ref $e eq 'HASH' ? $e : undef;
}

# run_john($fmt, $hf, $wf, $pot, $sess) - crack, then read the pot back.
# Built as ONE string per command: written as qx{...} . qq{...} the first half
# executes on its own the moment perl evaluates it, with no hash file, and
# john's complaint is silently concatenated into a result that can never match.
sub run_john {
    my ($fmt, $hf, $wf, $pot, $sess) = @_;

    my $cached = $reuse && -s $pot;
    unlink $pot unless $cached;

    my $out = '(reusing cached pot)';
    unless ($cached) {
        my $c = sprintf('timeout %d %s --format=%s --field-separator-char=tab '
                      . '--wordlist=%s --pot=%s --session=%s %s 2>&1',
                        $timeout, $JOHN, $fmt, $wf, $pot, $sess, $hf);
        $out = qx{$c};
    }

    my $s = sprintf('timeout 120 %s --format=%s --field-separator-char=tab '
                  . '--pot=%s --show %s 2>/dev/null',
                    $JOHN, $fmt, $pot, $hf);
    my $show = qx{$s};

    return ($out, $show);
}

my (@proven, @failed, @unprovable);
my %gpu_for;    # entry id -> [gpu formats proven on it]

for my $job (@jobs) {
    my ($fmt, $id) = @$job;

    my $e = load_entry($id);
    unless ($e) { push @unprovable, "$fmt -> $id (no such entry)"; next }
    if (($e->{status} // '') eq 'merged') {
        push @unprovable, "$fmt -> $id (tombstone; point the pair at $e->{merged_into})";
        next;
    }

    my @vec = grep { defined $_->{hash} && defined $_->{pass} } @{ $e->{vectors} || [] };
    unless (@vec) { push @unprovable, "$fmt -> $id (entry carries no vector)"; next }

    my $slug = "$fmt.$id"; $slug =~ s/[^\w.-]/_/g;
    my ($hf, $wf, $pot) = ("$WORK/$slug.hash", "$WORK/$slug.word", "$WORK/$slug.pot");

    open my $h, '>', $hf or die "$PROG: cannot write $hf: $!\n";
    open my $w, '>', $wf or die "$PROG: cannot write $wf: $!\n";
    print {$h} "$_->{hash}\n" for @vec;
    print {$w} "$_->{pass}\n" for @vec;
    close $h; close $w;

    my ($out, $show) = run_john($fmt, $hf, $wf, $pot, "$WORK/s.$slug");

    # --show prints tab-separated fields ending in the recovered plaintext.
    # The test is that the LAST field is a plaintext this entry already states
    # -- not merely that john cracked something.
    my %want = map {; $_->{pass} => 1 } @vec;
    my $hit  = 0;
    for my $line (split /\n/, $show) {
        next unless $line =~ /\t/;
        my @f = split /\t/, $line;
        $hit++ if defined $f[-1] && $want{ $f[-1] };
    }

    my $n = scalar @vec;
    if ($hit) {
        printf "PROVEN     %-24s -> %-46s %d/%d\n", $fmt, $id, $hit, $n;
        push @proven, [$fmt, $id, $hit, $n];
        push @{ $gpu_for{$id} }, $fmt;
    }
    else {
        printf "no crack   %-24s -> %-46s 0/%d\n", $fmt, $id, $n;
        push @failed, [$fmt, $id, $n];
        if ($verbose) { print "    $_\n" for grep { /\S/ } split /\n/, $out }
    }
}

#-----------------------------------------------------------------------
# Write.

my $written = 0;
if ($apply) {
    for my $id (sort keys %gpu_for) {
        my $e = load_entry($id) or next;
        $e->{tools} //= {};
        my $b = $e->{tools}{john} //= {};

        my @gpu  = @{ $b->{gpu} || [] };
        my %seen = map {; $_ => 1 } @gpu;
        my @new  = grep { !$seen{$_}++ } @{ $gpu_for{$id} };
        next unless @new;
        push @gpu, @new;
        $b->{gpu} = \@gpu;

        # The tier is left alone when the block already claims something
        # stronger or equal; only a block with no tier at all is set here.
        $b->{verified}      //= 'vector';
        $b->{verified_at}     = $TODAY if ($b->{verified} // '') eq 'vector';
        $b->{verified_with} //= 'john 1.9.0-jumbo-1+bleeding-9a336d800a';

        my $sentence = sprintf(
            'GPU build(s) %s proven on %s by cracking this entry\'s own '
          . 'vector(s) under that exact format; john ships no CPU format of '
          . 'that name, so discover-john.pl --mirror-gpu could not place them.',
            join(', ', @new), $TODAY);
        $b->{note} = length($b->{note} // '') ? "$b->{note} $sentence" : $sentence;

        my $p    = path_of($id);
        my $mode = (stat $p)[2] & 07777;
        my $tmp  = "$p.tmp$$";
        open my $fh, '>', $tmp or die "$PROG: cannot write $tmp: $!\n";
        print {$fh} entry_text($e) or die "$PROG: write failed on $tmp: $!\n";
        close $fh or die "$PROG: close failed on $tmp: $!\n";
        chmod $mode, $tmp;
        die "$PROG: refusing to install an empty $p\n" unless -s $tmp;
        rename $tmp, $p or die "$PROG: cannot rename $tmp to $p: $!\n";
        $written++;
    }
}

printf STDERR "\n- proven %d, no crack %d, unprovable %d\n",
    scalar @proven, scalar @failed, scalar @unprovable;
print STDERR "    $_\n" for @unprovable;
printf STDERR "- %s\n", $apply ? "$written file(s) written; run tools/validate.pl next"
                               : 'nothing written (no --apply)';
exit 0;
