#!/usr/bin/perl
#-----------------------------------------------------------------------
#
# Name: relate.pl
# Description: add or remove a typed relation between two entries, writing
#              both sides of it
# Category: cracking-rosetta curator
#
# Project: cracking-rosetta | Phase: 6 - relations between entries
#
#-----------------------------------------------------------------------
# METHODOLOGY AND WHY THIS EXISTS
#
# WHY THE EDGE IS WRITTEN TWICE
#
# A relation is a fact about two entries, and the whole point of one file per
# algorithm is that a reader opens the one file they care about. An edge
# recorded only on joomla is a fact md5-pass-salt does not tell, so whichever
# file the reader opens first decides whether they learn it. validate.pl
# therefore requires every edge to be mirrored, and this is what writes the
# mirror -- by hand it is exactly the sort of bookkeeping that gets half done.
#
# WHY IT IS NOT IN validate.pl
#
# validate.pl is the PR gate. It runs on pull requests from forks, it is the
# thing whose verdict people trust, and it writes nothing at all. Giving it a
# --fix would make the gate a program that edits the data it is judging. The
# check lives there; the repair lives here.
#
# THE VOCABULARY IS NOT DEFINED HERE
#
# kind and distinction are validated by validate.pl against the schema's
# enums, and this script deliberately does not keep a second copy of that list
# to drift out of step. It writes what it is told and leaves the verdict to
# the gate -- run tools/validate.pl afterwards, which the summary says.
#
# BATCHES, BECAUSE COLLISIONS ARRIVE IN GROUPS
#
# An expression claimed by four entries needs six edges, twelve stanzas, and
# getting one of them backwards is invisible until the gate complains. --from
# takes a tab-separated list so a whole curation decision is one reviewable
# input file rather than a dozen invocations.
#
#-----------------------------------------------------------------------
# Generated by Claude Opus 5 on 2026-08-29

use strict;
use warnings;

use File::Basename qw(basename);
use FindBin qw($RealBin);
use Getopt::Long qw(GetOptions);
use YAML::XS ();

use lib "$RealBin/lib";
use RosettaEmit qw(emit_entry);

my $PROG = basename($0);
my $ROOT = "$RealBin/..";

sub usage {
    print STDERR <<"END_USAGE";

Usage: $PROG --kind K --entry A --with B [options]
       $PROG --from FILE [options]

   --kind K          relation kind, e.g. same-computation, encodes,
                     duplicate-of, collides-on-subset
   --entry A         the entry the edge is written on
   --with B          the entry it points at; the mirror is written there
   --distinction D   why both entries exist: application, encoding,
                     input-encoding, iteration, truncation, salt-convention,
                     or none (none is only legal with duplicate-of)
   --note TEXT       free text, required for collides-on-subset
   --from FILE       batch: one edge per line, tab separated,
                     kind<TAB>A<TAB>B<TAB>distinction<TAB>note
                     ('#' comments and blank lines are skipped)
   --remove          delete the edge and its mirror instead of adding
   --algorithms DIR  curated entries (default: data/algorithms)
   --apply           write; without it the edges are only printed
   -v, --verbose     per-edge detail
   -h, --help        this help

   Writes both sides of every edge. Run tools/validate.pl afterwards: it owns
   the vocabulary and the rules, and this script deliberately does not.

   Exit 0 success, 1 error, 2 usage.

END_USAGE
    return;
}

my ($kind, $entry, $with, $distinction, $note, $from, $remove, $algdir,
    $apply, $help);
my $verbose  = 0;
my $had_args = scalar @ARGV;

GetOptions(
    'kind=s'        => \$kind,
    'entry=s'       => \$entry,
    'with=s'        => \$with,
    'distinction=s' => \$distinction,
    'note=s'        => \$note,
    'from=s'        => \$from,
    'remove'        => \$remove,
    'algorithms=s'  => \$algdir,
    'apply'         => \$apply,
    'v|verbose+'    => \$verbose,
    'h|help'        => \$help,
) or do { usage(); exit 2 };

if ($help)      { usage(); exit 0 }
if (!$had_args) { usage(); exit 2 }

$algdir //= "$ROOT/data/algorithms";

#-----------------------------------------------------------------------
# Collect the edges to apply.

my @want;
if (defined $from) {
    open my $fh, '<', $from or do {
        print STDERR "$PROG: cannot read $from: $!\n"; exit 1 };
    my $line = 0;
    while (<$fh>) {
        $line++;
        chomp;
        next if /^\s*(?:#|$)/;
        my ($k, $a, $b, $d, $n) = split /\t/, $_, 5;
        unless (defined $k && defined $a && defined $b) {
            print STDERR "$PROG: $from line $line: need at least kind, A and B\n";
            exit 1;
        }
        push @want, { kind => $k, a => $a, b => $b,
                      distinction => (defined $d && length $d ? $d : undef),
                      note        => (defined $n && length $n ? $n : undef) };
    }
    close $fh;
}
elsif (defined $kind && defined $entry && defined $with) {
    push @want, { kind => $kind, a => $entry, b => $with,
                  distinction => $distinction, note => $note };
}
else {
    print STDERR "$PROG: need --kind with --entry and --with, or --from FILE.\n";
    usage();
    exit 2;
}

#-----------------------------------------------------------------------
# Load only the entries the edges touch.

# What each kind mirrors to on the other entry. Every kind here mirrors to
# ITSELF except covers/covered-by: those state their direction in the kind
# word, so a same-kind mirror would assert both halves of a contradiction.
# validate.pl carries the same table as %REL_MIRROR and is what FAILS when a
# mirror is missing or wrong; this one only decides what gets written. Keep
# them in step -- a kind present here and absent there passes silently, since
# an unlisted kind falls back to mirroring itself on both sides.
my %MIRROR = (
    'covers'     => 'covered-by',
    'covered-by' => 'covers',
);

my (%entry, %path, %dirty);
sub load {
    my ($id) = @_;
    return $entry{$id} if $entry{$id};
    my $p = "$algdir/$id.yaml";
    my $e = eval { YAML::XS::LoadFile($p) };
    unless ($e && $e->{id}) {
        print STDERR "$PROG: no entry '$id' at $p\n";
        return;
    }
    $entry{$id} = $e;
    $path{$id}  = $p;
    return $e;
}

# put_edge($on, $to, $kind, $distinction, $note)
#   Replaces an edge of the same kind to the same entry rather than appending
#   a second one, so re-running with a corrected note is idempotent.
sub put_edge {
    my ($on, $to, $k, $d, $n) = @_;
    my $e = $entry{$on} or return 0;
    my @keep = grep { !(($_->{kind} // '') eq $k && ($_->{entry} // '') eq $to) }
               @{ $e->{relations} || [] };
    my $had = scalar(@{ $e->{relations} || [] }) - scalar @keep;

    if ($remove) {
        $e->{relations} = \@keep;
        delete $e->{relations} unless @keep;
        return $had;
    }

    my %edge = (kind => $k, entry => $to);
    $edge{distinction} = $d if defined $d && length $d;
    $edge{note}        = $n if defined $n && length $n;
    push @keep, \%edge;
    $e->{relations} = \@keep;
    return 1;
}

my $changes = 0;
my $failed  = 0;

for my $w (@want) {
    my ($a, $b) = ($w->{a}, $w->{b});
    if ($a eq $b) {
        print STDERR "$PROG: '$a' cannot relate to itself\n";
        $failed++;
        next;
    }
    unless (load($a) && load($b)) { $failed++; next }

    # The mirror carries the same distinction and note, and USUALLY the same
    # kind: these edges are symmetric statements about a pair, not directed
    # claims about one of them. `covers` is the exception and the only one --
    # its direction is in the kind word, so its mirror is `covered-by` and a
    # same-kind mirror would state both halves of a contradiction. Keep this
    # table in step with %REL_MIRROR in validate.pl, which is what FAILS when
    # a mirror is missing or wrong.
    my $mirror = $MIRROR{ $w->{kind} } // $w->{kind};
    my $n = put_edge($a, $b, $w->{kind}, $w->{distinction}, $w->{note})
          + put_edge($b, $a, $mirror,    $w->{distinction}, $w->{note});
    $changes += $n;
    $dirty{$a} = $dirty{$b} = 1 if $n;

    printf "%s %-18s %s <-> %s%s\n",
        ($remove ? 'remove' : 'add   '), $w->{kind}, $a, $b,
        (defined $w->{distinction} ? "  ($w->{distinction})" : '')
        if $verbose || !$apply;
}

if ($apply) {
    my $written = 0;
    $written += emit_entry($path{$_}, $entry{$_}) for sort keys %dirty;
    printf STDERR "- %d edge side(s) changed, %d file(s) rewritten\n",
        $changes, $written;
    printf STDERR "- now run: tools/validate.pl\n" if $written;
}
else {
    printf STDERR "- %d edge side(s) would change; re-run with --apply\n", $changes;
}

exit($failed ? 1 : 0);
