#!/usr/bin/perl
#-----------------------------------------------------------------------
#
# Name: render.pl
# Description: build the human-browsable views and the machine exports
# Category: cracking-rosetta renderer
#
# Project: cracking-rosetta | Phase: 6 - publish
#
#-----------------------------------------------------------------------
# METHODOLOGY AND WHY THESE CHOICES
#
# ONE FILE PER ALGORITHM IS RIGHT FOR GIT AND WRONG FOR READING
#
# Splitting the data into 784 files bought reviewable diffs, per-algorithm
# blame and path-based CODEOWNERS. It cost the thing the spreadsheet was
# actually good at: opening one page and scanning. This puts that back,
# generated, so nobody has to maintain a table by hand again.
#
# FOUR CELL STATES, NOT TWO
#
# The whole point of the tier column is that "no" and "nobody has looked" are
# different answers, and the old sheet could not tell them apart - a blank cell
# meant either. So a tool cell renders as one of:
#
#   proven    identifiers, verified here by round-trip        (tier vector)
#   claimed   identifiers, asserted or upstream-verified
#   no        the tool genuinely cannot do this               (tier absent)
#   unknown   nobody has said                                 (no block at all)
#
# "unknown" is the gap, and it is deliberately the loudest thing on the page,
# because a gap someone can see is a gap someone might fill.
#
# THE README COUNTER IS UPDATED HERE
#
# README.md carries the algorithm count between <!-- counter --> markers, the
# same trick kens-salty-rainbow uses. Updating it here means the number is a
# by-product of rendering rather than something a person has to remember, and
# it cannot drift from the data the way a hand-typed figure does.
#
# THE HTML CARRIES ITS OWN DATA
#
# The page embeds the rows as JSON and filters client-side. No build step, no
# fetch, no CDN - it works from a file:// URL, from GitHub Pages, and from a
# checkout on a machine with no network. That matters for a reference you might
# want open on a cracking box that is not on the internet.
#
#-----------------------------------------------------------------------
# Generated by Claude Opus 5 on 2026-08-29

use strict;
use warnings;

use File::Basename qw(basename);
use File::Path qw(make_path);
use FindBin qw($RealBin);
use lib "$RealBin/lib";
use Getopt::Long qw(GetOptions);
use JSON::PP ();
use POSIX qw(strftime);
use RosettaHx qw(%MODIFIER);
use YAML::XS ();

my $PROG = basename($0);
my $ROOT = "$RealBin/..";

sub usage {
    print STDERR <<"END_USAGE";

Usage: $PROG [options]

   --algorithms DIR  curated entries (default: data/algorithms)
   --tools DIR       generated inventories (default: data/tools)
   --docs DIR        where ROSETTA.md and index.html go (default: docs)
   --dist DIR        where the csv and json go (default: dist)
   -v, --verbose     counts on stderr
   -h, --help        this help

   Builds docs/index.html (browsable, filterable), docs/ROSETTA.md (flat
   table for GitHub), dist/rosetta.csv and dist/rosetta.json.

   Exit 0 success, 1 error, 2 usage.

END_USAGE
    return;
}

my ($algdir, $tooldir, $docsdir, $distdir, $help);
my $verbose = 0;
GetOptions(
    'algorithms=s' => \$algdir, 'tools=s' => \$tooldir,
    'docs=s' => \$docsdir, 'dist=s' => \$distdir,
    'v|verbose+' => \$verbose, 'h|help' => \$help,
) or do { usage(); exit 2 };
if ($help) { usage(); exit 0 }

$algdir  //= "$ROOT/data/algorithms";
$tooldir //= "$ROOT/data/tools";
$docsdir //= "$ROOT/docs";
$distdir //= "$ROOT/dist";
make_path($_) for grep { !-d } ($docsdir, $distdir);

# The stamp is the date of the last commit touching the data or this script -
# NOT the clock. Using the clock made the output differ between a local run
# and a CI run in another timezone, so the workflow rewrote three files with a
# date-only change every time and fought with local renders. Dating it from
# the source means the same checkout renders identically anywhere, and the
# stamp answers the more useful question: how current is the data?
my $today = `git -C \Q$ROOT\E log -1 --format=%cs -- data tools/render.pl 2>/dev/null`;
chomp $today;
$today = strftime('%Y-%m-%d', localtime) unless $today =~ /^\d{4}-\d{2}-\d{2}$/;

#-----------------------------------------------------------------------
# Load.

my %inv;
for my $t (qw(hashcat john mdxfind)) {
    my $f = "$tooldir/$t.yaml";
    $inv{$t} = -r $f ? YAML::XS::LoadFile($f) : {};
}

#-----------------------------------------------------------------------
# The inventories, indexed by the identifier an ENTRY names, so a practitioner
# column can be looked up rather than searched for. An entry names hashcat
# modes as integers, john formats by label and mdxfind types by name, which is
# exactly what these three keys are.
#
# Not every identifier resolves. 57 of the john labels entries name are real
# dynamics that this build has switched off in dynamic_disabled.conf, so they
# are absent from the inventory and no fact about them can be looked up. That
# is left EMPTY rather than guessed, and counted on stderr under --verbose.
my %by_mode  = map { $_->{mode}  => $_ } @{ $inv{hashcat}{modes}   || [] };
my %by_label = map { $_->{label} => $_ } @{ $inv{john}{formats}    || [] };
my %by_type  = map { $_->{name}  => $_ } @{ $inv{mdxfind}{types}   || [] };
my %unresolved;   # tool => count of identifiers with no inventory record

#-----------------------------------------------------------------------
# The practitioner columns.
#
# THESE ARE FACTS ABOUT A TOOL'S MODE, NOT ABOUT THE ALGORITHM, and that is
# the whole design risk. An entry can name a hashcat mode that takes no salt
# and an mdxfind type that does, because the two tools cut the problem
# differently; a single merged `salted` column would flatten that into a claim
# neither tool makes, which is precisely the conflation the two-layer split
# exists to prevent. So every column below is per-tool and says so in its
# name. There is deliberately no algorithm-level `salted`.
#
# Nothing here is curated and nothing here needs a tier. Each value is read
# straight out of data/tools/*.yaml, which is regenerated from the binary, so
# these columns cannot go stale relative to the tool the way a hand-written
# field would.

# tool_fact(\@ids, \%index, \&test) - fold a per-identifier yes/no over every
# identifier an entry names for one tool.
#
#   yes / no  every identifier that resolves agrees
#   mixed     they do not, and that is a real finding rather than an error --
#             the entry names two modes of one tool that differ on this
#   ''        the entry names none, or none of them resolve
#
# 'mixed' is never collapsed to a majority. A reader who has to know which of
# two modes they are holding is better served by being told the row is not
# uniform than by being handed the more common answer.
sub tool_fact {
    my ($ids, $index, $test) = @_;
    my @known = grep { $index->{$_} } @$ids;
    return '' unless @known;
    my %seen = map { ($test->($index->{$_}) ? 'yes' : 'no') => 1 } @known;
    return keys(%seen) > 1 ? 'mixed' : (keys %seen)[0];
}

# nesting_depth($expression) - how many hash applications deep the deepest
# operand sits. md5($p.$s) is 1, md5(md5($p)) is 2, and md5(upper(md5($p)))
# is 2 as well, because upper() changes the REPRESENTATION of a digest
# without computing another one.
#
# That last case is why this cannot be a paren counter: it would say 3, and
# the number a practitioner wants is how many times the input is hashed.
# Telling the two apart needs the modifier set, which is why %MODIFIER is
# declared in RosettaHx beside %FUNC rather than copied here -- a modifier
# added there and not here would silently inflate every depth that used it.
#
# Everything that is not a modifier is counted as a hash. The one structural
# guard is that the parentheses must balance; if they do not, the depth comes
# back undef and the column is left empty rather than reporting the count of
# something it failed to parse.
#
# There is deliberately no whitelist of legal characters. 20 expressions carry
# john's constant syntax -- md5($s.$c1.$p),c1=\x00, and {SSHA} and * as
# constant VALUES -- which a whitelist would have refused although the
# construction parses perfectly well: the constants sit after the expression
# and outside every bracket, so they contribute no token and no depth.
sub nesting_depth {
    my ($expr) = @_;
    return undef unless defined $expr && length $expr;
    my ($depth, $max) = (0, 0);
    my @stack;
    my @tok = ($expr =~ /([A-Za-z_][A-Za-z0-9_]*\(|\(|\))/g);
    for my $t (@tok) {
        if ($t eq ')') { $depth -= pop(@stack) // 0 }
        elsif ($t eq '(') { push @stack, 0 }              # a bare group
        else {
            my $fn = substr($t, 0, -1);
            my $is_hash = !$MODIFIER{$fn};
            push @stack, $is_hash ? 1 : 0;
            $depth += $is_hash ? 1 : 0;
            $max = $depth if $depth > $max;
        }
    }
    return undef if @stack;          # unbalanced: say nothing
    return $max;
}

# hash_length($entry) - how long the hash string on this row actually is, and
# how well that is evidenced.
#
# It measures the leading colon-delimited field when that field is entirely
# hex, which for a salted vector is the digest and for a bare one is the whole
# string. A container format ($2a$05$..., a volume header) has no such field
# and honestly yields nothing rather than a number that means something else.
#
# It is the length of the STRING a reader is holding, not the width of the
# underlying digest, and the two part company on blob formats -- pwsafe3's
# vector here is 144 hex characters and hashcat's example of the same mode is
# 720. That is why hashcat's example_hash is NOT folded in: on the 263 rows
# where both exist they agree 262 times, so the second source buys one
# disagreement and no information.
#
# The basis is the honest part. Only 137 entries carry two or more vectors, so
# on most rows a single length is one sample and not evidence that the length
# is fixed:
#
#   fixed     two or more vectors, all the same length
#   observed  exactly one vector -- true of what was seen, and no more
#   varies    the vectors disagree, and on six rows they do so for a reason
#             (lm is 16 or 32; mysql4-1-mysql5 is 32 or 40). Both lengths are
#             reported, because which one a reader is holding is the question.
#   ''        no vector has a leading hex field
sub hash_length {
    my ($e) = @_;
    my @len;
    for my $v (@{ $e->{vectors} || [] }) {
        my $h = $v->{hash};
        next unless defined $h;
        my ($first) = split /:/, $h, 2;
        push @len, length($first) if defined $first && $first =~ /^[0-9a-fA-F]+$/;
    }
    return ('', '') unless @len;
    my %u = map { $_ => 1 } @len;
    my @s = sort { $a <=> $b } keys %u;
    return (join('; ', @s), 'varies') if @s > 1;
    return ($s[0], @len > 1 ? 'fixed' : 'observed');
}

opendir(my $dh, $algdir) or do { print STDERR "$PROG: cannot read $algdir: $!\n"; exit 1 };
my @files = sort grep { /\.yaml$/ } readdir $dh;
closedir $dh;

# A tombstone (status: merged) is separated here, once, rather than tested for
# in every view below. It is not an algorithm: it is the id of one that lost a
# merge, kept alive because that id is the key in dist/rosetta.csv and the
# name someone may still search for. It appears in the exports as a row that
# makes no claims and names its survivor, and in the two human views as a
# short list at the end -- never as a row of dashes in the middle of the
# table, which would read as a gap rather than as a redirect.
my (@rows, @tombs);
for my $f (@files) {
    my $e = eval { YAML::XS::LoadFile("$algdir/$f") } or next;
    next unless $e->{id};
    push @{ ($e->{status} // '') eq 'merged' ? \@tombs : \@rows }, $e;
}
@rows  = sort { lc($a->{name} // $a->{id}) cmp lc($b->{name} // $b->{id}) } @rows;
@tombs = sort { $a->{id} cmp $b->{id} } @tombs;

#-----------------------------------------------------------------------
# Reduce one tool block to a cell: state plus the identifiers to show.

sub cell {
    my ($e, $tool) = @_;
    my $b = $e->{tools}{$tool};
    return { state => 'unknown', ids => [] } unless $b;

    my @ids = $tool eq 'hashcat' ? @{ $b->{modes} || [] }
            : $tool eq 'mdxfind' ? @{ $b->{types} || [] }
            : $tool eq 'john'    ? (@{ $b->{cpu} || [] }, @{ $b->{gpu} || [] })
            :                      ();

    my $tier = $b->{verified} // 'asserted';

    if ($tool eq 'crack') {
        return { state => (defined $b->{supported} && $b->{supported} ? 'claimed' : 'no'),
                 ids => [] };
    }
    return { state => 'no', ids => [] } if !@ids && $tier eq 'absent';
    return { state => 'unknown', ids => [] } unless @ids;

    my $label = $tool eq 'mdxfind' && $b->{iterations} && $b->{iterations} > 1
              ? [ map { "$_ -i$b->{iterations}" } @ids ]
              : [@ids];
    return { state => ($tier eq 'vector' ? 'proven' : 'claimed'),
             ids => $label, tier => $tier };
}

# same_as($entry) - the relations as one phrase a person can read in a table
# cell. A row that says "md5($p.$s)" twice in a 784-row table is a puzzle; a
# row that says "same as md5-pass-salt (application)" is an answer.
sub same_as {
    my ($e) = @_;
    my @r = @{ $e->{relations} || [] } or return '';
    my %verb = (
        'same-computation'   => 'same as',
        'encodes'            => 'encoding of',
        'input-encoding'     => 'input encoding of',
        'iterates'           => 'iterates',
        'truncates'          => 'truncates',
        'collides-on-subset' => 'collides with',
        'duplicate-of'       => 'duplicate of',
    );
    my @parts;
    for my $rel (sort { ($a->{kind} // '') cmp ($b->{kind} // '')
                     || ($a->{entry} // '') cmp ($b->{entry} // '') } @r) {
        my $v = $verb{ $rel->{kind} // '' } // ($rel->{kind} // '?');
        my $d = $rel->{distinction};
        push @parts, sprintf('%s %s%s', $v, $rel->{entry},
            (defined $d && length $d && $d ne 'none') ? " ($d)" : '');
    }
    return join('; ', @parts);
}

my (%tally, %state_count);
my @out;
for my $e (@rows) {
    my %r = (
        id     => $e->{id},
        name   => $e->{name} // $e->{id},
        alias  => join('; ', @{ $e->{aliases} || [] }),
        expr   => $e->{expression} // '',
        # The tier on the expression, and the fallback wording for a row that
        # has none. The expression has never appeared in the HTML or Markdown
        # tables -- those show name: -- so these follow it into the two
        # machine-consumption views and nowhere else.
        expr_tier  => (ref $e->{expression_proof} eq 'HASH'
                       ? ($e->{expression_proof}{verified} // '') : ''),
        # The same claim in john's own notation, which is NOT always the same
        # string: expression: is hx-style and writes a change of
        # representation as a wrapper -- upper(md5($p)) -- where john writes
        # it as a flavour of the hash function -- MD5($p). Copying the
        # expression column into a --format=dynamic= would hand a reader a
        # syntax error on 48 rows, so the runnable form is published
        # separately rather than left to be reconstructed.
        john_expr  => $e->{john_dynamic_expr} // '',
        denotation => (ref $e->{denotation} eq 'HASH'
                       ? ($e->{denotation}{text} // '') : ''),
        status => $e->{status} // 'ok',
        vecs   => scalar @{ $e->{vectors} || [] },
        # serialization: do the tools agree about the STRING, not just the
        # algorithm? Derived, never asserted -- from reads_in, which
        # verify-vectors.pl measures, and credential, which a curator sets to
        # say two spellings are one credential.
        #
        #   divergent  the entry holds one credential written more than one
        #              way, so a hash in one tool's form must be re-encoded
        #              for the other
        #   shared     one string was proven to load in two or more tools
        #   unknown    nothing has established either way
        #
        # Until this column existed, 197 entries had PROVEN that a single
        # string satisfies both hashcat and john and said so nowhere, and a
        # reader holding one could not tell that from "nobody checked".
        serialization => do {
            my ($shared, %tools) = (0);
            for my $v (@{ $e->{vectors} || [] }) {
                next unless ref $v->{reads_in} eq 'ARRAY';
                my @r = @{ $v->{reads_in} };
                $shared = 1 if @r > 1;      # one string, more than one tool
                $tools{$_} = 1 for @r;
            }
            # divergent needs no credential group: reads_in already proves it.
            # verify-vectors runs every tool against every vector of an entry
            # with every plaintext in the wordlist, so a tool that read none of
            # another tool's strings was given the chance and declined. Two
            # tools that each read something, and never the same something, do
            # not take each other's format.
            #
            # credential: adds the stronger claim -- that the two strings are
            # ONE credential rather than each tool's own example -- which
            # nothing in the strings can establish and only a curator sets.
            # Pairwise agreement is not the question a reader has. They hold
            # one string and want to know whether the other tools take it, so
            # the test is whether SOME vector is read by every tool that reads
            # anything here. scrypt is why: its hashcat vector is read by
            # mdxfind too, which looked like agreement, while john refuses
            # both strings and wants $7$86....NaCl$... of its own.
            my $all = join ',', sort keys %tools;
            $shared = 0;
            for my $v (@{ $e->{vectors} || [] }) {
                next unless ref $v->{reads_in} eq 'ARRAY';
                $shared = 1 if join(',', sort @{ $v->{reads_in} }) eq $all;
            }
              keys(%tools) < 2 ? 'unknown'
            : $shared          ? 'shared'
            :                    'divergent';
        },
        # Which form is PRIMARY. The native form -- what the producing system
        # itself stores -- outranks every tool's rewriting of it, so this is
        # simply which vector is native, if the entry knows. Empty means
        # nobody has said, and on a row whose serialization is 'divergent'
        # that is a live question rather than a shrug: a reader holding one of
        # several strings cannot tell the real credential from a cracker's
        # re-encoding of it. Derived, never asserted -- there is no 'primary'
        # flag in the data to drift out of step with this.
        primary_form => do {
            my ($p) = grep { ($_->{form} // '') eq 'native' }
                      @{ $e->{vectors} || [] };
            $p ? 'native' : '';
        },
        notes  => $e->{notes} // '',
        legacy => join('; ', grep { defined && length }
                        ($e->{legacy}{hashes_org}, $e->{legacy}{hashkiller})),
        # The practitioner columns. Per-tool by design -- see tool_fact above
        # for why there is no merged `salted`.
        hashcat_salted => tool_fact($e->{tools}{hashcat}{modes} || [],
                              \%by_mode, sub { exists $_[0]{salt_type} }),
        # hashcat publishes the fast/slow split itself, which is the
        # distinction a practitioner actually plans around, and it cannot go
        # stale relative to hashcat the way a benchmarked H/s figure on this
        # host's one GPU would.
        hashcat_speed  => (tool_fact($e->{tools}{hashcat}{modes} || [],
                              \%by_mode, sub { $_[0]{slow} })
                           =~ s/^yes$/slow/r =~ s/^no$/fast/r),
        john_salted    => tool_fact([ @{ $e->{tools}{john}{cpu} || [] },
                                      @{ $e->{tools}{john}{gpu} || [] } ],
                              \%by_label, sub { ($_[0]{salt_size} // 0) > 0 }),
        # john's own words for what it can tune, verbatim: "iteration count",
        # "N,r,p", argon2's "t,m,p,type". Several formats on one row can name
        # different costs, so they are joined rather than reduced -- an entry
        # spanning bcrypt and scrypt has two answers and should say so.
        john_work_factor => do {
            my %c;
            for my $l (@{ $e->{tools}{john}{cpu} || [] },
                       @{ $e->{tools}{john}{gpu} || [] }) {
                next unless $by_label{$l};
                my $t = $by_label{$l}{tunable_cost};
                $c{$t} = 1 if defined $t && length $t;
            }
            join('; ', sort keys %c);
        },
        mdxfind_salted => tool_fact($e->{tools}{mdxfind}{types} || [],
                              \%by_type,
                              sub { grep { $_ eq 's' } @{ $_[0]{flags} || [] } }),
        nesting_depth  => (nesting_depth($e->{expression}) // ''),
        category    => $e->{category} // '',
        application => join(' ', grep { defined && length }
                             ($e->{application}, $e->{application_version})),
        # Full edges for machines; one short phrase for people.
        relations   => [ map { { kind        => $_->{kind},
                                 entry       => $_->{entry},
                                 distinction => $_->{distinction} // '',
                                 note        => $_->{note} // '' } }
                         @{ $e->{relations} || [] } ],
        sameas      => same_as($e),
        # Why the tier is what it is. Carried for docs/OPEN-QUESTIONS.md,
        # which is only useful if it can print the reason already recorded on
        # the entry rather than re-deriving a worse one.
        expr_note   => (ref $e->{expression_proof} eq 'HASH'
                        ? ($e->{expression_proof}{note} // '') : ''),
        tool_note   => { map { $_ => ($e->{tools}{$_}{note} // '') }
                         qw(hashcat john mdxfind) },
    );
    ($r{hash_length}, $r{hash_length_basis}) = hash_length($e);

    # Identifiers an entry names that the inventory does not have. Counted
    # rather than silently skipped, because the practitioner columns above go
    # empty on exactly these and a reader is owed the reason.
    $unresolved{hashcat} += grep { !$by_mode{$_} }
                            @{ $e->{tools}{hashcat}{modes} || [] };
    $unresolved{john}    += grep { !$by_label{$_} }
                            (@{ $e->{tools}{john}{cpu} || [] },
                             @{ $e->{tools}{john}{gpu} || [] });
    $unresolved{mdxfind} += grep { !$by_type{$_} }
                            @{ $e->{tools}{mdxfind}{types} || [] };

    for my $t (qw(hashcat john mdxfind crack)) {
        my $c = cell($e, $t);
        $r{$t} = $c;
        $r{cracknote} = $e->{tools}{crack}{note} // '' if $t eq 'crack';
        $state_count{$t}{ $c->{state} }++;
    }
    $tally{ $r{status} }++;
    push @out, \%r;
}

# The export shape of a tombstone: the id, the name it had, where it went, and
# nothing else. Every claim column is empty on purpose -- an empty cell says
# "this row asserts nothing", where 'unknown' would say "nobody has checked",
# which is a statement about an algorithm this row no longer is.
my @tomb_out = map { {
    id     => $_->{id},
    name   => $_->{name} // $_->{id},
    into   => $_->{merged_into} // '',
    sameas => same_as($_),
    notes  => $_->{notes} // '',
} } @tombs;

#-----------------------------------------------------------------------
# dist/rosetta.csv - the closest thing to "open it in a spreadsheet".

sub csv_field {
    my ($v) = @_;
    $v //= '';
    return $v unless $v =~ /[",\n]/;
    $v =~ s/"/""/g;
    return qq{"$v"};
}

# merged_into follows status because it qualifies it, and is empty on every
# live row. It is a column rather than something to be dug out of the
# relations prose: the whole reason a merged id keeps a row is that a machine
# joining on it should be told where the row went.
# The practitioner columns sit between primary_form and the prose, because
# they are the same kind of thing as the columns before them -- derived,
# single-valued, machine-read -- and relations/legacy/notes are the long
# free text a spreadsheet reader wants at the far right.
#
# Every one of them names its tool. They are facts about a MODE, not about an
# algorithm, and a bare `salted` column would invite a reader to take one
# tool's convention for the algorithm's own.
my @CSV = qw(id name aliases expression expression_tier john_dynamic_expr
             denotation category application status merged_into
             hashcat hashcat_state john john_state mdxfind mdxfind_state
             crack_state vectors serialization primary_form
             hashcat_salted hashcat_speed john_salted john_work_factor
             mdxfind_salted nesting_depth hash_length hash_length_basis
             relations legacy notes);

# csv_row(@fields) - one row, with the field count checked against the header.
#
# A row that is one field short is not a parse error for most consumers: it
# shifts every column after the gap by one and each cell still looks
# plausible. Adding a column means touching the header, the live row and the
# tombstone row, and the tombstone row is the one that gets forgotten, so the
# count is asserted rather than trusted.
sub csv_row {
    my @f = @_;
    die sprintf("csv_row: %d field(s), header has %d\n", scalar @f, scalar @CSV)
        unless @f == @CSV;
    return join(',', map { csv_field($_) } @f) . "\n";
}

open my $csv, '>', "$distdir/rosetta.csv" or die "cannot write csv: $!\n";
print {$csv} join(',', @CSV), "\n";
for my $r (@out) {
    print {$csv} csv_row(
        $r->{id}, $r->{name}, $r->{alias}, $r->{expr},
        $r->{expr_tier}, $r->{john_expr}, $r->{denotation},
        $r->{category}, $r->{application}, $r->{status}, '',
        join(' ', @{ $r->{hashcat}{ids} }), $r->{hashcat}{state},
        join(' ', @{ $r->{john}{ids} }),    $r->{john}{state},
        join(' ', @{ $r->{mdxfind}{ids} }), $r->{mdxfind}{state},
        $r->{crack}{state}, $r->{vecs}, $r->{serialization},
        $r->{primary_form},
        $r->{hashcat_salted}, $r->{hashcat_speed}, $r->{john_salted},
        $r->{john_work_factor}, $r->{mdxfind_salted}, $r->{nesting_depth},
        $r->{hash_length}, $r->{hash_length_basis},
        $r->{sameas}, $r->{legacy}, $r->{notes},
    );
}
# Tombstones last, so the live table stays one contiguous block for anyone
# reading the file by eye rather than by key.
for my $t (@tomb_out) {
    # Every claim column empty on purpose: an empty cell says "this row
    # asserts nothing", where a value would say something about an algorithm
    # this row no longer is. The practitioner columns are claims like any
    # other, so they are empty here too.
    print {$csv} csv_row(
        $t->{id}, $t->{name}, '', '', '', '', '', '', '', 'merged', $t->{into},
        ('') x 10,                         # the tool and vector columns
        ('') x 8,                          # the practitioner columns
        $t->{sameas}, '', $t->{notes},
    );
}
close $csv;

#-----------------------------------------------------------------------
# dist/rosetta.json

my $json = JSON::PP->new->canonical->pretty;
open my $jf, '>', "$distdir/rosetta.json" or die "cannot write json: $!\n";
print {$jf} $json->encode({
    generated => $today,
    tools     => { map { $_ => ($inv{$_}{version} // 'unknown') } qw(hashcat john mdxfind) },
    # count is the number of algorithms, which is what it has always meant.
    # Tombstones are counted separately rather than folded in, so a merge
    # cannot look like the corpus growing.
    count     => scalar @out,
    merged    => scalar @tomb_out,
    entries   => \@out,
    tombstones=> [ map { { id     => $_->{id}, name => $_->{name},
                           status => 'merged', merged_into => $_->{into},
                           relations_text => $_->{sameas} } } @tomb_out ],
});
close $jf;

#-----------------------------------------------------------------------
# docs/ROSETTA.md - flat table, readable straight on GitHub.

# wrap_name($name) - give a long expression name somewhere to break.
#
# 12 of 784 names are single unbreakable runs over 45 characters, and because
# a table is as wide as its widest cell, those 12 rows were forcing horizontal
# scrolling on GitHub for the whole thing. Composed expressions concatenate at
# the top level - md5(A).md5(A).md5(A) - so a break at the shallowest '.'
# splits them into readable chunks.
sub wrap_name {
    my ($n) = @_;
    my $longest = 0;
    for my $tok (split /\s+/, $n) {
        $longest = length($tok) if length($tok) > $longest;
    }
    return $n if $longest <= 44;

    my @ch = split //, $n;

    # The break depth is wherever the SHALLOWEST '.' sits, not necessarily
    # zero: md5(A.B.C) wraps the whole composition in an outer call, putting
    # its separators at depth one. Dots deeper than that are inside a single
    # operand and are left alone.
    my ($depth, $min) = (0, undef);
    for my $c (@ch) {
        $depth++ if $c eq '(';
        $depth-- if $c eq ')';
        $min = $depth if $c eq '.' && (!defined $min || $depth < $min);
    }
    return $n unless defined $min;

    my $out = '';
    $depth = 0;
    for my $c (@ch) {
        $depth++ if $c eq '(';
        $depth-- if $c eq ')';
        $out .= $c;
        $out .= '<br>' if $c eq '.' && $depth == $min;
    }
    return $out;
}

# md_cell($cell) - one table cell.
#
# Identifiers are stacked with <br> rather than joined with ", ". A cell
# reading "`dynamic_1`, `dynamic_1016`, `dynamic_2001`" is 43 characters wide
# and forces the whole table past GitHub's content column, which then scrolls
# horizontally. Stacked, the same cell is as wide as its longest single
# identifier. Nothing is lost and the column gets roughly three times narrower.
sub md_cell {
    my ($c) = @_;
    return '**--**'    if $c->{state} eq 'unknown';
    return 'no'       if $c->{state} eq 'no';
    # Crack carries a state but never identifiers; saying "yes" for anything
    # that merely is not 'no' would have claimed Crack supports every entry.
    return 'yes'   unless @{ $c->{ids} };
    my $t = join('<br>', map { "`$_`" } @{ $c->{ids} });
    return $c->{state} eq 'proven' ? "$t (v)" : $t;
}

open my $md, '>', "$docsdir/ROSETTA.md" or die "cannot write md: $!\n";
printf {$md} "# Rosetta table\n\n";
printf {$md} "GENERATED by `tools/%s` on %s - do not edit; regenerate.\n\n", $PROG, $today;
printf {$md} "%d algorithms. hashcat %s, john %s, mdxfind %s.\n\n",
    scalar @out, $inv{hashcat}{version} // '?', $inv{john}{version} // '?',
    $inv{mdxfind}{version} // '?';
print  {$md} <<'LEGEND';
`x` (v) verified here by round-trip; `x` claimed, not verified; `no` tool
does not support it; **--** nobody has said yet (a gap worth filling)

(c) also attackable by Alec Muffett's Crack - see [CRACK.md](CRACK.md).

For sorting, filtering and search, open [index.html](index.html) - or
[dist/rosetta.csv](../dist/rosetta.csv) in a spreadsheet.

This table stays narrow enough to read on GitHub, so the practitioner columns
- whether a tool salts it, hashcat's fast/slow split, John's tunable cost, how
long the hash string is and how many hashes deep the construction goes - are
in those two views rather than here. They are read straight out of the tool
inventories, and each one names the tool it came from: an entry can name a
hashcat mode that takes no salt and an mdxfind type that does.

LEGEND
# Crack gets a dagger, not a column. It attacks 2 of these algorithms, so a
# column would say "no" on every row but two to buy two rows of information.
# The data
# itself is unchanged in data/algorithms, the CSV and the JSON; only the
# presentation moves, to docs/CRACK.md and a marker on the rows it concerns.
print  {$md} "| Algorithm | hashcat | John | mdxfind | Same as |\n|---|---|---|---|---|\n";
for my $r (@out) {
    my $n = wrap_name($r->{name}); $n =~ s/\|/\\|/g;
    $n .= ' (c)' if $r->{crack}{state} ne 'no' && $r->{crack}{state} ne 'unknown';
    my $rel = $r->{sameas}; $rel =~ s/\|/\\|/g;
    printf {$md} "| %s | %s | %s | %s | %s |\n", $n,
        md_cell($r->{hashcat}), md_cell($r->{john}), md_cell($r->{mdxfind}),
        (length $rel ? $rel : '');
}

# Merged ids go under the table, not in it. Someone who followed an old link
# or searched an old name needs one sentence telling them where it went; a row
# of empty cells in the main table would tell them the opposite.
if (@tomb_out) {
    print {$md} "\n## Merged ids\n\n";
    print {$md} "These ids no longer name an algorithm of their own. Each was folded\n"
              . "into the entry beside it and is kept so old links and\n"
              . "[dist/rosetta.csv](../dist/rosetta.csv) keys still resolve.\n\n";
    print {$md} "| Merged id | Now see |\n|---|---|\n";
    my %name_of = map { $_->{id} => $_->{name} } @out;
    for my $t (@tomb_out) {
        printf {$md} "| `%s` | %s (`%s`) |\n", $t->{id},
            $name_of{ $t->{into} } // $t->{into}, $t->{into};
    }
}
close $md;

#-----------------------------------------------------------------------
# docs/GAPS.md - what is missing, as an invitation rather than an apology.
#
# "unknown" is deliberately the loudest state on the browsable page, and 538
# empty john cells are the single most useful thing a stranger could fix. But
# a gap is only an invitation if someone can see WHICH gaps and what filling
# one costs, and neither the table nor the CSV answers that: they are sorted
# by name, so the promotable rows are scattered through 784 of them.
#
# So this page ranks by what it costs to fix. The order is deliberate:
#
#   1. a claim below tier vector -- somebody already believes it, the entry
#      has a vector, and one command settles it. Cheapest possible
#      contribution for a person who owns the tool;
#   2. no vector at all -- blocked on one piece of data, and anyone who has
#      that data can supply it without owning any cracker;
#   3. a whole tool column unknown -- real work, listed by example rather
#      than exhaustively, with the query for the rest;
#   4. hashcat modes with no row at all.
#
# Everything here is derived, so it cannot drift from the data the way a
# hand-kept "help wanted" list does.

my (@promotable, @novector, %unknown_by_tool);
for my $r (@out) {
    push @novector, $r unless $r->{vecs};
    for my $t (qw(hashcat john mdxfind)) {
        my $c = $r->{$t};
        push @{ $unknown_by_tool{$t} }, $r if $c->{state} eq 'unknown';
        # 'claimed' is the render-side name for a tier of upstream or
        # asserted: identifiers are recorded, nothing round-tripped them.
        push @promotable, { row => $r, tool => $t, tier => $c->{tier} // '?' }
            if $c->{state} eq 'claimed' && $r->{vecs};
    }
}

# hashcat modes nobody has claimed. The inventory is the denominator the
# coverage line in validate.pl uses, so this is the same set it counts.
my %claimed_mode;
for my $r (@out) { $claimed_mode{$_} = 1 for @{ $r->{hashcat}{ids} } }
my @orphan_modes = grep { !$claimed_mode{ $_->{mode} } }
                   @{ $inv{hashcat}{modes} || [] };

sub gaps_link {
    my ($r) = @_;
    return sprintf('[`%s`](index.html#%s)', $r->{id}, $r->{id});
}

open my $gp, '>', "$docsdir/GAPS.md" or die "cannot write GAPS.md: $!\n";
printf {$gp} "# Gaps worth filling\n\n";
printf {$gp} "GENERATED by `tools/%s` on %s - do not edit; regenerate.\n\n", $PROG, $today;
print  {$gp} <<'GAPS_HEAD';
A gap here is not a claim that a tool cannot do something. It means nobody has
said. That is the honest state of a cross-reference nobody has finished, and
it is also the shortest path to being useful to it.

Two ways in, and the first needs no cracker installed:

* **Open an issue** with what you know - an identifier, or better, a test
  vector. "A missing algorithm" and "a mapping is wrong" are the two forms.
* **Open a pull request** against the one small YAML file under
  `data/algorithms/`. `CONTRIBUTING.md` walks through it.

Each row below links to its entry in the [browsable table](index.html).
Gaps are absences; for the rows where something is known to be *odd*, see
[OPEN-QUESTIONS.md](OPEN-QUESTIONS.md).

GAPS_HEAD

printf {$gp} "## 1. Believed but never reproduced (%d)\n\n", scalar @promotable;
print  {$gp} <<'GAPS_1';
The cheapest contribution in the repository, if you own the tool. Each of
these already names an identifier and already carries a test vector; nobody
has run the one against the other. One command decides it, and a failure is
as useful as a success - it means the mapping is wrong and the row should say
so.

```sh
tools/verify-vectors.pl --tool <tool> --only <id> -v
```

| Entry | Tool | Says | Tier |
|---|---|---|---|
GAPS_1
for my $g (sort { $a->{row}{id} cmp $b->{row}{id} } @promotable) {
    printf {$gp} "| %s | %s | `%s` | %s |\n", gaps_link($g->{row}), $g->{tool},
        join('`, `', @{ $g->{row}{ $g->{tool} }{ids} }), $g->{tier};
}

printf {$gp} "\n## 2. No test vector at all (%d)\n\n", scalar @novector;
print  {$gp} <<'GAPS_2';
Blocked on one piece of data, and it is the piece that does not require any
tool: a hash and the plaintext that produces it. Nothing here can reach tier
`vector` without one, so these rows cannot be proven by anyone, however well
equipped. If you have a vector for one of these - from a tool's own test
suite, from your own scratch implementation, from a wordlist you cracked -
that is the whole contribution.

GAPS_2
printf {$gp} "* %s - %s\n", gaps_link($_), $_->{name} for @novector;

print {$gp} "\n## 3. A tool column nobody has filled\n\n";
print {$gp} <<'GAPS_3';
Real work rather than a one-liner: it means finding out whether the tool
supports the construction at all, and under which identifier. The counts are
the honest size of the job.

GAPS_3
for my $t (qw(john hashcat mdxfind)) {
    my @g = @{ $unknown_by_tool{$t} || [] } or next;
    printf {$gp} "### %s: %d entries say nothing\n\n", $t, scalar @g;
    # A sample, not the list: 538 bullet points is a wall, and the full set is
    # one filter away in a file built for exactly that. Which few matters
    # though -- alphabetical put 7ZIP and the FDE formats first, which are the
    # HARDEST rows in the set. Preferring entries that carry a proven
    # expression puts a concrete construction in front of the reader, which is
    # the case where a dynamic or a mode plausibly already exists.
    my @show = grep { $_->{vecs} && length $_->{expr}
                      && $_->{expr_tier} eq 'vector' } @g;
    my $shown_kind = 'a vector and a proven expression, so there is a definite '
                   . 'construction to look for';
    unless (@show) {
        @show = grep { $_->{vecs} } @g;
        $shown_kind = 'a vector, so a candidate identifier can be tested at once';
    }
    @show = @g unless @show;

    # One per family, not the first fifteen. Alphabetically the HAVAL entries
    # alone fill the sample, and fifteen rows of the same shape read as one
    # job repeated rather than as a choice of jobs. Grouping on the outermost
    # function of the expression puts a different piece of work on each line.
    my (%fam, @order);
    for my $r (@show) {
        # Alphabetic prefix only: haval128_3 and haval160_5 are the same job
        # twice, and keeping the digits made the sample fifteen HAVALs.
        my ($head) = ($r->{expr} || $r->{name}) =~ /^([A-Za-z]+)/;
        $head //= $r->{id};
        push @order, $head unless $fam{$head};
        push @{ $fam{$head} }, $r;
    }
    printf {$gp} "A few that carry %s, one per family:\n\n", $shown_kind;
    for my $head (@order[0 .. ($#order < 14 ? $#order : 14)]) {
        my @f = @{ $fam{$head} };
        printf {$gp} "* %s - `%s`%s\n", gaps_link($f[0]),
            ($f[0]{expr} || $f[0]{name}),
            (@f > 1 ? sprintf(' (and %d more starting `%s`)', scalar(@f) - 1, $head) : '');
    }
    printf {$gp} "\nAll %d: filter `%s_state` for `unknown` in "
                . "[rosetta.csv](../dist/rosetta.csv).\n\n", scalar @g, $t;

    # John is a special case worth stating once, because the column overstates
    # the problem: an entry with a proven expression can be attacked today
    # with john's dynamic compiler. What is missing is a NAMED format, which
    # is the only thing that belongs in the column.
    print {$gp} <<'GAPS_JOHN' if $t eq 'john';
Where such an entry carries an expression, john can already attack it without
a named format:

```sh
john --format=dynamic='haval128_3(md5($p))' hashes
```

That string is in the entry's `john_dynamic_expr:` field and in the CSV column
of the same name. Take it from there rather than from the `expression` column:
the expression is written in hx notation, which spells a change of
representation as a wrapper - `md5(upper(md5($p)))` - where john spells it as a
flavour of the hash function - `md5(MD5($p))` - and john rejects the first
outright. It is deliberately **not** in john's column, which lists formats
`--list=formats` will show; the gap worth filling is whether a named one exists.

GAPS_JOHN
}

printf {$gp} "## 4. hashcat modes with no row here (%d)\n\n", scalar @orphan_modes;
print  {$gp} <<'GAPS_4';
Whole algorithms rather than gaps in a row. Many are full-disk-encryption and
wallet formats whose place in this table is still an open question; others are
simply not written yet. hashcat publishes an example hash for each, so an
entry can usually be created and proven in one sitting.

GAPS_4
printf {$gp} "* `%d` - %s\n", $_->{mode}, ($_->{name} // '?')
    for @orphan_modes[0 .. ($#orphan_modes < 24 ? $#orphan_modes : 24)];
printf {$gp} "\nAll %d are listed by `tools/validate.pl -v`.\n", scalar @orphan_modes;
close $gp;

#-----------------------------------------------------------------------
# docs/OPEN-QUESTIONS.md - the ambiguity, published.
#
# GAPS.md is about what nobody has said. This is about what we have said and
# are not sure of, which is a different ask and a different reader: settling
# one of these usually needs someone who has cracked the format in anger, not
# someone with a spare afternoon.
#
# It exists because the reasoning behind every ambiguous row used to live in
# an untracked handoff file. A repository that publishes its gaps and hides
# its doubts is asking to be trusted rather than checked, which is exactly the
# failure mode the tier system was built against -- and if the answers have to
# come from other people, the questions have to be somewhere other people can
# read them.
#
# Everything here is derived from the entries themselves, so an answered
# question leaves this page by being answered in the data. The prose names the
# handful of cases whose explanation is narrative rather than a field.

my @expr_unproven = grep { $_->{expr} && $_->{expr_tier} ne 'vector'
                                      && $_->{expr_tier} ne 'absent' } @out;
my @novec_q       = grep { !$_->{vecs} } @out;
my @traps;
for my $r (@out) {
    push @traps, { row => $r, rel => $_ }
        for grep { $_->{kind} eq 'collides-on-subset' } @{ $r->{relations} };
}
# A tool block that names identifiers at a tier below vector is a belief, and
# GAPS.md already asks for it to be settled. Here it is only counted, with the
# pointer, so the two pages do not print the same table twice.
my $believed = grep { my $r = $_; grep { $r->{$_}{state} eq 'claimed' }
                                 qw(hashcat john mdxfind) } @out;

open my $oq, '>', "$docsdir/OPEN-QUESTIONS.md" or die "cannot write OPEN-QUESTIONS.md: $!\n";
printf {$oq} "# Open questions\n\n";
printf {$oq} "GENERATED by `tools/%s` on %s - do not edit; regenerate.\n\n", $PROG, $today;
print  {$oq} <<'OQ_HEAD';
Things this repository has looked at and cannot settle on its own. They are
not gaps - see [GAPS.md](GAPS.md) for what nobody has said yet - they are rows
where something is known to be odd and the answer needs a person who has
worked the format.

If you can settle one, an issue saying so is a complete contribution. You do
not need to open a pull request, and you do not need to be certain: "I have
seen this format do X" is information this cannot derive.

OQ_HEAD

printf {$oq} "## Expressions that do not reproduce their own vectors (%d)\n\n",
    scalar @expr_unproven;
print  {$oq} <<'OQ_EXPR';
Each of these carries an expression transcribed from somewhere that states it
- john's own `--list=subformats` for a format the entry has already proven, or
the hx specification's Appendix A for an mdxfind type - and yet compiling that
string with `--format=dynamic='...'` does not recover the entry's plaintext
from the entry's hash. Four things could be true and we cannot tell which from
here: the string is a wrong transcription, the vector belongs to a different
algorithm, john's dynamic compiler and its named format disagree about what
the string means, or john's expression language simply has no way to write
this construction - it has no `cut()`, `rev()` or `cap()`, and its base64
flavour encodes the raw digest rather than the hex string.

The last of those is the common case rather than a corner: the expression is
rewritten into john's own notation before it is tried - `upper(md5($p))`
becomes `MD5($p)`, `pad($p,100)` becomes `pad100($p)` - so a row that is still
here after that is one john was asked correctly and could not confirm.

The tier stays `upstream` rather than being promoted or deleted, which is the
honest state: john says it, we could not reproduce it.

`tools/triage-expressions.pl` has been over all of these, using john's own
test vectors for the format as a control and an independent Digest::
implementation as a second opinion, so the note on each says what is actually
wrong rather than that something is. Most are john-side and nothing a
contributor here can fix; the ones worth an outside answer are the rows whose
own vector turns out not to be the construction, because somebody has to say
what those vectors really are.

| Entry | Expression | Proven john format | Note |
|---|---|---|---|
OQ_EXPR
for my $r (sort { $a->{id} cmp $b->{id} } @expr_unproven) {
    # The john identifiers are the point: john states this expression FOR one
    # of them, and that identifier does crack the vector. Whatever is wrong
    # sits between the two, so a reader needs both in front of them. The note
    # column carries only what is not the standard transcription boilerplate.
    # triage-expressions.pl appends "TRIAGE <date>: <diagnosis>" after the
    # provenance the note already carried. The diagnosis is the useful half
    # here, so show that when it exists and drop the boilerplate.
    (my $note = $r->{expr_note}) =~ s/\s+/ /g;
    $note = $1 if $note =~ /TRIAGE \d{4}-\d{2}-\d{2}(?: \[[a-z-]+\])?: (.+)$/;
    $note = '' if $note =~ /^transcribed from john/;
    $note = substr($note, 0, 200) . '...' if length $note > 203;
    printf {$oq} "| %s | `%s` | `%s` | %s |\n", gaps_link($r), $r->{expr},
        (join('`, `', @{ $r->{john}{ids} }) || '-'), $note;
}

printf {$oq} "\n## Cracked, but not by that name (%d)\n\n", scalar @traps;
print  {$oq} <<'OQ_TRAP';
A tool recovers the plaintext from one of these vectors without implementing
the algorithm the row is about, so the identifier is deliberately **not**
recorded in that tool's column. The classic is `md5cap`: john's `dynamic_2`
cracks its vector because `cap()` is a no-op on a digest that is already
lowercase, which says nothing about whether john can do `cap(md5($p))` in
general.

These are recorded so the same true-looking mapping is not re-reported every
year. If you can show the tool really does implement the construction - on an
input where the two differ - that is exactly the contribution that would
promote it.

| Entry | Collides with | Why |
|---|---|---|
OQ_TRAP
for my $t (sort { $a->{row}{id} cmp $b->{row}{id} } @traps) {
    (my $note = $t->{rel}{note}) =~ s/\s+/ /g;
    $note = substr($note, 0, 150) . '...' if length $note > 153;
    printf {$oq} "| %s | `%s` | %s |\n", gaps_link($t->{row}), $t->{rel}{entry},
        (length $note ? $note : '-');
}

printf {$oq} "\n## Entries nothing can prove yet (%d)\n\n", scalar @novec_q;
print  {$oq} <<'OQ_NOVEC';
No test vector, so no tier above `asserted` is reachable for any tool, however
well equipped. Several are types whose publisher's own example does not
reproduce under that type, which is itself a question worth an answer. Any
hash-and-plaintext pair settles one.

OQ_NOVEC
for my $r (sort { $a->{id} cmp $b->{id} } @novec_q) {
    (my $note = $r->{notes}) =~ s/\s+/ /g;
    $note = substr($note, 0, 150) . '...' if length $note > 153;
    printf {$oq} "* %s - %s%s\n", gaps_link($r), $r->{name},
        (length $note ? " - $note" : '');
}

print {$oq} <<"OQ_MIXED";

## Rows that may be more than one algorithm

Not derivable from a field, so stated here. Three entries carry vectors that
fall to different constructions: `md5-md5-plain-salt` has five vectors
answering to three different john dynamics, `md5-md5-plain-salt-2` has two,
and `md5userpass` has two. Both `md5-md5-plain-salt*` entries also carry an
`aliases:` list naming several algorithms, so the spreadsheet collated them
deliberately and splitting them is a judgement about what the row is *for* -
one construction, or one thing people search for. Whoever put them together
knew something; if that was you, say so.

## Mappings believed but never reproduced ($believed)

Counted here, listed in [GAPS.md](GAPS.md#1-believed-but-never-reproduced),
because filling one is mechanical rather than a judgement call: the identifier
and the vector are both already recorded, and one command decides it.

## What is deliberately not a question

* **Gaps.** An empty cell is not a doubt, it is an absence. [GAPS.md](GAPS.md).
* **`category:` on most entries.** Unfilled, and derivable from what the entry
  already proves; grinding through it by hand would be worse than leaving it.
* **Crack's coverage.** Frozen at its 1996 manual on purpose - [CRACK.md](CRACK.md).
OQ_MIXED
close $oq;

#-----------------------------------------------------------------------
# docs/CRACK.md - the historical note the column was a poor substitute for.
#
# The prose is fixed because Crack is: v5.0 shipped in 1996 and will not gain
# an algorithm. Only the list of matching entries is derived, so that marking
# another entry tools.crack.supported shows up here without anyone editing
# this file.

my @crackable = grep { $_->{crack}{state} ne 'no' && $_->{crack}{state} ne 'unknown' } @out;

open my $cm, '>', "$docsdir/CRACK.md" or die "cannot write CRACK.md: $!\n";
print {$cm} <<'CRACK_HEAD';
# Crack

Alec Muffett's `Crack` - the password cracker that predates every other tool
in this repository. Included for historical reference only. Nothing here is
verified against it: it is not installed on the machine that builds this data,
and its capability is taken from its own manual rather than from a round-trip.

The newest thing quoted below is the v5.0 manual of December 1996. Treat any
version or date claim beyond what is quoted as unchecked - I have not tried to
establish a release history.

## What it could actually attack

Crack implements no hash of its own. It calls the host's `crypt(3)`, and picks
which implementation to build against by looking for a directory - `libdes`,
`ufc_crypt` or GNU `crypt` - and falling back to the system library. So its
capability is really the capability of a 1996 Unix `crypt(3)`, which is three
things.

From the v5.0 manual (Alec Muffett, December 1996):

* **descrypt** - traditional DES `crypt(3)`. The default, and the one it ships
  ready for: *"For traditional crypt() users, I ship with libdes."* The bundled
  libdes is Eric Young's, of SSLeay fame.

* **md5crypt** - the FreeBSD/NetBSD MD5-based `crypt()`: *"if you're using a
  MD5-based version of crypt(), you must first do ... `cp elcid.c,bsd
  elcid.c`"* before building.

* **crypt16** - Ultrix, OSF and Digital Unix: *"edit src/util/elcid.c to use
  crypt16() (change #undef to #define)"*. No algorithm in this repository
  names crypt16, so it appears nowhere in the table.

## What it could not

The manual is unambiguous, under the heading *Weird Password Systems (Novell,
Kerberos Tickets, LAN-Manager, VMS)*:

> Crack v5.0 does not (as distributed) support cracking these sorts of
> systems, although I am aware that versions of Crack v4.1f were modified to
> support one or more of the above.

Worth knowing if you go reading the source: circulating trees include
`src/util/elcid.c,lanman` and `elcid.c,nt`, plus `scripts/lanman2spf` and
`nt2spf`. Those belong to Elias Levy's `crack-nt` fork, not to stock Crack,
and crediting Crack with LM or NTLM support on the strength of finding them is
a mistake this file exists to prevent.

## Why it is frozen rather than tracked

Because Crack delegates to `crypt(3)`, building it on a modern glibc would
inherit sha256crypt, sha512crypt and possibly bcrypt, and the answer would
then depend on which machine you asked. That is useless as a historical
record. This records what the shipped release could do on the systems it
shipped for.

## Algorithms here that Crack could attack

CRACK_HEAD

if (@crackable) {
    print {$cm} "| Algorithm | hashcat | mdxfind | How |\n|---|---|---|---|\n";
    for my $r (@crackable) {
        my $how = '';
        printf {$cm} "| %s | %s | %s | %s |\n", $r->{name},
            md_cell($r->{hashcat}), md_cell($r->{mdxfind}),
            ($r->{cracknote} // '');
    }
}
else {
    print {$cm} "None currently marked.\n";
}

print {$cm} <<'CRACK_TAIL';

Marked with (c) in [ROSETTA.md](ROSETTA.md). The underlying field is
`tools.crack.supported` in `data/algorithms/`, and it is carried in
`dist/rosetta.csv` and `dist/rosetta.json` for anyone consuming those.

## References

* Manual, source and licence as distributed with Crack v5.0a
* [Elias Levy's crack-nt fork](https://github.com/eliaslevy/crack-nt) - the NT
  and LAN-Manager additions described above
CRACK_TAIL
close $cm;

#-----------------------------------------------------------------------
# docs/index.html - the browsable equivalent of the old sheet.

my $compact = JSON::PP->new->canonical->encode([
    map { [ $_->{name}, $_->{id},
            $_->{hashcat}{state}, join(', ', @{ $_->{hashcat}{ids} }),
            $_->{john}{state},    join(', ', @{ $_->{john}{ids} }),
            $_->{mdxfind}{state}, join(', ', @{ $_->{mdxfind}{ids} }),
            $_->{crack}{state},
            $_->{alias}, $_->{legacy}, $_->{vecs}, $_->{sameas},
            # 13, 14: what the algorithm IS. Absent from this array until
            # 2026-08-30, which meant the page could not find a row from the
            # one thing a person holding a hash actually has -- a guess at the
            # construction. Searching "md5($p.$s)" returned nothing.
            $_->{expr}, $_->{denotation},
            # 15-22: the practitioner columns, in the same order as the CSV.
            # They are here rather than only in the CSV because the question
            # they answer -- is this worth attacking, and is this the shape of
            # hash I am holding -- is asked while browsing, not afterwards in
            # a spreadsheet. Each one names its tool: they are facts about a
            # MODE, and a merged `salted` would read as a claim about the
            # algorithm that no tool has made.
            $_->{hashcat_salted}, $_->{hashcat_speed}, $_->{john_salted},
            $_->{john_work_factor}, $_->{mdxfind_salted},
            $_->{nesting_depth}, $_->{hash_length}, $_->{hash_length_basis},
          ] } @out
]);

# The footer sentence about merged ids, built here so the heredoc below stays
# a template. Empty string when nothing has been merged, which is the common
# case and should leave the page exactly as it was.
my $merged_note = '';
if (@tomb_out) {
    my %name_of = map { $_->{id} => $_->{name} } @out;
    $merged_note = 'Merged ids, kept so old links resolve: '
        . join('; ', map { sprintf('<code>%s</code> &rarr; %s',
                                   $_->{id}, $name_of{ $_->{into} } // $_->{into}) }
                     @tomb_out)
        . '.';
}

# The redirect map the page needs at runtime: a visitor following an old link
# lands on #ripemd320, which is nobody's row any more. Without this the hash
# silently does nothing, which is the 404 the tombstone decision rejected.
my $tomb_json = JSON::PP->new->canonical->encode({
    map { $_->{id} => [ $_->{into}, $_->{name} ] } @tomb_out
});

my $versions = sprintf('hashcat %s &middot; john %s &middot; mdxfind %s',
    $inv{hashcat}{version} // '?', $inv{john}{version} // '?', $inv{mdxfind}{version} // '?');

open my $html, '>', "$docsdir/index.html" or die "cannot write html: $!\n";
print {$html} <<"HTML_HEAD";
<!doctype html>
<html lang="en"><head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>cracking-rosetta</title>
<style>
:root{
  --bg:#fbfbfa; --surface:#fff; --rule:#e2e2df; --ink:#1a1a18; --ink2:#5c5c56;
  --ink3:#8a8a82; --proven:#1c6b4a; --provenbg:#e2f0e8; --claim:#7a5a12;
  --claimbg:#f6ecd6; --gap:#9c3620; --gapbg:#fae3dd; --no:#8a8a82; --nobg:#efefec;
}
\@media (prefers-color-scheme:dark){:root{
  --bg:#141413; --surface:#1c1c1a; --rule:#2e2e2b; --ink:#eceae4; --ink2:#a8a69e;
  --ink3:#75736c; --proven:#6fc79b; --provenbg:#163024; --claim:#d8ab4e;
  --claimbg:#332a14; --gap:#e08268; --gapbg:#3a1f18; --no:#75736c; --nobg:#262624;
}}
*{box-sizing:border-box}
body{margin:0;background:var(--bg);color:var(--ink);
 font:14px/1.5 ui-sans-serif,system-ui,-apple-system,"Segoe UI",Helvetica,Arial,sans-serif}
header{padding:22px 20px 14px;border-bottom:1px solid var(--rule);background:var(--surface)}
h1{margin:0 0 4px;font-size:1.15rem;letter-spacing:-.01em}
h1 code{font:inherit;font-weight:700}
.sub{color:var(--ink2);font-size:.82rem;margin:0}
.ver{color:var(--ink3);font-size:.74rem;margin:6px 0 0;font-family:ui-monospace,monospace}
.controls{display:flex;flex-wrap:wrap;gap:8px;align-items:center;
 padding:12px 20px;border-bottom:1px solid var(--rule);background:var(--surface);
 position:sticky;top:0;z-index:5}
input[type=search]{flex:1 1 240px;min-width:180px;padding:7px 10px;font:inherit;
 border:1px solid var(--rule);border-radius:5px;background:var(--bg);color:var(--ink)}
select,button{padding:7px 9px;font:inherit;border:1px solid var(--rule);
 border-radius:5px;background:var(--bg);color:var(--ink);cursor:pointer}
button.on{background:var(--gapbg);border-color:var(--gap);color:var(--gap);font-weight:600}
.count{color:var(--ink2);font-size:.8rem;white-space:nowrap}
.wrap{overflow-x:auto}
table{border-collapse:collapse;width:100%;font-size:.85rem}
th,td{text-align:left;padding:7px 12px;border-bottom:1px solid var(--rule);
 vertical-align:top}
th{position:sticky;top:57px;background:var(--surface);z-index:4;cursor:pointer;
 font-size:.72rem;letter-spacing:.06em;text-transform:uppercase;color:var(--ink3);
 white-space:nowrap;user-select:none}
th:hover{color:var(--ink)}
td.alg{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:.82rem;
 max-width:32ch;word-break:break-word}
td.alg .al{display:block;color:var(--ink3);font-size:.74rem;
 font-family:ui-sans-serif,system-ui,sans-serif}
td.alg .ex{display:block;color:var(--ink2);font-size:.76rem;
 font-family:ui-monospace,SFMono-Regular,Menlo,monospace;word-break:break-all}
td.rel{color:var(--ink3);font-size:.74rem;max-width:30ch;word-break:break-word;
 font-family:ui-sans-serif,system-ui,sans-serif}
/* The practitioner cells. Two columns carrying eight facts, so the secondary
   line is deliberately quiet: the scan is for "slow" and for a length, and
   the work factor, the per-tool salt and the nesting depth are there for the
   row you have already stopped on. Every one of them also has a title, since
   "hc+ jo+ mx-" is only readable once somebody has told you what it means. */
td.cost,td.shape{font-size:.78rem;white-space:nowrap}
td.cost .sub,td.shape .sub{display:block;color:var(--ink3);font-size:.72rem;
 font-family:ui-monospace,SFMono-Regular,Menlo,monospace;white-space:normal}
.slow{color:var(--no);font-weight:600}
.fast{color:var(--ink2)}
.ids{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:.8rem}
.pill{display:inline-block;padding:1px 6px;border-radius:3px;font-size:.66rem;
 font-weight:700;letter-spacing:.04em;text-transform:uppercase;margin-left:6px;
 vertical-align:1px}
.proven .pill{background:var(--provenbg);color:var(--proven)}
.claimed .pill{background:var(--claimbg);color:var(--claim)}
.proven .ids{color:var(--ink)}
.claimed .ids{color:var(--ink2)}
td.no{color:var(--no);background:var(--nobg)}
td.unknown{background:var(--gapbg);color:var(--gap);font-weight:700;
 background-image:repeating-linear-gradient(135deg,transparent,transparent 5px,
 rgba(156,54,32,.09) 5px,rgba(156,54,32,.09) 10px)}
legend,.legend{display:flex;flex-wrap:wrap;gap:14px;padding:10px 20px;
 font-size:.76rem;color:var(--ink2);border-bottom:1px solid var(--rule);
 background:var(--surface)}
.legend b{font-weight:600;color:var(--ink)}
.sw{display:inline-block;width:10px;height:10px;border-radius:2px;margin-right:5px;
 vertical-align:-1px}
footer{padding:16px 20px;color:var(--ink3);font-size:.76rem}
/* The permalink is the whole point of a row having an id: it is what someone
   pastes into an issue. Kept faint until the row is hovered so 784 of them do
   not turn the first column into a field of hashes. */
.permalink{float:right;margin-left:10px;color:var(--ink3);text-decoration:none;
 opacity:0;transition:opacity .12s}
tr:hover .permalink,.permalink:focus{opacity:1}
tr.hit td{background:var(--claimbg);box-shadow:inset 3px 0 0 var(--claim)}
#note{display:none;padding:10px 20px;background:var(--claimbg);color:var(--ink);
 border-bottom:1px solid var(--rule);font-size:.82rem}
#note.on{display:block}
a{color:inherit}
</style>
</head><body>
<header>
  <h1><code>cracking-rosetta</code></h1>
  <p class="sub">Password-cracking algorithm identifiers across hashcat, John the Ripper and mdxfind.</p>
  <p class="ver">$versions &middot; generated $today</p>
</header>
<div class="controls">
  <input type="search" id="q" placeholder="Search name, expression, id, alias, mode, format, type&hellip;" autocomplete="off">
  <select id="tool">
    <option value="">any tool</option>
    <option value="0">hashcat</option>
    <option value="1">John</option>
    <option value="2">mdxfind</option>
  </select>
  <select id="state">
    <option value="">any state</option>
    <option value="proven">proven</option>
    <option value="claimed">claimed</option>
    <option value="no">not supported</option>
    <option value="unknown">gap</option>
  </select>
  <button id="gaps" type="button">Show gaps only</button>
  <span class="count" id="count"></span>
</div>
<div class="legend">
  <span><span class="sw" style="background:var(--provenbg);border:1px solid var(--proven)"></span><b>proven</b> &mdash; cracked here, round-trip</span>
  <span><span class="sw" style="background:var(--claimbg);border:1px solid var(--claim)"></span><b>claimed</b> &mdash; asserted, unverified</span>
  <span><span class="sw" style="background:var(--nobg);border:1px solid var(--no)"></span><b>not supported</b> &mdash; checked; it cannot</span>
  <span><span class="sw" style="background:var(--gapbg);border:1px solid var(--gap)"></span><b>gap</b> &mdash; nobody has said yet</span>
</div>
<div class="wrap">
<div id="note"></div>
<table>
<thead><tr>
  <th data-c="0">Algorithm</th><th data-c="3">hashcat</th>
  <th data-c="5">John</th><th data-c="7">mdxfind</th>
  <th data-c="16" title="hashcat's own slow/fast split, and what John says is tunable">Cost</th>
  <th data-c="21" title="length of the hash string, how well evidenced, which tools salt it, and how many hashes deep">Shape</th>
  <th data-c="11">Vectors</th>
  <th data-c="12">Same as</th>
</tr></thead>
<tbody id="tb"></tbody>
</table></div>
<footer>
  Generated by <code>tools/render.pl</code>. Also available as
  <a href="ROSETTA.md">ROSETTA.md</a> and
  <a href="../dist/rosetta.csv">rosetta.csv</a>.
  Every row has a permalink &mdash; the <code>#</code> that appears when you
  hover it. What is missing, and what fixing it costs, is in
  <a href="GAPS.md">GAPS.md</a>; what is known to be doubtful is in
  <a href="OPEN-QUESTIONS.md">OPEN-QUESTIONS.md</a>.
  A gap is not a claim that the tool cannot do it &mdash; it means nobody has said.
  &quot;Cost&quot; is hashcat's own fast/slow split with John's tunable cost
  under it; &quot;Shape&quot; is how long the hash string is, then which tools
  salt it (<code>hc</code> hashcat, <code>jo</code> John, <code>mx</code>
  mdxfind) and how many hashes deep the construction goes. A length followed
  by <code>?</code> rests on a single vector and <code>!</code> means the
  vectors on that row disagree. The salt marks are per tool and never merged,
  because an entry can name a hashcat mode that takes no salt and an mdxfind
  type that does.
  &quot;Same as&quot; names another row that is the same computation, and why both
  rows exist; the full typed edges are in <code>rosetta.json</code>.
  Alec Muffett's Crack is covered separately in <a href="CRACK.md">CRACK.md</a>.
  Built on the community spreadsheet this replaces &mdash; years of work by
  multiple <a href="https://hashmob.net/">HashMob</a> members &mdash; and on
  <a href="https://github.com/Cynosureprime">Cynosure Prime</a>'s verified
  mdxfind and hashpipe data.
  $merged_note
</footer>
<script>
const D = $compact;
const tb=document.getElementById('tb'), q=document.getElementById('q'),
      toolSel=document.getElementById('tool'), stSel=document.getElementById('state'),
      gapsBtn=document.getElementById('gaps'), countEl=document.getElementById('count');
let gapsOnly=false, sortCol=0, sortDir=1;
const COLS=[[2,3],[4,5],[6,7]];               // [stateIdx, idsIdx] per tool
const label={proven:'ok',claimed:'?',no:'no',unknown:'gap'};

function cellHtml(st,ids){
  if(st==='unknown') return '<td class="unknown">&mdash;</td>';
  if(st==='no')      return '<td class="no">not supported</td>';
  return '<td class="'+st+'"><span class="ids">'+esc(ids)+'</span>'+
         '<span class="pill">'+label[st]+'</span></td>';
}
function esc(s){return String(s).replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));}

// costHtml: is this worth attacking? hashcat publishes the fast/slow split
// itself, which is the distinction a practitioner plans around, and John's
// tunable_cost names what can be turned up -- "iteration count", "N,r,p",
// argon2's "t,m,p,type". Both are read out of the tool inventories, so
// neither can drift from the tool.
function costHtml(r){
  const speed=r[16]||'', wf=r[18]||'';
  if(!speed && !wf) return '<td class="cost">&mdash;</td>';
  return '<td class="cost">'
    +(speed?'<span class="'+esc(speed)+'" title="hashcat '
      +(speed==='slow'?'marks this mode slow':'marks this mode fast')+'">'
      +esc(speed)+'</span>':'&mdash;')
    +(wf?'<span class="sub" title="John tunable cost">'+esc(wf)+'</span>':'')
    +'</td>';
}

// shapeHtml: what am I holding? The length of the hash string, then -- quietly
// -- how well that length is evidenced, which tools salt it, and how many
// hashes deep the construction goes.
//
// The salt markers are per tool and never merged. An entry can name a hashcat
// mode that takes no salt and an mdxfind type that does, because the two tools
// cut the problem differently, and a single "salted" here would read as a
// claim about the algorithm that neither tool has made. bcrypt is the standing
// example: hashcat salts it, mdxfind's BCRYPT carries no salt flag because the
// salt travels inside the string.
const SALTMARK={yes:'+',no:'-',mixed:'~'};
function shapeHtml(r){
  const len=r[21]||'', basis=r[22]||'', depth=r[20]||'';
  const salt=[['hc',r[15]],['jo',r[17]],['mx',r[19]]]
             .filter(p=>p[1]).map(p=>p[0]+(SALTMARK[p[1]]||'?'));
  const sub=[];
  if(salt.length) sub.push(salt.join(' '));
  if(depth!=='') sub.push('depth '+depth);
  if(!len && !sub.length) return '<td class="shape">&mdash;</td>';
  return '<td class="shape">'
    +(len?'<span title="'+(basis==='fixed'?'every vector on this row is this long'
       :basis==='observed'?'one vector, so this is what was seen and no more'
       :basis==='varies'?'the vectors on this row disagree, and both lengths are real'
       :'')+'">'+esc(len)+(basis==='observed'?'?':basis==='varies'?'!':'')
      +'</span>':'&mdash;')
    +(sub.length?'<span class="sub" title="salt per tool (hc hashcat, jo John, '
      +'mx mdxfind); + salted, - not, ~ the identifiers on the row disagree">'
      +esc(sub.join('  '))+'</span>':'')
    +'</td>';
}

function render(){
  const term=q.value.trim().toLowerCase(), tool=toolSel.value, st=stSel.value;
  let rows=D.filter(r=>{
    if(term){
      // name, id, tool identifiers, aliases, legacy names, relations, and
      // the expression or denotation -- everything a person might arrive with.
      // r[16], r[18] and r[21] are in here so a search for "slow", for
      // "iteration count", or for the length of the string in hand lands on
      // the rows that have it -- "32" is how a lot of people would start.
      const hay=(r[0]+' '+r[1]+' '+r[3]+' '+r[5]+' '+r[7]+' '+r[9]+' '+r[10]
                +' '+r[12]+' '+(r[13]||'')+' '+(r[14]||'')
                +' '+(r[16]||'')+' '+(r[18]||'')+' '+(r[21]||'')).toLowerCase();
      if(hay.indexOf(term)<0) return false;
    }
    const idx = tool===''? null : COLS[+tool][0];
    if(st){
      if(idx!==null){ if(r[idx]!==st) return false; }
      else if(!COLS.some(c=>r[c[0]]===st)) return false;
    } else if(idx!==null && r[idx]==='unknown') return false;
    if(gapsOnly && !COLS.some(c=>r[c[0]]==='unknown')) return false;
    return true;
  });
  rows.sort((a,b)=>{
    const x=String(a[sortCol]).toLowerCase(), y=String(b[sortCol]).toLowerCase();
    // Sort numerically when both cells are plain numbers, so the length
    // column does not put 128 before 32. Everything else still sorts as text.
    // Two heredoc hazards in one line, both silent. This script is emitted
    // from an INTERPOLATING Perl heredoc, so a lone backslash is eaten --
    // hence [0-9] rather than \\d -- and a bare \$ is a Perl variable, so the
    // regex anchor has to be escaped or \$/ interpolates as the input record
    // separator and closes the regex with a newline. test-index-page.js
    // catches both by eval'ing what was actually written.
    if(/^[0-9]+\$/.test(x) && /^[0-9]+\$/.test(y)) return (+x - +y)*sortDir;
    // An empty cell sorts last in either direction: a row that says nothing is
    // not the smallest answer, it is the absence of one.
    if(!x !== !y) return x?-1:1;
    return x<y?-sortDir:x>y?sortDir:0;
  });
  tb.innerHTML=rows.map(r=>
    '<tr id="'+esc(r[1])+'">'
    +'<td class="alg"><a class="permalink" href="#'+esc(r[1])+'" '
    +'title="link to this row">#</a>'+esc(r[0])
    // The expression is the semantic key, so it is worth a line of its own --
    // but only when it says something the name has not already said, which
    // for 259 of these rows it has.
    +((r[13]&&r[13]!==r[0])?'<span class="ex">'+esc(r[13])+'</span>':
      (r[14]&&r[14]!==r[0])?'<span class="ex">'+esc(r[14])+'</span>':'')
    +(r[9]?'<span class="al">'+esc(r[9])+'</span>':'')+'</td>'
    +cellHtml(r[2],r[3])+cellHtml(r[4],r[5])+cellHtml(r[6],r[7])
    +costHtml(r)+shapeHtml(r)
    +'<td>'+(r[11]||0)+'</td>'
    +'<td class="rel">'+esc(r[12]||'')+'</td>'
    +'</tr>'
  ).join('');
  countEl.textContent=rows.length+' of '+D.length;
}

// Deep links. Every row carries its entry id, which is the same key
// dist/rosetta.csv joins on and the same stem as the YAML file, so one
// identifier gets you from a link in an issue to the row to the file to edit.
// M is the tombstone map: an id that lost a merge still resolves, to a note
// saying where it went and the survivor's row.
const M = $tomb_json;
function focusHash(){
  const want = decodeURIComponent(location.hash.slice(1));
  const note = document.getElementById('note');
  note.className=''; note.textContent='';
  if(!want) return;
  const t = M[want];
  const id = t ? t[0] : want;
  if(t){
    note.textContent = want + ' was merged into ' + t[0] + '. Showing that row instead.';
    note.className = 'on';
  }
  // Only reset the filters if the row is not on screen: a permalink clicked
  // from inside a filtered view should not silently throw the filter away.
  if(!document.getElementById(id)){
    q.value=''; toolSel.value=''; stSel.value='';
    gapsOnly=false; gapsBtn.classList.remove('on');
    render();
  }
  const el = document.getElementById(id);
  if(!el){
    note.textContent = 'No row here has the id "' + want + '".';
    note.className = 'on';
    return;
  }
  document.querySelectorAll('tr.hit').forEach(x=>x.classList.remove('hit'));
  el.classList.add('hit');
  el.scrollIntoView({block:'center'});
}
window.addEventListener('hashchange', focusHash);
q.oninput=render; toolSel.onchange=render; stSel.onchange=render;
gapsBtn.onclick=()=>{gapsOnly=!gapsOnly;gapsBtn.classList.toggle('on',gapsOnly);render();};
document.querySelectorAll('th').forEach(th=>th.onclick=()=>{
  const c=+th.dataset.c; sortDir = (c===sortCol)? -sortDir : 1; sortCol=c; render();
});
render();
focusHash();
</script>
</body></html>
HTML_HEAD
close $html;

#-----------------------------------------------------------------------
# README counter. Left alone if the markers are absent, so this never becomes
# a reason a render fails.

my $readme = "$ROOT/README.md";
if (-w $readme) {
    open my $rf, '<', $readme or die "cannot read README: $!\n";
    my $txt = do { local $/; <$rf> };
    close $rf;
    my $n = scalar @out;
    if ($txt =~ s/(<!-- counter -->)\s*\d+\s*(<!-- endcounter -->)/$1 $n $2/) {
        open my $wf, '>', $readme or die "cannot write README: $!\n";
        print {$wf} $txt;
        close $wf;
    }
}

#-----------------------------------------------------------------------
# Report.

printf STDERR "- rendered %d algorithms\n", scalar @out;
printf STDERR "-   %s\n", "$docsdir/index.html";
printf STDERR "-   %s\n", "$docsdir/ROSETTA.md";
printf STDERR "-   %s (promotable %d, no vector %d)\n", "$docsdir/GAPS.md",
    scalar @promotable, scalar @novector;
printf STDERR "-   %s (expressions %d, traps %d, no vector %d)\n",
    "$docsdir/OPEN-QUESTIONS.md",
    scalar @expr_unproven, scalar @traps, scalar @novec_q;
printf STDERR "-   %s, %s\n", "$distdir/rosetta.csv", "$distdir/rosetta.json";
for my $t (qw(hashcat john mdxfind)) {
    printf STDERR "-   %-8s proven %3d, claimed %3d, not-supported %3d, GAP %3d\n",
        $t, map { $state_count{$t}{$_} // 0 } qw(proven claimed no unknown);
}

# The practitioner columns, counted. These are cheap to add and easy to stop
# noticing, so the render says how much of each one is actually populated --
# a column that has quietly gone empty looks exactly like a column nobody
# needed, and the difference matters.
{
    my %c;
    for my $r (@out) {
        $c{$_}{ length($r->{$_}) ? $r->{$_} : '(empty)' }++
            for qw(hashcat_salted hashcat_speed john_salted mdxfind_salted
                   hash_length_basis);
        $c{john_work_factor}{ length($r->{john_work_factor}) ? 'named' : '(empty)' }++;
        $c{nesting_depth}{ length($r->{nesting_depth}) ? $r->{nesting_depth} : '(empty)' }++;
    }
    for my $col (qw(hashcat_salted hashcat_speed john_salted john_work_factor
                    mdxfind_salted nesting_depth hash_length_basis)) {
        printf STDERR "-   %-18s %s\n", $col,
            join('  ', map { "$_ $c{$col}{$_}" }
                       sort { ($a eq '(empty)') <=> ($b eq '(empty)') || $a cmp $b }
                       keys %{ $c{$col} });
    }
    # An identifier with no inventory record is why a practitioner cell is
    # empty on a row that plainly names the tool. It is not an error -- 57 of
    # john's are dynamics this build has switched off in
    # dynamic_disabled.conf -- but it is the reason, and it should be visible.
    printf STDERR "-   %-18s hashcat %d, john %d, mdxfind %d\n",
        'unresolved ids', map { $unresolved{$_} // 0 } qw(hashcat john mdxfind);
}
exit 0;
