#!/usr/bin/perl
#-----------------------------------------------------------------------
#
# Name: render.pl
# Description: build the human-browsable views and the machine exports
# Category: cracking-rosetta renderer
#
# Project: cracking-rosetta | Phase: 6 - publish
#
#-----------------------------------------------------------------------
# METHODOLOGY AND WHY THESE CHOICES
#
# ONE FILE PER ALGORITHM IS RIGHT FOR GIT AND WRONG FOR READING
#
# Splitting the data into 784 files bought reviewable diffs, per-algorithm
# blame and path-based CODEOWNERS. It cost the thing the spreadsheet was
# actually good at: opening one page and scanning. This puts that back,
# generated, so nobody has to maintain a table by hand again.
#
# FOUR CELL STATES, NOT TWO
#
# The whole point of the tier column is that "no" and "nobody has looked" are
# different answers, and the old sheet could not tell them apart - a blank cell
# meant either. So a tool cell renders as one of:
#
#   proven    identifiers, verified here by round-trip        (tier vector)
#   claimed   identifiers, asserted or upstream-verified
#   no        the tool genuinely cannot do this               (tier absent)
#   unknown   nobody has said                                 (no block at all)
#
# "unknown" is the gap, and it is deliberately the loudest thing on the page,
# because a gap someone can see is a gap someone might fill.
#
# THE README COUNTER IS UPDATED HERE
#
# README.md carries the algorithm count between <!-- counter --> markers, the
# same trick kens-salty-rainbow uses. Updating it here means the number is a
# by-product of rendering rather than something a person has to remember, and
# it cannot drift from the data the way a hand-typed figure does.
#
# THE HTML CARRIES ITS OWN DATA
#
# The page embeds the rows as JSON and filters client-side. No build step, no
# fetch, no CDN - it works from a file:// URL, from GitHub Pages, and from a
# checkout on a machine with no network. That matters for a reference you might
# want open on a cracking box that is not on the internet.
#
#-----------------------------------------------------------------------
# Generated by Claude Opus 5 on 2026-08-29

use strict;
use warnings;

use File::Basename qw(basename);
use File::Path qw(make_path);
use FindBin qw($RealBin);
use Getopt::Long qw(GetOptions);
use JSON::PP ();
use POSIX qw(strftime);
use YAML::XS ();

my $PROG = basename($0);
my $ROOT = "$RealBin/..";

sub usage {
    print STDERR <<"END_USAGE";

Usage: $PROG [options]

   --algorithms DIR  curated entries (default: data/algorithms)
   --tools DIR       generated inventories (default: data/tools)
   --docs DIR        where ROSETTA.md and index.html go (default: docs)
   --dist DIR        where the csv and json go (default: dist)
   -v, --verbose     counts on stderr
   -h, --help        this help

   Builds docs/index.html (browsable, filterable), docs/ROSETTA.md (flat
   table for GitHub), dist/rosetta.csv and dist/rosetta.json.

   Exit 0 success, 1 error, 2 usage.

END_USAGE
    return;
}

my ($algdir, $tooldir, $docsdir, $distdir, $help);
my $verbose = 0;
GetOptions(
    'algorithms=s' => \$algdir, 'tools=s' => \$tooldir,
    'docs=s' => \$docsdir, 'dist=s' => \$distdir,
    'v|verbose+' => \$verbose, 'h|help' => \$help,
) or do { usage(); exit 2 };
if ($help) { usage(); exit 0 }

$algdir  //= "$ROOT/data/algorithms";
$tooldir //= "$ROOT/data/tools";
$docsdir //= "$ROOT/docs";
$distdir //= "$ROOT/dist";
make_path($_) for grep { !-d } ($docsdir, $distdir);

# The stamp is the date of the last commit touching the data or this script -
# NOT the clock. Using the clock made the output differ between a local run
# and a CI run in another timezone, so the workflow rewrote three files with a
# date-only change every time and fought with local renders. Dating it from
# the source means the same checkout renders identically anywhere, and the
# stamp answers the more useful question: how current is the data?
my $today = `git -C \Q$ROOT\E log -1 --format=%cs -- data tools/render.pl 2>/dev/null`;
chomp $today;
$today = strftime('%Y-%m-%d', localtime) unless $today =~ /^\d{4}-\d{2}-\d{2}$/;

#-----------------------------------------------------------------------
# Load.

my %inv;
for my $t (qw(hashcat john mdxfind)) {
    my $f = "$tooldir/$t.yaml";
    $inv{$t} = -r $f ? YAML::XS::LoadFile($f) : {};
}

opendir(my $dh, $algdir) or do { print STDERR "$PROG: cannot read $algdir: $!\n"; exit 1 };
my @files = sort grep { /\.yaml$/ } readdir $dh;
closedir $dh;

my @rows;
for my $f (@files) {
    my $e = eval { YAML::XS::LoadFile("$algdir/$f") } or next;
    next unless $e->{id};
    push @rows, $e;
}
@rows = sort { lc($a->{name} // $a->{id}) cmp lc($b->{name} // $b->{id}) } @rows;

#-----------------------------------------------------------------------
# Reduce one tool block to a cell: state plus the identifiers to show.

sub cell {
    my ($e, $tool) = @_;
    my $b = $e->{tools}{$tool};
    return { state => 'unknown', ids => [] } unless $b;

    my @ids = $tool eq 'hashcat' ? @{ $b->{modes} || [] }
            : $tool eq 'mdxfind' ? @{ $b->{types} || [] }
            : $tool eq 'john'    ? (@{ $b->{cpu} || [] }, @{ $b->{gpu} || [] })
            :                      ();

    my $tier = $b->{verified} // 'asserted';

    if ($tool eq 'crack') {
        return { state => (defined $b->{supported} && $b->{supported} ? 'claimed' : 'no'),
                 ids => [] };
    }
    return { state => 'no', ids => [] } if !@ids && $tier eq 'absent';
    return { state => 'unknown', ids => [] } unless @ids;

    my $label = $tool eq 'mdxfind' && $b->{iterations} && $b->{iterations} > 1
              ? [ map { "$_ -i$b->{iterations}" } @ids ]
              : [@ids];
    return { state => ($tier eq 'vector' ? 'proven' : 'claimed'),
             ids => $label, tier => $tier };
}

# same_as($entry) - the relations as one phrase a person can read in a table
# cell. A row that says "md5($p.$s)" twice in a 784-row table is a puzzle; a
# row that says "same as md5-pass-salt (application)" is an answer.
sub same_as {
    my ($e) = @_;
    my @r = @{ $e->{relations} || [] } or return '';
    my %verb = (
        'same-computation'   => 'same as',
        'encodes'            => 'encoding of',
        'input-encoding'     => 'input encoding of',
        'iterates'           => 'iterates',
        'truncates'          => 'truncates',
        'collides-on-subset' => 'collides with',
        'duplicate-of'       => 'duplicate of',
    );
    my @parts;
    for my $rel (sort { ($a->{kind} // '') cmp ($b->{kind} // '')
                     || ($a->{entry} // '') cmp ($b->{entry} // '') } @r) {
        my $v = $verb{ $rel->{kind} // '' } // ($rel->{kind} // '?');
        my $d = $rel->{distinction};
        push @parts, sprintf('%s %s%s', $v, $rel->{entry},
            (defined $d && length $d && $d ne 'none') ? " ($d)" : '');
    }
    return join('; ', @parts);
}

my (%tally, %state_count);
my @out;
for my $e (@rows) {
    my %r = (
        id     => $e->{id},
        name   => $e->{name} // $e->{id},
        alias  => join('; ', @{ $e->{aliases} || [] }),
        expr   => $e->{expression} // '',
        status => $e->{status} // 'ok',
        vecs   => scalar @{ $e->{vectors} || [] },
        notes  => $e->{notes} // '',
        legacy => join('; ', grep { defined && length }
                        ($e->{legacy}{hashes_org}, $e->{legacy}{hashkiller})),
        category    => $e->{category} // '',
        application => join(' ', grep { defined && length }
                             ($e->{application}, $e->{application_version})),
        # Full edges for machines; one short phrase for people.
        relations   => [ map { { kind        => $_->{kind},
                                 entry       => $_->{entry},
                                 distinction => $_->{distinction} // '',
                                 note        => $_->{note} // '' } }
                         @{ $e->{relations} || [] } ],
        sameas      => same_as($e),
    );
    for my $t (qw(hashcat john mdxfind crack)) {
        my $c = cell($e, $t);
        $r{$t} = $c;
        $r{cracknote} = $e->{tools}{crack}{note} // '' if $t eq 'crack';
        $state_count{$t}{ $c->{state} }++;
    }
    $tally{ $r{status} }++;
    push @out, \%r;
}

#-----------------------------------------------------------------------
# dist/rosetta.csv - the closest thing to "open it in a spreadsheet".

sub csv_field {
    my ($v) = @_;
    $v //= '';
    return $v unless $v =~ /[",\n]/;
    $v =~ s/"/""/g;
    return qq{"$v"};
}

my @CSV = qw(id name aliases expression category application status
             hashcat hashcat_state john john_state mdxfind mdxfind_state
             crack_state vectors relations legacy notes);

open my $csv, '>', "$distdir/rosetta.csv" or die "cannot write csv: $!\n";
print {$csv} join(',', @CSV), "\n";
for my $r (@out) {
    print {$csv} join(',', map { csv_field($_) } (
        $r->{id}, $r->{name}, $r->{alias}, $r->{expr},
        $r->{category}, $r->{application}, $r->{status},
        join(' ', @{ $r->{hashcat}{ids} }), $r->{hashcat}{state},
        join(' ', @{ $r->{john}{ids} }),    $r->{john}{state},
        join(' ', @{ $r->{mdxfind}{ids} }), $r->{mdxfind}{state},
        $r->{crack}{state}, $r->{vecs}, $r->{sameas}, $r->{legacy}, $r->{notes},
    )), "\n";
}
close $csv;

#-----------------------------------------------------------------------
# dist/rosetta.json

my $json = JSON::PP->new->canonical->pretty;
open my $jf, '>', "$distdir/rosetta.json" or die "cannot write json: $!\n";
print {$jf} $json->encode({
    generated => $today,
    tools     => { map { $_ => ($inv{$_}{version} // 'unknown') } qw(hashcat john mdxfind) },
    count     => scalar @out,
    entries   => \@out,
});
close $jf;

#-----------------------------------------------------------------------
# docs/ROSETTA.md - flat table, readable straight on GitHub.

# wrap_name($name) - give a long expression name somewhere to break.
#
# 12 of 784 names are single unbreakable runs over 45 characters, and because
# a table is as wide as its widest cell, those 12 rows were forcing horizontal
# scrolling on GitHub for the whole thing. Composed expressions concatenate at
# the top level - md5(A).md5(A).md5(A) - so a break at the shallowest '.'
# splits them into readable chunks.
sub wrap_name {
    my ($n) = @_;
    my $longest = 0;
    for my $tok (split /\s+/, $n) {
        $longest = length($tok) if length($tok) > $longest;
    }
    return $n if $longest <= 44;

    my @ch = split //, $n;

    # The break depth is wherever the SHALLOWEST '.' sits, not necessarily
    # zero: md5(A.B.C) wraps the whole composition in an outer call, putting
    # its separators at depth one. Dots deeper than that are inside a single
    # operand and are left alone.
    my ($depth, $min) = (0, undef);
    for my $c (@ch) {
        $depth++ if $c eq '(';
        $depth-- if $c eq ')';
        $min = $depth if $c eq '.' && (!defined $min || $depth < $min);
    }
    return $n unless defined $min;

    my $out = '';
    $depth = 0;
    for my $c (@ch) {
        $depth++ if $c eq '(';
        $depth-- if $c eq ')';
        $out .= $c;
        $out .= '<br>' if $c eq '.' && $depth == $min;
    }
    return $out;
}

# md_cell($cell) - one table cell.
#
# Identifiers are stacked with <br> rather than joined with ", ". A cell
# reading "`dynamic_1`, `dynamic_1016`, `dynamic_2001`" is 43 characters wide
# and forces the whole table past GitHub's content column, which then scrolls
# horizontally. Stacked, the same cell is as wide as its longest single
# identifier. Nothing is lost and the column gets roughly three times narrower.
sub md_cell {
    my ($c) = @_;
    return '**—**' if $c->{state} eq 'unknown';
    return '·'     if $c->{state} eq 'no';
    # Crack carries a state but never identifiers; saying "yes" for anything
    # that merely is not 'no' would have claimed Crack supports every entry.
    return 'yes'   unless @{ $c->{ids} };
    my $t = join('<br>', map { "`$_`" } @{ $c->{ids} });
    return $c->{state} eq 'proven' ? "$t ✓" : $t;
}

open my $md, '>', "$docsdir/ROSETTA.md" or die "cannot write md: $!\n";
printf {$md} "# Rosetta table\n\n";
printf {$md} "GENERATED by `tools/%s` on %s - do not edit; regenerate.\n\n", $PROG, $today;
printf {$md} "%d algorithms. hashcat %s, john %s, mdxfind %s.\n\n",
    scalar @out, $inv{hashcat}{version} // '?', $inv{john}{version} // '?',
    $inv{mdxfind}{version} // '?';
print  {$md} <<'LEGEND';
`x` ✓ verified here by round-trip · `x` claimed, not verified · `·` tool does
not support it · **—** nobody has said yet (a gap worth filling)

† also attackable by Alec Muffett's Crack - see [CRACK.md](CRACK.md).

For sorting, filtering and search, open [index.html](index.html) - or
[dist/rosetta.csv](../dist/rosetta.csv) in a spreadsheet.

LEGEND
# Crack gets a dagger, not a column. It attacks 2 of these algorithms, so a
# column spent 782 rows saying "no" to buy two rows of information. The data
# itself is unchanged in data/algorithms, the CSV and the JSON; only the
# presentation moves, to docs/CRACK.md and a marker on the rows it concerns.
print  {$md} "| Algorithm | hashcat | John | mdxfind | Same as |\n|---|---|---|---|---|\n";
for my $r (@out) {
    my $n = wrap_name($r->{name}); $n =~ s/\|/\\|/g;
    $n .= ' †' if $r->{crack}{state} ne 'no' && $r->{crack}{state} ne 'unknown';
    my $rel = $r->{sameas}; $rel =~ s/\|/\\|/g;
    printf {$md} "| %s | %s | %s | %s | %s |\n", $n,
        md_cell($r->{hashcat}), md_cell($r->{john}), md_cell($r->{mdxfind}),
        (length $rel ? $rel : '');
}
close $md;

#-----------------------------------------------------------------------
# docs/CRACK.md - the historical note the column was a poor substitute for.
#
# The prose is fixed because Crack is: v5.0 shipped in 1996 and will not gain
# an algorithm. Only the list of matching entries is derived, so that marking
# another entry tools.crack.supported shows up here without anyone editing
# this file.

my @crackable = grep { $_->{crack}{state} ne 'no' && $_->{crack}{state} ne 'unknown' } @out;

open my $cm, '>', "$docsdir/CRACK.md" or die "cannot write CRACK.md: $!\n";
print {$cm} <<'CRACK_HEAD';
# Crack

Alec Muffett's `Crack` - the password cracker that predates every other tool
in this repository. Included for historical reference only. Nothing here is
verified against it: it is not installed on the machine that builds this data,
and its capability is taken from its own manual rather than from a round-trip.

The newest thing quoted below is the v5.0 manual of December 1996. Treat any
version or date claim beyond what is quoted as unchecked - I have not tried to
establish a release history.

## What it could actually attack

Crack implements no hash of its own. It calls the host's `crypt(3)`, and picks
which implementation to build against by looking for a directory - `libdes`,
`ufc_crypt` or GNU `crypt` - and falling back to the system library. So its
capability is really the capability of a 1996 Unix `crypt(3)`, which is three
things.

From the v5.0 manual (Alec Muffett, December 1996):

* **descrypt** - traditional DES `crypt(3)`. The default, and the one it ships
  ready for: *"For traditional crypt() users, I ship with libdes."* The bundled
  libdes is Eric Young's, of SSLeay fame.

* **md5crypt** - the FreeBSD/NetBSD MD5-based `crypt()`: *"if you're using a
  MD5-based version of crypt(), you must first do ... `cp elcid.c,bsd
  elcid.c`"* before building.

* **crypt16** - Ultrix, OSF and Digital Unix: *"edit src/util/elcid.c to use
  crypt16() (change #undef to #define)"*. No algorithm in this repository
  names crypt16, so it appears nowhere in the table.

## What it could not

The manual is unambiguous, under the heading *Weird Password Systems (Novell,
Kerberos Tickets, LAN-Manager, VMS)*:

> Crack v5.0 does not (as distributed) support cracking these sorts of
> systems, although I am aware that versions of Crack v4.1f were modified to
> support one or more of the above.

Worth knowing if you go reading the source: circulating trees include
`src/util/elcid.c,lanman` and `elcid.c,nt`, plus `scripts/lanman2spf` and
`nt2spf`. Those belong to Elias Levy's `crack-nt` fork, not to stock Crack,
and crediting Crack with LM or NTLM support on the strength of finding them is
a mistake this file exists to prevent.

## Why it is frozen rather than tracked

Because Crack delegates to `crypt(3)`, building it on a modern glibc would
inherit sha256crypt, sha512crypt and possibly bcrypt, and the answer would
then depend on which machine you asked. That is useless as a historical
record. This records what the shipped release could do on the systems it
shipped for.

## Algorithms here that Crack could attack

CRACK_HEAD

if (@crackable) {
    print {$cm} "| Algorithm | hashcat | mdxfind | How |\n|---|---|---|---|\n";
    for my $r (@crackable) {
        my $how = '';
        printf {$cm} "| %s | %s | %s | %s |\n", $r->{name},
            md_cell($r->{hashcat}), md_cell($r->{mdxfind}),
            ($r->{cracknote} // '');
    }
}
else {
    print {$cm} "None currently marked.\n";
}

print {$cm} <<'CRACK_TAIL';

Marked with † in [ROSETTA.md](ROSETTA.md). The underlying field is
`tools.crack.supported` in `data/algorithms/`, and it is carried in
`dist/rosetta.csv` and `dist/rosetta.json` for anyone consuming those.

## References

* Manual, source and licence as distributed with Crack v5.0a
* [Elias Levy's crack-nt fork](https://github.com/eliaslevy/crack-nt) - the NT
  and LAN-Manager additions described above
CRACK_TAIL
close $cm;

#-----------------------------------------------------------------------
# docs/index.html - the browsable equivalent of the old sheet.

my $compact = JSON::PP->new->canonical->encode([
    map { [ $_->{name}, $_->{id},
            $_->{hashcat}{state}, join(', ', @{ $_->{hashcat}{ids} }),
            $_->{john}{state},    join(', ', @{ $_->{john}{ids} }),
            $_->{mdxfind}{state}, join(', ', @{ $_->{mdxfind}{ids} }),
            $_->{crack}{state},
            $_->{alias}, $_->{legacy}, $_->{vecs}, $_->{sameas} ] } @out
]);

my $versions = sprintf('hashcat %s &middot; john %s &middot; mdxfind %s',
    $inv{hashcat}{version} // '?', $inv{john}{version} // '?', $inv{mdxfind}{version} // '?');

open my $html, '>', "$docsdir/index.html" or die "cannot write html: $!\n";
print {$html} <<"HTML_HEAD";
<!doctype html>
<html lang="en"><head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>cracking-rosetta</title>
<style>
:root{
  --bg:#fbfbfa; --surface:#fff; --rule:#e2e2df; --ink:#1a1a18; --ink2:#5c5c56;
  --ink3:#8a8a82; --proven:#1c6b4a; --provenbg:#e2f0e8; --claim:#7a5a12;
  --claimbg:#f6ecd6; --gap:#9c3620; --gapbg:#fae3dd; --no:#8a8a82; --nobg:#efefec;
}
\@media (prefers-color-scheme:dark){:root{
  --bg:#141413; --surface:#1c1c1a; --rule:#2e2e2b; --ink:#eceae4; --ink2:#a8a69e;
  --ink3:#75736c; --proven:#6fc79b; --provenbg:#163024; --claim:#d8ab4e;
  --claimbg:#332a14; --gap:#e08268; --gapbg:#3a1f18; --no:#75736c; --nobg:#262624;
}}
*{box-sizing:border-box}
body{margin:0;background:var(--bg);color:var(--ink);
 font:14px/1.5 ui-sans-serif,system-ui,-apple-system,"Segoe UI",Helvetica,Arial,sans-serif}
header{padding:22px 20px 14px;border-bottom:1px solid var(--rule);background:var(--surface)}
h1{margin:0 0 4px;font-size:1.15rem;letter-spacing:-.01em}
h1 code{font:inherit;font-weight:700}
.sub{color:var(--ink2);font-size:.82rem;margin:0}
.ver{color:var(--ink3);font-size:.74rem;margin:6px 0 0;font-family:ui-monospace,monospace}
.controls{display:flex;flex-wrap:wrap;gap:8px;align-items:center;
 padding:12px 20px;border-bottom:1px solid var(--rule);background:var(--surface);
 position:sticky;top:0;z-index:5}
input[type=search]{flex:1 1 240px;min-width:180px;padding:7px 10px;font:inherit;
 border:1px solid var(--rule);border-radius:5px;background:var(--bg);color:var(--ink)}
select,button{padding:7px 9px;font:inherit;border:1px solid var(--rule);
 border-radius:5px;background:var(--bg);color:var(--ink);cursor:pointer}
button.on{background:var(--gapbg);border-color:var(--gap);color:var(--gap);font-weight:600}
.count{color:var(--ink2);font-size:.8rem;white-space:nowrap}
.wrap{overflow-x:auto}
table{border-collapse:collapse;width:100%;font-size:.85rem}
th,td{text-align:left;padding:7px 12px;border-bottom:1px solid var(--rule);
 vertical-align:top}
th{position:sticky;top:57px;background:var(--surface);z-index:4;cursor:pointer;
 font-size:.72rem;letter-spacing:.06em;text-transform:uppercase;color:var(--ink3);
 white-space:nowrap;user-select:none}
th:hover{color:var(--ink)}
td.alg{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:.82rem;
 max-width:32ch;word-break:break-word}
td.alg .al{display:block;color:var(--ink3);font-size:.74rem;
 font-family:ui-sans-serif,system-ui,sans-serif}
td.rel{color:var(--ink3);font-size:.74rem;max-width:30ch;word-break:break-word;
 font-family:ui-sans-serif,system-ui,sans-serif}
.ids{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:.8rem}
.pill{display:inline-block;padding:1px 6px;border-radius:3px;font-size:.66rem;
 font-weight:700;letter-spacing:.04em;text-transform:uppercase;margin-left:6px;
 vertical-align:1px}
.proven .pill{background:var(--provenbg);color:var(--proven)}
.claimed .pill{background:var(--claimbg);color:var(--claim)}
.proven .ids{color:var(--ink)}
.claimed .ids{color:var(--ink2)}
td.no{color:var(--no);background:var(--nobg)}
td.unknown{background:var(--gapbg);color:var(--gap);font-weight:700;
 background-image:repeating-linear-gradient(135deg,transparent,transparent 5px,
 rgba(156,54,32,.09) 5px,rgba(156,54,32,.09) 10px)}
legend,.legend{display:flex;flex-wrap:wrap;gap:14px;padding:10px 20px;
 font-size:.76rem;color:var(--ink2);border-bottom:1px solid var(--rule);
 background:var(--surface)}
.legend b{font-weight:600;color:var(--ink)}
.sw{display:inline-block;width:10px;height:10px;border-radius:2px;margin-right:5px;
 vertical-align:-1px}
footer{padding:16px 20px;color:var(--ink3);font-size:.76rem}
a{color:inherit}
</style>
</head><body>
<header>
  <h1><code>cracking-rosetta</code></h1>
  <p class="sub">Password-cracking algorithm identifiers across hashcat, John the Ripper and mdxfind.</p>
  <p class="ver">$versions &middot; generated $today</p>
</header>
<div class="controls">
  <input type="search" id="q" placeholder="Search name, alias, mode, format, type&hellip;" autocomplete="off">
  <select id="tool">
    <option value="">any tool</option>
    <option value="0">hashcat</option>
    <option value="1">John</option>
    <option value="2">mdxfind</option>
  </select>
  <select id="state">
    <option value="">any state</option>
    <option value="proven">proven</option>
    <option value="claimed">claimed</option>
    <option value="no">not supported</option>
    <option value="unknown">gap</option>
  </select>
  <button id="gaps" type="button">Show gaps only</button>
  <span class="count" id="count"></span>
</div>
<div class="legend">
  <span><span class="sw" style="background:var(--provenbg);border:1px solid var(--proven)"></span><b>proven</b> &mdash; cracked here, round-trip</span>
  <span><span class="sw" style="background:var(--claimbg);border:1px solid var(--claim)"></span><b>claimed</b> &mdash; asserted, unverified</span>
  <span><span class="sw" style="background:var(--nobg);border:1px solid var(--no)"></span><b>not supported</b> &mdash; checked; it cannot</span>
  <span><span class="sw" style="background:var(--gapbg);border:1px solid var(--gap)"></span><b>gap</b> &mdash; nobody has said yet</span>
</div>
<div class="wrap"><table>
<thead><tr>
  <th data-c="0">Algorithm</th><th data-c="3">hashcat</th>
  <th data-c="5">John</th><th data-c="7">mdxfind</th><th data-c="11">Vectors</th>
  <th data-c="12">Same as</th>
</tr></thead>
<tbody id="tb"></tbody>
</table></div>
<footer>
  Generated by <code>tools/render.pl</code>. Also available as
  <a href="ROSETTA.md">ROSETTA.md</a> and
  <a href="../dist/rosetta.csv">rosetta.csv</a>.
  A gap is not a claim that the tool cannot do it &mdash; it means nobody has said.
  &quot;Same as&quot; names another row that is the same computation, and why both
  rows exist; the full typed edges are in <code>rosetta.json</code>.
  Alec Muffett's Crack is covered separately in <a href="CRACK.md">CRACK.md</a>.
</footer>
<script>
const D = $compact;
const tb=document.getElementById('tb'), q=document.getElementById('q'),
      toolSel=document.getElementById('tool'), stSel=document.getElementById('state'),
      gapsBtn=document.getElementById('gaps'), countEl=document.getElementById('count');
let gapsOnly=false, sortCol=0, sortDir=1;
const COLS=[[2,3],[4,5],[6,7]];               // [stateIdx, idsIdx] per tool
const label={proven:'ok',claimed:'?',no:'no',unknown:'gap'};

function cellHtml(st,ids){
  if(st==='unknown') return '<td class="unknown">&mdash;</td>';
  if(st==='no')      return '<td class="no">not supported</td>';
  return '<td class="'+st+'"><span class="ids">'+esc(ids)+'</span>'+
         '<span class="pill">'+label[st]+'</span></td>';
}
function esc(s){return String(s).replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));}

function render(){
  const term=q.value.trim().toLowerCase(), tool=toolSel.value, st=stSel.value;
  let rows=D.filter(r=>{
    if(term){
      const hay=(r[0]+' '+r[3]+' '+r[5]+' '+r[7]+' '+r[9]+' '+r[10]+' '+r[12]).toLowerCase();
      if(hay.indexOf(term)<0) return false;
    }
    const idx = tool===''? null : COLS[+tool][0];
    if(st){
      if(idx!==null){ if(r[idx]!==st) return false; }
      else if(!COLS.some(c=>r[c[0]]===st)) return false;
    } else if(idx!==null && r[idx]==='unknown') return false;
    if(gapsOnly && !COLS.some(c=>r[c[0]]==='unknown')) return false;
    return true;
  });
  rows.sort((a,b)=>{
    const x=String(a[sortCol]).toLowerCase(), y=String(b[sortCol]).toLowerCase();
    return x<y?-sortDir:x>y?sortDir:0;
  });
  tb.innerHTML=rows.map(r=>
    '<td class="alg">'+esc(r[0])+(r[9]?'<span class="al">'+esc(r[9])+'</span>':'')+'</td>'
    +cellHtml(r[2],r[3])+cellHtml(r[4],r[5])+cellHtml(r[6],r[7])
    +'<td>'+(r[11]||0)+'</td>'
    +'<td class="rel">'+esc(r[12]||'')+'</td>'
  ).map(s=>'<tr>'+s+'</tr>').join('');
  countEl.textContent=rows.length+' of '+D.length;
}
q.oninput=render; toolSel.onchange=render; stSel.onchange=render;
gapsBtn.onclick=()=>{gapsOnly=!gapsOnly;gapsBtn.classList.toggle('on',gapsOnly);render();};
document.querySelectorAll('th').forEach(th=>th.onclick=()=>{
  const c=+th.dataset.c; sortDir = (c===sortCol)? -sortDir : 1; sortCol=c; render();
});
render();
</script>
</body></html>
HTML_HEAD
close $html;

#-----------------------------------------------------------------------
# README counter. Left alone if the markers are absent, so this never becomes
# a reason a render fails.

my $readme = "$ROOT/README.md";
if (-w $readme) {
    open my $rf, '<', $readme or die "cannot read README: $!\n";
    my $txt = do { local $/; <$rf> };
    close $rf;
    my $n = scalar @out;
    if ($txt =~ s/(<!-- counter -->)\s*\d+\s*(<!-- endcounter -->)/$1 $n $2/) {
        open my $wf, '>', $readme or die "cannot write README: $!\n";
        print {$wf} $txt;
        close $wf;
    }
}

#-----------------------------------------------------------------------
# Report.

printf STDERR "- rendered %d algorithms\n", scalar @out;
printf STDERR "-   %s\n", "$docsdir/index.html";
printf STDERR "-   %s\n", "$docsdir/ROSETTA.md";
printf STDERR "-   %s, %s\n", "$distdir/rosetta.csv", "$distdir/rosetta.json";
for my $t (qw(hashcat john mdxfind)) {
    printf STDERR "-   %-8s proven %3d, claimed %3d, not-supported %3d, GAP %3d\n",
        $t, map { $state_count{$t}{$_} // 0 } qw(proven claimed no unknown);
}
exit 0;
