#!/usr/bin/perl
#-----------------------------------------------------------------------
#
# Name: review-delta.pl
# Description: tell a maintainer what a contribution actually CLAIMS, and
#              which of those claims a machine here can still check
# Category: cracking-rosetta maintainer tool
#
# Project: cracking-rosetta | Phase: 6 - contribution ergonomics
#
#-----------------------------------------------------------------------
# METHODOLOGY AND WHY THESE CHOICES
#
# THE REVIEW PROBLEM THIS REPOSITORY HAS
#
# CI runs validate.pl and deliberately never runs a cracker: tier 'vector'
# must not be reachable by anything a pull request can influence, because a
# PR that could make CI verify it could make CI verify anything. That is the
# right call and it leaves a specific hole. A green check mark on a PR means
# "well formed, and every identifier it names exists". It does NOT mean the
# mappings are true, and the single most consequential line a contributor can
# write -- verified: vector -- is precisely the one CI takes on trust.
#
# So the maintainer's real job is not reading a diff. It is answering: which
# claims did this change make, which of them did anybody prove, and which can
# I prove here in the next five minutes? A unified diff does not answer that.
# 'verified: "asserted"' -> 'verified: "vector"' is one green line among forty
# and it is the whole review.
#
# WHAT THIS PRINTS
#
# Every changed entry, and under it only what CHANGED as a claim: a tier that
# moved, an identifier added or removed, a vector added, a relation added, an
# expression written. Each is graded by what a machine can do about it:
#
#   PROVE   a tier now says 'vector', or identifiers were added under a block
#           that already says 'vector'. Nothing is trustworthy until this
#           machine reproduces it. The exact verify-vectors.pl line is
#           printed, and --verify runs it.
#   READ    a claim no local run can settle -- tier 'upstream' or 'asserted',
#           a note, a relation's rationale. A human decides.
#   FYI     something already covered by validate.pl or inherently safe.
#
# WHY IT COMPARES STRUCTURES, NOT TEXT
#
# A reformat, a key reordering or a requoting is not a claim. Loading both
# sides and comparing the fields that carry meaning means an entry rewritten
# by fmt.pl reviews as "no claims changed", which is exactly true and is what
# lets a contributor run the formatter without drowning their reviewer.
#
# THE BASE IS A MERGE-BASE DIFF
#
# BASE...HEAD, three dots, so a commit that landed on main after the branch
# started is not attributed to the contributor. Uncommitted working-tree
# changes are included too, so this works on a branch you are still editing
# as well as on a PR you have checked out.
#
# DEPENDENCIES
#
#   perl, YAML::XS, git. --verify additionally needs the crackers, via
#   tools/verify-vectors.pl.
#
#-----------------------------------------------------------------------
# Generated by Claude Opus 5 on 2026-08-30

use strict;
use warnings;

use File::Basename qw(basename);
use FindBin qw($RealBin);
use Getopt::Long qw(GetOptions);
use YAML::XS ();

my $PROG = basename($0);
my $ROOT = "$RealBin/..";

sub usage {
    print STDERR <<"END_USAGE";

Usage: $PROG [options]

   --base REF        what to compare against (default: origin/main, then main)
   --algorithms DIR  curated entries (default: data/algorithms)
   --verify          run tools/verify-vectors.pl for every entry graded PROVE
                     (needs hashcat / john / mdxfind locally)
   --tool NAME       restrict --verify to one tool (repeatable)
   -v, --verbose     also list claims graded FYI
   -h, --help        this help

   Exit 0 if nothing needs proving, 1 if something does (or --verify failed),
   2 usage.

   Prints what a contribution CLAIMS rather than what it edited, and grades
   each claim by whether this machine can settle it. Run validate.pl --changed
   first for shape and identifier errors; this tool assumes those are clean
   and asks the different question of whether the content is true.

END_USAGE
    return;
}

my ($algdir, $base, $verify, $help);
my @tools;
my $verbose  = 0;
my $had_args = scalar @ARGV;

GetOptions(
    'algorithms=s' => \$algdir,
    'base=s'       => \$base,
    'verify'       => \$verify,
    'tool=s'       => \@tools,
    'v|verbose+'   => \$verbose,
    'h|help'       => \$help,
) or do { usage(); exit 2 };

if ($help) { usage(); exit 0 }
# Unlike the other tools this one is useful with no arguments at all -- "what
# does the branch I am on claim?" is the common case -- so it runs rather than
# printing usage. -h is there for anyone who wants the options.

$algdir //= "$ROOT/data/algorithms";

chomp(my $top = `git -C @{[quotemeta $ROOT]} rev-parse --show-toplevel 2>/dev/null`);
unless (length $top) {
    print STDERR "$PROG: not a git repository.\n";
    exit 2;
}

# Pick a base the caller did not name.
unless (defined $base && length $base) {
    for my $cand (qw(origin/main main)) {
        my $ok = system("git -C @{[quotemeta $top]} rev-parse --verify --quiet "
                      . quotemeta("$cand^{commit}") . " >/dev/null 2>&1");
        if ($ok == 0) { $base = $cand; last }
    }
}
unless (defined $base && length $base) {
    print STDERR "$PROG: no --base given and neither origin/main nor main exists.\n";
    exit 2;
}

#-----------------------------------------------------------------------
# Which entries changed.

my %changed;      # stem -> 1
my @generated;    # generated paths a contribution should not be hand-editing

sub note_path {
    my ($p) = @_;
    $changed{$1} = 1 if $p =~ m{(?:^|/)data/algorithms/([^/]+)\.yaml$};
    push @generated, $p
        if $p =~ m{(?:^|/)(?:data/tools/|dist/|docs/(?:index\.html|ROSETTA\.md|CRACK\.md))};
}

for my $line (`git -C @{[quotemeta $top]} status --porcelain 2>/dev/null`) {
    chomp $line;
    next unless $line =~ /^..\s+(.*)$/;
    my $p = $1;
    $p = $1 if $p =~ /->\s*(.*)$/;
    $p =~ s/^"|"$//g;
    note_path($p);
}
for my $p (split /\n/,
    `git -C @{[quotemeta $top]} diff --name-only @{[quotemeta $base]}...HEAD 2>/dev/null`) {
    note_path($p);
}

unless (%changed) {
    printf STDERR "- nothing under data/algorithms changed since %s\n", $base;
    exit 0;
}

#-----------------------------------------------------------------------
# Load both sides.

# at_base($stem) - the entry as it was at BASE, or undef if it is new.
sub at_base {
    my ($stem) = @_;
    my $rel = "data/algorithms/$stem.yaml";
    my $txt = `git -C @{[quotemeta $top]} show @{[quotemeta "$base:$rel"]} 2>/dev/null`;
    return undef unless defined $txt && length $txt;
    my $d = eval { YAML::XS::Load($txt) };
    return (ref $d eq 'HASH') ? $d : undef;
}

sub now {
    my ($stem) = @_;
    my $p = "$algdir/$stem.yaml";
    return undef unless -r $p;
    my $d = eval { YAML::XS::LoadFile($p) };
    return (ref $d eq 'HASH') ? $d : undef;
}

#-----------------------------------------------------------------------
# Claim extraction.
#
# Only fields that assert something. name:, notes: and status: are prose and
# are left to the human reading the diff.

my @TOOLS = qw(hashcat john mdxfind crack);
my %IDENT = (hashcat => ['modes'], john => ['cpu', 'gpu'], mdxfind => ['types']);

sub tier_of { my ($e,$t)=@_; return (ref $e->{tools}{$t} eq 'HASH')
                                 ? ($e->{tools}{$t}{verified} // '') : '' }
sub idents_of {
    my ($e, $t) = @_;
    return () unless ref $e->{tools}{$t} eq 'HASH';
    my @v;
    push @v, map { "$_" } @{ $e->{tools}{$t}{$_} || [] } for @{ $IDENT{$t} || [] };
    return @v;
}
sub vec_keys { my ($e)=@_; return map { ($_->{hash} // '') . "\0" . ($_->{pass} // '') }
                                   @{ $e->{vectors} || [] } }
sub rel_keys { my ($e)=@_; return map { "$_->{kind} -> $_->{entry}"
                                        . (($_->{distinction} // '') ne ''
                                           ? " ($_->{distinction})" : '') }
                                   @{ $e->{relations} || [] } }
sub expr_tier { my ($e)=@_; return (ref $e->{expression_proof} eq 'HASH')
                                 ? ($e->{expression_proof}{verified} // '') : '' }

# added(\@before, \@after) - members of after that were not in before.
sub added {
    my ($b, $a) = @_;
    my %had = map { $_ => 1 } @$b;
    return grep { !$had{$_} } @$a;
}

my (@report, %to_prove);
my $prove_count = 0;

for my $stem (sort keys %changed) {
    my $old = at_base($stem);
    my $new = now($stem);

    my @claims;    # [ grade, text ]

    unless (defined $new) {
        push @report, [$stem, [['READ', 'entry DELETED. An id is a published '
            . 'key -- dist/rosetta.csv and docs/index.html fragments point at '
            . 'it. A removal needs a duplicate-of edge and an alias on the '
            . 'survivor, not an rm.']]];
        next;
    }

    my $is_new = !defined $old;
    $old //= {};

    push @claims, ['READ', 'NEW ENTRY'] if $is_new;

    for my $t (@TOOLS) {
        my ($tb, $ta) = (tier_of($old, $t), tier_of($new, $t));
        my @ib = idents_of($old, $t);
        my @ia = idents_of($new, $t);
        my @new_ids = added(\@ib, \@ia);
        my @gone    = added(\@ia, \@ib);

        next unless $tb ne $ta || @new_ids || @gone;

        my $what = @new_ids ? join(', ', @new_ids) : '';

        if ($ta eq 'vector' && ($tb ne 'vector' || @new_ids)) {
            # The claim that only this machine can settle.
            push @claims, ['PROVE', sprintf(
                '%s: tier %s -> vector%s. Nothing here proves that yet.',
                $t, ($tb eq '' ? '(none)' : $tb),
                ($what ? " with $what" : ''))];
            $to_prove{$stem}{$t} = 1;
            $prove_count++;
        }
        elsif ($ta eq 'absent' && $tb ne 'absent') {
            push @claims, ['READ', sprintf(
                '%s: now claims absent -- "%s genuinely cannot do this". '
              . 'Check it is not simply unmapped.', $t, $t)];
        }
        elsif ($tb ne $ta) {
            push @claims, ['READ', sprintf('%s: tier %s -> %s%s', $t,
                ($tb eq '' ? '(none)' : $tb), ($ta eq '' ? '(none)' : $ta),
                ($what ? " with $what" : ''))];
        }
        elsif (@new_ids) {
            push @claims, ['READ', sprintf('%s: identifier(s) added at tier %s: %s',
                $t, ($ta eq '' ? '(none)' : $ta), $what)];
        }
        push @claims, ['READ', sprintf('%s: identifier(s) REMOVED: %s', $t,
            join(', ', @gone))] if @gone;
    }

    # Vectors. The most valuable thing anyone can contribute, and the thing
    # that makes every other claim on the entry checkable later.
    my @nv = added([vec_keys($old)], [vec_keys($new)]);
    if (@nv) {
        push @claims, ['PROVE', sprintf('%d new vector(s). Verify them: a '
            . 'vector nobody ran is a vector that promotes the wrong thing '
            . 'later.', scalar @nv)];
        $to_prove{$stem}{$_} = 1 for grep { tier_of($new, $_) ne '' }
                                      qw(hashcat john mdxfind);
        $prove_count++;
    }

    # Expression: the semantic join key, and a gate that can fail the build.
    my ($eb, $ea) = ($old->{expression} // '', $new->{expression} // '');
    if ($eb ne $ea) {
        my $t = expr_tier($new);
        push @claims, [($t eq 'vector' ? 'PROVE' : 'READ'), sprintf(
            'expression %s -> %s at tier %s%s',
            ($eb eq '' ? '(none)' : $eb), ($ea eq '' ? '(none)' : $ea),
            ($t eq '' ? '(none)' : $t),
            ($t eq 'vector'
             ? '. Re-prove with: tools/derive-expressions.pl --only '
               . $stem . ' --overwrite'
             : ''))];
    }
    elsif (expr_tier($old) ne expr_tier($new)) {
        push @claims, ['READ', sprintf('expression tier %s -> %s',
            (expr_tier($old) || '(none)'), (expr_tier($new) || '(none)'))];
    }

    my @nr = added([rel_keys($old)], [rel_keys($new)]);
    push @claims, ['READ', "relation added: $_"] for @nr;
    my @dr = added([rel_keys($new)], [rel_keys($old)]);
    push @claims, ['READ', "relation REMOVED: $_"] for @dr;

    push @claims, ['FYI', 'no claim changed (formatting or prose only)']
        unless @claims;

    push @report, [$stem, \@claims];
}

#-----------------------------------------------------------------------
# Report.

printf "Contribution review: %d entry/entries changed since %s\n\n",
    scalar(keys %changed), $base;

if (@generated) {
    my %u; my @g = grep { !$u{$_}++ } @generated;
    print "GENERATED FILES WERE EDITED. These are rebuilt by tools/render.pl\n"
        . "and the extractors; hand edits are lost on the next run and should\n"
        . "not be part of a data contribution:\n";
    print "  $_\n" for @g;
    print "\n";
}

for my $r (@report) {
    my ($stem, $claims) = @$r;
    my @show = grep { $verbose || $_->[0] ne 'FYI' } @$claims;
    next unless @show;
    print "$stem\n";
    printf "  %-5s %s\n", @$_ for @show;
    print "\n";
}

if (%to_prove) {
    print "Run these to settle the PROVE claims:\n\n";
    for my $stem (sort keys %to_prove) {
        my @t = sort keys %{ $to_prove{$stem} };
        printf "  tools/verify-vectors.pl --only %s %s\n",
            $stem, join(' ', map { "--tool $_" } @t);
    }
    print "\n";
}
else {
    print "Nothing in this change needs a cracker to settle.\n\n";
}

print "Also run: tools/validate.pl --changed $base   (shape and identifiers)\n"
    . "          tools/fmt.pl --all --check            (canonical form)\n";

#-----------------------------------------------------------------------
# Optionally settle them.

my $failed = 0;
if ($verify && %to_prove) {
    my %want = map { $_ => 1 } @tools;
    print "\n--- verifying ---\n";
    for my $stem (sort keys %to_prove) {
        my @t = grep { !%want || $want{$_} } sort keys %{ $to_prove{$stem} };
        next unless @t;
        my @cmd = ("$RealBin/verify-vectors.pl", '--only', $stem,
                   map { ('--tool', $_) } @t);
        printf "\n\$ %s\n", join(' ', @cmd);
        $failed = 1 if system(@cmd) != 0;
    }
}

exit(($failed || $prove_count) ? 1 : 0);
