#!/bin/sh
# runbg.sh -- run a long command in the background and wait for it in a way
# that is GUARANTEED to terminate.
#
# WHY THIS EXISTS
#
# Every long-running measurement in this repository -- a full mdxfind sweep, a
# corpus-wide binary comparison, an OpenSSL dependency build -- gets started in
# the background and then waited on. On 2026-09-05 four such waits were found
# still spinning hours after their work had finished, and reviewing the day
# turned up THREE distinct ways an ad-hoc wait goes wrong. All three are the
# same underlying mistake: the waiter polls a PREDICATE it inferred, instead of
# observing the thing that actually happened.
#
#   1. THE PREDICATE MATCHES THE WAITER ITSELF.
#      `until ! pgrep -f 'make all'; do sleep 20; done`
#      pgrep -f matches the polling loop's own command line, which contains the
#      string. The loop waits for itself to disappear. It never fires and never
#      notifies, which is indistinguishable from work still in progress.
#
#   2. THE PREDICATE MATCHES THE REASSURING CASE.
#      `until grep -qE 'exit=|ERROR|\*\*\*' build.log; do sleep 10; done`
#      fired early because `***` appears in OpenSSL's "successfully configured"
#      banner. A pattern meant to catch failure caught success.
#
#   3. THE PREDICATE'S SUBJECT IS REWRITTEN UNDERNEATH IT.
#      A later command rewrote the file the condition tested, so the predicate
#      became permanently unsatisfiable. Two loops span for four hours.
#
# WHAT THIS DOES INSTEAD
#
# It never greps program output and never pattern-matches a process list. The
# runner writes ONE file, `status`, containing the exit code, and it writes it
# exactly once, itself, after the command has actually exited. Waiting is:
# does that file exist yet. The signal is produced by the same shell that ran
# the command, so it cannot be a coincidence, cannot match the waiter, and
# nothing else writes it.
#
# THE THREE WAYS A WAIT CAN END, AND ALL THREE ARE REPORTED
#
# Silence is not success. A waiter that only recognises completion hangs
# forever on a crash, so this distinguishes:
#   done      the status file appeared      -> exits with the command's code
#   vanished  the pid is gone and no status -> exit 3 (killed -9, OOM, reboot)
#   waited    the wait budget ran out       -> exit 4, job left running
# and the wait loop is bounded by an iteration cap derived from the budget, so
# it terminates even if every one of those checks somehow misfires.
#
# The job carries its OWN timeout too, enforced by a watchdog, so a run that
# nobody ever waits on still cannot outlive its budget.
#
# Each run gets a FRESH directory. Nothing is ever appended to or reused, which
# is the other trap from that day: `tmp/binary-diff.out` was read as current
# when it was the previous run's, because the re-run had sent stdout elsewhere
# and never overwrote it. A run directory that cannot be reused cannot go stale.
#
# stdout and stderr are kept in SEPARATE files, never merged. `hashpipe -c`
# writes a verified line to stdout and echoes a refused line to stderr
# verbatim, so a merged stream is consistent with both and cannot tell you
# which happened -- see CLAUDE.md.
#
# POSIX sh. Uses setsid(1) when present so a timeout kills the whole process
# group rather than just the shell; falls back to killing the pid alone and
# says so. No GNU-only utilities.
#
# Generated by Claude Opus 5 on 2026-09-05

set -u

PROG=$(basename "$0")
ROOT=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
RUNS=${RUNBG_DIR:-$ROOT/tmp/runbg}

usage() {
    cat <<USAGE
Usage: $PROG start [-l LABEL] [-t SECS] -- COMMAND [ARGS...]
       $PROG wait  [-t SECS] [-i SECS] [-q] RUNDIR
       $PROG status RUNDIR
       $PROG list
       $PROG kill RUNDIR

   start   run COMMAND detached; print its run directory on stdout
           -l LABEL  short name for the run directory (default: the command)
           -t SECS   the job's own timeout, enforced by a watchdog
                     (default: 3600; 0 disables it)
   wait    block until the run finishes, then exit with ITS exit code
           -t SECS   how long to wait before giving up (default: 3600)
           -i SECS   poll interval (default: 5)
           -q        summary only, no progress on stderr
   status  print running|done|vanished and the exit code if known
   list    every run directory, newest last, with its state
   kill    terminate a running job and its process group

   A run directory holds: cmd, pid, stdout, stderr, started, status, elapsed.
   \$RUNBG_DIR overrides where they live (default: tmp/runbg).

   Exit: 0 the command succeeded, or its own code if it failed;
         2 usage; 3 the job vanished without writing a status;
         4 the wait budget ran out and the job is still running.
USAGE
}

die() { printf '%s: %s\n' "$PROG" "$*" >&2; exit 1; }

# alive PID - is that process still there? Uses kill -0, which asks the kernel
# rather than pattern-matching a process list, so it cannot match the caller.
alive() { kill -0 "$1" 2>/dev/null; }

cmd_start() {
    label=''; budget=3600
    while [ $# -gt 0 ]; do
        case $1 in
            -l) shift; [ $# -gt 0 ] || { usage; exit 2; }; label=$1; shift ;;
            -t) shift; [ $# -gt 0 ] || { usage; exit 2; }; budget=$1; shift ;;
            --) shift; break ;;
            -*) usage; exit 2 ;;
            *)  break ;;
        esac
    done
    [ $# -gt 0 ] || { usage; exit 2; }

    [ -n "$label" ] || label=$(basename "$1")
    # A run directory name that is safe on any filesystem, plus the pid of this
    # shell so two starts in the same second cannot collide.
    safe=$(printf '%s' "$label" | tr -c 'A-Za-z0-9._-' '_')
    dir=$RUNS/$(date -u +%Y%m%dT%H%M%SZ).$safe.$$
    mkdir -p "$dir" || die "cannot create $dir"

    # Record the command exactly, one argument per line, so a later reader can
    # see what ran without guessing at quoting.
    for a in "$@"; do printf '%s\n' "$a"; done >| "$dir/cmd"
    date -u +%Y-%m-%dT%H:%M:%SZ >| "$dir/started"
    printf '%s\n' "$budget" >| "$dir/budget"

    # The runner. It is the ONLY writer of status/, and it writes it after the
    # command has exited, via a temp file and a rename so a reader can never
    # see a half-written code.
    #
    # setsid puts the command in its own process group; without it a timeout
    # would kill the wrapper and orphan the real work.
    if command -v setsid >/dev/null 2>&1; then LEADER='setsid'; else LEADER=''; fi
    printf '%s\n' "${LEADER:-none}" >| "$dir/leader"

    (
        $LEADER "$@" >| "$dir/stdout" 2>| "$dir/stderr" &
        job=$!
        printf '%s\n' "$job" >| "$dir/pid"

        # Watchdog: enforce the job's own budget even if nobody ever waits.
        if [ "$budget" -gt 0 ] 2>/dev/null; then
            (
                # Sleep in one shot, then check once. No predicate, no loop:
                # there is nothing here to get wrong.
                sleep "$budget"
                if kill -0 "$job" 2>/dev/null; then
                    printf 'timeout after %ss\n' "$budget" >> "$dir/stderr"
                    kill -TERM "-$job" 2>/dev/null || kill -TERM "$job" 2>/dev/null
                    sleep 5
                    kill -KILL "-$job" 2>/dev/null || kill -KILL "$job" 2>/dev/null
                fi
            ) &
            printf '%s\n' "$!" >| "$dir/watchdog"
        fi

        wait "$job"
        code=$?
        printf '%s\n' "$code" >| "$dir/status.tmp"
        mv "$dir/status.tmp" "$dir/status"
        date -u +%Y-%m-%dT%H:%M:%SZ >| "$dir/finished"
        # The watchdog has nothing left to guard.
        if [ -f "$dir/watchdog" ]; then kill "$(cat "$dir/watchdog")" 2>/dev/null; fi
    ) </dev/null >/dev/null 2>&1 &

    # Give the runner a moment to record the pid, so `status` straight after
    # `start` is not a race. Bounded: ten tries, then report what we have.
    n=0
    while [ ! -f "$dir/pid" ] && [ $n -lt 10 ]; do n=$((n + 1)); sleep 0.2 2>/dev/null || sleep 1; done

    printf '%s\n' "$dir"
}

# state DIR - echoes running|done|vanished. Never greps output, never scans a
# process table by name.
state() {
    d=$1
    [ -d "$d" ] || die "no such run directory: $d"
    if [ -f "$d/status" ]; then echo done; return; fi
    if [ ! -f "$d/pid" ]; then echo running; return; fi   # runner not up yet
    if alive "$(cat "$d/pid")"; then echo running; else echo vanished; fi
}

cmd_status() {
    [ $# -eq 1 ] || { usage; exit 2; }
    st=$(state "$1")
    if [ "$st" = done ]; then
        printf 'done exit=%s\n' "$(cat "$1/status")"
    else
        printf '%s\n' "$st"
    fi
}

cmd_wait() {
    budget=3600; interval=5; quiet=0
    while [ $# -gt 0 ]; do
        case $1 in
            -t) shift; [ $# -gt 0 ] || { usage; exit 2; }; budget=$1; shift ;;
            -i) shift; [ $# -gt 0 ] || { usage; exit 2; }; interval=$1; shift ;;
            -q) quiet=1; shift ;;
            -*) usage; exit 2 ;;
            *)  break ;;
        esac
    done
    [ $# -eq 1 ] || { usage; exit 2; }
    dir=$1
    [ -d "$dir" ] || die "no such run directory: $dir"
    [ "$interval" -gt 0 ] 2>/dev/null || die "poll interval must be positive"

    # A HARD iteration cap, not just a clock comparison. Even if the clock, the
    # status file and the pid check all misbehave at once, this loop ends.
    cap=$(( budget / interval + 2 ))
    n=0
    while [ $n -lt $cap ]; do
        st=$(state "$dir")
        case $st in
            done)
                code=$(cat "$dir/status")
                [ $quiet -eq 1 ] || printf '%s: done in %ss, exit %s\n' \
                    "$PROG" "$((n * interval))" "$code" >&2
                return "$code" ;;
            vanished)
                printf '%s: the job vanished without writing a status -- killed, OOM, or the host went away. See %s/stderr\n' \
                    "$PROG" "$dir" >&2
                return 3 ;;
        esac
        n=$((n + 1))
        sleep "$interval"
    done
    printf '%s: gave up after %ss; the job is STILL RUNNING. %s\n' \
        "$PROG" "$((cap * interval))" "$dir" >&2
    return 4
}

cmd_list() {
    [ -d "$RUNS" ] || { printf 'no runs under %s\n' "$RUNS"; return 0; }
    for d in "$RUNS"/*; do
        [ -d "$d" ] || continue
        printf '%-10s %s  %s\n' "$(state "$d")" "$d" "$(head -1 "$d/cmd" 2>/dev/null)"
    done
}

cmd_kill() {
    [ $# -eq 1 ] || { usage; exit 2; }
    d=$1
    [ -f "$d/pid" ] || die "no pid recorded in $d"
    p=$(cat "$d/pid")
    kill -TERM "-$p" 2>/dev/null || kill -TERM "$p" 2>/dev/null || true
    printf '%s: sent TERM to %s\n' "$PROG" "$p" >&2
}

[ $# -gt 0 ] || { usage; exit 2; }
sub=$1; shift
case $sub in
    start)  cmd_start "$@" ;;
    wait)   cmd_wait "$@" ;;
    status) cmd_status "$@" ;;
    list)   cmd_list "$@" ;;
    kill)   cmd_kill "$@" ;;
    -h|--help|help) usage; exit 0 ;;
    *)      usage; exit 2 ;;
esac
