#!/usr/bin/perl
#-----------------------------------------------------------------------
#
# Name: seed-upstream.pl
# Description: fill data/algorithms/ from mappings upstream has already
#              verified by recomputation
# Category: cracking-rosetta seeder
#
# Project: cracking-rosetta | Phase: 3 - seed from upstream
#
#-----------------------------------------------------------------------
# METHODOLOGY AND WHY THESE CHOICES
#
# TWO SEED SOURCES, BOTH EARNED THE 'upstream' TIER
#
#   1. mdxfind's own hashcat column, already carried in data/tools/mdxfind.yaml.
#      298 types naming 327 distinct hashcat modes, shipped in the binary.
#   2. hashpipe's john_map.h. 125 john dynamic formats mapped to mdxfind types,
#      each confirmed by recomputation against john's own test vectors - 9672
#      of them across 403 formats - with the unverifiable rows omitted rather
#      than guessed.
#
# Neither is this project's own reproduction, so neither is tier 'vector'.
# Both come from projects that verify by recomputation and document what they
# could not verify, which is exactly what tier 'upstream' is for.
#
# CURATED DATA WINS. ALWAYS.
#
# A seed only ever fills a gap. If an entry already has a hashcat block, this
# script leaves it alone even when the seed disagrees - a human or the old
# sheet said something, and silently overwriting it would destroy the only
# record that a disagreement exists. Disagreements are REPORTED so they can be
# settled by verification rather than by whichever script ran last.
#
# ONLY A ONE-TO-ONE hashcat MAPPING IS SEEDED
#
# mdxfind's hashcat column is a list of RELATED modes, not an equivalence.
# Measured 2026-08-29: 279 of its 298 mapped types name exactly one mode, and
# those are real 1:1 claims. The other 19 are coarse, and dangerously so -
# type MD5 names modes 0, 2600, 3500 and 5100, which are md5, md5(md5(p)),
# md5(md5(md5(p))) and Half MD5: four DIFFERENT algorithms that mdxfind reaches
# from one type by varying -i and truncation. Writing all four onto one entry
# would manufacture precision that upstream never claimed.
#
# So a 1:N mapping is reported for a human rather than seeded. --include-multi
# overrides that for anyone who wants the raw upstream list. Nineteen types is
# a small price for not lying in the one column people will automate against.
#
# THE ITERATION SUFFIX IS PART OF THE IDENTITY
#
# john_map.h writes MD5x01, MD5x02, MD5x03 - mdxfind type MD5 at -i 1, 2 and 3
# - and those are john's dynamic_0, dynamic_2 and dynamic_3, three different
# algorithms. Upstream states this explicitly and it is the one thing that
# cannot be normalized away. The suffix is only stripped when the full name
# does NOT resolve as a type and the base does, so a genuine type ending in
# digits is never mangled.
#
# THE EMITTER IS SELF-TESTED BEFORE ANYTHING IS WRITTEN
#
# These entries were written by tools/import-sheet.py and are rewritten here by
# a different language's emitter. If the two disagree on key order or quoting
# by one byte, this pass reformats hundreds of files and buries the real diff.
# So it re-emits untouched entries first and refuses to run unless the bytes
# come back identical.
#
#-----------------------------------------------------------------------
# Generated by Claude Opus 5 on 2026-08-29

use strict;
use warnings;

use File::Basename qw(basename);
use FindBin qw($RealBin);
use Getopt::Long qw(GetOptions);
use POSIX qw(strftime);
use YAML::XS ();

use lib "$RealBin/lib";
use RosettaEmit qw(emit_entry entry_text);

my $PROG = basename($0);
my $ROOT = "$RealBin/..";

sub usage {
    print STDERR <<"END_USAGE";

Usage: $PROG [options]

   --john-map FILE   hashpipe john_map.h (default: vendor/cynosureprime/john_map.h)
   --include-multi   also seed mdxfind types naming SEVERAL hashcat modes
                     (off by default: such a list is 'related', not 'equal')
   --algorithms DIR  curated entries (default: data/algorithms)
   --tools DIR       generated inventories (default: data/tools)
   -n, --dry-run     report what would change; write nothing
   -v, --verbose     list each change (repeatable)
   -h, --help        this help

   Fills gaps in data/algorithms/ from mappings upstream verified by
   recomputation. Never overwrites a mapping that is already present;
   disagreements are reported instead.

   Exit 0 success, 1 error, 2 usage.

END_USAGE
    return;
}

my ($johnmap, $algdir, $tooldir, $dry, $help, $include_multi);
my $verbose = 0;

GetOptions(
    'john-map=s'   => \$johnmap,
    'include-multi' => \$include_multi,
    'algorithms=s' => \$algdir,
    'tools=s'      => \$tooldir,
    'n|dry-run'    => \$dry,
    'v|verbose+'   => \$verbose,
    'h|help'       => \$help,
) or do { usage(); exit 2 };

if ($help) { usage(); exit 0 }

$johnmap //= "$ROOT/vendor/cynosureprime/john_map.h";
$algdir  //= "$ROOT/data/algorithms";
$tooldir //= "$ROOT/data/tools";

my $today = strftime('%Y-%m-%d', localtime);

sub slurp_yaml {
    my ($f) = @_;
    my $d = eval { YAML::XS::LoadFile($f) };
    if ($@ || !defined $d) {
        print STDERR "$PROG: cannot load $f: $@\n";
        exit 1;
    }
    return $d;
}

#-----------------------------------------------------------------------
# Inventories.

my $mx_doc = slurp_yaml("$tooldir/mdxfind.yaml");
my $jn_doc = slurp_yaml("$tooldir/john.yaml");
my $hc_doc = slurp_yaml("$tooldir/hashcat.yaml");

my %MX_BY_NAME = map { uc($_->{name}) => $_ } @{ $mx_doc->{types} };
my %HC_MODE    = map { $_->{mode} => 1 }      @{ $hc_doc->{modes} };
my %JN_FMT     = map { $_->{label} => $_ }    @{ $jn_doc->{formats} };
my %JN_DISABLED = map { $_ => 1 } @{ $jn_doc->{disabled_dynamic} || [] };

#-----------------------------------------------------------------------
# Load the curated entries, and prove the emitter round-trips them.

opendir(my $dh, $algdir) or do { print STDERR "$PROG: cannot read $algdir: $!\n"; exit 1 };
my @files = sort grep { /\.yaml$/ } readdir $dh;
closedir $dh;

my (%entry, %path, %id_taken);
my $roundtrip_checked = 0;

for my $f (@files) {
    my $p  = "$algdir/$f";
    my $e  = slurp_yaml($p);
    my $id = $e->{id} // do { (my $s = $f) =~ s/\.yaml$//; $s };

    $entry{$id} = $e;
    $path{$id}  = $p;
    $id_taken{$id} = 1;

    # Emitter self-test. Only the first 25 are checked; if the emitters agree
    # on those they agree, and re-rendering 646 files to prove it is waste.
    if ($roundtrip_checked < 25) {
        open my $fh, '<', $p or next;
        local $/;
        my $on_disk = <$fh>;
        close $fh;
        my $rendered = entry_text($e);
        if ($on_disk ne $rendered) {
            print STDERR "$PROG: emitter mismatch on $f -- refusing to run.\n";
            print STDERR "$PROG: RosettaEmit::entry_text disagrees with what wrote this file;\n";
            print STDERR "$PROG: seeding now would reformat every entry it touches.\n";
            exit 1;
        }
        $roundtrip_checked++;
    }
}

#-----------------------------------------------------------------------
# Index by the mdxfind identity: type name plus iteration count.

sub mx_key { my ($t, $i) = @_; return uc($t) . '#' . ($i // 1) }

my %by_mx;
for my $id (keys %entry) {
    my $blk = $entry{$id}{tools}{mdxfind} or next;
    my $it  = $blk->{iterations} // 1;
    push @{ $by_mx{ mx_key($_, $it) } }, $id for @{ $blk->{types} || [] };
}

my (@added_hc, @added_jn, @created, @conflicts, @unresolved, @ambiguous);
my %changed;

# unique_id($base) - a permanent, non-colliding id.
sub unique_id {
    my ($base) = @_;
    $base =~ s/[^A-Za-z0-9]+/-/g;
    $base = lc $base;
    $base =~ s/^-+|-+$//g;
    $base = 'algorithm' unless length $base;
    return $base unless $id_taken{$base};
    my $n = 2;
    $n++ while $id_taken{"$base-$n"};
    return "$base-$n";
}

# make_entry($type, $iterations) - a new curated entry for an mdxfind type.
sub make_entry {
    my ($type, $it) = @_;
    my $rec = $MX_BY_NAME{ uc $type } or return undef;

    my $base = lc $type;
    $base .= "-x$it" if $it > 1;
    my $id = unique_id($base);

    my $name = $it > 1 ? "$type ($it iterations)" : $type;

    my $e = {
        id     => $id,
        name   => $name,
        status => 'needs-review',
        tools  => {
            mdxfind => {
                types    => [ $rec->{name} ],
                verified => 'upstream',
                verified_at => $today,
                verified_with => $mx_doc->{version},
            },
        },
    };
    $e->{tools}{mdxfind}{iterations} = $it if $it > 1;

    # mdxfind ships a self-test vector as "hash[:salt]:password".
    if (defined $rec->{example_vector} && defined $rec->{example_pass}) {
        my $v = $rec->{example_vector};
        my $i = rindex($v, ':');
        if ($i > 0) {
            push @{ $e->{vectors} }, {
                hash   => substr($v, 0, $i),
                pass   => $rec->{example_pass},
                source => 'mdxfind',
            };
        }
    }

    $entry{$id}   = $e;
    $path{$id}    = "$algdir/$id.yaml";
    $id_taken{$id} = 1;
    push @{ $by_mx{ mx_key($type, $it) } }, $id;
    push @created, $id;
    $changed{$id} = 1;
    return $id;
}

#-----------------------------------------------------------------------
# Seed 1: mdxfind's own hashcat mapping.

for my $t (@{ $mx_doc->{types} }) {
    my $modes = $t->{hashcat_modes} or next;
    my @valid = grep { $HC_MODE{$_} } @$modes;

    # A mode mdxfind names that this hashcat does not have is upstream skew,
    # not something to write into the data. Report it and move on.
    if (@valid != @$modes) {
        my %v = map { $_ => 1 } @valid;
        push @unresolved, sprintf('mdxfind %s -> hashcat mode %s not in %s',
            $t->{name}, join(',', grep { !$v{$_} } @$modes), $hc_doc->{version});
    }
    next unless @valid;

    # A list of related modes is not an equivalence claim; see methodology.
    if (@valid > 1 && !$include_multi) {
        push @ambiguous, sprintf('%s -> [%s]', $t->{name}, join(',', @valid));
        next;
    }

    my $ids = $by_mx{ mx_key($t->{name}, 1) };
    if (!$ids || !@$ids) {
        my $id = make_entry($t->{name}, 1) or next;
        $ids = [$id];
    }

    for my $id (@$ids) {
        my $e = $entry{$id};
        if (my $hc = $e->{tools}{hashcat}) {
            # Already populated. Note a real disagreement; never overwrite.
            if ($hc->{modes} && @{ $hc->{modes} }) {
                my %have = map { $_ => 1 } @{ $hc->{modes} };
                my @new  = grep { !$have{$_} } @valid;
                push @conflicts, sprintf('%s: has hashcat [%s], mdxfind also says [%s]',
                    $id, join(',', @{ $hc->{modes} }), join(',', @new)) if @new;
            }
            next;
        }
        $e->{tools}{hashcat} = {
            modes         => [ sort { $a <=> $b } @valid ],
            verified      => 'upstream',
            verified_at   => $today,
            verified_with => $mx_doc->{version},
            note          => "hashcat mapping shipped in mdxfind's own type table",
        };
        $changed{$id} = 1;
        push @added_hc, $id;
    }
}

#-----------------------------------------------------------------------
# Seed 2: hashpipe's john_map.h.

my $jm_disabled = 0;

if (-r $johnmap) {
    open my $fh, '<', $johnmap or do { print STDERR "$PROG: cannot read $johnmap: $!\n"; exit 1 };
    my $src = do { local $/; <$fh> };
    close $fh;

    # ONLY the first table, JohnMap[]. hashpipe v1.189 added a second,
    # JohnMapLocal[], holding config-defined dynamics read from the
    # dynamic.conf of the machine that ran upstream's generator. Upstream's
    # own comment says the numbering is local and the table is consulted on
    # INPUT ONLY, and that is demonstrable here: upstream's dynamic_1013 is
    # MD5PASSSALT and its dynamic_1014 is POSTGRESQL, while this host's john
    # has the two the other way round (measured 2026-09-02). Seeding from it
    # would write another machine's numbering into the john column, where
    # every other row means an identifier this host's john answers to.
    # data/upstream-disagreements.yaml carries the record; check_john_map in
    # check-upstream.pl makes the same cut for the same reason.
    if ($src =~ /\bJohnMap\s*\[\s*\]\s*=\s*\{(.*?)^\s*\}\s*;/ms) {
        $src = $1;
    }
    else {
        print STDERR "$PROG: $johnmap has no JohnMap[] table -- has its "
                   . "shape changed? Refusing to seed from it.\n";
        exit 1;
    }

    # Rows this repository has MEASURED upstream to be wrong about. The
    # register is the single place that records them, so read it rather than
    # keeping a second list here that can drift from it. A row named in a
    # john-map-agreement record's differs: is reported unresolved, never
    # seeded: see data/upstream-disagreements.yaml for what each one is.
    my %disputed;
    my $regpath = "$ROOT/data/upstream-disagreements.yaml";
    if (-r $regpath) {
        my $reg = eval { YAML::XS::LoadFile($regpath) };
        for my $rec (@{ ($reg || {})->{disagreements} || [] }) {
            next unless ($rec->{kind} // '') eq 'john-map-agreement';
            for my $d (@{ $rec->{differs} || [] }) {
                $disputed{ $d->{john} } = $d->{why} // 'recorded disagreement'
                    if defined $d->{john};
            }
        }
    }

    while ($src =~ /\{\s*"([^"]+)"\s*,\s*"([^"]+)"\s*\}/g) {
        my ($label, $hptype) = ($1, $2);

        if (my $why = $disputed{$label}) {
            push @unresolved, "john_map $label -> '$hptype' is a recorded "
                            . "disagreement ($why); not seeded";
            next;
        }

        # Strip the iteration suffix ONLY if the whole name is not itself a
        # type; see methodology.
        my ($base, $it) = ($hptype, 1);
        if (!$MX_BY_NAME{ uc $hptype } && $hptype =~ /^(.+)x(\d+)$/ && $MX_BY_NAME{ uc $1 }) {
            ($base, $it) = ($1, $2 + 0);
        }

        if (!$MX_BY_NAME{ uc $base }) {
            push @unresolved, "john_map $label -> '$hptype' is not an mdxfind type";
            next;
        }

        my $known = $JN_FMT{$label};
        if (!$known && !$JN_DISABLED{$label}) {
            push @unresolved, "john_map $label does not exist in " . $jn_doc->{version};
            next;
        }
        $jm_disabled++ if !$known && $JN_DISABLED{$label};

        my $ids = $by_mx{ mx_key($base, $it) };
        if (!$ids || !@$ids) {
            my $id = make_entry($base, $it) or next;
            $ids = [$id];
        }

        for my $id (@$ids) {
            my $e = $entry{$id};
            my $jn = $e->{tools}{john};

            if (!$jn) {
                $e->{tools}{john} = {
                    cpu           => [$label],
                    verified      => 'upstream',
                    verified_at   => $today,
                    verified_with => $jn_doc->{version},
                    note          => 'from hashpipe john_map.h, confirmed upstream by recomputation',
                };
                $changed{$id} = 1;
                push @added_jn, $id;
                next;
            }

            # Present already: add the label if missing, leave the tier alone.
            my %have = map { $_ => 1 } @{ $jn->{cpu} || [] };
            next if $have{$label};
            push @{ $jn->{cpu} }, $label;
            @{ $jn->{cpu} } = sort @{ $jn->{cpu} };
            $changed{$id} = 1;
            push @added_jn, $id;
        }
    }
}
else {
    print STDERR "$PROG: $johnmap not readable; skipping the john_map seed.\n";
}

#-----------------------------------------------------------------------
# Write.

my $written = 0;
if (!$dry) {
    for my $id (sort keys %changed) {
        $written += emit_entry($path{$id}, $entry{$id});
    }
}

#-----------------------------------------------------------------------
# Report.

printf STDERR "- Seeded from mdxfind %s and %s\n", $mx_doc->{version}, basename($johnmap);
printf STDERR "-   entries created:        %d\n", scalar @created;
printf STDERR "-   hashcat blocks added:   %d\n", scalar @added_hc;
printf STDERR "-   john blocks added:      %d\n", scalar @added_jn;
printf STDERR "-   entries changed:        %d%s\n", scalar(keys %changed),
    $dry ? ' (dry run; nothing written)' : " ($written file(s) written)";
printf STDERR "-   john_map rows naming a disabled dynamic: %d\n", $jm_disabled if $jm_disabled;

if (@ambiguous) {
    printf STDERR "- %d mdxfind type(s) name several hashcat modes and were NOT seeded:\n",
        scalar @ambiguous;
    print STDERR "-   Such a list means 'related to', not 'equal to' -- a human decides.\n";
    print STDERR "-   Use --include-multi to seed them verbatim anyway.\n";
    my $n = 0;
    for my $a (@ambiguous) { print STDERR "-   $a\n"; last if ++$n >= ($verbose ? @ambiguous : 6) }
}

if (@conflicts) {
    printf STDERR "- %d disagreement(s) left for a human; curated data was NOT overwritten:\n",
        scalar @conflicts;
    my $n = 0;
    for my $c (@conflicts) { print STDERR "-   $c\n"; last if ++$n >= ($verbose ? @conflicts : 8) }
}

if (@unresolved) {
    printf STDERR "- %d unresolved upstream reference(s):\n", scalar @unresolved;
    my $n = 0;
    for my $u (@unresolved) { print STDERR "-   $u\n"; last if ++$n >= ($verbose ? @unresolved : 8) }
}

exit 0;
