#!/usr/bin/perl
#
# seed-hx.pl -- transcribe mdxfind type expressions from the hx specification
#
# PURPOSE
#
# Appendix A of the hx Language Specification (Waffle, rev 1.15, Aug 2026)
# states an hx expression for 1011 mdxfind types, covering 998 of the 1001 in
# our inventory. 475 entries here name such a type and carry no expression at
# all. This transcribes them at tier `upstream` so that derive-expressions.pl
# can then try to PROVE each one through john's dynamic compiler.
#
# WHY UPSTREAM AND NEVER VECTOR
#
# Transcription is not reproduction. The tier vocabulary is fixed and
# `upstream` means exactly this: asserted by an upstream project that verifies
# by recomputation. Only derive-expressions.pl may write `vector`, and only
# after john has recovered the entry's own plaintext from its own hash.
#
# WHY IT BAILS INSTEAD OF GUESSING
#
# hx spells functions its own way (hav128, md5_bin, utf16le) where this
# repository uses john's spelling (haval128_3, md5_raw, utf16). A translation
# table is fine for the digests, but hx also has tokens with no expression
# meaning here at all -- pbkdf2_sha256(), bcrypt(), descrypt(), emit(), lm().
# Those are containers and KDFs; they belong in denotation:, not in an
# expression that validate.pl treats as a semantic join key. So any candidate
# containing a token outside %FUNC is DISCARDED rather than partially
# translated. Dropping a token silently is how md5(md5($p).":".$u) once looked
# like md5(md5($p).$s).
#
# MULTI-EMIT TYPES ARE SKIPPED
#
# Note [24] of the specification names 34 types that emit SEVERAL candidate
# digests per input and match if any one reproduces the digest. Such a type has
# no single expression, so writing one would be a false claim even when the
# string is one of the forms. See CLAUDE.md.
#
# The specification is NOT vendored: this repository is MIT throughout and the
# PDF carries no licence grant. Re-fetch it to re-run this.
#
# Usage: seed-hx.pl [--appendix FILE] [--apply] [-v]
#
# Generated by Claude Opus 4.5 on 2026-08-31

use strict;
use warnings;
use FindBin qw($RealBin);
use lib "$RealBin/lib";
use Getopt::Long qw(GetOptions);
use File::Basename qw(basename);
use YAML::XS qw(LoadFile);
use RosettaEmit qw(emit_entry);
use RosettaExpr qw(compile_expression);

my $PROG = basename($0);
my $ROOT = "$RealBin/..";

my $appendix = "$ROOT/tmp/hx/appA.txt";
my $algdir   = "$ROOT/data/algorithms";
my ($apply, $verbose, $help) = (0, 0, 0);

sub usage {
    print <<"USAGE";
Usage: $PROG [options]

   --appendix FILE  parsed Appendix A text  (default: tmp/hx/appA.txt)
   --algorithms DIR curated entries         (default: data/algorithms)
   --apply          write; without it, report only
   -v, --verbose    per-entry detail on stderr
   -h, --help       this help

   Transcribes at tier 'upstream' only, and only for entries that have an
   mdxfind type, no expression, and a type that is not multi-emit. Any hx
   token outside the known vocabulary discards that candidate entirely.

   Exit 0 success, 1 error, 2 usage.
USAGE
    exit 2;
}

GetOptions(
    'appendix=s'   => \$appendix,
    'algorithms=s' => \$algdir,
    'apply'        => \$apply,
    'verbose|v+'   => \$verbose,
    'help|h'       => \$help,
) or usage();
usage() if $help;
usage() unless -f $appendix;

# hx spelling -> this repository's spelling. A token absent from here is a
# token this tool refuses to translate.
my %FUNC = (
    md5 => 'md5', md4 => 'md4', md2 => 'md2',
    sha1 => 'sha1', sha0 => 'sha0', sha224 => 'sha224', sha256 => 'sha256',
    sha384 => 'sha384', sha512 => 'sha512',
    wrl => 'whirlpool', gost => 'gost',
    rmd128 => 'ripemd128', rmd160 => 'ripemd160',
    rmd256 => 'ripemd256', rmd320 => 'ripemd320',
    sne128 => 'snefru128', sne256 => 'snefru256',
    hav128 => 'haval128_3', hav160 => 'haval160_3',
    hav192 => 'haval192_3', hav224 => 'haval224_3', hav256 => 'haval256_3',
    # representation modifiers that carry over unchanged in meaning
    upper => 'upper', lower => 'lower', cap => 'cap', rev => 'rev',
    base64 => 'base64', hex => 'hex',
    # structural, and descriptive rather than cryptographic. These cannot be
    # compiled by john, so an expression using one stays at tier upstream --
    # but the field is documented as hx-style, and ciscoasa already carries a
    # pad(). Refusing them would lose real information for no gain.
    cut => 'cut', pad => 'pad', fromhex => 'fromhex',
    frombase64 => 'frombase64', utf16be => 'utf16be',
);
# hav128_4 / hav160_5 / ... expand mechanically
for my $w (qw(128 160 192 224 256)) {
    for my $r (3, 4, 5) { $FUNC{"hav${w}_$r"} = "haval${w}_$r" }
}
# _bin is this repository's _raw
for my $k (keys %FUNC) { $FUNC{"${k}_bin"} = "$FUNC{$k}_raw" if $k =~ /^(md|sha|wrl|gost|rmd|sne|hav)/ }
$FUNC{utf16le} = 'utf16';

# Note [24]: types that emit several candidate digests per input.
my %MULTI = map { $_ => 1 } qw(
    MD5MD5PASS MD5PASSMD5 MD5HEXSALT SHA1HEXSALT SHA256HEXSALT GOSTHEXSALT
    HAV128HEXSALT MD5BASE64MD5RAW MD5BASE64SHA1RAW MD52SALTMD5 MD5MD5USER
    SHA1MD5USER MD5CAPMD5USER MD5CAPMD5MD5USER MD5UCBASE64MD5RAW
    MD5UCBASE64SHA1RAW SHA1MD5DSALT SHA1MD5MD5DSALT SHA1SHA1MD5MD5PASS1SALT
    SHA1MD5BASE641SALT SHA1SHA256TRUNC SHA1SHA1TRUNC SHA1SHA512TRUNC
    SHA1MD6TRUNC SHA1SHA1CAPTRUNC SHA1SHA1UCTRUNC SHA1SHA256TRUNCSALT
    SHA1SHA512UCTRUNC SHA1SALTSHA512UCTRUNC SHA1SALTSHA256UCTRUNC
    SHA1SHA384TRUNC SHA1RMD160TRUNC SHA1SHA1SHA1TRUNC SHA1SHA1TRUNCMD5
);

#-----------------------------------------------------------------------
# Parse Appendix A: "e286   MD5MD5USER   md5(md5(pass).user) (Note [24])"

my %hx;
open my $fh, '<', $appendix or die "$PROG: $appendix: $!\n";
while (my $line = <$fh>) {
    next unless $line =~ /^(e\d+)\s+(\S+)\s+(.+?)\s*$/;
    my ($idx, $name, $expr) = ($1, $2, $3);
    $expr =~ s/\s*\(Note \[\d+\]\)\s*//g;        # note citation
    $expr =~ s/\s*\([A-Z][^()]*\)\s*$//;          # trailing prose gloss
    $hx{$name} = { index => $idx, expr => $expr };
}
close $fh;
printf STDERR "- appendix: %d type(s)\n", scalar keys %hx;

#-----------------------------------------------------------------------
# Translate one hx expression into this repository's notation, or undef.

sub translate {
    my ($e) = @_;
    return undef unless defined $e && length $e;
    return undef if $e =~ /^\(/;              # "(complex: ...)"
    return undef if $e =~ /\bemit\b/;

    # hx binds a repeated subexpression: "h=md5(md5(pass)); md5(h . h)".
    # Inline it; the meaning is identical and this repository does not have
    # variables in the expression field.
    if ($e =~ /^\s*(\w+)\s*=\s*(.+?)\s*;\s*(.+)$/) {
        my ($var, $val, $body) = ($1, $2, $3);
        return undef if $val =~ /[;=]/;
        $body =~ s/\b\Q$var\E\b/$val/g;
        $e = $body;
    }
    return undef if $e =~ /[;=]/;

    $e =~ s/\s+//g;
    # operands
    $e =~ s/\bpass\b/\$p/g;
    $e =~ s/\bsalt\b/\$s/g;
    $e =~ s/\buser\b/\$s/g;

    # every function token must be known
    my @tok = $e =~ /([A-Za-z][A-Za-z0-9_]*)\s*\(/g;
    for my $t (@tok) { return undef unless exists $FUNC{$t} }
    $e =~ s/([A-Za-z][A-Za-z0-9_]*)\s*\(/$FUNC{$1}."("/ge;

    # must actually mention the password: a candidate that never uses $p is
    # the tokeniser having lost an operand, not an algorithm.
    return undef unless $e =~ /\$p/;
    return undef if $e =~ /[^A-Za-z0-9_\$\(\)\.,]/;   # no stray literals
    return $e;
}

#-----------------------------------------------------------------------

my ($seen, $written, %skip) = (0, 0);
opendir my $dh, $algdir or die "$PROG: $algdir: $!\n";
my @files = sort grep { /\.yaml$/ } readdir $dh;
closedir $dh;

# validate.pl fails a build where two entries claim the same expression without
# relation edges joining them, and that gate is the reason the expression is a
# key rather than a decoration. A transcription pass must not be what forces
# those edges into existence: deciding that two rows are the same computation,
# and WHY both still exist, is curation. CLAUDE.md is explicit that only a
# person writes `distinction: naming`. So a candidate whose expression another
# entry already claims is held back and reported, never written and related
# automatically.
my %claimed;
for my $f (@files) {
    my $e = eval { LoadFile("$algdir/$f") } or next;
    next unless $e->{id} && defined $e->{expression} && length $e->{expression};
    push @{ $claimed{ $e->{expression} } }, $e->{id};
}

for my $f (@files) {
    my $path = "$algdir/$f";
    my $e = eval { LoadFile($path) } or next;
    next unless $e->{id};
    next if ($e->{status} // '') eq 'merged';
    next if defined $e->{expression} && length $e->{expression};
    my $types = $e->{tools}{mdxfind}{types} or next;
    ref $types eq 'ARRAY' && @$types or next;

    $seen++;
    my ($type) = grep { $hx{$_} } @$types;
    unless ($type) { $skip{'type not in appendix'}++; next }
    if ($MULTI{$type}) { $skip{'multi-emit type'}++; next }

    my $expr = translate($hx{$type}{expr});
    unless (defined $expr) {
        $skip{'untranslatable token or form'}++;
        printf STDERR "  skip %-34s %-22s %s\n", $e->{id}, $type, $hx{$type}{expr}
            if $verbose > 1;
        next;
    }

    # Verify before writing, wherever that is possible at all. RosettaExpr
    # covers md5/sha1/sha256/sha512 constructions; anything else (haval, wrl,
    # cut, pad) cannot be checked here and is transcribed on upstream's word.
    # A candidate that CAN be checked and reproduces nothing is held back: the
    # check cannot tell "the expression is wrong" from "the vector is in the
    # tool's own encoding", and after ciscoasa the benefit of the doubt goes to
    # not writing. Those are reported for a human.
    my $confirmed = 0;
    if (my $fn = compile_expression($expr)) {
        my @v = grep { ($_->{source} // '') ne 'vanity' } @{ $e->{vectors} || [] };
        if (@v) {
            for my $v (@v) {
                my ($h, $salt) = split /:/, $v->{hash}, 2;
                my $got = eval { $fn->($v->{pass}, defined $salt ? $salt : '') };
                if (defined $got && lc($got) eq lc($h)) { $confirmed = 1; last }
            }
            unless ($confirmed) {
                $skip{'checkable but reproduces no vector'}++;
                printf STDERR "  HELD %-30s %-22s %s\n", $e->{id}, $type, $expr;
                next;
            }
        }
    }

    if (my $by = $claimed{$expr}) {
        $skip{'expression already claimed by another entry'}++;
        printf STDERR "  COLLIDES %-27s %-22s %s  (claimed by %s)\n",
            $e->{id}, $type, $expr, join(', ', @$by);
        next;
    }
    push @{ $claimed{$expr} }, $e->{id};   # and against each other within this run

    printf STDERR "+ %-34s %-22s %s%s\n", $e->{id}, $type, $expr,
        ($confirmed ? '   [confirmed on own vector]' : '') if $verbose;
    $written++;
    next unless $apply;

    # denotation: exists for entries that have NO expression, and validate.pl
    # fails a file carrying both. Where the sheet's looser wording said the
    # same thing -- "md5(base64_encode($plain))" against hx's "md5(base64($p))"
    # -- the expression supersedes it. Keep the old text inside the note so
    # nothing is lost, and record where it came from.
    my $retired = '';
    if (my $d = delete $e->{denotation}) {
        $retired = sprintf ' Superseded the denotation %s (source: %s), which validate.pl '
                 . 'forbids alongside an expression.',
                 (defined $d->{text} ? "\"$d->{text}\"" : '(none)'), ($d->{source} // 'unknown');
    }

    $e->{expression} = $expr;
    $e->{expression_proof} = {
        verified      => 'upstream',
        verified_at   => '2026-08-31',
        verified_with => 'hx Language Specification $Revision: 1.15$ (Waffle, Aug 2026), Appendix A',
        note          => "transcribed from the hx specification's Appendix A entry for mdxfind type "
                       . "$type ($hx{$type}{index}), which states $hx{$type}{expr}. Transcription, "
                       . "not reproduction, so this is upstream and not vector; run "
                       . "derive-expressions.pl to try to promote it. "
                       . ($confirmed
                          ? "An independent Digest:: computation of this string DOES reproduce this "
                          . "entry's own vector, checked 2026-08-31."
                          : "Not checkable locally: the construction uses functions RosettaExpr "
                          . "cannot compile, so this rests on upstream's word alone.") . $retired,
    };
    emit_entry($path, $e);
}

printf STDERR "\n%s: %d candidate entry/entries, %d %s\n",
    $PROG, $seen, $written, ($apply ? 'written' : 'would be written (no --apply)');
printf STDERR "  skipped %-32s %d\n", $_, $skip{$_} for sort keys %skip;
print  STDERR "  tiers are 'upstream'; now run derive-expressions.pl to promote\n" if $apply;
exit 0;
