#!/usr/bin/perl
#
# seed-hashcat-orphans.pl -- give every hashcat mode a findable row
#
# PURPOSE
#
# 306 of hashcat's 593 modes had no entry here at all. Someone arriving by a
# hashcat mode -- which is how most people arrive -- had a coin-flip chance of
# finding nothing. That is a direct failure of the first test in STATE.md:
# good enough to replace the spreadsheet.
#
# Royce decided 2026-08-31 that all of them get first-class entries, including
# the FDE, wallet, archive and document containers. That answers the scope
# question filed in STATE.md ("do hashcat's 101 FDE and 35 wallet modes get
# first-class entries?"), which had been deferred pending the john work.
#
# NOTHING IS WRITTEN THAT WAS NOT REPRODUCED
#
# hashcat publishes an example hash and its plaintext for almost every mode.
# That is a round-trip waiting to happen: run hashcat at that mode against its
# own example with a one-word wordlist, and either it recovers the plaintext or
# it does not. Only a mode that recovers gets tools.hashcat at tier `vector`.
# A mode that does not is REPORTED and skipped -- there is no lower tier used
# as a consolation, because "hashcat says it supports this" is already in
# data/tools/hashcat.yaml and copying it into a curated entry would launder an
# inventory line into a mapping.
#
# TWO ACTIONS, AND ATTACHING BEATS CREATING
#
# hashcat names many modes as the construction itself -- "md5(md5($pass.$salt))"
# -- so a mode can belong to a row this repository already has. --attach finds
# those by normalising the name to repo expression notation and matching
# expression:, then requires hashcat at that mode to crack THE EXISTING ENTRY'S
# OWN VECTOR before adding the mode. That last condition is what stops an
# expression collision (mode 4510 matches two entries) from putting a mode on
# the wrong row. Creating a duplicate entry for a computation already described
# would be the worst outcome available, so attaching is tried first and a mode
# that attaches is never also created.
#
# WHAT AN ENTRY GETS, AND WHAT IT DELIBERATELY DOES NOT
#
# id, name, category, status, tools.hashcat (tier vector), one vector, and for
# a name that is not expression-shaped a denotation: of hashcat's own label
# with source: "hashcat" -- the schema's literal case, "the label a suite or a
# standard uses (PBKDF2-HMAC-SHA256, 7-Zip)".
#
# It does NOT write expression:, john or mdxfind blocks. Those already have
# tools that do the job properly and are already trusted: derive-expressions.pl
# proves an expression through john's compiler, discover-john.pl finds a john
# format by cracking the entry's vector. Reimplementing either here would give
# this repository two answers to the same question, which is the drift the
# two-layer split exists to prevent. Run them after this.
#
# ids ARE FOREVER, so the slug is conservative
#
# `id` is the filename stem, a URL fragment and the dist/rosetta.csv key. The
# slug maps comparison operators to words, because hashcat distinguishes
# "Episerver 6.x < .NET 4" from ">= .NET 4" and from "iTunes backup < 10.0"
# from ">= 10.0", and stripping punctuation collapses each pair into one name
# for two different algorithms. Where a slug still collides -- mode 2630
# md5(md5($pass.$salt)) against the existing md5-md5-pass-salt, which is
# md5(md5($pass).$salt) and a DIFFERENT computation whose parenthesisation the
# slug cannot carry -- the mode number is appended rather than the difference
# being papered over.
#
# Usage: seed-hashcat-orphans.pl [--attach] [--apply] [--only MODE] [-v]
#
# Generated by Claude Opus 5 on 2026-08-31

use strict;
use warnings;
use FindBin qw($RealBin);
use lib "$RealBin/lib";
use Getopt::Long qw(GetOptions);
use File::Basename qw(basename);
use File::Path qw(make_path);
use YAML::XS qw(LoadFile);
use RosettaEmit qw(emit_entry);
use RosettaTools qw(tool_path tool_env_help);

my $PROG = basename($0);
my $ROOT = "$RealBin/..";

my $algdir  = "$ROOT/data/algorithms";
my $workdir = "$ROOT/tmp/orphans";
my $hashcat;
my ($apply, $attach, $verbose, $help, $dry) = (0,0,0,0,0);
my $timeout = 120;
my $limit   = 0;
my @only;
my $had_args = scalar @ARGV;

sub usage {
    print STDERR <<"USAGE";

Usage: $PROG [options]

   --hashcat PATH   hashcat binary   (default: @{[tool_env_help('hashcat')]})
   --algorithms DIR curated entries  (default: data/algorithms)
   --attach         add orphan modes to entries that ALREADY describe the
                    computation, instead of creating a new entry. Requires
                    hashcat at that mode to crack the existing entry's own
                    vector. Run this pass first.
   --only MODE      just this hashcat mode (repeatable)
   --limit N        stop after N modes attempted
   --timeout N      seconds per hashcat run (default 120; 217 of the orphans
                    are slow hashes and a few KDFs need most of it)
   --apply          write; without it, report only
   -n, --dry-run    decide ids and report, run no hashcat
   -v, --verbose    per-mode detail on stderr (repeatable)
   -h, --help       this help

   Only a mode whose own published example round-trips gets an entry.
   Exit 0 success, 1 error, 2 usage.

USAGE
    exit 2;
}

GetOptions(
    'hashcat=s'    => \$hashcat,
    'algorithms=s' => \$algdir,
    'attach'       => \$attach,
    'only=i'       => \@only,
    'limit=i'      => \$limit,
    'timeout=i'    => \$timeout,
    'apply'        => \$apply,
    'dry-run|n'    => \$dry,
    'verbose|v+'   => \$verbose,
    'help|h'       => \$help,
) or usage();
usage() if $help || !$had_args;
$hashcat //= tool_path('hashcat');
make_path($workdir) unless -d $workdir;
my %want_mode = map { $_ => 1 } @only;

#-----------------------------------------------------------------------
# hashcat category -> this repository's category axis. hashcat groups by
# PRODUCT, this repository by what the row IS, so the mapping is lossy on
# purpose: everything that is a product's use of a construction is
# `application`, which is exactly what that value means here.

my %CATEGORY = (
    'Raw Hash'                              => 'primitive',
    'Raw Hash salted and/or iterated'       => 'composite',
    'Raw Hash authenticated'                => 'composite',
    'Raw Checksum'                          => 'primitive',
    'Raw Cipher, Known-plaintext attack'    => 'primitive',
    'Generic KDF'                           => 'kdf',
    'Network Protocol'                      => 'protocol',
    'Operating System'                      => 'application',
    'Database Server'                       => 'application',
    'FTP, HTTP, SMTP, LDAP Server'          => 'application',
    'Enterprise Application Software (EAS)' => 'application',
    'Full-Disk Encryption (FDE)'            => 'application',
    'File-Based Encryption (FBE)'           => 'application',
    'Document'                              => 'application',
    'Password Manager'                      => 'application',
    'Archive'                               => 'application',
    'Forums, CMS, E-Commerce'               => 'application',
    'One-Time Password'                     => 'protocol',
    'Instant Messaging Service'             => 'application',
    'Cryptocurrency Wallet'                 => 'application',
    'Private Key'                           => 'application',
    'Framework'                             => 'application',
    'Application Database'                  => 'application',
    'Plaintext'                             => 'encoding',
);

#-----------------------------------------------------------------------
# slug($name) - hashcat's mode name to an id.

sub slug {
    my ($n) = @_;
    my $s = lc $n;
    # comparison operators carry the whole distinction between two modes
    $s =~ s/>=/ ge /g; $s =~ s/<=/ le /g;
    $s =~ s/>/ gt /g;  $s =~ s/</ lt /g;
    $s =~ s/\$//g;                       # $pass -> pass
    $s =~ s/[^a-z0-9]+/-/g;
    $s =~ s/^-+|-+$//g;
    return $s;
}

# hashcat's name in this repository's expression notation, or undef.
sub to_expr {
    my ($n) = @_;
    return undef unless defined $n && $n =~ /^[a-z][a-z0-9_]*\(.*\)$/;
    my $s = $n;
    $s =~ s/\s+//g;
    $s =~ s/\$pass\b/\$p/g;
    $s =~ s/\$salt\b/\$s/g;
    $s =~ s/\$user\b/\$u/g;
    return $s;
}

#-----------------------------------------------------------------------

sub run_capture {
    my ($secs, @cmd) = @_;
    my $out = '';
    my $pid = open my $fh, '-|';
    die "$PROG: fork: $!\n" unless defined $pid;
    unless ($pid) {                                    # child
        open STDERR, '>', '/dev/null';
        exec @cmd or exit 127;
    }
    my $code = 0;
    eval {
        local $SIG{ALRM} = sub { kill 'KILL', $pid; die "timeout\n" };
        alarm $secs;
        local $/;
        $out = <$fh> // '';
        alarm 0;
    };
    if ($@) { $code = -2 }
    close $fh;
    waitpid $pid, 0;
    return ($code, $out);
}

sub write_file {
    my ($path, @lines) = @_;
    open my $fh, '>', $path or die "$PROG: $path: $!\n";
    print $fh "$_\n" for @lines;
    close $fh;
    return $path;
}

# hashcat_cracks($mode, $hash, $pass, $deprecated) - the round-trip.
sub hashcat_cracks {
    my ($mode, $hash, $pass, $dep) = @_;
    my $hf = write_file("$workdir/m$mode.hash", $hash);
    my $wf = write_file("$workdir/m$mode.word", $pass);
    my @cmd = ($hashcat, '-m', $mode, '-a', '0', '--quiet', '--potfile-disable',
               '--self-test-disable', '--backend-ignore-opencl');
    push @cmd, '--deprecated-check-disable' if $dep;
    my ($code, $out) = run_capture($timeout, @cmd, $hf, $wf);
    return (0, 'timeout') if $code == -2;
    # hashcat prints "<hash>:<plain>". Require BOTH, so a mode that emits the
    # hash for another reason is not read as a crack.
    return (1, '') if index($out, $hash) >= 0 && $out =~ /\Q$hash\E:\Q$pass\E\s*$/m;
    return (0, 'no crack');
}

#-----------------------------------------------------------------------
# Load the corpus.

opendir my $dh, $algdir or die "$PROG: $algdir: $!\n";
my @files = sort grep { /\.yaml$/ } readdir $dh;
closedir $dh;

my (%taken, %claimed, %by_expr, %entry_of);
for my $f (@files) {
    my $e = eval { LoadFile("$algdir/$f") } or next;
    next unless $e->{id};
    $taken{ $e->{id} } = 1;
    next if ($e->{status}//'') eq 'merged';
    $entry_of{ $e->{id} } = { path => "$algdir/$f", data => $e };
    push @{ $by_expr{ $e->{expression} } }, $e->{id}
        if defined $e->{expression} && length $e->{expression};
    my $m = $e->{tools}{hashcat}{modes};
    $claimed{$_} = 1 for (ref $m eq 'ARRAY' ? @$m : ());
}

my $inv = LoadFile("$ROOT/data/tools/hashcat.yaml");
my $HCVER = $inv->{version} // 'hashcat';

my @orphans = grep { !$claimed{ $_->{mode} } } @{ $inv->{modes} };
@orphans = grep { $want_mode{ $_->{mode} } } @orphans if @only;
printf STDERR "- %d orphan mode(s)%s\n", scalar @orphans,
    (@only ? ' (filtered by --only)' : '');

my ($tried, $ok, $failed, $wrote, $attached, %why) = (0,0,0,0,0);
my %used;

for my $m (@orphans) {
    last if $limit && $tried >= $limit;
    my $mode = $m->{mode};
    my $ex   = $m->{example_hash} // '';
    my $pw   = $m->{example_pass} // '';

    unless (length $ex && length $pw && $ex !~ /Truncated/) {
        $why{'no usable example hash or plaintext'}++;
        printf STDERR "  skip  %-7d %s\n", $mode, $m->{name} if $verbose;
        next;
    }

    #-- attach: does an entry already describe this computation? ----------
    my $expr = to_expr($m->{name});
    if ($attach && $expr && $by_expr{$expr}) {
        my @cand = @{ $by_expr{$expr} };
        my $landed;
        for my $id (@cand) {
            my $ent = $entry_of{$id} or next;
            my @v = @{ $ent->{data}{vectors} || [] } or next;
            # the entry's OWN vector must fall at this mode, which is what
            # separates the right row from a row that merely shares the string
            next if $dry;
            my ($got) = hashcat_cracks($mode, $v[0]{hash}, $v[0]{pass},
                                       $m->{deprecated});
            next unless $got;
            $landed = $id;
            last;
        }
        $tried++;
        if ($dry) {
            printf STDERR "ATTACH? %-7d %-34s -> %s\n", $mode, $expr,
                join(',', @cand);
            next;
        }
        if ($landed) {
            $attached++;
            printf STDERR "ATTACH  %-7d %-34s -> %s\n", $mode, $expr, $landed;
            next unless $apply;
            my $ent = $entry_of{$landed};
            my $hc  = $ent->{data}{tools}{hashcat} ||= {};
            push @{ $hc->{modes} }, $mode;
            @{ $hc->{modes} } = sort { $a <=> $b } @{ $hc->{modes} };
            $hc->{verified}      = 'vector';
            $hc->{verified_at}   = '2026-08-31';
            $hc->{verified_with} = "hashcat $HCVER";
            $hc->{note} = "mode $mode added 2026-08-31 by seed-hashcat-orphans.pl: "
                        . "hashcat names it \"$m->{name}\", which is this entry's own "
                        . "expression, and hashcat at that mode recovers this entry's "
                        . "own vector. It had no entry at all before.";
            emit_entry($ent->{path}, $ent->{data});
            $claimed{$mode} = 1;
            next;
        }
        printf STDERR "  no-attach %-7d %-30s (expression matched %s, vector did not)\n",
            $mode, $expr, join(',', @cand) if $verbose;
        # fall through and create a row of its own
    }
    next if $attach;          # --attach does only that

    #-- create ------------------------------------------------------------
    $tried++;
    my ($cracked, $err) = $dry ? (1, '')
                               : hashcat_cracks($mode, $ex, $pw, $m->{deprecated});
    unless ($cracked) {
        $failed++;
        $why{"example did not round-trip: $err"}++;
        printf STDERR "  FAIL  %-7d %-34s %s\n", $mode, $m->{name}, $err;
        next;
    }
    $ok++;

    my $id = slug($m->{name});
    $id = "mode-$mode" unless length $id;
    if ($taken{$id} || $used{$id}) {
        $id .= "-hc$mode";
        printf STDERR "  id collision -> %s\n", $id if $verbose;
    }
    $used{$id} = 1;

    my $entry = {
        id     => $id,
        name   => $m->{name},
        status => 'needs-review',
        tools  => {
            hashcat => {
                modes         => [ $mode ],
                verified      => 'vector',
                verified_at   => '2026-08-31',
                verified_with => "hashcat $HCVER",
                note          => "hashcat's own published example hash for this mode, "
                               . "recovered by hashcat at this mode with hashcat's own "
                               . "published plaintext.",
            },
            crack => { supported => 0 },
        },
        vectors => [ { hash => $ex, pass => $pw, source => 'hashcat' } ],
    };
    $entry->{category} = $CATEGORY{ $m->{category} }
        if exists $CATEGORY{ $m->{category} };

    # A name that is not expression-shaped is a LABEL, which is precisely what
    # denotation: is for. One that IS expression-shaped is left alone, so that
    # derive-expressions.pl can try to PROVE it -- writing a denotation here
    # would foreclose that, because validate.pl forbids both on one entry.
    unless (to_expr($m->{name})) {
        # WHY there is no expression differs, and saying the wrong one is a
        # false statement about the algorithm. A Raw Hash / Checksum / KDF mode
        # whose name is a label -- Keccak-256, CRC32, PBKDF2-HMAC-SHA256 -- IS
        # a bare construction; john's dynamic language simply has no token for
        # it. A container is a different thing entirely.
        my $bare = ($m->{category} // '') =~ /^(Raw Hash|Raw Checksum|Raw Cipher|Generic KDF)/;
        $entry->{denotation} = {
            text   => $m->{name},
            source => 'hashcat',
            note   => "hashcat's own label for mode $mode, category "
                    . "\"$m->{category}\", in $HCVER."
                    . ($bare ? "" : " This is a container or application format "
                             . "rather than a bare construction, so there is no "
                             . "single digest expression to record."),
        };
        $entry->{expression_proof} = {
            verified      => 'absent',
            verified_at   => '2026-08-31',
            verified_with => "hashcat $HCVER",
            note          => $bare
                ? "hashcat mode $mode is \"$m->{name}\" ($m->{category}). It is a "
                . "bare construction, but john's dynamic EXPRESSION language has no "
                . "token for it, so it cannot be written as an expression here. That "
                . "says nothing about whether john can CRACK it -- run "
                . "discover-john.pl, and if john has a format it goes in tools.john."
                : "hashcat mode $mode is a $m->{category} format. john's dynamic "
                . "expression language describes constructions over a password and a "
                . "salt; it cannot express a container's KDF-plus-cipher, so this has "
                . "no expression and will not acquire one. That says nothing about "
                . "whether john can CRACK it -- run discover-john.pl, and if john has "
                . "a format it goes in tools.john.",
        };
    }

    printf STDERR "+ %-7d %-38s %s\n", $mode, $id, $m->{name} if $verbose;
    $wrote++;
    next unless $apply;
    emit_entry("$algdir/$id.yaml", $entry);
    $taken{$id} = 1;
}

printf STDERR "\n%s: %d mode(s) attempted, %d round-tripped, %d failed, %d %s, %d attached\n",
    $PROG, $tried, $ok, $failed, $wrote,
    ($apply ? 'entries written' : 'entries would be written (no --apply)'), $attached;
printf STDERR "  %-52s %d\n", $_, $why{$_} for sort keys %why;
print  STDERR "  now run: derive-expressions.pl --apply, then discover-john.pl --apply\n"
    if $apply && $wrote;
exit 0;
