#!/usr/bin/perl
#
# seed-vectors.pl -- give an entry that has no test vector one that the tool
# publishing it actually reproduces.
#
# WHY THIS EXISTS
#
# Nothing in this repository can be proven about an entry with no vector: every
# tier above 'asserted' is a round-trip, and a round-trip needs a hash and a
# plaintext to run. 78 entries have neither. Meanwhile both generated
# inventories have carried an example the whole time and nothing has ever read
# it -- data/tools/mdxfind.yaml has example_vector/example_pass for 969 of its
# 1001 types, data/tools/hashcat.yaml has example_hash/example_pass for 592 of
# 593 modes. This pass reads them.
#
# These are upstream-published vectors, not ones we computed, so they are
# evidence in the sense gotchas 26 and 27 mean: a hash we generated ourselves
# with `mdxfind -z` could never promote mdxfind, but the example mdxfind ships
# for a type is the project's own statement about that type. Filling a gap this
# way is exactly what those gotchas permit; replacing an existing vector is not,
# so an entry that already carries one is never touched.
#
# WHY IT VERIFIES BEFORE IT WRITES
#
# A vector seeded and not re-proven is how 42 entries reached tier 'vector' on
# the wrong digest (see audit-iterations.pl). So a candidate is stored only if
# the tool that published it reproduces it under the identifier AND the
# iteration count THIS entry declares -- which is a real test, because the
# inventory's example belongs to the type, and the entry's claim to that type
# is precisely what has never been checked. A candidate that fails is reported
# and not written: it is evidence the entry's type, mode or iteration count is
# wrong, and that is worth a human's attention rather than a file write.
#
# This tool NEVER touches a `verified:` tier. verify-vectors.pl owns tiers, and
# keeping promotion in one place is what stops a seed pass from quietly
# promoting its own seed. Run it afterwards -- the closing report says how.
#
# SOURCE PREFERENCE
#
# mdxfind's example where the entry names a type that has one, hashcat's
# otherwise. mdxfind reaches 70 of the 78 and its example is already stored in
# the shape entries use ("<hash>[:<salt-or-user>]", plaintext separate).
#
# TWO TARGETS
#
# By default: entries with no vectors at all. With --fill: entries that DO have
# a vector, but whose tool block names an identifier and sits below tier
# 'vector' -- 45 hashcat blocks and 27 mdxfind blocks, mostly container and KDF
# formats whose recorded vector is in the other tool's encoding. The published
# example is added ALONGSIDE what is there, never over it (gotcha 27: a vector
# from hashcat is evidence about hashcat, and replacing an independently
# sourced one throws that provenance away). A block already at tier 'vector'
# is left alone: it has nothing to gain, and an extra vector is not free --
# derive-expressions.pl requires EVERY vector of an entry to fall before it
# will write an expression.
#
# DEPENDENCIES: YAML::XS, tools/lib/RosettaEmit.pm, and the crackers named in
# --mdxfind / --hashcat. Run from anywhere; paths resolve against the repo.
#
# Generated by Claude Opus 5 on 2026-08-30

use strict;
use warnings;
use FindBin qw($RealBin);
use lib "$RealBin/lib";
use YAML::XS ();
use Getopt::Long qw(GetOptions);
use File::Path qw(make_path);
use File::Basename qw(basename);
use POSIX qw(strftime);
use Time::HiRes qw(time);
use RosettaEmit qw(emit_entry);

my $PROG = basename($0);
my $ROOT = "$RealBin/..";

sub usage {
    print <<"USAGE";
Usage: $PROG --report | --apply | -n [options]

   --report          verify every candidate, print the result, write nothing
   --apply           verify every candidate, write the ones that verified
   -n, --dry-run     list the candidates; run no cracker, write nothing

   --fill            target entries that HAVE a vector but whose tool block
                     is below tier 'vector', adding the published example
                     alongside; without it, only entries with no vector at all
   --tool NAME       restrict to 'mdxfind' or 'hashcat' (repeatable)
   --only ID         just this entry (repeatable)
   --limit N         stop after N candidates; for smoke tests
   --mdxfind PATH    mdxfind binary  (default: /usr/local/bin/mdxfind)
   --hashcat PATH    hashcat binary  (default: /usr/local/bin/hashcat)
   --algorithms DIR  curated entries (default: data/algorithms)
   --work DIR        scratch files   (default: tmp/seed-vectors)
   --timeout SECS    per invocation  (default: 120)
   -v, --verbose     per-candidate progress on stderr (repeatable)
   -h, --help        this help

   A vector is written only when the tool that published it reproduces it
   under the identifier and iteration count the entry declares, and only ever
   in addition to what the entry already carries. Tiers are never touched --
   run verify-vectors.pl afterwards to promote what this makes provable.

   Exit 0 success, 1 error, 2 usage.
USAGE
}

my (@tools, @only, $report, $apply, $dry, $fill, $limit, $verbose, $help);
my ($mdxfind, $hashcat, $algdir, $workdir, $timeout);
GetOptions(
    'report'       => \$report,
    'apply'        => \$apply,
    'n|dry-run'    => \$dry,
    'fill'         => \$fill,
    'tool=s'       => \@tools,
    'only=s'       => \@only,
    'limit=i'      => \$limit,
    'mdxfind=s'    => \$mdxfind,
    'hashcat=s'    => \$hashcat,
    'algorithms=s' => \$algdir,
    'work=s'       => \$workdir,
    'timeout=i'    => \$timeout,
    'v|verbose+'   => \$verbose,
    'h|help'       => \$help,
) or do { usage(); exit 2 };

if ($help) { usage(); exit 0 }

# House convention: no arguments means "tell me how to use this", never
# "start doing something".
unless ($report || $apply || $dry) { usage(); exit 2 }
if (($report ? 1 : 0) + ($apply ? 1 : 0) + ($dry ? 1 : 0) > 1) {
    print STDERR "$PROG: choose exactly one of --report, --apply, -n\n";
    exit 2;
}

$mdxfind //= '/usr/local/bin/mdxfind';
$hashcat //= '/usr/local/bin/hashcat';
$algdir  //= "$ROOT/data/algorithms";
$workdir //= "$ROOT/tmp/seed-vectors";
$timeout //= 120;
$verbose //= 0;

@tools = qw(mdxfind hashcat) unless @tools;
my %want = map { $_ => 1 } @tools;
for my $t (@tools) {
    next if $t eq 'mdxfind' || $t eq 'hashcat';
    print STDERR "$PROG: unknown tool '$t'\n";
    exit 2;
}
my %only = map { $_ => 1 } @only;

make_path($workdir) unless -d $workdir;

#-----------------------------------------------------------------------
# Inventories.

sub load_yaml {
    my ($path) = @_;
    my $d = eval { YAML::XS::LoadFile($path) };
    unless ($d) { print STDERR "$PROG: cannot load $path: $@\n"; exit 1 }
    return $d;
}

my $mx_inv = load_yaml("$ROOT/data/tools/mdxfind.yaml");
my $hc_inv = load_yaml("$ROOT/data/tools/hashcat.yaml");

# Types are matched case-insensitively: john is inconsistent about case and the
# sheet was too, so the corpus is not guaranteed to spell a type as mdxfind
# does. The tool's own spelling is what gets handed to -h.
my (%mx_by_name, %mx_salted);
for my $t (@{ $mx_inv->{types} }) {
    $mx_by_name{ uc $t->{name} } = $t;
    # 's' is a salt carried in the hash line, 'u' a userid carried the same
    # way (mdxfind's HMAC types take their key like that). Both need -F.
    $mx_salted{ uc $t->{name} } = 1
        if grep { $_ eq 's' || $_ eq 'u' } @{ $t->{flags} || [] };
}
my %hc_by_mode = map { $_->{mode} => $_ } @{ $hc_inv->{modes} };

#-----------------------------------------------------------------------
# Entries with no vector at all.

opendir(my $dh, $algdir) or do { print STDERR "$PROG: cannot read $algdir: $!\n"; exit 1 };
my @files = sort grep { /\.yaml$/ } readdir $dh;
closedir $dh;

my (@cand, @noscore);
my $targets = 0;

for my $f (@files) {
    my $path = "$algdir/$f";
    my $e    = load_yaml($path);
    my $id   = $e->{id} // ($f =~ s/\.yaml$//r);
    next if %only && !$only{$id};

    my $has_vectors = ($e->{vectors} && @{ $e->{vectors} }) ? 1 : 0;
    next if $fill ? !$has_vectors : $has_vectors;

    if ($fill) {
        # A block stands to gain only if it names an identifier and has not
        # already reached tier 'vector'. Everything else is not a target, and
        # counting it as one would drown the report.
        my %below = map { $_ => 1 }
            grep { my $b = $e->{tools}{$_} || {};
                   ($b->{ $_ eq 'mdxfind' ? 'types' : 'modes' } || [])->[0]
                   && ($b->{verified} // '') ne 'vector' }
            qw(mdxfind hashcat);
        next unless %below;
        $targets++;

        # Only a vector the entry does not already carry -- re-adding hashcat's
        # own example under a block that already proved on it would be noise,
        # not evidence.
        my %have = map { ($_->{hash} // '') . "\0" . ($_->{pass} // '') => 1 }
                   @{ $e->{vectors} };
        my @c = grep { $below{ $_->{tool} } && !$have{ "$_->{hash}\0$_->{pass}" } }
                candidates($e, $id, $path);
        push @cand, @c;
        push @noscore, $id unless @c;
    }
    else {
        $targets++;
        # One entry, one vector: the preference order in candidates() decides.
        my @c = candidates($e, $id, $path);
        if (@c) { push @cand, $c[0] }
        else    { push @noscore, $id }
    }
}

# candidates($entry, $id, $path) - at most one published example per tool,
# mdxfind first, in the order a caller that wants only one should prefer them.
#
# mdxfind leads because it reaches most entries and its example_vector is
# already the shape the corpus stores. example_vector is "<hash>[:<extra>]:<pass>"
# and example_pass is that tail exactly, so the stored hash is the string with
# ":<pass>" removed -- computed by stripping, never by splitting on ':', because
# a salt may itself contain colons.
sub candidates {
    my ($e, $id, $path) = @_;
    my @out;

    if ($want{mdxfind}) {
        for my $name (@{ $e->{tools}{mdxfind}{types} || [] }) {
            my $t = $mx_by_name{ uc $name } or next;
            my ($ev, $ep) = ($t->{example_vector}, $t->{example_pass});
            next unless defined $ev && defined $ep && length $ep;
            my $suffix = ":$ep";
            # Shape guard: an example that does not end in its own plaintext is
            # not the shape documented above, and guessing at it is how a wrong
            # vector gets stored.
            next unless length($ev) > length($suffix)
                     && substr($ev, -length($suffix)) eq $suffix;
            push @out, {
                id     => $id,  path => $path, entry => $e,
                tool   => 'mdxfind',
                ident  => $t->{name},
                salted => ($mx_salted{ uc $name } ? 1 : 0),
                iter   => ($e->{tools}{mdxfind}{iterations} // 1),
                hash   => substr($ev, 0, length($ev) - length($suffix)),
                pass   => $ep,
            };
            last;
        }
    }

    if ($want{hashcat}) {
        for my $mode (sort { $a <=> $b } @{ $e->{tools}{hashcat}{modes} || [] }) {
            my $m = $hc_by_mode{$mode} or next;
            my ($eh, $ep) = ($m->{example_hash}, $m->{example_pass});
            next unless defined $eh && defined $ep;
            # A hex-encoded example is a binary file rendered as hex, not a hash
            # line; storing it would put something in vectors: that no recipe in
            # CLAUDE.md can feed back to a tool.
            next unless ($m->{example_hash_format} // '') eq 'plain';
            push @out, {
                id    => $id, path => $path, entry => $e,
                tool  => 'hashcat',
                ident => $mode,
                iter  => 1,
                hash  => $eh,
                pass  => $ep,
            };
            last;
        }
    }

    return @out;
}

#-----------------------------------------------------------------------
# Verification. One pinned invocation per candidate: mdxfind reports the FIRST
# internal type that reproduces a digest, so an unpinned run would credit a
# broader type (CLAUDE.md, "Type masking").

sub run_capture {
    my ($secs, @argv) = @_;
    my $out = '';
    my $pid = open(my $fh, '-|');
    defined $pid or return (-1, '');
    if (!$pid) {
        open STDERR, '>&', \*STDOUT;
        exec { $argv[0] } @argv or exit 127;
    }
    my $killed = 0;
    eval {
        local $SIG{ALRM} = sub { $killed = 1; kill 'KILL', $pid; die "timeout\n" };
        alarm $secs;
        local $/;                        # slurp: $/ is the input record separator
        $out = <$fh> // '';
        alarm 0;
    };
    alarm 0;
    close $fh;
    return ($killed ? -2 : ($? >> 8), $out);
}

sub write_file {
    my ($path, @lines) = @_;
    open my $fh, '>', $path or die "$PROG: cannot write $path: $!\n";
    print {$fh} "$_\n" for @lines;
    close $fh;
    return $path;
}

# verify($c) - does the publishing tool reproduce this candidate, under the
# identifier and iteration count the entry declares? Returns (ok, reason).
sub verify {
    my ($c) = @_;
    (my $safe = "$c->{tool}.$c->{ident}") =~ s/[^A-Za-z0-9._-]/_/g;
    my $hf = write_file("$workdir/$safe.hash", $c->{hash});
    my $wf = write_file("$workdir/$safe.word", $c->{pass});

    if ($c->{tool} eq 'mdxfind') {
        # -F for a salted or userid-bearing type: the salt rides in the line.
        my $readflag = $c->{salted} ? '-F' : '-f';
        my ($code, $out) = run_capture($timeout, $mdxfind,
            '-h', "^\Q$c->{ident}\E\$", $readflag, $hf, '-i', $c->{iter}, $wf);
        return (0, 'timeout') if $code == -2;
        for my $line (split /\n/, $out) {
            # "TYPExNN <hash>:<plain>". The iteration suffix is part of the
            # identity -- a vector that falls at x01 does not verify an entry
            # declaring x02 -- so it is compared, not stripped.
            next unless $line =~ /^\Q$c->{ident}\E(?:x(\d+))?\s+(.+)$/;
            my $got = defined $1 ? $1 + 0 : $c->{iter};
            next unless $got == $c->{iter};
            return (1, '') if $2 eq "$c->{hash}:$c->{pass}";
        }
        return (0, 'not reproduced');
    }

    my ($code, $out) = run_capture($timeout, $hashcat,
        '-m', $c->{ident}, '-a', '0', '--quiet', '--potfile-disable',
        '--self-test-disable', '--backend-ignore-opencl', $hf, $wf);
    return (0, 'timeout') if $code == -2;
    # hashcat echoes "<hash>:<plain>"; match on the hash it was given.
    return (1, '') if $out =~ /^\Q$c->{hash}\E:/m;
    return (0, 'not cracked');
}

#-----------------------------------------------------------------------
# Run.

my $started = time;
my $today   = strftime('%Y-%m-%d', localtime);
my (@ok, @bad);
my $n = 0;

printf "# %s -- %d target entr%s (%s); %d candidate(s), %d with nothing to offer\n",
    $PROG, $targets, ($targets == 1 ? 'y' : 'ies'),
    ($fill ? 'have a vector, a tool block below tier vector' : 'no vector at all'),
    scalar @cand, scalar @noscore;
print "# columns: result, entry, tool, identifier, hash, pass\n";

for my $c (@cand) {
    last if $limit && $n >= $limit;
    $n++;

    if ($dry) {
        printf "PLAN\t%s\t%s\t%s\t%s\t%s\n",
            $c->{id}, $c->{tool}, $c->{ident}, $c->{hash}, $c->{pass};
        next;
    }

    my ($ok, $why) = verify($c);
    printf STDERR "-   %-40s %-7s %-28s %s\n",
        $c->{id}, $c->{tool}, $c->{ident}, ($ok ? 'verified' : "FAILED ($why)")
        if $verbose;

    if ($ok) {
        push @ok, $c;
        printf "OK\t%s\t%s\t%s\t%s\t%s\n",
            $c->{id}, $c->{tool}, $c->{ident}, $c->{hash}, $c->{pass};
    }
    else {
        push @bad, [$c, $why];
        printf "FAIL\t%s\t%s\t%s\t%s\t%s\t%s\n",
            $c->{id}, $c->{tool}, $c->{ident}, $c->{hash}, $c->{pass}, $why;
    }
}

print "SKIP\t$_\t-\t-\t-\t-\tno published example\n" for @noscore;

#-----------------------------------------------------------------------
# Write. Only the verified ones, and only under --apply.

my $written = 0;
if ($apply) {
    # Append, never replace: an entry can collect a candidate from each tool in
    # --fill, and what it already carries is provenance we do not own.
    my %touched;
    for my $c (@ok) {
        my $e = $c->{entry};
        push @{ $e->{vectors} }, {
            hash   => $c->{hash},
            pass   => $c->{pass},
            source => $c->{tool},
        };
        $touched{ $c->{path} } = $e;
    }
    $written += emit_entry($_, $touched{$_}) for sort keys %touched;
}

my $elapsed = time - $started;
printf STDERR "%s: %d candidate(s) examined, %d verified, %d failed, %d file(s) written in %.1fs\n",
    $PROG, $n, scalar @ok, scalar @bad, $written, $elapsed;

if (@bad) {
    printf STDERR "%s: a failed candidate is evidence the entry's identifier or iteration count is wrong -- review the FAIL rows.\n", $PROG;
}
if ($apply && $written) {
    printf STDERR "%s: tiers untouched. Promote what is now provable with:\n    ./tools/verify-vectors.pl --tool all -v\n", $PROG;
}

exit 0;
