#!/usr/bin/perl
#
# seed-john-vectors.pl -- give an entry that has no test vector one that john
# itself publishes, and prove it by cracking it.
#
# WHY THIS EXISTS
#
# 54 entries carry no vector at all, so nothing about them can ever reach tier
# 'vector' for ANY tool: every tier above 'asserted' is a round-trip and a
# round-trip needs a hash and a plaintext. seed-vectors.pl already reads the
# published example out of data/tools/mdxfind.yaml and data/tools/hashcat.yaml.
# It cannot reach these, and CLAUDE.md says why: john's --list=format-details
# TRUNCATES example_ciphertext at 896 characters with no marker at all, and
# every container format's example is a whole volume header, so the extractor
# that built data/tools/john.yaml never saw a loadable hash for them.
#
# john's own source does carry them, in full:
#
#   route 1  static struct fmt_tests <name>[] in src/*.c, entries of the shape
#            { "<ciphertext>", "<plaintext>" }.  28 of the 54.
#   route 2  Test= lines in run/dynamic.conf, "<ciphertext>:<plaintext>[:<login>]",
#            for the config-defined dynamics that have no C file.  8 of the 54.
#
# WHY THE SOURCE IS NOT THE PROOF
#
# CLAUDE.md's rule for exactly this: the source PROPOSES and john's crack
# PROVES. So every candidate harvested here is handed back to john under the
# label THIS entry names, against a wordlist holding nothing but the candidate
# plaintext, and is stored only if john recovers it. A test array is evidence
# about the array; it is not evidence that this entry's john label is the one
# that computes it, and that second claim is the whole reason the entry exists.
#
# One hash and one word per invocation, so `--show`'s own "N password hash(es)
# cracked" is the signal. That sidesteps two recorded traps at once: --show
# does not always put the plaintext last (it re-inserts a login into the
# original line structure instead), and a field-wise match on a common
# plaintext can coincide. With a single-line hash file and a single-word
# wordlist there is only one thing john can have cracked.
#
# WHY IT REFUSES A CANDIDATE THAT NEEDS A LOGIN FIELD
#
# A vector stored here has to be re-provable by verify-vectors.pl, which writes
# a SYNTHETIC login before every hash. So a ciphertext that only cracks when a
# particular login sits beside it would verify once here and never again. Where
# the source line carries a login, this tool transcodes it into john's own
# self-contained spelling -- ciphertext . '$$U' . login, which dynamic_1401's
# own Test= lines demonstrate upstream -- and proves THAT string under a
# synthetic login. A wrong transcode fails to load or fails to crack, which is
# the standard CLAUDE.md requires of a transcode. Nothing is stored otherwise.
#
# WHY TWO READING SCHEMES
#
# --field-separator-char governs READING, not just printing, so the tab scheme
# cannot work for a format whose ciphertext EMBEDS its own login: NETLM,
# NetHalfLM, MSCHAPv2 and NetNTLM all put USER::DOMAIN: at the front, and
# displacing that field is exactly what breaks the parse. Such a format is
# handed the bare line natively instead. The tab scheme is tried first because
# it is the one verify-vectors.pl uses, so a candidate that only passes
# natively is reported as such.
#
# WHAT IT NEVER DOES
#
# It never touches a `verified:` tier -- verify-vectors.pl owns those, and
# keeping promotion in one place is what stops a seed pass from promoting its
# own seed. It never replaces a vector an entry already carries.
#
# DEPENDENCIES: YAML::XS, tools/lib/RosettaEmit.pm, a jumbo john binary and a
# readable john source tree. Run from anywhere; paths resolve against the repo.
#
# Generated by Claude Opus 5 on 2026-09-04

use strict;
use warnings;
use FindBin qw($RealBin);
use lib "$RealBin/lib";
use YAML::XS ();
use Getopt::Long qw(GetOptions);
use File::Path qw(make_path);
use File::Basename qw(basename dirname);
use Time::HiRes qw(time);
use RosettaEmit qw(emit_entry);
use RosettaTools qw(tool_path tool_env_help);

my $PROG = basename($0);
my $ROOT = "$RealBin/..";

sub usage {
    print <<"USAGE";
Usage: $PROG --report | --apply | -n [options]

   --report          harvest, verify with john, print the result, write nothing
   --apply           harvest, verify, write the vectors that john reproduced
   -n, --dry-run     list the harvested candidates; run john not at all

   --only ID         just this entry (repeatable)
   --limit N         stop after N candidates; for smoke tests
   --john PATH       john binary        (@{[ tool_env_help('john') ]})
   --src DIR         john source tree   (default: <john>/../src)
   --conf PATH       dynamic.conf       (default: <john>/dynamic.conf)
   --algorithms DIR  curated entries    (default: data/algorithms)
   --work DIR        scratch files      (default: tmp/seed-john-vectors)
   --timeout SECS    per invocation     (default: 120)
   -v, --verbose     per-candidate progress on stderr (repeatable)
   -h, --help        this help

   Only entries with NO vector at all are targeted, and only those naming a
   john format label or dynamic this tool can find an example for. A candidate
   is stored only when john, given that label and a wordlist holding nothing
   but the candidate plaintext, recovers it. Tiers are never touched -- run
   verify-vectors.pl afterwards to promote what this makes provable.

   Exit 0 success, 1 error, 2 usage.
USAGE
}

my ($report, $apply, $dry, $john, $src, $conf, $algdir, $workdir, $timeout);
my (@only, $help, $limit);
my $verbose = 0;
$timeout = 120;
GetOptions(
    'report'       => \$report,
    'apply'        => \$apply,
    'n|dry-run'    => \$dry,
    'only=s'       => \@only,
    'limit=i'      => \$limit,
    'john=s'       => \$john,
    'src=s'        => \$src,
    'conf=s'       => \$conf,
    'algorithms=s' => \$algdir,
    'work=s'       => \$workdir,
    'timeout=i'    => \$timeout,
    'v|verbose+'   => \$verbose,
    'h|help'       => \$help,
) or do { usage(); exit 2 };

if ($help) { usage(); exit 0 }
unless ($report || $apply || $dry) { usage(); exit 2 }

$john    = tool_path('john', $john);
my $jdir = dirname($john);
$src   //= "$jdir/../src";
$conf  //= "$jdir/dynamic.conf";
$algdir  //= "$ROOT/data/algorithms";
$workdir //= "$ROOT/tmp/seed-john-vectors";
make_path($workdir) unless -d $workdir;
my %only = map { $_ => 1 } @only;

#-----------------------------------------------------------------------
# C string evaluation.
#
# A test entry's ciphertext is not always a bare literal: john writes
# {FORMAT_TAG "ce85b9..."} and relies on the preprocessor. So a literal is a
# SEQUENCE of tokens, each either a string literal or a macro that expands to
# one, and an unknown token makes the whole candidate unusable rather than
# partially usable. That refusal is the same rule derive-expressions.pl uses:
# silently dropping a token is how a wrong string proves itself.

# c_unescape($body) - the bytes a C string literal denotes, given its INSIDE.
sub c_unescape {
    my ($s) = @_;
    my $out = '';
    my $i   = 0;
    my $len = length $s;
    while ($i < $len) {
        my $ch = substr($s, $i, 1);
        if ($ch ne "\\") { $out .= $ch; $i++; next }
        my $esc = substr($s, $i + 1, 1);
        $i += 2;
        if    ($esc eq 'n') { $out .= "\n" }
        elsif ($esc eq 't') { $out .= "\t" }
        elsif ($esc eq 'r') { $out .= "\r" }
        elsif ($esc eq 'f') { $out .= "\f" }
        elsif ($esc eq 'b') { $out .= "\b" }
        elsif ($esc eq 'a') { $out .= "\a" }
        elsif ($esc eq 'v') { $out .= "\013" }
        elsif ($esc eq 'e') { $out .= "\033" }
        elsif ($esc eq 'x') {
            # \xNN.. is greedy in C; john never writes more than two digits.
            my $h = '';
            $h .= substr($s, $i++, 1) while $i < $len && substr($s, $i, 1) =~ /[0-9a-fA-F]/ && length($h) < 2;
            return undef unless length $h;
            $out .= chr(hex $h);
        }
        elsif ($esc =~ /[0-7]/) {
            my $o = $esc;
            $o .= substr($s, $i++, 1) while $i < $len && substr($s, $i, 1) =~ /[0-7]/ && length($o) < 3;
            $out .= chr(oct $o);
        }
        else { $out .= $esc }        # \\ \" \' and anything else: itself
    }
    return $out;
}

# str_expr($text, $defines) - evaluate a concatenation of literals and macros,
# or undef if any token is not one of those. $depth guards a macro cycle.
sub str_expr {
    my ($text, $defines, $depth) = @_;
    $depth //= 0;
    return undef if $depth > 8;
    my $out = '';
    my $any = 0;
    while ($text =~ /\G\s*(?:"((?:[^"\\]|\\.)*)"|(\w+))/gc) {
        if (defined $1) { my $v = c_unescape($1); return undef unless defined $v; $out .= $v }
        else {
            my $d = $defines->{$2};
            return undef unless defined $d;
            my $v = str_expr($d, $defines, $depth + 1);
            return undef unless defined $v;
            $out .= $v;
        }
        $any = 1;
    }
    # Anything left over (a cast, an arithmetic expression, a comment) means
    # this is not a plain string and must not be guessed at.
    return undef unless $any;
    return undef if $text =~ /\G\s*\S/gc;
    return $out;
}

#-----------------------------------------------------------------------
# john's source: every fmt_tests array, and which FORMAT_LABEL uses which.

# skip_to_close($txt, $i) - $i is at '{'; return the index of its match, with
# strings, char constants and both comment styles stepped over.
sub skip_to_close {
    my ($txt, $i) = @_;
    my $len   = length $txt;
    my $depth = 0;
    while ($i < $len) {
        my $ch = substr($txt, $i, 1);
        my $two = substr($txt, $i, 2);
        if ($two eq '/*') { my $e = index($txt, '*/', $i + 2); $i = $e < 0 ? $len : $e + 2; next }
        if ($two eq '//') { my $e = index($txt, "\n", $i);     $i = $e < 0 ? $len : $e + 1; next }
        if ($ch eq '"' || $ch eq "'") {
            my $q = $ch; $i++;
            while ($i < $len) {
                my $c = substr($txt, $i, 1);
                last if $c eq $q;
                $i += ($c eq "\\") ? 2 : 1;
            }
            $i++;
            next;
        }
        $depth++ if $ch eq '{';
        if ($ch eq '}') { $depth--; return $i if $depth == 0 }
        $i++;
    }
    return -1;
}

# split_top($body) - split on commas at brace depth 0, strings respected.
sub split_top {
    my ($body) = @_;
    my (@out, $cur, $depth);
    $cur = ''; $depth = 0;
    my $i = 0; my $len = length $body;
    while ($i < $len) {
        my $ch  = substr($body, $i, 1);
        my $two = substr($body, $i, 2);
        if ($two eq '/*') { my $e = index($body, '*/', $i + 2); $i = $e < 0 ? $len : $e + 2; next }
        if ($two eq '//') { my $e = index($body, "\n", $i);     $i = $e < 0 ? $len : $e + 1; next }
        if ($ch eq '"' || $ch eq "'") {
            my $q = $ch; my $s = $i; $i++;
            while ($i < $len) {
                my $c = substr($body, $i, 1);
                last if $c eq $q;
                $i += ($c eq "\\") ? 2 : 1;
            }
            $i++;
            $cur .= substr($body, $s, $i - $s);
            next;
        }
        $depth++ if $ch eq '{' || $ch eq '(';
        $depth-- if $ch eq '}' || $ch eq ')';
        if ($ch eq ',' && $depth == 0) { push @out, $cur; $cur = ''; $i++; next }
        $cur .= $ch;
        $i++;
    }
    push @out, $cur;
    return @out;
}

my (%text, %defines, %array, %arrays_named);

sub load_source {
    opendir(my $dh, $src) or do {
        print STDERR "$PROG: cannot read john source $src: $!\n"; exit 1;
    };
    my @files = sort grep { /\.(?:c|h)$/ } readdir $dh;
    closedir $dh;

    for my $f (@files) {
        open my $fh, '<:raw', "$src/$f" or next;
        local $/;
        my $txt = <$fh>;
        close $fh;
        $text{$f} = $txt;

        # Object-like #defines whose body starts a string or a macro name. A
        # trailing comment is stripped; a function-like macro is skipped.
        my %d;
        while ($txt =~ /^[ \t]*#[ \t]*define[ \t]+(\w+)[ \t]+([^\n]*)$/mg) {
            my ($name, $body) = ($1, $2);
            $body =~ s{/\*.*}{};
            $body =~ s{//.*}{};
            $body =~ s/\s+$//;
            next unless $body =~ /^\s*(?:"|\w+\s*")/;
            $d{$name} = $body;
        }
        $defines{$f} = \%d;

        while ($txt =~ /struct\s+fmt_tests\s+(\w+)\s*\[\s*\]\s*=\s*/g) {
            my $name = $1;
            my $open = index($txt, '{', pos $txt);
            next if $open < 0;
            my $close = skip_to_close($txt, $open);
            next if $close < 0;
            $array{"$f\0$name"} = substr($txt, $open + 1, $close - $open - 1);
            push @{ $arrays_named{$name} }, $f;
        }
    }
    return scalar @files;
}

# index_labels() - which fmt_tests array each john format label uses.
#
# Read from the format struct itself rather than from the file, because
# neither half of the pairing is where a first pass would look for it.
#
#   struct fmt_main fmt_haval_128_4 = {
#       {
#           "HAVAL-128-4",        <- the label, and NOT always a FORMAT_LABEL
#           ...                      #define: a file defining several formats
#           haval_128_4_tests     <- the tests array, last member of the
#       }, {                         params struct
#
# Two things this gets right that a per-file heuristic does not. A file can
# hold SEVERAL fmt_main structs with a string literal for each label
# (haval_fmt_plug.c, ripemd_fmt_plug.c, truecrypt_fmt_plug.c all do), so
# scanning for #define FORMAT_LABEL misses every one of them. And the array is
# not always in the same file: john keeps a container format's tests in
# <name>_common_plug.c, and wpapsk_fmt_plug.c gets its `tests` from the
# wpapsk.h it includes. So resolution follows the identifier -- this file
# first, then the files this file #includes, then the unique file in the tree
# that defines it. A name defined in several files and included by none of
# them is refused rather than guessed at: john's file-local `tests` is
# declared in dozens of plugins and picking one would be a coin toss.
my %tests_of;

sub index_labels {
    for my $f (sort keys %text) {
        my $txt = $text{$f};
        my $d   = $defines{$f} || {};

        # Files this one includes by name, in order, for the array lookup.
        my @inc = $txt =~ /^[ \t]*#[ \t]*include[ \t]+"([^"]+)"/mg;

        while ($txt =~ /struct\s+fmt_main\s+\w+\s*=\s*/g) {
            my $open = index($txt, '{', pos $txt);
            next if $open < 0;
            my $close = skip_to_close($txt, $open);
            next if $close < 0;
            # The first top-level element of the fmt_main initialiser is the
            # whole params struct; the label and the tests identifier are its
            # first and last members.
            my ($pa) = split_top(substr($txt, $open + 1, $close - $open - 1));
            my $po = index($pa, '{');
            next if $po < 0;
            my $pc = skip_to_close($pa, $po);
            next if $pc < 0;
            my @member = split_top(substr($pa, $po + 1, $pc - $po - 1));
            next if @member < 2;

            my $label = str_expr($member[0], $d);
            next unless defined $label && length $label;

            # The tail can carry #endif lines; the identifier is the last bare
            # word in it.
            my @word = $member[-1] =~ /([A-Za-z_]\w*)/g;
            next unless @word;
            my $id = $word[-1];

            my $owner;
            if (exists $array{"$f\0$id"}) { $owner = $f }
            else {
                for my $h (@inc) { next unless exists $array{"$h\0$id"}; $owner = $h; last }
                unless (defined $owner) {
                    my $o = $arrays_named{$id};
                    $owner = $o->[0] if $o && @$o == 1;
                }
            }
            next unless defined $owner;
            # The array's own file and the file that names it BOTH contribute
            # macros: a test entry written {FORMAT_TAG "..."} takes FORMAT_TAG
            # from wherever it is defined, which is not always where the array
            # sits.
            $tests_of{ lc $label } //= [ $array{"$owner\0$id"},
                                         $defines{$owner} || {}, $d, "$owner:$id" ];
        }
    }
}

# examples_from_array($body, $defs_a, $defs_b, $where) - the
# { ciphertext, plaintext } pairs that evaluate to plain strings, in source
# order. Two define tables are consulted, the array's file and the naming
# file's, in that order.
#
# #if is NOT evaluated, so a conditionally compiled array yields the UNION of
# its branches: wpapsk.h holds one `tests` whose #ifdef WPAPMK half carries
# PMK plaintexts and whose #else half carries passphrases, and both halves
# come back here. That is safe only because john is the oracle -- a pair from
# the branch this build did not compile simply fails to crack and the next
# candidate is tried. It would NOT be safe in a tool that believed the source.
sub examples_from_array {
    my ($body, $da, $db) = @_;
    my $d = { %{ $db || {} }, %{ $da || {} } };
    my @out;
    my $i = 0;
    my $len = length $body;
    while ($i < $len) {
        my $open = index($body, '{', $i);
        last if $open < 0;
        my $close = skip_to_close($body, $open);
        last if $close < 0;
        my $rec = substr($body, $open + 1, $close - $open - 1);
        $i = $close + 1;
        my @field = split_top($rec);
        next if @field < 2;
        # A third element is fields[], which carries a login john needs beside
        # the hash. That cannot be stored self-contained, so it is skipped.
        next if @field > 2 && $field[2] =~ /\S/;
        my $hash = str_expr($field[0], $d);
        my $pass = str_expr($field[1], $d);
        next unless defined $hash && defined $pass;
        push @out, { hash => $hash, pass => $pass };
    }
    return @out;
}

#-----------------------------------------------------------------------
# dynamic.conf: Test=<ciphertext>:<plaintext>[:<login>]
#
# A line with a login is transcoded to john's self-contained spelling before it
# is offered, and only where the ciphertext does not already carry one. The
# 2-field lines are preferred, so the transcode is a fallback rather than the
# usual path.

my %dyn_tests;

sub load_dynamic_conf {
    open my $fh, '<:raw', $conf or do {
        print STDERR "$PROG: cannot read $conf: $!\n"; return 0;
    };
    my $section = '';
    my $n = 0;
    while (my $line = <$fh>) {
        $line =~ s/\r?\n$//;
        if ($line =~ /^\[List\.Generic:(dynamic_\d+)\]/i) { $section = lc $1; next }
        next unless $section;
        next unless $line =~ /^Test=(.*)$/;              # TestM=/TestF= are
        my $rest = $1;                                   # length-probe variants
        my @f = split /:/, $rest;
        next if @f < 2;
        my ($hash, $pass, $login) = ($f[0], $f[1], (@f > 2 ? join(':', @f[2 .. $#f]) : undef));
        next unless length $hash && length $pass;
        push @{ $dyn_tests{$section} }, { hash => $hash, pass => $pass, login => $login };
        $n++;
    }
    close $fh;
    return $n;
}

# dyn_candidates($label) - self-contained ciphertexts for a dynamic, best first.
sub dyn_candidates {
    my ($label) = @_;
    my @out;
    for my $t (@{ $dyn_tests{ lc $label } || [] }) {
        push @out, { hash => $t->{hash}, pass => $t->{pass}, transcoded => 0 }
            unless defined $t->{login};
    }
    for my $t (@{ $dyn_tests{ lc $label } || [] }) {
        next unless defined $t->{login} && length $t->{login};
        next if $t->{hash} =~ /\$\$U/;            # already self-contained
        push @out, { hash => "$t->{hash}\$\$U$t->{login}", pass => $t->{pass},
                     transcoded => 1 };
    }
    return @out;
}

#-----------------------------------------------------------------------
# Verification. One hash, one word, a fresh pot, and --show's own count.

sub write_file {
    my ($path, @lines) = @_;
    open my $fh, '>', $path or die "$PROG: cannot write $path: $!\n";
    print {$fh} "$_\n" for @lines;
    close $fh;
    return $path;
}

sub run_capture {
    my ($secs, @argv) = @_;
    my $out = '';
    my $pid = open(my $fh, '-|');
    defined $pid or return (-1, '');
    if (!$pid) {
        open STDERR, '>&', \*STDOUT;
        exec { $argv[0] } @argv or exit 127;
    }
    my $killed = 0;
    eval {
        local $SIG{ALRM} = sub { $killed = 1; kill 'KILL', $pid; die "timeout\n" };
        alarm $secs;
        local $/;                       # slurp: $/ is the input record separator
        $out = <$fh> // '';
        alarm 0;
    };
    alarm 0;
    close $fh;
    return ($killed ? -2 : ($? >> 8), $out);
}

# ENC_REFUSAL is john refusing to run at all, and it looks exactly like a
# format that did not crack once the output is discarded:
#
#   This format does not yet support other encodings than ISO-8859-1
#
# john.c raises it for a format flagged FMT_UNICODE but not FMT_ENC whenever
# the configured encoding is neither raw nor ISO-8859-1, and this host's
# john.conf sets DefaultEncoding = UTF-8 (line 274). It is a fact about the
# host's configuration, not about the entry's label: dynamic_1507 passes its
# own --test=0 and cracks its own published vector the moment the encoding is
# named on the command line.
#
# The retry is offered ONLY when john printed that line AND the plaintext is
# pure ASCII, where UTF-8 and ISO-8859-1 are byte-for-byte the same input and
# the flag therefore cannot change what was proven. On a non-ASCII plaintext
# the two encodings feed the format different bytes, so a crack under the flag
# would be a claim about a different string; that case is reported, not retried.
my $ENC_REFUSAL = 'does not yet support other encodings';
my $ENC_FLAG    = '--input-encoding=iso-8859-1 ';

# crack($label, $hash, $pass, $tab) - did john recover $pass from $hash under
# $label? $tab picks the reading scheme: a synthetic login and a tab separator,
# which is what verify-vectors.pl uses, or the bare line handed over natively.
# Returns (ok, reason, encoding-flag-needed).
sub crack {
    my ($label, $hash, $pass, $tab, $tag) = @_;
    my $jbin = basename($john);
    (my $safe = "$tag.$label") =~ s/[^A-Za-z0-9._-]/_/g;
    my $hf  = write_file("$workdir/$safe.hash", $tab ? "v0\t$hash" : $hash);
    my $wf  = write_file("$workdir/$safe.word", $pass);
    my $pot = "$workdir/$safe.pot";
    my $sep = $tab ? '--field-separator-char=tab ' : '';

    for my $enc ('', $ENC_FLAG) {
        unlink $pot;

        # Run from run/ -- john resolves john.conf against the cwd -- with the
        # pot and the session in the work dir, which is writable when run/ is
        # not. john exits 1 with NO message when it cannot write john.log,
        # which is indistinguishable from "did not crack", so --session must
        # land here. stderr is KEPT rather than discarded, because the whole
        # point of the retry is a refusal that only shows up there.
        my ($code, $out) = run_capture($timeout, '/bin/sh', '-c',
            sprintf('cd %s && ./%s --format=%s %s%s--wordlist=%s --pot=%s --session=%s %s 2>&1 >/dev/null',
                    quotemeta($jdir), quotemeta($jbin), quotemeta($label), $sep, $enc,
                    quotemeta($wf), quotemeta($pot), quotemeta("$workdir/$safe"),
                    quotemeta($hf)));
        return (0, 'timeout', 0) if $code == -2;

        if (index($out, $ENC_REFUSAL) >= 0) {
            next if !length $enc && $pass !~ /[^\x20-\x7e]/;
            return (0, 'refused: needs ISO-8859-1 and the plaintext is not ASCII', 0)
                if !length $enc;
            return (0, 'refused on the encoding even with the flag', 0);
        }

        my (undef, $shown) = run_capture($timeout, '/bin/sh', '-c',
            sprintf('cd %s && ./%s --show --format=%s %s%s--pot=%s %s 2>/dev/null',
                    quotemeta($jdir), quotemeta($jbin), quotemeta($label), $sep, $enc,
                    quotemeta($pot), quotemeta($hf)));

        # One hash in, one word in: john's own tally is unambiguous, and it
        # avoids both --show reading traps (the plaintext is not always the
        # last field, and a field-wise match on a common plaintext can
        # coincide).
        return (1, '', (length $enc ? 1 : 0))
            if ($shown // '') =~ /^(\d+) password hash(?:es)? cracked/m && $1 > 0;
        last unless length $enc;      # no refusal seen: the flag changes nothing
    }
    return (0, 'not cracked', 0);
}

#-----------------------------------------------------------------------
# Targets: entries with no vector at all that name a john identifier we have
# an example for.

my $nsrc = load_source();
index_labels();
my $ndyn = load_dynamic_conf();
printf STDERR "%s: %d john source file(s), %d fmt_tests array(s), %d label(s) resolved, %d dynamic.conf Test= line(s)\n",
    $PROG, $nsrc, scalar keys %array, scalar keys %tests_of, $ndyn if $verbose;

opendir(my $dh, $algdir) or do { print STDERR "$PROG: cannot read $algdir: $!\n"; exit 1 };
my @files = sort grep { /\.yaml$/ } readdir $dh;
closedir $dh;

my (@cand, @noscore);
my $targets = 0;

for my $f (@files) {
    my $path = "$algdir/$f";
    my $e = eval { YAML::XS::LoadFile($path) };
    unless ($e) { print STDERR "$PROG: cannot load $path: $@\n"; exit 1 }
    my $id = $e->{id} // ($f =~ s/\.yaml$//r);
    next if %only && !$only{$id};
    next if ($e->{status} // '') eq 'merged';
    next if $e->{vectors} && @{ $e->{vectors} };
    my @labels = (@{ $e->{tools}{john}{cpu} || [] }, @{ $e->{tools}{john}{gpu} || [] });
    next unless @labels;
    $targets++;

    my @c;
    for my $label (@labels) {
        if ($label =~ /^dynamic_\d+$/i) {
            for my $t (dyn_candidates($label)) {
                push @c, { id => $id, path => $path, entry => $e, label => $label,
                           route => ($t->{transcoded} ? 'dynamic.conf (transcoded)'
                                                      : 'dynamic.conf'),
                           hash => $t->{hash}, pass => $t->{pass} };
            }
        }
        my $t = $tests_of{ lc $label } or next;
        for my $x (examples_from_array(@$t)) {
            push @c, { id => $id, path => $path, entry => $e, label => $label,
                       route => "fmt_tests ($t->[3])",
                       hash => $x->{hash}, pass => $x->{pass} };
        }
    }
    # A plaintext john cannot put in a wordlist proves nothing: an empty one
    # and one carrying a newline are both unusable as a candidate line.
    @c = grep { length $_->{pass} && $_->{pass} !~ /[\r\n]/ && $_->{hash} !~ /[\r\n]/ } @c;
    if (@c) { push @cand, \@c }
    else    { push @noscore, $id }
}

#-----------------------------------------------------------------------
# Run. Each entry gets its candidates tried in order until one verifies: the
# first is not always loadable (a test array can hold several serializations)
# and one that john reads is worth more than the one that came first.

my $started = time;
my (@ok, @bad);
my $n = 0;

printf "# %s -- %d target entr%s with no vector naming a john identifier; %d with an example, %d without\n",
    $PROG, $targets, ($targets == 1 ? 'y' : 'ies'), scalar @cand, scalar @noscore;
print "# columns: result, entry, label, route, scheme, hash, pass\n";

for my $set (@cand) {
    last if $limit && $n >= $limit;
    $n++;

    if ($dry) {
        my $c = $set->[0];
        printf "PLAN\t%s\t%s\t%s\t-\t%s\t%s\n",
            $c->{id}, $c->{label}, $c->{route}, $c->{hash}, $c->{pass};
        next;
    }

    my ($won, $why);
    for my $c (@$set) {
        for my $tab (1, 0) {
            my ($good, $reason, $enc) = crack($c->{label}, $c->{hash}, $c->{pass}, $tab, $c->{id});
            if ($good) {
                $c->{scheme} = ($tab ? 'tab' : 'native') . ($enc ? '+iso8859-1' : '');
                $won = $c;
                last;
            }
            $why = $reason;
        }
        last if $won;
    }

    my $first = $set->[0];
    printf STDERR "-   %-46s %-24s %s\n", $first->{id}, $first->{label},
        ($won ? "verified ($won->{scheme}, $won->{route})" : "FAILED ($why)")
        if $verbose;

    if ($won) {
        push @ok, $won;
        printf "OK\t%s\t%s\t%s\t%s\t%s\t%s\n",
            $won->{id}, $won->{label}, $won->{route}, $won->{scheme},
            $won->{hash}, $won->{pass};
    }
    else {
        push @bad, $first;
        printf "FAIL\t%s\t%s\t%s\t-\t%s\t%s\n",
            $first->{id}, $first->{label}, $first->{route},
            $first->{hash}, $first->{pass};
    }
}

print "SKIP\t$_\t-\t-\t-\t-\t-\n" for @noscore;

#-----------------------------------------------------------------------
# Write. Only the verified ones, and only under --apply.

my $written = 0;
if ($apply) {
    my %touched;
    for my $c (@ok) {
        push @{ $c->{entry}{vectors} }, {
            hash   => $c->{hash},
            pass   => $c->{pass},
            source => 'john',
        };
        $touched{ $c->{path} } = $c->{entry};
    }
    $written += emit_entry($_, $touched{$_}) for sort keys %touched;
}

my $elapsed = time - $started;
printf STDERR "%s: %d entr%s examined, %d verified, %d failed, %d file(s) written in %.1fs\n",
    $PROG, $n, ($n == 1 ? 'y' : 'ies'), scalar @ok, scalar @bad, $written, $elapsed;

if (@bad) {
    printf STDERR "%s: a failure is evidence about the entry's john label, not just about the example -- review the FAIL rows.\n", $PROG;
}
if ($apply && $written) {
    printf STDERR "%s: tiers untouched. Promote what is now provable with:\n    ./tools/verify-vectors.pl --tool john -v\n", $PROG;
}

exit 0;
