#!/usr/bin/perl
#-----------------------------------------------------------------------
#
# Name: seed-hashpipe.pl
# Description: fill tools.hashpipe by round-tripping each candidate type
#              PINNED, never by trusting what an unpinned run reported
# Category: cracking-rosetta seeder
#
# Project: cracking-rosetta | Phase: 7 - pre-publication readiness
#
#-----------------------------------------------------------------------
# METHODOLOGY AND WHY THESE CHOICES
#
# WHY PINNING IS NOT OPTIONAL
#
# hashpipe reports the FIRST type that reproduces a digest, exactly as mdxfind
# does, so an unpinned answer names A type that works and not necessarily THE
# type an entry is about. MD5CAP is cap(md5(pass)), a no-op whenever the digest
# has no letters to capitalize, and is then byte-identical to plain MD5. Taking
# an unpinned report as a mapping is how that trap is walked into.
#
# So an unpinned run only ever PROPOSES here. Every candidate is re-run with
# -m pinned to that single type, and only a type that reproduces one of the
# entry's own vectors under its own name is written. Pinning costs 48ms, so
# the whole corpus is under a minute; there is no reason to take the shortcut.
#
# WHERE CANDIDATES COME FROM
#
# Two sources, both cheap and neither trusted:
#
#   * The entry's own mdxfind types, where hashpipe has a type of that name.
#     The two share a catalog and agree on 975 names, so this is where most of
#     the corpus is answered. It is still a proposal: sharing a name is not
#     sharing an implementation, which is exactly what BMW224 demonstrates --
#     mdxfind computes it correctly and hashpipe returns a different digest on
#     every run.
#   * An unpinned hashpipe pass, via --resolved. That is what finds the types
#     an entry does NOT already name, including the ones mdxfind has no
#     equivalent of.
#
# WHAT IS REFUSED
#
#   * A type whose own self-test fails. It cannot prove anything about an
#     entry when it cannot reproduce its own vector, and validate.pl rejects
#     tier 'vector' on one anyway. Reported, never written.
#   * An entry whose existing hashpipe block names a type this run did not
#     test. Replacing it would silently drop a curator's work; the run says so
#     and moves on.
#
# THE PROMOTION RULE IS verify-vectors.pl's, DELIBERATELY
#
# A type qualifies when it reproduces AT LEAST ONE of the entry's vectors, and
# the block is written only if every type in it qualifies. That is the same
# rule the other three tools are held to, and an entry carrying one vector per
# tool serialization would fail any stricter one for a reason that has nothing
# to do with hashpipe.
#
# USAGE
#   tools/seed-hashpipe.pl [--resolved FILE] [--apply] [-v]
#
# DEPENDENCIES
#   perl, YAML::XS, tools/lib/RosettaEmit.pm, tools/lib/RosettaTools.pm,
#   a hashpipe binary
#
#-----------------------------------------------------------------------
# Generated by Claude Opus 5 on 2026-09-03

use strict;
use warnings;

use File::Basename qw(basename);
use File::Path qw(make_path);
use FindBin qw($RealBin);
use Getopt::Long qw(GetOptions);
use POSIX qw(strftime);
use Time::HiRes qw(time);
use YAML::XS ();

use lib "$RealBin/lib";
use RosettaEmit qw(emit_entry);
use RosettaTools qw(tool_path tool_env_help);

my $PROG = basename($0);
my $ROOT = "$RealBin/..";

sub usage {
    print STDERR <<"END_USAGE";
Usage: $PROG [options]

   --hashpipe PATH   hashpipe binary  (default: @{[tool_env_help('hashpipe')]})
   --algorithms DIR  curated entries  (default: data/algorithms)
   --inventory PATH  hashpipe inventory (default: data/tools/hashpipe.yaml)
   --resolved FILE   output of an unpinned hashpipe pass, to propose types an
                     entry does not already name
   --work DIR        scratch (default: tmp/seed-hashpipe)
   --only ID         just this entry (repeatable)
   --apply           write the blocks; without it nothing is written
   -v, --verbose     per-type result (repeatable)
   -h, --help        this help

   Exit 0 success, 1 error, 2 usage.
END_USAGE
    return;
}

my ($hashpipe, $algdir, $invpath, $resolved, $workdir, @only, $apply,
    $verbose, $help);
GetOptions(
    'hashpipe=s'   => \$hashpipe,
    'algorithms=s' => \$algdir,
    'inventory=s'  => \$invpath,
    'resolved=s'   => \$resolved,
    'work=s'       => \$workdir,
    'only=s'       => \@only,
    'apply'        => \$apply,
    'verbose+'     => \$verbose,
    'help|h'       => \$help,
) or do { usage(); exit 2 };
if ($help) { usage(); exit 0 }

$hashpipe = tool_path('hashpipe', $hashpipe);
$algdir  //= "$ROOT/data/algorithms";
$invpath //= "$ROOT/data/tools/hashpipe.yaml";
$workdir //= "$ROOT/tmp/seed-hashpipe";
my %only = map { $_ => 1 } @only;
make_path($workdir) unless -d $workdir;

#-----------------------------------------------------------------------
# Inventory.

my $inv = eval { YAML::XS::LoadFile($invpath) }
    or die "$PROG: cannot load $invpath: $@\n";
my (%HP_TYPE, %HP_INDEX, %HP_FAIL);
for my $t (@{ $inv->{types} }) {
    $HP_TYPE{ $t->{name} }  = $t->{index};
    $HP_INDEX{ $t->{name} } = $t->{index};
    $HP_FAIL{ $t->{name} }  = 1 if ($t->{selftest} // '') eq 'fail';
}
my $version = $inv->{version} // 'unknown';

#-----------------------------------------------------------------------
# Entries, and the candidates each proposes.

opendir(my $dh, $algdir) or die "$PROG: cannot read $algdir: $!\n";
my @files = sort grep { /\.yaml$/ } readdir $dh;
closedir $dh;

my (%entry, %path, %cand);
for my $f (@files) {
    my $e = eval { YAML::XS::LoadFile("$algdir/$f") } or next;
    next unless $e->{id};
    next if ($e->{status} // '') eq 'merged';
    next if %only && !$only{ $e->{id} };
    my @v = ref $e->{vectors} eq 'ARRAY' ? @{ $e->{vectors} } : ();
    next unless @v;
    $entry{ $e->{id} } = $e;
    $path{  $e->{id} } = "$algdir/$f";

    # Candidate source 1: the mdxfind types this entry already names.
    for my $t (@{ $e->{tools}{mdxfind}{types} || [] }) {
        $cand{ $e->{id} }{$t} = 'own' if $HP_TYPE{$t};
    }
}

# Candidate source 2: an unpinned pass, which is the only way to propose a
# type the entry does not already name.
if (defined $resolved) {
    my %by_line;
    for my $id (sort keys %entry) {
        for my $v (@{ $entry{$id}{vectors} }) {
            next unless defined $v->{hash} && defined $v->{pass};
            push @{ $by_line{"$v->{hash}:$v->{pass}"} }, $id;
        }
    }
    open my $rf, '<', $resolved or die "$PROG: cannot read $resolved: $!\n";
    my $n = 0;
    while (<$rf>) {
        chomp;
        next unless /^(\S+?)(?:x\d+)?\s+(.+)$/;
        my ($type, $line) = ($1, $2);
        next unless $HP_TYPE{$type};
        for my $id (@{ $by_line{$line} || [] }) {
            $cand{$id}{$type} ||= 'proposed';
            $n++;
        }
    }
    close $rf;
    printf STDERR "- %d candidate(s) proposed by the unpinned pass\n", $n if $verbose;
}

# norm($s) - the separator-drift rule: the sheet wrote HAV128_4 where mdxfind
# writes HAV128-4. Compare on this; store the tool's own spelling.
sub norm {
    my ($s) = @_;
    return '' unless defined $s;
    $s = uc $s;
    $s =~ s/[^A-Z0-9]//g;
    return $s;
}

# names_it($entry, $type) - does the entry itself publish this name? A
# proposal that does is corroborated by the entry; one that does not is a type
# that merely reproduces the same digest.
#
# The john formats count, and that is a deliberate exception to the rule that
# normalizing across two tools' vocabularies produces collisions rather than
# mappings. It does when both write EXPRESSIONS: mdxfind's MD5MD5PASS is
# md5(md5(pass).pass) and hashcat's mode 2600 is named md5(md5($pass)), and
# both reduce to MD5MD5PASS. hashpipe's names are not expressions. The types
# it has and mdxfind does not exist, on upstream's own account, because
# Waffle is improving hashpipe's overlap with algorithms JOHN supports, so
# those names are john's names -- oracle11, h3c, MongoDB, gost94crypt.
# CLAUDE.md records the same match independently, finding 13 of the 25
# reachable by an exact john identifier.
sub names_it {
    my ($e, $type) = @_;
    my $n = norm($type) or return 0;
    for my $c ($e->{id}, $e->{name}, @{ $e->{aliases} || [] },
               values %{ $e->{legacy} || {} },
               @{ $e->{tools}{john}{cpu} || [] },
               @{ $e->{tools}{john}{gpu} || [] }) {
        next unless defined $c && length $c;
        return 1 if norm($c) eq $n;
    }
    return 0;
}

#-----------------------------------------------------------------------
# One pinned run per candidate type.

my (%byte_type, %refused_fail);
for my $id (sort keys %cand) {
    for my $t (sort keys %{ $cand{$id} }) {
        if ($HP_FAIL{$t}) { $refused_fail{$t}{$id} = 1; next }
        push @{ $byte_type{$t} }, $id;
    }
}

my $started = time;
my %ok;          # entry id -> type -> 1, when that type reproduced a vector
my $runs = 0;
for my $type (sort keys %byte_type) {
    my @ids = @{ $byte_type{$type} };
    my (@lines, %owner);
    for my $id (@ids) {
        for my $v (@{ $entry{$id}{vectors} }) {
            next unless defined $v->{hash} && defined $v->{pass};
            my $line = "$v->{hash}:$v->{pass}";
            push @lines, $line;
            $owner{$line}{$id} = 1;
        }
    }
    next unless @lines;

    (my $safe = $type) =~ s/[^A-Za-z0-9]/_/g;
    my $in = "$workdir/$safe.in";
    open my $ih, '>', $in or die "$PROG: cannot write $in: $!\n";
    my %u; print {$ih} "$_\n" for grep { !$u{$_}++ } @lines;
    close $ih;

    # -m pins to this one type. -L is raised past its default because hashpipe
    # DECLINES an expensive verify above it and reports the line unresolved,
    # which its own help says looks exactly like a genuine miss.
    my $out = `$hashpipe -m $HP_INDEX{$type} -L 5000 '$in' 2>/dev/null` // '';
    $runs++;
    my $hits = 0;
    for my $line (split /\n/, $out) {
        next unless $line =~ /^\Q$type\E(?:x\d+)?\s+(.+)$/;
        for my $id (keys %{ $owner{$1} || {} }) { $ok{$id}{$type} = 1; $hits++ }
    }
    printf STDERR "-   %-28s %d entry(ies), %d hit(s)\n",
        $type, scalar @ids, $hits if $verbose && $verbose > 1;
}

#-----------------------------------------------------------------------
# Decide and write.

my $today = strftime('%Y-%m-%d', localtime);
my (@write, @partial, @skipped, @candidates_out);

for my $id (sort keys %cand) {
    my $e = $entry{$id};
    my @all = grep { !$HP_FAIL{$_} } sort keys %{ $cand{$id} };
    next unless @all;

    my @own      = grep { $cand{$id}{$_} eq 'own' } @all;
    my @proposal = grep { $cand{$id}{$_} ne 'own' } @all;

    my @good;
    if (@own) {
        # The entry's identity. All or nothing: a subset would record a type
        # this entry is not about.
        my @bad = grep { !$ok{$id}{$_} } @own;
        if (@bad) {
            push @partial, [ $id, "hashpipe did not reproduce @bad" ];
            next;
        }
        @good = @own;
        # A proposal alongside the entry's own types is a collision candidate,
        # never a mapping: the entry already says what it is.
        push @candidates_out, [ $id, "also reproduced by @proposal" ] if @proposal;
    }
    else {
        # No mdxfind type at all. A proposal is writable only where the entry
        # itself publishes that name.
        my @named = grep { $ok{$id}{$_} && names_it($e, $_) } @proposal;
        my @other = grep { !$ok{$id}{$_} || !names_it($e, $_) } @proposal;
        push @candidates_out, [ $id, "proposed @other, not corroborated by any "
            . "identifier this entry publishes" ] if @other;
        @good = @named;
    }
    unless (@good) { push @skipped, [ $id, 'nothing writable' ]; next }

    # Never silently drop a type somebody put there by hand.
    my $existing = $entry{$id}{tools}{hashpipe} || {};
    my @have = @{ $existing->{types} || [] };
    my %tested = map { $_ => 1 } @all;
    if (my @untested = grep { !$tested{$_} } @have) {
        push @skipped, [ $id, "existing block names untested type(s) @untested" ];
        next;
    }
    push @write, [ $id, \@good ];
}

printf STDERR "- %d pinned run(s) in %.1fs\n", $runs, time - $started;
printf STDERR "-   would write %d, partial %d, skipped %d, candidate %d\n",
    scalar @write, scalar @partial, scalar @skipped, scalar @candidates_out;
if (%refused_fail) {
    printf STDERR "-   refused %d type(s) whose own self-test fails: %s\n",
        scalar keys %refused_fail, join(', ', sort keys %refused_fail);
}
if ($verbose) {
    printf STDERR "-   PARTIAL   %-40s %s\n", @$_ for @partial;
    printf STDERR "-   SKIPPED   %-40s %s\n", @$_ for @skipped;
    printf STDERR "-   CANDIDATE %-40s %s\n", @$_ for @candidates_out;
}

unless ($apply) {
    print STDERR "- dry run; nothing written. Add --apply.\n";
    exit 0;
}

my $note = "verified by round-tripping each type PINNED with -m, not by "
         . "taking an unpinned report: hashpipe names the FIRST type that "
         . "reproduces a digest, so an unpinned answer names a type that works "
         . "and not necessarily this one.";

my $written = 0;
for my $row (@write) {
    my ($id, $types) = @$row;
    $entry{$id}{tools}{hashpipe} = {
        types         => [ @$types ],
        verified      => 'vector',
        verified_at   => $today,
        verified_with => "hashpipe $version",
        note          => $note,
    };
    $written++ if emit_entry($path{$id}, $entry{$id});
}
printf STDERR "- wrote %d hashpipe block(s)\n", $written;
exit 0;
