#!/usr/bin/perl
#
# seed-hx.pl -- transcribe mdxfind type expressions from the hx specification
#
# PURPOSE
#
# Appendix A of the hx Language Specification (Waffle, rev 1.15, Aug 2026)
# states an hx expression for 1011 mdxfind types, covering 998 of the 1001 in
# our inventory. 475 entries here name such a type and carry no expression at
# all. This transcribes them at tier `upstream` so that derive-expressions.pl
# can then try to PROVE each one through john's dynamic compiler.
#
# WHY UPSTREAM AND NEVER VECTOR
#
# Transcription is not reproduction. The tier vocabulary is fixed and
# `upstream` means exactly this: asserted by an upstream project that verifies
# by recomputation. Only derive-expressions.pl may write `vector`, and only
# after john has recovered the entry's own plaintext from its own hash.
#
# WHY IT BAILS INSTEAD OF GUESSING
#
# hx spells functions its own way (hav128, md5_bin, utf16le) where this
# repository uses john's spelling (haval128_3, md5_raw, utf16). A translation
# table is fine for the digests, but hx also has tokens with no expression
# meaning here at all -- pbkdf2_sha256(), bcrypt(), descrypt(), emit(), lm().
# Those are containers and KDFs; they belong in denotation:, not in an
# expression that validate.pl treats as a semantic join key. So any candidate
# containing a token outside %FUNC is DISCARDED rather than partially
# translated. Dropping a token silently is how md5(md5($p).":".$u) once looked
# like md5(md5($p).$s).
#
# MULTI-EMIT TYPES ARE SKIPPED
#
# Note [24] of the specification names 34 types that emit SEVERAL candidate
# digests per input and match if any one reproduces the digest. Such a type has
# no single expression, so writing one would be a false claim even when the
# string is one of the forms. See CLAUDE.md.
#
# THE PARSER LIVES IN RosettaHx, NOT HERE
#
# denote-hx.pl writes denotation: for the types this tool refuses, and
# validate.pl fails an entry carrying both fields. Two private copies of "is
# this expressible here" would eventually disagree, and the day they do an
# entry says the same thing twice at two strengths. So the appendix parse, the
# %FUNC boundary and the multi-emit test are all in tools/lib/RosettaHx.pm and
# both tools read the same one. Moving them there fixed three defects this
# tool had shipped -- a lowercase prose gloss surviving into the expression, a
# non-ASCII iteration operator, and bare hx operands (salt2, pepper, N) passing
# a check that only ever looked at function tokens. Nine entries were carrying
# the results; see RosettaHx's header.
#
# The specification is NOT vendored: this repository is MIT throughout and the
# PDF carries no licence grant. Re-fetch it to re-run this.
#
# Usage: seed-hx.pl [--appendix FILE] [--apply] [-v]
#
# Generated by Claude Opus 4.5 on 2026-08-31, revised by Claude Opus 5 on 2026-08-31

use strict;
use warnings;
use FindBin qw($RealBin);
use lib "$RealBin/lib";
use Getopt::Long qw(GetOptions);
use File::Basename qw(basename);
use YAML::XS qw(LoadFile);
use RosettaEmit qw(emit_entry);
use RosettaExpr qw(compile_expression);
use RosettaHx qw(parse_appendix translate_hx is_multi_emit);

my $PROG = basename($0);
my $ROOT = "$RealBin/..";

my $appendix = "$ROOT/tmp/hx/appA.txt";
my $algdir   = "$ROOT/data/algorithms";
my ($apply, $verbose, $help) = (0, 0, 0);

sub usage {
    print <<"USAGE";
Usage: $PROG [options]

   --appendix FILE  parsed Appendix A text  (default: tmp/hx/appA.txt)
   --algorithms DIR curated entries         (default: data/algorithms)
   --apply          write; without it, report only
   -v, --verbose    per-entry detail on stderr
   -h, --help       this help

   Transcribes at tier 'upstream' only, and only for entries that have an
   mdxfind type, no expression, and a type that is not multi-emit. Any hx
   token outside the known vocabulary discards that candidate entirely.

   Exit 0 success, 1 error, 2 usage.
USAGE
    exit 2;
}

GetOptions(
    'appendix=s'   => \$appendix,
    'algorithms=s' => \$algdir,
    'apply'        => \$apply,
    'verbose|v+'   => \$verbose,
    'help|h'       => \$help,
) or usage();
usage() if $help;
usage() unless -f $appendix;

my $hx = parse_appendix($appendix);
printf STDERR "- appendix: %d type(s)\n", scalar keys %$hx;

#-----------------------------------------------------------------------

my ($seen, $written, %skip) = (0, 0);
opendir my $dh, $algdir or die "$PROG: $algdir: $!\n";
my @files = sort grep { /\.yaml$/ } readdir $dh;
closedir $dh;

# validate.pl fails a build where two entries claim the same expression without
# relation edges joining them, and that gate is the reason the expression is a
# key rather than a decoration. A transcription pass must not be what forces
# those edges into existence: deciding that two rows are the same computation,
# and WHY both still exist, is curation. CLAUDE.md is explicit that only a
# person writes `distinction: naming`. So a candidate whose expression another
# entry already claims is held back and reported, never written and related
# automatically.
my %claimed;
for my $f (@files) {
    my $e = eval { LoadFile("$algdir/$f") } or next;
    next unless $e->{id} && defined $e->{expression} && length $e->{expression};
    push @{ $claimed{ $e->{expression} } }, $e->{id};
}

for my $f (@files) {
    my $path = "$algdir/$f";
    my $e = eval { LoadFile($path) } or next;
    next unless $e->{id};
    next if ($e->{status} // '') eq 'merged';
    next if defined $e->{expression} && length $e->{expression};
    my $types = $e->{tools}{mdxfind}{types} or next;
    ref $types eq 'ARRAY' && @$types or next;

    $seen++;
    my ($type) = grep { $hx->{$_} } @$types;
    unless ($type) { $skip{'type not in appendix'}++; next }
    if (is_multi_emit($type, $hx->{$type})) { $skip{'multi-emit type'}++; next }

    # translate_hx names WHY it refused. Bucketing the residue is what exposed
    # the gloss and operand defects, so keep the reasons rather than counting
    # one lump; denote-hx.pl consumes the same reasons from the other side.
    my ($expr, $why, $tokens) = translate_hx($hx->{$type}{expr});
    unless (defined $expr) {
        $skip{"refused: $why"}++;
        printf STDERR "  skip %-34s %-22s %-16s %s\n", $e->{id}, $type, $why,
            $hx->{$type}{expr} if $verbose > 1;
        next;
    }

    # Verify before writing, wherever that is possible at all. RosettaExpr
    # covers md5/sha1/sha256/sha512 constructions; anything else (haval, wrl,
    # cut, pad) cannot be checked here and is transcribed on upstream's word.
    # A candidate that CAN be checked and reproduces nothing is held back: the
    # check cannot tell "the expression is wrong" from "the vector is in the
    # tool's own encoding", and after ciscoasa the benefit of the doubt goes to
    # not writing. Those are reported for a human.
    my $confirmed = 0;
    if (my $fn = compile_expression($expr)) {
        my @v = grep { ($_->{source} // '') ne 'vanity' } @{ $e->{vectors} || [] };
        if (@v) {
            for my $v (@v) {
                my ($h, $salt) = split /:/, $v->{hash}, 2;
                my $got = eval { $fn->($v->{pass}, defined $salt ? $salt : '') };
                if (defined $got && lc($got) eq lc($h)) { $confirmed = 1; last }
            }
            unless ($confirmed) {
                $skip{'checkable but reproduces no vector'}++;
                printf STDERR "  HELD %-30s %-22s %s\n", $e->{id}, $type, $expr;
                next;
            }
        }
    }

    if (my $by = $claimed{$expr}) {
        $skip{'expression already claimed by another entry'}++;
        printf STDERR "  COLLIDES %-27s %-22s %s  (claimed by %s)\n",
            $e->{id}, $type, $expr, join(', ', @$by);
        next;
    }
    push @{ $claimed{$expr} }, $e->{id};   # and against each other within this run

    printf STDERR "+ %-34s %-22s %s%s\n", $e->{id}, $type, $expr,
        ($confirmed ? '   [confirmed on own vector]' : '') if $verbose;
    $written++;
    next unless $apply;

    # denotation: exists for entries that have NO expression, and validate.pl
    # fails a file carrying both. Where the sheet's looser wording said the
    # same thing -- "md5(base64_encode($plain))" against hx's "md5(base64($p))"
    # -- the expression supersedes it. Keep the old text inside the note so
    # nothing is lost, and record where it came from.
    my $retired = '';
    if (my $d = delete $e->{denotation}) {
        $retired = sprintf ' Superseded the denotation %s (source: %s), which validate.pl '
                 . 'forbids alongside an expression.',
                 (defined $d->{text} ? "\"$d->{text}\"" : '(none)'), ($d->{source} // 'unknown');
    }

    $e->{expression} = $expr;
    $e->{expression_proof} = {
        verified      => 'upstream',
        verified_at   => '2026-08-31',
        verified_with => 'hx Language Specification $Revision: 1.15$ (Waffle, Aug 2026), Appendix A',
        note          => "transcribed from the hx specification's Appendix A entry for mdxfind type "
                       . "$type ($hx->{$type}{index}), which states $hx->{$type}{raw}. Transcription, "
                       . "not reproduction, so this is upstream and not vector; run "
                       . "derive-expressions.pl to try to promote it. "
                       . ($confirmed
                          ? "An independent Digest:: computation of this string DOES reproduce this "
                          . "entry's own vector, checked 2026-08-31."
                          : "Not checkable locally: the construction uses functions RosettaExpr "
                          . "cannot compile, so this rests on upstream's word alone.") . $retired,
    };
    emit_entry($path, $e);
}

printf STDERR "\n%s: %d candidate entry/entries, %d %s\n",
    $PROG, $seen, $written, ($apply ? 'written' : 'would be written (no --apply)');
printf STDERR "  skipped %-32s %d\n", $_, $skip{$_} for sort keys %skip;
print  STDERR "  tiers are 'upstream'; now run derive-expressions.pl to promote\n" if $apply;
exit 0;
