#!/usr/bin/perl
#
# seed-hashpipe-vectors.pl -- give an entry that has no test vector the one
# hashpipe ships for the mdxfind type it names, and prove it by re-verifying it.
#
# WHY THIS EXISTS
#
# This is the third and last route into the entries that carry no vector at
# all. seed-vectors.pl reads the published example out of data/tools/*.yaml
# and seed-john-vectors.pl reads john's own source; between them they leave a
# residue that names an mdxfind type and NO john format, so john's source has
# nothing to offer it, and whose mdxfind inventory row has no example_vector
# either. hashpipe has one for all but a single registered type: `ht->example`
# is the last argument of every HT/HT_ALT/HT_ALT2/HTC/HTV/HTVC registration in
# hashpipe.c, and `hashpipe -T` reproduces all 1026 of them.
#
# WHY THE SOURCE AND NOT THE CATALOG
#
# CLAUDE.md's authority order: the source, then the binary's own output, then
# the specification, then HASH_TYPES.md. The vendored catalog is the weakest
# of the four and here it is also the stalest -- it publishes 1000 types as of
# v1.102 where the binary is v1.192 with 1026, so several of these types are
# not in it at all. `hashpipe -G` looked like the binary-output answer and is
# not: it GENERATES a vector for a type that has no ht->example and prints
# nothing for the ones that do (hashpipe.c, the `if (!ht->example)` branch).
#
# WHY THE SPLIT ON THE LAST COLON IS NOT A GUESS
#
# An example is "hash[:salt]:password" and a salt can contain a colon --
# SHA1MD5HUM's is "00- x 1". hashpipe's own self-test splits it with
# strrchr(ex, ':'), so this does the same. It is the tool's parse of the tool's
# own field, not a rule invented here.
#
# WHAT VERIFIES IT
#
# `hashpipe -c`, which verifies each line against its own leading TYPE label
# and runs no detection -- the per-line equivalent of `mdxfind -h '^TYPE$'`.
# One line per invocation, streams kept apart, and the EMITTED label compared
# with the one asked for: those three are the reading traps CLAUDE.md records,
# and the second is the one that makes a refusal look exactly like a pass.
# That -c is actually strict is not assumed here; tools/test-hashpipe-c.pl
# asserts it in 37 measurements, including every off-diagonal cell of
# md5^1..md5^5 and the batch path that leaked twice.
#
# WHY IT ALSO RUNS MDXFIND, AND WHY THAT DOES NOT GATE
#
# hashpipe is not a column in this repository; what a vector like this stands
# to promote is the MDXFIND block. So mdxfind is asked, pinned to the same
# type, and its answer is REPORTED -- but it does not gate the write, because
# a serialization mdxfind cannot read is still a true hash/plaintext pair for
# the algorithm and is exactly what makes the mdxfind gap a measured fact
# rather than an untested one. verify-vectors.pl owns tiers and has a solo
# fallback for the types whose report line does not echo what it was given.
#
# DEPENDENCIES: YAML::XS, tools/lib/RosettaEmit.pm, a hashpipe binary, a
# readable hashpipe.c, and optionally mdxfind. Run from anywhere.
#
# Generated by Claude Opus 5 on 2026-09-04

use strict;
use warnings;
use FindBin qw($RealBin);
use lib "$RealBin/lib";
use YAML::XS ();
use Getopt::Long qw(GetOptions);
use File::Path qw(make_path);
use File::Basename qw(basename);
use Time::HiRes qw(time);
use RosettaEmit qw(emit_entry);
use RosettaTools qw(tool_path tool_env_help);

my $PROG = basename($0);
my $ROOT = "$RealBin/..";
my $SRC_DEFAULT = '/usr/local/src/sec/crack/hashpipe/hashpipe.c';

sub usage {
    print <<"USAGE";
Usage: $PROG --report | --apply | -n [options]

   --report          harvest, verify with hashpipe, print the result, write nothing
   --apply           harvest, verify, write the vectors hashpipe reproduced
   -n, --dry-run     list the harvested candidates; run no cracker

   --only ID         just this entry (repeatable)
   --limit N         stop after N candidates; for smoke tests
   --hashpipe PATH   hashpipe binary  (@{[ tool_env_help('hashpipe') ]})
   --mdxfind PATH    mdxfind binary   (@{[ tool_env_help('mdxfind') ]})
   --src PATH        hashpipe.c       (default: $SRC_DEFAULT)
   --no-mdxfind      skip the informational mdxfind probe
   --algorithms DIR  curated entries  (default: data/algorithms)
   --work DIR        scratch files    (default: tmp/seed-hashpipe-vectors)
   --timeout SECS    per invocation   (default: 120)
   -v, --verbose     per-candidate progress on stderr (repeatable)
   -h, --help        this help

   Only entries with NO vector at all are targeted, and only those naming an
   mdxfind type hashpipe ships an example for. A vector is stored when
   hashpipe, pinned to that type with -c, reproduces it at the iteration count
   the entry declares. mdxfind is asked too and its answer reported; it does
   not gate the write. Tiers are never touched -- run verify-vectors.pl
   afterwards to promote what this makes provable.

   Exit 0 success, 1 error, 2 usage.
USAGE
}

my ($report, $apply, $dry, $hashpipe, $mdxfind, $src, $algdir, $workdir);
my (@only, $help, $limit, $no_mdxfind);
my $timeout = 120;
my $verbose = 0;
GetOptions(
    'report'       => \$report,
    'apply'        => \$apply,
    'n|dry-run'    => \$dry,
    'only=s'       => \@only,
    'limit=i'      => \$limit,
    'hashpipe=s'   => \$hashpipe,
    'mdxfind=s'    => \$mdxfind,
    'src=s'        => \$src,
    'no-mdxfind'   => \$no_mdxfind,
    'algorithms=s' => \$algdir,
    'work=s'       => \$workdir,
    'timeout=i'    => \$timeout,
    'v|verbose+'   => \$verbose,
    'h|help'       => \$help,
) or do { usage(); exit 2 };

if ($help) { usage(); exit 0 }
unless ($report || $apply || $dry) { usage(); exit 2 }

$hashpipe = tool_path('hashpipe', $hashpipe);
$mdxfind  = tool_path('mdxfind',  $mdxfind);
$src    //= $SRC_DEFAULT;
$algdir  //= "$ROOT/data/algorithms";
$workdir //= "$ROOT/tmp/seed-hashpipe-vectors";
make_path($workdir) unless -d $workdir;
my %only = map { $_ => 1 } @only;

#-----------------------------------------------------------------------
# hashpipe's registration table.
#
# Six macros register a type and the example is the LAST argument of every
# one of them:
#
#   HT(name, len, flags, fn, ex)        HTC(name, len, flags, chain, ex)
#   HT_ALT(name, len, flags, fn, alt, ex)   HTV(name, flags, vfn, ex)
#   HT_ALT2(name, len, flags, fn, alt, alt2, ex)  HTVC(name, flags, vfn, vc, ex)
#
# so the call is scanned to its closing paren, with strings stepped over, and
# the last string literal in the argument list is the example. A call with no
# string after the name is a type with no vector, which is what PARALLEL is
# and why `hashpipe -T` skips it.

# skip_to_close($txt, $i) - $i is just past the opening paren; return the index
# of its match, with strings and both comment styles stepped over.
sub skip_to_close {
    my ($txt, $i) = @_;
    my $len   = length $txt;
    my $depth = 1;
    while ($i < $len) {
        my $ch  = substr($txt, $i, 1);
        my $two = substr($txt, $i, 2);
        if ($two eq '/*') { my $e = index($txt, '*/', $i + 2); $i = $e < 0 ? $len : $e + 2; next }
        if ($two eq '//') { my $e = index($txt, "\n", $i);     $i = $e < 0 ? $len : $e + 1; next }
        if ($ch eq '"' || $ch eq "'") {
            my $q = $ch; $i++;
            while ($i < $len) {
                my $c = substr($txt, $i, 1);
                last if $c eq $q;
                $i += ($c eq "\\") ? 2 : 1;
            }
            $i++;
            next;
        }
        $depth++ if $ch eq '(';
        if ($ch eq ')') { $depth--; return $i if $depth == 0 }
        $i++;
    }
    return -1;
}

# c_unescape($body) - the bytes a C string literal denotes, given its INSIDE.
sub c_unescape {
    my ($s) = @_;
    my ($out, $i, $len) = ('', 0, length $s);
    while ($i < $len) {
        my $ch = substr($s, $i, 1);
        if ($ch ne "\\") { $out .= $ch; $i++; next }
        my $esc = substr($s, $i + 1, 1);
        $i += 2;
        if    ($esc eq 'n') { $out .= "\n" }
        elsif ($esc eq 't') { $out .= "\t" }
        elsif ($esc eq 'r') { $out .= "\r" }
        elsif ($esc eq 'x') {
            my $h = '';
            $h .= substr($s, $i++, 1)
                while $i < $len && substr($s, $i, 1) =~ /[0-9a-fA-F]/ && length($h) < 2;
            return undef unless length $h;
            $out .= chr(hex $h);
        }
        elsif ($esc =~ /[0-7]/) {
            my $o = $esc;
            $o .= substr($s, $i++, 1)
                while $i < $len && substr($s, $i, 1) =~ /[0-7]/ && length($o) < 3;
            $out .= chr(oct $o);
        }
        else { $out .= $esc }
    }
    return $out;
}

my %EXAMPLE;
sub load_examples {
    open my $fh, '<:raw', $src or do {
        print STDERR "$PROG: cannot read hashpipe source $src: $!\n"; exit 1;
    };
    my $txt = do { local $/; <$fh> };          # $/ is the input record separator
    close $fh;
    my $n = 0;
    while ($txt =~ /\bHT(?:_ALT2?|C|V|VC)?\s*\(\s*"((?:[^"\\]|\\.)*)"\s*,/g) {
        my $name  = c_unescape($1);
        my $start = pos $txt;
        my $close = skip_to_close($txt, $start);
        next if $close < 0;
        my $args  = substr($txt, $start, $close - $start);
        my @lit   = $args =~ /"((?:[^"\\]|\\.)*)"/g;
        next unless @lit;
        my $ex = c_unescape($lit[-1]);
        next unless defined $ex && length $ex;
        # Uppercase for the lookup: john and the sheet are both inconsistent
        # about case, so the corpus is not guaranteed to spell a type as the
        # tool does. The tool's own spelling is what gets pinned.
        $EXAMPLE{ uc $name } = { name => $name, example => $ex };
        $n++;
    }
    return $n;
}

#-----------------------------------------------------------------------
# Verification.

sub write_file {
    my ($path, @lines) = @_;
    open my $fh, '>', $path or die "$PROG: cannot write $path: $!\n";
    print {$fh} "$_\n" for @lines;
    close $fh;
    return $path;
}

# run_capture($secs, @argv) - (exit, stdout). stderr is DELIBERATELY not
# merged: `hashpipe -c` echoes a REFUSED line to stderr verbatim, so a merged
# stream is consistent with both a pass and a refusal and cannot tell you which.
sub run_capture {
    my ($secs, @argv) = @_;
    my $out = '';
    my $pid = open(my $fh, '-|');
    defined $pid or return (-1, '');
    if (!$pid) {
        open STDERR, '>', '/dev/null';
        exec { $argv[0] } @argv or exit 127;
    }
    my $killed = 0;
    eval {
        local $SIG{ALRM} = sub { $killed = 1; kill 'KILL', $pid; die "timeout\n" };
        alarm $secs;
        local $/;
        $out = <$fh> // '';
        alarm 0;
    };
    alarm 0;
    close $fh;
    return ($killed ? -2 : ($? >> 8), $out);
}

# hashpipe_verifies($type, $hash, $pass, $iter) - one line, pinned to its own
# label, stdout only. Returns (ok, reason).
sub hashpipe_verifies {
    my ($type, $hash, $pass, $iter) = @_;
    (my $safe = $type) =~ s/[^A-Za-z0-9._-]/_/g;
    # Ask BARE and let the tool say what depth matched: the emitted label is
    # bare where the input was bare or x01, mdxfind's own convention.
    my $in = write_file("$workdir/hp.$safe.in", "$type $hash:$pass");
    my ($code, $out) = run_capture($timeout, '/bin/sh', '-c',
        sprintf('%s -c < %s 2>/dev/null', quotemeta($hashpipe), quotemeta($in)));
    return (0, 'timeout') if $code == -2;
    for my $line (split /\n/, $out) {
        next unless $line =~ /^\Q$type\E(?:x(\d+))?\s+(.+)$/;
        # The suffix is part of the identity. A bare emission is the FIRST
        # iteration stated by the tool, so it reads as 1 and not as "unknown".
        my $got = defined $1 ? $1 + 0 : 1;
        return (0, "verified at x$got, entry declares x$iter") unless $got == $iter;
        return (1, '') if $2 eq "$hash:$pass";
        return (0, 'reproduced a different string');
    }
    return (0, 'refused');
}

# mdxfind_reads($type, $hash, $pass, $iter, $salted) - informational only.
sub mdxfind_reads {
    my ($type, $hash, $pass, $iter, $salted) = @_;
    (my $safe = $type) =~ s/[^A-Za-z0-9._-]/_/g;
    my $hf = write_file("$workdir/mx.$safe.hash", $hash);
    my $wf = write_file("$workdir/mx.$safe.word", $pass);
    my ($code, $out) = run_capture($timeout, $mdxfind,
        '-h', "^\Q$type\E\$", ($salted ? '-F' : '-f'), $hf, '-i', $iter, $wf);
    return 'timeout' if $code == -2;
    for my $line (split /\n/, $out) {
        next unless $line =~ /^\Q$type\E(?:x(\d+))?\s+(.+)$/;
        my $got = defined $1 ? $1 + 0 : $iter;
        next unless $got == $iter;
        # An exact echo is the strong answer. mdxfind does not always echo what
        # it was given -- a type whose salt rides INSIDE the hash field prints
        # "(null)" in the salt slot -- so a line that names the pinned type and
        # ends in this plaintext, with one hash in the file, is reported as a
        # weaker "yes (re-serialized)" rather than silently as either.
        return 'yes' if $2 eq "$hash:$pass";
        return 'yes (re-serialized)' if $2 =~ /(?:^|:)\Q$pass\E$/;
    }
    return 'no';
}

#-----------------------------------------------------------------------
# Targets.

my $nex = load_examples();
printf STDERR "%s: %d hashpipe type(s) with an example in %s\n", $PROG, $nex, $src
    if $verbose;

my $mx_inv = eval { YAML::XS::LoadFile("$ROOT/data/tools/mdxfind.yaml") };
my %MX_SALTED;
if ($mx_inv) {
    for my $t (@{ $mx_inv->{types} }) {
        $MX_SALTED{ uc $t->{name} } = 1
            if grep { $_ eq 's' || $_ eq 'u' } @{ $t->{flags} || [] };
    }
}
else {
    print STDERR "$PROG: cannot load the mdxfind inventory; assuming no type is salted.\n";
}

opendir(my $dh, $algdir) or do { print STDERR "$PROG: cannot read $algdir: $!\n"; exit 1 };
my @files = sort grep { /\.yaml$/ } readdir $dh;
closedir $dh;

my (@cand, @noscore);
my $targets = 0;

for my $f (@files) {
    my $path = "$algdir/$f";
    my $e = eval { YAML::XS::LoadFile($path) };
    unless ($e) { print STDERR "$PROG: cannot load $path: $@\n"; exit 1 }
    my $id = $e->{id} // ($f =~ s/\.yaml$//r);
    next if %only && !$only{$id};
    next if ($e->{status} // '') eq 'merged';
    next if $e->{vectors} && @{ $e->{vectors} };
    my @types = @{ $e->{tools}{mdxfind}{types} || [] };
    next unless @types;
    $targets++;

    my $hit;
    for my $t (@types) {
        my $x = $EXAMPLE{ uc $t } or next;
        # hashpipe's own self-test splits the example with strrchr(ex, ':').
        my $i = rindex($x->{example}, ':');
        next if $i <= 0;
        my ($hash, $pass) = (substr($x->{example}, 0, $i),
                             substr($x->{example}, $i + 1));
        next unless length $hash && length $pass;
        next if "$hash$pass" =~ /[\r\n]/;
        $hit = {
            id   => $id, path => $path, entry => $e,
            type => $x->{name},
            iter => ($e->{tools}{mdxfind}{iterations} // 1),
            salted => ($MX_SALTED{ uc $t } ? 1 : 0),
            hash => $hash, pass => $pass,
        };
        last;
    }
    if ($hit) { push @cand, $hit }
    else      { push @noscore, $id }
}

#-----------------------------------------------------------------------
# Run.

my $started = time;
my (@ok, @bad);
my $n = 0;

printf "# %s -- %d entr%s with no vector naming an mdxfind type; %d with a hashpipe example, %d without\n",
    $PROG, $targets, ($targets == 1 ? 'y' : 'ies'), scalar @cand, scalar @noscore;
print "# columns: result, entry, type, hashpipe, mdxfind, hash, pass\n";

for my $c (@cand) {
    last if $limit && $n >= $limit;
    $n++;

    if ($dry) {
        printf "PLAN\t%s\t%s\t-\t-\t%s\t%s\n", $c->{id}, $c->{type}, $c->{hash}, $c->{pass};
        next;
    }

    my ($good, $why) = hashpipe_verifies($c->{type}, $c->{hash}, $c->{pass}, $c->{iter});
    my $mx = ($no_mdxfind || !$good) ? '-'
           : mdxfind_reads($c->{type}, $c->{hash}, $c->{pass}, $c->{iter}, $c->{salted});
    $c->{mdxfind} = $mx;

    printf STDERR "-   %-24s %-22s hashpipe %-10s mdxfind %s\n",
        $c->{id}, $c->{type}, ($good ? 'verified' : "FAILED"), $mx if $verbose;

    if ($good) {
        push @ok, $c;
        printf "OK\t%s\t%s\tverified\t%s\t%s\t%s\n",
            $c->{id}, $c->{type}, $mx, $c->{hash}, $c->{pass};
    }
    else {
        push @bad, [$c, $why];
        printf "FAIL\t%s\t%s\t%s\t-\t%s\t%s\n",
            $c->{id}, $c->{type}, $why, $c->{hash}, $c->{pass};
    }
}

print "SKIP\t$_\t-\tno hashpipe example\t-\t-\t-\n" for @noscore;

#-----------------------------------------------------------------------
# Write.

my $written = 0;
if ($apply) {
    my %touched;
    for my $c (@ok) {
        push @{ $c->{entry}{vectors} }, {
            hash   => $c->{hash},
            pass   => $c->{pass},
            source => 'hashpipe',
        };
        $touched{ $c->{path} } = $c->{entry};
    }
    $written += emit_entry($_, $touched{$_}) for sort keys %touched;
}

my $elapsed = time - $started;
printf STDERR "%s: %d candidate(s) examined, %d verified by hashpipe, %d failed, %d file(s) written in %.1fs\n",
    $PROG, $n, scalar @ok, scalar @bad, $written, $elapsed;

if (@ok && !$no_mdxfind) {
    my $yes = grep { $_->{mdxfind} =~ /^yes/ } @ok;
    printf STDERR "%s: mdxfind reads %d of the %d, pinned to the same type. The rest are a MEASURED gap between the two tools, not an untested one.\n",
        $PROG, $yes, scalar @ok;
}
if ($apply && $written) {
    printf STDERR "%s: tiers untouched. Promote what is now provable with:\n    ./tools/verify-vectors.pl --tool mdxfind -v\n", $PROG;
}

exit 0;
