#!/usr/bin/perl
#-----------------------------------------------------------------------
#
# Name: status-sweep.pl
# Description: derive status: ok / needs-review from what an entry proves,
#              instead of leaving the importer's blanket needs-review on it
# Category: cracking-rosetta curator
#
# Project: cracking-rosetta | Phase: 7 - pre-publication readiness
#
#-----------------------------------------------------------------------
# METHODOLOGY AND WHY THIS EXISTS
#
# A FIELD THAT IS TRUE OF EVERYTHING SAYS NOTHING
#
# The sheet importer stamped status: needs-review on all 646 entries it
# created, seed-upstream.pl kept doing it, and by 2026-08-30 it was on 783 of
# 783. It renders into every row of dist/rosetta.csv -- the file the README
# points a former spreadsheet user at -- so the first impression of a project
# whose whole argument is calibrated trust is a column saying nothing here has
# been reviewed. It was literally true and completely uninformative.
#
# The tiers already say how well each mapping is known. What status can add,
# and only if it is rare, is "a human still owes this entry a decision".
#
# THE RULE IS DERIVED, NEVER TYPED
#
# Same principle as the category work: propose only what a rule can defend.
# An entry is 'ok' when nothing about it is outstanding --
#
#   * every tool block it carries is at tier vector or absent. upstream and
#     asserted are claims nobody here reproduced, which is exactly the
#     backlog this field should point at;
#   * it has at least one test vector, because an entry with none cannot be
#     promoted by anything;
#   * if it states an expression, that expression is proven -- an expression
#     at tier upstream that does not reproduce the entry's own vectors is a
#     known open item, not a finished row;
#   * no relation out of it is a duplicate-of with distinction: none, which
#     is the model's way of saying a merge is still owed.
#
# Anything else stays needs-review, and the report says which clause held it
# there, so the field is a queue rather than a verdict.
#
# WHY IT DOES NOT WRITE A REASON INTO THE ENTRY
#
# Every reason is recomputable from the entry in microseconds, and a note
# recording one would be a second copy free to go stale -- the same argument
# that keeps counts out of STATE.md. The reasons belong in this report.
#
# TOMBSTONES ARE SKIPPED
#
# status: merged is not a review state, and a tombstone asserts nothing that
# could be reviewed. Touching one would also be an error the gate catches.
#
# DEPENDENCIES
#   perl, YAML::XS, tools/lib/RosettaEmit.pm
#
#-----------------------------------------------------------------------
# Generated by Claude Opus 5 on 2026-08-30

use strict;
use warnings;

use File::Basename qw(basename);
use FindBin qw($RealBin);
use Getopt::Long qw(GetOptions);
use YAML::XS ();

use lib "$RealBin/lib";
use RosettaEmit qw(emit_entry);

my $PROG = basename($0);
my $ROOT = "$RealBin/..";

sub usage {
    print STDERR <<"END_USAGE";

Usage: $PROG [options]

   --algorithms DIR  curated entries (default: data/algorithms)
   --only ID         just this entry (repeatable)
   --apply           write the derived status; without it, nothing is written
   -v, --verbose     list every entry that would change, with the reason
   -h, --help        this help

   Derives status: from what the entry proves. 'ok' means nothing is
   outstanding: every tool block is at tier vector or absent, there is a test
   vector, any expression is proven, and no duplicate-of/none edge is open.
   Everything else is needs-review, and the reason is reported.

   Exit 0 success, 1 error, 2 usage.

END_USAGE
    return;
}

my ($algdir, $apply, $help);
my @only;
my $verbose = 0;
GetOptions(
    'algorithms=s' => \$algdir, 'only=s' => \@only, 'apply' => \$apply,
    'v|verbose+' => \$verbose, 'h|help' => \$help,
) or do { usage(); exit 2 };
if ($help) { usage(); exit 0 }
# No arguments at all is a request for help, not a whole-corpus rewrite.
if (!@ARGV && !$apply && !$verbose && !@only && !defined $algdir) {
    usage();
    exit 2;
}
$algdir //= "$ROOT/data/algorithms";
my %scope = map { $_ => 1 } @only;

#-----------------------------------------------------------------------
# reasons_for($entry) - the clauses that hold an entry at needs-review.
#
# Returns a list, not a boolean, because the report is the useful half: 57
# entries all saying "needs-review" is the problem this script exists to fix,
# and "13 mdxfind asserted, 11 no vector" is the queue it turns them into.

sub reasons_for {
    my ($d) = @_;
    my @why;

    push @why, 'no vector'
        unless ref $d->{vectors} eq 'ARRAY' && @{ $d->{vectors} };

    for my $t (qw(hashcat john mdxfind)) {
        my $b = $d->{tools}{$t};
        next unless ref $b eq 'HASH';
        # A block with identifiers but no tier defaults to asserted the same
        # way render.pl reads it, so an omitted tier cannot pass as proven.
        my $tier = $b->{verified} // 'asserted';
        push @why, "$t $tier" unless $tier eq 'vector' || $tier eq 'absent';
    }

    push @why, 'expression below vector'
        if defined $d->{expression} && length $d->{expression}
        && (ref $d->{expression_proof} ne 'HASH'
            || ($d->{expression_proof}{verified} // '') ne 'vector');

    push @why, 'open duplicate'
        if grep { ref $_ eq 'HASH' && ($_->{distinction} // '') eq 'none' }
           @{ ref $d->{relations} eq 'ARRAY' ? $d->{relations} : [] };

    return @why;
}

#-----------------------------------------------------------------------
# Walk.

opendir(my $dh, $algdir) or do {
    print STDERR "$PROG: cannot read $algdir: $!\n";
    exit 1;
};
my @files = sort grep { /\.yaml$/ } readdir $dh;
closedir $dh;

my $start = time;
my ($seen, $tombs, $changed, %to, %why_count) = (0, 0, 0);
my @moved;

for my $file (@files) {
    my $stem = $file; $stem =~ s/\.yaml$//;
    next if %scope && !$scope{$stem};
    my $path = "$algdir/$file";

    my $d = eval { YAML::XS::LoadFile($path) };
    if ($@ || ref $d ne 'HASH') {
        print STDERR "$PROG: $file does not load; skipped\n";
        next;
    }
    if (($d->{status} // '') eq 'merged') { $tombs++; next }
    $seen++;

    my @why    = reasons_for($d);
    my $want   = @why ? 'needs-review' : 'ok';
    my $have   = $d->{status} // 'ok';
    $to{$want}++;
    $why_count{$_}++ for @why;

    next if $have eq $want;
    $changed++;
    push @moved, { id => $stem, from => $have, to => $want, why => [@why] };

    next unless $apply;
    $d->{status} = $want;
    emit_entry($path, $d);
}

#-----------------------------------------------------------------------
# Report. Counts and timing on stderr per house convention; the list of
# entries still needing a human goes to stdout, where it can be piped.

if ($verbose) {
    for my $m (sort { $a->{id} cmp $b->{id} } @moved) {
        printf STDERR "-   %-38s %s -> %s%s\n", $m->{id}, $m->{from}, $m->{to},
            (@{ $m->{why} } ? ' (' . join('; ', @{ $m->{why} }) . ')' : '');
    }
}

printf STDERR "- %d entry/entries examined%s in %ds\n", $seen,
    ($tombs ? " ($tombs tombstone(s) skipped)" : ''), time - $start;
printf STDERR "-   ok %d, needs-review %d; %d would change%s\n",
    $to{ok} // 0, $to{'needs-review'} // 0, $changed,
    ($apply ? ' and were written' : '');
printf STDERR "-   %-28s %d\n", $_, $why_count{$_}
    for sort { $why_count{$b} <=> $why_count{$a} || $a cmp $b } keys %why_count;
print STDERR "- nothing written; re-run with --apply\n" if !$apply && $changed;
print STDERR "- run tools/validate.pl and tools/fmt.pl --all --check\n" if $apply;

exit 0;
