#!/usr/bin/perl
#-----------------------------------------------------------------------
#
# Name: test-hashpipe-label.pl
# Description: assert that a type whose name ends in `x` is named to
#              hashpipe unambiguously, and that a bare name is not
#
# Project: cracking-rosetta | Phase: 5 - promote mappings to tier 'vector'
#
#-----------------------------------------------------------------------
# METHODOLOGY AND WHY THIS EXISTS
#
# TWELVE mdxfind/hashpipe type names end in a bare `x`, and for at least four
# of them the name WITHOUT the `x` is also a real type. hashpipe emits
# `<name>x%02d` when the depth is non-zero, so its OUTPUT tells the two apart
# perfectly. Its INPUT parse does not: a bare `MD5SHA1x` is taken as a suffix
# marker with a missing number and answered as `MD5SHA1` (e178), a different
# algorithm.
#
# Measured 2026-09-16 against hashpipe RCS 1.194, on one digest:
#
#     MD5SHA1      ->  MD5SHA1x01     e178 at depth 1
#     MD5SHA1x     ->  MD5SHA1x01     e178 again -- NOT what was asked
#     MD5SHA1xx01  ->  MD5SHA1xx01    e702, which is what was asked
#
# Of the twelve, eleven answer as the shorter type and one is refused.
#
# WHAT THIS COST WAS COVERAGE, NEVER CORRECTNESS, and that is worth stating
# because it decides how alarmed to be. The matchers in attach-mdxfind-ahead,
# seed-orphans and seed-hashpipe-vectors all compare the emitted label against
# the type they asked for, so they REFUSED the other type's echo and withheld
# the claim. The question was wrong; the answer was still checked.
#
# THREE ASSERTIONS, AND THE MIDDLE ONE IS THE POINT.
#
#   1. A trailing-`x` type asked with the label the helper builds comes back
#      as ITSELF.
#   2. The same type asked BARE comes back as something else -- the defect,
#      asserted so that hashpipe fixing it shows up here as a failure rather
#      than as silence. Without this, "we name it correctly" and "the bare
#      name would have worked anyway" are the same reading.
#   3. An ordinary type is left alone: the helper must not append a depth to
#      a name that does not end in `x`, or every other pin changes meaning.
#
# It needs a hashpipe with MD5SHA1 and MD5SHA1x, so it is NOT in CI --
# validate.yml deliberately runs no cracker -- and it skips LOUDLY.
#
# USAGE
#   perl tools/test-hashpipe-label.pl            run the assertions
#   perl tools/test-hashpipe-label.pl --verbose  print each case
#   HASHPIPE= overrides where the binary is looked for.
#   Exit 0 all assertions passed (or skipped), 1 one or more failed.
#
# DEPENDENCIES
#   perl, tools/lib/RosettaTools.pm, a hashpipe with e178 and e702
#
#-----------------------------------------------------------------------
# Generated by Claude Opus 5 on 2026-09-16

use strict;
use warnings;
use FindBin qw($RealBin);
use lib "$RealBin/lib";
use RosettaTools qw(tool_path hashpipe_label);
use IPC::Open3;
use Symbol 'gensym';

my $PROG = 'test-hashpipe-label.pl';
if (grep { /^(?:-h|--help)$/ } @ARGV) {
    print <<"USAGE";

Usage: $PROG [--verbose]

   -v, --verbose     print each case's outcome
   -h, --help        this help

   Asserts that RosettaTools::hashpipe_label names a trailing-`x` type
   unambiguously to hashpipe -c, that the bare name is still answered as a
   DIFFERENT type, and that an ordinary name is passed through untouched.

   Needs a hashpipe (\$HASHPIPE, else the resolver default). Skips loudly when
   there is none. Not run in CI: validate.yml runs no cracker.

   Exit 0 all assertions passed or skipped, 1 one or more failed.
USAGE
    exit 0;
}

my $verbose = grep { /^-v$|^--verbose$/ } @ARGV;
my $HP = tool_path('hashpipe');
unless (-x $HP) {
    print STDERR "- SKIPPED: no hashpipe at $HP (set HASHPIPE= to point at one)\n";
    print STDERR "-   This is a skip, NOT a pass: the label rule was not checked.\n";
    exit 0;
}

# md5(sha1("password123")) -- reproduced by e178 at depth 1 and, because the
# `x` family coincides with its base at parameter 1, by e702 as well. That
# coincidence is exactly why the label has to be unambiguous: the DIGEST
# cannot tell the callers apart, so only the name can.
my $HASH  = 'e933f35ad585ac6753ee607ab8fd0a4d';
my $PLAIN = 'password123';

# ask($label) - one line in, stdout and stderr kept APART, the emitted type
# name returned. A merged stream is consistent with a pass and with a refusal
# alike, which is the hashpipe -c reading trap CLAUDE.md records.
sub ask {
    my ($label) = @_;
    my ($w, $r, $e) = (undef, undef, gensym);
    my $pid = open3($w, $r, $e, $HP, '-c', '-t', '1');
    print {$w} "$label $HASH:$PLAIN\n";
    close $w;
    my $out = do { local $/; <$r> // '' };
    my $err = do { local $/; <$e> // '' };
    waitpid($pid, 0);
    return '' unless $out =~ /^(\S+)\s/;
    return $1;
}

my ($pass, $fail) = (0, 0);
sub ok {
    my ($cond, $what, $detail) = @_;
    if ($cond) { $pass++; print STDERR "- ok    $what\n" if $verbose }
    else       { $fail++; print STDERR "- FAIL  $what\n";
                 print STDERR "-       $detail\n" if defined $detail }
}

my $type = 'MD5SHA1x';
my $askd = hashpipe_label($type);
ok($askd eq 'MD5SHA1xx01',
   "hashpipe_label('$type') appends an explicit depth", "got '$askd'");

my $got = ask($askd);
ok($got =~ /^\Q$type\Ex\d+$/,
   "asked '$askd', hashpipe answers as $type",
   "got '$got'");

my $bare = ask($type);
ok($bare ne '' && $bare !~ /^\Q$type\Ex\d+$/,
   "asked bare '$type', hashpipe answers as a DIFFERENT type -- the defect "
 . "this exists to pin down",
   "got '$bare'; if this now equals the type asked for, hashpipe has FIXED "
 . "its input parse and the helper can be retired");

my $plainlbl = hashpipe_label('MD5SHA1');
ok($plainlbl eq 'MD5SHA1',
   "an ordinary name is passed through untouched", "got '$plainlbl'");
my $pgot = ask($plainlbl);
ok($pgot =~ /^MD5SHA1x\d+$/,
   "and still round-trips as itself", "got '$pgot'");

printf STDERR "- %s: %d assertion(s) passed, %d failed\n", $PROG, $pass, $fail;
if ($fail) {
    print STDERR <<'WHY';
-
- If the BARE case started answering as the type asked for, hashpipe has
-   fixed its input parse. That is good news, not a regression: retire
-   RosettaTools::hashpipe_label and delete the record in
-   data/upstream-disagreements.yaml rather than working around a defect that
-   is gone.
- If the SUFFIXED case failed, the helper or hashpipe's emitter has changed
-   shape. Check hashpipe.c's `x%02d` label block before changing anything
-   here.
WHY
}
exit($fail ? 1 : 0);
