#!/usr/bin/perl
#-----------------------------------------------------------------------
#
# Name: test-attach-mdxfind-ahead.pl
# Description: assert what attach-mdxfind-ahead.pl REFUSES, which is the half
#              of it nothing else can see
# Category: cracking-rosetta test
#
# Project: cracking-rosetta | Phase: 8 - the inventory is ahead of the binary
#
#-----------------------------------------------------------------------
# METHODOLOGY AND WHY THIS EXISTS
#
# The tool's happy path is self-announcing: it prints what it attached and
# validate.pl checks the result. Its REFUSALS are invisible when they work --
# a type it declined to propose looks exactly like a type nothing matched --
# and every one of them is load-bearing:
#
#   * a type the INSTALLED binary HAS must not come through here at tier
#     `upstream`, because discover-mdxfind.pl can prove it outright;
#   * an entry already at tier `vector` must be BLOCKED, because a tool block
#     carries ONE tier for every identifier in it and adding an `upstream`
#     identifier either overstates the new one or understates the old ones;
#   * a proposal whose PINNED re-run does not come back must write nothing,
#     which is the entire difference between this and trusting detection;
#   * a transcode hint is a hint, so a line that does not verify must write
#     nothing either.
#
# WHY IT IS NOT IN CI, AND WHY IT SKIPS LOUDLY
#
# It needs a hashpipe and an mdxfind binary. validate.yml deliberately runs no
# cracker, so this is a local gate -- and a test that silently passes when its
# instrument is missing is worse than no test, so an absent binary is a SKIP
# with a message and exit 0, never a quiet pass.
#
# THE FIXTURE IS A DIRECTORY, NOT THE CORPUS
#
# --algorithms points the tool at a scratch tree, so nothing here can touch
# data/algorithms/. The INVENTORY is the real one on purpose: what counts as
# "ahead of the binary" is a fact about this host that a fixture cannot
# usefully fake, and faking it would test the fixture rather than the rule.
# That does mean the whole file skips when the inventory and the binary agree
# -- which is the day the tool has nothing to do anyway, and it says so.
#
# USAGE
#   tools/test-attach-mdxfind-ahead.pl [-v]
#
#-----------------------------------------------------------------------
# Generated by Claude Opus 5 on 2026-09-05

use strict;
use warnings;

use File::Basename qw(basename);
use File::Path qw(make_path remove_tree);
use FindBin qw($RealBin);
use YAML::XS qw(LoadFile);

use lib "$RealBin/lib";
use RosettaTools qw(tool_path tool_version);

my $PROG = basename($0);
my $ROOT = "$RealBin/..";
my $DIR  = "$ROOT/tmp/attach-ahead-test";
my $verbose = grep { $_ eq '-v' } @ARGV;

my ($pass, $fail) = (0, 0);
sub ok {
    my ($cond, $why) = @_;
    die "$PROG: ok() called with no description\n" unless defined $why && length $why;
    if ($cond) { $pass++; printf "ok   %s\n", $why }
    else       { $fail++; printf "FAIL %s\n", $why }
    return $cond ? 1 : 0;
}
sub skip_all {
    printf STDERR "- SKIP: %s\n", $_[0];
    printf "# skipped: %s\n", $_[0];
    exit 0;
}

#-----------------------------------------------------------------------
# Instruments.

my $HP = tool_path('hashpipe');
my $MX = tool_path('mdxfind');
skip_all("no hashpipe at $HP") unless -x $HP || `command -v $HP 2>/dev/null`;
skip_all("no mdxfind at $MX")  unless -x $MX || `command -v $MX 2>/dev/null`;
my $HP_VER = tool_version('hashpipe') or skip_all("$HP would not state a version");
my $MX_VER = tool_version('mdxfind')  or skip_all("$MX would not state a version");

make_path($DIR) unless -d $DIR;

my $inv = LoadFile("$ROOT/data/tools/mdxfind.yaml");
my %INV = map { $_->{name} => $_ } @{ $inv->{types} };
my %HAVE;
{
    my $h = `\Q$MX\E -h 2>&1 </dev/null`;
    $HAVE{$1} = 1 while $h =~ /^e\d+\s+\S+\s+(\S+)/mg;
}
skip_all("parsed no types from $MX -h") unless %HAVE;

# A type the inventory has and the binary does not, WITH an example. Picked
# from the data rather than named here, so this file does not go stale the day
# the binary catches up -- and picked by MEASURING rather than by taking the
# first alphabetically. hashpipe's detection path names the FIRST type that
# reproduces a digest, so an example whose digest a broader type also
# reproduces resolves to that other type and the positive control would fail
# for a reason that has nothing to do with this tool.
my $AHEAD;
for my $t (sort grep { !$HAVE{$_} && ($INV{$_}{example_vector} // '') ne '' }
                keys %INV) {
    my $v = $INV{$t}{example_vector};
    my $p = $INV{$t}{example_pass};
    (my $h = $v) =~ s/:\Q$p\E$// or next;
    open my $fh, '>', "$DIR/probe.txt" or last;
    print $fh "$h:$p\n";
    close $fh;
    my $out = `\Q$HP\E \Q$DIR/probe.txt\E 2>/dev/null`;
    next unless $out =~ /^\Q$t\E(?:x\d+)?\s/m;
    $AHEAD = $t;
    last;
}
skip_all("no type in the inventory is both absent from the installed mdxfind "
       . "($MX_VER) and self-identifying under hashpipe detection; either the "
       . "binary has caught up with $inv->{version}, or every ahead type's "
       . "example is claimed by a broader type")
    unless defined $AHEAD;

# A type BOTH have, also with an example: the scope refusal needs one.
my ($INSTALLED) = sort grep { $HAVE{$_} && ($INV{$_}{example_vector} // '') ne '' }
                       keys %INV;
skip_all("no shared type with an example") unless defined $INSTALLED;

printf STDERR "- ahead: %s   installed: %s   (mdxfind %s, inventory %s)\n",
    $AHEAD, $INSTALLED, $MX_VER, $inv->{version} // '?' if $verbose;

#-----------------------------------------------------------------------
# Fixtures. An entry is the minimum the tool reads: id, status, vectors, and
# optionally a tools.mdxfind block.

sub vector_of {
    my ($type) = @_;
    my $v = $INV{$type}{example_vector};
    my $p = $INV{$type}{example_pass};
    (my $h = $v) =~ s/:\Q$p\E$// or return;
    return ($h, $p, $v);
}

sub write_entry {
    my ($id, $hash, $pass_, %over) = @_;
    my $y = qq{id: "$id"\nname: "$id"\nstatus: "ok"\n};
    if ($over{mdxfind_tier}) {
        $y .= qq{tools:\n  mdxfind:\n    types: ["$over{mdxfind_type}"]\n}
            . qq{    verified: "$over{mdxfind_tier}"\n}
            . qq{    verified_at: "2026-01-01"\n}
            . qq{    verified_with: "a fixture"\n};
    }
    $y .= qq{vectors:\n  - hash: "$hash"\n    pass: "$pass_"\n    source: "fixture"\n};
    open my $fh, '>', "$DIR/algorithms/$id.yaml" or die "$PROG: $!\n";
    print $fh $y;
    close $fh;
    return;
}

sub reset_fixtures {
    remove_tree("$DIR/algorithms") if -d "$DIR/algorithms";
    make_path("$DIR/algorithms");
    return;
}

sub run_tool {
    my (@extra) = @_;
    my $cmd = sprintf('perl -I%s/lib %s/attach-mdxfind-ahead.pl --algorithms %s/algorithms %s 2>&1',
                      $RealBin, $RealBin, $DIR, join(' ', @extra));
    my $out = `$cmd`;
    return ($? >> 8, $out);
}

my ($AH_HASH, $AH_PASS, $AH_LINE) = vector_of($AHEAD);
my ($IN_HASH, $IN_PASS)           = vector_of($INSTALLED);
skip_all("$AHEAD publishes no usable example") unless defined $AH_HASH;
skip_all("$INSTALLED publishes no usable example") unless defined $IN_HASH;

#-----------------------------------------------------------------------
# 1. The happy path, so every refusal below is measured against something that
#    DOES fire. Without this a broken tool passes every negative assertion.

reset_fixtures();
write_entry('fix-ahead', $AH_HASH, $AH_PASS);
{
    my ($code, $out) = run_tool('--report');
    ok($code == 0, 'a run over a clean fixture exits 0');
    ok($out =~ /^\Q$AHEAD\E\s+->\s+fix-ahead\s/m,
       "positive control: $AHEAD is proposed for the entry carrying its vector");
}
{
    my ($code, $out) = run_tool('--apply');
    my $e = LoadFile("$DIR/algorithms/fix-ahead.yaml");
    my $blk = $e->{tools}{mdxfind} || {};
    ok((grep { $_ eq $AHEAD } @{ $blk->{types} || [] }) ? 1 : 0,
       '--apply writes the type onto the entry');
    ok(($blk->{verified} // '') eq 'upstream',
       'the tier is `upstream` and NOT `vector`: mdxfind did not run it');
    ok(($blk->{verified_with} // '') =~ /\Q$MX_VER\E/
         && ($blk->{verified_with} // '') =~ /\Q$HP_VER\E/,
       'verified_with names BOTH binaries, the one that could not and the one that did');
    ok(($blk->{note} // '') =~ /verify-vectors\.pl|seed-orphans\.pl/,
       'the note carries the command that promotes the claim');
}

#-----------------------------------------------------------------------
# 2. A type the INSTALLED binary has is out of scope here.

reset_fixtures();
write_entry('fix-installed', $IN_HASH, $IN_PASS);
{
    my ($code, $out) = run_tool('--report');
    ok($out !~ /^\Q$INSTALLED\E\s+->/m,
       "a type the installed binary HAS ($INSTALLED) is never proposed here");
    ok($out =~ /0 proposed/,
       'and nothing else is proposed in its place');
}

#-----------------------------------------------------------------------
# 3. An entry already at tier `vector` is BLOCKED, not extended.

reset_fixtures();
write_entry('fix-vector', $AH_HASH, $AH_PASS,
            mdxfind_tier => 'vector', mdxfind_type => $INSTALLED);
{
    my ($code, $out) = run_tool('--apply');
    ok($out =~ /BLOCKED/, 'an entry whose mdxfind block is at tier `vector` is blocked');
    my $e = LoadFile("$DIR/algorithms/fix-vector.yaml");
    my $blk = $e->{tools}{mdxfind} || {};
    ok(!grep({ $_ eq $AHEAD } @{ $blk->{types} || [] }),
       'and the type is NOT written, so the stronger tier is not diluted');
    ok(($blk->{verified} // '') eq 'vector', 'the existing tier is left alone');
}

#-----------------------------------------------------------------------
# 4. A type already on another entry is not moved.

reset_fixtures();
write_entry('fix-owner', $AH_HASH, $AH_PASS,
            mdxfind_tier => 'upstream', mdxfind_type => $AHEAD);
write_entry('fix-other', $AH_HASH, $AH_PASS);
{
    my ($code, $out) = run_tool('--report');
    ok($out !~ /^\Q$AHEAD\E\s+->\s+fix-other\s/m,
       'a type another entry already claims is not proposed again');
}

#-----------------------------------------------------------------------
# 5. A transcode hint is a hint: a line that does not verify writes nothing.

reset_fixtures();
write_entry('fix-hint', 'not-a-digest-at-all', 'nobody');
{
    open my $fh, '>', "$DIR/bad.tsv" or die "$PROG: $!\n";
    print $fh "$AHEAD\tfix-hint\tdeadbeef:wrongpass\n";
    close $fh;
    my ($code, $out) = run_tool('--apply', '--transcode', "$DIR/bad.tsv");
    ok($out =~ /1 proposed/ && $out =~ /1 refused/,
       'a transcode hint that does not verify is proposed and then REFUSED');
    my $e = LoadFile("$DIR/algorithms/fix-hint.yaml");
    ok(!exists $e->{tools} || !exists $e->{tools}{mdxfind},
       'and nothing is written to the entry');
}

#-----------------------------------------------------------------------
# 6. A transcode hint naming a type the inventory does not have is FATAL,
#    because a typo there would otherwise silently do nothing.

reset_fixtures();
write_entry('fix-hint2', $AH_HASH, $AH_PASS);
{
    open my $fh, '>', "$DIR/bogus.tsv" or die "$PROG: $!\n";
    print $fh "NO-SUCH-TYPE-HERE\tfix-hint2\tdeadbeef:x\n";
    close $fh;
    my ($code, $out) = run_tool('--apply', '--transcode', "$DIR/bogus.tsv");
    ok($code != 0, 'a transcode row naming an unknown type exits non-zero');
    ok($out =~ /is not a type of/, 'and says so');
}

#-----------------------------------------------------------------------
# 7. --report writes nothing at all.

reset_fixtures();
write_entry('fix-report', $AH_HASH, $AH_PASS);
{
    my $before = -s "$DIR/algorithms/fix-report.yaml";
    my ($code, $out) = run_tool('--report');
    ok(-s "$DIR/algorithms/fix-report.yaml" == $before,
       '--report leaves the entry byte-identical');
    ok($out =~ /no --apply/, 'and says it wrote nothing');
}

remove_tree($DIR);
printf STDERR "- %d passed, %d failed (hashpipe %s, mdxfind %s)\n",
    $pass, $fail, $HP_VER, $MX_VER;
exit($fail ? 1 : 0);
