#!/usr/bin/perl
#-----------------------------------------------------------------------
#
# Name: test-rosetta-tools.pl
# Description: assert when the --max-share guard has measured a share and
#              when it has only measured the size of its own corpus
# Category: cracking-rosetta test
#
# Project: cracking-rosetta | Phase: 7 - pre-publication readiness
#
#-----------------------------------------------------------------------
# METHODOLOGY AND WHY THIS EXISTS
#
# All three discovery tools hold back an identifier that matched more than
# --max-share percent of the corpus, on the theory that such an identifier is
# over-permissive rather than a mapping. The corpus is the TARGET set, not the
# repository, so any option that narrows the targets narrows the denominator.
#
# Under --only the denominator is 1. Every format that matched at all then has
# a 100% share, every one is "over-broad", and the entry is held with the
# reason "every matching format is over-broad" -- which is not what was
# measured and reads like a fact about the format. Measured 2026-09-05: saph
# on sapcodvnh256 was held that way, and the same run as
# --format '^saph$' --all measures its true share at 4 of 1561 and applies.
#
# The guard is right to withhold and wrong to explain, so this asserts the
# distinction rather than the guard: a share is measurable only when a SINGLE
# hit does not by itself trip the threshold. That is exactly 100 <= max_share
# * corpus, the guard's own arithmetic with hits fixed at 1, so the predicate
# cannot drift away from the rule it describes. The boundary cases are the
# point -- corpus 5 at 20% is the first denominator on which one hit is not a
# violation -- and so is --max-share 0, which holds back everything by
# construction and has therefore measured nothing either.
#
# The reason string is asserted too, negatively: it must not call an
# identifier over-broad when nothing established that it was.
#
# READING HASHCAT'S CRACK LINE is the second thing here, and it is here for
# the same reason: a wrong answer understates hashcat's support, which reads
# exactly like a mode that does not crack, so nothing downstream can catch it.
# hc_line_plain_is is only ever applied to a SOLO run -- one hash, one
# candidate -- so the hash's spelling does not have to match; the plaintext
# still does. It was wrong once, splitting on the FIRST colon, which on
# -m 22000's re-serialized line read the plaintext as
# "fc690c158264:f4747f87f9f4:hashcat-essid:hashcat!" and recorded a successful
# round trip as a failure. That exact line is the first assertion below.
#
# USAGE
#   perl -Itools/lib tools/test-rosetta-tools.pl
#   Exit 0 all assertions passed, 1 one or more failed, 2 usage.
#
# DEPENDENCIES
#   perl, tools/lib/RosettaTools.pm
#
#-----------------------------------------------------------------------
# Generated by Claude Opus 5 on 2026-09-05

use strict;
use warnings;

use FindBin qw($RealBin);
use lib "$RealBin/lib";
use RosettaTools qw(share_measurable share_unmeasurable_reason
                    hc_plain_is hc_line_plain_is);

my $PROG = 'test-rosetta-tools.pl';

if (@ARGV && $ARGV[0] =~ /^(-h|--help)$/) {
    print <<"USAGE";
Usage: $PROG

   Runs the assertion table. Takes no arguments.
   Exit 0 all passed, 1 one or more failed, 2 usage.
USAGE
    exit 0;
}
if (@ARGV) { print STDERR "$PROG: takes no arguments\n"; exit 2 }

# [ corpus, max_share, expected, why ]
my @CASES = (
    [ 1,    20, 0, '--only: one entry, so every hit is 100%'                ],
    [ 2,    20, 0, 'two entries: one hit is 50%'                            ],
    [ 4,    20, 0, 'four entries: one hit is 25%, still over 20'            ],
    [ 5,    20, 1, 'five entries: one hit is exactly 20%, not OVER it'      ],
    [ 6,    20, 1, 'six entries: one hit is under the threshold'            ],
    [ 1561, 20, 1, 'the full corpus, which is what the guard was written for'],
    [ 1,   100, 1, '--max-share 100: even a total share is not over it'     ],
    [ 2,    50, 1, 'boundary from the other side: one hit is exactly 50%'   ],
    [ 2,    49, 0, 'and one percent lower makes the same hit a violation'   ],
    [ 100,   1, 1, 'a strict threshold is still measurable on a big corpus' ],
    [ 99,    1, 0, 'but not once one hit exceeds it'                        ],
    [ 10,    0, 0, '--max-share 0 holds back every hit, so measures nothing'],
    [ 0,    20, 0, 'an empty corpus is not a denominator'                   ],
    [ -1,   20, 0, 'nor is a negative one'                                  ],
    [ undef, 20, 0, 'undef corpus is not a measurement'                     ],
    [ 10, undef, 0, 'undef threshold is not a measurement'                  ],
);

my ($pass, $fail) = (0, 0);

sub check {
    my ($ok, $why, $detail) = @_;
    if ($ok) { $pass++; printf "ok   %s\n", $why }
    else     { $fail++; printf "FAIL %s\n     %s\n", $why, $detail // '' }
}

for my $c (@CASES) {
    my ($corpus, $max_share, $want, $why) = @$c;
    my $got = share_measurable($corpus, $max_share) ? 1 : 0;
    check($got == $want, $why,
          sprintf('corpus=%s max_share=%s want %d got %d',
                  defined $corpus    ? $corpus    : '(undef)',
                  defined $max_share ? $max_share : '(undef)', $want, $got));
}

# The reason string is the whole point of the fix: the guard may withhold, but
# it may not report a fact it did not establish.
my $r = share_unmeasurable_reason('format', 1, 20);
check($r =~ /UNMEASURABLE/,  'the reason says the share was not measured', $r);
check($r !~ /over-broad/,    'and never calls the identifier over-broad',  $r);
check($r =~ /\b1 entry\b/,   'it names the corpus it actually had',        $r);
check($r =~ /--max-share 20/,'and the threshold that was applied',         $r);
check($r =~ /format/,        'and the kind of identifier it is about',     $r);
check($r =~ /--all/,         'and how to get a run that CAN measure it',   $r);

my $r4 = share_unmeasurable_reason('type', 4, 20);
check($r4 =~ /\b4 entries\b/, 'plural corpus reads correctly',             $r4);
check($r4 =~ /\b25%/,         'and it states the share one hit would be',  $r4);

#-----------------------------------------------------------------------
# Reading hashcat's crack line. [ line, want, expected, why ]

my $WPA22000 = '4d4fe7aac3a2cecab195321ceb99a7d0:fc690c158264:f4747f87f9f4:'
             . 'hashcat-essid:hashcat!';

my @LINES = (
    [ $WPA22000, 'hashcat!', 1,
      'the -m 22000 line that split on the first colon and lost the crack' ],
    [ $WPA22000, 'hashcat',  0,
      'and it is not satisfied by a plaintext that is merely a prefix'     ],
    [ $WPA22000, 'hashcat-essid', 0,
      'nor by an inner field that is not the last one'                     ],
    [ '5f4dcc3b5aa765d61d8327deb882cf99:password', 'password', 1,
      'the ordinary two-field crack line'                                  ],
    [ '05b56c69b512a1c641fc59d1070df60b:abc123:rosetta', 'rosetta', 1,
      'a salted line, where the salt is a field of its own'                ],
    [ 'deadbeef:a:b', 'a:b', 1,
      'a plaintext containing a colon still matches, widening the tail'    ],
    [ 'password', 'password', 0,
      'a bare echo of the candidate is not a crack: no hash field ahead'   ],
    [ '', 'password', 0,          'an empty line is not a crack'           ],
    [ 'deadbeef:', '', 1,         'an empty plaintext is a real field'     ],
    [ 'deadbeef:91b2e062b9', '$HEX[91b2e062b9]', 1,
      'the $HEX spelling on the vector side is unwrapped'                  ],
    [ 'deadbeef:$HEX[91b2e062b9]', '91b2e062b9', 1,
      'and on hashcat\'s side'                                             ],
    [ 'deadbeef:cafe', 'beef', 0,
      'a substring of a field is not a field'                              ],
);

for my $c (@LINES) {
    my ($line, $want, $expect, $why) = @$c;
    my $got = hc_line_plain_is($line, $want) ? 1 : 0;
    check($got == $expect, $why,
          sprintf('line=%s want=%s expected %d got %d', $line, $want, $expect, $got));
}

# hc_plain_is on its own: one $HEX wrapper either way and nothing more.
check( hc_plain_is('password', 'password'),          'identical plaintexts');
check( hc_plain_is('$HEX[6162]', 'ab'),              '$HEX unwraps to bytes');
check( hc_plain_is('$HEX[6162]', '6162'),            'and compares as text too');
check(!hc_plain_is('PASSWORD', 'password'),          'case is not normalized');
check(!hc_plain_is('$HEX[6162]', 'abc'),             'a wrong plaintext still fails');
check(!hc_plain_is(undef, 'password'),               'undef is not a match');

printf STDERR "- %d passed, %d failed\n", $pass, $fail;
exit($fail ? 1 : 0);
