#!/usr/bin/perl
#-----------------------------------------------------------------------
#
# Name: test-check-upstream.pl
# Description: assert that every failure mode of check-upstream.pl actually
#              fires, against synthetic fixtures
# Category: cracking-rosetta test
#
# Project: cracking-rosetta | Phase: upstream drift
#
#-----------------------------------------------------------------------
# METHODOLOGY AND WHY THIS EXISTS
#
# check-upstream.pl passes today and will pass every day until an upstream
# catalog changes, which may be never. A gate in that state is
# indistinguishable from a gate that CANNOT fail, and the register exists
# precisely because "nothing happened" and "the thing we were watching for
# happened and nobody noticed" looked identical.
#
# So each mode is provoked here on purpose. The convergence case is the one
# worth the whole file: it is the state change nothing could previously
# detect, and it is also the case with an ordering rule attached -- when
# upstream fixes a value, "upstream moved" and "the two agree now" are both
# true, and only the second is reported, because "delete this record" is the
# entire action and the other line would send a reader hunting a second
# problem that is not there. That rule is asserted below, not just described
# in a comment.
#
# The fixtures are synthetic and live under the project's own tmp/. Nothing
# here reads or writes vendor/, data/algorithms/ or data/tools/: a test that
# mutated the real files to prove a gate fires would be the same class of
# defect as editing vendor/ to fix a row.
#
# USAGE
#   perl -Itools/lib tools/test-check-upstream.pl
#   Exit 0 all assertions passed, 1 one or more failed, 2 usage.
#
# DEPENDENCIES
#   perl, YAML::XS, tools/check-upstream.pl
#
#-----------------------------------------------------------------------
# Generated by Claude Opus 5 on 2026-09-02

use strict;
use warnings;

use File::Path qw(make_path remove_tree);
use FindBin qw($RealBin);

my $PROG = 'test-check-upstream.pl';
my $ROOT = "$RealBin/..";

# Assertions go to stdout and the summary to stderr; unbuffer stdout so a
# failing transcript reads in the order it happened.
$| = 1;

if (@ARGV && $ARGV[0] =~ /^(-h|--help)$/) {
    print <<"USAGE";
Usage: $PROG

   Provokes every failure mode of check-upstream.pl against synthetic
   fixtures under tmp/. Takes no arguments.
   Exit 0 all passed, 1 one or more failed, 2 usage.
USAGE
    exit 0;
}
if (@ARGV) { print STDERR "$PROG: takes no arguments\n"; exit 2 }

# Absolute, per the house rule: the working directory can change under a
# session and a relative tmp/ path lands somewhere nobody expects.
my $DIR = "$ROOT/tmp/check-upstream-test";
my $REL = "tmp/check-upstream-test";        # the same place, as the register
                                            # writes it: relative to the root

remove_tree($DIR) if -d $DIR;
make_path("$DIR/algorithms") or die "$PROG: cannot create $DIR: $!\n";

#-----------------------------------------------------------------------
# Fixture builders. Each takes overrides and writes one file.

sub spit {
    my ($path, $content) = @_;
    open my $fh, '>', $path or die "$PROG: cannot write $path: $!\n";
    print $fh $content;
    close $fh or die "$PROG: cannot close $path: $!\n";
    return;
}

# The value under dispute, in the catalog's own hash[:salt]:password form.
my $UP_VALUE  = '786aab53:1122 3344:password123';
my $OUR_HASH  = '0992047f:1122 3344';
my $OUR_PASS  = 'password123';
my $OUR_VALUE = "$OUR_HASH:$OUR_PASS";

# A three-row catalog. %over replaces any field of any row, and a row whose
# name is set to undef is omitted entirely.
sub write_catalog {
    my (%over) = @_;
    my @rows = (
        { index => 'e1',   name => 'MD5',        modes => '0',   example => 'aa:password123' },
        { index => 'e607', name => 'DISPUTED',   modes => 'n/a', example => $UP_VALUE },
        { index => 'e999', name => 'TAIL',       modes => '100', example => 'cc:password123' },
    );
    my $out = "# hashpipe - Supported Hash Types\n\n"
            . "| Index | Name | Hashcat Mode | Example (hash:password) |\n"
            . "|-------|------|-------------|------------------------|\n";
    for my $r (@rows) {
        my $o = $over{ $r->{index} } || {};
        next if exists $o->{drop};
        my %f = (%$r, %$o);
        $out .= sprintf "| %s | %s | %s | `%s` |\n",
                        @f{qw(index name modes example)};
    }
    $out .= sprintf "| %s | %s | %s | `%s` |\n", @{$over{extra}}{qw(index name modes example)}
        if $over{extra};
    spit("$DIR/catalog.md", $out);
    return;
}

# The generated inventory, in data/tools/mdxfind.yaml's shape. Two types the
# catalog does not have (e426, e1002) so the index-set record has something to
# be about.
sub write_inventory {
    my (%over) = @_;
    my @rows = (
        { index => 'e1',    name => 'MD5',      modes => ['0'],   example => 'aa:password123' },
        { index => 'e426',  name => 'PARALLEL', modes => [],      example => undef },
        { index => 'e607',  name => 'DISPUTED', modes => [],      example => $UP_VALUE },
        { index => 'e999',  name => 'TAIL',     modes => ['100'], example => 'cc:password123' },
        { index => 'e1002', name => 'RMD256',   modes => [],      example => undef },
    );
    my $out = "# GENERATED by a test fixture -- not a real inventory\n"
            . "tool: \"mdxfind\"\nversion: \"fixture\"\ncount: 5\ntypes:\n";
    for my $r (@rows) {
        my $o = $over{ $r->{index} } || {};
        next if exists $o->{drop};
        my %f = (%$r, %$o);
        $out .= sprintf "  - index: \"%s\"\n    name: \"%s\"\n", @f{qw(index name)};
        $out .= sprintf "    hashcat_modes: [%s]\n",
                        join(', ', map { "\"$_\"" } @{ $f{modes} })
            if @{ $f{modes} };
        $out .= sprintf "    example_vector: \"%s\"\n", $f{example}
            if defined $f{example};
    }
    spit("$DIR/inventory.yaml", $out);
    return;
}

# The curated entry carrying the value we assert.
sub write_entry {
    my ($hash, $pass) = @_;
    spit("$DIR/algorithms/disputed.yaml", <<"YAML");
id: "disputed"
name: "DISPUTED"
status: "ok"
vectors:
  - hash: "$hash"
    pass: "$pass"
    source: "test"
YAML
    return;
}

#-----------------------------------------------------------------------
# john-map-agreement fixtures.
#
# The gate this proves is the one the other two could not: hashpipe and
# mdxfind number ITERATIONS differently on chained types, and the suffix is
# part of the identity. It is also the gate most at risk of reading the wrong
# table -- v1.189 shipped a JohnMapLocal[] whose numbering is local to the
# machine that generated it -- so one case asserts that reading it would have
# fired, and that it does not.

# A fixture john_map.h. %over patches a JohnMap[] row: pass a type string, or
# drop => 1. JohnMapLocal[] always carries a row that CONTRADICTS the entries,
# so a gate that read it would fail the baseline.
sub write_john_map {
    my (%over) = @_;
    my %row = (dynamic_900 => 'FIXTYPEx01', dynamic_901 => 'OTHERTYPEx02');
    for my $k (keys %over) {
        if (ref $over{$k} eq 'HASH' && $over{$k}{drop}) { delete $row{$k} }
        else { $row{$k} = $over{$k} }
    }
    my $body = join('', map { qq{    { "$_", "$row{$_}" },\n} } sort keys %row);
    spit("$DIR/john_map.h", <<"C");
/* fixture, not upstream's file */
struct john_map_ent { const char *john; const char *hptype; };

static const struct john_map_ent JohnMap[] = {
$body};

/* Numbering is LOCAL to the generating machine; input only. */
static const struct john_map_ent JohnMapLocal[] = {
    { "dynamic_900", "WRONGIFREAD" },
};
C
    return;
}

# An entry naming a john dynamic plus the mdxfind type and iteration count
# this repository asserts for it.
sub write_john_entry {
    my ($stem, $dyn, $type, $iter) = @_;
    my $it = defined $iter ? "    iterations: $iter\n" : '';
    spit("$DIR/algorithms/$stem.yaml", <<"YAML");
id: "$stem"
name: "$stem"
status: "ok"
tools:
  john:
    cpu: ["$dyn"]
    verified: "vector"
  mdxfind:
    types: ["$type"]
$it    verified: "vector"
YAML
    return;
}

# The baseline pair: dynamic_900 agrees (FIXTYPE at 1 iteration, which is what
# an unsuffixed x01 means), dynamic_901 is the recorded disagreement.
sub write_john_entries {
    my (%over) = @_;
    write_john_entry('jm-agree', 'dynamic_900',
                     $over{agree_type} // 'FIXTYPE', $over{agree_iter});
    write_john_entry('jm-differ', 'dynamic_901',
                     $over{differ_type} // 'OTHERTYPE',
                     exists $over{differ_iter} ? $over{differ_iter} : 3);
    return;
}

# The register. %over patches the row-value record; anything in %set_index
# patches the index-set record.
sub write_register {
    my (%over) = @_;
    my $absent = $over{absent_upstream} // '["e426", "e1002"]';
    # The recorded john-map disagreement: dynamic_901, where upstream says
    # two iterations and the entry says three.
    my $differs = $over{differs} // qq{      - john: "dynamic_901"\n}
                . qq{        publishes: "OTHERTYPEx02"\n}
                . qq{        we_assert: "OTHERTYPE x03"\n}
                . qq{        why: "iteration-numbering"\n};
    my $kind   = $over{kind}            // 'catalog-row-value';
    # mode_differs: is optional on a catalog-index-set record, so the default
    # is EMPTY -- the baseline must keep proving that an unrecorded hashcat
    # mapping disagreement still fails.
    my $modes  = $over{mode_differs}     // '';
    my $core   = $over{no_because} ? '' : "    because: \"a fixture\"\n";
    spit("$DIR/register.yaml", <<"YAML");
version: 1
disagreements:
  - id: "row-value"
    kind: "$kind"
    upstream: "$REL/catalog.md"
    inventory: "$REL/inventory.yaml"
    key: "DISPUTED"
    entry: "disputed"
    publishes: "$UP_VALUE"
    we_assert: "$OUR_VALUE"
    recorded: "2026-09-02"
$core  - id: "index-set"
    kind: "catalog-index-set"
    upstream: "$REL/catalog.md"
    inventory: "$REL/inventory.yaml"
    absent_upstream: $absent
$modes    recorded: "2026-09-02"
    because: "a fixture"
  - id: "johnmap"
    kind: "john-map-agreement"
    upstream: "$REL/john_map.h"
    inventory: "$REL/algorithms"
    differs:
$differs    recorded: "2026-09-02"
    because: "a fixture"
YAML
    return;
}

#-----------------------------------------------------------------------
# Run the gate over the current fixtures and return its exit status and the
# set of "id [mode]" pairs it reported.

sub run_gate {
    my $cmd = sprintf('perl -I%s/lib %s/check-upstream.pl --check '
                    . '--register %s/register.yaml --algorithms %s/algorithms 2>&1',
                      $RealBin, $RealBin, $DIR, $DIR);
    my $out    = `$cmd`;
    my $status = $? >> 8;
    my %modes;
    # The report line is:  - <id> [<mode>]: message
    while ($out =~ /^- (\S+) \[([a-z-]+)\]:/mg) { $modes{"$1 $2"} = 1 }
    return ($status, \%modes, $out);
}

#-----------------------------------------------------------------------
# The assertion table. Each case sets the fixtures up, then names the exact
# set of findings expected -- exact, not "contains", because a mode firing
# that should not have is as much a defect as one that did not fire.

my @CASES = (
    {
        why   => 'baseline: all three disagreements exactly as recorded',
        setup => sub { write_catalog(); write_inventory(); write_entry($OUR_HASH, $OUR_PASS);
                       write_john_map(); write_john_entries(); write_register() },
        want  => [],
    },
    {
        why   => 'upstream moved: the catalog cell is a third value',
        setup => sub { write_catalog(e607 => { example => 'ffff:1122 3344:password123' }) },
        # Two findings for one event, and both are wanted: the catalog moved,
        # and the inventory generated from it has not been regenerated yet.
        # They name different actions -- re-measure the entry, re-run the
        # extractor -- so collapsing them would hide one of the two.
        want  => ['row-value upstream-moved', 'row-value inventory-moved'],
    },
    {
        why   => 'upstream moved: the catalog no longer has the row at all',
        setup => sub { write_catalog(e607 => { drop => 1 }) },
        # e607 leaving the catalog also widens the set the index-set record
        # is about, which is a true second finding rather than noise.
        want  => ['row-value upstream-moved', 'index-set set-moved'],
    },
    {
        why   => 'our side moved: the entry no longer carries the proven vector',
        setup => sub { write_catalog(); write_entry('deadbeef:1122 3344', $OUR_PASS) },
        want  => ['row-value ours-moved'],
    },
    {
        why   => 'our side moved: a re-seed put upstream\'s value back on the entry',
        setup => sub { write_entry('786aab53:1122 3344', 'password123') },
        # This is convergence in the only sense the data can express, and it
        # is reported as such -- which is right: the two layers now agree, and
        # a reader who did not intend that has one line telling them so.
        want  => ['row-value converged'],
    },
    {
        why   => 'converged: upstream published our value, and says so ALONE',
        setup => sub {
            write_entry($OUR_HASH, $OUR_PASS);
            write_catalog(e607 => { example => $OUR_VALUE });
        },
        want  => ['row-value converged'],
    },
    {
        why   => 'the generated inventory stopped matching the catalog it comes from',
        setup => sub { write_catalog(); write_inventory(e607 => { example => 'stale:1122 3344:password123' }) },
        want  => ['row-value inventory-moved'],
    },
    {
        why   => 'index set moved: the catalog picked one of the two up',
        setup => sub {
            write_inventory();
            write_catalog(extra => { index => 'e1002', name => 'RMD256', modes => 'n/a', example => 'dd:password123' });
        },
        want  => ['index-set set-moved'],
    },
    {
        why   => 'index set converged: the catalog covers every type',
        setup => sub {
            write_catalog(
                extra => { index => 'e1002', name => 'RMD256', modes => 'n/a', example => 'dd:password123' },
            );
            write_inventory(e426 => { drop => 1 });
        },
        want  => ['index-set converged'],
    },
    {
        why   => 'upstream is ahead: a catalog index the local binary lacks',
        setup => sub { write_catalog(); write_inventory(e999 => { drop => 1 }) },
        # absent_upstream is unchanged -- e426 and e1002 are still the types
        # only the binary has -- so set-moved correctly stays quiet. The
        # catalog being AHEAD is a different direction and its own finding.
        want  => ['index-set upstream-ahead'],
    },
    {
        why   => 'the alias assertion: a name diverged on a shared index',
        setup => sub { write_inventory(e999 => { name => 'RENAMED' }) },
        want  => ['index-set alias-broken'],
    },
    {
        why   => 'the alias assertion: a hashcat mapping diverged',
        setup => sub { write_inventory(e999 => { modes => ['100', '110'] }) },
        want  => ['index-set alias-broken'],
    },
    # mode_differs: exists because since hashpipe v1.193 the catalog's mode
    # column is an INVERTED mode-to-one-index map while mdxfind's -h prints
    # every mode a type can serve, so the two spell a synonym pair differently
    # with neither being wrong. It must not become a way to silence the alias
    # check, so all three states are asserted.
    {
        why   => 'a RECORDED hashcat mapping disagreement passes',
        setup => sub { write_inventory(e999 => { modes => ['100', '110'] });
                       write_register(mode_differs =>
                           qq{    mode_differs:\n}
                         . qq{      - index: "e999"\n}
                         . qq{        publishes: "100"\n}
                         . qq{        we_assert: "100,110"\n}
                         . qq{        why: "synonym"\n}) },
        want  => [],
    },
    {
        why   => 'a recorded mapping disagreement whose upstream half moved',
        setup => sub { write_catalog(e999 => { modes => '100,120' }) },
        want  => ['index-set upstream-moved'],
    },
    {
        why   => 'a recorded mapping disagreement whose OUR half moved',
        setup => sub { write_catalog(); write_inventory(e999 => { modes => ['100', '130'] }) },
        want  => ['index-set ours-moved'],
    },
    {
        why   => 'a recorded mapping disagreement that converged is reported',
        setup => sub { write_inventory() },
        want  => ['index-set row-converged'],
    },
    {
        why   => 'back to an empty mode_differs: the unrecorded case fails again',
        setup => sub { write_register(); write_inventory(e999 => { modes => ['100', '110'] }) },
        want  => ['index-set alias-broken'],
    },
    {
        why   => 'a register record missing a core field fails, it is not skipped',
        setup => sub { write_inventory(); write_register(no_because => 1) },
        want  => ['row-value malformed'],
    },
    {
        why   => 'an unimplemented kind fails rather than passing silently',
        setup => sub { write_register(kind => 'catalog-vibes') },
        want  => ['row-value malformed'],
    },
    # --- the third kind ------------------------------------------------
    {
        why   => 'john-map: the local table is NOT read',
        # JohnMapLocal[] maps dynamic_900 to WRONGIFREAD, which contradicts
        # the entry. A gate that read the second table fails here, and that
        # is the entire point of the case: upstream says the numbering in it
        # belongs to another machine.
        setup => sub { write_john_map(); write_john_entries(); write_register() },
        want  => [],
    },
    {
        why   => 'john-map: upstream changed a recorded row',
        setup => sub { write_john_map(dynamic_901 => 'OTHERTYPEx05') },
        want  => ['johnmap upstream-moved'],
    },
    {
        why   => 'john-map: our side moved off the recorded value',
        setup => sub { write_john_map(); write_john_entries(differ_iter => 4) },
        want  => ['johnmap ours-moved'],
    },
    {
        why   => 'john-map: a disagreement appeared that is not recorded',
        setup => sub { write_john_entries(agree_type => 'SOMETHINGELSE') },
        want  => ['johnmap set-moved'],
    },
    {
        why   => 'john-map: the ITERATION SUFFIX alone is a disagreement',
        # The type name matches and only the suffix differs. This is the
        # case catalog-index-set structurally cannot see, and the reason
        # this kind was added.
        setup => sub { write_john_entries(agree_iter => 7) },
        want  => ['johnmap set-moved'],
    },
    {
        why   => 'john-map: one recorded row converged, another still differs',
        setup => sub { write_john_entries(agree_type => 'SOMETHINGELSE',
                                          differ_iter => 2) },
        want  => ['johnmap set-moved', 'johnmap row-converged'],
    },
    {
        why   => 'john-map: everything converged, so the record is spent',
        setup => sub { write_john_entries(differ_iter => 2) },
        want  => ['johnmap converged'],
    },
    {
        why   => 'back to baseline: the fixtures were not left broken',
        setup => sub { write_catalog(); write_inventory(); write_entry($OUR_HASH, $OUR_PASS);
                       write_john_map(); write_john_entries(); write_register() },
        want  => [],
    },
);

my ($pass, $fail) = (0, 0);
for my $c (@CASES) {
    $c->{setup}->();
    my ($status, $got, $out) = run_gate();
    my %want = map { $_ => 1 } @{ $c->{want} };
    my $want_status = @{ $c->{want} } ? 1 : 0;

    my @missing = grep { !$got->{$_}  } sort keys %want;
    my @extra   = grep { !$want{$_}   } sort keys %$got;

    if (!@missing && !@extra && $status == $want_status) {
        $pass++;
        printf "ok   %s\n", $c->{why};
    }
    else {
        $fail++;
        printf "FAIL %s\n", $c->{why};
        printf "     missing: %s\n", join(', ', @missing) if @missing;
        printf "     unexpected: %s\n", join(', ', @extra) if @extra;
        printf "     exit %d, wanted %d\n", $status, $want_status
            if $status != $want_status;
        $out =~ s/^/       | /mg;
        print $out;
    }
}

# Leave nothing behind: tmp/ is scratch, and a stale fixture tree is one more
# thing for a later session to wonder about.
remove_tree($DIR);

printf STDERR "- %d passed, %d failed\n", $pass, $fail;
exit($fail ? 1 : 0);
