#!/usr/bin/perl
#-----------------------------------------------------------------------
#
# Name: test-verify-native.pl
# Description: assert verify-vectors.pl's NATIVE john path -- that it fires
#              when the grouped scheme cannot parse a ciphertext, that it
#              does NOT fire otherwise, and that it relaxes nothing
#
#-----------------------------------------------------------------------
# METHODOLOGY AND WHY THIS EXISTS
#
# verify-vectors.pl writes every john line as "<synthetic login>TAB<hash>".
# That is right for a hash which is only a digest and wrong for one that
# EMBEDS its own login: a NETNTLMv2 ciphertext is
# USER::DOMAIN:challenge:response:blob, and displacing that first field is
# exactly what stops john parsing it. john then loads nothing, which is
# indistinguishable from a format that ran and found nothing. netntlmv2 sat
# below tier 'vector' on that for a week while every identifier it named
# round-tripped by hand.
#
# So the tool now retries NATIVELY -- one vector per invocation, no login,
# no --field-separator-char -- gated on john's own --show summary saying it
# LOADED nothing.
#
# THE FAILURE MODE OF THAT CODE IS SILENCE, WHICH IS WHY THIS FILE EXISTS.
# If the gate stopped firing, netntlmv2 would quietly stop verifying; and
# because failure never demotes, the tier already written would stand and
# nobody would be told. Nothing else in the repository would notice.
#
# FOUR ASSERTIONS, AND THE LAST TWO ARE THE POINT.
#
#   1. POSITIVE. A challenge-response entry the grouped scheme cannot parse
#      reaches tier 'vector'.
#   2. UNCHANGED. An ordinary digest entry still reaches 'vector', and does
#      it WITHOUT the native path.
#   3. THE GATE IS NOT ALWAYS-ON. A format that LOADS its hash and fails to
#      crack it must not trigger the retry. Without this, "the gate fires
#      correctly" and "the gate fires unconditionally" are the same reading,
#      since both leave the entry unpromoted.
#   4. NOTHING IS RELAXED. nethalflm TRUNCATES to seven characters, so it
#      cracks john's own vector and returns a plaintext that is not the
#      stored one. It must still fail. If this ever passes, the comparison
#      has been loosened, which would silently promote truncating formats
#      across the corpus.
#
# Assertions 2 and 3 look at whether the tool WROTE its native scratch files
# for that label, because the outcome alone cannot tell the two apart -- in
# 3 the entry is unpromoted either way. That reaches into an implementation
# detail on purpose: it is the only observable that distinguishes them.
#
# It needs a john binary, so it is NOT in CI -- validate.yml deliberately
# runs no cracker -- and it skips LOUDLY when there is none, because an
# absent binary must not read as a pass.
#
# USAGE
#   perl tools/test-verify-native.pl            run the assertions
#   perl tools/test-verify-native.pl --verbose  print each case's outcome
#   JOHN=/path/to/john  overrides where the binary is looked for.
#   Exit 0 all assertions passed (or skipped), 1 one or more failed.
#
# DEPENDENCIES
#   perl, YAML::XS, tools/lib/RosettaTools.pm, tools/verify-vectors.pl,
#   a john binary with netntlmv2, nethalflm and dynamic_26
#
#-----------------------------------------------------------------------
# Generated by Claude Opus 5 on 2026-09-06

use strict;
use warnings;
use FindBin qw($RealBin);
use lib "$RealBin/lib";
use RosettaTools qw(tool_path);
use Digest::SHA qw(sha1_hex);
use File::Temp qw(tempdir);
use File::Path qw(make_path);
use Cwd qw(getcwd);
use YAML::XS;

my $PROG = 'test-verify-native.pl';
if (grep { /^(?:-h|--help)$/ } @ARGV) {
    print <<"USAGE";

Usage: $PROG [--verbose]

   -v, --verbose     print each case's outcome
   -h, --help        this help

   Asserts verify-vectors.pl's native john path: that it fires when the
   grouped "<login>TAB<hash>" scheme cannot parse a ciphertext, that it does
   NOT fire when john loaded its hashes and merely failed to crack them, and
   that it relaxes no comparison -- a TRUNCATING format must still fail.

   Needs a john binary (\$JOHN, else the resolver default). Skips loudly when
   there is none, because a skip must not read as a pass. Not run in CI:
   validate.yml deliberately runs no cracker.

   Exit 0 all assertions passed or skipped, 1 one or more failed.
USAGE
    exit 0;
}

my $verbose = grep { /^-v$|^--verbose$/ } @ARGV;
my $JOHN    = tool_path('john');

unless (-x $JOHN) {
    print STDERR "- SKIPPED: no john at $JOHN (set JOHN= to point at one)\n";
    print STDERR "-   This is a skip, NOT a pass: the native path was not checked.\n";
    exit 0;
}

my $VV = "$RealBin/verify-vectors.pl";
-x $VV or die "$PROG: cannot find verify-vectors.pl at $VV\n";

my $TMP = tempdir(CLEANUP => 1);

# Computed here rather than transcribed, so a typo cannot masquerade as a
# behaviour change.
my $SHA1  = sha1_hex('password');           # dynamic_26 cracks this
my $SHA1X = sha1_hex(sha1_hex('password')); # dynamic_26 LOADS and cannot crack it

# id => [ john format, hash, plaintext, expected tier, native expected? ]
#
# 'native expected' is undef where it is not asserted, 1 where the tool must
# have written its native scratch files for that label, and 0 where it must
# not have.
my @CASE = (
    [ 'tn-challenge-response', 'netntlmv2',
      'user::domain:1122334455667788:d5add1cebafed2180b3cca8728f5aff8'
      . ':01010000000000000000000000000000aabbccdd1122334400000000',
      'password123', 'vector', 1,
      'a ciphertext that embeds its own login: grouped cannot parse it, native can' ],

    [ 'tn-ordinary-digest', 'dynamic_26', $SHA1, 'password', 'vector', 0,
      'an ordinary digest still verifies, and without the native path' ],

    [ 'tn-loads-but-wrong', 'dynamic_26', $SHA1X, 'password', 'asserted', 0,
      'john LOADS this and cannot crack it, so the gate must stay shut' ],

    [ 'tn-truncating', 'nethalflm',
      '$NETHALFLM$1122334455667788$6E1EC36D3417CE9E09A4424309F116C4C991948DAEB4ADAD',
      'G3RG3P00!', 'asserted', undef,
      'nethalflm truncates to 7 characters: the strict comparison must refuse it' ],
);

my ($pass, $fail) = (0, 0);
sub ok {
    my ($cond, $what, $detail) = @_;
    if ($cond) { $pass++; print STDERR "- ok    $what\n" if $verbose }
    else       { $fail++; print STDERR "- FAIL  $what\n";
                 print STDERR "-       $detail\n" if defined $detail }
}

for my $c (@CASE) {
    my ($id, $label, $hash, $plain, $want_tier, $want_native, $why) = @$c;

    my $adir = "$TMP/$id/algorithms";
    my $wdir = "$TMP/$id/work";
    make_path($adir, $wdir);

    # A minimal entry. tier starts at 'asserted' so a promotion is visible as a
    # CHANGE rather than as a value that was already there.
    YAML::XS::DumpFile("$adir/$id.yaml", {
        id     => $id,
        name   => $id,
        status => 'needs-review',
        tools  => { john => { cpu => [$label], verified => 'asserted' } },
        vectors => [ { hash => $hash, pass => $plain, source => 'john' } ],
    });

    my $rc = system($^X, $VV, '--tool', 'john', '--john', $JOHN,
                    '--algorithms', $adir, '--work', $wdir,
                    '--timeout', '120', '--only', $id) >> 8;
    ok($rc == 0, "$id: verify-vectors.pl exited 0", "exit was $rc");

    my $got = eval { YAML::XS::LoadFile("$adir/$id.yaml") };
    my $tier = $got ? ($got->{tools}{john}{verified} // '(none)') : '(unreadable)';
    ok($tier eq $want_tier, "$id: tier is '$want_tier' -- $why",
       "got '$tier'");

    next unless defined $want_native;

    # The only observable that separates "the gate fired" from "the gate did
    # not": the tool names its native scratch files jn.<label>.native.<n>.*
    (my $safe = $label) =~ s/[^A-Za-z0-9]/_/g;
    opendir(my $dh, $wdir) or die "$wdir: $!";
    my @nat = grep { /^jn\.\Q$safe\E\.native\./ } readdir $dh;
    closedir $dh;
    my $fired = @nat ? 1 : 0;
    ok($fired == $want_native,
       "$id: native path " . ($want_native ? 'FIRED' : 'did NOT fire'),
       "found " . scalar(@nat) . " native scratch file(s) for $label");
}

# A RELATIVE --work MUST WORK, and until 2026-09-16 it silently did not.
#
# The john branch runs `cd <john's run dir> && ./john ...`, because john finds
# john.conf relative to its own tree. Every path handed to it is therefore
# resolved from THERE, so a relative --work made the hash file, the wordlist,
# the pot and the session all unresolvable and john cracked nothing. mdxfind
# and hashcat never cd, which is why the defect was john-only.
#
# It is asserted here rather than left to care at the call site because the
# failure is silent and expensive: "0 cracked" is exactly what a wrong mapping
# looks like, and the reads_in clear then DELETED a proven read on the
# strength of it -- commit 463ba1c stripped john from dynamic-31 that way.
#
# The control is the same entry under an ABSOLUTE --work in the loop above
# (tn-ordinary-digest). Without it, "the relative path works" and "this format
# verifies no matter what" are the same reading.
{
    my $id   = 'tn-relative-work';
    my $adir = "$TMP/$id/algorithms";
    make_path($adir);
    YAML::XS::DumpFile("$adir/$id.yaml", {
        id     => $id,
        name   => $id,
        status => 'needs-review',
        tools  => { john => { cpu => ['dynamic_26'], verified => 'asserted' } },
        vectors => [ { hash => $SHA1, pass => 'password', source => 'john' } ],
    });
    # Relative to the CURRENT directory, which is not john's -- that is the
    # whole point. It is created under the temp tree so nothing is left behind.
    my $cwd = getcwd();
    chdir $TMP or die "chdir $TMP: $!";
    my $rc = system($^X, $VV, '--tool', 'john', '--john', $JOHN,
                    '--algorithms', $adir, '--work', "$id/relwork",
                    '--timeout', '120', '--only', $id) >> 8;
    chdir $cwd or die "chdir back: $!";
    ok($rc == 0, "$id: verify-vectors.pl exited 0", "exit was $rc");
    my $got  = eval { YAML::XS::LoadFile("$adir/$id.yaml") };
    my $tier = $got ? ($got->{tools}{john}{verified} // '(none)') : '(unreadable)';
    ok($tier eq 'vector',
       "$id: a RELATIVE --work still verifies -- john is run from its own "
     . "directory, so every path must be resolved before the chdir",
       "got '$tier'");
}

printf STDERR "- %s: %d assertion(s) passed, %d failed\n", $PROG, $pass, $fail;
if ($fail) {
    print STDERR <<'WHY';
-
- If the POSITIVE case failed, the native retry stopped firing: check the
-   gate, which reads john's own "N password hashes cracked, M left" summary
-   out of the grouped --show output. john changing that wording breaks it
-   silently.
- If the "loads but wrong" case fired the native path, the gate has become
-   unconditional and every failed crack now costs one invocation per vector.
- If the TRUNCATING case reached tier vector, a comparison has been relaxed;
-   that would promote truncating formats corpus-wide and must be reverted,
-   not accommodated.
WHY
}
exit($fail ? 1 : 0);
