#!/usr/bin/perl
#
# test-runbg.pl -- prove that tools/runbg.sh actually terminates, on every
# path, including the three that failed in the wild.
#
# WHY THIS EXISTS
#
# runbg.sh is a wrapper whose entire claim is "this wait will end". A claim
# like that is worthless asserted and cheap to check, and the failures it
# replaces were all SILENT -- a wait that never fires looks exactly like work
# still in progress. So each way the wrapper can finish gets an assertion, and
# each assertion is bounded by this script's own alarm so a regression here
# fails loudly instead of hanging CI.
#
# The three real failures being guarded against, all 2026-09-04/05:
#   * a wait whose pgrep pattern matched the waiting loop itself
#   * a wait whose failure pattern matched OpenSSL's success banner
#   * a wait on a file a later command rewrote
# The wrapper answers all three by never inspecting program output at all, so
# the tests below check the OBSERVABLE consequence: a wait returns, quickly,
# with the right code, whatever the job printed.
#
# Needs nothing but a shell. No cracker, so it runs in CI.
#
# Generated by Claude Opus 5 on 2026-09-05

use strict;
use warnings;
use FindBin qw($RealBin);
use File::Temp qw(tempdir);
use Time::HiRes qw(time);

my $RUNBG = "$RealBin/runbg.sh";
my $work  = tempdir(CLEANUP => 1);
$ENV{RUNBG_DIR} = "$work/runs";

my ($pass, $fail) = (0, 0);
# NOTE the prototype-free but SCALAR-forced first argument. A failed `m//` in
# LIST context returns the empty list, so `ok(!!($e =~ /x/), 'msg')` collapses to
# `ok('msg')` -- the message becomes the condition and the test passes on a
# failure. Callers below therefore pass a forced scalar, and this guards it.
sub ok {
    my ($cond, $what) = @_;
    die "ok() called without a description -- a list-context m// collapsed\n"
        unless defined $what;
    if ($cond) { $pass++; print "ok   $what\n" }
    else       { $fail++; print "FAIL $what\n" }
}

# run(@argv) - (exit code, stdout, stderr), with a hard alarm so a wrapper that
# hangs fails this script rather than wedging the run.
sub run {
    my (@argv) = @_;
    my $out = "$work/o.$$"; my $err = "$work/e.$$";
    my $code;
    eval {
        local $SIG{ALRM} = sub { die "alarm\n" };
        alarm 120;
        my $pid = fork();
        die "fork: $!\n" unless defined $pid;
        if (!$pid) {
            # No shell anywhere on this path, so an argument containing quotes
            # -- which the OpenSSL decoy does -- cannot be mangled on the way in.
            open STDOUT, '>', $out or exit 127;
            open STDERR, '>', $err or exit 127;
            exec { $argv[0] } @argv;
            exit 127;
        }
        waitpid $pid, 0;
        $code = $?;
        alarm 0;
        1;
    } or do { alarm 0; return (-1, '', "TIMED OUT") };
    my $slurp = sub { open my $f, '<', $_[0] or return ''; local $/; <$f> };
    return ($code >> 8, scalar $slurp->($out), scalar $slurp->($err));
}

#-----------------------------------------------------------------------
# Usage and shape.

{
    my ($c) = run($RUNBG);
    ok($c == 2, 'no arguments: usage and exit 2');
    my ($c2) = run($RUNBG, 'nonsense-subcommand');
    ok($c2 == 2, 'an unknown subcommand: exit 2 rather than guessing');
    my ($c3, $o) = run($RUNBG, '--help');
    ok($c3 == 0 && $o =~ /Usage:/, '--help: exit 0 and a usage block');
}

#-----------------------------------------------------------------------
# The happy path, and the exit code has to come back from the JOB.

my $dir;
{
    my ($c, $o) = run($RUNBG, 'start', '-l', 'ok-job', '--', 'true');
    chomp($dir = $o);
    ok($c == 0 && length $dir, 'start: prints a run directory');
    ok(-d $dir, 'start: the run directory exists');

    my $t0 = time;
    my ($w) = run($RUNBG, 'wait', '-t', '30', '-i', '1', $dir);
    my $took = time - $t0;
    ok($w == 0, 'wait: a successful job returns 0');
    ok($took < 20, sprintf('wait: returned promptly (%.1fs), it did not spin', $took));
}

{
    my (undef, $o) = run($RUNBG, 'start', '-l', 'fail-job', '--', 'sh', '-c', 'exit 7');
    chomp(my $d = $o);
    my ($w) = run($RUNBG, 'wait', '-t', '30', '-i', '1', $d);
    ok($w == 7, "wait: the JOB'S exit code comes back, not the wrapper's");
    my (undef, $s) = run($RUNBG, 'status', $d);
    ok(!!($s =~ /done exit=7/), 'status: reports done and the code');
}

#-----------------------------------------------------------------------
# THE FAILURE THAT STARTED THIS. A job whose output contains every string an
# ad-hoc waiter would have keyed on -- the OpenSSL success banner, the word
# ERROR, an "exit=" line -- and whose command line contains the very pattern a
# pgrep-based waiter would match. The wrapper must be indifferent to all of it.

{
    my $noisy = join '; ',
        q{echo '**********************************************'},
        q{echo '***   OpenSSL has been successfully configured'},
        q{echo 'ERROR: this line is a decoy'},
        q{echo 'exit=0 decoy'},
        q{sleep 2},
        q{exit 3};
    my (undef, $o) = run($RUNBG, 'start', '-l', 'make-all-decoy', '--', 'sh', '-c', $noisy);
    chomp(my $d = $o);
    my $t0 = time;
    my ($w) = run($RUNBG, 'wait', '-t', '30', '-i', '1', $d);
    my $took = time - $t0;
    ok($w == 3, 'a job whose output carries every decoy string still reports its real code');
    ok($took >= 1 && $took < 20,
       sprintf('it waited for the JOB, not for a pattern (%.1fs)', $took));
    open my $fh, '<', "$d/stdout" or die;
    my $so = do { local $/; <$fh> };
    ok($so =~ /successfully configured/ && $so =~ /ERROR/,
       'the decoys really were in the output that was ignored');
}

#-----------------------------------------------------------------------
# Streams stay apart. hashpipe -c is the reason: a verified line goes to
# stdout, a refused line is echoed to stderr verbatim, and a merged stream
# cannot tell you which happened.

{
    my (undef, $o) = run($RUNBG, 'start', '-l', 'streams', '--',
                         'sh', '-c', 'echo TO_STDOUT; echo TO_STDERR >&2');
    chomp(my $d = $o);
    run($RUNBG, 'wait', '-t', '30', '-i', '1', $d);
    my $slurp = sub { open my $f, '<', $_[0] or return ''; local $/; <$f> };
    my ($so, $se) = ($slurp->("$d/stdout"), $slurp->("$d/stderr"));
    ok(!!($so =~ /TO_STDOUT/ && $so !~ /TO_STDERR/), 'stdout holds only stdout');
    ok(!!($se =~ /TO_STDERR/ && $se !~ /TO_STDOUT/), 'stderr holds only stderr');
}

#-----------------------------------------------------------------------
# Silence is not success. Two different deaths, and the wrapper distinguishes
# them -- which an ad-hoc `until` loop cannot, because it hangs on both.
#
# Measured 2026-09-05: killing the JOB does NOT produce "vanished". The runner
# outlives its child, reaps it, and records exit 137 (128 + SIGKILL), which is
# strictly better information than "it went away". `vanished` is reserved for
# the runner itself dying before it can write anything -- an OOM kill of the
# whole tree, or the host going down.

{
    my (undef, $o) = run($RUNBG, 'start', '-t', '0', '-l', 'victim', '--', 'sleep', '600');
    chomp(my $d = $o);
    my $n = 0; $n++, select(undef,undef,undef,0.2) while !-f "$d/pid" && $n < 25;
    open my $pf, '<', "$d/pid" or die "no pid file";
    chomp(my $pid = <$pf>);
    kill 'KILL', -$pid;
    kill 'KILL', $pid;
    my $t0 = time;
    my ($w) = run($RUNBG, 'wait', '-t', '30', '-i', '1', $d);
    my $took = time - $t0;
    ok($w == 137, 'a job killed with -9 comes back as exit 137, not as a hang');
    ok($took < 20, sprintf('and promptly (%.1fs)', $took));
}

# The vanished branch itself, from a fixture rather than by racing a kill: a
# run directory with a pid that is not running and no status file is exactly
# the state the runner leaves behind when it dies mid-flight. Asserting it this
# way is deterministic, where killing a whole process tree at the right instant
# is not.

{
    my (undef, $o) = run($RUNBG, 'start', '-l', 'fixture', '--', 'true');
    chomp(my $d = $o);
    run($RUNBG, 'wait', '-t', '30', '-i', '1', $d);
    unlink "$d/status" or die "fixture: $!";
    # A pid that cannot be running: allocate one, reap it, reuse the number.
    my $dead = fork(); if (!$dead) { exit 0 } waitpid $dead, 0;
    open my $pf, '>', "$d/pid" or die; print {$pf} "$dead\n"; close $pf;
    my $t0 = time;
    my ($w, undef, $e) = run($RUNBG, 'wait', '-t', '30', '-i', '1', $d);
    my $took = time - $t0;
    ok($w == 3, 'a run whose pid is gone with no status is reported vanished (exit 3)');
    ok(!!($e =~ /vanished/), 'and the message says so in words');
    ok($took < 20, sprintf('vanished is detected promptly (%.1fs)', $took));
}

#-----------------------------------------------------------------------
# The wait budget is real, and running out is distinguishable from finishing.

{
    my (undef, $o) = run($RUNBG, 'start', '-t', '0', '-l', 'slow', '--', 'sleep', '600');
    chomp(my $d = $o);
    my $t0 = time;
    my ($w, undef, $e) = run($RUNBG, 'wait', '-t', '3', '-i', '1', $d);
    my $took = time - $t0;
    ok($w == 4, 'the wait budget expiring is its own exit code (4), not a silent hang');
    ok(!!($e =~ /STILL RUNNING/), 'and it says the job is still running rather than implying failure');
    ok($took < 30, sprintf('the bounded loop really ended (%.1fs)', $took));
    run($RUNBG, 'kill', $d);
}

#-----------------------------------------------------------------------
# The job's OWN timeout, so a run nobody waits on cannot outlive its budget.

{
    my (undef, $o) = run($RUNBG, 'start', '-t', '2', '-l', 'budgeted', '--', 'sleep', '600');
    chomp(my $d = $o);
    my ($w) = run($RUNBG, 'wait', '-t', '40', '-i', '1', $d);
    ok($w != 0, 'a job that blew its own timeout does not report success');
    my (undef, $s) = run($RUNBG, 'status', $d);
    ok(!!($s =~ /^done/), 'and the watchdog left a status behind rather than a hang');
}

#-----------------------------------------------------------------------
# A fresh directory per run, so last run's output can never be read as current.
# That is the tmp/binary-diff.out trap.

{
    my (undef, $a) = run($RUNBG, 'start', '-l', 'same', '--', 'sh', '-c', 'echo FIRST');
    my (undef, $b) = run($RUNBG, 'start', '-l', 'same', '--', 'sh', '-c', 'echo SECOND');
    chomp($a); chomp($b);
    ok($a ne $b, 'two runs with the same label get different directories');
    run($RUNBG, 'wait', '-t', '30', '-i', '1', $_) for ($a, $b);
    my $slurp = sub { open my $f, '<', $_[0] or return ''; local $/; <$f> };
    ok($slurp->("$a/stdout") =~ /FIRST/ && $slurp->("$b/stdout") =~ /SECOND/,
       'and neither can be mistaken for the other');
}

printf "- %d passed, %d failed\n", $pass, $fail;
exit($fail ? 1 : 0);
