#!/usr/bin/perl
#-----------------------------------------------------------------------
#
# Name: test-rosetta-emit.pl
# Description: assert that RosettaEmit round-trips every value it writes, and
#              that a multi-line string is written as a readable block only
#              where the block form gives the string back unchanged
# Category: cracking-rosetta test
#
# Project: cracking-rosetta | Phase: 7 - pre-publication readiness
#
#-----------------------------------------------------------------------
# METHODOLOGY AND WHY THIS EXISTS
#
# RosettaEmit is the single writer for data/algorithms. Every seeding tool,
# relate.pl, merge.pl and fmt.pl all render through entry_text, so a defect
# here does not damage one file, it damages whatever the next bulk pass
# touches. fmt.pl compares its own before and after and so protects ITSELF,
# but emit_entry has no such check: seed-vectors.pl writes what it is given.
#
# The behavior under test is the block scalar. Two entries now carry a note
# that is a multi-paragraph document rather than a sentence, and the old
# emitter folded those into one 4000-character line -- valid YAML, unreadable
# in review, and the exact "one-line change buried in a reformat" that fmt.pl
# exists to prevent. Emitting "notes: |" instead fixes that, and introduces a
# failure mode the quoted form did not have: a block scalar can give back a
# DIFFERENT string. Leading indentation on the first line, trailing whitespace
# on any line, a CR, more than one trailing newline -- each changes what the
# loader returns, and none of them looks wrong in the file.
#
# So the assertions that matter are the REFUSALS: for every awkward shape the
# emitter must fall back to the quoted form rather than write a block that
# lies. The positive cases prove only that the readable form is actually
# reached for the ordinary note; the round-trip assertion runs on every case,
# block or not, because that is the property the repository depends on.
#
# USAGE
#   perl -Itools/lib tools/test-rosetta-emit.pl
#   Exit 0 all assertions passed, 1 one or more failed, 2 usage.
#
# DEPENDENCIES
#   perl, YAML::XS, tools/lib/RosettaEmit.pm
#
#-----------------------------------------------------------------------
# Generated by Claude Opus 5 on 2026-09-03

use strict;
use warnings;

use FindBin qw($RealBin);
use YAML::XS ();

use lib "$RealBin/lib";
use RosettaEmit qw(entry_text);

my $PROG = 'test-rosetta-emit.pl';

if (@ARGV && $ARGV[0] =~ /^(-h|--help)$/) {
    print <<"USAGE";
Usage: $PROG

   Runs the assertion table. Takes no arguments.
   Exit 0 all passed, 1 one or more failed, 2 usage.
USAGE
    exit 0;
}
if (@ARGV) { print STDERR "$PROG: takes no arguments\n"; exit 2 }

# An entry skeleton every case is built on. id and name are the only fields
# entry_text needs to emit anything at all.
sub entry_with {
    my (%extra) = @_;
    return { id => 'test-entry', name => 'test', %extra };
}

# [ name, entry, want_block (1 block / 0 quoted / undef don't care), why ]
#
# want_block is asserted against the emitted TEXT; the round trip is asserted
# on every case regardless.
my @CASES = (
    [ 'ordinary multi-paragraph note',
      entry_with(notes => "First paragraph, which runs\nover two lines.\n\nSecond paragraph.\n"),
      1, 'the readable form is reached for the note this change is for' ],

    [ 'multi-line with no trailing newline',
      entry_with(notes => "line one\nline two"),
      1, 'the strip indicator covers a value that does not end in a newline' ],

    [ 'multi-line inside a tool block',
      entry_with(tools => { mdxfind => { types => ['MD5'], verified => 'vector',
                                         note => "why this type\nand not the other\n" } }),
      1, 'nesting depth does not defeat the block, and the indent is right' ],

    [ 'multi-line inside a relation',
      entry_with(relations => [ { kind => 'same-computation', entry => 'other',
                                  distinction => 'naming',
                                  note => "one reason\nand a second\n" } ]),
      1, 'a key emitted under a sequence item still indents correctly' ],

    [ 'trailing space on an inner line',
      entry_with(notes => "a line with a trailing space \nand another\n"),
      0, 'trailing whitespace is invisible in review; refuse the block' ],

    [ 'first line indented',
      entry_with(notes => "  indented first line\nsecond\n"),
      0, 'a block whose first line is indented needs an explicit indicator' ],

    [ 'two trailing newlines',
      entry_with(notes => "body\n\n"),
      0, 'clip chomping would silently drop the second newline' ],

    [ 'carriage return in the value',
      entry_with(notes => "body\r\nmore\n"),
      0, 'CR is ambiguous with the line break the block form introduces' ],

    [ 'a line that is only whitespace',
      entry_with(notes => "para one\n   \npara two\n"),
      0, 'a whitespace-only line is trailing whitespace wearing a disguise' ],

    [ 'single-line note',
      entry_with(notes => 'one sentence, no newline anywhere'),
      0, 'the ordinary case must keep the quoted form' ],

    # Not about the block form at all: the value that must NOT become one.
    # Five entries describe mdxfind separator bytes and spell them as the two
    # characters backslash and n. Turning those into a real newline would
    # rewrite the claim.
    [ 'a literal backslash-n in the text',
      entry_with(notes => 'emit(md5(md5(pass).S)) where S = \\n, \\r, \\r\\n'),
      0, 'backslash-n as text is not a newline and must stay quoted' ],

    [ 'a line that would parse as YAML on its own',
      entry_with(notes => "prose\n- kind: same-computation\n  entry: x\n"),
      1, 'block content is opaque text; structure inside it must survive' ],

    [ 'a tab inside the content',
      entry_with(notes => "before\n\tindented by tab\nafter\n"),
      undef, 'whichever form is chosen, the tab must come back' ],

    [ 'quotes and backslashes',
      entry_with(notes => qq(he said "no"\nand a backslash \\ too\n)),
      1, 'a block needs no escaping, which is most of the point' ],

    [ 'a colon-space inside the content',
      entry_with(notes => "key: value looking line\nsecond\n"),
      1, 'a colon in prose does not make it a mapping' ],
);

my ($pass, $fail) = (0, 0);

# check($ok, $label) - one assertion.
sub check {
    my ($ok, $label) = @_;
    if ($ok) { $pass++; print "ok   $label\n" }
    else     { $fail++; print "FAIL $label\n" }
    return;
}

for my $c (@CASES) {
    my ($name, $entry, $want_block, $why) = @$c;

    my $text = entry_text($entry);

    # 1. It must parse.
    my $back = eval { YAML::XS::Load($text) };
    if ($@ || ref $back ne 'HASH') {
        $fail++;
        my $err = $@ || 'not a mapping';
        $err =~ s/\s+/ /g;
        print "FAIL $name: emitted text does not parse back ($err)\n";
        next;
    }

    # 2. Every string that went in must come back byte for byte. Walk the
    #    structure rather than naming fields, so a case added later is covered
    #    without touching this loop.
    my $lost = compare($entry, $back, '');
    check(!defined $lost, "$name: round-trips" . (defined $lost ? " [$lost]" : ''));

    # 3. The form, where the case cares which one was chosen. A block scalar
    #    is a key whose value is "|" or "|-" and nothing else on the line.
    next unless defined $want_block;
    my $is_block = ($text =~ /^\s*(?:- )?\w+: \|-?$/m) ? 1 : 0;
    check($is_block == $want_block,
          "$name: " . ($want_block ? 'block form' : 'quoted form') . " -- $why");
}

# compare($want, $got, $path) - undef when identical, else the first path that
# differs. Recurses hashes and arrays; compares leaves as strings.
sub compare {
    my ($want, $got, $path) = @_;
    if (ref $want eq 'HASH') {
        return "$path: not a hash" unless ref $got eq 'HASH';
        for my $k (sort keys %$want) {
            my $d = compare($want->{$k}, $got->{$k}, $path eq '' ? $k : "$path.$k");
            return $d if defined $d;
        }
        return undef;
    }
    if (ref $want eq 'ARRAY') {
        return "$path: not an array"    unless ref $got eq 'ARRAY';
        return "$path: length differs"  unless @$want == @$got;
        for my $i (0 .. $#$want) {
            my $d = compare($want->[$i], $got->[$i], "$path.$i");
            return $d if defined $d;
        }
        return undef;
    }
    return undef if !defined $want && !defined $got;
    return "$path: one side undef" if !defined $want || !defined $got;
    return undef if "$want" eq "$got";
    return "$path: " . _show($want) . ' -> ' . _show($got);
}

# _show($s) - a string with its whitespace made visible, truncated, so a
# failure report distinguishes "body\n" from "body\n\n".
sub _show {
    my ($s) = @_;
    $s = substr($s, 0, 60) . '...' if length($s) > 60;
    $s =~ s/\\/\\\\/g;
    $s =~ s/\n/\\n/g;
    $s =~ s/\r/\\r/g;
    $s =~ s/\t/\\t/g;
    return qq{"$s"};
}

printf STDERR "- %d passed, %d failed\n", $pass, $fail;
exit($fail ? 1 : 0);
