#!/usr/bin/perl
#-----------------------------------------------------------------------
#
# Name: test-verify-solo-gate.pl
# Description: assert that verify-vectors.pl's SOLO fallbacks are gated per
#              (VECTOR, identifier) and not per (ENTRY, identifier)
#
# Project: cracking-rosetta | Phase: 5 - promote mappings to tier 'vector'
#
#-----------------------------------------------------------------------
# METHODOLOGY AND WHY THIS EXISTS
#
# The mdxfind and hashcat solo fallbacks re-run ONE hash with ONE candidate
# so that a re-serializing identifier's crack can be attributed. Both read a
# gate first: "has this pair already been settled?"
#
# Until 2026-09-09 that gate read %cracked, which is an ENTRY-level fact.
# The two coincide on a single-vector entry and diverge on every other, so a
# grouped run that attributed ONE vector suppressed the retry for every
# SIBLING it could not attribute, and the sibling kept reads_in: []. Measured
# 2026-09-08 on argon2: mdxfind pinned to ^ARGON2$ reports "3 hash(es) -> 2
# cracked" and vector [0] stays unread, yet cracks immediately handed to the
# same binary alone.
#
# THE FAILURE MODE IS SILENCE IN BOTH DIRECTIONS, which is the whole reason
# for this file. A gate that closes again loses reads_in on sibling vectors
# and nothing reports it -- failure never demotes, so the tier already
# written stands. A gate that opens unconditionally costs one process per
# vector per identifier across the corpus and equally says nothing.
#
# THE OUTCOME CANNOT TELL THOSE APART, so the assertions read the SCRATCH
# FILES. A solo run that finds nothing leaves the entry byte-identical to one
# that never ran, so "did it fire" has no observable in the data at all. The
# tool therefore writes mx.<type>.<i>.solo.<vector index>.* and
# hc.<mode>.solo.<vector index>.*, and this reaches into that on purpose --
# the same argument, and the same precedent, as test-verify-native.pl.
#
# SIX ASSERTIONS PER TOOL, AND THE MIDDLE PAIR IS THE POINT.
#
#   1. SIBLING. Two vectors, one crackable and one not. The grouped run
#      attributes the first, so the ENTRY has a crack under that identifier.
#      The solo run must still fire for the SECOND. This is the defect.
#   2. NOT ALWAYS-ON. Two vectors, BOTH crackable. The grouped run attributes
#      both, so no solo run may fire for either. Without this, "the gate
#      opens when it should" and "the gate is gone" are the same reading,
#      since case 1 passes under both.
#   3. UNCHANGED. Two vectors, NEITHER crackable. Both get a solo run, as
#      they always did. This is the pre-existing behaviour the change must
#      not disturb.
#
# The uncrackable vector is a digest of a string that is in no wordlist the
# run builds, so "not cracked" here is a fact about the input and not about
# the tool -- and case 3 is the positive control for that, since it asserts
# the tool does reach those vectors.
#
# It needs a cracker, so it is NOT in CI -- validate.yml deliberately runs
# none -- and it skips LOUDLY per tool when the binary is absent, because a
# skip must not read as a pass.
#
# USAGE
#   perl tools/test-verify-solo-gate.pl            run the assertions
#   perl tools/test-verify-solo-gate.pl --verbose  print each case's outcome
#   MDXFIND= / HASHCAT= override where each binary is looked for.
#   Exit 0 all assertions passed (or skipped), 1 one or more failed.
#
# DEPENDENCIES
#   perl, YAML::XS, tools/lib/RosettaTools.pm, tools/verify-vectors.pl,
#   an mdxfind with type MD5 and/or a hashcat with mode 0
#
#-----------------------------------------------------------------------
# Generated by Claude Opus 5 on 2026-09-09

use strict;
use warnings;
use FindBin qw($RealBin);
use lib "$RealBin/lib";
use RosettaTools qw(tool_path);
use Digest::MD5 qw(md5_hex);
use File::Temp qw(tempdir);
use File::Path qw(make_path);
use YAML::XS;

my $PROG = 'test-verify-solo-gate.pl';
if (grep { /^(?:-h|--help)$/ } @ARGV) {
    print <<"USAGE";

Usage: $PROG [--verbose]

   -v, --verbose     print each case's outcome
   -h, --help        this help

   Asserts that verify-vectors.pl's solo fallbacks fire per VECTOR and not
   per entry: that a vector whose SIBLING already cracked still gets its own
   run, that two vectors which both cracked get none, and that two vectors
   which cracked neither still get one each.

   Needs mdxfind and/or hashcat (\$MDXFIND, \$HASHCAT, else the resolver
   defaults). Skips loudly per tool when the binary is absent, because a skip
   must not read as a pass. Not run in CI: validate.yml runs no cracker.

   Exit 0 all assertions passed or skipped, 1 one or more failed.
USAGE
    exit 0;
}

my $verbose = grep { /^-v$|^--verbose$/ } @ARGV;
my $VV = "$RealBin/verify-vectors.pl";
-x $VV or die "$PROG: cannot find verify-vectors.pl at $VV\n";

# Computed, never transcribed, so a typo cannot masquerade as a behaviour
# change. CRACK falls to the candidate the entry carries; DEAF is a digest of
# a string that reaches no wordlist this run builds, so it cannot crack.
my $CRACK = md5_hex('password123');
my $DEAF  = md5_hex('no-candidate-in-any-wordlist-here');

my ($pass, $fail) = (0, 0);
sub ok {
    my ($cond, $what, $detail) = @_;
    if ($cond) { $pass++; print STDERR "- ok    $what\n" if $verbose }
    else       { $fail++; print STDERR "- FAIL  $what\n";
                 print STDERR "-       $detail\n" if defined $detail }
}

# id => [ [vector hashes], [vector indices that MUST get a solo run],
#         [indices that must NOT], why ]
my @CASE = (
    [ 'sg-sibling', [ $CRACK, $DEAF ], [1], [0],
      'a vector whose SIBLING cracked must still get its own solo run' ],
    [ 'sg-both',    [ $CRACK, $CRACK ], [], [0, 1],
      'two vectors that both cracked need no solo run at all' ],
    [ 'sg-neither', [ $DEAF, $DEAF ], [0, 1], [],
      'two vectors that cracked neither still get one solo run each' ],
);

# tool => [ binary, how the entry names the identifier, the scratch-file
#           prefix for a given vector index ]
my %TOOL = (
    mdxfind => {
        bin   => tool_path('mdxfind'),
        block => sub { { types => ['MD5'], verified => 'asserted' } },
        scratch => sub { my $vi = shift; "mx.MD5.1.solo.$vi." },
    },
    hashcat => {
        bin   => tool_path('hashcat'),
        block => sub { { modes => [0], verified => 'asserted' } },
        scratch => sub { my $vi = shift; "hc.0.solo.$vi." },
    },
);

my $TMP = tempdir(CLEANUP => 1);

for my $tool (sort keys %TOOL) {
    my $t = $TOOL{$tool};
    unless (-x $t->{bin}) {
        print STDERR "- SKIPPED $tool: no binary at $t->{bin} "
                   . "(set \U$tool\E= to point at one)\n";
        print STDERR "-   This is a skip, NOT a pass: the $tool gate was not "
                   . "checked.\n";
        next;
    }

    for my $c (@CASE) {
        my ($id, $hashes, $want_fired, $want_quiet, $why) = @$c;
        my $dir  = "$TMP/$tool-$id";
        my $adir = "$dir/algorithms";
        my $wdir = "$dir/work";
        make_path($adir, $wdir);

        # Every vector carries the SAME plaintext on purpose: the wordlist a
        # grouped run builds then holds exactly one candidate, so a vector
        # that does not crack did not crack for want of the right string and
        # not for want of being asked.
        YAML::XS::DumpFile("$adir/$id.yaml", {
            id      => $id,
            name    => $id,
            status  => 'needs-review',
            tools   => { $tool => $t->{block}->() },
            vectors => [ map { { hash => $_, pass => 'password123',
                                 source => 'sheet' } } @$hashes ],
        });

        my @extra = ("--$tool", $t->{bin});
        my $rc = system($^X, $VV, '--tool', $tool, @extra,
                        '--algorithms', $adir, '--work', $wdir,
                        '--timeout', '120', '--only', $id) >> 8;
        ok($rc == 0, "$tool/$id: verify-vectors.pl exited 0", "exit was $rc");

        opendir(my $dh, $wdir) or die "$wdir: $!";
        my @files = readdir $dh;
        closedir $dh;

        for my $vi (@$want_fired) {
            my $p = $t->{scratch}->($vi);
            ok((grep { index($_, $p) == 0 } @files) > 0,
               "$tool/$id: solo run FIRED for vector $vi -- $why",
               "no scratch file '$p*' in $wdir; saw: "
               . join(' ', sort grep { !/^\.\.?$/ } @files));
        }
        for my $vi (@$want_quiet) {
            my $p = $t->{scratch}->($vi);
            ok((grep { index($_, $p) == 0 } @files) == 0,
               "$tool/$id: solo run did NOT fire for vector $vi -- $why",
               "found scratch file '$p*' in $wdir");
        }
    }
}

printf STDERR "- %s: %d assertion(s) passed, %d failed\n", $PROG, $pass, $fail;
if ($fail) {
    print STDERR <<'WHY';
-
- If the SIBLING case did not fire, the gate has gone back to reading
-   %cracked, which is entry-level. Sibling vectors will silently stop
-   acquiring reads_in and nothing else in the repository will notice.
- If the BOTH case fired, the gate is gone rather than corrected, and every
-   verified vector now costs an extra process per identifier.
- If the NEITHER case stopped firing, the %read gate (mdxfind) or the
-   per-vector cracked map (hashcat) is being set where no crack happened,
-   which would also suppress the fallback the solo run exists to provide.
WHY
}
exit($fail ? 1 : 0);
