#!/usr/bin/perl
#-----------------------------------------------------------------------
#
# Name: test-rosetta-john.pl
# Description: assert what RosettaJohn rewrites and, more importantly, what
#              it refuses
# Category: cracking-rosetta test
#
# Project: cracking-rosetta | Phase: 7 - pre-publication readiness
#
#-----------------------------------------------------------------------
# METHODOLOGY AND WHY THIS EXISTS
#
# RosettaJohn rewrites an hx-style expression into the notation john's dynamic
# compiler parses, and the string it produces is handed to john as PROOF: if
# john recovers the entry's plaintext, the entry's expression reaches tier
# vector. So a rewrite that quietly drops a token does not fail loudly -- it
# manufactures a proof for a construction nobody computes. cap() on a
# lowercase digest and lower() on a hex string are both no-ops on the inputs a
# test vector happens to carry, which is exactly how md5cap once looked like
# plain md5.
#
# That makes the REFUSALS the part worth testing. A missing rewrite costs
# coverage and is visible in the run report; a wrong one is silent and
# permanent. Every case below that expects undef is a token john does not
# have, or a shape john cannot express -- pad() on anything but $p, upper() of
# a concatenation, base64() of a hex string rather than of the raw digest.
#
# The positive cases are the six rewrites the module claims, one each, plus
# the two identities: an expression needing no rewrite must come back
# unchanged, or derive-expressions.pl would stop proving the 392 entries that
# were already fine (measured 2026-09-02).
#
# USAGE
#   perl -Itools/lib tools/test-rosetta-john.pl
#   Exit 0 all assertions passed, 1 one or more failed, 2 usage.
#
# DEPENDENCIES
#   perl, tools/lib/RosettaJohn.pm
#
#-----------------------------------------------------------------------
# Generated by Claude Opus 5 on 2026-09-02

use strict;
use warnings;

use FindBin qw($RealBin);
use lib "$RealBin/lib";
use RosettaJohn qw(hx_to_john);

my $PROG = 'test-rosetta-john.pl';

if (@ARGV && $ARGV[0] =~ /^(-h|--help)$/) {
    print <<"USAGE";
Usage: $PROG

   Runs the assertion table. Takes no arguments.
   Exit 0 all passed, 1 one or more failed, 2 usage.
USAGE
    exit 0;
}
if (@ARGV) { print STDERR "$PROG: takes no arguments\n"; exit 2 }

# [ hx expression, expected john spelling or undef, what it is testing ]
my @CASES = (
    # The identities. These must not change: they are most of the corpus.
    [ 'md5($p)',            'md5($p)',            'no rewrite needed'        ],
    [ 'sha1(md5($p.$s))',   'sha1(md5($p.$s))',   'nested, still unchanged'  ],
    [ 'md4(utf16($p))',     'md4(utf16($p))',     'utf16 is john\'s own'     ],
    [ 'sha1(utf16be($p))',  'sha1(utf16be($p))',  'so is utf16be'            ],

    # The six rewrites.
    [ 'md5(upper(md5($p)))',      'md5(MD5($p))',     'upper -> UC flavor'  ],
    [ 'md5(lower(md5($p)))',      'md5(md5($p))',     'lower is the default' ],
    [ 'md5(hex(md5_raw($p)))',    'md5(md5($p))',     'hex of raw is base16' ],
    [ 'md5(base64(md5_raw($p)))', 'md5(md5_64($p))',  'base64 of raw -> _64' ],
    [ 'md5(upper($p))',           'md5(uc($p))',      'casing the password'  ],
    [ 'md5(pad($p,100))',         'md5(pad100($p))',  'pad length -> token'  ],

    # Structure survives the rewrite.
    [ 'sha1(upper(md5($p)).$s)',  'sha1(MD5($p).$s)', 'rewrite inside concat'],
    [ 'upper(md4(utf16($p)))',    'MD4(utf16($p))',   'rewrite at the top'   ],
    [ 'md5($c1.upper(sha1(sha1_raw($p)))),c1=*',
      'md5($c1.SHA1(sha1_raw($p))),c1=*',
      'the constants trailer is carried across untouched' ],

    # The refusals. Each of these is a token or a shape john does not have,
    # and each would be a silent false proof if it were dropped instead.
    [ 'md5(cut(md5($p),0,16))',   undef, 'no cut() in john'                  ],
    [ 'md5(rev($p))',             undef, 'no rev()'                          ],
    [ 'md5(cap(md5($p)))',        undef, 'no cap() -- the md5cap trap'       ],
    [ 'md5(frombase64($p))',      undef, 'no frombase64()'                   ],
    [ 'md5(utf16le($p))',         undef, 'john spells this utf16(), not le'  ],
    [ 'md5(base64(md5($p)))',     undef, 'base64 of HEX is not the _64 flavor'],
    [ 'md5(base64($p))',          undef, 'base64 of the password either'     ],
    [ 'md5(pad(md5($p),100))',    undef, 'john pads only $p'                 ],
    [ 'md5(pad($p,7))',           undef, 'and only at 16, 20 or 100'         ],
    [ 'sha1(upper(md5($p).$s))',  undef, 'no casing a concatenation'         ],
    [ 'md5(lower($s))',           undef, 'no casing the salt'                ],
    [ 'md5(upper(md5_raw($p)))',  undef, 'no upper-case flavor of a raw'    ],
    [ 'md5(md5($s.$p):$s)',       undef, 'a colon is not in the grammar'     ],
);

my ($pass, $fail) = (0, 0);
for my $c (@CASES) {
    my ($in, $want, $why) = @$c;
    my $got = hx_to_john($in);
    my $ok  = defined $want ? (defined $got && $got eq $want)
                            : !defined $got;
    if ($ok) { $pass++; printf "ok   %s\n", $why }
    else {
        $fail++;
        printf "FAIL %s\n     %s\n     want %s\n     got  %s\n",
            $why, $in,
            defined $want ? $want : '(refused)',
            defined $got  ? $got  : '(refused)';
    }
}

printf STDERR "- %d passed, %d failed\n", $pass, $fail;
exit($fail ? 1 : 0);
