#!/usr/bin/perl
#-----------------------------------------------------------------------
#
# Name: test-hashpipe-c.pl
# Description: assert what `hashpipe -c` actually does with an iteration
#              label, so the day upstream changes it we are told
#
#-----------------------------------------------------------------------
# METHODOLOGY AND WHY THIS EXISTS
#
# hashpipe v1.190 added -c: verify each line against its own leading
# TYPE[xNN] label, no detection and no fallback. That is a per-line TYPE PIN
# and it is the equivalent of `mdxfind -h '^TYPE$'`, which makes hashpipe a
# pinnable third oracle instead of a suggester.
#
# It has one hole. A pair that matches at ONE iteration is accepted whatever
# depth the label asks for, and re-emitted as x01. Everything else
# off-diagonal is correctly refused. Reported 2026-09-04 and CONFIRMED BY
# UPSTREAM as a bug, so it is expected to be fixed -- which is exactly why
# this file exists rather than a sentence somewhere.
#
# CLAUDE.md tells every future reader to code around the hole: read the
# EMITTED suffix, never the exit status. That instruction has a shelf life.
# Without a check, the way anyone would learn the hole had closed is by
# remembering to re-test it, and this repository has already been bitten by
# a "documented drift detector" that was a human remembering to read a diff
# (see the extract-hashpipe.pl history in CLAUDE.md).
#
# SO THE ASSERTION IS DELIBERATELY OF THE CURRENT, BUGGY BEHAVIOUR. When
# upstream fixes it this test FAILS, and the failure text says what to do:
# drop the guard. A test that passed either way would be decoration.
#
# WHY IT IS NOT IN CI
#
# validate.yml deliberately never runs a cracker -- tier `vector` must not be
# reachable by anything a pull request can influence -- and a hosted runner
# has no hashpipe. So this skips cleanly when the binary is absent, and the
# skip is stated rather than silent: an absent binary must not read as a pass.
#
# USAGE
#   perl tools/test-hashpipe-c.pl            run the assertions
#   perl tools/test-hashpipe-c.pl --verbose  print the whole matrix
#   HASHPIPE=/path/to/hashpipe  overrides where the binary is looked for.
#   Exit 0 all assertions passed (or skipped), 1 one or more failed.
#
# DEPENDENCIES
#   perl, tools/lib/RosettaTools.pm, a hashpipe binary with -c
#
#-----------------------------------------------------------------------
# Generated by Claude Opus 5 on 2026-09-04

use strict;
use warnings;
use FindBin qw($RealBin);
use lib "$RealBin/lib";
use RosettaTools qw(tool_path);
use Digest::MD5 qw(md5_hex);
use File::Temp qw(tempdir);

my $PROG = 'test-hashpipe-c.pl';
if (grep { /^(?:-h|--help)$/ } @ARGV) {
    print <<"USAGE";

Usage: $PROG [--verbose]

   -v, --verbose     print the whole label-against-truth matrix
   -h, --help        this help

   Asserts what `hashpipe -c` does with an iteration label: it verifies at
   the labelled depth, EXCEPT that a depth-1 match is accepted under any
   depth and re-emitted as x01. Upstream confirmed that hole as a bug on
   2026-09-04, so the current behaviour is asserted as it stands and this
   test FAILS when a fix lands, saying to drop the guard CLAUDE.md carries.

   Needs a hashpipe binary (\$HASHPIPE, else the resolver default). Skips
   loudly when there is none, because a skip must not read as a pass. Not
   run in CI: validate.yml deliberately runs no cracker.

   Exit 0 all assertions passed or skipped, 1 one or more failed.
USAGE
    exit 0;
}

my $verbose = grep { /^-v$|^--verbose$/ } @ARGV;
my $HP   = tool_path('hashpipe');
my $PASS = 'password';
my $MAX  = 5;

unless (-x $HP || `command -v $HP 2>/dev/null`) {
    print STDERR "- SKIPPED: no hashpipe at $HP (set HASHPIPE= to point at one)\n";
    print STDERR "-   This is a skip, NOT a pass: nothing about -c was checked.\n";
    exit 0;
}

my $TMP = tempdir(CLEANUP => 1);

# md5^n($PASS), computed here rather than transcribed.
my @digest;
{
    my $h = $PASS;
    for my $n (1 .. $MAX) { $h = md5_hex($h); $digest[$n] = $h }
}

# run_c($line) - feed one line to `hashpipe -c` and say what happened.
# Streams are read SEPARATELY and that is not fastidiousness: a rejected line
# is echoed to stderr VERBATIM, and where the label already matches what the
# tool would emit, the accepted and rejected forms are byte-identical. Merge
# the streams and the two become indistinguishable.
sub run_c {
    my ($line) = @_;
    my ($o, $e) = ("$TMP/o", "$TMP/e");
    open my $in, '|-', "'$HP' -c > '$o' 2> '$e'" or die "cannot run $HP: $!\n";
    print {$in} "$line\n";
    my $ok = close $in;
    my $status = $?;
    my $out = do { local (@ARGV, $/) = ($o); <> } // '';
    my $err = do { local (@ARGV, $/) = ($e); <> } // '';
    chomp for ($out, $err);
    return {
        verified => (length $out ? 1 : 0),
        label    => (split / /, $out)[0] // '',
        stderr   => $err,
        exit     => ($status >> 8),
    };
}

my ($pass_n, $fail_n) = (0, 0);
sub check {
    my ($ok, $why, $detail) = @_;
    if ($ok) { $pass_n++; printf "ok   %s\n", $why }
    else     { $fail_n++; printf "FAIL %s\n%s", $why, ($detail // '') }
}

#-----------------------------------------------------------------------
# The matrix: label depth against true depth. Measured 2026-09-04 on
# v1.190. Accepted exactly when the label matches the truth, OR when the
# truth is 1 -- that second clause is the bug.
#-----------------------------------------------------------------------
my $leak_seen = 0;
printf "%-8s%s\n", 'label', join '', map { sprintf '%-11s', "md5^$_" } 1 .. $MAX
    if $verbose;
for my $label (1 .. $MAX) {
    my @row;
    for my $true (1 .. $MAX) {
        my $r = run_c(sprintf 'MD5x%02d %s:%s', $label, $digest[$true], $PASS);
        push @row, $r->{verified} ? $r->{label} : '.';

        my $want_verified = ($label == $true || $true == 1) ? 1 : 0;
        my $why = sprintf 'MD5x%02d against md5^%d: %s', $label, $true,
            $want_verified ? 'verifies' : 'refused';
        # The diagonal and the true off-diagonal refusals are the contract.
        if ($label == $true) {
            check($r->{verified} && $r->{label} eq sprintf('MD5x%02d', $label),
                  "$why as MD5x" . sprintf('%02d', $label),
                  sprintf("     got verified=%d label=%s\n", $r->{verified}, $r->{label}));
        }
        elsif ($true == 1) {
            # THE BUG. Asserted as-is so a fix breaks this loudly.
            $leak_seen++ if $r->{verified};
            check($r->{verified} && $r->{label} eq 'MD5x01',
                  "$why as MD5x01 -- the CONFIRMED UPSTREAM BUG, still present",
                  "     A depth-1 match is no longer accepted under a deeper\n"
                . "     label. That means upstream FIXED it. Re-measure, then\n"
                . "     drop the guard in CLAUDE.md's iteration-suffix pitfall\n"
                . "     and delete this branch.\n");
        }
        else {
            check(!$r->{verified},
                  $why,
                  sprintf("     wrongly verified as %s\n", $r->{label}));
        }
    }
    printf "MD5x%02d  %s\n", $label, join '', map { sprintf '%-11s', $_ } @row
        if $verbose;
}

#-----------------------------------------------------------------------
# The parts that are strict, so a regression there is caught too.
#-----------------------------------------------------------------------
my $r = run_c("NTLM $digest[1]:$PASS");
check(!$r->{verified}, 'a wrong type of the same width is refused',
      sprintf("     wrongly verified as %s\n", $r->{label}));

$r = run_c("MD5x01 $digest[1]:wrongpw");
check(!$r->{verified}, 'a wrong plaintext under the right type is refused',
      sprintf("     wrongly verified as %s\n", $r->{label}));

$r = run_c("NOSUCHTYPE $digest[1]:$PASS");
check(!$r->{verified} && $r->{exit} == 2 && $r->{stderr} =~ /INVALID LABEL/,
      'an unknown label is fatal: INVALID LABEL, exit 2',
      sprintf("     exit=%d stderr=%s\n", $r->{exit}, $r->{stderr}));

$r = run_c("$digest[1]:$PASS");
check(!$r->{verified} && $r->{exit} == 2,
      'a line with no label at all is fatal too',
      sprintf("     exit=%d stderr=%s\n", $r->{exit}, $r->{stderr}));

printf STDERR "- %d passed, %d failed (hashpipe %s)\n", $pass_n, $fail_n, $HP;
printf STDERR "- the depth-1 leak is still present in %d of %d deeper labels\n",
    $leak_seen, $MAX - 1;
exit($fail_n ? 1 : 0);
