#!/usr/bin/perl
#-----------------------------------------------------------------------
#
# Name: test-verify-split.pl
# Description: assert verify-vectors.pl's mdxfind SPLIT fallback -- that it
#              fires for a salt field carrying a second value in EITHER
#              order, and that it manufactures nothing
#
# Project: cracking-rosetta | Phase: 5 - promote mappings to tier 'vector'
#
#-----------------------------------------------------------------------
# METHODOLOGY AND WHY THIS EXISTS
#
# Some mdxfind types publish a vector whose salt position holds TWO values
# separated by a space, and mdxfind reads the second out of the pepper array
# (-j) rather than out of the hash line. Handed the whole field it answers
# "None found, sorry!", which is indistinguishable from a wrong mapping.
#
# THE GATE WAS WRONG TWICE, IN OPPOSITE DIRECTIONS.
#
#   Until 2026-09-16 the fallback ran only for a type flagged 'j' in the
#   inventory. The flag names PEPPER types; it does not name the types that
#   spell a second value in the salt position, and those are not the same
#   set. SHA1WRLUCTRUNCSALT (e672) is flagged 'f,s' and sat at tier
#   'upstream' carrying a note that mdxfind would not reproduce its own
#   published example -- which was a fact about the gate.
#
#   Widening it uncovered the second: the split was tried in ONE order.
#   SHA1WRLUCTRUNCSALT writes "<digest>:<salt> <N>", salt first, N being the
#   truncation length. SHA1MD5xSALT writes "<digest>:<N> <salt>", the other
#   way round, N being the inner iteration count its own name's `x` denotes.
#   Nothing in the inventory says which a type wants.
#
# So this asserts BOTH orders, and one thing more important than either.
#
# THE RELAXATION MUST NOT MANUFACTURE A VERIFICATION. Trying two shapes of
# the same input is one step from "try variants until one passes", which is
# the re-casing pitfall CLAUDE.md names. It is safe here for a reason that
# has to be tested rather than asserted: mx_echo_is compares the ECHOED hash
# against the string the entry stores, so a split that dropped a field would
# echo something shorter and attribute nothing. The negative case is what
# separates "the fallback works" from "the fallback passes anything" -- both
# leave the positive cases green.
#
# THREE CASES.
#
#   1. SALT FIRST.      SHA1WRLUCTRUNCSALT reaches tier 'vector'.
#   2. PARAMETER FIRST. SHA1MD5xSALT reaches tier 'vector'.
#   3. WRONG PLAINTEXT. The same vector with a plaintext that does not
#      produce it must stay below 'vector' under both orders.
#
# It needs an mdxfind with those two types, so it is NOT in CI -- validate.yml
# deliberately runs no cracker -- and it skips LOUDLY when there is none.
#
# USAGE
#   perl tools/test-verify-split.pl            run the assertions
#   perl tools/test-verify-split.pl --verbose  print each case's outcome
#   MDXFIND= overrides where the binary is looked for.
#   Exit 0 all assertions passed (or skipped), 1 one or more failed.
#
# DEPENDENCIES
#   perl, YAML::XS, tools/lib/RosettaTools.pm, tools/verify-vectors.pl,
#   an mdxfind carrying SHA1WRLUCTRUNCSALT and SHA1MD5xSALT
#
#-----------------------------------------------------------------------
# Generated by Claude Opus 5 on 2026-09-16

use strict;
use warnings;
use FindBin qw($RealBin);
use lib "$RealBin/lib";
use RosettaTools qw(tool_path);
use File::Temp qw(tempdir);
use File::Path qw(make_path);
use YAML::XS;

my $PROG = 'test-verify-split.pl';
if (grep { /^(?:-h|--help)$/ } @ARGV) {
    print <<"USAGE";

Usage: $PROG [--verbose]

   -v, --verbose     print each case's outcome
   -h, --help        this help

   Asserts that verify-vectors.pl splits a two-value salt field in EITHER
   order, and that the relaxation cannot promote a vector whose plaintext
   does not produce it.

   Needs an mdxfind with SHA1WRLUCTRUNCSALT and SHA1MD5xSALT (\$MDXFIND, else
   the resolver default). Skips loudly when there is none, because a skip must
   not read as a pass. Not run in CI: validate.yml runs no cracker.

   Exit 0 all assertions passed or skipped, 1 one or more failed.
USAGE
    exit 0;
}

my $verbose = grep { /^-v$|^--verbose$/ } @ARGV;
my $VV = "$RealBin/verify-vectors.pl";
-x $VV or die "$PROG: cannot find verify-vectors.pl at $VV\n";
my $MDXFIND = tool_path('mdxfind');

unless (-x $MDXFIND) {
    print STDERR "- SKIPPED: no mdxfind at $MDXFIND (set MDXFIND= to point at one)\n";
    print STDERR "-   This is a skip, NOT a pass: the split fallback was not checked.\n";
    exit 0;
}

# Both vectors are upstream's own, and the type each belongs to states the
# field order. They are transcribed rather than computed because only mdxfind
# can produce them; the run itself is what checks them.
my @CASE = (
    [ 'sp-salt-first', 'SHA1WRLUCTRUNCSALT',
      '18e34151169d78716359709e30233f238e5e9a54:1122334455667788 128',
      'password123', 'vector',
      'salt first, truncation length second' ],

    [ 'sp-param-first', 'SHA1MD5xSALT',
      '12d66f224a0fbdf4b7371400f9fece702d4c48a5:1 Salt',
      'password123', 'vector',
      'iteration count first, salt second -- the opposite order' ],

    [ 'sp-wrong-plain', 'SHA1WRLUCTRUNCSALT',
      '18e34151169d78716359709e30233f238e5e9a54:1122334455667788 128',
      'not-the-plaintext', 'asserted',
      'a plaintext that does not produce this digest must stay unproven '
      . 'under BOTH orders' ],
);

my ($pass, $fail) = (0, 0);
sub ok {
    my ($cond, $what, $detail) = @_;
    if ($cond) { $pass++; print STDERR "- ok    $what\n" if $verbose }
    else       { $fail++; print STDERR "- FAIL  $what\n";
                 print STDERR "-       $detail\n" if defined $detail }
}

my $TMP = tempdir(CLEANUP => 1);

for my $c (@CASE) {
    my ($id, $type, $hash, $plain, $want, $why) = @$c;
    my $adir = "$TMP/$id/algorithms";
    my $wdir = "$TMP/$id/work";
    make_path($adir, $wdir);

    # tier starts at 'asserted' so a promotion shows as a CHANGE rather than
    # as a value that was already there.
    YAML::XS::DumpFile("$adir/$id.yaml", {
        id      => $id,
        name    => $id,
        status  => 'needs-review',
        tools   => { mdxfind => { types => [$type], verified => 'asserted' } },
        vectors => [ { hash => $hash, pass => $plain, source => 'mdxfind' } ],
    });

    my $rc = system($^X, $VV, '--tool', 'mdxfind', '--mdxfind', $MDXFIND,
                    '--algorithms', $adir, '--work', $wdir,
                    '--timeout', '120', '--only', $id) >> 8;
    ok($rc == 0, "$id: verify-vectors.pl exited 0", "exit was $rc");

    my $got  = eval { YAML::XS::LoadFile("$adir/$id.yaml") };
    my $tier = $got ? ($got->{tools}{mdxfind}{verified} // '(none)') : '(unreadable)';
    ok($tier eq $want, "$id: tier is '$want' -- $why", "got '$tier'");
}

printf STDERR "- %s: %d assertion(s) passed, %d failed\n", $PROG, $pass, $fail;
if ($fail) {
    print STDERR <<'WHY';
-
- If a POSITIVE case failed, the split fallback has narrowed again: check that
-   it is not gated on the inventory's 'j' flag, which names PEPPER types and
-   not the types that spell two values in the salt position, and that BOTH
-   field orders are still tried.
- If the WRONG PLAINTEXT case reached tier vector, the relaxation has stopped
-   being one: mx_echo_is must still compare the echoed hash against the
-   string the entry stores. That would promote on a shape rather than on a
-   round trip, corpus-wide, and must be reverted rather than accommodated.
WHY
}
exit($fail ? 1 : 0);
