#!/usr/bin/perl
#-----------------------------------------------------------------------
#
# Name: test-rosetta-expr.pl
# Description: assert that RosettaExpr computes what mdxfind's own hx engine
#              computes, and that it still refuses everything it cannot
# Category: cracking-rosetta test
#
# Project: cracking-rosetta | Phase: 7 - pre-publication readiness
#
#-----------------------------------------------------------------------
# METHODOLOGY AND WHY THIS EXISTS
#
# RosettaExpr is an INDEPENDENT implementation of what an entry's expression
# computes. triage-expressions.pl uses it as the control that separates "john
# will not reproduce this" from "nobody can", and on the strength of a
# `corroborated` or `expression-wrong` verdict curate.pl either files a human
# question or suppresses one. So an off-by-one in cut(), or a cap() that
# capitalises the first CHARACTER rather than the first lower-case LETTER,
# does not fail loudly: it reports a correct expression as wrong, and buries
# or invents a curation question. That is the same trap that kept the module
# deliberately tiny in the first place.
#
# THE EXPECTED VALUES ARE UPSTREAM'S, NOT MINE
#
# Every value below was MEASURED by running mdxfind's own standalone hx
# evaluator, built from the source tree named in CLAUDE.md as the highest
# authority there is:
#
#   cc -O2 -I$M -DHX_STANDALONE -o hx $M/hx.c $M/hx_func.c $M/hx_ast.c \
#      $M/hx_compile.c $M/hx_vm.c $M/hx.tab.c $M/hx.lex.c $M/crypt-des.c \
#      $M/myprogress.c -lcrypto -lssl
#   ./hx -p rosetta -s NaCl 'base64(sha1_bin(salt . pass))'
#
# measured 2026-09-02 against mdxfind source RCS 1.545. That is why cases are
# carried in BOTH spellings: `hx` is the string that was handed to the oracle,
# `expr` is the same construction in this repository's notation ($p, $s,
# _raw). --oracle re-runs the whole table through a live hx binary and checks
# the fixture itself has not drifted, which is what makes re-measuring after
# an upstream pull a command rather than a memory.
#
# WHY THE REFUSALS MATTER MORE THAN THE AGREEMENTS
#
# A construction RosettaExpr cannot compute must return undef, never a value
# computed from a silently dropped token. Every refusal below is a function
# this host genuinely cannot evaluate (md4 -- no Digest::MD4 here; whirlpool,
# gost, ripemd, haval, sha3 likewise) or a shape outside the grammar. If one
# of them starts returning a value, triage gains a verdict it has not earned.
#
# NOT being in hx is NOT a reason to refuse, and saying so cost this fixture
# two wrong assertions until 2026-09-04. `sha224` and `sha384` are absent
# from hx's function table but present in this corpus's expression: fields,
# which take them from john's dynamics; they are computed exactly by core
# Perl, and the entries carrying them hold john-proven vectors that pin what
# the token means. The right question for a refusal is whether this host can
# compute the construction, not which upstream happens to spell it.
#
# USAGE
#   perl tools/test-rosetta-expr.pl            fixture only, no hx needed
#   perl tools/test-rosetta-expr.pl --oracle   also re-measure against hx
#   HX=/path/to/hx  overrides where the oracle is looked for.
#   Exit 0 all assertions passed, 1 one or more failed, 2 usage.
#
# DEPENDENCIES
#   perl, tools/lib/RosettaExpr.pm; --oracle additionally needs a built hx
#
#-----------------------------------------------------------------------
# Generated by Claude Opus 5 on 2026-09-02

use strict;
use warnings;

use FindBin qw($RealBin);
use lib "$RealBin/lib";
use RosettaExpr qw(compile_expression);

my $PROG = 'test-rosetta-expr.pl';

# The two inputs every case is evaluated on. Fixed, because the fixture is a
# measurement against exactly these.
my $PASS = 'rosetta';
my $SALT = 'NaCl';

my $oracle;
for (@ARGV) {
    if (/^(-h|--help)$/) {
        print <<"USAGE";
Usage: $PROG [--oracle]

   Runs the assertion table against RosettaExpr. Expected values were
   measured from mdxfind's own hx evaluator (see the header).

   --oracle   additionally re-run every case through a live hx binary and
              report where the FIXTURE has drifted from upstream. Looked for
              in \$HX, then tmp/hx-build/hx.

   Exit 0 all passed, 1 one or more failed, 2 usage.
USAGE
        exit 0;
    }
    if (/^--oracle$/) { $oracle = 1; next }
    print STDERR "$PROG: unknown argument '$_'\n";
    exit 2;
}

# [ hx spelling (what the oracle was asked), repository spelling (what
#   RosettaExpr is asked), expected output, what it is testing,
#   OPTIONALLY a password to use instead of $PASS ]
# An expected value of undef means RosettaExpr MUST refuse to compile it.
#
# The fifth element exists for the utf16 family and is used by the direct
# loop and by --oracle alike, so the two never diverge. Everything about
# utf16 that can be got wrong is on input 'rosetta' cannot express: it is a
# UTF-8 conversion rather than a byte widening, and the two agree on every
# ASCII string in this corpus. Those passwords are written as \x escapes so
# this file stays ASCII on disk.
my @CASES = (
    # --- the four hashes, plain -------------------------------------
    [ 'md5(pass)',    'md5($p)',    '975790dfb2854c88094fe62477a7d5f3',
      'md5' ],
    [ 'sha1(pass)',   'sha1($p)',   'd21af7ece046af0e12d3c38472792cd5f081c39f',
      'sha1' ],
    [ 'sha256(pass)', 'sha256($p)',
      '27c3d3b047672ba2cf4abd7688e81f4fbb044eadeec897b665fc76636069daa7',
      'sha256' ],
    [ 'sha512(pass)', 'sha512($p)',
      'a914375619cd494d3079f93dd4a7ed8848fbe4da9929700cdc4c31819a3f0685'
    . 'ec3f7e100762826f16c9a9a1f5983e1a25af01058ab0a178190322f8661f8137',
      'sha512' ],

    # --- concatenation and nesting: the pre-existing grammar --------
    [ 'md5(pass . salt)', 'md5($p.$s)', 'de49507c01828ef359c42b4ca81b76fd',
      'password then salt' ],
    [ 'md5(salt . pass)', 'md5($s.$p)', '54f76a539f8413d1efecb3955392b60e',
      'salt then password' ],
    [ 'sha1(md5(pass) . salt)', 'sha1(md5($p).$s)',
      'cb5b5ea60b1e1be368700f174428dea0a8800a15', 'nested, then concatenated' ],
    [ 'md5(md5(pass))', 'md5(md5($p))', 'bd62daf88a5f6d734e91228e7f2e540a',
      'md5 of the hex digest, not of the bytes' ],
    [ 'md5(pass . pass)', 'md5($p.$p)', '667cef28c3bf9136cbf819981d3412ea',
      'the same variable twice' ],

    # --- _raw: the whole reason the value model had to become bytes -
    [ 'hex(md5_bin(pass))', 'hex(md5_raw($p))',
      '975790dfb2854c88094fe62477a7d5f3', 'hex of raw is the default form' ],
    [ 'hex(sha1_bin(pass))', 'hex(sha1_raw($p))',
      'd21af7ece046af0e12d3c38472792cd5f081c39f', 'hex of a raw sha1' ],
    [ 'hex(sha256_bin(pass))', 'hex(sha256_raw($p))',
      '27c3d3b047672ba2cf4abd7688e81f4fbb044eadeec897b665fc76636069daa7',
      'hex of a raw sha256' ],
    [ 'base64(md5_bin(pass))', 'base64(md5_raw($p))', 'l1eQ37KFTIgJT+Ykd6fV8w==',
      'base64 of 16 RAW bytes' ],
    [ 'base64(sha1_bin(pass))', 'base64(sha1_raw($p))',
      '0hr37OBGrw4S08OEcnks1fCBw58=', 'base64 of 20 RAW bytes' ],
    [ 'base64(sha256_bin(pass))', 'base64(sha256_raw($p))',
      'J8PTsEdnK6LPSr12iOgfT7sETq3uyJe2Zfx2Y2Bp2qc=', 'base64 of 32 raw bytes' ],
    [ 'base64(sha1_bin(salt . pass))', 'base64(sha1_raw($s.$p))',
      'C09EeCrDYHtj4VjvztegmjIbxd0=', 'the EPiServer/SSHA shape' ],
    # The distinction STATE.md records as costing 20 entries: john's _64
    # flavour is base64 of the RAW digest, and this is base64 of the HEX.
    [ 'base64(md5(pass))', 'base64(md5($p))',
      'OTc1NzkwZGZiMjg1NGM4ODA5NGZlNjI0NzdhN2Q1ZjM=',
      'base64 of the 32-character HEX string is a different thing entirely' ],
    [ 'md5(base64(md5_bin(pass)))', 'md5(base64(md5_raw($p)))',
      'bf0ce280c48de2362bf5f8e921b545e6', 'hashing a base64 string' ],
    [ 'sha1(base64(md5_bin(pass)))', 'sha1(base64(md5_raw($p)))',
      '61491661bb74130c3c0c070e28b28deb1ad15deb', 'and with a different outer' ],

    # --- case, reversal, capitalisation ----------------------------
    [ 'upper(md5(pass))', 'upper(md5($p))',
      '975790DFB2854C88094FE62477A7D5F3', 'upper' ],
    [ 'lower(upper(md5(pass)))', 'lower(upper(md5($p)))',
      '975790dfb2854c88094fe62477a7d5f3', 'lower undoes upper' ],
    # The md5cap trap, measured rather than assumed: cap() moves the first
    # LOWER-CASE LETTER, which in this digest is the 'd' at index 6 -- not
    # the leading '9'. A cap() that capitalised index 0 would agree with hx
    # on every digest starting with a letter and silently differ on the rest.
    [ 'cap(md5(pass))', 'cap(md5($p))', '975790Dfb2854c88094fe62477a7d5f3',
      'cap moves the first lower-case LETTER, not the first character' ],
    [ 'cap(sha1(pass))', 'cap(sha1($p))',
      'D21af7ece046af0e12d3c38472792cd5f081c39f',
      'and here that letter IS at index 0' ],
    [ 'cap(upper(md5(pass)))', 'cap(upper(md5($p)))',
      '975790DFB2854C88094FE62477A7D5F3',
      'cap of an all-upper string changes nothing' ],
    [ 'cap(md5(pass), 2)', 'cap(md5($p),2)',
      '975790dfb2854c88094fe62477a7d5f3',
      'positional cap on a digit changes nothing' ],
    [ 'rev(md5(pass))', 'rev(md5($p))', '3f5d7a77426ef49088c4582bfd097579',
      'rev of a digest' ],
    [ 'rev(pass)', 'rev($p)', 'attesor', 'rev of the password' ],
    [ 'md5(rev(md5(pass)))', 'md5(rev(md5($p)))',
      '722c484d8b83d0852b35519e8a2d1bfa', 'rev inside a hash' ],
    [ 'rev(cut(sha1(pass),0,8))', 'rev(cut(sha1($p),0,8))', 'ce7fa12d',
      'rev of a slice' ],

    # --- cut / trunc: every argument form, including the clamps -----
    [ 'cut(md5(pass), 0, 16)', 'cut(md5($p),0,16)', '975790dfb2854c88',
      'cut with start and length' ],
    [ 'cut(sha1(pass), 0, 32)', 'cut(sha1($p),0,32)',
      'd21af7ece046af0e12d3c38472792cd5', 'the AXCRYPTSHA1 shape' ],
    [ 'cut(md5(pass), 8)', 'cut(md5($p),8)', 'b2854c88094fe62477a7d5f3',
      'cut with start only runs to the end' ],
    [ 'cut(md5(pass), -8)', 'cut(md5($p),-8)', '77a7d5f3',
      'a negative start counts back from the end' ],
    [ 'cut(md5(pass), 8, 8)', 'cut(md5($p),8,8)', 'b2854c88',
      'a slice from the middle' ],
    [ 'cut(md5(pass), 0, 999)', 'cut(md5($p),0,999)',
      '975790dfb2854c88094fe62477a7d5f3',
      'a length past the end is clamped, not an error' ],
    [ 'cut(md5(pass), 99, 4)', 'cut(md5($p),99,4)', '',
      'a start past the end yields the empty string' ],
    [ 'cut(pass, 2)', 'cut($p,2)', 'setta', 'cut on the password' ],
    [ 'cut(pass, -3, 2)', 'cut($p,-3,2)', 'tt',
      'negative start with a length' ],
    [ 'trunc(md5(pass), 10)', 'trunc(md5($p),10)', '975790dfb2',
      'trunc is cut from zero' ],
    [ 'md5(cut(md5(pass), 0, 16))', 'md5(cut(md5($p),0,16))',
      '39c54645d976ebc25d56e1c96f45ba7c', 'cut inside a hash' ],
    [ 'upper(cut(sha1(pass), 0, 20))', 'upper(cut(sha1($p),0,20))',
      'D21AF7ECE046AF0E12D3', 'cut then upper' ],

    # --- pad: NUL bytes, and truncation when already too long ------
    [ 'hex(pad(pass, 16))', 'hex(pad($p,16))',
      '726f7365747461000000000000000000', 'pad is NUL padding to a width' ],
    [ 'hex(pad(pass, 4))', 'hex(pad($p,4))', '726f7365',
      'pad TRUNCATES when the input is longer' ],
    [ 'hex(pad(md5_bin(pass), 20))', 'hex(pad(md5_raw($p),20))',
      '975790dfb2854c88094fe62477a7d5f300000000', 'pad on raw bytes' ],

    # --- the decoders ----------------------------------------------
    [ 'hex(fromhex(md5(pass)))', 'hex(fromhex(md5($p)))',
      '975790dfb2854c88094fe62477a7d5f3', 'fromhex then hex is identity' ],
    [ 'frombase64(base64(md5(pass)))', 'frombase64(base64(md5($p)))',
      '975790dfb2854c88094fe62477a7d5f3', 'frombase64 undoes base64' ],
    [ 'base64(pass)', 'base64($p)', 'cm9zZXR0YQ==', 'base64 of the password' ],

    # --- the refusals ----------------------------------------------
    # Each of these must come back undef. A value here is a token that got
    # dropped or guessed, and triage would spend it on a verdict.
    [ undef, 'md4($p)',           undef,
      'md4 is real hx, but there is no Digest::MD4 on this host' ],
    [ undef, 'whirlpool($p)',     undef, 'no whirlpool here' ],
    # sha224($p) and utf16($p) were refusals here until 2026-09-04, and both
    # reasons are recorded above where they are now computed. The utf16 one
    # was wrong when it was written -- hx HAS utf16le, and RosettaHx's
    # %MOD_HX already mapped it onto this repository's utf16 -- so the
    # fixture and RosettaHx were asserting opposite things about the same
    # token. Neither was ever a dropped token; both are computed exactly.
    # --- sha224 and sha384, added 2026-09-04 ------------------------
    # hx has NO sha224 and NO sha384: its function table is md5, md4, sha1,
    # sha256, sha512 and nothing else (hx_func.c, measured 2026-09-04). So
    # the hx column is undef here and --oracle skips these, which is why
    # the expected values are the corpus's OWN vectors -- raw-sha224 and
    # raw-sha384 both carry the 'rosetta' digest, each already proven by
    # john's dynamic compiler. Digest::SHA reproducing them is a second,
    # independent implementation agreeing, not a transcription.
    [ undef, 'sha224($p)',
      '223b5c5625a10b045533f2f731dc47f572b3070feaf0838dffba0dbb',
      "sha224 (raw-sha224's own vector; hx cannot be asked)" ],
    [ undef, 'sha384($p)',
      'c91ac188daac08cf79159835683e3f907c97b25652e01c9c779874589da77e071'
    . '9bfc0216bba661205d1384536288343',
      "sha384 (raw-sha384's own vector; hx cannot be asked)" ],
    [ undef, 'hex(sha384_raw($p))',
      'c91ac188daac08cf79159835683e3f907c97b25652e01c9c779874589da77e071'
    . '9bfc0216bba661205d1384536288343',
      'the _raw flavour of a hash hx does not have' ],
    [ undef, 'sha224(sha224_raw($p))',
      '1886a854d9f3088e6f947e7aa512d3d02e4048b7998b2c89f0f9b4c8',
      'sha224 nested over its own raw output' ],

    # --- the utf16 family -------------------------------------------
    # These DO have an hx form, so --oracle re-measures every one of them
    # against the binary. utf16 is this repository's spelling of hx's
    # utf16le; both are accepted, exactly as _raw is for hx's _bin.
    [ 'hex(utf16le(pass))', 'hex(utf16($p))',
      '72006f0073006500740074006100',
      "utf16 is this repository's spelling of hx's utf16le" ],
    [ 'hex(utf16le(pass))', 'hex(utf16le($p))',
      '72006f0073006500740074006100',
      'the hx spelling is accepted too (PEOPLESOFT carries it)' ],
    [ 'hex(utf16be(pass))', 'hex(utf16be($p))',
      '0072006f00730065007400740061', 'utf16be' ],
    [ 'sha1(utf16le(pass))', 'sha1(utf16($p))',
      '9e6b5d761d32257a81c62b309f159d0c808f6296',
      'the composite the MSSQL and NTLM rows are built on' ],
    # The four that separate a UTF-8 conversion from a byte widening. A
    # blind zero-extension would answer 7200c300a900 to the first and would
    # never drop anything at all in the last three.
    [ 'hex(utf16le(pass))', 'hex(utf16($p))', '7200e900',
      'U+00E9 is ONE unit: utf16 converts UTF-8, it does not widen bytes',
      "r\xc3\xa9" ],
    [ 'hex(utf16le(pass))', 'hex(utf16($p))', '3dd800de',
      'above the BMP, one code point becomes a surrogate PAIR',
      "\xf0\x9f\x98\x80" ],
    [ 'hex(utf16le(pass))', 'hex(utf16($p))', '41004200',
      'an invalid byte is DROPPED (iconv //IGNORE), not replaced',
      "A\xffB" ],
    [ 'hex(utf16le(pass))', 'hex(utf16($p))', '41004200',
      'the drop is the maximal subpart: f0 9f both go, the 41 survives',
      "\xf0\x9fAB" ],
    [ 'hex(utf16le(pass))', 'hex(utf16($p))', '',
      'a UTF-8-encoded surrogate is not valid UTF-8 and vanishes whole',
      "\xed\xa0\x80" ],

    [ undef, 'md5(cap($p,1,2))',  undef, 'cap takes at most two arguments' ],
    [ undef, 'md5($u)',           undef, 'the userid variable is not modelled' ],
    [ undef, 'md5(pass)',         undef,
      "hx's bare 'pass' is not this repository's notation" ],
    [ undef, 'md5($p) . junk',    undef, 'an unknown trailing token' ],
    [ undef, 'md5($p',            undef, 'an unclosed call' ],
    [ undef, 'md5($p,$s)',        undef, 'md5 does not take two arguments' ],
    [ undef, 'cut(md5($p))',      undef, 'cut needs at least a start' ],
    [ undef, 'pad($p)',           undef, 'pad needs a width' ],
    [ undef, 'md5($c1.$p)',       undef, 'constants are not modelled here' ],
    [ undef, 'md5($p.":".$s)',    undef, 'string literals are not modelled' ],
    [ undef, '',                  undef, 'the empty expression' ],
);

my ($pass_n, $fail_n) = (0, 0);
sub check {
    my ($ok, $why, $detail) = @_;
    if ($ok) { $pass_n++; printf "ok   %s\n", $why }
    else     { $fail_n++; printf "FAIL %s\n%s", $why, $detail }
}

for my $c (@CASES) {
    my (undef, $expr, $want, $why, $pw) = @$c;
    $pw = $PASS unless defined $pw;
    my $fn = compile_expression($expr);
    if (!defined $want) {
        check(!defined $fn, $why,
              defined $fn
                ? sprintf("     %s\n     want (refused)\n     got  %s\n",
                          $expr, eval { $fn->($pw, $SALT) } // '(died)')
                : '');
        next;
    }
    unless (defined $fn) {
        check(0, $why, "     $expr\n     want $want\n     got  (refused)\n");
        next;
    }
    my $got = eval { $fn->($pw, $SALT) };
    $got = '(died: ' . ($@ =~ s/\n.*//sr) . ')' unless defined $got;
    check($got eq $want, $why,
          "     $expr\n     want $want\n     got  $got\n");
}

#-----------------------------------------------------------------------
# --oracle: is the FIXTURE still what upstream says? Everything above only
# proves RosettaExpr agrees with a table of strings; this proves the table
# still agrees with mdxfind. Separate on purpose, because CI has no hx.
#-----------------------------------------------------------------------
if ($oracle) {
    my $hx = $ENV{HX} || "$RealBin/../tmp/hx-build/hx";
    unless (-x $hx) {
        print STDERR "- oracle: no hx binary at $hx (build it, or set HX=)\n";
        $fail_n++;
    }
    else {
        my $checked = 0;
        for my $c (@CASES) {
            my ($hxe, undef, $want, $why, $pw) = @$c;
            $pw = $PASS unless defined $pw;
            next unless defined $hxe && defined $want;
            # -p/-s are passed as separate argv entries, so nothing is
            # interpolated by a shell.
            my $pid = open(my $fh, '-|');
            defined $pid or die "fork: $!";
            unless ($pid) {
                open(STDERR, '>', '/dev/null');
                exec($hx, '-p', $pw, '-s', $SALT, $hxe) or exit 127;
            }
            my $got = do { local $/; <$fh> };
            close $fh;
            $got = '' unless defined $got;
            $got =~ s/\n\z//;
            $checked++;
            check($got eq $want, "oracle: $why",
                  "     $hxe\n     fixture $want\n     hx      $got\n");
        }
        printf STDERR "- oracle: %d case(s) re-measured against %s\n",
            $checked, $hx;
    }
}

printf STDERR "- %d passed, %d failed\n", $pass_n, $fail_n;
exit($fail_n ? 1 : 0);
