#!/usr/bin/perl
#-----------------------------------------------------------------------
#
# Name: test-absence.pl
# Description: assert that absence.pl writes 'absent' only where the evidence
#              supports it, and refuses in every case where it does not --
#              for BOTH tools, against synthetic fixtures
# Category: cracking-rosetta test
#
# Project: cracking-rosetta | Phase: 7 - pre-publication readiness
#
#-----------------------------------------------------------------------
# METHODOLOGY AND WHY THIS EXISTS
#
# absence.pl writes a CLAIM into data/algorithms in bulk: tier 'absent' means
# the tool has no identifier for this algorithm. A wrong one is invisible --
# an empty column and a false "does not support this" read the same to a
# human, and the second is worse because it stops anyone looking again. The
# 415 bare hashcat absences this tool exists to re-earn are what that looks
# like after a few years.
#
# Two rules for deciding which vectors a sweep actually searched were tried
# during development and BOTH were measurably wrong: "hex and at least 16
# characters" over-predicted against the binary's own count, and "hex whose
# length matches a digest length in the chunk" agreed on one chunk out of
# fifty-one. That is why this file exists. The third approach -- a shape is
# searched only where the sweep reported a hit on some vector of that shape --
# is not obviously right either, and these assertions are what stop it
# drifting back into a rule somebody reasoned out.
#
# The table runs against BOTH tools, because the decision core is shared and
# only the evidence reader differs: mdxfind leaves raw chunk output, hashcat
# leaves one potfile per mode. A refactor that broke one reader while leaving
# the other working is exactly the failure a single-tool test would miss.
#
# The refusals are the assertions that matter. A missed absence costs coverage
# and is visible in the run report; a false one is a false claim in a
# published file.
#
# Fixtures are synthetic and under the project's own tmp/. Nothing here reads
# or writes the real data/algorithms, data/tools or discovery work dirs.
#
# USAGE
#   perl -Itools/lib tools/test-absence.pl
#   Exit 0 all assertions passed, 1 one or more failed, 2 usage.
#
# DEPENDENCIES
#   perl, YAML::XS, tools/absence.pl
#
#-----------------------------------------------------------------------
# Generated by Claude Opus 5 on 2026-09-03

use strict;
use warnings;

use File::Path qw(make_path remove_tree);
use FindBin qw($RealBin);
use YAML::XS ();

my $PROG = 'test-absence.pl';
my $ROOT = "$RealBin/..";

if (@ARGV && $ARGV[0] =~ /^(-h|--help)$/) {
    print <<"USAGE";
Usage: $PROG

   Runs the assertion table against synthetic fixtures under tmp/, for both
   tools. Takes no arguments. Exit 0 all passed, 1 one or more failed, 2 usage.
USAGE
    exit 0;
}
if (@ARGV) { print STDERR "$PROG: takes no arguments\n"; exit 2 }

# Absolute, because the working directory is not this repository's by the time
# a session gets here and a relative tmp/ lands somewhere nobody expects.
my $DIR = "$ROOT/tmp/absence-test";

# A 32-hex shape with a control, and a 40-hex shape without one.
my $CTRL = 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa';
my $TGT  = 'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb';
my $LONG = 'cccccccccccccccccccccccccccccccccccccccc';
my $BLOB = '$container$1$deadbeef$cafebabe';
my $PASS = 'password123';

sub spit {
    my ($path, $text) = @_;
    my ($dir) = $path =~ m{^(.*)/[^/]+$};
    make_path($dir) if $dir && !-d $dir;
    open my $fh, '>', $path or die "$PROG: cannot write $path: $!\n";
    print {$fh} $text or die "$PROG: write failed: $!\n";
    close $fh or die "$PROG: close failed: $!\n";
    return;
}

# The two inventories. Each carries one identifier that shares a normalised
# name with an entry below, so the name veto has something to fire on.
sub write_inventories {
    spit("$DIR/tools/mdxfind.yaml", <<"END_INV");
tool: "mdxfind"
version: "RCS 9.999 (2026/09/03)"
count: 2
types:
  - index: "e1"
    index_num: 1
    name: "MD5"
    flags: ["f"]
    example_vector: "$CTRL:$PASS"
  - index: "e2"
    index_num: 2
    name: "WIDGETHASH"
    flags: ["f"]
    example_vector: "$LONG:$PASS"
END_INV
    spit("$DIR/tools/hashcat.yaml", <<'END_HC');
tool: "hashcat"
version: "v9.9.9-test"
count: 2
modes:
  - mode: 1
    name: "MD5"
    password_len_min: 0
    password_len_max: 256
  - mode: 2
    name: "WIDGETHASH"
    password_len_min: 0
    password_len_max: 256
END_HC
    return;
}

# One control and five targets, one per verdict class. The tool block is
# written for whichever tool is under test, so the same entries serve both.
sub write_entries {
    my ($tool) = @_;
    remove_tree("$DIR/algorithms") if -d "$DIR/algorithms";
    make_path("$DIR/algorithms");

    my $ids = $tool eq 'mdxfind' ? qq(    types: ["MD5"]\n) : qq(    modes: [1]\n);
    spit("$DIR/algorithms/ctrl.yaml", <<"END_E");
id: "ctrl"
name: "control entry"
tools:
  $tool:
$ids    verified: "vector"
vectors:
  - hash: "$CTRL"
    pass: "$PASS"
END_E

    spit("$DIR/algorithms/decidable.yaml", <<"END_E");
id: "decidable"
name: "some product credential"
vectors:
  - hash: "$TGT"
    pass: "$PASS"
END_E

    spit("$DIR/algorithms/uncontrolled.yaml", <<"END_E");
id: "uncontrolled"
name: "another product credential"
vectors:
  - hash: "$LONG"
    pass: "$PASS"
END_E

    spit("$DIR/algorithms/blob.yaml", <<"END_E");
id: "blob"
name: "a container format"
vectors:
  - hash: "$BLOB"
    pass: "$PASS"
END_E

    spit("$DIR/algorithms/named.yaml", <<"END_E");
id: "widget-hash"
name: "Widget-Hash"
vectors:
  - hash: "$TGT"
    pass: "$PASS"
END_E

    spit("$DIR/algorithms/novec.yaml", <<'END_E');
id: "novec"
name: "no vector here"
END_E

    # A bare verdict: 'absent' with no date, version or note. The sweep agrees
    # with it, so --reearn must replace it with the same verdict plus the
    # evidence.
    spit("$DIR/algorithms/bare.yaml", <<"END_E");
id: "bare"
name: "an unevidenced claim"
tools:
  $tool:
    verified: "absent"
vectors:
  - hash: "$TGT"
    pass: "$PASS"
END_E

    # A bare verdict the evidence CONTRADICTS: the sweep cracked this very
    # vector, so 'absent' is wrong -- and a machine still may not turn it into
    # a mapping.
    spit("$DIR/algorithms/barewrong.yaml", <<"END_E");
id: "barewrong"
name: "a contradicted claim"
tools:
  $tool:
    verified: "absent"
vectors:
  - hash: "$CTRL"
    pass: "$PASS"
END_E

    # An absence somebody DID check. Not this tool's to revisit, with or
    # without --reearn.
    spit("$DIR/algorithms/evidenced.yaml", <<"END_E");
id: "evidenced"
name: "a checked claim"
tools:
  $tool:
    verified: "absent"
    verified_at: "2026-01-01"
    verified_with: "somebody"
    note: "checked by hand"
vectors:
  - hash: "$TGT"
    pass: "$PASS"
END_E

    spit("$DIR/algorithms/dead.yaml", <<'END_E');
id: "dead"
name: "dead"
status: "merged"
merged_into: "ctrl"
END_E
    return;
}

# A synthetic work directory in whichever layout the tool under test reads.
#   full    => cover both identifiers (default), else only the first
#   control => report the control vector (default), else report nothing
sub write_evidence {
    my ($tool, %opt) = @_;
    my $full    = exists $opt{full}    ? $opt{full}    : 1;
    my $control = exists $opt{control} ? $opt{control} : 1;

    remove_tree("$DIR/evidence") if -d "$DIR/evidence";
    if ($tool eq 'mdxfind') {
        make_path("$DIR/evidence/out");
        my $line = $control ? "MD5x01 $CTRL:$PASS\n" : '';
        spit("$DIR/evidence/out/" . ($full ? 'e1-e2.txt' : 'e1-e1.txt'),
             "SSSE3 hex conversion enabled\n$line");
    }
    else {
        make_path("$DIR/evidence/pot");
        # An EMPTY potfile is the record that the mode ran and cracked
        # nothing; that distinction is the whole coverage check.
        spit("$DIR/evidence/pot/1.pot", $control ? "$CTRL:$PASS\n" : '');
        spit("$DIR/evidence/pot/2.pot", '') if $full;
    }
    return;
}

sub run_tool {
    my ($tool, @args) = @_;
    my $out = "$DIR/run.out";
    my $rc = system("perl -I$ROOT/tools/lib $ROOT/tools/absence.pl "
                  . "--tool $tool --from '$DIR/evidence' "
                  . "--algorithms '$DIR/algorithms' "
                  . "--inventory '$DIR/tools/$tool.yaml' "
                  . join(' ', @args) . " >'$out' 2>&1");
    my $text = '';
    if (open my $fh, '<', $out) { local $/; $text = <$fh> // ''; close $fh }
    return ($rc >> 8, $text);
}

sub verdict {
    my ($tool, $file) = @_;
    my $e = eval { YAML::XS::LoadFile("$DIR/algorithms/$file.yaml") }
        or return '(unreadable)';
    return $e->{tools}{$tool}{verified} // '';
}

# evidence($tool, $file) - 'full' when the verdict carries a date, a version
# and a note; 'none' when it carries none of them; 'partial' otherwise. That
# three-way answer is what distinguishes a bare claim from an earned one.
sub evidence {
    my ($tool, $file) = @_;
    my $e = eval { YAML::XS::LoadFile("$DIR/algorithms/$file.yaml") }
        or return '(unreadable)';
    my $b = $e->{tools}{$tool} || {};
    my $n = grep { defined $b->{$_} } qw(verified_at verified_with note);
    return $n == 3 ? 'full' : $n == 0 ? 'none' : 'partial';
}

my ($pass, $fail) = (0, 0);

# check($ok, $label, $detail) - one assertion.
#
# Every caller forces $ok to a scalar: a bare "$out =~ /x/" in an argument
# list is evaluated in LIST context, and a failed match returns the empty list
# rather than false, which shifts the label into $ok and turns a failing
# assertion into a passing one with no name.
sub check {
    my ($ok, $label, $detail) = @_;
    if ($ok) { $pass++; print "ok   $label\n" }
    else     { $fail++; print "FAIL $label\n"; print "     $detail\n" if $detail }
    return;
}

#-----------------------------------------------------------------------

remove_tree($DIR) if -d $DIR;
make_path("$DIR/tools");
write_inventories();

for my $tool (qw(mdxfind hashcat)) {
    print "\n# $tool\n";

    # 1. A partial sweep must refuse, whatever else is true.
    write_entries($tool);
    write_evidence($tool, full => 0);
    {
        my ($rc, $out) = run_tool($tool, '--apply');
        check(verdict($tool, 'decidable') eq '',
              "$tool partial sweep: writes nothing even with --apply",
              "verdict is '" . verdict($tool, 'decidable') . "'");
        check(!!($out =~ /^-\s+absent \(swept, nothing\)\s+0$/m),
              "$tool partial sweep: nothing reaches absent");
        # Every target with a vector is held back, not only the one this
        # fixture is built around: the coverage objection is checked before
        # the control test, and it applies to all of them equally.
        check(!!($out =~ /^-\s+partial \(identifier unrun\)\s+[1-9]\d*$/m),
              "$tool partial sweep: targets are held back as partial");
        check($rc == 0, "$tool partial sweep: still exits 0, it is a report");
    }

    # 2. A sweep with no control is vacuous.
    write_entries($tool);
    write_evidence($tool, control => 0);
    {
        my ($rc, $out) = run_tool($tool, '--apply');
        check($rc == 1, "$tool no control: exits 1");
        check(!!($out =~ /no shape has a control/), "$tool no control: explains why");
        check(verdict($tool, 'decidable') eq '', "$tool no control: writes nothing");
    }

    # 3. The complete, controlled run. The only shape that may write.
    write_entries($tool);
    write_evidence($tool);
    {
        my ($rc, $out) = run_tool($tool);
        check($rc == 0, "$tool dry run: exits 0");
        check(!!($out =~ /nothing written/), "$tool dry run: says so");
        check(verdict($tool, 'decidable') eq '',
              "$tool dry run: writes nothing without --apply");

        ($rc, $out) = run_tool($tool, '--apply');
        check($rc == 0, "$tool apply: exits 0");
        check(verdict($tool, 'decidable') eq 'absent',
              "$tool apply: writes absent where a control proves the shape was searched",
              "verdict is '" . verdict($tool, 'decidable') . "'");
        check(verdict($tool, 'uncontrolled') eq '',
              "$tool apply: writes NOTHING for a shape with no control",
              "verdict is '" . verdict($tool, 'uncontrolled') . "'");
        check(verdict($tool, 'blob') eq '',
              "$tool apply: writes NOTHING for a shape the loader never takes",
              "verdict is '" . verdict($tool, 'blob') . "'");
        check(verdict($tool, 'named') eq '',
              "$tool apply: a name match is a candidate mapping, never an absence",
              "verdict is '" . verdict($tool, 'named') . "'");
        check(verdict($tool, 'novec') eq '',
              "$tool apply: writes NOTHING for an entry with no vector");
        check(!!($out =~ /^-\s+candidate \(name match\)\s+1$/m),
              "$tool apply: the name match is reported as a candidate");
        check(verdict($tool, 'ctrl') eq 'vector',
              "$tool apply: an entry that already names an identifier is left alone");
        check(!!($out !~ /\bdead\b/), "$tool apply: a tombstone is never a target");
    }

    # 4. Idempotence: a verdict is never overwritten.
    {
        my $before = verdict($tool, 'decidable');
        my ($rc, $out) = run_tool($tool, '--apply');
        check($rc == 0 && verdict($tool, 'decidable') eq $before,
              "$tool second apply: an existing verdict is never rewritten");
        check(!!($out =~ /^-\s+absent \(swept, nothing\)\s+0$/m),
              "$tool second apply: the decided entry is no longer a target");
    }

    # 4b. An identifier the sweep could not finish is not a tested one, and
    #     the evidence on disk cannot say so: the discovery tools write a
    #     potfile or a chunk file for a killed run too, so --resume can tell
    #     "tried" from "not tried". Only the list distinguishes them.
    write_entries($tool);
    write_evidence($tool);
    {
        my $first = $tool eq 'mdxfind' ? 1 : 1;
        spit("$DIR/evidence/timeouts", "$first\n");
        my ($rc, $out) = run_tool($tool, '--apply');
        check(verdict($tool, 'decidable') eq '',
              "$tool timeout: an unfinished identifier blocks the absence",
              "verdict is '" . verdict($tool, 'decidable') . "'");
        check(!!($out =~ /treated as never run/),
              "$tool timeout: the run says it is honouring the list");
        unlink "$DIR/evidence/timeouts";
    }

    # 5. --reearn. A bare verdict carries no date, version or note; replacing
    #    it can only ever add evidence to the same verdict.
    write_entries($tool);
    write_evidence($tool);
    {
        my ($rc, $out) = run_tool($tool, '--apply');
        check(evidence($tool, 'bare') eq 'none',
              "$tool without --reearn: a bare verdict is not a target");

        ($rc, $out) = run_tool($tool, '--reearn', '--apply');
        check($rc == 0, "$tool reearn: exits 0");
        check(verdict($tool, 'bare') eq 'absent',
              "$tool reearn: the verdict stays absent");
        check(evidence($tool, 'bare') eq 'full',
              "$tool reearn: it gains a date, a version and a note",
              'evidence is ' . evidence($tool, 'bare'));

        check(verdict($tool, 'barewrong') eq 'absent'
           && evidence($tool, 'barewrong') eq 'none',
              "$tool reearn: a CONTRADICTED bare claim is left exactly as it was",
              'evidence is ' . evidence($tool, 'barewrong'));
        check(!!($out =~ /bare 'absent' claim\(s\) the evidence CONTRADICTS/),
              "$tool reearn: the contradiction is reported");

        check(evidence($tool, 'evidenced') eq 'full'
           && !!(YAML::XS::LoadFile("$DIR/algorithms/evidenced.yaml")
                    ->{tools}{$tool}{verified_at} eq '2026-01-01'),
              "$tool reearn: an absence somebody checked is not revisited");
    }
}

# 5. Usage. No --tool is not a run with a default; it is a usage error.
{
    my $rc = system("perl -I$ROOT/tools/lib $ROOT/tools/absence.pl "
                  . ">/dev/null 2>&1") >> 8;
    check($rc == 2, 'no arguments: exits 2 with usage');
    $rc = system("perl -I$ROOT/tools/lib $ROOT/tools/absence.pl --tool john "
                  . ">/dev/null 2>&1") >> 8;
    check($rc == 2, 'an unsupported tool: exits 2 rather than guessing');
}

printf STDERR "- %d passed, %d failed\n", $pass, $fail;
remove_tree($DIR) unless $fail;
exit($fail ? 1 : 0);
