#!/usr/bin/perl
#-----------------------------------------------------------------------
#
# Name: test-hashpipe-c.pl
# Description: assert what `hashpipe -c` actually does with an iteration
#              label, so the day upstream changes it we are told
#
#-----------------------------------------------------------------------
# METHODOLOGY AND WHY THIS EXISTS
#
# hashpipe v1.190 added -c: verify each line against its own leading
# TYPE[xNN] label, no detection and no fallback. That is a per-line TYPE PIN
# and it is the equivalent of `mdxfind -h '^TYPE$'`, which makes hashpipe a
# pinnable third oracle instead of a suggester.
#
# v1.190 had a hole in it. A pair that matched at ONE iteration was accepted
# whatever depth the label asked for, and re-emitted as x01. Reported and
# CONFIRMED by upstream on 2026-09-04. This file asserted that hole as it
# stood, on the rule that a test which passes either way is decoration.
#
# v1.191 FIXED IT PER LINE, and this file is why we found out on the day
# rather than by remembering to re-check: the four assertions of the hole
# failed, and their failure text said what to do. That is the whole design.
#
# THE HOLE MOVED INTO THE BATCH IN 1.191, AND 1.192 CLOSED THAT TOO. On
# 1.191 a line's plaintext could still claim ANOTHER line's digest at a
# depth that line did not ask for, when the two were the same hash family
# and the other line's own check succeeded:
#
#     MD5x02 <md5^2> + MD5x03 <md5^1>   ->  BOTH VERIFIED, and the md5^1
#                                           line came back labeled MD5x01
#
# That assertion was written as it stood, so 1.192 broke it and said so.
# Measured on 1.192, the same batch verifies the x02 line and REFUSES the
# x03 line.
#
# THE RISK IS NOW THE OPPOSITE ONE, and it is what the controls below are
# for. A -c that refused more than it should would make the old leak case
# pass just as well as a correct fix does, and nothing here would notice.
# So there are positive controls at BATCH scope: correctly-labeled
# multi-line batches at MIXED depths, which must still verify every line.
# Without them "the leak is gone" and "the batch path is broken" are the
# same measurement.
#
# ONE CONSEQUENCE FOR ANY CALLER SURVIVES ALL OF IT:
#
#   - read the EMITTED suffix, never the exit status. The emitted label is
#     the depth that actually matched, and that is what makes a wrong one
#     visible. It cost nothing when the tool was right and caught it twice
#     when it was not.
#
# Streams still have to be read apart -- see run_lines -- and in a batch the
# output lines still do not correspond one-to-one with the input lines,
# since refusals go to stderr. Match on the emitted HASH, not on position.
#
# WHY IT IS NOT IN CI
#
# validate.yml deliberately never runs a cracker -- tier `vector` must not be
# reachable by anything a pull request can influence -- and a hosted runner
# has no hashpipe. So this skips cleanly when the binary is absent, and the
# skip is stated rather than silent: an absent binary must not read as a pass.
#
# USAGE
#   perl tools/test-hashpipe-c.pl            run the assertions
#   perl tools/test-hashpipe-c.pl --verbose  print the whole matrix
#   HASHPIPE=/path/to/hashpipe  overrides where the binary is looked for.
#   Exit 0 all assertions passed (or skipped), 1 one or more failed.
#
# DEPENDENCIES
#   perl, tools/lib/RosettaTools.pm, a hashpipe binary with -c
#
#-----------------------------------------------------------------------
# Generated by Claude Opus 5 on 2026-09-04

use strict;
use warnings;
use FindBin qw($RealBin);
use lib "$RealBin/lib";
use RosettaTools qw(tool_path);
use Digest::MD5 qw(md5_hex);
use Digest::SHA qw(sha1_hex);
use File::Temp qw(tempdir);

my $PROG = 'test-hashpipe-c.pl';
if (grep { /^(?:-h|--help)$/ } @ARGV) {
    print <<"USAGE";

Usage: $PROG [--verbose]

   -v, --verbose     print the whole label-against-truth matrix
   -h, --help        this help

   Asserts what `hashpipe -c` does with an iteration label. Since v1.192 it
   is strict both per line and per batch: it verifies at the labeled depth
   and refuses every other, and one line's plaintext can no longer claim
   another line's digest. Both halves are asserted, and so is the opposite
   failure -- a correctly-labeled multi-line batch must still verify every
   line, or "the leak is gone" and "the batch path is broken" would be the
   same reading.

   Needs a hashpipe binary (\$HASHPIPE, else the resolver default). Skips
   loudly when there is none, because a skip must not read as a pass. Not
   run in CI: validate.yml deliberately runs no cracker.

   Exit 0 all assertions passed or skipped, 1 one or more failed.
USAGE
    exit 0;
}

my $verbose = grep { /^-v$|^--verbose$/ } @ARGV;
my $HP   = tool_path('hashpipe');
my $PASS = 'password';
my $MAX  = 5;

unless (-x $HP || `command -v $HP 2>/dev/null`) {
    print STDERR "- SKIPPED: no hashpipe at $HP (set HASHPIPE= to point at one)\n";
    print STDERR "-   This is a skip, NOT a pass: nothing about -c was checked.\n";
    exit 0;
}

my $TMP = tempdir(CLEANUP => 1);

# md5^n($PASS), computed here rather than transcribed.
my @digest;
{
    my $h = $PASS;
    for my $n (1 .. $MAX) { $h = md5_hex($h); $digest[$n] = $h }
}
my $SHA1 = sha1_hex($PASS);

# run_lines(@lines) - feed a whole batch to one `hashpipe -c` and say what
# came back. Streams are read SEPARATELY and that is not fastidiousness: a
# rejected line is echoed to stderr VERBATIM, and where the label already
# matches what the tool would emit, the accepted and rejected forms are
# byte-identical. Merge the streams and the two become indistinguishable --
# which is exactly how a one-liner in a terminal reads a refusal as a pass.
sub run_lines {
    my (@lines) = @_;
    my ($o, $e) = ("$TMP/o", "$TMP/e");
    open my $in, '|-', "'$HP' -c > '$o' 2> '$e'" or die "cannot run $HP: $!\n";
    print {$in} "$_\n" for @lines;
    close $in;
    my $status = $?;
    my $out = do { local (@ARGV, $/) = ($o); <> } // '';
    my $err = do { local (@ARGV, $/) = ($e); <> } // '';
    my @out = grep { length } split /\n/, $out;
    my @err = grep { length } split /\n/, $err;
    return {
        out    => \@out,                          # verified, as emitted
        err    => \@err,                          # refused, echoed verbatim
        labels => [ map { (split / /, $_)[0] } @out ],
        exit   => ($status >> 8),
    };
}

# run_c($line) - ONE line, one process. The only shape a caller should use.
sub run_c {
    my ($line) = @_;
    my $r = run_lines($line);
    return {
        verified => (scalar @{ $r->{out} } ? 1 : 0),
        label    => $r->{labels}[0] // '',
        stderr   => join("\n", @{ $r->{err} }),
        exit     => $r->{exit},
    };
}

my ($pass_n, $fail_n) = (0, 0);
sub check {
    my ($ok, $why, $detail) = @_;
    if ($ok) { $pass_n++; printf "ok   %s\n", $why }
    else     { $fail_n++; printf "FAIL %s\n%s", $why, ($detail // '') }
}

#-----------------------------------------------------------------------
# The per-line matrix: label depth against true depth. STRICT since v1.191
# -- the diagonal verifies and re-emits its own label, everything else is
# refused. $leak_seen counts the v1.190 hole, and is asserted to be zero.
#-----------------------------------------------------------------------
my $leak_seen = 0;
printf "%-8s%s\n", 'label', join '', map { sprintf '%-11s', "md5^$_" } 1 .. $MAX
    if $verbose;
for my $label (1 .. $MAX) {
    my @row;
    for my $true (1 .. $MAX) {
        my $r = run_c(sprintf 'MD5x%02d %s:%s', $label, $digest[$true], $PASS);
        push @row, $r->{verified} ? $r->{label} : '.';

        my $why = sprintf 'MD5x%02d against md5^%d: %s', $label, $true,
            $label == $true ? 'verifies' : 'refused';
        if ($label == $true) {
            check($r->{verified} && $r->{label} eq sprintf('MD5x%02d', $label),
                  "$why as MD5x" . sprintf('%02d', $label),
                  sprintf("     got verified=%d label=%s\n",
                          $r->{verified}, $r->{label}));
        }
        else {
            # $true == 1 under a deeper label is the v1.190 hole. It is now
            # one off-diagonal cell like any other, but still counted, so
            # the summary line says in one number whether it came back.
            $leak_seen++ if $true == 1 && $r->{verified};
            check(!$r->{verified}, $why,
                  sprintf("     wrongly verified as %s\n", $r->{label}));
        }
    }
    printf "MD5x%02d  %s\n", $label, join '', map { sprintf '%-11s', $_ } @row
        if $verbose;
}

#-----------------------------------------------------------------------
# The BATCH, where the hole moved. Asserted as it stands on 1.191, with the
# three controls that say what it is NOT -- because without them "two lines
# verified" is equally consistent with -c simply being lax, and a claim that
# fits both cases has not measured anything.
#-----------------------------------------------------------------------
{
    # Control 1: the same wrong label, alone. This is the v1.190 hole, and
    # it is what 1.191 fixed.
    my $r = run_c("MD5x03 $digest[1]:$PASS");
    check(!$r->{verified},
          'batch control: MD5x03 on md5^1 ALONE is refused (the v1.190 fix)',
          sprintf("     verified as %s -- the v1.190 hole is BACK\n", $r->{label}));

    # Control 2: two lines, neither of which can verify. Refusal is not
    # about being alone.
    $r = run_lines("MD5x03 $digest[1]:$PASS", "MD5x05 $digest[1]:$PASS");
    check(@{ $r->{out} } == 0 && @{ $r->{err} } == 2,
          'batch control: two lines that cannot verify are both refused',
          sprintf("     out=%d err=%d\n", scalar @{ $r->{out} }, scalar @{ $r->{err} }));

    # Control 3: a line that DOES verify, but in another hash family. The
    # leak does not cross families, so this is not "any success unlocks
    # everything".
    $r = run_lines("SHA1x01 $SHA1:$PASS", "MD5x03 $digest[1]:$PASS");
    check(@{ $r->{out} } == 1 && $r->{labels}[0] eq 'SHA1x01'
              && @{ $r->{err} } == 1 && $r->{err}[0] =~ /^MD5x03 /,
          'batch control: a verifying SHA1 line does not unlock an MD5 line',
          sprintf("     out=[%s] err=[%s]\n",
                  join('|', @{ $r->{out} }), join('|', @{ $r->{err} })));

    # THE CASE THAT LEAKED ON 1.190 AND 1.191. A verifying MD5 line in the
    # same batch, on a DIFFERENT digest, used to let the wrongly-labeled
    # line through as well, emitted at a depth no line asked for. Closed in
    # 1.192: the x02 line verifies and the x03 line is refused.
    $r = run_lines("MD5x02 $digest[2]:$PASS", "MD5x03 $digest[1]:$PASS");
    my $leaked = (grep { /^MD5x01 / } @{ $r->{out} }) ? 1 : 0;
    check(!$leaked && @{ $r->{out} } == 1
              && $r->{labels}[0] eq 'MD5x02' && @{ $r->{err} } == 1,
          'BATCH: a wrongly labeled line is refused beside a verifying one '
        . 'of the same family',
          "     The 1.190/1.191 leak is BACK. Re-measure, restore the batch\n"
        . "     clause in CLAUDE.md's iteration-suffix pitfall, and feed -c\n"
        . "     one line per invocation until it is fixed again.\n"
        . sprintf("     out=[%s] err=[%s]\n",
                  join('|', @{ $r->{out} }), join('|', @{ $r->{err} })));

    # AND THE OPPOSITE FAILURE, which the case above cannot see. A -c that
    # refused too much would satisfy it exactly as a correct fix does, so a
    # correctly-labeled batch must still verify EVERY line -- including at
    # mixed depths, which is where a naive per-batch depth check would break.
    for my $pair ([2, 1], [5, 3], [1, 4]) {
        my ($a, $b) = @$pair;
        $r = run_lines(sprintf('MD5x%02d %s:%s', $a, $digest[$a], $PASS),
                       sprintf('MD5x%02d %s:%s', $b, $digest[$b], $PASS));
        my %got = map { $_ => 1 } @{ $r->{labels} };
        check(@{ $r->{out} } == 2 && @{ $r->{err} } == 0
                  && $got{ sprintf('MD5x%02d', $a) }
                  && $got{ sprintf('MD5x%02d', $b) },
              sprintf('BATCH control: x%02d and x%02d together, each correctly '
                    . 'labeled, both verify', $a, $b),
              sprintf("     out=[%s] err=[%s]\n",
                      join('|', @{ $r->{out} }), join('|', @{ $r->{err} })));
    }
}

#-----------------------------------------------------------------------
# The parts that are strict, so a regression there is caught too.
#-----------------------------------------------------------------------
my $r = run_c("NTLM $digest[1]:$PASS");
check(!$r->{verified}, 'a wrong type of the same width is refused',
      sprintf("     wrongly verified as %s\n", $r->{label}));

$r = run_c("MD5x01 $digest[1]:wrongpw");
check(!$r->{verified}, 'a wrong plaintext under the right type is refused',
      sprintf("     wrongly verified as %s\n", $r->{label}));

$r = run_c("NOSUCHTYPE $digest[1]:$PASS");
check(!$r->{verified} && $r->{exit} == 2 && $r->{stderr} =~ /INVALID LABEL/,
      'an unknown label is fatal: INVALID LABEL, exit 2',
      sprintf("     exit=%d stderr=%s\n", $r->{exit}, $r->{stderr}));

$r = run_c("$digest[1]:$PASS");
check(!$r->{verified} && $r->{exit} == 2,
      'a line with no label at all is fatal too',
      sprintf("     exit=%d stderr=%s\n", $r->{exit}, $r->{stderr}));

# MD5CAP is the type whose two numberings disagree: -c calls this vector
# MD5CAPx02, mdxfind's way, where the DETECT path calls it MD5CAPx01. That
# split is what data/upstream-disagreements.yaml records, and it survived
# 1.191, so it is asserted here rather than only written down.
$r = run_c('MD5CAP bd62daf88a5f6d734e91228e7f2e540a:rosetta');
check($r->{verified} && $r->{label} eq 'MD5CAPx02',
      'a bare label is emitted at the depth that matched: MD5CAP -> MD5CAPx02',
      sprintf("     verified=%d label=%s\n", $r->{verified}, $r->{label}));

printf STDERR "- %d passed, %d failed (hashpipe %s)\n", $pass_n, $fail_n, $HP;
printf STDERR "- the v1.190 per-line depth-1 leak is present in %d of %d "
            . "deeper labels\n", $leak_seen, $MAX - 1;
exit($fail_n ? 1 : 0);
