#!/usr/bin/perl
#-----------------------------------------------------------------------
#
# Name: triage-expressions.pl
# Description: for an expression that does not reproduce its entry's vectors,
#              find out WHY, using john's own test vectors as the control
# Category: cracking-rosetta curator
#
# Project: cracking-rosetta | Phase: 7 - pre-publication readiness
#
#-----------------------------------------------------------------------
# METHODOLOGY AND WHY THIS EXISTS
#
# THE QUESTION THIS ANSWERS
#
# expressions.pl transcribes what john's --list=subformats says a dynamic
# computes, for a dynamic the entry has already proven by round-trip. Some of
# those strings, compiled back with --format=dynamic='EXPR', do not recover
# the entry's own plaintext from the entry's own hash. That was recorded as an
# open question -- which is honest and useless, because "something is wrong
# with one of three things" is not a lead.
#
# THE CONTROL IS JOHN'S OWN TEST VECTORS
#
# john ships test vectors for every format: --list=format-tests prints them.
# Running the transcribed expression against THOSE separates the two
# possibilities that matter, and it is the whole idea here:
#
#   cracks john's own vectors  -> the transcription is right, and it is OUR
#                                 vector that is odd. That is a data question
#                                 with a definite answer.
#   cracks none of them        -> john's compiler and john's named format
#                                 disagree about the string. Nothing in this
#                                 repository can fix that, and no contributor
#                                 should be asked to.
#
# The second case then splits further, and the split is worth making because
# each part is a different sentence to write in the entry:
#
#   * the format has its OWN ciphertext encoding -- ciscoasa's digest is
#     base64, not hex -- so a generic hex expression could never match it,
#     however correct it is as a description;
#   * the digest is shorter than the expression's outer function produces,
#     so the format truncates;
#   * the expression contains a literal ':', which john prints and its own
#     compiler then rejects;
#   * none of the above: a genuine disagreement, worth reporting upstream.
#     The keccak family is here -- dynamic_430's own vector is real
#     Keccak-224, and the compiled keccak_224($p) reproduces neither it nor
#     SHA3-224.
#
# WHAT IT WRITES, AND WHAT IT REFUSES TO
#
# Only expression_proof.note, and only with --apply. Never a tier: this
# explains a failure, it does not turn one into a success. Promotion stays
# derive-expressions.pl's job, which requires an actual round-trip against the
# entry's own vectors.
#
# DEPENDENCIES
#   perl, YAML::XS, tools/lib/RosettaEmit.pm, john
#
#-----------------------------------------------------------------------
# Generated by Claude Opus 5 on 2026-08-30

use strict;
use warnings;

use File::Basename qw(basename);
use FindBin qw($RealBin);
use Getopt::Long qw(GetOptions);
use YAML::XS ();

use lib "$RealBin/lib";
use RosettaEmit qw(emit_entry);
use RosettaTools qw(tool_path tool_env_help);
# An independent implementation of the expression, for the constructions this
# host can compute. It is what turns "john will not reproduce this" into
# either "and neither does the arithmetic, so the string is wrong" or "but the
# arithmetic does, so the string is right and john's compiler is the problem".
use RosettaExpr qw(compile_expression);

my $PROG = basename($0);
my $ROOT = "$RealBin/..";
my $TODAY = do { my @t = localtime; sprintf '%04d-%02d-%02d',
                 $t[5]+1900, $t[4]+1, $t[3] };

sub usage {
    print STDERR <<"END_USAGE";

Usage: $PROG [options]

   --algorithms DIR  curated entries (default: data/algorithms)
   --only ID         just this entry (repeatable)
   --john PATH       john binary (default: @{[tool_env_help('john')]})
   --work DIR        scratch (default: tmp/triage)
   --tests N         test vectors per format to try (default: 6)
   --apply           write the diagnosis into expression_proof.note
   -v, --verbose     per-entry detail
   -h, --help        this help

   Diagnoses every entry whose expression is recorded at a tier below
   'vector', by compiling the expression and running it against the test
   vectors john itself ships for the format it named. Writes only a note, and
   never a tier.

   Exit 0 success, 1 error, 2 usage.

END_USAGE
    return;
}

my ($algdir, $workdir, $john, $apply, $help);
my @only;
my ($verbose, $tests) = (0, 6);
GetOptions(
    'algorithms=s' => \$algdir, 'only=s' => \@only, 'john=s' => \$john,
    'work=s' => \$workdir, 'tests=i' => \$tests, 'apply' => \$apply,
    'v|verbose+' => \$verbose, 'h|help' => \$help,
) or do { usage(); exit 2 };
if ($help) { usage(); exit 0 }
if (!@only && !$apply && !$verbose) { usage(); exit 2 }

$algdir  //= "$ROOT/data/algorithms";
$workdir //= "$ROOT/tmp/triage";
$john = tool_path('john', $john);
mkdir $workdir unless -d $workdir;
my %scope = map { $_ => 1 } @only;
my ($jdir, $jbin) = $john =~ m{^(.*)/([^/]+)$} ? ($1, $2) : ('.', $john);

# Digest width in hex characters, for the truncation test. Only the functions
# that actually appear as the OUTER call of an expression here; an unknown one
# simply means the truncation test is skipped rather than guessed.
my %WIDTH = (
    md5 => 32, md4 => 32, sha1 => 40, sha224 => 56, sha256 => 64,
    sha384 => 96, sha512 => 128, ripemd128 => 32, ripemd160 => 40,
    ripemd256 => 64, ripemd320 => 80, whirlpool => 128, gost => 64,
    tiger => 48, keccak_224 => 56, keccak_256 => 64, keccak_384 => 96,
    keccak_512 => 128, sha3_224 => 56, sha3_256 => 64, sha3_384 => 96,
    sha3_512 => 128, haval128_3 => 32, haval160_3 => 40, haval192_3 => 48,
    haval224_3 => 56, haval256_3 => 64,
);

#-----------------------------------------------------------------------
# john's own test vectors for a format: label, index, ciphertext, plaintext.

sub format_tests {
    my ($fmt) = @_;
    my @out;
    for my $line (`cd \Q$jdir\E && ./\Q$jbin\E --list=format-tests --format=\Q$fmt\E 2>/dev/null`) {
        chomp $line;
        my (undef, undef, $ct, $pw) = split /\t/, $line, 4;
        next unless defined $ct && defined $pw && length $pw;
        # Strip the format's own tag: the ad-hoc compiler is a different
        # format and will not read another one's ciphertext.
        (my $bare = $ct) =~ s/^\$\Q$fmt\E\$//;
        push @out, { bare => $bare, pass => $pw };
        last if @out >= $tests;
    }
    return @out;
}

# try_expression($expr, \@tests) - how many of john's own vectors the compiled
# expression recovers.
sub try_expression {
    my ($expr, $t) = @_;
    return 0 unless @$t;
    (my $safe = $expr) =~ s/[^A-Za-z0-9]/_/g;
    $safe = substr($safe, 0, 60);
    open my $h, '>', "$workdir/$safe.hash" or return 0;
    my $i = 0;
    print {$h} join("\n", map { sprintf("t%d\t%s", $i++, $_->{bare}) } @$t), "\n";
    close $h;
    open my $w, '>', "$workdir/$safe.word" or return 0;
    print {$w} join("\n", map { $_->{pass} } @$t), "\n";
    close $w;
    unlink "$workdir/$safe.pot";
    system(sprintf('cd %s && ./%s --format=dynamic=%s --field-separator-char=tab '
                 . '--wordlist=%s --pot=%s --session=%s %s >/dev/null 2>&1',
        quotemeta($jdir), quotemeta($jbin), quotemeta($expr),
        quotemeta("$workdir/$safe.word"), quotemeta("$workdir/$safe.pot"),
        quotemeta("$workdir/$safe"), quotemeta("$workdir/$safe.hash")));
    my $shown = `cd \Q$jdir\E && ./\Q$jbin\E --show --format=dynamic=\Q$expr\E --field-separator-char=tab --pot=\Q$workdir/$safe.pot\E \Q$workdir/$safe.hash\E 2>/dev/null`;
    my $got = () = $shown =~ /^t\d+\t/mg;
    return $got;
}

#-----------------------------------------------------------------------
# recompute_vectors($fn, $expr, $entry)
#
# Compute the expression over each of the entry's own vectors and report how
# many it reproduces. Returns (reproduced, contradicted, unusable).
#
# The third number is the point of this sub. The comparison used to be
# `lc($h) eq lc($mine)` against the first colon-field of the hash, which is
# right only when that field IS a bare digest. It is not, for any vector held
# in the producing tool's own serialization -- $episerver$*0*RGVm*qNFZ...,
# {SHA}base64, $B$salt$hash -- and it is not for a base64 output either, where
# lower-casing destroys the very distinction being tested. Counting those as
# CONTRADICTED would report a correct expression as wrong, which is precisely
# the failure this whole tool exists to avoid, and it would do it on the
# entries most likely to be right. So they are counted apart and no verdict
# claims anything about them.
#
# A vector is also unusable when the expression needs a salt the vector does
# not carry: computing with the empty string produces a confidently wrong
# digest rather than an error.
sub recompute_vectors {
    my ($fn, $expr, $d) = @_;
    my ($ok, $no, $skip) = (0, 0, 0);
    return ($ok, $no, $skip) unless $fn;
    my $needs_salt = $expr =~ /\$s/;

    for my $v (@{ $d->{vectors} || [] }) {
        my $raw = $v->{hash} // '';
        # The recorded shape is <digest>:<salt> for a salted vector, and the
        # salt: field overrides when the entry states one.
        my ($h, $salt) = split /:/, $raw, 2;
        $salt = $v->{salt} if defined $v->{salt} && length $v->{salt};
        $h = '' unless defined $h;

        # Not a bare digest: hex, or base64 with optional padding. Anything
        # framed by the producing tool ($..$, {SHA}, *) lands here.
        unless ($h =~ /^[0-9a-fA-F]+$/ || $h =~ m{^[A-Za-z0-9+/]+={0,2}$}) {
            $skip++;
            next;
        }
        if ($needs_salt && !(defined $salt && length $salt)) { $skip++; next }

        my $mine = eval { $fn->($v->{pass} // '', defined $salt ? $salt : '') };
        unless (defined $mine) { $skip++; next }

        # Hex is compared without regard to case, because both spellings are
        # the same digest and the catalogs disagree about which to print.
        # Anything else is compared exactly: in base64 the case IS the value.
        my $same = ($h =~ /^[0-9a-fA-F]+$/ && $mine =~ /^[0-9a-fA-F]+$/)
                 ? lc($h) eq lc($mine)
                 : $h eq $mine;
        $same ? $ok++ : $no++;
    }
    return ($ok, $no, $skip);
}

#-----------------------------------------------------------------------
# Walk.

opendir(my $dh, $algdir) or do {
    print STDERR "$PROG: cannot read $algdir: $!\n"; exit 1;
};
my @files = sort grep { /\.yaml$/ } readdir $dh;
closedir $dh;

my $start = time;
my (%verdict_count, $seen, $wrote);

for my $file (@files) {
    my $stem = $file; $stem =~ s/\.yaml$//;
    next if %scope && !$scope{$stem};
    my $path = "$algdir/$file";
    my $d = eval { YAML::XS::LoadFile($path) } or next;
    next unless ref $d eq 'HASH';
    next if ($d->{status} // '') eq 'merged';
    my $expr = $d->{expression} or next;
    my $pf = $d->{expression_proof};
    next unless ref $pf eq 'HASH';
    my $tier = $pf->{verified} // '';
    next unless $tier eq 'upstream' || $tier eq 'asserted';
    $seen++;

    my $fn = compile_expression($expr);

    # EVERY john format this entry names, not just the first.
    #
    # One entry routinely names several formats that are the SAME computation
    # in different SERIALIZATIONS, and an expression can only describe one of
    # them. Measured 2026-09-05 on mysql4-1-mysql5, which names dynamic_1028
    # and mysql-sha1: john's own subformat listing calls dynamic_1028
    # "sha1(sha1_raw($p)) (hash truncated to length 32)", while mysql-sha1
    # stores the same computation as "*" followed by the digest in upper case.
    # The entry's expression, $c1.upper(sha1(sha1_raw($p))),c1=*, describes
    # mysql-sha1 exactly and reproduces none of dynamic_1028's vectors --
    # the leading "*" defeats even the truncation check below. Testing the
    # FIRST label only reported `expression-wrong` about an expression that is
    # right, on an entry whose every vector is also right.
    #
    # The independent recomputation is what selects, not try_expression: john's
    # ad-hoc compiler is handed the hx-style string and rejects wrappers it
    # spells as flavours -- upper(F(x)) is F_UPPERCASED(x) to john -- so $got
    # is 0 for every label here and could not tell them apart. Ranked by
    # vectors REPRODUCED, then by fewest CONTRADICTED, which can only move a
    # verdict from worse to better: a label explaining nothing cannot displace
    # one explaining something.
    my @labels = @{ $d->{tools}{john}{cpu} || [] };
    my ($fmt, $got, $width, $nonhex, $ind_ok, $ind_no, $ind_cut);
    my @t;
    for my $label (@labels) {
        my @tt = format_tests($label) or next;

        # Is this format's own digest plain hex, and how wide?
        my ($w, $nh) = (0, 0);
        for my $x (@tt) {
            my ($digest) = split /\$/, $x->{bare};
            if (defined $digest && $digest =~ /^[0-9a-fA-F]+$/) {
                $w = length $digest if length($digest) > $w;
            }
            else { $nh++ }
        }

        # The independent check: does the expression, computed here, reproduce
        # john's OWN test vectors for this format? This is the difference
        # between a wrong string and a compiler that cannot eat a right one,
        # and no amount of john runs can tell them apart.
        my ($iok, $ino, $icut) = (0, 0, 0);
        if ($fn) {
            for my $x (@tt) {
                my ($digest, $salt) = split /\$/, $x->{bare}, 2;
                next unless defined $digest;
                $salt = '' unless defined $salt;
                my $mine = eval { $fn->($x->{pass}, $salt) };
                next unless defined $mine;
                if (lc($digest) eq lc($mine)) { $iok++; next }
                # A stored digest that is a PREFIX of what the expression
                # computes is not a wrong expression, it is a format that
                # truncates -- and this is proof of it rather than an
                # inference from the width.
                if (length($digest) < length($mine)
                    && lc($digest) eq lc(substr($mine, 0, length $digest))) {
                    $icut++;
                    next;
                }
                $ino++;
            }
        }

        my $better = !defined $fmt
                  || $iok > $ind_ok
                  || ($iok == $ind_ok && $ino < $ind_no);
        next unless $better;
        ($fmt, $width, $nonhex, $ind_ok, $ind_no, $ind_cut)
            = ($label, $w, $nh, $iok, $ino, $icut);
        @t = @tt;
    }
    ($ind_ok, $ind_no, $ind_cut) = (0, 0, 0) unless defined $fmt;
    ($width, $nonhex) = (0, 0) unless defined $fmt;
    $fmt = $labels[0] unless defined $fmt;
    $got = @t ? try_expression($expr, \@t) : 0;

    my ($outer) = $expr =~ /^([A-Za-z0-9_]+)\s*\(/;
    my $expect  = $outer ? $WIDTH{ lc $outer } : undef;

    # And a control at a salt length nothing could object to: if the compiled
    # expression recovers a vector we computed ourselves with a two-character
    # salt, then john's compiler understands the construction and the failure
    # above is about this format's salt, not its meaning.
    my $short_ok = 0;
    if ($fn && !$got && $ind_ok) {
        my $ctrl = eval { $fn->('rosetta', 'ab') };
        $short_ok = try_expression($expr, [ { bare => "$ctrl\$ab", pass => 'rosetta' } ])
            if defined $ctrl;
    }
    my $max_salt = 0;
    for my $x (@t) {
        my (undef, $salt) = split /\$/, $x->{bare}, 2;
        $max_salt = length $salt if defined $salt && length($salt) > $max_salt;
    }

    my ($verdict, $note);
    if (!$fmt) {
        # No john format means john ships no test vectors to use as a control.
        # That is a statement about the CONTROL, not about the expression, and
        # curate.pl stops asking a human on the strength of this verdict -- so
        # do not stop at "cannot check" while our own compiler can still run
        # the thing against the entry's own vectors. RosettaExpr is
        # independent of all three crackers, which is what makes the answer
        # worth having and also what caps it: per CLAUDE.md a recomputation
        # here is corroboration, never tier 'vector', because that requires
        # john's own compiler.
        my ($ours_ok, $ours_no, $ours_skip)
            = recompute_vectors($fn, $expr, $d);

        if (!$fn) {
            $verdict = 'no-john-format';
            $note = 'no john format on this entry, so john ships no control '
                  . 'vectors, and RosettaExpr cannot compile this expression '
                  . 'either -- nothing here can check it';
        }
        elsif (!$ours_ok && !$ours_no && $ours_skip) {
            # The expression compiles and the entry has vectors, but not one
            # of them is a bare digest this can line up against -- they are
            # in the producing tool's own serialization, or the construction
            # needs a salt the vector does not carry. Reserializing them is
            # real work with real coverage behind it (STATE.md, "a vector in
            # a tool's native serialization"), and it is NOT evidence that
            # anything here is wrong.
            $verdict = 'native-serialization';
            $note = sprintf('no john format, and RosettaExpr can compute this '
                  . 'expression but none of the entry\'s %d vector(s) is a '
                  . 'bare digest to compare it against -- each is in a tool\'s '
                  . 'own serialization, or lacks a salt the expression needs. '
                  . 'The expression is unchecked, not contradicted',
                    $ours_skip);
        }
        elsif (!$ours_ok && !$ours_no) {
            $verdict = 'no-john-format';
            $note = 'no john format on this entry, so john ships no control '
                  . 'vectors, and the entry carries no vector of its own to '
                  . 'check the expression against';
        }
        elsif ($ours_ok && !$ours_no) {
            $verdict = 'corroborated';
            $note = "no john format, so john ships no control vectors; but "
                  . "RosettaExpr -- an implementation independent of all three "
                  . "crackers -- computes this expression over the entry's own "
                  . "vector(s) and reproduces $ours_ok of $ours_ok. That is "
                  . 'corroboration, not tier vector, which needs john\'s own '
                  . 'compiler';
        }
        elsif ($ours_ok) {
            $verdict = 'partial';
            $note = "no john format; RosettaExpr reproduces $ours_ok of "
                  . ($ours_ok + $ours_no) . " comparable vector(s), so "
                  . 'the expression is right for some and not others -- which '
                  . 'is what a multi-emit type looks like, and is a question '
                  . 'for a person';
        }
        else {
            $verdict = 'expression-wrong';
            $note = 'no john format, but RosettaExpr -- an implementation '
                  . 'independent of all three crackers -- computes this '
                  . "expression over the entry's own vector(s) and reproduces "
                  . 'none of them. Either the expression or the vector is '
                  . 'wrong';
        }
    }
    elsif (!@t) {
        $verdict = 'no-test-vectors';
        $note = "john ships no test vectors for $fmt, so the expression cannot "
              . 'be checked against anything but this entry';
    }
    elsif ($got == @t) {
        # The expression is right. Now: is OUR vector right too? The
        # independent implementation answers that without john, and the two
        # answers are completely different questions for a contributor -- one
        # is "find out what this vector really is", the other is "john will
        # not eat a vector that is provably correct".
        my ($ours_ok, $ours_no, $ours_skip)
            = recompute_vectors($fn, $expr, $d);

        if ($fn && $ours_ok && !$ours_no) {
            $verdict = 'john-refuses-our-vector';
            $note = sprintf('both the expression and this entry\'s vector are '
                  . 'correct and independently checked: compiled with '
                  . '--format=dynamic the expression recovers all %d of john\'s '
                  . 'own test vectors for %s, and computed here with Digest:: '
                  . 'it reproduces all %d of this entry\'s. john\'s ad-hoc '
                  . 'compiler simply will not crack this particular vector -- '
                  . 'a salt string it mishandles is the known cause',
                    $got, $fmt, $ours_ok);
        }
        elsif ($fn && $ours_no) {
            $verdict = 'vector-anomalous';
            $note = sprintf('the expression is correct -- compiled with '
                  . '--format=dynamic it recovers all %d of john\'s own test '
                  . 'vectors for %s -- and %d of this entry\'s %d vectors are '
                  . 'not of that construction by independent computation. Those '
                  . 'vectors are something else and want identifying',
                    $got, $fmt, $ours_no, $ours_no + $ours_ok);
        }
        else {
            $verdict = 'vector-anomalous';
            $note = "the expression is a correct transcription: compiled with "
                  . "--format=dynamic it recovers all $got of john's own test "
                  . "vectors for $fmt. It is this entry's vector that it does "
                  . "not reproduce, so the vector is the thing to question";
        }
    }
    elsif ($got) {
        $verdict = 'partial';
        $note = sprintf('the expression recovers %d of %d of john\'s own test '
              . 'vectors for %s, so it is right for some inputs and not others '
              . '-- most likely a length or encoding limit', $got, scalar @t, $fmt);
    }
    elsif ($fn && $ind_ok && !$ind_no && $short_ok) {
        $verdict = 'salt-length';
        $note = sprintf('the expression is correct -- computed here with '
              . 'Digest:: it reproduces all %d of john\'s own test vectors for '
              . '%s -- but john\'s ad-hoc compiler will not take it with this '
              . 'format\'s %d-character salt, while the same expression '
              . 'recovers a control vector with a 2-character salt. A limit in '
              . 'the compiled form, not a disagreement about the algorithm',
                $ind_ok, $fmt, $max_salt);
    }
    elsif ($fn && $ind_ok && !$ind_no) {
        $verdict = 'compiler-cannot';
        $note = sprintf('the expression is correct -- computed here with '
              . 'Digest:: it reproduces all %d of john\'s own test vectors for '
              . '%s -- and john\'s ad-hoc compiler still recovers none of '
              . 'them, so the string is right and --format=dynamic cannot '
              . 'execute it', $ind_ok, $fmt);
    }
    elsif ($fn && $ind_cut && !$ind_no) {
        $verdict = 'truncation';
        $note = sprintf('%s truncates: computed here, the expression produces '
              . 'a digest of which the stored %d-character ciphertext is '
              . 'exactly the leading part, on all %d of john\'s own test '
              . 'vectors. The expression describes the computation, not the '
              . 'cut', $fmt, $width, $ind_cut);
    }
    elsif ($fn && $expr =~ /\$s/ && !$max_salt && !$nonhex) {
        # !$nonhex keeps this out of format-encoding's way. Where the
        # ciphertext is not plain hex at all, THAT is the more specific reason
        # the control is unusable and it already has a verdict; this one is for
        # the case format-encoding cannot see -- a ciphertext that is entirely
        # hex and still carries its salt inside the hash string.
        # The control was never applied. A format whose ciphertext carries the
        # salt INSIDE one field -- rather than as a $-separated second field --
        # yields no salt to compute with, and the expression is then evaluated
        # with the empty string, which produces a confidently wrong digest
        # rather than an error. Measured 2026-09-05 on netscaler: Citrix_NS10
        # stores "1" + 8 hex of salt + 40 hex of SHA-1 in a single field, and
        # sha1($s.$p.$c1),c1=\x00 is exactly right -- by hand,
        # sha1("00000000"."password123"."\0") is the digest inside this entry's
        # own vector. Calling that expression-wrong was a verdict about the
        # PARSER, stated as a fact about the algorithm.
        $verdict = 'salt-not-parsed';
        $note = sprintf('the expression needs a salt and %s does not publish '
              . 'one as a separate field -- its test ciphertexts carry the salt '
              . 'inside the hash string -- so the expression was computed with '
              . 'an empty salt and could not match. That is a limit of this '
              . 'check, not evidence about the expression: nothing here has '
              . 'tested it', $fmt);
    }
    elsif ($fn && $ind_no && !$ind_ok && !$nonhex) {
        $verdict = 'expression-wrong';
        $note = sprintf('the expression does not describe %s: computed here '
              . 'with Digest:: it reproduces none of the %d test vectors john '
              . 'ships for that format, so what --list=subformats prints is '
              . 'not the whole construction', $fmt, $ind_no);
    }
    elsif ($expr =~ /:/) {
        $verdict = 'literal-colon';
        $note = "the expression john prints contains a literal ':', which its "
              . 'own dynamic compiler then rejects, so this string cannot be '
              . 'round-tripped as written';
    }
    elsif ($nonhex) {
        $verdict = 'format-encoding';
        $note = "$fmt has its own ciphertext encoding rather than plain hex, "
              . 'so a generic expression cannot be checked against it however '
              . 'correctly it describes the computation';
    }
    elsif ($expect && $width && $width < $expect) {
        $verdict = 'truncation';
        $note = sprintf('%s stores a %d-character digest where %s produces %d, '
              . 'so the format truncates and the expression describes only the '
              . 'part before the cut', $fmt, $width, $outer, $expect);
    }
    else {
        $verdict = 'compiler-disagrees';
        $note = "compiled with --format=dynamic this expression recovers none "
              . "of john's own test vectors for $fmt either, so john's dynamic "
              . 'compiler and its named format disagree about what the string '
              . 'means; this is an upstream question, not a data error here';
    }

    $verdict_count{$verdict}++;
    printf STDERR "-   %-38s %-19s %d/%d %s\n", $stem, $verdict, $got,
        scalar @t, $expr if $verbose;

    next unless $apply;
    # Keep whatever the note already said about provenance, and add the
    # diagnosis after it, so the audit trail is not overwritten by it.
    # The verdict slug is in the note on purpose: it is the only place a
    # later tool can read it from, and curate.pl uses it to stop asking a
    # human about failures that are john's rather than ours. Re-running
    # REPLACES a previous triage rather than appending to it, so the note
    # cannot grow a stack of stale diagnoses.
    my $old = $pf->{note} // '';
    $old =~ s/;?\s*TRIAGE \d{4}-\d{2}-\d{2}(?: \[[a-z-]+\])?:.*$//s;

    # Withdraw a machine-written clause that this very run contradicts.
    #
    # seed-hx.pl writes "Not checkable locally: the construction uses functions
    # RosettaExpr cannot compile, so this rests on upstream's word alone" when
    # it cannot compile the expression. RosettaExpr has been widened twice
    # since -- the $c1 constants most recently -- so a good many of those are
    # now compiled and checked, and the note kept the old sentence beside the
    # new diagnosis. Measured 2026-09-05: 10 entries said the expression could
    # not be checked locally next to a verdict that exists ONLY because it was.
    # mysql4-1-mysql5 said it while triage was reporting that the expression
    # reproduces all 6 of john's own mysql-sha1 vectors.
    #
    # Only where THIS run compiled it ($fn) -- the sentence is still true, and
    # must stay, wherever it still cannot be compiled.
    my $UNCHECKABLE = "Not checkable locally: the construction uses functions "
                    . "RosettaExpr cannot compile, so this rests on upstream's "
                    . "word alone.";
    $old =~ s/\s*\Q$UNCHECKABLE\E//s if $fn;

    $old =~ s/\s+$//;
    $old =~ s/;\s*$//;
    my $new = (length $old ? "$old; " : '') . "TRIAGE $TODAY [$verdict]: $note";
    next if ($pf->{note} // '') eq $new;
    $pf->{note} = $new;
    emit_entry($path, $d);
    $wrote++;
}

printf STDERR "- %d entr(ies) with an unproven expression, in %ds\n", $seen, time - $start;
printf STDERR "-   %-20s %d\n", $_, $verdict_count{$_}
    for sort { $verdict_count{$b} <=> $verdict_count{$a} || $a cmp $b } keys %verdict_count;
printf STDERR "-   %d note(s) written\n", $wrote if $apply;
print  STDERR "- nothing written; re-run with --apply\n" unless $apply;
exit 0;
