#!/usr/bin/perl
#-----------------------------------------------------------------------
# Project: cracking-rosetta | Phase: maintenance | Task: upstream suite refresh
#
# Name:        upstream-refresh.pl
# Description: check the four upstream cracking suites for new versions, pull
#              and rebuild the ones this account owns, regenerate the mechanical
#              inventories, and print the DELTA a curator needs to decide what
#              to re-verify. It never touches data/algorithms/ and never moves a
#              tier -- regenerating an inventory is mechanical, promoting a
#              mapping is judgment, and this tool does only the first.
#
# METHODOLOGY, AND WHY IT STOPS WHERE IT DOES
#
#   This repository tracks each tool's upstream TIP, not its releases (README,
#   "What you can depend on"). That policy has a standing cost: every pull can
#   change what a type computes, and until now the pull-build-extract-diff loop
#   was run by hand across many sessions, from memory, with the traps recorded
#   only as prose in CLAUDE.md and STATE.md. This script is that loop, with the
#   traps encoded as guards rather than remembered:
#
#     - mdxfind MUST be built CPU-only. A plain `make` links OpenCL (the
#       Makefile auto-enables it on /usr/include/CL/cl.h), and the resulting
#       binary claims the GPU by default -- which has corrupted data on this
#       host -- AND appends " [GPU]" to 109 of its -h rows, which
#       extract-mdxfind.pl's four-column regex does not match, so a regenerated
#       inventory would SILENTLY lose 109 types. We build with the exact
#       CPU-only invocation and refuse to extract if the marker is present.
#     - The delta is computed by IDENTIFIER, not by line: added / removed /
#       changed modes, types and formats, each cross-referenced against the
#       proven corpus so "what to re-verify" is a list, not a hunch.
#     - Nothing is written into data/tools/ without --write, and nothing is
#       ever written into data/algorithms/. john is REPORT-ONLY, because its
#       tree is royce-owned and this account cannot build it (corpus Rule Zero).
#
# WHAT "THE DELTA" IS
#
#   For each buildable tool: old version -> new version, the upstream commit
#   subjects in between (the behavior-change signal CLAUDE.md tells you to read
#   after a pull), and the inventory diff expressed as identifiers added,
#   removed and changed. Every removed or changed identifier that a tier-`vector`
#   row names is flagged: those are the mappings whose proof the new build may
#   have invalidated, and they are the work the move creates.
#
# DEPENDENCIES
#   Perl core (Getopt::Long, Cwd, Digest::MD5), Text::CSV, and the repo's own
#   RosettaTools (for tool_version). git with the gh credential helper for the
#   pulls, and make/cc/etc. for the builds -- all present on this host. The
#   extractors in tools/ do the actual inventory generation; this orchestrates.
#
# INVOCATION
#   No arguments prints usage and exits 2. See --help.
#
# Generated by Claude Opus 4.8 on 2026-09-22
#-----------------------------------------------------------------------

use strict;
use warnings;
use Getopt::Long qw(GetOptions);
use Cwd qw(abs_path);
use Digest::MD5 qw(md5_hex);
use File::Temp qw(tempdir);
use File::Path qw(make_path);

# Resolve our own path BEFORE anything can chdir, both for the md5 identity
# line the corpus convention requires and to locate the repo root from it.
# This runs in BEGIN so $root is set before the `use lib` below, which the
# compiler reaches first otherwise.
my ($self, $root, $md5);
BEGIN {
    $self = abs_path($0);
    $root = $self;
    $root =~ s{/tools/[^/]+$}{};         # .../cracking-rosetta/tools/x.pl -> repo
    open my $fh, '<:raw', $self or die "cannot read self ($self): $!\n";
    local $/;                            # slurp: $/ is the input record separator
    $md5 = md5_hex(<$fh>);
}

use lib "$root/tools/lib";
use RosettaTools qw(tool_path tool_version);

#-----------------------------------------------------------------------
# The suite table. One row per tool. Everything tool-specific lives here so the
# body below is the same loop for all of them.
#
#   clone    git working copy this account can pull/build, or undef (john)
#   binary   the built binary the inventory is extracted from
#   build    arrayref of command arrayrefs, run in order (mdxfind needs two)
#   inv      the committed inventory this tool owns
#   extract  how to (re)generate that inventory to a named file -- __BIN__ and
#            __OUT__ are substituted per run
#   idkey    which record field is the stable identifier: mode | index | label
#   kind     the tool's own word for one identifier, for the report
#   xref     which dist/rosetta.csv columns hold this tool's identifiers and its
#            tier, so a delta identifier can be looked up in the proven corpus
#   note     a fixed caveat printed with this tool's section
#-----------------------------------------------------------------------
my $CATALOG = 'vendor/cynosureprime/hashpipe-HASH_TYPES.md';

my %SUITE = (
    hashcat => {
        order   => 1,
        clone   => '/home/claude/src/upstream/hashcat',
        binary  => '/home/claude/src/upstream/hashcat/hashcat',
        build   => [ [qw(make -j)] ],
        inv     => 'data/tools/hashcat.yaml',
        extract => [qw(tools/extract-hashcat.pl --binary __BIN__ --out __OUT__)],
        idkey   => 'mode',
        kind    => 'mode',
        xref    => { id => 'hashcat', state => 'hashcat_state' },
        note    => 'GPU build; a full make can take several minutes.',
    },
    mdxfind => {
        order   => 2,
        clone   => '/home/claude/src/upstream/mdxfind',
        binary  => '/home/claude/src/upstream/mdxfind/mdxfind',
        # TWO commands, and the second is the CPU-only guard the whole file is
        # built around. Never replace this with a bare `make`.
        build   => [ [qw(make clean)],
                     [qw(make OPENCL_GPU= OSOPT=-fgnu89-inline mdxfind)] ],
        inv     => 'data/tools/mdxfind.yaml',
        extract => [qw(tools/extract-mdxfind.pl --binary __BIN__
                       --catalog), $CATALOG, qw(--out __OUT__)],
        idkey   => 'index',
        kind    => 'type',
        xref    => { id => 'mdxfind', state => 'mdxfind_state' },
        note    => 'Built CPU-only on purpose; the extract step refuses a '
                 . 'GPU-linked binary.',
    },
    hashpipe => {
        order   => 3,
        clone   => '/home/claude/src/upstream/hashpipe',
        binary  => '/home/claude/src/upstream/hashpipe/hashpipe',
        # Plain make relinks in seconds against the vendored libsph.a etc. If it
        # fails for a missing archive, the operator runs `make deps` once -- we
        # do NOT, because deps clones and builds a dozen crypto libraries and
        # that is a decision, not a step. See CLAUDE.md (BMW224/256).
        build   => [ [qw(make)] ],
        inv     => 'data/tools/hashpipe.yaml',
        extract => [qw(tools/extract-hashpipe.pl --hashpipe __BIN__ --out __OUT__)],
        idkey   => 'index',
        kind    => 'type',
        xref    => { id => 'hashpipe', state => 'hashpipe_state' },
        note    => 'Shares mdxfind\'s type list; a second instrument, not a '
                 . 'second inventory.',
    },
    john => {
        order   => 4,
        clone   => undef,                       # royce-owned: report only
        binary  => undef,                        # resolved via RosettaTools
        inv     => 'data/tools/john.yaml',
        extract => [qw(tools/extract-john.pl --binary __BIN__ --out __OUT__)],
        idkey   => 'label',
        kind    => 'format',
        xref    => { id => 'john', state => 'john_state' },
        note    => 'Tree is royce-owned; this account cannot build it. '
                 . 'Rebuild with newjohn as the operator, then re-run extract-john.pl.',
    },
);

#-----------------------------------------------------------------------
# Options
#-----------------------------------------------------------------------
my (@only, $no_build, $write, $catalogs, $verbose, $help);
my $build_timeout = 1800;                        # seconds per build command

GetOptions(
    'only=s'         => \@only,
    'no-build'       => \$no_build,
    'write'          => \$write,
    'catalogs'       => \$catalogs,
    'build-timeout=i'=> \$build_timeout,
    'verbose|v+'     => \$verbose,
    'help|h'         => \$help,
) or usage(2);

usage(0) if $help;

my $action = shift @ARGV;
usage(2) unless defined $action;                 # no args => usage + exit 2
usage(2) unless $action eq 'check' || $action eq 'update';

@only = split /,/, join(',', @only);             # --only a,b or --only a --only b
for my $t (@only) {
    die "unknown tool '$t' (known: ", join(', ', sort keys %SUITE), ")\n"
        unless $SUITE{$t};
}
my @tools = @only ? @only
                  : sort { $SUITE{$a}{order} <=> $SUITE{$b}{order} } keys %SUITE;

# The identity line. This tool produces a REPORT, so its status goes to stdout
# (corpus rule: stderr only when stdout is data). First line of output.
print "upstream-refresh.pl - $md5\n";
chdir $root or die "cannot chdir to repo root ($root): $!\n";

my $rundir = "$root/tmp/upstream-refresh/" . iso_stamp();
make_path($rundir);
info("run artifacts: $rundir");

#-----------------------------------------------------------------------
# Main loop
#-----------------------------------------------------------------------
my %report;                                      # tool -> hashref of findings
for my $tool (@tools) {
    my $s = $SUITE{$tool};
    print "\n", ('=' x 70), "\n== $tool\n", ('=' x 70), "\n";
    print "   note: $s->{note}\n" if $s->{note};

    my $r = { tool => $tool };
    $report{$tool} = $r;

    # --- version reconnaissance -------------------------------------------
    if ($s->{clone}) {
        recon_git($tool, $s, $r);
    } else {
        recon_john($tool, $s, $r);
    }

    next if $action eq 'check';                   # check mode stops here

    # --- update: pull, build, extract, diff -------------------------------
    if (!$s->{clone}) {
        print "   update: SKIPPED (report-only tool). $s->{note}\n";
        # We can still re-extract john from its existing binary to surface an
        # inventory that has drifted behind the installed build.
        do_extract_and_diff($tool, $s, $r);
        next;
    }

    unless ($no_build) {
        do_pull($tool, $s, $r)  or next;
        do_build($tool, $s, $r) or next;
    } else {
        print "   --no-build: using the on-disk checkout and binary as-is\n";
    }
    do_extract_and_diff($tool, $s, $r);
}

# --- vendored catalogs (feed extract-mdxfind and check-upstream.pl) --------
if ($action eq 'update' && $catalogs) {
    print "\n", ('=' x 70), "\n== vendored catalogs\n", ('=' x 70), "\n";
    my $rc = run_logged("$rundir/fetch-upstream.log", $build_timeout,
                        ['tools/fetch-upstream.sh']);
    if ($rc == 0) {
        print "   refreshed vendor/cynosureprime/. Run tools/check-upstream.pl "
            . "to reconcile data/upstream-disagreements.yaml.\n";
    } else {
        print "   fetch-upstream.sh FAILED (rc=$rc); see the log.\n";
    }
}

summary(\%report, $action);
exit 0;

#=======================================================================
# Reconnaissance
#=======================================================================

# recon_git - fetch (read-only) and report how far behind upstream we are, and
# whether the committed inventory already lags the built binary.
sub recon_git {
    my ($tool, $s, $r) = @_;
    my $c = $s->{clone};
    unless (-d "$c/.git") {
        print "   clone MISSING at $c -- nothing to check\n";
        $r->{error} = 'clone missing';
        return;
    }

    # Read-only fetch over HTTPS with the gh credential helper (SSH is off
    # limits from a session). --tags so `git describe` and availability.pl see
    # new release tags.
    my $log = "$rundir/$tool.fetch.log";
    my $rc = run_logged($log, 120, [git_cmd($c, qw(fetch --tags --quiet))]);
    if ($rc != 0) {
        print "   git fetch FAILED (rc=$rc); see $log. Reporting local state only.\n";
    }

    my $local_desc = git_out($c, qw(describe --tags --always));
    my $up_ref     = git_out($c, qw(rev-parse --abbrev-ref --symbolic-full-name @{u}))
                     || 'origin/HEAD';
    my $up_desc    = git_out($c, 'describe', '--tags', '--always', $up_ref);
    my $behind     = git_out($c, 'rev-list', '--count', "HEAD..$up_ref") // '?';

    $r->{local_desc} = $local_desc;
    $r->{up_desc}    = $up_desc;
    $r->{behind}     = $behind;

    # The committed inventory's version vs the version the on-disk binary
    # reports: a gap here means we already hold a newer binary than the
    # inventory reflects (update --no-build closes it without pulling anything).
    my $inv_ver = inventory_version("$root/$s->{inv}");
    my $bin_ver = (-x $s->{binary}) ? tool_version($tool, $s->{binary}) : undef;
    $r->{inv_ver} = $inv_ver;
    $r->{bin_ver} = $bin_ver;

    printf "   checkout : %s\n", $local_desc // '?';
    printf "   upstream : %s  (%s commit%s ahead)\n",
        $up_desc // '?', $behind, ($behind eq '1' ? '' : 's');
    printf "   inventory: %s   binary now: %s\n",
        $inv_ver // '(none)', $bin_ver // '(unbuilt)';

    if (defined $behind && $behind ne '0' && $behind ne '?') {
        my $subjects = git_out($c, 'log', '--no-merges', '--format=  * %s',
                               "HEAD..$up_ref");
        if ($subjects) {
            print "   upstream commits since our checkout (behavior signal):\n";
            print "$subjects\n";
        }
        $r->{new_commits} = 1;
    } else {
        print "   checkout is up to date with upstream.\n";
    }
    if (defined $inv_ver && defined $bin_ver && $inv_ver ne $bin_ver) {
        print "   >> inventory lags the built binary; 'update --no-build "
            . "--only $tool' regenerates it with no pull.\n";
    }
}

# recon_john - no clone to fetch; compare the installed build against the
# committed inventory and say what the operator must do.
sub recon_john {
    my ($tool, $s, $r) = @_;
    my $bin = tool_path('john', undef);
    my $bin_ver = tool_version('john', $bin);
    my $inv_ver = inventory_version("$root/$s->{inv}");
    $r->{bin_ver} = $bin_ver;
    $r->{inv_ver} = $inv_ver;
    printf "   binary   : %s\n   inventory: %s\n",
        $bin_ver // '(cannot read)', $inv_ver // '(none)';
    if (defined $bin_ver && defined $inv_ver && $bin_ver ne $inv_ver) {
        print "   >> installed john differs from the inventory; "
            . "re-run extract-john.pl (operator rebuilds via newjohn).\n";
        $r->{new_commits} = 1;
    } else {
        print "   inventory matches the installed build.\n";
    }
}

#=======================================================================
# Pull / build
#=======================================================================

sub do_pull {
    my ($tool, $s, $r) = @_;
    return 1 unless $r->{new_commits};            # nothing to pull
    my $c = $s->{clone};
    my $log = "$rundir/$tool.pull.log";
    # --ff-only: a fast-forward or nothing. We never want a merge commit in a
    # mirror of someone else's tree.
    my $rc = run_logged($log, 300,
        [git_cmd($c, qw(pull --ff-only --tags --quiet))]);
    if ($rc != 0) {
        print "   git pull FAILED (rc=$rc); see $log. Skipping build.\n";
        $r->{error} = 'pull failed';
        return 0;
    }
    my $now = git_out($c, qw(describe --tags --always));
    print "   pulled -> $now\n";
    $r->{pulled_to} = $now;
    return 1;
}

sub do_build {
    my ($tool, $s, $r) = @_;
    my $c = $s->{clone};
    my $log = "$rundir/$tool.build.log";
    print "   building (log: $log) ...\n";
    for my $cmd (@{ $s->{build} }) {
        # Each build command runs in the clone dir. Prepend `timeout` so a hung
        # build cannot stall the operator forever.
        my $rc = run_logged($log, $build_timeout,
            ['timeout', $build_timeout, @$cmd], $c, 1);
        if ($rc != 0) {
            print "   build step '@$cmd' FAILED (rc=$rc); see $log.\n";
            print "   (hashpipe: if an archive is missing, run 'make deps' once "
                . "as the operator.)\n" if $tool eq 'hashpipe';
            $r->{error} = 'build failed';
            return 0;
        }
    }
    unless (-x $s->{binary}) {
        print "   build reported success but $s->{binary} is missing.\n";
        $r->{error} = 'binary missing after build';
        return 0;
    }

    # The CPU-only guard for mdxfind: a GPU-linked binary marks 109 -h rows with
    # " [GPU]" that the extractor drops silently. Catch it here, loudly, before
    # it can produce a truncated inventory.
    if ($tool eq 'mdxfind') {
        my $h = qx{$s->{binary} -h 2>&1 </dev/null};
        if ($h =~ /\[GPU\]/) {
            print "   REFUSING to extract: mdxfind was built with OpenCL "
                . "(' [GPU]' present in -h). Rebuild CPU-only.\n";
            $r->{error} = 'mdxfind GPU-linked';
            return 0;
        }
    }
    my $bin_ver = tool_version($tool, $s->{binary});
    print "   built: ", $bin_ver // '(version unread)', "\n";
    $r->{bin_ver} = $bin_ver;
    return 1;
}

#=======================================================================
# Extract to a scratch file and diff against the committed inventory
#=======================================================================

sub do_extract_and_diff {
    my ($tool, $s, $r) = @_;
    my $bin = $s->{binary} // tool_path($tool, undef);
    unless (-x $bin || $tool eq 'john') {
        print "   no binary to extract from ($bin).\n";
        return;
    }

    my $new = "$rundir/$tool.new.yaml";
    my @cmd = map { $_ eq '__BIN__' ? $bin
                  : $_ eq '__OUT__' ? $new
                  : $_ } @{ $s->{extract} };
    my $log = "$rundir/$tool.extract.log";
    print "   extracting inventory -> scratch ...\n";
    my $rc = run_logged($log, $build_timeout, [@cmd]);
    if ($rc != 0 || !-s $new) {
        print "   extract FAILED (rc=$rc); see $log.\n";
        $r->{error} = 'extract failed';
        return;
    }

    my $old = "$root/$s->{inv}";
    my $delta = diff_inventory($old, $new, $s->{idkey});
    $r->{delta} = $delta;
    report_delta($tool, $s, $delta);

    if ($write) {
        # Overwrite the committed inventory. This is the only file this script
        # writes into the repo, and only in data/tools/, the mechanical layer.
        require File::Copy;
        File::Copy::copy($new, $old) or die "cannot install $old: $!\n";
        print "   --write: installed $s->{inv} (review 'git diff' before commit)\n";
    } else {
        print "   (scratch inventory kept at $new; pass --write to install it)\n";
    }
}

# diff_inventory - compare two inventory YAMLs by IDENTIFIER, not by line.
#
# Records begin at a line matching /^  - /. Each record's stable id is the
# idkey field (mode number, eN index, or quoted label); its name (where it has
# one) is carried for the report and for the corpus cross-reference. Returns a
# hashref: added / removed (arrayrefs of {id,name}) and changed (arrayref of
# {id,name,name_old,renamed}).
sub diff_inventory {
    my ($old_file, $new_file, $idkey) = @_;
    my $old = parse_records($old_file, $idkey);
    my $new = parse_records($new_file, $idkey);

    my (@added, @removed, @changed);
    for my $id (sort keys %$new) {
        if (!exists $old->{$id}) {
            push @added, { id => $id, name => $new->{$id}{name} };
        } elsif ($old->{$id}{text} ne $new->{$id}{text}) {
            my $renamed = defined $new->{$id}{name}
                       && defined $old->{$id}{name}
                       && $new->{$id}{name} ne $old->{$id}{name};
            push @changed, {
                id       => $id,
                name     => $new->{$id}{name},
                name_old => $old->{$id}{name},
                renamed  => $renamed,
            };
        }
    }
    for my $id (sort keys %$old) {
        push @removed, { id => $id, name => $old->{$id}{name} }
            unless exists $new->{$id};
    }
    return { added => \@added, removed => \@removed, changed => \@changed };
}

# parse_records - id -> { name, text } for one inventory file.
sub parse_records {
    my ($file, $idkey) = @_;
    open my $fh, '<', $file or die "cannot read $file: $!\n";
    my %rec;
    my @cur;                                      # current record's lines
    my $flush = sub {
        return unless @cur;
        my $text = join('', @cur);
        my ($id, $name);
        if    ($idkey eq 'mode')  { ($id)   = $text =~ /^\s*-\s*mode:\s*(\d+)/m }
        elsif ($idkey eq 'index') { ($id)   = $text =~ /^\s*-\s*index:\s*"([^"]+)"/m }
        elsif ($idkey eq 'label') { ($id)   = $text =~ /^\s*-\s*label:\s*"([^"]+)"/m }
        ($name) = $text =~ /^\s+name:\s*"([^"]*)"/m;    # mdxfind/hashpipe/hashcat
        $name //= $id if $idkey eq 'label';            # john's id IS its name
        @cur = ();
        return unless defined $id;
        $rec{$id} = { name => $name, text => $text };
    };
    while (my $line = <$fh>) {
        if ($line =~ /^  - /) { $flush->(); }     # new record boundary
        push @cur, $line if @cur || $line =~ /^  - /;
    }
    $flush->();
    close $fh;
    return \%rec;
}

# report_delta - print the added/removed/changed identifiers and, crucially,
# which proven corpus rows the removed and changed ones touch.
sub report_delta {
    my ($tool, $s, $d) = @_;
    my ($na, $nr, $nc) = (scalar @{$d->{added}}, scalar @{$d->{removed}},
                          scalar @{$d->{changed}});
    printf "   inventory delta: +%d %s, -%d, ~%d changed\n",
        $na, $s->{kind}, $nr, $nc;

    if (!$na && !$nr && !$nc) {
        print "   inventory is identical to the committed copy.\n";
        return;
    }

    my $xref = load_xref($s->{xref});             # identifier -> [proven ids]

    if ($na) {
        print "   ADDED ($s->{kind}s -- new coverage opportunities):\n";
        print_ids($d->{added}, $tool);
    }
    if ($nr) {
        print "   REMOVED ($s->{kind}s no longer in the build):\n";
        print_ids($d->{removed}, $tool);
        flag_proven('REMOVED', $d->{removed}, $xref, $tool);
    }
    if ($nc) {
        print "   CHANGED ($s->{kind}s whose record moved):\n";
        for my $c (@{ $d->{changed} }) {
            my $tag = $c->{renamed}
                    ? " RENAMED '$c->{name_old}' -> '$c->{name}'" : '';
            printf "     %s %s%s\n", $c->{id}, ($c->{name} // ''), $tag;
        }
        flag_proven('CHANGED', $d->{changed}, $xref, $tool);
    }
}

sub print_ids {
    my ($list, $tool) = @_;
    my @show = @$list;
    my $more = 0;
    if (!$verbose && @show > 40) { $more = @show - 40; @show = @show[0..39]; }
    for my $e (@show) {
        printf "     %s %s\n", $e->{id}, ($e->{name} // '');
    }
    print "     ... and $more more (use -v to see all)\n" if $more;
}

# flag_proven - the point of the whole exercise: for each delta identifier,
# name the tier-`vector` rows that depend on it. These are the mappings the
# move may have invalidated -- the re-verification work the pull creates.
sub flag_proven {
    my ($label, $list, $xref, $tool) = @_;
    my @hits;
    for my $e (@$list) {
        # hashcat is keyed by mode number in both inventory and corpus; the two
        # type tools are keyed by NAME in the corpus (the eN index is internal).
        for my $key ($tool eq 'hashcat' ? ($e->{id})
                   : grep { defined } ($e->{name}, $e->{name_old})) {
            next unless defined $key && $xref->{$key};
            push @hits, { key => $key, rows => $xref->{$key} };
        }
    }
    unless (@hits) {
        print "     -> no tier-'vector' rows name these. Nothing to re-verify.\n";
        return;
    }
    print "     -> PROVEN rows to RE-VERIFY (their '$tool' block is tier vector):\n";
    for my $h (@hits) {
        printf "        %-24s <- %s\n", $h->{key}, join(', ', @{ $h->{rows} });
    }
}

# load_xref - build identifier -> [row id, ...] from dist/rosetta.csv, limited
# to rows whose <tool>_state is 'proven'. Text::CSV because the notes column
# carries commas and quotes.
sub load_xref {
    my ($cols) = @_;
    my $csv_file = "$root/dist/rosetta.csv";
    return {} unless -r $csv_file;
    require Text::CSV;
    my $csv = Text::CSV->new({ binary => 1 });
    open my $fh, '<:encoding(utf8)', $csv_file or return {};
    my $hdr = $csv->getline($fh);
    $csv->column_names(@$hdr);
    my %map;
    while (my $row = $csv->getline_hr($fh)) {
        next unless ($row->{ $cols->{state} } // '') eq 'proven';
        my $ids = $row->{ $cols->{id} } // '';
        for my $id (split /[,\s]+/, $ids) {
            next unless length $id;
            push @{ $map{$id} }, $row->{id};
        }
    }
    close $fh;
    return \%map;
}

#=======================================================================
# Summary
#=======================================================================

sub summary {
    my ($rep, $act) = @_;
    print "\n", ('#' x 70), "\n# SUMMARY ($act)\n", ('#' x 70), "\n";
    my $any_new = 0;
    my $any_reverify = 0;
    for my $tool (sort { $SUITE{$a}{order} <=> $SUITE{$b}{order} } keys %$rep) {
        my $r = $rep->{$tool};
        my @bits;
        push @bits, "ERROR: $r->{error}" if $r->{error};
        push @bits, "behind by $r->{behind}"
            if defined $r->{behind} && $r->{behind} ne '0' && $r->{behind} ne '?';
        push @bits, "pulled to $r->{pulled_to}" if $r->{pulled_to};
        if (my $d = $r->{delta}) {
            my $n = @{$d->{added}} + @{$d->{removed}} + @{$d->{changed}};
            push @bits, $n ? "inventory delta $n" : 'inventory unchanged';
            $any_reverify++ if @{$d->{removed}} || @{$d->{changed}};
        }
        $any_new++ if $r->{new_commits};
        printf "  %-9s %s\n", $tool, (@bits ? join('; ', @bits) : 'up to date');
    }
    print "\n";
    if ($act eq 'check') {
        print $any_new
            ? "  New upstream work exists. Run 'update' to pull, build and see "
              . "the inventory delta.\n"
            : "  Everything is current. No action needed.\n";
    } else {
        print "  Inventories regenerated in $rundir.\n";
        print "  Review 'git diff data/tools/' before committing.\n" if $write;
        print "  Nothing was written; re-run with --write to install "
            . "inventories.\n" unless $write;
        print "  >> Some proven rows depend on removed/changed identifiers "
            . "(see above). Re-verify them with tools/verify-vectors.pl before "
            . "trusting their tier.\n" if $any_reverify;
        print "  Curation (data/algorithms/) is deliberately untouched.\n";
    }
}

#=======================================================================
# Small helpers
#=======================================================================

# git_cmd / git_out - always with the gh credential helper, always with -C so
# we never chdir into someone else's tree and never run git in the project as
# the wrong user (corpus Rule Zero).
sub git_cmd {
    my ($dir, @args) = @_;
    return ('git', '-c', q{credential.helper=!gh auth git-credential},
            '-C', $dir, @args);
}
sub git_out {
    my ($dir, @args) = @_;
    my @cmd = git_cmd($dir, @args);
    my $out = qx{@{[ map { quote($_) } @cmd ]} 2>/dev/null};
    return undef unless defined $out && $! == 0 || length $out;
    chomp $out;
    return length $out ? $out : undef;
}
sub quote { my $s = shift; $s =~ s/'/'\\''/g; return "'$s'"; }

# run_logged - run a command with stdout+stderr to a log file, return its exit
# code. Optional chdir for the child only (via a fork), optional append. We do
# NOT hand-roll a wait loop: system() waits on the child directly, which cannot
# misfire the way a pgrep poll can (CLAUDE.md, background-jobs).
sub run_logged {
    my ($log, $timeout, $cmd, $chdir, $append) = @_;
    info("exec: @$cmd" . ($chdir ? " (in $chdir)" : ''));
    my $pid = fork();
    die "fork failed: $!\n" unless defined $pid;
    if ($pid == 0) {                              # child
        if ($chdir) { chdir $chdir or die "chdir $chdir: $!\n"; }
        my $mode = $append ? '>>' : '>';
        open STDOUT, $mode, $log or die "open $log: $!\n";
        open STDERR, '>&', \*STDOUT or die "dup: $!\n";
        exec @$cmd;
        die "exec failed: $!\n";
    }
    waitpid($pid, 0);                             # wait on the PID, not a pattern
    return $? >> 8;
}

# inventory_version - the version: field an extractor stamps into an inventory.
sub inventory_version {
    my ($file) = @_;
    return undef unless -r $file;
    open my $fh, '<', $file or return undef;
    while (my $l = <$fh>) {
        return $1 if $l =~ /^version:\s*"([^"]*)"/;
        last if $l =~ /^(?:modes|types|formats):/;   # past the header
    }
    return undef;
}

sub iso_stamp {
    my @t = localtime;                            # localtime: matches the day the operator sees
    return sprintf '%04d%02d%02d-%02d%02d%02d',
        $t[5]+1900, $t[4]+1, $t[3], $t[2], $t[1], $t[0];
}

sub info { print STDERR "[refresh] $_[0]\n" if $verbose; }

sub usage {
    my $code = shift // 0;
    my $fh = $code ? \*STDERR : \*STDOUT;
    print $fh <<'USAGE';
upstream-refresh.pl - check, pull, build and diff the upstream cracking suites

USAGE:
    tools/upstream-refresh.pl check   [--only TOOL]...
    tools/upstream-refresh.pl update  [--only TOOL]... [--no-build] [--write] [--catalogs]

ACTIONS:
    check    Fetch each upstream (read-only) and report the version delta:
             how far the checkout is behind, the new commit subjects, and
             whether the committed inventory already lags the built binary.
             Writes nothing, builds nothing.

    update   For each buildable tool that is behind: pull (fast-forward only),
             build (mdxfind CPU-only, always), regenerate the inventory into a
             scratch file, and print the delta by identifier -- modes/types/
             formats added, removed and changed -- with every removed or
             changed identifier that a tier-'vector' row names flagged for
             re-verification. john is report-only (royce-owned tree).

OPTIONS:
    --only TOOL     Restrict to one tool (repeatable, or comma-separated).
                    Known: hashcat, mdxfind, hashpipe, john.
    --no-build      Skip pull and build; re-extract from the on-disk binaries
                    and diff. The fast, safe way to refresh an inventory that
                    already lags a binary you built earlier.
    --write         Install the regenerated inventories into data/tools/.
                    Without it, scratch copies are kept and the diff only
                    printed. Never writes to data/algorithms/.
    --catalogs      (update) Also refresh vendor/cynosureprime/ via
                    fetch-upstream.sh, then remind you to run check-upstream.pl.
    --build-timeout SECS   Per build command (default 1800).
    -v, --verbose   Progress and exec lines to stderr (repeatable).
    -h, --help      This help.

EXIT: 0 success, 1 error, 2 usage.

This tool regenerates the MECHANICAL layer (data/tools/) and reports what
changed. It never edits mappings or moves a tier -- that is curation, and it
is a person's job. See HUMAN.md, "Refreshing an upstream suite".
USAGE
    exit $code;
}
