#!/usr/bin/perl
#-----------------------------------------------------------------------
#
# Name: upstream-findings.pl
# Description: render docs/UPSTREAM-FINDINGS.md from the measured record
# Category: cracking-rosetta upstream drift
#
# Project: cracking-rosetta | Phase: 6 - publish
#
#-----------------------------------------------------------------------
# METHODOLOGY AND WHY THESE CHOICES
#
# THIS REPOSITORY HAS BECOME A DEFECT DETECTOR FOR UPSTREAM'S DOCUMENTS
#
# Verifying every mapping by round-trip means reading upstream's statement of
# what a type computes and then finding out. Most of the time the document is
# right. Where it is not, the evidence has been landing in an entry's
# expression_proof note, a module comment or a commit message -- three places
# nobody outside this repository reads. Cynosure Prime's stated mission is
# coverage and validation, so a list of measured documentation defects is
# close to the most useful thing this repository can hand back.
#
# GENERATED, BECAUSE THE ALTERNATIVE IS A FOURTH COPY
#
# Every finding here already has a home: the correction lives in
# data/algorithms/ with its proof, or the type list lives in RosettaHx, or it
# is derivable from a vendored file. Retyping any of it into a Markdown page
# would create one more place for the same claim to go stale, and the whole
# point of the finding is that somebody checked.
#
# So data/upstream-findings.yaml holds the CLAIM SKELETON and a pointer, and
# this tool pulls the prose out of the thing that was measured. An entry-backed
# finding renders the entry's own note verbatim.
#
# WHY IT IS NOT data/upstream-disagreements.yaml
#
# That register's worth is that check-upstream.pl runs every record in it, and
# the rule there is that a record must be executable against a vendored file.
# None of these are. The hx specification is a PDF that is not vendored, so
# nothing can diff Appendix A; an omission from Note [24] has nothing to
# compare against; an emission count needs mdxfind and 17 minutes. Forcing
# them into the register would put unrunnable records in the one file whose
# value is that all of its records run.
#
# THE CHECKS ARE THE POINT, AND THEY RUN ON EVERY BUILD
#
# A findings page nobody re-derives is a page that quietly stops being true.
# Each record therefore names evidence this tool re-verifies:
#
#   - an entry-backed record must still find its entry, must still find a
#     non-empty note at the named field, and its we_measured must still equal
#     that entry's own expression or denotation. That last check is the one
#     that matters: if someone re-seeds upstream's value back over a corrected
#     entry, this render FAILS rather than continuing to publish a correction
#     the data no longer makes. It is failure mode (2) from the register's
#     header, applied to the unexecutable half.
#
#   - a type-backed record must name types the mdxfind inventory has, which
#     catches the separator-drift spelling trap -- measuring the C identifier
#     JOB_MD5DBLPASS rather than the published MD5-DBL-PASS reports zero and
#     looks exactly like a single-emit type. Where the record asserts
#     multi-emit, RosettaHx has to agree.
#
#   - a computed record derives its own subject list, so its count cannot be
#     wrong. This exists because a count that WAS carried in prose -- "15
#     types' example digests in uppercase hex" -- could not be reproduced by
#     any rule tried on either catalog on 2026-09-03.
#
# Dependencies: YAML::XS, RosettaHx. Reads data/upstream-findings.yaml,
# data/upstream-disagreements.yaml, data/algorithms/, data/tools/mdxfind.yaml
# and vendor/cynosureprime/hashpipe-HASH_TYPES.md. Writes one Markdown file.
#
#-----------------------------------------------------------------------
# Generated by Claude Opus 5 on 2026-09-03

use strict;
use warnings;

use File::Basename qw(basename);
use FindBin qw($RealBin);
use lib "$RealBin/lib";
use Getopt::Long qw(GetOptions);
use RosettaHx qw(is_multi_emit);
use YAML::XS ();

my $PROG = basename($0);
my $ROOT = "$RealBin/..";

sub usage {
    print STDERR <<"END_USAGE";

Usage: $PROG [options]

   --findings PATH   the record (default: data/upstream-findings.yaml)
   --out PATH        where to write (default: docs/UPSTREAM-FINDINGS.md)
   --check           verify every record and write nothing
   -v, --verbose     counts on stderr
   -h, --help        this help

   Renders the places this repository has measured an upstream DOCUMENT to be
   wrong, from the record and from the evidence each record points at. Every
   record is re-verified on the way through: a finding whose entry no longer
   makes the claim, or whose type the inventory does not have, is an error and
   not a line in the page.

   For disagreements that CAN be executed against a vendored file, see
   data/upstream-disagreements.yaml and tools/check-upstream.pl. This tool
   lists those too, briefly, so the page is the whole picture.

   Exit 0 success, 1 error, 2 usage.

END_USAGE
    return;
}

my ($findpath, $outpath, $check, $help);
my $verbose = 0;
GetOptions(
    'findings=s' => \$findpath, 'out=s' => \$outpath,
    'check'      => \$check,    'v|verbose+' => \$verbose,
    'h|help'     => \$help,
) or do { usage(); exit 2 };
if ($help) { usage(); exit 0 }

$findpath //= "$ROOT/data/upstream-findings.yaml";
$outpath  //= "$ROOT/docs/UPSTREAM-FINDINGS.md";
my $regpath  = "$ROOT/data/upstream-disagreements.yaml";
my $catalog  = "$ROOT/vendor/cynosureprime/hashpipe-HASH_TYPES.md";

my @err;
sub oops { push @err, $_[0]; return }

#-----------------------------------------------------------------------
# Load.

my $doc = eval { YAML::XS::LoadFile($findpath) }
    or do { print STDERR "$PROG: cannot read $findpath: $@\n"; exit 1 };
my @findings = @{ $doc->{findings} || [] };
@findings or do { print STDERR "$PROG: $findpath names no findings\n"; exit 1 };

my $inv = eval { YAML::XS::LoadFile("$ROOT/data/tools/mdxfind.yaml") } || {};
my %by_type = map { $_->{name} => $_ } @{ $inv->{types} || [] };

# The entries, by id, so an entry-backed finding can be re-verified against
# the claim the entry actually makes today.
my %entry;
opendir(my $dh, "$ROOT/data/algorithms")
    or do { print STDERR "$PROG: cannot read data/algorithms: $!\n"; exit 1 };
for my $f (sort grep { /\.yaml$/ } readdir $dh) {
    my $e = eval { YAML::XS::LoadFile("$ROOT/data/algorithms/$f") } or next;
    $entry{ $e->{id} } = $e if $e->{id};
}
closedir $dh;

#-----------------------------------------------------------------------
# uppercase_examples() - the derived subject list.
#
# The catalog's own preamble says every example is the complete self-test
# vector "in the same format hashpipe accepts as input". The rule here is
# deliberately narrow: take the leading colon-delimited field, require it to
# be hex, and require it to carry an upper-case letter and no lower-case one.
# A mixed-case field is not evidence of anything, and a container format has
# no leading digest to judge.
sub uppercase_examples {
    open my $fh, '<', $catalog or return oops("cannot read $catalog: $!");
    my @hit;
    while (my $line = <$fh>) {
        next unless $line =~ /^\|\s*(e\d+)\s*\|\s*(\S+)\s*\|[^|]*\|\s*`([^`]*)`/;
        my ($idx, $name, $example) = ($1, $2, $3);
        my ($first) = split /:/, $example, 2;
        next unless defined $first && $first =~ /^[0-9A-Fa-f]+\z/;
        next unless $first =~ /[A-F]/ && $first !~ /[a-f]/;
        push @hit, { index => $idx, name => $name, digest => $first };
    }
    close $fh;
    return @hit;
}

#-----------------------------------------------------------------------
# Verify. Every record earns its line on the page or stops the build.

# entry_claim($entry) - what the entry says the construction is, in the one
# field a finding's we_measured can be compared against. An entry has an
# expression or a denotation and never both (validate.pl enforces that), so
# there is no ambiguity about which to read.
sub entry_claim {
    my ($e) = @_;
    return $e->{expression} if defined $e->{expression} && length $e->{expression};
    return $e->{denotation}{text}
        if ref $e->{denotation} eq 'HASH' && defined $e->{denotation}{text};
    return undef;
}

# dig($entry, "expression_proof.note") - the note a record points at.
sub dig {
    my ($e, $path) = @_;
    my $cur = $e;
    for my $k (split /\./, $path) {
        return undef unless ref $cur eq 'HASH';
        $cur = $cur->{$k};
    }
    return (defined $cur && !ref $cur && length $cur) ? $cur : undef;
}

my %seen_id;
for my $f (@findings) {
    my $id = $f->{id} // '(unnamed)';
    oops("$id: duplicate id") if $seen_id{$id}++;
    for my $k (qw(document subject kind states we_measured measured evidence)) {
        oops("$id: no $k:") unless defined $f->{$k};
    }
    oops("$id: kind '$f->{kind}' is not one of wrong-construction, omission, "
        . "rendering, question")
        unless ($f->{kind} // '') =~ /^(wrong-construction|omission|rendering|question)$/;

    my $ev = $f->{evidence};
    unless (ref $ev eq 'HASH') { oops("$id: evidence: is not a mapping"); next }

    my @forms = grep { exists $ev->{$_} } qw(entry types computed);
    oops("$id: evidence names " . (@forms ? scalar @forms : 'no')
        . " form(s); exactly one of entry:, types:, computed: is required")
        unless @forms == 1;

    if (exists $ev->{entry}) {
        my $e = $entry{ $ev->{entry} };
        if (!$e) { oops("$id: evidence entry '$ev->{entry}' does not exist"); next }
        oops("$id: evidence entry '$ev->{entry}' is a tombstone")
            if ($e->{status} // '') eq 'merged';
        if (defined $ev->{field}) {
            my $note = dig($e, $ev->{field});
            if (!defined $note) {
                oops("$id: $ev->{entry} has no non-empty $ev->{field}");
            }
            else {
                # The note is quoted on the page AS the evidence, so it has to
                # say something about this finding. Without this check a record
                # can cite a note that is about something else entirely and the
                # page publishes a quotation that does not support the claim
                # above it -- which is exactly what happened on 2026-09-03,
                # when MD5RAWUC's expression_proof note turned out to be about
                # john's notation and said nothing about Appendix A.
                #
                # mentions: is required rather than defaulted, because the
                # curator is the one who knows which words make the note
                # evidence, and a default would quietly pass the case it exists
                # to catch.
                my $want = $ev->{mentions};
                if (!defined $want || !length $want) {
                    oops("$id: evidence names an entry field but no mentions:; "
                       . "say which text makes that note evidence for this finding");
                }
                elsif (index($note, $want) < 0) {
                    oops("$id: $ev->{entry}'s $ev->{field} does not mention "
                       . "'$want', so it is not evidence for this finding");
                }
                $f->{_note} = $note;
            }
        }
        # The check that matters: the entry must still make the claim this
        # finding reports. A re-seed from upstream over a corrected entry
        # fails the render rather than being published as a correction the
        # data no longer makes.
        my $claim = entry_claim($e);
        if (!defined $claim) {
            oops("$id: $ev->{entry} carries neither expression: nor denotation:");
        }
        elsif ($claim ne $f->{we_measured}) {
            oops("$id: we_measured is '$f->{we_measured}' but $ev->{entry} now "
                . "says '$claim' -- the entry was re-seeded, or this record is stale");
        }
    }
    elsif (exists $ev->{types}) {
        my @t = @{ $ev->{types} || [] };
        oops("$id: evidence types: is empty") unless @t;
        my %want = map { $_ => 1 } @{ $ev->{check} || [] };
        for my $k (keys %want) {
            oops("$id: check '$k' is not one of multi-emit, uppercase-example")
                unless $k =~ /^(multi-emit|uppercase-example)$/;
        }
        my %uc = map { $_->{name} => 1 } uppercase_examples();
        for my $t (@t) {
            # Spelling first. The separator-drift trap reaches this from a new
            # direction: a C identifier looks exactly like a type that measured
            # nothing rather than like a name that was never found.
            oops("$id: type '$t' is not in data/tools/mdxfind.yaml")
                unless $by_type{$t};
            oops("$id: type '$t' is asserted multi-emit and RosettaHx says it is not")
                if $want{'multi-emit'} && !is_multi_emit($t, undef);
            oops("$id: type '$t' is asserted to have an upper-case example and does not")
                if $want{'uppercase-example'} && !$uc{$t};
        }
        # A subject that opens with a number is naming the size of its own
        # evidence list, and that is exactly the kind of figure that is typed
        # once and then quietly stops being true when somebody adds a type.
        # check-numbers.pl cannot see it -- it reads the tracked Markdown, and
        # this is a count inside a YAML string -- so it is checked here.
        if (($f->{subject} // '') =~ /^(\d+)\b/ && $1 != @t) {
            oops("$id: subject says $1 but evidence names " . scalar(@t) . " type(s)");
        }
        $f->{_types} = \@t;
    }
    else {
        my $rule = $ev->{computed} // '';
        if ($rule eq 'uppercase-example-digest') {
            my @hit = uppercase_examples();
            oops("$id: rule '$rule' derived no subjects -- has the catalog moved?")
                unless @hit;
            $f->{_computed} = \@hit;
        }
        else { oops("$id: computed rule '$rule' is not implemented") }
    }
}

if (@err) {
    print STDERR "$PROG: $_\n" for @err;
    printf STDERR "%s: %d problem(s); nothing written\n", $PROG, scalar @err;
    exit 1;
}
if ($check) {
    printf STDERR "- %d finding(s) checked, all evidence still stands\n",
        scalar @findings if $verbose;
    print STDERR "OK: every finding still holds\n";
    exit 0;
}

#-----------------------------------------------------------------------
# Render.

# The stamp is the date of the last commit touching the record or this tool,
# not the clock, for the same reason render.pl does it: a CI run in another
# timezone must not rewrite the file with a date-only change.
my $today = `git -C \Q$ROOT\E log -1 --format=%cs -- data/upstream-findings.yaml data/upstream-disagreements.yaml tools/upstream-findings.pl 2>/dev/null`;
chomp $today;
$today = '(uncommitted)' unless $today =~ /^\d{4}-\d{2}-\d{2}$/;

# Markdown does not reflow a YAML folded block the way a reader expects, and
# these summaries are two to eight sentences. One space-joined paragraph is
# what a Markdown paragraph is.
# codeish($value) - back-tick a construction, leave a sentence alone.
#
# Both sides of the comparison table are usually expressions and want a code
# span. Sometimes neither is: where the appendix omits the password operand
# from three rows at once, the honest statement of what was measured is a
# sentence, and setting a sentence in a monospace span makes it read like a
# literal the reader should be able to paste somewhere.
#
# The test is structural rather than a guess at prose: every comma-separated
# part has to look like a call. Anything else is text.
sub codeish {
    my ($v) = @_;
    $v //= '';
    my @part = split /,\s+/, $v;
    return "`$v`" if @part && !grep { !/^[A-Za-z0-9_]+\(.*\)\z/ } @part;
    return $v;
}

sub para {
    my ($s) = @_;
    $s //= '';
    $s =~ s/\s+/ /g;
    $s =~ s/^\s+|\s+$//g;
    return $s;
}

my %KIND_HEAD = (
    'wrong-construction' => 'A stated construction the type does not compute',
    'omission'           => 'Something the document does not say',
    'rendering'          => 'An example the tool will not read back',
    'question'           => 'A question, not a defect',
);

open my $out, '>', $outpath or do {
    print STDERR "$PROG: cannot write $outpath: $!\n"; exit 1 };

printf {$out} "# What this repository has measured upstream to have wrong\n\n";
printf {$out} "GENERATED by `tools/%s` on %s - do not edit; regenerate.\n\n",
    $PROG, $today;

print {$out} <<'HEAD';
This page is for the people who maintain mdxfind, hashpipe and the hx
specification. It is not a complaint: almost everything in those documents
checks out, and the ones that do not were found precisely because this
repository refuses to record a mapping it has not reproduced. Each finding
below was measured here, and each says how.

Nothing on this page is asserted from reading. Where a finding names an entry,
the correction is carried by that entry with its proof, and this page renders
the entry's own note rather than a retelling of it - so if the entry is ever
re-seeded back to the published value, the page fails to build instead of
going quietly out of date.

**Two kinds of disagreement, and they live in different files.** A
disagreement that can be tested against a file vendored into this repository
is a record in `data/upstream-disagreements.yaml`, executed by
`tools/check-upstream.pl` on every build; those are summarised at the end. The
findings here cannot be tested that way - the hx specification is a PDF that
is not vendored, an omission has nothing to diff against, and an emission
count needs the binary - so they are recorded, checked as far as they can be,
and published.

HEAD

# The count of question findings is derived, because it is exactly the sort of
# figure that is written once and then quietly stops being true. There were
# two when this paragraph was written and the number is not typed anywhere.
{
    my $q = grep { ($_->{kind} // '') eq 'question' } @findings;
    printf {$out} "**How to read a `question`.** %s\n\n", $q == 1
        ? 'One finding below is a measurement that disagrees with a document '
        . 'and is *not* strong enough to overrule it. It is here so upstream '
        . 'can settle it from the source, and nothing in this repository has '
        . 'been withdrawn on the strength of it.'
        : "$q of the findings below are measurements that disagree with a "
        . 'document and are *not* strong enough to overrule it. They are here '
        . 'so upstream can settle them from the source, and nothing in this '
        . 'repository has been withdrawn on the strength of them.';
}

# One section per finding, grouped by document so a maintainer reads their own
# document's findings together rather than hunting for them.
my %by_doc;
push @{ $by_doc{ $_->{document} } }, $_ for @findings;

for my $d (sort keys %by_doc) {
    printf {$out} "## %s\n\n", $d;
    for my $f (sort { $a->{id} cmp $b->{id} } @{ $by_doc{$d} }) {
        printf {$out} "### %s\n\n", $f->{subject};
        printf {$out} "*%s.* Measured %s", $KIND_HEAD{ $f->{kind} }, $f->{measured};
        printf {$out} " with %s", $f->{measured_with} if $f->{measured_with};
        print  {$out} ".\n\n";
        printf {$out} "| | |\n|---|---|\n";
        printf {$out} "| the document states | %s |\n", codeish($f->{states});
        printf {$out} "| measured here | %s |\n\n", codeish($f->{we_measured});
        printf {$out} "%s\n\n", para($f->{summary}) if $f->{summary};

        if (my $n = $f->{_note}) {
            printf {$out} "The evidence, as it stands in `data/algorithms/%s.yaml`"
                        . " under `%s`:\n\n", $f->{evidence}{entry}, $f->{evidence}{field};
            printf {$out} "> %s\n\n", para($n);
        }
        if (my $t = $f->{_types}) {
            printf {$out} "The %d type(s), as the binary spells them:\n\n", scalar @$t;
            printf {$out} "%s\n\n", join(', ', map { "`$_`" } @$t);
        }
        if (my $c = $f->{_computed}) {
            printf {$out} "Derived from the vendored catalog at render time,"
                        . " not typed here - %d type(s):\n\n", scalar @$c;
            print  {$out} "| Index | Type | Example digest as published |\n|---|---|---|\n";
            printf {$out} "| `%s` | `%s` | `%s` |\n",
                $_->{index}, $_->{name}, $_->{digest} for @$c;
            print  {$out} "\n";
        }
    }
}

#-----------------------------------------------------------------------
# The executable half, briefly, so the page is the whole picture.

if (my $reg = eval { YAML::XS::LoadFile($regpath) }) {
    my @recs = @{ $reg->{disagreements} || [] };
    if (@recs) {
        print {$out} "## Disagreements that are tested on every build\n\n";
        print {$out} <<'REG';
These are in `data/upstream-disagreements.yaml` rather than above, because each
one can be executed against a file vendored into this repository.
`tools/check-upstream.pl` fails three ways on them: upstream moved, this
repository was re-seeded back to upstream's value, or the two have CONVERGED
and the record should be deleted. The third is the one nothing else can see -
it looks exactly like nothing having happened - and it is what makes a re-fetch
that changes nothing a passing test rather than an absence of evidence.

REG
        print {$out} "| Record | Kind | Recorded | What it holds |\n|---|---|---|---|\n";
        for my $r (sort { ($a->{id} // '') cmp ($b->{id} // '') } @recs) {
            my $because = para($r->{because} // '');
            # One sentence is the right size for a summary row; the file is
            # one click away and carries the whole argument.
            $because =~ s/^(.{0,200}?\.)\s.*$/$1/s;
            printf {$out} "| `%s` | %s | %s | %s |\n",
                $r->{id} // '?', $r->{kind} // '?', $r->{recorded} // '?', $because;
        }
        print {$out} "\n";
    }
}

print {$out} <<'FOOT';
## How to report a mistake in this page

Open an issue. A finding here is only worth having if it is right, and the
fastest way to retire one is to show the measurement that contradicts it - the
invocation, the version, and what came back. This repository has been wrong in
both directions and re-run things on the strength of one message, so a
correction is welcome rather than merely tolerated.

A finding that upstream has fixed should be deleted here rather than left
standing with a note, for the same reason a converged record is deleted from
`data/upstream-disagreements.yaml`: a page of retired findings is a page
nobody trusts the current ones on.
FOOT
close $out;

printf STDERR "- wrote %s (%d finding(s), %d document(s))\n",
    $outpath, scalar @findings, scalar keys %by_doc if $verbose;
exit 0;
