#!/usr/bin/perl
#-----------------------------------------------------------------------
#
# Name: validate.pl
# Description: check data/algorithms/ against the schema AND against what the
#              tools actually support
# Category: cracking-rosetta validator
#
# Project: cracking-rosetta | Phase: 0 - validation contract
#
#-----------------------------------------------------------------------
# METHODOLOGY AND WHY THESE CHOICES
#
# WHY THIS IS NOT A JSON SCHEMA VALIDATOR
#
# schema/algorithm.schema.json describes the SHAPE of an entry, and that is
# worth having for editors and outside consumers. It cannot express the checks
# that actually matter here, all of which are cross-references into the
# generated inventories:
#
#   - does hashcat mode 2811 exist in THIS hashcat?
#   - does dynamic_12 exist in THIS john, and is it really a CPU format?
#   - does MD5-MD5SALTMD5PASS exist in THIS mdxfind?
#
# A curated mapping that names an identifier no installed tool has is the
# single most likely defect in this repository - it is exactly what happens
# when upstream renames or retires something and the rosetta is not updated.
# That is the defect the old spreadsheet accumulated for three years. So the
# cross-reference is the point of this script, and the shape checks are done
# here too rather than in two places that could disagree.
#
# EVERY ERROR NAMES THE FILE AND THE FIX
#
# This gates PRs from contributors who did not write the schema, so an error
# says which file, which field, and what would make it pass. "Invalid" on its
# own sends people to read source.
#
# TIER 'absent' IS CHECKED, NOT ASSUMED
#
# An entry saying john does not support an algorithm, while also naming a john
# format, is a contradiction that would otherwise sit there looking populated.
#
#-----------------------------------------------------------------------
# Generated by Claude Opus 5 on 2026-08-29

use strict;
use warnings;

use File::Basename qw(basename);
use FindBin qw($RealBin);
use Getopt::Long qw(GetOptions);
use YAML::XS ();

my $PROG = basename($0);
my $ROOT = "$RealBin/..";

sub usage {
    print STDERR <<"END_USAGE";

Usage: $PROG [options]

   --algorithms DIR  curated entries (default: data/algorithms)
   --tools DIR       generated inventories (default: data/tools)
   -q, --quiet       errors only; no summary
   -v, --verbose     per-tool coverage breakdown (repeatable)
   -h, --help        this help

   Checks every data/algorithms/*.yaml for shape, and cross-references every
   identifier it names against the generated tool inventories.

   Exit 0 clean, 1 validation errors found, 2 usage or missing inventories.

END_USAGE
    return;
}

my ($algdir, $tooldir, $quiet, $help);
my $verbose = 0;

GetOptions(
    'algorithms=s' => \$algdir,
    'tools=s'      => \$tooldir,
    'q|quiet'      => \$quiet,
    'v|verbose+'   => \$verbose,
    'h|help'       => \$help,
) or do { usage(); exit 2 };

if ($help) { usage(); exit 0 }

$algdir  //= "$ROOT/data/algorithms";
$tooldir //= "$ROOT/data/tools";

#-----------------------------------------------------------------------
# Known vocabulary. Kept beside the checks that use it so the two cannot drift.

my @TIERS      = qw(vector upstream asserted absent);
my %IS_TIER    = map { $_ => 1 } @TIERS;
my %IS_STATUS  = map { $_ => 1 } qw(ok needs-review);

my %TOP_KEY = map { $_ => 1 } qw(
    id name aliases expression john_dynamic_expr expression_proof denotation
    category application application_version status
    tools relations vectors legacy notes
);

my %EXPR_PROOF_KEY = map { $_ => 1 } qw(verified verified_at verified_with note);
my %DENOTATION_KEY = map { $_ => 1 } qw(text source note);
my %IS_DENOT_SOURCE = map { $_ => 1 }
    qw(sheet mdxfind hashcat john hashpipe hashes.org human);

my %IS_CATEGORY = map { $_ => 1 } qw(
    primitive composite iterated encoding application protocol kdf
);

# The relation vocabulary. See ACTION-PLAN.md section 11 for what each edge
# means; the short version is that 'kind' says what the relationship is and
# 'distinction' says why both entries nonetheless exist.
my %IS_REL_KIND = map { $_ => 1 } qw(
    same-computation encodes input-encoding iterates truncates
    collides-on-subset duplicate-of
);
my %IS_REL_DISTINCTION = map { $_ => 1 } qw(
    application encoding input-encoding iteration truncation
    salt-convention none
);

# An edge of one of these kinds is what makes two entries allowed to share an
# expression: it says the shared computation is deliberate and accounted for.
my %JOINS_EXPRESSION = map { $_ => 1 } qw(same-computation encodes duplicate-of);

# What each kind mirrors to on the other entry. Every relation is symmetric --
# an unmirrored edge is a half-truth that only one of the two files tells.
my %REL_MIRROR = (
    'same-computation'  => 'same-computation',
    'encodes'           => 'encodes',
    'input-encoding'    => 'input-encoding',
    'collides-on-subset'=> 'collides-on-subset',
    'duplicate-of'      => 'duplicate-of',
    'iterates'          => 'iterates',
    'truncates'         => 'truncates',
);

my %TOOL_KEY = (
    hashcat => { map { $_ => 1 } qw(modes verified verified_at verified_with note) },
    john    => { map { $_ => 1 } qw(cpu gpu verified verified_at verified_with note) },
    mdxfind => { map { $_ => 1 } qw(types iterations verified verified_at verified_with note) },
    crack   => { map { $_ => 1 } qw(supported note) },
);

# Which key in each tool block holds the identifiers to cross-reference.
my %IDENT_KEYS = (
    hashcat => ['modes'],
    john    => ['cpu', 'gpu'],
    mdxfind => ['types'],
);

my (@errors, @warnings);

sub err  { push @errors,   sprintf(shift, @_) }
sub warn_ { push @warnings, sprintf(shift, @_) }

#-----------------------------------------------------------------------
# Load the generated inventories. Without these there is nothing to check
# against, so a missing one is fatal rather than a skipped check.

sub load_inventory {
    my ($file, $listkey) = @_;
    -r $file or do {
        print STDERR "$PROG: cannot read $file -- run the extractor first.\n";
        exit 2;
    };
    my $d = eval { YAML::XS::LoadFile($file) };
    if (!$d || $@) {
        print STDERR "$PROG: $file did not parse as YAML: $@\n";
        exit 2;
    }
    return ($d, $d->{$listkey} || []);
}

my ($hc_doc, $hc_list) = load_inventory("$tooldir/hashcat.yaml", 'modes');
my ($jn_doc, $jn_list) = load_inventory("$tooldir/john.yaml",    'formats');
my ($mx_doc, $mx_list) = load_inventory("$tooldir/mdxfind.yaml", 'types');

my %HC_MODE = map { $_->{mode} => $_ } @$hc_list;
my %JN_FMT  = map { $_->{label} => $_ } @$jn_list;

# Dynamics that exist in the build but are switched off by dynamic_disabled.conf.
# Naming one is legitimate - the format is real and a host can re-enable it -
# so it validates, but it is counted and reported so nobody is surprised when
# "john --format=dynamic_81" says no such format on a default install.
my %JN_DISABLED = map { $_ => 1 } @{ $jn_doc->{disabled_dynamic} || [] };
my %used_disabled;
my %MX_TYPE = map { $_->{name} => $_ } @$mx_list;

# mdxfind is also addressable by index (e1), which the old sheet sometimes used.
my %MX_INDEX = map { $_->{index} => $_ } @$mx_list;

# Which inventory entries any algorithm file actually references. Drives the
# coverage report, which is the number this project exists to move.
my (%hit_hc, %hit_jn, %hit_mx);

#-----------------------------------------------------------------------
# Walk the curated entries.

opendir(my $dh, $algdir) or do {
    print STDERR "$PROG: cannot read $algdir: $!\n";
    exit 2;
};
my @files = sort grep { /\.yaml$/ } readdir $dh;
closedir $dh;

my %seen_id;
my %by_expression;   # expression -> [ ids ] , for the collision rule
my @rel_edges;       # every edge seen, resolved after the loop
my $entries = 0;

for my $file (@files) {
    my $path = "$algdir/$file";
    my $stem = $file; $stem =~ s/\.yaml$//;

    my $d = eval { YAML::XS::LoadFile($path) };
    if ($@ || !defined $d) {
        # YAML::XS puts the useful part ("found character that cannot start
        # any token", with a line number) several lines into its message, so
        # keep the first few lines flattened rather than just the first.
        my $why = $@ || 'empty file';
        $why =~ s/\s+/ /g;
        $why = substr($why, 0, 200);
        err("%s: does not parse as YAML: %s", $file, $why);
        next;
    }
    if (ref $d ne 'HASH') {
        err("%s: top level must be a mapping, got %s", $file, (ref $d || 'a scalar'));
        next;
    }
    $entries++;

    # --- identity -----------------------------------------------------
    my $id = $d->{id};
    if (!defined $id || !length $id) {
        err("%s: missing required key 'id'", $file);
    }
    elsif ($id ne $stem) {
        err("%s: id '%s' does not match the filename; rename the file to %s.yaml or fix id",
            $file, $id, $id);
    }
    elsif ($id !~ /^[a-z0-9][a-z0-9._-]*$/) {
        err("%s: id '%s' must be lowercase alphanumeric with . _ or -", $file, $id);
    }
    elsif ($seen_id{$id}++) {
        err("%s: duplicate id '%s'", $file, $id);
    }

    err("%s: missing required key 'name'", $file)
        unless defined $d->{name} && length $d->{name};

    for my $k (sort keys %$d) {
        err("%s: unknown top-level key '%s'", $file, $k) unless $TOP_KEY{$k};
    }

    if (defined $d->{status} && !$IS_STATUS{ $d->{status} }) {
        err("%s: status '%s' is not one of: %s", $file, $d->{status},
            join(', ', sort keys %IS_STATUS));
    }

    # --- expression_proof ---------------------------------------------
    #
    # expression: is a gate: rule 3 below fails a build where two entries
    # claim the same one. A field with that much authority must say how it
    # was established, the same way every per-tool mapping does -- otherwise
    # a transcription and a round-trip are indistinguishable and the first
    # awkward collision becomes an argument for weakening the rule.
    my $has_expr  = defined $d->{expression} && length $d->{expression};
    my $proof     = $d->{expression_proof};
    my $expr_tier;

    if (defined $proof) {
        if (ref $proof ne 'HASH') {
            err("%s: 'expression_proof' must be a mapping", $file);
        }
        else {
            for my $k (sort keys %$proof) {
                err("%s: unknown key 'expression_proof.%s'", $file, $k)
                    unless $EXPR_PROOF_KEY{$k};
            }
            $expr_tier = $proof->{verified};
            if (!defined $expr_tier || !length $expr_tier) {
                err("%s: expression_proof needs a 'verified' tier", $file);
            }
            elsif (!$IS_TIER{$expr_tier}) {
                err("%s: expression_proof.verified '%s' is not one of: %s",
                    $file, $expr_tier, join(', ', @TIERS));
            }

            if (defined $proof->{verified_at}
                && $proof->{verified_at} !~ /^\d{4}-\d{2}-\d{2}$/) {
                err("%s: expression_proof.verified_at '%s' is not YYYY-MM-DD",
                    $file, $proof->{verified_at});
            }

            # Same rule the tool blocks get: 'vector' means something was
            # round-tripped, and there is nothing to round-trip against.
            if (defined $expr_tier && $expr_tier eq 'vector'
                && !(ref $d->{vectors} eq 'ARRAY' && @{ $d->{vectors} })) {
                err("%s: expression_proof.verified is 'vector' but the entry "
                  . "has no vectors", $file);
            }

            # 'absent' is the settled decision that this algorithm has no
            # expression in the dynamic language. Carrying one anyway is the
            # entry contradicting itself.
            if (defined $expr_tier && $expr_tier eq 'absent' && $has_expr) {
                err("%s: expression_proof.verified is 'absent' but an "
                  . "expression is recorded", $file);
            }
        }
    }

    # Nothing lands untiered. This is what stops the field drifting back to
    # a bare string whose provenance nobody can reconstruct.
    if ($has_expr && !defined $proof) {
        err("%s: 'expression' is set but there is no expression_proof tier",
            $file);
    }

    if (defined $d->{john_dynamic_expr} && length $d->{john_dynamic_expr}
        && !$has_expr) {
        err("%s: 'john_dynamic_expr' is set without an 'expression'", $file);
    }

    # --- denotation ---------------------------------------------------
    my $den = $d->{denotation};
    if (defined $den) {
        if (ref $den ne 'HASH') {
            err("%s: 'denotation' must be a mapping", $file);
        }
        else {
            for my $k (sort keys %$den) {
                err("%s: unknown key 'denotation.%s'", $file, $k)
                    unless $DENOTATION_KEY{$k};
            }
            err("%s: denotation needs a 'text'", $file)
                unless defined $den->{text} && length $den->{text};
            if (defined $den->{source} && !$IS_DENOT_SOURCE{ $den->{source} }) {
                err("%s: denotation.source '%s' is not one of: %s", $file,
                    $den->{source}, join(', ', sort keys %IS_DENOT_SOURCE));
            }
            # denotation is the fallback for an entry with no expression. An
            # entry with both says the same thing twice at two strengths, and
            # a reader has no way to know which one to believe.
            err("%s: denotation is set alongside an expression; denotation is "
              . "for entries that have none", $file) if $has_expr;
        }
    }

    # --- tools --------------------------------------------------------
    my $tools = $d->{tools};
    if (defined $tools) {
        if (ref $tools ne 'HASH') {
            err("%s: 'tools' must be a mapping", $file);
        }
        else {
            for my $tool (sort keys %$tools) {
                if (!$TOOL_KEY{$tool}) {
                    err("%s: unknown tool '%s'; known: %s", $file, $tool,
                        join(', ', sort keys %TOOL_KEY));
                    next;
                }
                my $blk = $tools->{$tool};
                if (ref $blk ne 'HASH') {
                    err("%s: tools.%s must be a mapping", $file, $tool);
                    next;
                }

                for my $k (sort keys %$blk) {
                    err("%s: unknown key 'tools.%s.%s'", $file, $tool, $k)
                        unless $TOOL_KEY{$tool}{$k};
                }

                if (defined $blk->{iterations}
                    && $blk->{iterations} !~ /^[1-9][0-9]*$/) {
                    err("%s: tools.%s.iterations '%s' must be a positive integer",
                        $file, $tool, $blk->{iterations});
                }

                my $tier = $blk->{verified};
                if (defined $tier && !$IS_TIER{$tier}) {
                    err("%s: tools.%s.verified '%s' is not one of: %s",
                        $file, $tool, $tier, join(', ', @TIERS));
                }

                if (defined $blk->{verified_at}
                    && $blk->{verified_at} !~ /^\d{4}-\d{2}-\d{2}$/) {
                    err("%s: tools.%s.verified_at '%s' is not YYYY-MM-DD",
                        $file, $tool, $blk->{verified_at});
                }

                # A claim of 'vector' with nothing to verify against is the
                # one tier that must never be taken on trust.
                if (defined $tier && $tier eq 'vector'
                    && !(ref $d->{vectors} eq 'ARRAY' && @{ $d->{vectors} })) {
                    err("%s: tools.%s.verified is 'vector' but the entry has no vectors",
                        $file, $tool);
                }

                # Identifier cross-reference, the point of this script.
                my $named = 0;
                for my $key (@{ $IDENT_KEYS{$tool} || [] }) {
                    my $vals = $blk->{$key} or next;
                    if (ref $vals ne 'ARRAY') {
                        err("%s: tools.%s.%s must be a list", $file, $tool, $key);
                        next;
                    }
                    $named += scalar @$vals;

                    for my $v (@$vals) {
                        if ($tool eq 'hashcat') {
                            if ($v !~ /^\d+$/) {
                                err("%s: hashcat mode '%s' is not a number", $file, $v);
                            }
                            elsif (!exists $HC_MODE{ $v + 0 }) {
                                err("%s: hashcat mode %s does not exist in %s",
                                    $file, $v, $hc_doc->{version});
                            }
                            else { $hit_hc{ $v + 0 } = 1 }
                        }
                        elsif ($tool eq 'john') {
                            my $f = $JN_FMT{$v};
                            if (!$f && $JN_DISABLED{$v}) {
                                # Real format, disabled by config, not an error.
                                # NOT counted in %hit_jn: coverage is measured
                                # against the formats john actually loaded, and
                                # mixing a disabled label into that numerator
                                # would let coverage exceed the denominator.
                                $used_disabled{$v} = 1;
                            }
                            elsif (!$f) {
                                err("%s: john format '%s' does not exist in %s",
                                    $file, $v, $jn_doc->{version});
                            }
                            else {
                                $hit_jn{$v} = 1;
                                my $dev = $f->{device} // 'cpu';
                                if ($key eq 'cpu' && $dev ne 'cpu') {
                                    err("%s: john format '%s' is a %s build; list it under tools.john.gpu",
                                        $file, $v, $dev);
                                }
                                if ($key eq 'gpu' && $dev eq 'cpu') {
                                    err("%s: john format '%s' is a CPU format; list it under tools.john.cpu",
                                        $file, $v);
                                }
                            }
                        }
                        elsif ($tool eq 'mdxfind') {
                            if (exists $MX_TYPE{$v})      { $hit_mx{$v} = 1 }
                            elsif (exists $MX_INDEX{$v})  {
                                err("%s: mdxfind '%s' is an index; use the type name '%s'",
                                    $file, $v, $MX_INDEX{$v}{name});
                            }
                            else {
                                err("%s: mdxfind type '%s' does not exist in %s",
                                    $file, $v, $mx_doc->{version});
                            }
                        }
                    }
                }

                # 'absent' means the tool cannot do this. Naming an identifier
                # anyway is a contradiction, not extra information.
                if (defined $tier && $tier eq 'absent' && $named) {
                    err("%s: tools.%s.verified is 'absent' but %d identifier(s) are listed",
                        $file, $tool, $named);
                }
            }
        }
    }

    push @{ $by_expression{ $d->{expression} } }, ($id // $stem)
        if defined $d->{expression} && length $d->{expression};

    # --- category -----------------------------------------------------
    if (defined $d->{category} && !$IS_CATEGORY{ $d->{category} }) {
        err("%s: category '%s' is not one of: %s",
            $file, $d->{category}, join(' ', sort keys %IS_CATEGORY));
    }
    if (defined $d->{application} && ($d->{category} // '') ne 'application') {
        warn_("%s: names an application but category is not 'application'", $file);
    }

    # --- relations ----------------------------------------------------
    if (defined $d->{relations}) {
        if (ref $d->{relations} ne 'ARRAY') {
            err("%s: 'relations' must be a list", $file);
        }
        else {
            my $i = 0;
            for my $r (@{ $d->{relations} }) {
                $i++;
                if (ref $r ne 'HASH') {
                    err("%s: relations[%d] must be a mapping", $file, $i);
                    next;
                }
                my ($kind, $to) = ($r->{kind}, $r->{entry});
                if (!defined $kind || !$IS_REL_KIND{$kind}) {
                    err("%s: relations[%d] kind '%s' is not one of: %s",
                        $file, $i, $kind // '(missing)',
                        join(' ', sort keys %IS_REL_KIND));
                    next;
                }
                if (!defined $to || $to !~ /^[a-z0-9][a-z0-9._-]*$/) {
                    err("%s: relations[%d] needs an 'entry' id", $file, $i);
                    next;
                }
                err("%s: relations[%d] points at its own entry", $file, $i)
                    if defined $id && $to eq $id;

                my $dist = $r->{distinction};
                if (defined $dist && !$IS_REL_DISTINCTION{$dist}) {
                    err("%s: relations[%d] distinction '%s' is not one of: %s",
                        $file, $i, $dist, join(' ', sort keys %IS_REL_DISTINCTION));
                }
                # 'none' means nothing separates these two, which is only a
                # coherent thing to say while proposing a merge.
                if (defined $dist && $dist eq 'none' && $kind ne 'duplicate-of') {
                    err("%s: relations[%d] has distinction 'none' but kind '%s'; "
                      . "'none' is only legal with 'duplicate-of'", $file, $i, $kind);
                }
                if ($kind eq 'duplicate-of' && defined $dist && $dist ne 'none') {
                    err("%s: relations[%d] is 'duplicate-of' but claims a "
                      . "distinction '%s'", $file, $i, $dist);
                }
                # The whole point of this kind is to record WHY the agreement
                # is an accident, so an unexplained one is worse than none.
                if ($kind eq 'collides-on-subset'
                    && !(defined $r->{note} && length $r->{note})) {
                    err("%s: relations[%d] is 'collides-on-subset' and must carry "
                      . "a note naming the inputs on which the two agree",
                        $file, $i);
                }
                push @rel_edges, { from => ($id // $stem), to => $to,
                                   kind => $kind, file => $file };
            }
        }
    }

    # --- vectors ------------------------------------------------------
    if (defined $d->{vectors}) {
        if (ref $d->{vectors} ne 'ARRAY') {
            err("%s: 'vectors' must be a list", $file);
        }
        else {
            my $i = 0;
            for my $v (@{ $d->{vectors} }) {
                $i++;
                if (ref $v ne 'HASH') {
                    err("%s: vectors[%d] must be a mapping", $file, $i);
                    next;
                }
                err("%s: vectors[%d] is missing 'hash'", $file, $i)
                    unless defined $v->{hash} && length $v->{hash};
                err("%s: vectors[%d] is missing 'pass'", $file, $i)
                    unless defined $v->{pass};
            }
        }
    }
}

#-----------------------------------------------------------------------
# Cross-entry relation checks.
#
# These are the rules that make expression: a gate rather than a decoration.
# Everything above validates one file at a time; a relation is by definition
# about two, and the collision rule is about the whole corpus at once.

{
    my %edge;                       # "from\0to\0kind" -> 1
    $edge{"$_->{from}\0$_->{to}\0$_->{kind}"} = 1 for @rel_edges;

    # Union-find over the joining edges: equivalence is transitive, so a group
    # of four entries sharing an expression needs three edges in a star, not
    # six in a clique. Requiring the clique would make the data unreadable
    # long before it made it more correct.
    my %parent;
    my $find; $find = sub {
        my ($x) = @_;
        $parent{$x} //= $x;
        return $x if $parent{$x} eq $x;
        return $parent{$x} = $find->($parent{$x});
    };
    my $union = sub {
        my ($x, $y) = @_;
        my ($rx, $ry) = ($find->($x), $find->($y));
        $parent{$rx} = $ry unless $rx eq $ry;
    };

    for my $e (@rel_edges) {
        # 1. The other end has to exist.
        unless ($seen_id{ $e->{to} }) {
            err("%s: relation names '%s', which is not an entry",
                $e->{file}, $e->{to});
            next;
        }
        # 2. And it has to say so too. A one-sided edge is a fact only one of
        #    the two files tells, and whichever file a reader opens first
        #    decides whether they learn it. tools/relate.pl writes both.
        my $mirror = $REL_MIRROR{ $e->{kind} } // $e->{kind};
        unless ($edge{"$e->{to}\0$e->{from}\0$mirror"}) {
            err("%s: relation '%s' -> %s is not mirrored; %s.yaml needs "
              . "'%s' -> %s (tools/relate.pl --apply writes both sides)",
                $e->{file}, $e->{kind}, $e->{to}, $e->{to}, $mirror, $e->{from});
        }
        $union->($e->{from}, $e->{to}) if $JOINS_EXPRESSION{ $e->{kind} };
    }

    # 3. Two entries claiming the same expression are claiming to be the same
    #    computation. That is allowed -- Joomla and generic md5($p.$s) really
    #    are -- but it has to be stated, or the table has two rows and no
    #    account of why. Every entry in a colliding group must reach every
    #    other through same-computation, encodes or duplicate-of edges.
    for my $x (sort keys %by_expression) {
        my @ids = @{ $by_expression{$x} };
        next unless @ids > 1;
        my %group;
        push @{ $group{ $find->($_) } }, $_ for @ids;
        next if keys %group == 1;
        err("'%s' is claimed by entries that are not related to each other: "
          . "%s. Join them with same-computation, encodes or duplicate-of "
          . "(see ACTION-PLAN.md section 11)",
            $x, join(' | ', map { join(', ', sort @{ $group{$_} }) }
                            sort keys %group));
    }
}

#-----------------------------------------------------------------------
# Report.

print STDERR "- $_\n" for @warnings;

if (@errors) {
    print STDERR "- Error: $_\n" for @errors;
}

unless ($quiet) {
    printf STDERR "\n- Inventories: hashcat %d modes (%s), john %d formats (%s), mdxfind %d types (%s)\n",
        scalar(@$hc_list), $hc_doc->{version},
        scalar(@$jn_list), $jn_doc->{version},
        scalar(@$mx_list), $mx_doc->{version};

    printf STDERR "- Entries:     %d file(s) in %s\n", $entries, $algdir;

    my $pc = sub {
        my ($n, $d) = @_;
        return $d ? sprintf('%.1f%%', 100 * $n / $d) : 'n/a';
    };

    printf STDERR "- Coverage:    hashcat %d/%d (%s)  john %d/%d (%s)  mdxfind %d/%d (%s)\n",
        scalar(keys %hit_hc), scalar(@$hc_list), $pc->(scalar(keys %hit_hc), scalar(@$hc_list)),
        scalar(keys %hit_jn), scalar(@$jn_list), $pc->(scalar(keys %hit_jn), scalar(@$jn_list)),
        scalar(keys %hit_mx), scalar(@$mx_list), $pc->(scalar(keys %hit_mx), scalar(@$mx_list));

    if ($verbose) {
        my @unmapped = sort { $a <=> $b } grep { !$hit_hc{$_} } map { $_->{mode} } @$hc_list;
        printf STDERR "-   hashcat modes with no entry: %d (first: %s)\n",
            scalar(@unmapped), join(', ', @unmapped[0 .. ($#unmapped > 9 ? 9 : $#unmapped)]);
    }

    if (%used_disabled) {
        printf STDERR "- Note:        %d john dynamic(s) named by entries are disabled in dynamic_disabled.conf\n",
            scalar(keys %used_disabled);
        printf STDERR "-              (real formats; re-enable them in that file to use them)\n";
    }

    printf STDERR "- %s\n", @errors
        ? sprintf('FAILED: %d error(s)', scalar @errors)
        : 'OK: no errors';
}

exit(@errors ? 1 : 0);
