#!/usr/bin/perl
#-----------------------------------------------------------------------
#
# Name: validate.pl
# Description: check data/algorithms/ against the schema AND against what the
#              tools actually support
# Category: cracking-rosetta validator
#
# Project: cracking-rosetta | Phase: 0 - validation contract
#
#-----------------------------------------------------------------------
# METHODOLOGY AND WHY THESE CHOICES
#
# WHY THIS IS NOT A JSON SCHEMA VALIDATOR
#
# schema/algorithm.schema.json describes the SHAPE of an entry, and that is
# worth having for editors and outside consumers. It cannot express the checks
# that actually matter here, all of which are cross-references into the
# generated inventories:
#
#   - does hashcat mode 2811 exist in THIS hashcat?
#   - does dynamic_12 exist in THIS john, and is it really a CPU format?
#   - does MD5-MD5SALTMD5PASS exist in THIS mdxfind?
#
# A curated mapping that names an identifier no installed tool has is the
# single most likely defect in this repository - it is exactly what happens
# when upstream renames or retires something and the rosetta is not updated.
# That is the defect the old spreadsheet accumulated for three years. So the
# cross-reference is the point of this script, and the shape checks are done
# here too rather than in two places that could disagree.
#
# EVERY ERROR NAMES THE FILE AND THE FIX
#
# This gates PRs from contributors who did not write the schema, so an error
# says which file, which field, and what would make it pass. "Invalid" on its
# own sends people to read source.
#
# TIER 'absent' IS CHECKED, NOT ASSUMED
#
# An entry saying john does not support an algorithm, while also naming a john
# format, is a contradiction that would otherwise sit there looking populated.
#
#-----------------------------------------------------------------------
# Generated by Claude Opus 5 on 2026-08-29

use strict;
use warnings;

use File::Basename qw(basename);
use FindBin qw($RealBin);
use Getopt::Long qw(GetOptions);
use YAML::XS ();

my $PROG = basename($0);
my $ROOT = "$RealBin/..";

sub usage {
    print STDERR <<"END_USAGE";

Usage: $PROG [options]

   --algorithms DIR  curated entries (default: data/algorithms)
   --tools DIR       generated inventories (default: data/tools)
   -q, --quiet       errors only; no summary
   -v, --verbose     per-tool coverage breakdown (repeatable)
   -h, --help        this help

   Checks every data/algorithms/*.yaml for shape, and cross-references every
   identifier it names against the generated tool inventories.

   Exit 0 clean, 1 validation errors found, 2 usage or missing inventories.

END_USAGE
    return;
}

my ($algdir, $tooldir, $quiet, $help);
my $verbose = 0;

GetOptions(
    'algorithms=s' => \$algdir,
    'tools=s'      => \$tooldir,
    'q|quiet'      => \$quiet,
    'v|verbose+'   => \$verbose,
    'h|help'       => \$help,
) or do { usage(); exit 2 };

if ($help) { usage(); exit 0 }

$algdir  //= "$ROOT/data/algorithms";
$tooldir //= "$ROOT/data/tools";

#-----------------------------------------------------------------------
# Known vocabulary. Kept beside the checks that use it so the two cannot drift.

my @TIERS      = qw(vector upstream asserted absent);
my %IS_TIER    = map { $_ => 1 } @TIERS;
my %IS_STATUS  = map { $_ => 1 } qw(ok needs-review);

my %TOP_KEY = map { $_ => 1 } qw(
    id name aliases expression john_dynamic_expr category status
    tools vectors legacy notes
);

my %TOOL_KEY = (
    hashcat => { map { $_ => 1 } qw(modes verified verified_at verified_with note) },
    john    => { map { $_ => 1 } qw(cpu gpu verified verified_at verified_with note) },
    mdxfind => { map { $_ => 1 } qw(types iterations verified verified_at verified_with note) },
    crack   => { map { $_ => 1 } qw(supported note) },
);

# Which key in each tool block holds the identifiers to cross-reference.
my %IDENT_KEYS = (
    hashcat => ['modes'],
    john    => ['cpu', 'gpu'],
    mdxfind => ['types'],
);

my (@errors, @warnings);

sub err  { push @errors,   sprintf(shift, @_) }
sub warn_ { push @warnings, sprintf(shift, @_) }

#-----------------------------------------------------------------------
# Load the generated inventories. Without these there is nothing to check
# against, so a missing one is fatal rather than a skipped check.

sub load_inventory {
    my ($file, $listkey) = @_;
    -r $file or do {
        print STDERR "$PROG: cannot read $file -- run the extractor first.\n";
        exit 2;
    };
    my $d = eval { YAML::XS::LoadFile($file) };
    if (!$d || $@) {
        print STDERR "$PROG: $file did not parse as YAML: $@\n";
        exit 2;
    }
    return ($d, $d->{$listkey} || []);
}

my ($hc_doc, $hc_list) = load_inventory("$tooldir/hashcat.yaml", 'modes');
my ($jn_doc, $jn_list) = load_inventory("$tooldir/john.yaml",    'formats');
my ($mx_doc, $mx_list) = load_inventory("$tooldir/mdxfind.yaml", 'types');

my %HC_MODE = map { $_->{mode} => $_ } @$hc_list;
my %JN_FMT  = map { $_->{label} => $_ } @$jn_list;

# Dynamics that exist in the build but are switched off by dynamic_disabled.conf.
# Naming one is legitimate - the format is real and a host can re-enable it -
# so it validates, but it is counted and reported so nobody is surprised when
# "john --format=dynamic_81" says no such format on a default install.
my %JN_DISABLED = map { $_ => 1 } @{ $jn_doc->{disabled_dynamic} || [] };
my %used_disabled;
my %MX_TYPE = map { $_->{name} => $_ } @$mx_list;

# mdxfind is also addressable by index (e1), which the old sheet sometimes used.
my %MX_INDEX = map { $_->{index} => $_ } @$mx_list;

# Which inventory entries any algorithm file actually references. Drives the
# coverage report, which is the number this project exists to move.
my (%hit_hc, %hit_jn, %hit_mx);

#-----------------------------------------------------------------------
# Walk the curated entries.

opendir(my $dh, $algdir) or do {
    print STDERR "$PROG: cannot read $algdir: $!\n";
    exit 2;
};
my @files = sort grep { /\.yaml$/ } readdir $dh;
closedir $dh;

my %seen_id;
my $entries = 0;

for my $file (@files) {
    my $path = "$algdir/$file";
    my $stem = $file; $stem =~ s/\.yaml$//;

    my $d = eval { YAML::XS::LoadFile($path) };
    if ($@ || !defined $d) {
        # YAML::XS puts the useful part ("found character that cannot start
        # any token", with a line number) several lines into its message, so
        # keep the first few lines flattened rather than just the first.
        my $why = $@ || 'empty file';
        $why =~ s/\s+/ /g;
        $why = substr($why, 0, 200);
        err("%s: does not parse as YAML: %s", $file, $why);
        next;
    }
    if (ref $d ne 'HASH') {
        err("%s: top level must be a mapping, got %s", $file, (ref $d || 'a scalar'));
        next;
    }
    $entries++;

    # --- identity -----------------------------------------------------
    my $id = $d->{id};
    if (!defined $id || !length $id) {
        err("%s: missing required key 'id'", $file);
    }
    elsif ($id ne $stem) {
        err("%s: id '%s' does not match the filename; rename the file to %s.yaml or fix id",
            $file, $id, $id);
    }
    elsif ($id !~ /^[a-z0-9][a-z0-9._-]*$/) {
        err("%s: id '%s' must be lowercase alphanumeric with . _ or -", $file, $id);
    }
    elsif ($seen_id{$id}++) {
        err("%s: duplicate id '%s'", $file, $id);
    }

    err("%s: missing required key 'name'", $file)
        unless defined $d->{name} && length $d->{name};

    for my $k (sort keys %$d) {
        err("%s: unknown top-level key '%s'", $file, $k) unless $TOP_KEY{$k};
    }

    if (defined $d->{status} && !$IS_STATUS{ $d->{status} }) {
        err("%s: status '%s' is not one of: %s", $file, $d->{status},
            join(', ', sort keys %IS_STATUS));
    }

    # --- tools --------------------------------------------------------
    my $tools = $d->{tools};
    if (defined $tools) {
        if (ref $tools ne 'HASH') {
            err("%s: 'tools' must be a mapping", $file);
        }
        else {
            for my $tool (sort keys %$tools) {
                if (!$TOOL_KEY{$tool}) {
                    err("%s: unknown tool '%s'; known: %s", $file, $tool,
                        join(', ', sort keys %TOOL_KEY));
                    next;
                }
                my $blk = $tools->{$tool};
                if (ref $blk ne 'HASH') {
                    err("%s: tools.%s must be a mapping", $file, $tool);
                    next;
                }

                for my $k (sort keys %$blk) {
                    err("%s: unknown key 'tools.%s.%s'", $file, $tool, $k)
                        unless $TOOL_KEY{$tool}{$k};
                }

                if (defined $blk->{iterations}
                    && $blk->{iterations} !~ /^[1-9][0-9]*$/) {
                    err("%s: tools.%s.iterations '%s' must be a positive integer",
                        $file, $tool, $blk->{iterations});
                }

                my $tier = $blk->{verified};
                if (defined $tier && !$IS_TIER{$tier}) {
                    err("%s: tools.%s.verified '%s' is not one of: %s",
                        $file, $tool, $tier, join(', ', @TIERS));
                }

                if (defined $blk->{verified_at}
                    && $blk->{verified_at} !~ /^\d{4}-\d{2}-\d{2}$/) {
                    err("%s: tools.%s.verified_at '%s' is not YYYY-MM-DD",
                        $file, $tool, $blk->{verified_at});
                }

                # A claim of 'vector' with nothing to verify against is the
                # one tier that must never be taken on trust.
                if (defined $tier && $tier eq 'vector'
                    && !(ref $d->{vectors} eq 'ARRAY' && @{ $d->{vectors} })) {
                    err("%s: tools.%s.verified is 'vector' but the entry has no vectors",
                        $file, $tool);
                }

                # Identifier cross-reference, the point of this script.
                my $named = 0;
                for my $key (@{ $IDENT_KEYS{$tool} || [] }) {
                    my $vals = $blk->{$key} or next;
                    if (ref $vals ne 'ARRAY') {
                        err("%s: tools.%s.%s must be a list", $file, $tool, $key);
                        next;
                    }
                    $named += scalar @$vals;

                    for my $v (@$vals) {
                        if ($tool eq 'hashcat') {
                            if ($v !~ /^\d+$/) {
                                err("%s: hashcat mode '%s' is not a number", $file, $v);
                            }
                            elsif (!exists $HC_MODE{ $v + 0 }) {
                                err("%s: hashcat mode %s does not exist in %s",
                                    $file, $v, $hc_doc->{version});
                            }
                            else { $hit_hc{ $v + 0 } = 1 }
                        }
                        elsif ($tool eq 'john') {
                            my $f = $JN_FMT{$v};
                            if (!$f && $JN_DISABLED{$v}) {
                                # Real format, disabled by config, not an error.
                                # NOT counted in %hit_jn: coverage is measured
                                # against the formats john actually loaded, and
                                # mixing a disabled label into that numerator
                                # would let coverage exceed the denominator.
                                $used_disabled{$v} = 1;
                            }
                            elsif (!$f) {
                                err("%s: john format '%s' does not exist in %s",
                                    $file, $v, $jn_doc->{version});
                            }
                            else {
                                $hit_jn{$v} = 1;
                                my $dev = $f->{device} // 'cpu';
                                if ($key eq 'cpu' && $dev ne 'cpu') {
                                    err("%s: john format '%s' is a %s build; list it under tools.john.gpu",
                                        $file, $v, $dev);
                                }
                                if ($key eq 'gpu' && $dev eq 'cpu') {
                                    err("%s: john format '%s' is a CPU format; list it under tools.john.cpu",
                                        $file, $v);
                                }
                            }
                        }
                        elsif ($tool eq 'mdxfind') {
                            if (exists $MX_TYPE{$v})      { $hit_mx{$v} = 1 }
                            elsif (exists $MX_INDEX{$v})  {
                                err("%s: mdxfind '%s' is an index; use the type name '%s'",
                                    $file, $v, $MX_INDEX{$v}{name});
                            }
                            else {
                                err("%s: mdxfind type '%s' does not exist in %s",
                                    $file, $v, $mx_doc->{version});
                            }
                        }
                    }
                }

                # 'absent' means the tool cannot do this. Naming an identifier
                # anyway is a contradiction, not extra information.
                if (defined $tier && $tier eq 'absent' && $named) {
                    err("%s: tools.%s.verified is 'absent' but %d identifier(s) are listed",
                        $file, $tool, $named);
                }
            }
        }
    }

    # --- vectors ------------------------------------------------------
    if (defined $d->{vectors}) {
        if (ref $d->{vectors} ne 'ARRAY') {
            err("%s: 'vectors' must be a list", $file);
        }
        else {
            my $i = 0;
            for my $v (@{ $d->{vectors} }) {
                $i++;
                if (ref $v ne 'HASH') {
                    err("%s: vectors[%d] must be a mapping", $file, $i);
                    next;
                }
                err("%s: vectors[%d] is missing 'hash'", $file, $i)
                    unless defined $v->{hash} && length $v->{hash};
                err("%s: vectors[%d] is missing 'pass'", $file, $i)
                    unless defined $v->{pass};
            }
        }
    }
}

#-----------------------------------------------------------------------
# Report.

print STDERR "- $_\n" for @warnings;

if (@errors) {
    print STDERR "- Error: $_\n" for @errors;
}

unless ($quiet) {
    printf STDERR "\n- Inventories: hashcat %d modes (%s), john %d formats (%s), mdxfind %d types (%s)\n",
        scalar(@$hc_list), $hc_doc->{version},
        scalar(@$jn_list), $jn_doc->{version},
        scalar(@$mx_list), $mx_doc->{version};

    printf STDERR "- Entries:     %d file(s) in %s\n", $entries, $algdir;

    my $pc = sub {
        my ($n, $d) = @_;
        return $d ? sprintf('%.1f%%', 100 * $n / $d) : 'n/a';
    };

    printf STDERR "- Coverage:    hashcat %d/%d (%s)  john %d/%d (%s)  mdxfind %d/%d (%s)\n",
        scalar(keys %hit_hc), scalar(@$hc_list), $pc->(scalar(keys %hit_hc), scalar(@$hc_list)),
        scalar(keys %hit_jn), scalar(@$jn_list), $pc->(scalar(keys %hit_jn), scalar(@$jn_list)),
        scalar(keys %hit_mx), scalar(@$mx_list), $pc->(scalar(keys %hit_mx), scalar(@$mx_list));

    if ($verbose) {
        my @unmapped = sort { $a <=> $b } grep { !$hit_hc{$_} } map { $_->{mode} } @$hc_list;
        printf STDERR "-   hashcat modes with no entry: %d (first: %s)\n",
            scalar(@unmapped), join(', ', @unmapped[0 .. ($#unmapped > 9 ? 9 : $#unmapped)]);
    }

    if (%used_disabled) {
        printf STDERR "- Note:        %d john dynamic(s) named by entries are disabled in dynamic_disabled.conf\n",
            scalar(keys %used_disabled);
        printf STDERR "-              (real formats; re-enable them in that file to use them)\n";
    }

    printf STDERR "- %s\n", @errors
        ? sprintf('FAILED: %d error(s)', scalar @errors)
        : 'OK: no errors';
}

exit(@errors ? 1 : 0);
