#!/usr/bin/perl
#-----------------------------------------------------------------------
#
# Name: validate.pl
# Description: check data/algorithms/ against the schema AND against what the
#              tools actually support
# Category: cracking-rosetta validator
#
# Project: cracking-rosetta | Phase: 0 - validation contract
#
#-----------------------------------------------------------------------
# METHODOLOGY AND WHY THESE CHOICES
#
# WHY THIS IS NOT A JSON SCHEMA VALIDATOR
#
# schema/algorithm.schema.json describes the SHAPE of an entry, and that is
# worth having for editors and outside consumers. It cannot express the checks
# that actually matter here, all of which are cross-references into the
# generated inventories:
#
#   - does hashcat mode 2811 exist in THIS hashcat?
#   - does dynamic_12 exist in THIS john, and is it really a CPU format?
#   - does MD5-MD5SALTMD5PASS exist in THIS mdxfind?
#
# A curated mapping that names an identifier no installed tool has is the
# single most likely defect in this repository - it is exactly what happens
# when upstream renames or retires something and the rosetta is not updated.
# That is the defect the old spreadsheet accumulated for three years. So the
# cross-reference is the point of this script, and the shape checks are done
# here too rather than in two places that could disagree.
#
# EVERY ERROR NAMES THE FILE AND THE FIX
#
# This gates PRs from contributors who did not write the schema, so an error
# says which file, which field, and what would make it pass. "Invalid" on its
# own sends people to read source.
#
# TIER 'absent' IS CHECKED, NOT ASSUMED
#
# An entry saying john does not support an algorithm, while also naming a john
# format, is a contradiction that would otherwise sit there looking populated.
#
#-----------------------------------------------------------------------
# Generated by Claude Opus 5 on 2026-08-29

use strict;
use warnings;

use File::Basename qw(basename);
use FindBin qw($RealBin);
use Getopt::Long qw(GetOptions);
use YAML::XS ();

my $PROG = basename($0);
my $ROOT = "$RealBin/..";

sub usage {
    print STDERR <<"END_USAGE";

Usage: $PROG [options]

   --algorithms DIR  curated entries (default: data/algorithms)
   --tools DIR       generated inventories (default: data/tools)
   --only ID         report only errors that concern this entry (repeatable)
   --changed [REF]   report only errors that concern entries you have changed.
                     With no REF: whatever git says is modified, staged or
                     untracked right now. With a REF (e.g. --changed main):
                     that, plus everything the branch changed since REF.
   -q, --quiet       errors only; no summary
   -v, --verbose     per-tool coverage breakdown (repeatable)
   -h, --help        this help

   Checks every data/algorithms/*.yaml for shape, and cross-references every
   identifier it names against the generated tool inventories.

   --only and --changed narrow the REPORT, never the checking. The whole
   corpus is always loaded, because the rules that matter most are not about
   one file: an expression collision is about every entry that claims it, and
   a relation is by definition about two. Scoping tells you which errors are
   YOURS, and says separately how many were already there.

   Exit 0 clean, 1 validation errors found in scope, 2 usage or missing
   inventories.

END_USAGE
    return;
}

my ($algdir, $tooldir, $quiet, $help, $changed);
my @only;
my $verbose = 0;

GetOptions(
    'algorithms=s' => \$algdir,
    'tools=s'      => \$tooldir,
    'only=s'       => \@only,
    'changed:s'    => \$changed,
    'q|quiet'      => \$quiet,
    'v|verbose+'   => \$verbose,
    'h|help'       => \$help,
) or do { usage(); exit 2 };

if ($help) { usage(); exit 0 }

$algdir  //= "$ROOT/data/algorithms";
$tooldir //= "$ROOT/data/tools";

#-----------------------------------------------------------------------
# Scope: which entries the caller wants to hear about.
#
# Empty means "all of them", which is the gate's behavior and what CI runs.

my %scope = map { $_ => 1 } @only;

if (defined $changed) {
    # git names paths from the repo root, so ask git where that is rather
    # than assuming this script sits two levels down from it.
    chomp(my $top = `git -C @{[quotemeta $ROOT]} rev-parse --show-toplevel 2>/dev/null`);
    if (!length $top) {
        print STDERR "$PROG: --changed needs a git repository.\n";
        exit 2;
    }

    my @paths;
    # Working tree, index and untracked: what a contributor has in hand right
    # now, before anything is committed.
    for my $line (`git -C @{[quotemeta $top]} status --porcelain 2>/dev/null`) {
        chomp $line;
        # "XY path" or "XY old -> new"; the new name is the one that exists.
        next unless $line =~ /^..\s+(.*)$/;
        my $pth = $1;
        $pth = $1 if $pth =~ /->\s*(.*)$/;
        $pth =~ s/^"|"$//g;
        push @paths, $pth;
    }
    # And, when a ref was named, everything the branch changed since it
    # diverged -- three dots, so an unrelated commit on main is not counted
    # as part of this contribution.
    if (length $changed) {
        push @paths, split /\n/,
            `git -C @{[quotemeta $top]} diff --name-only @{[quotemeta $changed]}...HEAD 2>/dev/null`;
    }

    for my $pth (@paths) {
        next unless $pth =~ m{(?:^|/)data/algorithms/([^/]+)\.yaml$};
        $scope{$1} = 1;
    }

    unless (%scope) {
        print STDERR "$PROG: nothing changed under data/algorithms"
                   . (length $changed ? " since $changed" : '') . ".\n";
    }
}

my $scoped = %scope ? 1 : 0;

#-----------------------------------------------------------------------
# Known vocabulary. Kept beside the checks that use it so the two cannot drift.

my @TIERS      = qw(vector upstream asserted absent);
my %IS_TIER    = map { $_ => 1 } @TIERS;
my %IS_STATUS  = map { $_ => 1 } qw(ok needs-review merged);

# The serializations a test vector can be written in. 'native' is the form the
# producing system itself stores; the three tool names are each tool's own
# spelling of the same credential. Fixed vocabulary, like the tiers: a fifth
# value changes what every row means to a consumer.
my %FORM = map { $_ => 1 } qw(native hashcat john mdxfind);

# A tombstone (status: merged) is a redirect, not an entry: its content moved
# to the survivor and the file survives only so the published id keeps
# resolving. So it may carry nothing that asserts anything -- these keys are
# the survivor's job, and a tombstone holding a stale copy of them is exactly
# the drift the merge was meant to remove.
my @TOMB_FORBIDDEN = qw(
    expression john_dynamic_expr expression_proof denotation category
    application application_version tools vectors no_vector aliases legacy
);

my %TOP_KEY = map { $_ => 1 } qw(
    id name aliases expression john_dynamic_expr expression_proof denotation
    category application application_version status merged_into
    tools relations vectors no_vector legacy notes
);

my %EXPR_PROOF_KEY = map { $_ => 1 } qw(verified verified_at verified_with note);
my %DENOTATION_KEY = map { $_ => 1 } qw(text source note);
my %IS_DENOT_SOURCE = map { $_ => 1 }
    qw(sheet mdxfind hashcat john hashpipe hashes.org human);

my %NO_VECTOR_KEY = map { $_ => 1 } qw(reason note measured_at measured_with);

# Why an entry carries no vectors, where that is a settled fact rather than a
# backlog. The distinction is the whole point: GAPS.md asks the world for a
# vector for every entry that has none, and for some entries that request is
# not merely unanswered but unanswerable. 'impossible' means the type emits
# nothing at all, so no plaintext has a hash to be paired with; 'withheld'
# means a vector exists and recording it HERE would assert something false,
# which is a curator's decision and not a contributor's data. An entry with
# neither block nor vectors stays an ordinary gap and is still asked for.
my %IS_NO_VECTOR_REASON = map { $_ => 1 } qw(impossible withheld);

my %IS_CATEGORY = map { $_ => 1 } qw(
    primitive composite iterated encoding application protocol kdf
);

# The relation vocabulary. See ACTION-PLAN.md section 11 for what each edge
# means; the short version is that 'kind' says what the relationship is and
# 'distinction' says why both entries nonetheless exist.
my %IS_REL_KIND = map { $_ => 1 } qw(
    same-computation encodes input-encoding iterates truncates
    collides-on-subset duplicate-of
);
# 'naming' is deliberately in this list and not in %JOINS_EXPRESSION's
# reasoning: it is the answer a curator gives when a proposed duplicate turns
# out to be two tool names for one computation and both names are worth a row.
# It distinguishes nothing about the algorithm, which is why it is separate
# from 'none' -- 'none' says a merge is still owed, 'naming' says it was
# considered and declined.
my %IS_REL_DISTINCTION = map { $_ => 1 } qw(
    application encoding input-encoding iteration truncation
    salt-convention naming none
);

# An edge of one of these kinds is what makes two entries allowed to share an
# expression: it says the shared computation is deliberate and accounted for.
my %JOINS_EXPRESSION = map { $_ => 1 } qw(same-computation encodes duplicate-of);

# What each kind mirrors to on the other entry. Every relation is symmetric --
# an unmirrored edge is a half-truth that only one of the two files tells.
my %REL_MIRROR = (
    'same-computation'  => 'same-computation',
    'encodes'           => 'encodes',
    'input-encoding'    => 'input-encoding',
    'collides-on-subset'=> 'collides-on-subset',
    'duplicate-of'      => 'duplicate-of',
    'iterates'          => 'iterates',
    'truncates'         => 'truncates',
);

# no_round_trip on every one of them: it is a statement about whether THIS
# entry's vectors can exercise THAT tool's identifier, which every column can
# fail to do for its own reasons.
my %TOOL_KEY = (
    hashcat  => { map { $_ => 1 } qw(modes verified verified_at verified_with note no_round_trip) },
    john     => { map { $_ => 1 } qw(cpu gpu verified verified_at verified_with note no_round_trip) },
    mdxfind  => { map { $_ => 1 } qw(types iterations verified verified_at verified_with note no_round_trip) },
    # No iterations: hashpipe's suffix reports the algorithm's own round count
    # read out of the hash where mdxfind's counts outer re-hashing driven by
    # -i, so the two are different quantities. See the schema.
    hashpipe => { map { $_ => 1 } qw(types verified verified_at verified_with note no_round_trip) },
    crack    => { map { $_ => 1 } qw(supported note no_round_trip) },
);

my %NO_RT_KEY = map { $_ => 1 } qw(reason note measured_at measured_with);
# Why this entry's vectors cannot promote this tool's mapping. Measured, not
# assumed: 'different-algorithm' means the tool computes something else under
# the identifier, so a failure to crack this row's vector says nothing about
# the mapping; 'emits-nothing' means the tool's type produces no digest for
# any input at all.
my %IS_NO_RT_REASON = map { $_ => 1 } qw(different-algorithm emits-nothing not-comparable);

# Which key in each tool block holds the identifiers to cross-reference.
my %IDENT_KEYS = (
    hashcat  => ['modes'],
    john     => ['cpu', 'gpu'],
    mdxfind  => ['types'],
    hashpipe => ['types'],
);

my (@errors, @warnings);

# Every error records which entries it is about, so --only and --changed can
# tell a contributor's own mistakes from the ones that were already there.
# @ABOUT is set by whichever loop is running; an error with an empty @ABOUT is
# corpus-wide and is always reported.
our @ABOUT = ();
sub err  { push @errors,   { msg => sprintf(shift, @_), about => [@ABOUT] } }
sub warn_ { push @warnings, sprintf(shift, @_) }

# in_scope($error) - does this error concern anything the caller asked about?
sub in_scope {
    my ($e) = @_;
    return 1 unless $scoped;
    return 1 unless @{ $e->{about} };
    for my $id (@{ $e->{about} }) {
        return 1 if $scope{$id};
    }
    return 0;
}

#-----------------------------------------------------------------------
# Load the generated inventories. Without these there is nothing to check
# against, so a missing one is fatal rather than a skipped check.

sub load_inventory {
    my ($file, $listkey) = @_;
    -r $file or do {
        print STDERR "$PROG: cannot read $file -- run the extractor first.\n";
        exit 2;
    };
    my $d = eval { YAML::XS::LoadFile($file) };
    if (!$d || $@) {
        print STDERR "$PROG: $file did not parse as YAML: $@\n";
        exit 2;
    }
    return ($d, $d->{$listkey} || []);
}

my ($hc_doc, $hc_list) = load_inventory("$tooldir/hashcat.yaml", 'modes');
my ($jn_doc, $jn_list) = load_inventory("$tooldir/john.yaml",    'formats');
my ($mx_doc, $mx_list) = load_inventory("$tooldir/mdxfind.yaml", 'types');
my ($hp_doc, $hp_list) = load_inventory("$tooldir/hashpipe.yaml", 'types');

my %HC_MODE = map { $_->{mode} => $_ } @$hc_list;
my %JN_FMT  = map { $_->{label} => $_ } @$jn_list;

# Dynamics that exist in the build but are switched off by dynamic_disabled.conf.
# Naming one is legitimate - the format is real and a host can re-enable it -
# so it validates, but it is counted and reported so nobody is surprised when
# "john --format=dynamic_81" says no such format on a default install.
my %JN_DISABLED = map { $_ => 1 } @{ $jn_doc->{disabled_dynamic} || [] };
my %used_disabled;
my %MX_TYPE = map { $_->{name} => $_ } @$mx_list;
my %HP_TYPE = map { $_->{name} => $_ } @$hp_list;

# Types whose own self-test hashpipe fails. Naming one is not an error -- the
# type exists and a reader arriving by that name must land somewhere -- but it
# cannot be at tier 'vector', because the tool cannot reproduce its own vector
# for it, let alone ours. Measured 2026-09-03: BMW224 and BMW256, and they
# return a DIFFERENT digest on every invocation, which is uninitialized state
# rather than a wrong constant.
my %HP_SELFTEST_FAIL =
    map { $_->{name} => 1 } grep { ($_->{selftest} // '') eq 'fail' } @$hp_list;

# mdxfind is also addressable by index (e1), which the old sheet sometimes used.
my %MX_INDEX = map { $_->{index} => $_ } @$mx_list;

# Which inventory entries any algorithm file actually references. Drives the
# coverage report, which is the number this project exists to move.
my (%hit_hc, %hit_jn, %hit_mx, %hit_hp);

#-----------------------------------------------------------------------
# Walk the curated entries.

opendir(my $dh, $algdir) or do {
    print STDERR "$PROG: cannot read $algdir: $!\n";
    exit 2;
};
my @files = sort grep { /\.yaml$/ } readdir $dh;
closedir $dh;

my %seen_id;
# Tallies for --verbose. Counting here rather than in a separate status script
# because this pass already loads and parses every entry: any other tool that
# reported these would be a second implementation of the same walk, free to
# disagree with the gate about what the corpus contains.
my %tier_count;      # tool tier -> n
my %expr_tier;       # expression_proof.verified -> n
my ($n_expr, $n_denot, $n_novec) = (0, 0, 0);
my %novec_reason;   # no_vector.reason -> n; the subset that is NOT a backlog

# An 'absent' claim is a MEASUREMENT against a particular build, and it expires
# when that tool gains types. Measured 2026-09-05: every one of the 343 mdxfind
# absences here had been established against RCS 1.545 with 1002 types, while
# data/tools/mdxfind.yaml had already moved to RCS 1.576 with 1027 -- and 19 of
# those absences were wrong, because the 25 indices added between the two builds
# are exactly the john-shaped types several of them named. The claims even said
# so: "if mdxfind gains one, this becomes a mapping". Nothing compared the two
# version strings, so nothing noticed. This does.
my %absent_build;   # tool -> the build string the claim names -> n
my $tombstones = 0;
my %tomb;            # tombstone id -> { into => survivor id, file => ... }
my %by_expression;   # expression -> [ ids ] , for the collision rule
my @rel_edges;       # every edge seen, resolved after the loop
my $entries = 0;

for my $file (@files) {
    my $path = "$algdir/$file";
    my $stem = $file; $stem =~ s/\.yaml$//;
    local @ABOUT = ($stem);

    my $d = eval { YAML::XS::LoadFile($path) };
    if ($@ || !defined $d) {
        # YAML::XS puts the useful part ("found character that cannot start
        # any token", with a line number) several lines into its message, so
        # keep the first few lines flattened rather than just the first.
        my $why = $@ || 'empty file';
        $why =~ s/\s+/ /g;
        $why = substr($why, 0, 200);
        err("%s: does not parse as YAML: %s", $file, $why);
        next;
    }
    if (ref $d ne 'HASH') {
        err("%s: top level must be a mapping, got %s", $file, (ref $d || 'a scalar'));
        next;
    }
    $entries++;

    # --- tombstone ----------------------------------------------------
    #
    # Decided 2026-08-30: a merged-away id keeps its file as a tombstone
    # rather than 404ing, because the id is a filename stem, a URL fragment
    # and the key in dist/rosetta.csv, and a consumer that joins on it should
    # be told where the row went rather than told nothing. A tombstone is
    # counted separately everywhere below: it is not a 785th algorithm, and
    # letting it into the coverage denominators would make every merge look
    # like a small regression.
    my $is_tomb = defined $d->{status} && $d->{status} eq 'merged';
    $tombstones++ if $is_tomb;

    unless ($is_tomb) {
        $n_expr++  if defined $d->{expression} && length $d->{expression};
        $n_denot++ if ref $d->{denotation} eq 'HASH';
        $n_novec++ unless ref $d->{vectors} eq 'ARRAY' && @{ $d->{vectors} };
        $novec_reason{ $d->{no_vector}{reason} // '?' }++
            if ref $d->{no_vector} eq 'HASH';
        for my $t (qw(hashcat john mdxfind hashpipe)) {
            my $b = $d->{tools}{$t} or next;
            next unless ($b->{verified} // '') eq 'absent';
            $absent_build{$t}{ $b->{verified_with} // '(unrecorded)' }++;
        }
        $expr_tier{ $d->{expression_proof}{verified} // '?' }++
            if ref $d->{expression_proof} eq 'HASH';
        for my $t (qw(hashcat john mdxfind hashpipe crack)) {
            my $b = $d->{tools}{$t};
            next unless ref $b eq 'HASH' && defined $b->{verified};
            $tier_count{ $b->{verified} }++;
        }
    }

    # --- identity -----------------------------------------------------
    my $id = $d->{id};
    if (!defined $id || !length $id) {
        err("%s: missing required key 'id'", $file);
    }
    elsif ($id ne $stem) {
        err("%s: id '%s' does not match the filename; rename the file to %s.yaml or fix id",
            $file, $id, $id);
    }
    elsif ($id !~ /^[a-z0-9][a-z0-9._-]*$/) {
        err("%s: id '%s' must be lowercase alphanumeric with . _ or -", $file, $id);
    }
    elsif ($seen_id{$id}++) {
        err("%s: duplicate id '%s'", $file, $id);
    }

    err("%s: missing required key 'name'", $file)
        unless defined $d->{name} && length $d->{name};

    for my $k (sort keys %$d) {
        err("%s: unknown top-level key '%s'", $file, $k) unless $TOP_KEY{$k};
    }

    if (defined $d->{status} && !$IS_STATUS{ $d->{status} }) {
        err("%s: status '%s' is not one of: %s", $file, $d->{status},
            join(', ', sort keys %IS_STATUS));
    }

    # --- tombstone shape ----------------------------------------------
    #
    # The two halves of the rule are stated together so neither can be met
    # alone: 'merged' without a destination is a dead end, and a destination
    # without 'merged' is a live entry quietly claiming to be a redirect.
    my $into = $d->{merged_into};
    if ($is_tomb) {
        if (!defined $into || !length $into) {
            err("%s: status 'merged' needs merged_into naming the survivor", $file);
        }
        elsif ($into eq ($id // '')) {
            err("%s: merged_into names itself", $file);
        }
        else {
            $tomb{$id} = { into => $into, file => $file } if defined $id;
        }

        for my $k (@TOMB_FORBIDDEN) {
            next unless exists $d->{$k};
            err("%s: a tombstone (status: merged) must not carry '%s' -- fold "
              . "it into %s.yaml and delete it here", $file, $k, $into // 'the survivor');
        }

        # The redirect is stated twice on purpose, as a scalar a machine can
        # follow and as an edge the relation checks can mirror onto the
        # survivor. Requiring both is what stops a tombstone from pointing
        # somewhere the survivor has never heard of.
        my $edge = grep { ref $_ eq 'HASH'
                          && ($_->{kind}  // '') eq 'duplicate-of'
                          && ($_->{entry} // '') eq ($into // '') }
                   @{ ref $d->{relations} eq 'ARRAY' ? $d->{relations} : [] };
        err("%s: a tombstone needs a duplicate-of relation to %s as well as "
          . "merged_into (tools/relate.pl writes both sides)", $file, $into // '?')
            if defined $into && length $into && !$edge;
    }
    elsif (defined $into) {
        err("%s: merged_into is only legal with status: merged", $file);
    }

    # --- expression_proof ---------------------------------------------
    #
    # expression: is a gate: rule 3 below fails a build where two entries
    # claim the same one. A field with that much authority must say how it
    # was established, the same way every per-tool mapping does -- otherwise
    # a transcription and a round-trip are indistinguishable and the first
    # awkward collision becomes an argument for weakening the rule.
    my $has_expr  = defined $d->{expression} && length $d->{expression};
    my $proof     = $d->{expression_proof};
    my $expr_tier;

    if (defined $proof) {
        if (ref $proof ne 'HASH') {
            err("%s: 'expression_proof' must be a mapping", $file);
        }
        else {
            for my $k (sort keys %$proof) {
                err("%s: unknown key 'expression_proof.%s'", $file, $k)
                    unless $EXPR_PROOF_KEY{$k};
            }
            $expr_tier = $proof->{verified};
            if (!defined $expr_tier || !length $expr_tier) {
                err("%s: expression_proof needs a 'verified' tier", $file);
            }
            elsif (!$IS_TIER{$expr_tier}) {
                err("%s: expression_proof.verified '%s' is not one of: %s",
                    $file, $expr_tier, join(', ', @TIERS));
            }

            if (defined $proof->{verified_at}
                && $proof->{verified_at} !~ /^\d{4}-\d{2}-\d{2}$/) {
                err("%s: expression_proof.verified_at '%s' is not YYYY-MM-DD",
                    $file, $proof->{verified_at});
            }

            # Same rule the tool blocks get: 'vector' means something was
            # round-tripped, and there is nothing to round-trip against.
            if (defined $expr_tier && $expr_tier eq 'vector'
                && !(ref $d->{vectors} eq 'ARRAY' && @{ $d->{vectors} })) {
                err("%s: expression_proof.verified is 'vector' but the entry "
                  . "has no vectors", $file);
            }

            # 'absent' is the settled decision that this algorithm has no
            # expression in the dynamic language. Carrying one anyway is the
            # entry contradicting itself.
            if (defined $expr_tier && $expr_tier eq 'absent' && $has_expr) {
                err("%s: expression_proof.verified is 'absent' but an "
                  . "expression is recorded", $file);
            }
        }
    }

    # Nothing lands untiered. This is what stops the field drifting back to
    # a bare string whose provenance nobody can reconstruct.
    if ($has_expr && !defined $proof) {
        err("%s: 'expression' is set but there is no expression_proof tier",
            $file);
    }

    if (defined $d->{john_dynamic_expr} && length $d->{john_dynamic_expr}
        && !$has_expr) {
        err("%s: 'john_dynamic_expr' is set without an 'expression'", $file);
    }

    # --- denotation ---------------------------------------------------
    my $den = $d->{denotation};
    if (defined $den) {
        if (ref $den ne 'HASH') {
            err("%s: 'denotation' must be a mapping", $file);
        }
        else {
            for my $k (sort keys %$den) {
                err("%s: unknown key 'denotation.%s'", $file, $k)
                    unless $DENOTATION_KEY{$k};
            }
            err("%s: denotation needs a 'text'", $file)
                unless defined $den->{text} && length $den->{text};
            if (defined $den->{source} && !$IS_DENOT_SOURCE{ $den->{source} }) {
                err("%s: denotation.source '%s' is not one of: %s", $file,
                    $den->{source}, join(', ', sort keys %IS_DENOT_SOURCE));
            }
            # denotation is the fallback for an entry with no expression. An
            # entry with both says the same thing twice at two strengths, and
            # a reader has no way to know which one to believe.
            err("%s: denotation is set alongside an expression; denotation is "
              . "for entries that have none", $file) if $has_expr;
        }
    }

    # --- no_vector ------------------------------------------------------
    #
    # GAPS.md tells the world that every entry with no vectors is waiting for
    # one, and names the contribution as "a hash and the plaintext that
    # produces it". For some entries that is not a gap at all: mdxfind's
    # PARALLEL computes nothing -- its case in mdxfind.c increments the hash
    # counter and breaks -- so there is no digest for any plaintext to
    # produce and no amount of equipment will supply one. Asking anyway sends
    # a willing contributor after something that is not there, and the fact
    # that it is not there is exactly what the repository knows and was
    # saying only in prose.
    #
    # So the reason becomes data. It is deliberately NOT a tier: nothing here
    # is promoted, and 'impossible' is not a weaker 'vector'.
    my $novec = $d->{no_vector};
    if (defined $novec) {
        if (ref $novec ne 'HASH') {
            err("%s: 'no_vector' must be a mapping", $file);
        }
        else {
            for my $k (sort keys %$novec) {
                err("%s: unknown key 'no_vector.%s'", $file, $k)
                    unless $NO_VECTOR_KEY{$k};
            }

            my $reason = $novec->{reason};
            if (!defined $reason || !length $reason) {
                err("%s: no_vector needs a 'reason'", $file);
            }
            elsif (!$IS_NO_VECTOR_REASON{$reason}) {
                err("%s: no_vector.reason '%s' is not one of: %s", $file,
                    $reason, join(', ', sort keys %IS_NO_VECTOR_REASON));
            }

            # An unexplained 'impossible' forecloses the question it claims
            # to settle, and is indistinguishable from a shrug. The note is
            # what a later reader audits the claim against.
            err("%s: no_vector needs a 'note' saying what was measured or "
              . "what decision is owed", $file)
                unless defined $novec->{note} && length $novec->{note};

            if (defined $novec->{measured_at}
                && $novec->{measured_at} !~ /^\d{4}-\d{2}-\d{2}$/) {
                err("%s: no_vector.measured_at '%s' is not YYYY-MM-DD",
                    $file, $novec->{measured_at});
            }

            # The one that keeps it honest. A vector arriving later is the
            # good outcome, and it must not leave a stale denial standing
            # beside the thing it denies.
            if (ref $d->{vectors} eq 'ARRAY' && @{ $d->{vectors} }) {
                err("%s: no_vector is set alongside %d vector(s); it is for "
                  . "entries that have none -- drop the block", $file,
                  scalar @{ $d->{vectors} });
            }
        }
    }

    # --- tools --------------------------------------------------------
    my $tools = $d->{tools};
    if (defined $tools) {
        if (ref $tools ne 'HASH') {
            err("%s: 'tools' must be a mapping", $file);
        }
        else {
            for my $tool (sort keys %$tools) {
                if (!$TOOL_KEY{$tool}) {
                    err("%s: unknown tool '%s'; known: %s", $file, $tool,
                        join(', ', sort keys %TOOL_KEY));
                    next;
                }
                my $blk = $tools->{$tool};
                if (ref $blk ne 'HASH') {
                    err("%s: tools.%s must be a mapping", $file, $tool);
                    next;
                }

                for my $k (sort keys %$blk) {
                    err("%s: unknown key 'tools.%s.%s'", $file, $tool, $k)
                        unless $TOOL_KEY{$tool}{$k};
                }

                if (defined $blk->{iterations}
                    && $blk->{iterations} !~ /^[1-9][0-9]*$/) {
                    err("%s: tools.%s.iterations '%s' must be a positive integer",
                        $file, $tool, $blk->{iterations});
                }

                my $tier = $blk->{verified};
                if (defined $tier && !$IS_TIER{$tier}) {
                    err("%s: tools.%s.verified '%s' is not one of: %s",
                        $file, $tool, $tier, join(', ', @TIERS));
                }

                if (defined $blk->{verified_at}
                    && $blk->{verified_at} !~ /^\d{4}-\d{2}-\d{2}$/) {
                    err("%s: tools.%s.verified_at '%s' is not YYYY-MM-DD",
                        $file, $tool, $blk->{verified_at});
                }

                # A claim of 'vector' with nothing to verify against is the
                # one tier that must never be taken on trust.
                if (defined $tier && $tier eq 'vector'
                    && !(ref $d->{vectors} eq 'ARRAY' && @{ $d->{vectors} })) {
                    err("%s: tools.%s.verified is 'vector' but the entry has no vectors",
                        $file, $tool);
                }

                # --- no_round_trip ---------------------------------------
                #
                # GAPS.md sells a claimed-but-unproven mapping as the
                # cheapest contribution there is: the identifier and the
                # vector are both on the row, so "one command decides it".
                # That is only true where the command CAN decide. mdxfind's
                # MD5SPECAM reads a userid off the line and performs zero
                # hash calculations on this row's vector -- which is
                # hashpipe's, for a type of the same name that computes
                # something else -- so running it settles nothing, and the
                # queue was advertising a job that had already been done and
                # had come back inconclusive.
                my $nrt = $blk->{no_round_trip};
                if (defined $nrt) {
                    if (ref $nrt ne 'HASH') {
                        err("%s: tools.%s.no_round_trip must be a mapping",
                            $file, $tool);
                    }
                    else {
                        for my $k (sort keys %$nrt) {
                            err("%s: unknown key 'tools.%s.no_round_trip.%s'",
                                $file, $tool, $k) unless $NO_RT_KEY{$k};
                        }

                        my $reason = $nrt->{reason};
                        if (!defined $reason || !length $reason) {
                            err("%s: tools.%s.no_round_trip needs a 'reason'",
                                $file, $tool);
                        }
                        elsif (!$IS_NO_RT_REASON{$reason}) {
                            err("%s: tools.%s.no_round_trip.reason '%s' is not "
                              . "one of: %s", $file, $tool, $reason,
                                join(', ', sort keys %IS_NO_RT_REASON));
                        }

                        err("%s: tools.%s.no_round_trip needs a 'note' saying "
                          . "what was measured", $file, $tool)
                            unless defined $nrt->{note} && length $nrt->{note};

                        if (defined $nrt->{measured_at}
                            && $nrt->{measured_at} !~ /^\d{4}-\d{2}-\d{2}$/) {
                            err("%s: tools.%s.no_round_trip.measured_at '%s' "
                              . "is not YYYY-MM-DD", $file, $tool,
                                $nrt->{measured_at});
                        }

                        # The contradiction that matters. 'vector' means this
                        # tool DID reproduce one of this entry's vectors, so
                        # a standing statement that it cannot is stale by
                        # definition -- and leaving both would let a reader
                        # pick whichever half they liked.
                        if (defined $tier && $tier eq 'vector') {
                            err("%s: tools.%s is tier 'vector' but carries a "
                              . "no_round_trip block saying this entry's "
                              . "vectors cannot promote it; the round trip "
                              . "happened, so the block comes out",
                                $file, $tool);
                        }

                        # 'absent' says the tool does not support this
                        # algorithm at all. Then there is no identifier for a
                        # vector to fail against and nothing to explain.
                        if (defined $tier && $tier eq 'absent') {
                            err("%s: tools.%s is tier 'absent', so there is no "
                              . "mapping for a vector to promote and "
                              . "no_round_trip has nothing to say", $file,
                                $tool);
                        }
                    }
                }

                # And a block must not say the opposite of its own tier.
                # seed-orphans.pl writes 'NOT REPRODUCED HERE ... the claim
                # is upstream's, not this repository's' on a row it created
                # but could not round-trip. That sentence is true at tier
                # 'upstream' and false at tier 'vector', and a later
                # verification used to promote the tier without withdrawing
                # it: measured 2026-09-02, 24 blocks carried both, and a
                # reader of one of those rows had no way to tell which half
                # to believe. It is a machine-written marker, so testing for
                # it is a lookup rather than a judgment about prose.
                if (defined $tier && $tier eq 'vector'
                    && ($blk->{note} // '') =~ /^NOT REPRODUCED HERE/) {
                    err("%s: tools.%s is tier 'vector' but its note still says "
                      . "NOT REPRODUCED HERE. Re-run verify-vectors.pl --tool %s "
                      . "--only %s, which withdraws the marker on a clean run; "
                      . "if it does not verify, the TIER is the wrong half",
                        $file, $tool, $tool, $d->{id} // '?');
                }

                # Identifier cross-reference, the point of this script.
                my $named = 0;
                for my $key (@{ $IDENT_KEYS{$tool} || [] }) {
                    my $vals = $blk->{$key} or next;
                    if (ref $vals ne 'ARRAY') {
                        err("%s: tools.%s.%s must be a list", $file, $tool, $key);
                        next;
                    }
                    $named += scalar @$vals;

                    for my $v (@$vals) {
                        if ($tool eq 'hashcat') {
                            if ($v !~ /^\d+$/) {
                                err("%s: hashcat mode '%s' is not a number", $file, $v);
                            }
                            elsif (!exists $HC_MODE{ $v + 0 }) {
                                err("%s: hashcat mode %s does not exist in %s",
                                    $file, $v, $hc_doc->{version});
                            }
                            else { $hit_hc{ $v + 0 } = 1 }
                        }
                        elsif ($tool eq 'john') {
                            my $f = $JN_FMT{$v};
                            if (!$f && $JN_DISABLED{$v}) {
                                # Real format, disabled by config, not an error.
                                # NOT counted in %hit_jn: coverage is measured
                                # against the formats john actually loaded, and
                                # mixing a disabled label into that numerator
                                # would let coverage exceed the denominator.
                                $used_disabled{$v} = 1;
                            }
                            elsif (!$f) {
                                err("%s: john format '%s' does not exist in %s",
                                    $file, $v, $jn_doc->{version});
                            }
                            else {
                                $hit_jn{$v} = 1;
                                my $dev = $f->{device} // 'cpu';
                                if ($key eq 'cpu' && $dev ne 'cpu') {
                                    err("%s: john format '%s' is a %s build; list it under tools.john.gpu",
                                        $file, $v, $dev);
                                }
                                if ($key eq 'gpu' && $dev eq 'cpu') {
                                    err("%s: john format '%s' is a CPU format; list it under tools.john.cpu",
                                        $file, $v);
                                }
                            }
                        }
                        elsif ($tool eq 'mdxfind') {
                            if (exists $MX_TYPE{$v})      { $hit_mx{$v} = 1 }
                            elsif (exists $MX_INDEX{$v})  {
                                err("%s: mdxfind '%s' is an index; use the type name '%s'",
                                    $file, $v, $MX_INDEX{$v}{name});
                            }
                            else {
                                err("%s: mdxfind type '%s' does not exist in %s",
                                    $file, $v, $mx_doc->{version});
                            }
                        }
                        elsif ($tool eq 'hashpipe') {
                            if (!exists $HP_TYPE{$v}) {
                                err("%s: hashpipe type '%s' does not exist in %s",
                                    $file, $v, $hp_doc->{version});
                            }
                            else {
                                $hit_hp{$v} = 1;
                                # A type whose own self-test fails cannot
                                # prove anything about an entry. Naming it is
                                # fine -- the type exists and a reader may
                                # arrive by it -- but not at tier vector.
                                if ($HP_SELFTEST_FAIL{$v}
                                 && ($blk->{verified} // '') eq 'vector') {
                                    err("%s: hashpipe type '%s' FAILS its own "
                                      . "self-test in %s, so this block cannot "
                                      . "be at tier 'vector'",
                                        $file, $v, $hp_doc->{version});
                                }
                            }
                        }
                    }
                }

                # 'absent' means the tool cannot do this. Naming an identifier
                # anyway is a contradiction, not extra information.
                if (defined $tier && $tier eq 'absent' && $named) {
                    err("%s: tools.%s.verified is 'absent' but %d identifier(s) are listed",
                        $file, $tool, $named);
                }
            }
        }
    }

    push @{ $by_expression{ $d->{expression} } }, ($id // $stem)
        if defined $d->{expression} && length $d->{expression};

    # --- category -----------------------------------------------------
    if (defined $d->{category} && !$IS_CATEGORY{ $d->{category} }) {
        err("%s: category '%s' is not one of: %s",
            $file, $d->{category}, join(' ', sort keys %IS_CATEGORY));
    }
    if (defined $d->{application} && ($d->{category} // '') ne 'application') {
        warn_("%s: names an application but category is not 'application'", $file);
    }

    # --- relations ----------------------------------------------------
    if (defined $d->{relations}) {
        if (ref $d->{relations} ne 'ARRAY') {
            err("%s: 'relations' must be a list", $file);
        }
        else {
            my $i = 0;
            for my $r (@{ $d->{relations} }) {
                $i++;
                if (ref $r ne 'HASH') {
                    err("%s: relations[%d] must be a mapping", $file, $i);
                    next;
                }
                my ($kind, $to) = ($r->{kind}, $r->{entry});
                if (!defined $kind || !$IS_REL_KIND{$kind}) {
                    err("%s: relations[%d] kind '%s' is not one of: %s",
                        $file, $i, $kind // '(missing)',
                        join(' ', sort keys %IS_REL_KIND));
                    next;
                }
                if (!defined $to || $to !~ /^[a-z0-9][a-z0-9._-]*$/) {
                    err("%s: relations[%d] needs an 'entry' id", $file, $i);
                    next;
                }
                err("%s: relations[%d] points at its own entry", $file, $i)
                    if defined $id && $to eq $id;

                my $dist = $r->{distinction};
                if (defined $dist && !$IS_REL_DISTINCTION{$dist}) {
                    err("%s: relations[%d] distinction '%s' is not one of: %s",
                        $file, $i, $dist, join(' ', sort keys %IS_REL_DISTINCTION));
                }
                # 'none' means nothing separates these two, which is only a
                # coherent thing to say while proposing a merge.
                if (defined $dist && $dist eq 'none' && $kind ne 'duplicate-of') {
                    err("%s: relations[%d] has distinction 'none' but kind '%s'; "
                      . "'none' is only legal with 'duplicate-of'", $file, $i, $kind);
                }
                if ($kind eq 'duplicate-of' && defined $dist && $dist ne 'none') {
                    err("%s: relations[%d] is 'duplicate-of' but claims a "
                      . "distinction '%s'", $file, $i, $dist);
                }
                # The whole point of this kind is to record WHY the agreement
                # is an accident, so an unexplained one is worse than none.
                if ($kind eq 'collides-on-subset'
                    && !(defined $r->{note} && length $r->{note})) {
                    err("%s: relations[%d] is 'collides-on-subset' and must carry "
                      . "a note naming the inputs on which the two agree",
                        $file, $i);
                }
                push @rel_edges, { from => ($id // $stem), to => $to,
                                   kind => $kind, file => $file };
            }
        }
    }

    # --- vectors ------------------------------------------------------
    if (defined $d->{vectors}) {
        if (ref $d->{vectors} ne 'ARRAY') {
            err("%s: 'vectors' must be a list", $file);
        }
        else {
            my $i = 0;
            my %cred;      # credential label -> how many vectors carry it
            my %form_n;    # form value      -> how many vectors carry it
            my %cred_form; # credential+form -> seen, to catch two of a kind
            for my $v (@{ $d->{vectors} }) {
                $i++;
                if (ref $v ne 'HASH') {
                    err("%s: vectors[%d] must be a mapping", $file, $i);
                    next;
                }
                err("%s: vectors[%d] is missing 'hash'", $file, $i)
                    unless defined $v->{hash} && length $v->{hash};
                err("%s: vectors[%d] is missing 'pass'", $file, $i)
                    unless defined $v->{pass};

                # reads_in is a measurement and only verify-vectors.pl writes
                # it, so the only thing to check is that it names real tools.
                if (defined $v->{reads_in}) {
                    if (ref $v->{reads_in} ne 'ARRAY') {
                        err("%s: vectors[%d].reads_in must be a list", $file, $i);
                    }
                    else {
                        my %ok = map { $_ => 1 } qw(hashcat john mdxfind);
                        my %seen;
                        for my $t (@{ $v->{reads_in} }) {
                            err("%s: vectors[%d].reads_in names '%s', which is "
                              . "not a tool", $file, $i, $t) unless $ok{$t};
                            err("%s: vectors[%d].reads_in names '%s' twice",
                                $file, $i, $t) if $seen{$t}++;
                        }
                    }
                }
                err("%s: vectors[%d].credential must be a scalar", $file, $i)
                    if defined $v->{credential} && ref $v->{credential};

                # form: which serialization this string is written in.
                #
                # 'native' is the form the producing system stores or emits,
                # and it is PRIMARY over any tool's rewriting of it -- a tool
                # that reshapes a credential to suit its parser has not
                # changed what the credential is. Primacy is derived from
                # that, never asserted, so there is no 'primary' flag to get
                # out of step with this one: within a credential group the
                # native vector IS the primary one, which is why at most one
                # may be native.
                if (defined $v->{form}) {
                    if (ref $v->{form}) {
                        err("%s: vectors[%d].form must be a scalar", $file, $i);
                    }
                    elsif (!$FORM{ $v->{form} }) {
                        err("%s: vectors[%d].form is '%s'; it must be one of "
                          . "%s", $file, $i, $v->{form},
                            join(', ', sort keys %FORM));
                    }
                    else {
                        $form_n{ $v->{form} }++;
                        # A string cannot be in a tool's format and have been
                        # measured NOT to load in that tool. reads_in is only
                        # ever written by verify-vectors.pl and a non-empty
                        # list means that run read SOMETHING here, so the
                        # omission is a measurement rather than a gap.
                        if ($v->{form} ne 'native'
                            && ref $v->{reads_in} eq 'ARRAY'
                            && @{ $v->{reads_in} }
                            && !grep { $_ eq $v->{form} } @{ $v->{reads_in} }) {
                            err("%s: vectors[%d].form says '%s' but reads_in "
                              . "was measured as (%s), which does not include "
                              . "it -- a string in a tool's own format that "
                              . "the tool declined is a contradiction",
                                $file, $i, $v->{form},
                                join(' ', @{ $v->{reads_in} }));
                        }
                        # Two vectors both claiming to be john's spelling are
                        # two different strings said to be one format.
                        if ($v->{form} ne 'native' && defined $v->{credential}
                            && !ref $v->{credential}) {
                            my $k = "$v->{credential}\0$v->{form}";
                            err("%s: credential '%s' has two vectors in '%s' "
                              . "form; one credential has one spelling per "
                              . "tool", $file, $v->{credential}, $v->{form})
                                if $cred_form{$k}++;
                        }
                    }
                }

                $cred{ $v->{credential} }++ if defined $v->{credential}
                                            && !ref $v->{credential};
            }

            # At most one native form. Two would be two different claims about
            # what the producing system stores, and the derivation of primacy
            # would have no answer.
            err("%s: %d vectors carry form: native; the native form is the "
              . "primary one and an entry has at most one",
                $file, $form_n{native})
                if ($form_n{native} // 0) > 1;

            # A native form is only useful if the reader can tell what shape it
            # is. Same discipline as the credential group: the claim lives in
            # the data, the explanation has to be in the entry.
            if (($form_n{native} // 0) && ($d->{notes} // '') !~ /\S/) {
                err("%s: a vector is form: native, so notes: must say what "
                  . "that form is shaped like -- otherwise the reader is told "
                  . "a string is primary and not what makes it so", $file);
            }

            # A credential group is the statement "these are ONE credential
            # written in two tools' serializations, so they are not
            # independent evidence". Two things follow, and neither was
            # checkable while the claim lived in prose:
            #
            #   - a group of one asserts nothing and is almost always a typo
            #     in the other member's label;
            #   - a real group needs the entry to SAY how the forms differ and
            #     that the re-encoding was proven rather than assumed, which
            #     is the rule CLAUDE.md sets for the Kerberos AS-REP transcode.
            #     Seven entries carried two tool-sourced vectors with no such
            #     note on 2026-09-02, and a reader would rightly have read them
            #     as two agreeing pieces of evidence.
            for my $c (sort keys %cred) {
                if ($cred{$c} < 2) {
                    err("%s: credential '%s' is on one vector only; a group "
                      . "says two spellings are ONE credential, so a group of "
                      . "one says nothing", $file, $c);
                }
                elsif (($d->{notes} // '') !~ /\S/) {
                    err("%s: credential '%s' groups %d vectors, so they are "
                      . "not independent evidence -- notes: must say how the "
                      . "serializations differ and that the re-encoding was "
                      . "proven, not assumed", $file, $c, $cred{$c});
                }
            }

            # A mode no vector of this entry could ever exercise.
            #
            # hashcat is the only one of the three that publishes password
            # bounds, and the inventory already carries them per mode, so this
            # costs a lookup. Mode 14000 is single-DES and wants exactly 8
            # characters, so an entry whose only vector records 'password123'
            # under it cannot be round-tripped -- that is a data fault, not a
            # cracking failure, and it stays invisible precisely because
            # nothing ever runs.
            #
            # Judged per MODE and not per vector: an entry may legitimately
            # carry one vector per tool in each tool's own encoding, and a
            # plaintext that is wrong for hashcat can be right for the mdxfind
            # type beside it. What matters is whether SOME vector could
            # exercise the mode. Seeding hashcat's own example is therefore
            # how one of these warnings gets cleared.
            #
            # A WARNING, not an error. The ones this finds are inherited from
            # the source sheet rather than introduced by a contributor, and
            # failing the gate on them would block every unrelated pull
            # request until someone re-sourced a vector.
            my @plen = map  { length $_->{pass} }
                       grep { ref $_ eq 'HASH' && defined $_->{pass} }
                       @{ $d->{vectors} };
            for my $mode (@{ $d->{tools}{hashcat}{modes} || [] }) {
                my $m = $HC_MODE{$mode} or next;
                my ($lo, $hi) = ($m->{password_len_min}, $m->{password_len_max});
                next unless defined $lo && defined $hi;
                next if grep { $_ >= $lo && $_ <= $hi } @plen;
                warn_("%s: hashcat mode %d accepts a plaintext of %s, and no "
                    . "vector here has one (%s) -- the mode cannot be "
                    . "round-tripped from this entry",
                    $file, $mode,
                    ($lo == $hi ? "exactly $lo character(s)" : "$lo to $hi characters"),
                    join(', ', map { "$_" } @plen));
            }
        }
    }
}

#-----------------------------------------------------------------------
# Cross-entry relation checks.
#
# These are the rules that make expression: a gate rather than a decoration.
# Everything above validates one file at a time; a relation is by definition
# about two, and the collision rule is about the whole corpus at once.

# 0. A tombstone's destination has to exist and has to be alive. A chain
#    (a -> b where b is itself merged) is rejected rather than followed: the
#    second merge should repoint the first tombstone, so that every dead id
#    costs a consumer exactly one lookup and can never loop.
for my $t (sort keys %tomb) {
    local @ABOUT = ($t, $tomb{$t}{into});
    my $into = $tomb{$t}{into};
    if (!$seen_id{$into}) {
        err("%s: merged_into names '%s', which is not an entry",
            $tomb{$t}{file}, $into);
    }
    elsif ($tomb{$into}) {
        err("%s: merged_into names '%s', which is itself a tombstone -- "
          . "point it at %s instead", $tomb{$t}{file}, $into, $tomb{$into}{into});
    }
}

{
    my %edge;                       # "from\0to\0kind" -> 1
    $edge{"$_->{from}\0$_->{to}\0$_->{kind}"} = 1 for @rel_edges;

    # Union-find over the joining edges: equivalence is transitive, so a group
    # of four entries sharing an expression needs three edges in a star, not
    # six in a clique. Requiring the clique would make the data unreadable
    # long before it made it more correct.
    my %parent;
    my $find; $find = sub {
        my ($x) = @_;
        $parent{$x} //= $x;
        return $x if $parent{$x} eq $x;
        return $parent{$x} = $find->($parent{$x});
    };
    my $union = sub {
        my ($x, $y) = @_;
        my ($rx, $ry) = ($find->($x), $find->($y));
        $parent{$rx} = $ry unless $rx eq $ry;
    };

    for my $e (@rel_edges) {
        # A relation error is about BOTH ends: whichever of the two the
        # contributor touched, they need to see it.
        local @ABOUT = ($e->{from}, $e->{to});
        # 1. The other end has to exist.
        unless ($seen_id{ $e->{to} }) {
            err("%s: relation names '%s', which is not an entry",
                $e->{file}, $e->{to});
            next;
        }
        # 2. And it has to say so too. A one-sided edge is a fact only one of
        #    the two files tells, and whichever file a reader opens first
        #    decides whether they learn it. tools/relate.pl writes both.
        my $mirror = $REL_MIRROR{ $e->{kind} } // $e->{kind};
        unless ($edge{"$e->{to}\0$e->{from}\0$mirror"}) {
            err("%s: relation '%s' -> %s is not mirrored; %s.yaml needs "
              . "'%s' -> %s (tools/relate.pl --apply writes both sides)",
                $e->{file}, $e->{kind}, $e->{to}, $e->{to}, $mirror, $e->{from});
        }
        $union->($e->{from}, $e->{to}) if $JOINS_EXPRESSION{ $e->{kind} };
    }

    # 3. Two entries claiming the same expression are claiming to be the same
    #    computation. That is allowed -- Joomla and generic md5($p.$s) really
    #    are -- but it has to be stated, or the table has two rows and no
    #    account of why. Every entry in a colliding group must reach every
    #    other through same-computation, encodes or duplicate-of edges.
    for my $x (sort keys %by_expression) {
        my @ids = @{ $by_expression{$x} };
        next unless @ids > 1;
        local @ABOUT = @ids;
        my %group;
        push @{ $group{ $find->($_) } }, $_ for @ids;
        next if keys %group == 1;
        err("'%s' is claimed by entries that are not related to each other: "
          . "%s. Join them with same-computation, encodes or duplicate-of "
          . "(see ACTION-PLAN.md section 11)",
            $x, join(' | ', map { join(', ', sort @{ $group{$_} }) }
                            sort keys %group));
    }
}

#-----------------------------------------------------------------------
# Report.

print STDERR "- $_\n" for @warnings;

my @shown = grep { in_scope($_) } @errors;
my $elsewhere = @errors - @shown;

if (@shown) {
    print STDERR "- Error: $_->{msg}\n" for @shown;
}

unless ($quiet) {
    # Absences that were measured against a build the inventory has moved past.
    # Not an error: a stale claim is unverified, not necessarily wrong. But it
    # is the one thing a reader cannot tell from the row, and it is how 19 wrong
    # absences survived a refresh -- see the comment on %absent_build above.
    {
        my %invver = (hashcat  => $hc_doc->{version}, john     => $jn_doc->{version},
                      mdxfind  => $mx_doc->{version}, hashpipe => $hp_doc->{version});
        my @stale;
        for my $t (sort keys %absent_build) {
            my $cur = $invver{$t};
            next unless defined $cur && length $cur;
            for my $claimed (sort keys %{ $absent_build{$t} }) {
                my $n = $absent_build{$t}{$claimed};
                # An unrecorded build cannot be compared and is its own problem.
                if ($claimed eq '(unrecorded)') {
                    push @stale, [$t, $claimed, $cur, $n]; next;
                }
                # A claim is current when the build it names still appears in
                # the inventory's version string. Deliberately a substring test
                # rather than a version parse: the two strings are written by
                # different tools and only have their build token in common.
                my ($ctok) = $claimed =~ /((?:RCS\s+)?v?[0-9]+(?:\.[0-9]+)+(?:-[0-9A-Za-z.]+)?)/;
                next if defined $ctok && index($cur, $ctok) >= 0;
                push @stale, [$t, $claimed, $cur, $n];
            }
        }
        if (@stale) {
            my $total = 0; $total += $_->[3] for @stale;
            printf STDERR "\n- Stale absences: %d 'absent' claim(s) name a build the inventory has\n"
                        . "                  moved past. An absence expires when the tool gains types,\n"
                        . "                  so each is unverified rather than wrong -- re-run the\n"
                        . "                  matching discover-*.pl over the indices added since.\n",
                   $total;
            printf STDERR "                  %-8s %4d claim(s) measured against %s; inventory is %s\n",
                   $_->[0], $_->[3], $_->[1], $_->[2] for @stale;
        }
    }

    printf STDERR "\n- Inventories: hashcat %d modes (%s), john %d formats (%s), mdxfind %d types (%s)\n",
        scalar(@$hc_list), $hc_doc->{version},
        scalar(@$jn_list), $jn_doc->{version},
        scalar(@$mx_list), $mx_doc->{version};
    printf STDERR "-              hashpipe %d types (%s)%s\n",
        scalar(@$hp_list), $hp_doc->{version},
        (keys %HP_SELFTEST_FAIL)
            ? sprintf(', of which %d FAIL their own self-test: %s',
                      scalar(keys %HP_SELFTEST_FAIL),
                      join(', ', sort keys %HP_SELFTEST_FAIL))
            : '';

    printf STDERR "- Entries:     %d file(s) in %s%s\n", $entries, $algdir,
        $tombstones ? sprintf(", of which %d tombstone(s) redirecting a "
                            . "merged-away id and counted in nothing below",
                              $tombstones)
                    : '';

    if ($scoped) {
        printf STDERR "- Scope:       reporting on %d entry/entries: %s\n",
            scalar(keys %scope),
            join(', ', (sort keys %scope)[0 .. ((keys %scope) > 8 ? 7 : (keys %scope) - 1)])
              . ((keys %scope) > 8 ? sprintf(' ... (+%d)', (keys %scope) - 8) : '');
        printf STDERR "-              everything was still CHECKED; %d error(s) "
                    . "elsewhere in the corpus are not yours\n", $elsewhere
            if $elsewhere;
    }

    my $pc = sub {
        my ($n, $d) = @_;
        return $d ? sprintf('%.1f%%', 100 * $n / $d) : 'n/a';
    };

    printf STDERR "- Coverage:    hashcat %d/%d (%s)  john %d/%d (%s)  mdxfind %d/%d (%s)\n",
        scalar(keys %hit_hc), scalar(@$hc_list), $pc->(scalar(keys %hit_hc), scalar(@$hc_list)),
        scalar(keys %hit_jn), scalar(@$jn_list), $pc->(scalar(keys %hit_jn), scalar(@$jn_list)),
        scalar(keys %hit_mx), scalar(@$mx_list), $pc->(scalar(keys %hit_mx), scalar(@$mx_list));
    printf STDERR "-              hashpipe %d/%d (%s)\n",
        scalar(keys %hit_hp), scalar(@$hp_list), $pc->(scalar(keys %hit_hp), scalar(@$hp_list));

    if ($verbose) {
        printf STDERR "- Tool tiers:  %s\n",
            join('  ', map { "$_ $tier_count{$_}" }
                 grep { $tier_count{$_} } qw(vector upstream asserted absent));
        printf STDERR "- Expression:  %d of %d entries carry one (%s); "
                    . "no vector at all %d%s; denotation %d\n",
            # Live entries only: a tombstone carries no expression by rule,
            # so counting it in the denominator would report a slow decline
            # every time a merge succeeded.
            $n_expr, $entries - $tombstones,
            join(', ', map { "$_ $expr_tier{$_}" }
                 grep { $expr_tier{$_} } qw(vector upstream asserted absent)),
            $n_novec,
            (%novec_reason
             ? sprintf(' (of which %d settled: %s)',
                       eval { my $s = 0; $s += $_ for values %novec_reason; $s },
                       join(', ', map { "$_ $novec_reason{$_}" }
                            grep { $novec_reason{$_} }
                            qw(impossible withheld)))
             : ''),
            $n_denot;

        my @unmapped = sort { $a <=> $b } grep { !$hit_hc{$_} } map { $_->{mode} } @$hc_list;
        printf STDERR "-   hashcat modes with no entry: %d (first: %s)\n",
            scalar(@unmapped), join(', ', @unmapped[0 .. ($#unmapped > 9 ? 9 : $#unmapped)]);
    }

    if (%used_disabled) {
        printf STDERR "- Note:        %d john dynamic(s) named by entries are disabled in dynamic_disabled.conf\n",
            scalar(keys %used_disabled);
        printf STDERR "-              (real formats; re-enable them in that file to use them)\n";
    }

    printf STDERR "- %s\n", @shown
        ? sprintf('FAILED: %d error(s)%s', scalar @shown,
                  $scoped ? ' in scope' : '')
        : ($scoped ? 'OK: no errors in scope' : 'OK: no errors');
}

# Only in-scope errors fail the run. A contributor is not responsible for a
# defect that was in the corpus before they arrived, and telling them their
# one-line change "failed" because of one would be both wrong and hostile.
exit(@shown ? 1 : 0);
