#!/usr/bin/perl
#
# vanity.pl -- find a salt that makes an entry's test vector spell something.
#
# WHAT AND WHY
#
# A reference vector is more useful when it is recognisable. An entry whose
# digest begins 'dec0ded' announces itself in a bug report, a paste, or a
# screenshot, and costs nothing extra to carry: it is a second vector beside
# the plain one, not a replacement for it. The plain vectors stay because they
# are what the sheet, hashcat, mdxfind and john actually published, and that
# provenance is the point of them.
#
# THE SHAPE OF THE SEARCH (decided 2026-08-30; see STATE.md)
#
#   plaintext   'rosetta', never varied -- a marker is recognisable because it
#               is always the same string
#   salt        anything CONTAINING 'rosetta'; the affix is unconstrained
#   digest      starts with 'dec0ded'
#
# Salted constructions only. On an unsalted hash the only free variable is the
# plaintext, and keeping that pure matters more than the marker.
#
# WHY THIS AND NOT hashcat-pattern
#
# The hashcat-pattern fork is the general vanity engine and it works -- it
# reproduced this tool's md5($p.$s) result byte for byte. But it varies the
# PLAINTEXT and matches the digest, where this needs the plaintext pinned and
# the SALT varying, and it cannot drive a generic salt at all: outside
# descrypt/bcrypt/crypt it uses the single salt from the module's own self-test
# hash. Its numbers on the reference GPU here were 8.95 M/s against this
# script's 6.5 M/s on 16 cores, so it is not yet buying speed either.
#
# The deciding argument is provenance. A digest computed by a hashcat fork
# cannot be evidence about hashcat -- gotcha 26, same kernels. Digest::MD5 and
# Digest::SHA are independent of all three crackers, so a vector from here can
# legitimately promote hashcat, john AND mdxfind. Use --salt to record a salt
# found elsewhere; the digest is recomputed here regardless, so what gets
# stored is always this implementation's answer.
#
# THE CONSTRUCTION COMES FROM THE ENTRY
#
# Not from a table in this file. The entry's own `expression:` says what it
# computes, most of them proven by round-trip through john's dynamic compiler,
# and that string is compiled here into a closure. The vocabulary is small --
# md5, sha1, sha256, sha512, concatenation, $p and $s -- and anything outside
# it BAILS rather than guessing, the same rule derive-expressions.pl follows.
# Bailing costs an entry; guessing costs the corpus its meaning.
#
# Only constructions that reduce are worth attempting anyway. With the
# plaintext pinned, md5($p.$s) is an ordinary unsalted digest over one varying
# string, which is why 28 bits falls in under a minute. A slow KDF does not
# reduce and is not worth the electricity.
#
# DEPENDENCIES: Digest::MD5, Digest::SHA (core), YAML::XS, RosettaEmit.
#
# Generated by Claude Opus 5 on 2026-08-30

use strict;
use warnings;
use FindBin qw($RealBin);
use lib "$RealBin/lib";
use Digest::MD5 qw(md5_hex);
use Digest::SHA qw(sha1_hex sha256_hex sha512_hex);
use YAML::XS ();
use Getopt::Long qw(GetOptions);
use POSIX qw(:sys_wait_h);
use Time::HiRes qw(time);
use File::Basename qw(basename);
use RosettaEmit qw(emit_entry);
# The expression compiler moved to RosettaExpr the moment triage-expressions
# needed it too: two implementations of "what does this expression mean" is
# the drift this repository exists to prevent.
use RosettaExpr qw(compile_expression);

my $PROG = basename($0);
my $ROOT = "$RealBin/..";

sub usage {
    print <<"USAGE";
Usage: $PROG --entry ID [options]

   --entry ID       entry to give a vanity vector (repeatable)
   --all            every entry whose expression this can compile
   --salt TEXT      use this salt instead of searching for one; the digest is
                    still computed here, so a salt found on another machine
                    can be recorded without trusting that machine's arithmetic
   --pass TEXT      the plaintext, never varied      (default: rosetta)
   --marker HEX     digest prefix to reach           (default: dec0ded)
   --salt-base TEXT the salt must contain this       (default: rosetta)
   --workers N      parallel processes               (default: 16)
   --max N          give up after N salts per entry  (default: 4e9)
   --algorithms DIR curated entries  (default: data/algorithms)
   --apply          append the vector to the entry; without it, print only
   -v, --verbose    rate and timing on stderr
   -h, --help       this help

   An entry that already carries a vanity vector is skipped: it is closed.
   Tiers are never touched -- run verify-vectors.pl afterwards.

   Exit 0 success, 1 nothing found, 2 usage.
USAGE
}

my (@ids, $all, $fixed_salt, $pass, $marker, $salt_base);
my ($workers, $max, $algdir, $apply, $verbose, $help);
GetOptions(
    'entry=s'      => \@ids,
    'all'          => \$all,
    'salt=s'       => \$fixed_salt,
    'pass=s'       => \$pass,
    'marker=s'     => \$marker,
    'salt-base=s'  => \$salt_base,
    'workers=i'    => \$workers,
    'max=s'        => \$max,
    'algorithms=s' => \$algdir,
    'apply'        => \$apply,
    'v|verbose'    => \$verbose,
    'h|help'       => \$help,
) or do { usage(); exit 2 };

if ($help) { usage(); exit 0 }
unless (@ids || $all) { usage(); exit 2 }

$pass      //= 'rosetta';
$marker    //= 'dec0ded';
$salt_base //= 'rosetta';
$workers   //= 16;
$max        = defined $max ? $max + 0 : 4e9;
$algdir    //= "$ROOT/data/algorithms";

$marker =~ /^[0-9a-f]+$/ or do {
    print STDERR "$PROG: --marker must be lowercase hex -- a hex digest cannot "
               . "hold anything else, which is why the word is 'dec0ded'.\n";
    exit 2;
};
if (defined $fixed_salt && (@ids != 1 || $all)) {
    print STDERR "$PROG: --salt names one salt, so it needs exactly one --entry.\n";
    exit 2;
}
if (defined $fixed_salt && index($fixed_salt, $salt_base) < 0) {
    print STDERR "$PROG: salt '$fixed_salt' does not contain '$salt_base'.\n";
    exit 2;
}

#-----------------------------------------------------------------------
# Compile an expression into a closure, or return nothing.
#
# The grammar accepted is exactly: fn( arg ), '.' concatenation, $p, $s. It is
# parsed by recursive descent over a token list rather than by regex, because
# a regex that "mostly" parses nested calls is how a wrong construction gets
# computed and then stored as fact.

#-----------------------------------------------------------------------
# The salt affix. 36 characters, so each one buys log2(36) = 5.17 bits and six
# of them already cover the 28 bits 'dec0ded' costs. ':' and tab are excluded
# by construction: vectors are stored "hash:salt" and john runs with
# --field-separator-char=tab.

my @ALPHA = ('0'..'9', 'a'..'z');

# affix($n) - $n in base 36, least significant digit first, so consecutive
# counter values differ in their FIRST character and a sample looks varied.
sub affix {
    my ($n) = @_;
    my $s = '';
    do { $s .= $ALPHA[ $n % 36 ]; $n = int($n / 36) } while $n;
    return $s;
}

#-----------------------------------------------------------------------
# Load the entries.

opendir(my $dh, $algdir) or do { print STDERR "$PROG: cannot read $algdir: $!\n"; exit 1 };
my @files = sort grep { /\.yaml$/ } readdir $dh;
closedir $dh;

my (%entry, %path);
for my $f (@files) {
    my $p = "$algdir/$f";
    my $e = eval { YAML::XS::LoadFile($p) } or next;
    next unless $e->{id};
    $entry{ $e->{id} } = $e;
    $path{  $e->{id} } = $p;
}

if ($all) {
    @ids = grep {
        my $e = $entry{$_};
        my $x = $e->{expression};
        # A salted construction only, and one this can actually compute.
        defined $x && $x =~ /\$s/ && compile_expression($x);
    } sort keys %entry;
}

#-----------------------------------------------------------------------
# Search.

my $started   = time;
my $found_any = 0;
my $written   = 0;

for my $id (@ids) {
    my $e = $entry{$id};
    unless ($e) { print STDERR "$PROG: no entry '$id'\n"; next }

    # Closed once it has one: the marker is the same string every time, so a
    # second one adds nothing and costs another vector on every future pass
    # that requires them all to fall.
    if (grep { ($_->{source} // '') eq 'vanity' } @{ $e->{vectors} || [] }) {
        print STDERR "- $id: already has a vanity vector; closed\n" if $verbose;
        next;
    }

    my $expr = $e->{expression};
    my $fn   = compile_expression($expr);
    unless ($fn) {
        printf STDERR "- %-24s no compilable expression (%s); skipped\n",
            $id, (defined $expr && length $expr ? $expr : 'none');
        next;
    }
    unless ($expr =~ /\$s/) {
        printf STDERR "- %-24s unsalted; the plaintext is the only free "
                    . "variable and it stays pure\n", $id;
        next;
    }

    my ($hash, $salt, $tries);
    my $t0 = time;

    if (defined $fixed_salt) {
        $salt = $fixed_salt;
        $hash = $fn->($pass, $salt);
        unless (index($hash, $marker) == 0) {
            printf STDERR "- %-24s salt '%s' gives %s, which does not start "
                        . "with '%s'\n", $id, $salt, $hash, $marker;
            next;
        }
        $tries = 0;
    }
    else {
        # Workers walk disjoint residue classes, so no salt is tested twice
        # and no coordination is needed beyond the result file.
        my @kid;
        for my $w (0 .. $workers - 1) {
            my $out = "/tmp/$PROG.$$.$w";
            my $pid = fork;
            defined $pid or die "$PROG: fork failed: $!\n";
            if (!$pid) {
                for (my $n = $w; $n < $max; $n += $workers) {
                    my $s = $salt_base . affix($n);
                    my $d = $fn->($pass, $s);
                    next unless index($d, $marker) == 0;
                    open my $fh, '>', $out or exit 1;
                    print {$fh} "$d\t$s\t$n\n";
                    close $fh;
                    exit 0;
                }
                exit 1;
            }
            push @kid, [$pid, $out];
        }

        my $left = scalar @kid;
        while ($left > 0) {
            my $pid = waitpid(-1, 0);
            last if $pid <= 0;
            $left--;
            my ($k) = grep { $_->[0] == $pid } @kid;
            next unless $k && -s $k->[1];
            open my $fh, '<', $k->[1] or next;
            chomp(my $line = <$fh>);
            close $fh;
            ($hash, $salt, $tries) = split /\t/, $line;
            kill 'TERM', map { $_->[0] } grep { $_->[0] != $pid } @kid;
            last;
        }
        waitpid(-1, WNOHANG) for 1 .. $workers;
        unlink $_->[1] for @kid;
    }

    my $secs = time - $t0;
    unless (defined $hash) {
        printf STDERR "- %-24s nothing in %.0f salts (%.1fs)\n", $id, $max, $secs;
        next;
    }
    $found_any = 1;

    printf STDERR "- %-24s %s  %s tries, %.1fs%s\n", $id, $hash, ($tries || 'n/a'),
        $secs, ($tries && $secs ? sprintf(' (%.2f MH/s)', $tries/$secs/1e6) : '')
        if $verbose;

    my $vec = { hash => "$hash:$salt", pass => $pass, source => 'vanity' };

    if ($apply) {
        push @{ $e->{vectors} }, $vec;
        $written += emit_entry($path{$id}, $e);
    }
    else {
        printf "# %s  --  %s\nvectors:\n  - hash: \"%s\"\n    pass: \"%s\"\n"
             . "    source: \"vanity\"\n", $id, $expr, $vec->{hash}, $pass;
    }
}

printf STDERR "%s: %d entr%s, %d file(s) written in %.1fs\n",
    $PROG, scalar @ids, (@ids == 1 ? 'y' : 'ies'), $written, time - $started;
printf STDERR "%s: tiers untouched. Now run:\n"
            . "    ./tools/verify-vectors.pl --tool all %s\n",
    $PROG, join(' ', map { "--only $_" } @ids) if $apply && $written;

exit($found_any ? 0 : 1);
