#!/usr/bin/perl
# INDEX: decode john's $WPAPSK$ hccap ciphertext into hashcat/mdxfind's WPA*02* line.
# Project: cracking-rosetta.  Phase: backlog item 5 -- the two wpa-wpa2-pmf-pmkid-* rows.
# Task: decode john's $WPAPSK$<essid>#<base64> ciphertext into the hccap_t it encodes,
#       and re-serialize it as hashcat/mdxfind's WPA*02*... line, so that mdxfind's
#       WPA-EAPOL / WPA-PMK types and hashcat's 22000/22001 can be asked about a row
#       whose only vector is in john's serialization.
#
# Why this shape:
#   - john's encoding is NOT RFC 4648 base64.  wpapsk.h decode_hccap() walks the
#     string 4 chars -> 3 bytes using john's atoi64 table, which is the crypt(3)
#     "./0-9A-Za-z" alphabet.  Decoding with MIME::Base64 gives plausible-looking
#     garbage, which is exactly the failure mode CLAUDE.md warns about.
#   - The encoded run covers sizeof(hccap_t) - 36 bytes (356), i.e. the struct from
#     mac1 onward; the essid comes from the text before the '#'.  118 full quads plus
#     a 2-byte tail, per the loop in wpapsk.h.
#   - keyver is NOT emitted: hashcat's WPA*02* line carries the EAPOL frame, whose
#     Key Information field already states the descriptor version, so re-emitting it
#     would be a second, unverifiable claim.
#   - message_pair is NOT in hccap_t at all.  It is emitted as a caller-supplied
#     value (default 00) and the caller has to prove the line by round-trip, not
#     assume it.
#
# Dependencies: core Perl only (no Digest, no MIME::Base64 -- see above).
# Generated by Claude Opus 5 on 2026-09-07.

use strict;
use warnings;

# john's atoi64 alphabet, from src/common.c: itoa64[] = "./0123456789A-Za-z".
my $ITOA64 = './0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz';
my %ATOI64;
@ATOI64{ split //, $ITOA64 } = ( 0 .. 63 );

sub usage {
    print STDERR <<"USAGE";
usage: $0 <ciphertext> [message_pair_hex]
       $0 stdin [message_pair_hex]      read one ciphertext per line from stdin

Decodes a john \$WPAPSK\$ / \$WPAPSK\$-style ciphertext and prints, on stdout:
  a "# field" comment block, then the WPA*02*... line for hashcat -m 22000/22001
  and mdxfind -h '^WPA-EAPOL\$' / '^WPA-PMK\$'.
message_pair defaults to 00.  Progress and diagnostics go to stderr.
USAGE
    exit 2;
}

usage() unless @ARGV;
my $arg  = shift @ARGV;
my $mpair = shift(@ARGV) // '00';
die "message_pair must be two hex digits, got '$mpair'\n" unless $mpair =~ /^[0-9a-fA-F]{2}$/;

# Decode john's 4-char group into 3 bytes, exactly as decode_hccap() does.
sub john_b64_decode {
    my ($cap, $quads, $tail) = @_;   # $tail: extra bytes from a final partial group
    my @c = map { $ATOI64{$_} // die "not a john-base64 character: '$_'\n" } split //, $cap;
    my $out = '';
    for my $i ( 0 .. $quads - 1 ) {
        my ( $a, $b, $c, $d ) = @c[ 4 * $i .. 4 * $i + 3 ];
        $out .= pack 'C3', ( ( $a << 2 ) | ( $b >> 4 ) ) & 0xff,
                           ( ( $b << 4 ) | ( $c >> 2 ) ) & 0xff,
                           ( ( $c << 6 ) |   $d        ) & 0xff;
    }
    if ($tail) {                      # wpapsk.h emits exactly 2 more bytes
        my ( $a, $b, $c ) = @c[ 4 * $quads .. 4 * $quads + 2 ];
        $out .= pack 'C2', ( ( $a << 2 ) | ( $b >> 4 ) ) & 0xff,
                           ( ( $b << 4 ) | ( $c >> 2 ) ) & 0xff;
    }
    return $out;
}

sub transcode {
    my ($ct) = @_;

    # $WPAPSK$<essid>#<475 chars>.  strrchr('#') in wpapsk.h, so split on the LAST '#'
    # -- an essid may legitimately contain one.
    my $i = rindex $ct, '#';
    die "no '#' in ciphertext\n" if $i < 0;
    my $head = substr $ct, 0, $i;
    my $cap  = substr $ct, $i + 1;

    $head =~ s/^\$WPAPSK\$// or die "not a \$WPAPSK\$ ciphertext\n";
    my $essid = $head;

    # john appends a fixed trailer after the encoded struct in some builds; take
    # only what decode_hccap() reads: 118 quads + one 3-char group.
    die "encoded part is ", length($cap), " chars, need at least 475\n"
        if length($cap) < 475;
    my $blob = john_b64_decode( substr( $cap, 0, 475 ), 118, 1 );
    die "decoded ", length($blob), " bytes, expected 356\n" unless length($blob) == 356;

    # The struct from offset 36 onward: mac1[6] mac2[6] nonce1[32] nonce2[32]
    # eapol[256] eapol_size(u32 LE) keyver(u32 LE) keymic[16].
    my ( $mac1, $mac2, $nonce1, $nonce2, $eapol, $esize, $keyver, $keymic )
        = unpack 'a6 a6 a32 a32 a256 V V a16', $blob;

    die "eapol_size $esize is out of range\n" if $esize < 1 || $esize > 256;

    my $h = sub { unpack 'H*', $_[0] };
    return {
        essid      => $essid,
        essid_hex  => unpack( 'H*', $essid ),
        mac_ap     => $h->($mac1),
        mac_sta    => $h->($mac2),
        nonce_sta  => $h->($nonce1),          # hccap.h: nonce1 is snonce
        nonce_ap   => $h->($nonce2),          # hccap.h: nonce2 is anonce
        eapol      => $h->( substr $eapol, 0, $esize ),
        eapol_size => $esize,
        keyver     => $keyver,
        keymic     => $h->($keymic),
    };
}

sub emit {
    my ($ct) = @_;
    my $f = transcode($ct);
    print "# essid      $f->{essid} ($f->{essid_hex})\n";
    print "# mac_ap     $f->{mac_ap}\n";
    print "# mac_sta    $f->{mac_sta}\n";
    print "# anonce     $f->{nonce_ap}\n";
    print "# snonce     $f->{nonce_sta}\n";
    print "# keyver     $f->{keyver}\n";
    print "# keymic     $f->{keymic}\n";
    print "# eapol_size $f->{eapol_size}\n";
    printf "WPA*02*%s*%s*%s*%s*%s*%s*%s\n",
        $f->{keymic}, $f->{mac_ap}, $f->{mac_sta}, $f->{essid_hex},
        $f->{nonce_ap}, $f->{eapol}, $mpair;
}

if ( $arg eq 'stdin' ) {
    while ( my $line = <STDIN> ) {
        chomp $line;
        next unless length $line;
        emit($line);
    }
}
else {
    emit($arg);
}
